local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[439557] = {
		readable = "Nightmare Moss",
		model = 219463,
		text = {
			en = "Nightmare Moss",
			es = "Musgo de la Pesadilla",
			de = "Alptraummoos",
			fr = "Mousse des cauchemars",
			it = "[Nightmare Moss]",
			pt = "Musgo do Pesadelo",
			ru = "[Nightmare Moss]",
			ko = "악몽 이끼",
			cn = "[Nightmare Moss]",
		},
	},
	[439558] = {
		readable = "Cold Iron Deposit",
		model = 219532,
		text = {
			en = "Cold Iron Deposit",
			es = "Depósito de hierro frío",
			de = "Kalteisenvorkommen",
			fr = "Gisement de fer froid",
			it = "[Cold Iron Deposit]",
			pt = "Depósito de Ferro Frio",
			ru = "[Cold Iron Deposit]",
			ko = "[Cold Iron Deposit]",
			cn = "[Cold Iron Deposit]",
		},
	},
	[441113] = {
		readable = "Ogre Magi Text",
		model = 198021,
		text = {
			en = "Ogre Magi Text",
			es = "[Ogre Magi Text]",
			de = "Ogermagiertext",
			fr = "Texte de l’ogre magi",
			it = "[Ogre Magi Text]",
			pt = "Texto de Magus Ogro",
			ru = "[Ogre Magi Text]",
			ko = "[Ogre Magi Text]",
			cn = "[Ogre Magi Text]",
		},
	},
	[441114] = {
		readable = "Mysterious Box",
		model = 196976,
		text = {
			en = "Mysterious Box",
			es = "[Mysterious Box]",
			de = "Geheimnisvolle Kiste",
			fr = "Boîte mystérieuse",
			it = "[Mysterious Box]",
			pt = "Caixa Misteriosa",
			ru = "[Mysterious Box]",
			ko = "[Mysterious Box]",
			cn = "[Mysterious Box]",
		},
	},
	[441119] = {
		readable = "Unhatched Green Dragon Egg",
		model = 200964,
		text = {
			en = "Unhatched Green Dragon Egg",
			es = "[Unhatched Green Dragon Egg]",
			de = "Ungeschlüpftes grünes Drachenei",
			fr = "Œuf de dragon vert non-éclos",
			it = "[Unhatched Green Dragon Egg]",
			pt = "Ovo de Dragão Verde Choco",
			ru = "[Unhatched Green Dragon Egg]",
			ko = "[Unhatched Green Dragon Egg]",
			cn = "[Unhatched Green Dragon Egg]",
		},
	},
})
do ObjectDB[objectID] = objectData; end