local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[422483] = {
		readable = "The Salvagematic 9000",
		model = 201020,
		text = {
			en = "The Salvagematic 9000",
			es = "[The Salvagematic 9000]",
			de = "Der Wiederverwertungsmat 9000",
			fr = "Recycle-o-Matic 9000",
			it = "[The Salvagematic 9000]",
			pt = "[The Salvagematic 9000]",
			ru = "[The Salvagematic 9000]",
			ko = "자동 수습기 9000",
			cn = "[The Salvagematic 9000]",
		},
	},
	[424074] = {
		readable = "Quadrangulation Beacon 001",
		model = 197768,
		text = {
			en = "Quadrangulation Beacon 001",
			es = "Baliza de cuadrangulación 001",
			de = "Quadrangulationssignalgeber 001",
			fr = "Balise de quandrangulation 001",
			it = "[Quadrangulation Beacon 001]",
			pt = "Sinalizador de Quadrangulação 001",
			ru = "[Quadrangulation Beacon 001]",
			ko = "사각 측량 신호기 001",
			cn = "四边定位信标001",
		},
	},
	[424075] = {
		readable = "Quadrangulation Beacon 002",
		model = 197768,
		text = {
			en = "Quadrangulation Beacon 002",
			es = "Baliza de cuadrangulación 002",
			de = "Quadrangulationssignalgeber 002",
			fr = "Balise de quandrangulation 002",
			it = "[Quadrangulation Beacon 002]",
			pt = "[Quadrangulation Beacon 002]",
			ru = "Квадрангуляционный маяк 002",
			ko = "사각 측량 신호기 002",
			cn = "四边定位信标002",
		},
	},
	[424076] = {
		readable = "Quadrangulation Beacon 003",
		model = 197768,
		text = {
			en = "Quadrangulation Beacon 003",
			es = "[Quadrangulation Beacon 003]",
			de = "[Quadrangulation Beacon 003]",
			fr = "[Quadrangulation Beacon 003]",
			it = "[Quadrangulation Beacon 003]",
			pt = "[Quadrangulation Beacon 003]",
			ru = "[Quadrangulation Beacon 003]",
			ko = "[Quadrangulation Beacon 003]",
			cn = "四边定位信标003",
		},
	},
	[424077] = {
		readable = "Quadrangulation Beacon 004",
		model = 197768,
		text = {
			en = "Quadrangulation Beacon 004",
			es = "[Quadrangulation Beacon 004]",
			de = "[Quadrangulation Beacon 004]",
			fr = "[Quadrangulation Beacon 004]",
			it = "[Quadrangulation Beacon 004]",
			pt = "[Quadrangulation Beacon 004]",
			ru = "[Quadrangulation Beacon 004]",
			ko = "사각 측량 신호기 004",
			cn = "四边定位信标004",
		},
	},
})
do ObjectDB[objectID] = objectData; end