local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[406918] = {
		readable = "Messenger Bag",
		text = {
			en = "Messenger Bag",
			es = "Bolsa de mensajero",
			de = "Kuriertasche",
			fr = "Sac de messager",
			it = "[Messenger Bag]",
			pt = "Bolsa de Mensageiro",
			ru = "Сумка посланника",
			ko = "배낭",
			cn = "信使行囊",
		},
	},
	[415106] = {
		readable = "Burned-Out Remains",
		model = 197145,
		text = {
			en = "Burned-Out Remains",
			es = "Restos carbonizados",
			de = "Ausgebrannte Überreste",
			fr = "Restes brûlés",
			it = "[Burned-Out Remains]",
			pt = "Restos Queimados",
			ru = "Прогоревшие останки",
			ko = "불타버린 잔해",
			cn = "焦焚残骸",
		},
	},
	[415107] = {
		readable = "Burned-Out Remains",
		model = 197145,
		text = {
			en = "Burned-Out Remains",
			es = "Restos carbonizados",
			de = "Ausgebrannte Überreste",
			fr = "Restes brûlés",
			it = "[Burned-Out Remains]",
			pt = "Restos Queimados",
			ru = "Прогоревшие останки",
			ko = "불타버린 잔해",
			cn = "焦焚残骸",
		},
	},
	[417072] = {
		readable = "Nailed Plank",
		model = 200454,
		text = {
			en = "Nailed Plank",
			es = "Tablón claveteado",
			de = "Festgenagelte Planke",
			fr = "Planche à clous",
			it = "[Nailed Plank]",
			pt = "Tábua com Pregos",
			ru = "Доска с гвоздями",
			ko = "못으로 고정한 판자",
			cn = "镶钉木板",
		},
	},
	[424005] = {
		readable = "Pocket Litter",
		model = 197641,
		text = {
			en = "Pocket Litter",
			es = "Basura de bolsillo",
			de = "Taschenmüll",
			fr = "Litière de poche",
			it = "[Pocket Litter]",
			pt = "Lixo de Bolso",
			ru = "Карманный мусор",
			ko = "휴대용 쓰레기통",
			cn = "垃圾袋",
		},
	},
	[424006] = {
		readable = "Hastily Rolled-Up Satchel",
		model = 203429,
		text = {
			en = "Hastily Rolled-Up Satchel",
			es = "Cartera enrollada a toda prisa",
			de = "Hastig eingerollter Beutel",
			fr = "Besace roulée à la hâte",
			it = "[Hastily Rolled-Up Satchel]",
			pt = "Algibeira Enrolada às Pressas",
			ru = "Наскоро завернутая сумка",
			ko = "황급히 만 주머니",
			cn = "草草收起的包裹",
		},
	},
	[424007] = {
		readable = "Carved Figurine",
		model = 200296,
		text = {
			en = "Carved Figurine",
			es = "Figurilla tallada",
			de = "Geschnitzte Figure",
			fr = "Figurine sculptée",
			it = "[Carved Figurine]",
			pt = "Estatueta Entalhada",
			ru = "Вырезанная статуэтка",
			ko = "조각상",
			cn = "雕刻塑像",
		},
	},
	[424010] = {
		readable = "Nailed Plank",
		model = 200454,
		text = {
			en = "Nailed Plank",
			es = "Tablón claveteado",
			de = "Planke mit Nagel",
			fr = "Planche clouée",
			it = "[Nailed Plank]",
			pt = "Tábua com Pregos",
			ru = "Доска с гвоздями",
			ko = "못으로 고정한 판자",
			cn = "镶钉木板",
		},
	},
	[424012] = {
		readable = "Mound of Dirt",
		model = 189528,
		text = {
			en = "Mound of Dirt",
			es = "Túmulo de barro",
			de = "Erdhaufen",
			fr = "Monticule de terre",
			it = "[Mound of Dirt]",
			pt = "Monturo de Terra",
			ru = "Куча грязи",
			ko = "흙무더기",
			cn = "一堆泥土",
		},
	},
})
do ObjectDB[objectID] = objectData; end