local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[28024] = {
		readable = "Caravan Chest",
		model = 196976,
		text = {
			en = "Caravan Chest",
			es = "Cofre de la caravana",
			de = "Karawanentruhe",
			fr = "Coffre de la caravane",
			it = "Caravan Chest",
			pt = "Baú da Caravana",
			ru = "Сундук из каравана",
			ko = "짐마차 상자",
			cn = "车队箱子",
		},
	},
	[30854] = {
		readable = "Atal'ai Artifact",
		model = 190341,
		text = {
			en = "Atal'ai Artifact",
			es = "Artefacto Atal'ai",
			de = "Artefakt der Atal'ai",
			fr = "Artéfact atal'ai",
			it = "Atal'ai Artifact",
			pt = "Artefato Atal'ai",
			ru = "Артефакт Атал'ай",
			ko = "아탈라이 유물",
			cn = "阿塔莱神器",
		},
	},
	[30855] = {
		readable = "Atal'ai Artifact",
		model = 190358,
		text = {
			en = "Atal'ai Artifact",
			es = "Artefacto Atal'ai",
			de = "Artefakt der Atal'ai",
			fr = "Artéfact atal'ai",
			it = "Atal'ai Artifact",
			pt = "Artefato Atal'ai",
			ru = "Артефакт Атал'ай",
			ko = "아탈라이 유물",
			cn = "阿塔莱神器",
		},
	},
	[30856] = {
		readable = "Atal'ai Artifact",
		model = 190354,
		text = {
			en = "Atal'ai Artifact",
			es = "Artefacto Atal'ai",
			de = "Artefakt der Atal'ai",
			fr = "Artéfact atal'ai",
			it = "Atal'ai Artifact",
			pt = "Artefato Atal'ai",
			ru = "Артефакт Атал'ай",
			ko = "아탈라이 유물",
			cn = "阿塔莱神器",
		},
	},
	[35252] = {
		readable = "Ancient Relic",
		model = 199748,
		text = {
			en = "Ancient Relic",
			es = "Reliquia antigua",
			de = "Uraltes Relikt",
			fr = "Relique ancienne",
			it = "Ancient Relic",
			pt = "Relíquia Antiga",
			ru = "Древняя святыня",
			ko = "고대 유물",
			cn = "古代遗物",
		},
	},
	[36738] = {
		readable = "The Book of Ur",
		model = 198017,
		text = {
			en = "The Book of Ur",
			es = "El libro de Ur",
			de = "Das Buch von Ur",
			fr = "Le Livre d'Ur",
			it = "The Book of Ur",
			pt = "O Livro de Ur",
			ru = "Книга Ура",
			ko = "우르의 책",
			cn = "乌尔之书",
		},
	},
	[50935] = {
		readable = "Sack of Corn",
		model = 190015,
		text = {
			en = "Sack of Corn",
			es = "Saco de maíz",
			de = "Sack Korn",
			fr = "Sac de maïs",
			it = "Sack of Corn",
			pt = "Saco de Milho",
			ru = "Мешок кукурузы",
			ko = "옥수수 부대",
			cn = "一袋玉米",
		},
	},
	[50936] = {
		readable = "Sack of Barley",
		model = 197608,
		text = {
			en = "Sack of Barley",
			es = "Saco de cebada",
			de = "Sack Gerste",
			fr = "Sac d'orge",
			it = "Sack of Barley",
			pt = "Saco de Cevada",
			ru = "Мешок ячменя",
			ko = "보리 부대",
			cn = "一袋大麦",
		},
	},
	[50937] = {
		readable = "Sack of Rye",
		model = 190015,
		text = {
			en = "Sack of Rye",
			es = "Saco de centeno",
			de = "Sack Roggen",
			fr = "Sac de seigle",
			it = "Sack of Rye",
			pt = "Saco de Centeio",
			ru = "Мешок ржи",
			ko = "호밀 부대",
			cn = "一袋黑麦",
		},
	},
	[50982] = {
		readable = "The Charred Oak",
		model = 189260,
		text = {
			en = "The Charred Oak",
			es = "El roble carbonizado",
			de = "Die verbrannte Eiche",
			fr = "Le chêne carbonisé",
			it = "The Charred Oak",
			pt = "O Carvalho Calcinado",
			ru = "Опаленный дуб",
			ko = "참나무 숯",
			cn = "烧焦的橡木",
		},
	},
	[58595] = {
		readable = "Burning Blade Stash",
		model = 196976,
		text = {
			en = "Burning Blade Stash",
			es = "Alijo del Filo Ardiente",
			de = "Geheimlager der Brennenden Klinge",
			fr = "Planque de la Lame ardente",
			it = "Burning Blade Stash",
			pt = "Tesouro da Lâmina Ardente",
			ru = "Тайник клана Пылающего Клинка",
			ko = "불타는 칼날단 은신처",
			cn = "火刃营地",
		},
	},
	[68865] = {
		readable = "Snufflenose Command Sticks",
		model = 202821,
		text = {
			en = "Snufflenose Command Sticks",
			es = "Varas de mando de husmeador",
			de = "Schnüffelnasenleitstecken",
			fr = "Bâtons de commandement de Sniffetarin",
			it = "Snufflenose Command Sticks",
			pt = "Bastões de Comando do Fungafuça",
			ru = "Палочка-погонялочка для шмыгуносов",
			ko = "땅다람쥐 지휘봉",
			cn = "地鼠指挥棒",
		},
	},
	[85563] = {
		readable = "Dead-tooth's Strongbox",
		model = 197617,
		text = {
			en = "Dead-tooth's Strongbox",
			es = "Caja fuerte de Dentomuerto",
			de = "Stumpfzahns Geldkassette",
			fr = "Coffre de Dent-Morte",
			it = "Dead-tooth's Strongbox",
			pt = "Caixa-forte do Dente-podre",
			ru = "Сейф Мертвозуба",
			ko = "썩은니의 금고",
			cn = "蛀牙杰克的箱子",
		},
	},
	[86492] = {
		readable = "Crate of Elunite",
		model = 200960,
		text = {
			en = "Crate of Elunite",
			es = "Cajón de Elunite",
			de = "Kiste mit Elunit",
			fr = "Caisse d'élunite",
			it = "Crate of Elunite",
			pt = "Cratera de Elunita",
			ru = "Ящик с элунитом",
			ko = "엘루니트 상자",
			cn = "月神矿石",
		},
	},
	[89635] = {
		readable = "Sunscorched Shell",
		model = 202738,
		text = {
			en = "Sunscorched Shell",
			es = "Cáscara asolada",
			de = "Sonnenverbrannte Schale",
			fr = "Coquille brûlée par le soleil",
			it = "Sunscorched Shell",
			pt = "Casca Queimada de Sol",
			ru = "Высохшая на солнце скорлупа",
			ko = "바짝 마른 알껍질",
			cn = "晒焦的蛋壳",
		},
	},
	[92420] = {
		readable = "Bailor's Ore",
		model = 198168,
		text = {
			en = "Bailor's Ore",
			es = "Mena de Bailor",
			de = "Bailors Erz",
			fr = "Minerai de Bailor",
			it = "Bailor's Ore",
			pt = "Minério do Bailor",
			ru = "Руда Бэйлора",
			ko = "베일러의 광석",
			cn = "白洛尔的矿石",
		},
	},
	[93192] = {
		readable = "Heartswood",
		model = 203691,
		text = {
			en = "Heartswood",
			es = "Duramen",
			de = "Herzholz",
			fr = "Cœur du bois",
			it = "Heartswood",
			pt = "Palocórdio",
			ru = "Сердцедрево",
			ko = "사랑나무",
			cn = "同心树",
		},
	},
	[102985] = {
		readable = "Balnir Snapdragons",
		model = 203732,
		text = {
			en = "Balnir Snapdragons",
			es = "Bocas de dragón de Balnir",
			de = "Balnirlöwenmäulchen",
			fr = "Gueules-de-loup de Balnir",
			it = "Balnir Snapdragons",
			pt = "Boca-de-leão de Balnir",
			ru = "Львиный зев Бальнира",
			ko = "발니르 금어초",
			cn = "巴尼尔金鱼草",
		},
	},
	[103574] = {
		readable = "Filled Containment Coffer",
		model = 201015,
		text = {
			en = "Filled Containment Coffer",
			es = "Arca de contención llena",
			de = "Gefüllte Verwahrungskästen",
			fr = "Coffre de stockage rempli",
			it = "Filled Containment Coffer",
			pt = "Cofre de Contenção Cheio",
			ru = "Заполненная шкатулка-духоловка",
			ko = "채워진 속박의 상자",
			cn = "装满的封灵箱",
		},
	},
	[103628] = {
		readable = "Ur's Treatise on Shadow Magic",
		model = 198022,
		text = {
			en = "Ur's Treatise on Shadow Magic",
			es = "Tratado de Ur sobre la magia de las Sombras",
			de = "Urs Abhandlung über Schattenmagie",
			fr = "Traité d'Ur sur la Magie des Ombres",
			it = "Ur's Treatise on Shadow Magic",
			pt = "Tratado de Ur sobre Umbromancia",
			ru = "Трактат Ура по темной магии",
			ko = "우르의 흑마법 논문",
			cn = "乌尔的暗影魔法研究论文",
		},
	},
	[104564] = {
		readable = "Bingles's Toolbucket",
		model = 197640,
		text = {
			en = "Bingles's Toolbucket",
			es = "Cubo de herramientas de Bingles",
			de = "Bingles' Werkzeugeimer",
			fr = "Seau d'outils de Bingles",
			it = "Bingles's Toolbucket",
			pt = "Balde de Ferramentas do Bingles",
			ru = "Ведро с инструментами Бинглза",
			ko = "빙글스의 공구통",
			cn = "宾格斯的工具箱",
		},
	},
	[104569] = {
		readable = "Bingles's Toolbucket",
		model = 197641,
		text = {
			en = "Bingles's Toolbucket",
			es = "Cubo de herramientas de Bingles",
			de = "Bingles' Werkzeugeimer",
			fr = "Seau d'outils de Bingles",
			it = "Bingles's Toolbucket",
			pt = "Balde de Ferramentas do Bingles",
			ru = "Ведро с инструментами Бинглза",
			ko = "빙글스의 공구통",
			cn = "宾格斯的工具箱",
		},
	},
	[104574] = {
		readable = "Bingles's Toolbucket",
		model = 197642,
		text = {
			en = "Bingles's Toolbucket",
			es = "Cubo de herramientas de Bingles",
			de = "Bingles' Werkzeugeimer",
			fr = "Seau d'outils de Bingles",
			it = "Bingles's Toolbucket",
			pt = "Balde de Ferramentas do Bingles",
			ru = "Ведро с инструментами Бинглза",
			ko = "빙글스의 공구통",
			cn = "宾格斯的工具箱",
		},
	},
	[104575] = {
		readable = "Bingles's Blastencapper",
		model = 197464,
		text = {
			en = "Bingles's Blastencapper",
			es = "Cartucho de Bingles",
			de = "Bingles' Superspreng",
			fr = "Capsuleur soufflant de Bingles",
			it = "Bingles's Blastencapper",
			pt = "Detona-cuca do Gomez",
			ru = "Сорвиголовка Бинглза",
			ko = "빙글스의 깡그리싸그리 폭탄",
			cn = "宾格斯的气压炸弹",
		},
	},
	[105169] = {
		readable = "Agamand Weapon Rack",
		model = 198636,
		text = {
			en = "Agamand Weapon Rack",
			es = "Portaarmas de Agamand",
			de = "Agamands Waffenregal",
			fr = "Râtelier d'armes Agamand",
			it = "Agamand Weapon Rack",
			pt = "Cavalete de Armas dos Agamand",
			ru = "Оружейная стойка Агамонда",
			ko = "아가만드 무기 선반",
			cn = "[Agamand Weapon Rack]",
		},
	},
	[105170] = {
		readable = "Agamand Weapon Rack",
		model = 198636,
		text = {
			en = "Agamand Weapon Rack",
			es = "Portaarmas de Agamand",
			de = "Agamands Waffenregal",
			fr = "Râtelier d'armes Agamand",
			it = "Agamand Weapon Rack",
			pt = "Cavalete de Armas dos Agamand",
			ru = "Оружейная стойка Агамонда",
			ko = "아가만드 무기 선반",
			cn = "[Agamand Weapon Rack]",
		},
	},
	[105171] = {
		readable = "Agamand Weapon Rack",
		model = 198636,
		text = {
			en = "Agamand Weapon Rack",
			es = "Portaarmas de Agamand",
			de = "Agamands Waffenregal",
			fr = "Râtelier d'armes Agamand",
			it = "Agamand Weapon Rack",
			pt = "Cavalete de Armas dos Agamand",
			ru = "Оружейная стойка Агамонда",
			ko = "아가만드 무기 선반",
			cn = "[Agamand Weapon Rack]",
		},
	},
	[105172] = {
		readable = "Agamand Weapon Rack",
		model = 198636,
		text = {
			en = "Agamand Weapon Rack",
			es = "Portaarmas de Agamand",
			de = "Agamands Waffenregal",
			fr = "Râtelier d'armes Agamand",
			it = "Agamand Weapon Rack",
			pt = "Cavalete de Armas dos Agamand",
			ru = "Оружейная стойка Агамонда",
			ko = "아가만드 무기 선반",
			cn = "[Agamand Weapon Rack]",
		},
	},
	[105174] = {
		readable = "Chest of Containment Coffers",
		model = 196979,
		text = {
			en = "Chest of Containment Coffers",
			es = "Cofre de arcas de contención",
			de = "Truhe mit Verwahrungskästen",
			fr = "Caisse de coffres de stockage",
			it = "Chest of Containment Coffers",
			pt = "Baú de Cofres de Contenção",
			ru = "Ящик со шкатулками-духоловками",
			ko = "속박의 상자",
			cn = "封灵箱",
		},
	},
	[105175] = {
		readable = "Cantation of Manifestation",
		model = 198453,
		text = {
			en = "Cantation of Manifestation",
			es = "Canto de manifestación",
			de = "Inkantation der Manifestation",
			fr = "Chants de manifestation",
			it = "Cantation of Manifestation",
			pt = "Cantochão da Manifestação",
			ru = "Свиток заклятия проявления",
			ko = "현신의 주문서",
			cn = "显形卷轴",
		},
	},
	[375544] = {
		readable = "Wooden Figurine",
		model = 201094,
		text = {
			en = "Wooden Figurine",
			es = "Figurilla de madera",
			de = "Holzstatuette",
			fr = "Figurine en bois",
			it = "Wooden Figurine",
			pt = "Estatueta de Madeira",
			ru = "Деревянная статуэтка",
			ko = "목재 조각상",
			cn = "[Wooden Figurine]",
		},
	},
})
do ObjectDB[objectID] = objectData; end