local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[457098] = {
		readable = "Finding Your Inner Feline: A Guide to Modern Druidism",
		model = 198028,
		text = {
			en = "Finding Your Inner Feline: A Guide to Modern Druidism",
			es = "[Finding Your Inner Feline: A Guide to Modern Druidism]",
			de = "Die innere Katze finden: Ein Leitfaden für moderne Druidenkünste",
			fr = "Trouver votre félin intérieur : guide du druidisme moderne",
			it = "[Finding Your Inner Feline: A Guide to Modern Druidism]",
			pt = "[Finding Your Inner Feline: A Guide to Modern Druidism]",
			ru = "Душа кошки: руководство по современному друидизму",
			ko = "내면의 표범을 찾아서: 현대 드루이드학 안내서",
			cn = "《心若灵豹：当代德鲁伊指南》",
		},
	},
	[457099] = {
		readable = "Zirene's Guide to Getting Punched",
		model = 198028,
		text = {
			en = "Zirene's Guide to Getting Punched",
			es = "[Zirene's Guide to Getting Punched]",
			de = "Zirenes Leitfaden für den Schlagabtausch",
			fr = "Guide de l’encaissement des beignes, par Zirène",
			it = "[Zirene's Guide to Getting Punched]",
			pt = "Guia de Zerene para Levar Socos",
			ru = "Руководство Зайрина по выдерживанию тумаков",
			ko = "지렌의 맞는 법 강의",
			cn = "《吉勒内扛揍指南》",
		},
	},
	[457100] = {
		readable = "Renzik's Thoughts on \"Fair\" Fighting",
		model = 198028,
		text = {
			en = "Renzik's Thoughts on \"Fair\" Fighting",
			es = "[Renzik's Thoughts on \"Fair\" Fighting]",
			de = "Renziks Gedanken zu \"fairem\" Kämpfen",
			fr = "Réflexions de Renzik sur les combats « à la loyale »",
			it = "[Renzik's Thoughts on \"Fair\" Fighting]",
			pt = "Comentários de Renzik sobre a Luta \"Justa\"",
			ru = "Мысли Рензика о \"справедливых\" поединках",
			ko = "\"공정한\" 싸움에 대한 렌지크의 단상",
			cn = "《雷吉克的“公平”对决总结》",
		},
	},
	[457101] = {
		readable = "The Rites of Mak'Gora",
		model = 198028,
		text = {
			en = "The Rites of Mak'Gora",
			es = "[The Rites of Mak'Gora]",
			de = "Die Riten von Mak'Gora",
			fr = "Les rites de Mak’Gora",
			it = "[The Rites of Mak'Gora]",
			pt = "Os Ritos do Mak'Gora",
			ru = "[The Rites of Mak'Gora]",
			ko = "막고라 의례",
			cn = "《荣耀决斗仪式》",
		},
	},
	[457102] = {
		readable = "Elements for Dummies Volume III: Arcane",
		model = 198028,
		text = {
			en = "Elements for Dummies Volume III: Arcane",
			es = "[Elements for Dummies Volume III: Arcane]",
			de = "Elemente für Dummies Band I: Arkan",
			fr = "Les éléments pour les Nuls, vol. 3 : Arcanes",
			it = "[Elements for Dummies Volume III: Arcane]",
			pt = "Elementos Para Leigos Volume III: Arcano",
			ru = "[Elements for Dummies Volume III: Arcane]",
			ko = "왕초보도 이해하는 원소 마법 제3권: 비전",
			cn = "《元素奥义傻瓜入门第III卷：奥术》",
		},
	},
})
do ObjectDB[objectID] = objectData; end