local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[457088] = {
		readable = "Advanced Swordplay",
		model = 198028,
		text = {
			en = "Advanced Swordplay",
			es = "[Advanced Swordplay]",
			de = "Fortgeschrittener Schwertkampf",
			fr = "Maniement avancé de l’épée",
			it = "[Advanced Swordplay]",
			pt = "Esgrima Avançada",
			ru = "[Advanced Swordplay]",
			ko = "고급 검술",
			cn = "《进阶剑法》",
		},
	},
	[457089] = {
		readable = "The Shadow Connection",
		model = 198028,
		text = {
			en = "The Shadow Connection",
			es = "[The Shadow Connection]",
			de = "Die Schattenverbindung",
			fr = "Le lien de l’ombre",
			it = "[The Shadow Connection]",
			pt = "[The Shadow Connection]",
			ru = "[The Shadow Connection]",
			ko = "어둠의 유대",
			cn = "《暗影的联系》",
		},
	},
	[457090] = {
		readable = "Famous (and Infamous) Rangers of Azeroth",
		model = 198028,
		text = {
			en = "Famous (and Infamous) Rangers of Azeroth",
			es = "[Famous (and Infamous) Rangers of Azeroth]",
			de = "Berühmte (und berüchtigte) Waldläufer von Azeroth",
			fr = "Forestiers célèbres (et funestes) d’Azeroth",
			it = "[Famous (and Infamous) Rangers of Azeroth]",
			pt = "Famosos (e Infames) Patrulheiros de Azeroth",
			ru = "Прославленные (и бесславные) следопыты Азерота",
			ko = "아제로스의 유명한(혹은 악명 높은) 순찰자",
			cn = "《艾泽拉斯著名（与恶名）游侠列传》",
		},
	},
	[457092] = {
		readable = "The Fury of Stormrage",
		model = 198028,
		text = {
			en = "The Fury of Stormrage",
			es = "[The Fury of Stormrage]",
			de = "Der Furor von Sturmgrimm",
			fr = "La fureur de Hurlorage",
			it = "[The Fury of Stormrage]",
			pt = "A Fúria de Tempesfúria",
			ru = "Гнев Ярости Бури",
			ko = "스톰레이지의 격노",
			cn = "[The Fury of Stormrage]",
		},
	},
	[457093] = {
		readable = "Blunt Justice: A Dwarf's Tale",
		model = 198028,
		text = {
			en = "Blunt Justice: A Dwarf's Tale",
			es = "[Blunt Justice: A Dwarf's Tale]",
			de = "Schonungslose Gerechtigkeit: Die Geschichte eines Zwerges",
			fr = "Justice expéditive : l’histoire d’un Nain",
			it = "[Blunt Justice: A Dwarf's Tale]",
			pt = "[Blunt Justice: A Dwarf's Tale]",
			ru = "Ударное правосудие: история одного дворфа",
			ko = "무딘 정의: 드워프 이야기",
			cn = "《正义钝击：矮人传奇》",
		},
	},
})
do ObjectDB[objectID] = objectData; end