local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[206638] = {
		readable = "Refrigeration Pipe",
		model = 197736,
		text = {
			en = "Refrigeration Pipe",
			es = "Conducto de refrigeración",
			de = "Kühlleitung",
			fr = "Conduit de réfrigération",
			it = "Condotto di Refrigerazione",
			pt = "Cano de Refrigeração",
			ru = "Холодильная труба",
			ko = "냉각 수송관",
			cn = "冷凝管",
		},
	},
	[206639] = {
		readable = "Refrigeration Pipe",
		model = 197737,
		text = {
			en = "Refrigeration Pipe",
			es = "Conducto de refrigeración",
			de = "Kühlleitung",
			fr = "Conduit de réfrigération",
			it = "Condotto di Refrigerazione",
			pt = "Cano de Refrigeração",
			ru = "Холодильная труба",
			ko = "냉각 수송관",
			cn = "冷凝管",
		},
	},
	[206640] = {
		readable = "Refrigeration Pipe",
		model = 197738,
		text = {
			en = "Refrigeration Pipe",
			es = "Conducto de refrigeración",
			de = "Kühlleitung",
			fr = "Conduit de réfrigération",
			it = "Condotto di Refrigerazione",
			pt = "Cano de Refrigeração",
			ru = "Холодильная труба",
			ko = "냉각 수송관",
			cn = "冷凝管",
		},
	},
	[206641] = {
		readable = "Refrigeration Pipe",
		model = 197739,
		text = {
			en = "Refrigeration Pipe",
			es = "Conducto de refrigeración",
			de = "Kühlleitung",
			fr = "Conduit de réfrigération",
			it = "Condotto di Refrigerazione",
			pt = "Cano de Refrigeração",
			ru = "Холодильная труба",
			ko = "냉각 수송관",
			cn = "冷凝管",
		},
	},
})
do ObjectDB[objectID] = objectData; end