local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[104564] = {
		readable = "Bingles's Toolbucket",
		model = 197640,
		text = {
			en = "Bingles's Toolbucket",
			es = "Cubo de herramientas de Bingles",
			de = "Bingles’ Werkzeugeimer",
			fr = "Seau d'outils de Bingles",
			it = "Bingles's Toolbucket",
			pt = "Balde de Ferramentas do Bingles",
			ru = "Ведро с инструментами Бинглза",
			ko = "빙글스의 공구통",
			cn = "宾格斯的工具箱",
		},
	},
	[104569] = {
		readable = "Bingles's Toolbucket",
		model = 197641,
		text = {
			en = "Bingles's Toolbucket",
			es = "Cubo de herramientas de Bingles",
			de = "Bingles’ Werkzeugeimer",
			fr = "Seau d'outils de Bingles",
			it = "Bingles's Toolbucket",
			pt = "Balde de Ferramentas do Bingles",
			ru = "Ведро с инструментами Бинглза",
			ko = "빙글스의 공구통",
			cn = "宾格斯的工具箱",
		},
	},
	[104574] = {
		readable = "Bingles's Toolbucket",
		model = 197642,
		text = {
			en = "Bingles's Toolbucket",
			es = "Cubo de herramientas de Bingles",
			de = "Bingles’ Werkzeugeimer",
			fr = "Seau d'outils de Bingles",
			it = "Bingles's Toolbucket",
			pt = "Balde de Ferramentas do Bingles",
			ru = "Ведро с инструментами Бинглза",
			ko = "빙글스의 공구통",
			cn = "宾格斯的工具箱",
		},
	},
	[104575] = {
		readable = "Bingles's Blastencapper",
		model = 197464,
		text = {
			en = "Bingles's Blastencapper",
			es = "Cartucho de Bingles",
			de = "Bingles Superspreng",
			fr = "Capsuleur soufflant de Bingles",
			it = "Bingles's Blastencapper",
			pt = "Detona-cuca do Gomez",
			ru = "Сорвиголовка Бинглза",
			ko = "빙글스의 깡그리싸그리 폭탄",
			cn = "宾格斯的气压炸弹",
		},
	},
	[402215] = {
		readable = "Charred Note",
		text = {
			en = "Charred Note",
			es = "Nota chamuscada",
			de = "Verkohlte Notiz",
			fr = "Note calcinée",
			it = "[Charred Note]",
			pt = "[Charred Note]",
			ru = "Обгоревшая записка",
			ko = "까맣게 탄 기록",
			cn = "[Charred Note]",
		},
	},
	[407850] = {
		readable = "Sunken Reliquary",
		model = 200953,
		text = {
			en = "Sunken Reliquary",
			es = "Relicario sumergido",
			de = "Versunkener Reliquienschrein",
			fr = "Reliquaire englouti",
			it = "[Sunken Reliquary]",
			pt = "[Sunken Reliquary]",
			ru = "[Sunken Reliquary]",
			ko = "[Sunken Reliquary]",
			cn = "[Sunken Reliquary]",
		},
	},
	[409315] = {
		readable = "Shattered Orb",
		text = {
			en = "Shattered Orb",
			es = "[Shattered Orb]",
			de = "Zerschmetterte Kugel",
			fr = "Orbe fracassé",
			it = "[Shattered Orb]",
			pt = "[Shattered Orb]",
			ru = "Разбитая сфера",
			ko = "[Shattered Orb]",
			cn = "[Shattered Orb]",
		},
	},
	[409754] = {
		readable = "Wall-Mounted Shield",
		text = {
			en = "Wall-Mounted Shield",
			es = "Escudo montado en la pared",
			de = "Aufgehängter Schild",
			fr = "Bouclier mural",
			it = "[Wall-Mounted Shield]",
			pt = "[Wall-Mounted Shield]",
			ru = "[Wall-Mounted Shield]",
			ko = "[Wall-Mounted Shield]",
			cn = "[Wall-Mounted Shield]",
		},
	},
	[409758] = {
		readable = "Discarded Helm",
		text = {
			en = "Discarded Helm",
			es = "Yelmo desechado",
			de = "Weggeworfener Helm",
			fr = "Heaume abandonné",
			it = "[Discarded Helm]",
			pt = "[Discarded Helm]",
			ru = "Выброшенный шлем",
			ko = "버려진 투구",
			cn = "[Discarded Helm]",
		},
	},
	[411710] = {
		readable = "Demonic Reliquary",
		model = 196976,
		text = {
			en = "Demonic Reliquary",
			es = "[Demonic Reliquary]",
			de = "Dämonisches Reliquiar",
			fr = "[Demonic Reliquary]",
			it = "[Demonic Reliquary]",
			pt = "[Demonic Reliquary]",
			ru = "[Demonic Reliquary]",
			ko = "[Demonic Reliquary]",
			cn = "[Demonic Reliquary]",
		},
	},
	[412224] = {
		readable = "Dark Ritual Stone",
		model = 201097,
		text = {
			en = "Dark Ritual Stone",
			es = "[Dark Ritual Stone]",
			de = "Dunkler Ritualstein",
			fr = "Pierre de rituel des ténèbres",
			it = "[Dark Ritual Stone]",
			pt = "[Dark Ritual Stone]",
			ru = "[Dark Ritual Stone]",
			ko = "암흑 의식용 돌",
			cn = "[Dark Ritual Stone]",
		},
	},
	[414658] = {
		readable = "Rubble",
		model = 189478,
		text = {
			en = "Rubble",
			es = "[Rubble]",
			de = "Geröll",
			fr = "Débris",
			it = "[Rubble]",
			pt = "[Rubble]",
			ru = "[Rubble]",
			ko = "[Rubble]",
			cn = "[Rubble]",
		},
	},
	[414713] = {
		readable = "Storage Locker",
		model = 196976,
		text = {
			en = "Storage Locker",
			es = "[Storage Locker]",
			de = "[Storage Locker]",
			fr = "Vestiaire",
			it = "[Storage Locker]",
			pt = "[Storage Locker]",
			ru = "[Storage Locker]",
			ko = "[Storage Locker]",
			cn = "[Storage Locker]",
		},
	},
})
do ObjectDB[objectID] = objectData; end