local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[439627] = {
		readable = "Dreamroot",
		model = 219469,
		text = {
			en = "Dreamroot",
			es = "Raíz del Sueño",
			de = "Traumwurzel",
			fr = "Oniracine",
			it = "[Dreamroot]",
			pt = "Raiz-de-sonho",
			ru = "Сон-корень",
			ko = "꿈뿌리",
			cn = "梦之根",
		},
	},
	[439628] = {
		readable = "Fool's Gold Vein",
		model = 219524,
		text = {
			en = "Fool's Gold Vein",
			es = "Filón de oro falso",
			de = "Katzengoldvorkommen",
			fr = "Filon de pyrite",
			it = "[Fool's Gold Vein]",
			pt = "Veio de Ouro de Tolo",
			ru = "Жила ложного золота",
			ko = "바보의 금 광맥",
			cn = "愚人金矿脉",
		},
	},
	[441124] = {
		readable = "Dream-Touched Dragon Egg",
		model = 200964,
		text = {
			en = "Dream-Touched Dragon Egg",
			es = "Huevo de dragón tocado por el Sueño",
			de = "Traumberührtes Drachenei",
			fr = "Œuf de dragon touché par le Rêve",
			it = "[Dream-Touched Dragon Egg]",
			pt = "Ovo de Dragão Tocado pelo Sonho",
			ru = "Усиленное Сном яйцо дракона",
			ko = "꿈에 물든 용의 알",
			cn = "梦触龙蛋",
		},
	},
	[441128] = {
		readable = "Vibrating Crate",
		model = 197150,
		text = {
			en = "Vibrating Crate",
			es = "Cajón vibrante",
			de = "Vibrierende Kiste",
			fr = "Caisse vibrante",
			it = "[Vibrating Crate]",
			pt = "Caixote Vibratório",
			ru = "Вибрирующий ящик",
			ko = "진동하는 상자",
			cn = "震动的箱子",
		},
	},
	[441129] = {
		readable = "Azsharan Prophecy",
		model = 198454,
		text = {
			en = "Azsharan Prophecy",
			es = "Profecía de Azshara",
			de = "Azsharische Prophezeiung",
			fr = "Prophétie d’Azshara",
			it = "[Azsharan Prophecy]",
			pt = "Profecia Azshariana",
			ru = "Азшарское пророчество",
			ko = "아즈샤라의 예언",
			cn = "[Azsharan Prophecy]",
		},
	},
})
do ObjectDB[objectID] = objectData; end