local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[439810] = {
		readable = "Moonroot",
		model = 219486,
		text = {
			en = "Moonroot",
			es = "Raíz lunar",
			de = "Mondwurzel",
			fr = "Racine lunaire",
			it = "[Moonroot]",
			pt = "Raiz-da-lua",
			ru = "[Moonroot]",
			ko = "달뿌리",
			cn = "[Moonroot]",
		},
	},
	[439815] = {
		readable = "Greater Moonstone Formation",
		model = 190809,
		text = {
			en = "Greater Moonstone Formation",
			es = "Formación de piedra lunar superior",
			de = "Große Mondsteinformation",
			fr = "Formation de pierre de lune supérieure",
			it = "[Greater Moonstone Formation]",
			pt = "Formação de Pedras-da-lua Maiores",
			ru = "[Greater Moonstone Formation]",
			ko = "상급 월장석 형성물",
			cn = "[Greater Moonstone Formation]",
		},
	},
	[441310] = {
		readable = "Moonglow Dragon Egg",
		model = 200964,
		text = {
			en = "Moonglow Dragon Egg",
			es = "Huevo de dragón de resplandor lunar",
			de = "Mondscheindrachenei",
			fr = "Œuf de dragon lueur-de-lune",
			it = "[Moonglow Dragon Egg]",
			pt = "Ovo de Dragão do Brilho da Lua",
			ru = "[Moonglow Dragon Egg]",
			ko = "달빛너울 용의 알",
			cn = "[Moonglow Dragon Egg]",
		},
	},
	[441312] = {
		readable = "Mad Keeper's Notes",
		model = 198036,
		text = {
			en = "Mad Keeper's Notes",
			es = "Notas del vigilante demente",
			de = "Notizen des wahnsinnigen Bewahrers",
			fr = "Notes du gardien fou",
			it = "[Mad Keeper's Notes]",
			pt = "Anotações do Guardião Louco",
			ru = "[Mad Keeper's Notes]",
			ko = "광기 어린 수호자의 기록",
			cn = "[Mad Keeper's Notes]",
		},
	},
	[441314] = {
		readable = "Harpy Screed",
		model = 201113,
		text = {
			en = "Harpy Screed",
			es = "Desvaríos de arpía",
			de = "Harpyienschrift",
			fr = "Diatribe de harpie",
			it = "[Harpy Screed]",
			pt = "Escrito das Harpias",
			ru = "[Harpy Screed]",
			ko = "하피의 장광설",
			cn = "[Harpy Screed]",
		},
	},
})
do ObjectDB[objectID] = objectData; end