local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[92013] = {
		readable = "Tome of the Cabal",
		model = 203385,
		text = {
			en = "Tome of the Cabal",
			es = "Libro del Conciliábulo",
			de = "Foliant der Kabale",
			fr = "Tome de la Cabale",
			it = "Tome of the Cabal",
			pt = "Tomo do Conluio",
			ru = "Фолиант Заговора",
			ko = "비밀의 고서",
			cn = "阴谋之书",
		},
	},
	[92423] = {
		readable = "Damaged Chest",
		model = 196979,
		text = {
			en = "Damaged Chest",
			es = "Cofre dañado",
			de = "Beschädigte Truhe",
			fr = "Coffre endommagé",
			it = "Damaged Chest",
			pt = "Baú Danificado",
			ru = "Поврежденный сундук",
			ko = "부서진 궤짝",
			cn = "破损的箱子",
		},
	},
	[386675] = {
		readable = "Buried Treasure",
		model = 196988,
		text = {
			en = "Buried Treasure",
			es = "Tesoro enterrado",
			de = "Vergrabener Schatz",
			fr = "Trésor enfoui",
			it = "[Buried Treasure]",
			pt = "[Buried Treasure]",
			ru = "Зарытое сокровище",
			ko = "파묻힌 보물",
			cn = "[Buried Treasure]",
		},
	},
	[386691] = {
		readable = "Library Book",
		model = 198017,
		text = {
			en = "Library Book",
			es = "Libro de la biblioteca",
			de = "Bibliotheksbuch",
			fr = "Livre de la bibliothèque",
			it = "[Library Book]",
			pt = "[Library Book]",
			ru = "Книга из библиотеки",
			ko = "도서관 책",
			cn = "图书馆书籍",
		},
	},
	[386759] = {
		readable = "Library Book",
		model = 198036,
		text = {
			en = "Library Book",
			es = "Libro de la biblioteca",
			de = "Bibliotheksbuch",
			fr = "Livre de la bibliothèque",
			it = "[Library Book]",
			pt = "Livro da Biblioteca",
			ru = "Книга из библиотеки",
			ko = "도서관 책",
			cn = "图书馆书籍",
		},
	},
	[386777] = {
		readable = "Dusty Chest",
		model = 219372,
		text = {
			en = "Dusty Chest",
			es = "Cofre cubierto de polvo",
			de = "Verstaubte Kiste",
			fr = "Coffre poussiéreux",
			it = "[Dusty Chest]",
			pt = "Baú Empoeirado",
			ru = "Пыльный сундук",
			ko = "먼지투성이 상자",
			cn = "尘封的宝箱",
		},
	},
	[387466] = {
		readable = "Rusty Lockbox",
		model = 196976,
		text = {
			en = "Rusty Lockbox",
			es = "Arcón oxidado",
			de = "Rostige Schließkassette",
			fr = "Coffret poussiéreux",
			it = "[Rusty Lockbox]",
			pt = "Cofre Enferrujado",
			ru = "Ржавый сейф",
			ko = "녹슨 금고",
			cn = "生锈的宝箱",
		},
	},
	[387477] = {
		readable = "Defias Stashbox",
		model = 196976,
		text = {
			en = "Defias Stashbox",
			es = "Caja secreta de los Defias",
			de = "Lagertruhe der Defias",
			fr = "Boîte de rangement des Défias",
			it = "[Defias Stashbox]",
			pt = "Estoque dos Défias",
			ru = "Тайник Братства Справедливости",
			ko = "데피아즈단 은닉함",
			cn = "迪菲亚储藏箱",
		},
	},
	[392029] = {
		readable = "Swordsman's Reward",
		model = 196988,
		text = {
			en = "Swordsman's Reward",
			es = "Recompensa del espadachín",
			de = "Belohnung des Schwertkämpfers",
			fr = "Récompense de l’épéiste",
			it = "[Swordsman's Reward]",
			pt = "Recompensa do Espadachim",
			ru = "Награда мечника",
			ko = "[Swordsman's Reward]",
			cn = "[Swordsman's Reward]",
		},
	},
	[397987] = {
		readable = "Kobold Stashbox",
		model = 196982,
		text = {
			en = "Kobold Stashbox",
			es = "Caja secreta kóbold",
			de = "Lagertruhe der Kobolde",
			fr = "Boîte de rangement de Kobold",
			it = "[Kobold Stashbox]",
			pt = "Estoque dos Kobolds",
			ru = "Тайник кобольдов",
			ko = "[Kobold Stashbox]",
			cn = "狗头人的贮藏",
		},
	},
	[402215] = {
		readable = "Charred Note",
		text = {
			en = "Charred Note",
			es = "Nota chamuscada",
			de = "Verkohlte Notiz",
			fr = "Note calcinée",
			it = "[Charred Note]",
			pt = "[Charred Note]",
			ru = "Обгоревшая записка",
			ko = "까맣게 탄 기록",
			cn = "[Charred Note]",
		},
	},
	[403041] = {
		readable = "Blasting Supplies",
		model = 200898,
		text = {
			en = "Blasting Supplies",
			es = "Suministros explosivos",
			de = "Sprengvorräte",
			fr = "Fournitures pour dynamitage",
			it = "[Blasting Supplies]",
			pt = "[Blasting Supplies]",
			ru = "Припасы для взрывов",
			ko = "발파용 보급품",
			cn = "[Blasting Supplies]",
		},
	},
	[403102] = {
		readable = "Bristleback Loot Cache",
		model = 196987,
		text = {
			en = "Bristleback Loot Cache",
			es = "Alijo de botín Erizapúas",
			de = "Beutelager der Borstennacken",
			fr = "Cache à butin dos-hirsute",
			it = "[Bristleback Loot Cache]",
			pt = "[Bristleback Loot Cache]",
			ru = "Склад добычи Дыбогривов",
			ko = "뾰족털일족 전리품 보관함",
			cn = "[Bristleback Loot Cache]",
		},
	},
	[403105] = {
		readable = "Windfury Cone",
		model = 202297,
		text = {
			en = "Windfury Cone",
			es = "Bellota Viento Furioso",
			de = "Windzornzapfen",
			fr = "Cône de Furie-des-vents",
			it = "[Windfury Cone]",
			pt = "[Windfury Cone]",
			ru = "Шишка неистовства ветра",
			ko = "질풍의 솔방울",
			cn = "[Windfury Cone]",
		},
	},
	[403718] = {
		readable = "Prairie Flower",
		model = 219436,
		text = {
			en = "Prairie Flower",
			es = "Flor de la pradera",
			de = "Prärieblume",
			fr = "Fleur de prairie",
			it = "[Prairie Flower]",
			pt = "[Prairie Flower]",
			ru = "Луговой цветок",
			ko = "초원꽃",
			cn = "[Prairie Flower]",
		},
	},
	[404352] = {
		readable = "Artifact Storage",
		model = 196988,
		text = {
			en = "Artifact Storage",
			es = "Depósito del artefacto",
			de = "Artefaktlagertruhe",
			fr = "Entrepôt de l’Artéfact",
			it = "[Artifact Storage]",
			pt = "[Artifact Storage]",
			ru = "Хранилище артефактов",
			ko = "유물 보관함",
			cn = "[Artifact Storage]",
		},
	},
	[404433] = {
		readable = "Lunar Chest",
		model = 219372,
		text = {
			en = "Lunar Chest",
			es = "Cofre lunar",
			de = "Mondtruhe",
			fr = "Coffre lunaire",
			it = "[Lunar Chest]",
			pt = "Baú Lunar",
			ru = "Лунный сундук",
			ko = "[Lunar Chest]",
			cn = "[Lunar Chest]",
		},
	},
	[404695] = {
		readable = "Waterlogged Stashbox",
		model = 196987,
		text = {
			en = "Waterlogged Stashbox",
			es = "Caja secreta empapada",
			de = "Durchnässte Lagertruhe",
			fr = "Boîte de rangement détrempée",
			it = "[Waterlogged Stashbox]",
			pt = "Estoque Encharcado",
			ru = "Отсыревший тайник",
			ko = "흠뻑 젖은 은닉함",
			cn = "[Waterlogged Stashbox]",
		},
	},
	[404830] = {
		readable = "Dusty Chest",
		model = 196988,
		text = {
			en = "Dusty Chest",
			es = "[Dusty Chest]",
			de = "Verstaubte Kiste",
			fr = "Coffre poussiéreux",
			it = "[Dusty Chest]",
			pt = "[Dusty Chest]",
			ru = "[Dusty Chest]",
			ko = "[Dusty Chest]",
			cn = "[Dusty Chest]",
		},
	},
	[404911] = {
		readable = "Hidden Cache",
		model = 196989,
		text = {
			en = "Hidden Cache",
			es = "Alijo oculto",
			de = "Versteckte Truhe",
			fr = "Cache dissimulée",
			it = "[Hidden Cache]",
			pt = "Baú Escondido",
			ru = "Тайник",
			ko = "숨겨진 보관함",
			cn = "隐秘的宝箱",
		},
	},
	[404941] = {
		readable = "Relic Coffer",
		model = 196988,
		text = {
			en = "Relic Coffer",
			es = "Arca de reliquias",
			de = "Reliktkasten",
			fr = "Coffret à relique",
			it = "[Relic Coffer]",
			pt = "[Relic Coffer]",
			ru = "Реликварий",
			ko = "유물 금고",
			cn = "[Relic Coffer]",
		},
	},
	[405149] = {
		readable = "Mural of Ta'zo",
		text = {
			en = "Mural of Ta'zo",
			es = "Mural de Ta'zo",
			de = "Wandgemälde von Ta'zo",
			fr = "Fresque de Ta’zo",
			it = "[Mural of Ta'zo]",
			pt = "Mural de Ta'zo",
			ru = "Фреска с Та'зо",
			ko = "타조의 벽화",
			cn = "塔佐的浮雕",
		},
	},
	[405201] = {
		readable = "Shipwreck Cache",
		model = 196989,
		text = {
			en = "Shipwreck Cache",
			es = "[Shipwreck Cache]",
			de = "Schiffswracktruhe",
			fr = "Cache de l’épave",
			it = "[Shipwreck Cache]",
			pt = "[Shipwreck Cache]",
			ru = "[Shipwreck Cache]",
			ko = "[Shipwreck Cache]",
			cn = "[Shipwreck Cache]",
		},
	},
	[405628] = {
		readable = "Frostmane Loot Cache",
		model = 196987,
		text = {
			en = "Frostmane Loot Cache",
			es = "Alijo de botín Peloescarcha",
			de = "Beutelager der Frostmane",
			fr = "Cache à butin crins-de-givre",
			it = "[Frostmane Loot Cache]",
			pt = "Baú de Saque Jubafria",
			ru = "Склад добычи Мерзлогривов",
			ko = "서리갈기 전리품 보관함",
			cn = "[Frostmane Loot Cache]",
		},
	},
	[405633] = {
		readable = "Rockjaw Footlocker",
		model = 196976,
		text = {
			en = "Rockjaw Footlocker",
			es = "Baúl Comepiedras",
			de = "Schließkiste der Felsenkiefer",
			fr = "Cantine mâcheroc",
			it = "[Rockjaw Footlocker]",
			pt = "Maleta Pedraqueixo",
			ru = "Сундучок племени Каменной Челюсти",
			ko = "바위턱 사물함",
			cn = "[Rockjaw Footlocker]",
		},
	},
	[405879] = {
		readable = "Apothecary Society Primer",
		model = 198025,
		text = {
			en = "Apothecary Society Primer",
			es = "Manual de la Sociedad de Boticarios",
			de = "Fibel der Apothekervereinigung",
			fr = "Manuel de la Société des apothicaires",
			it = "[Apothecary Society Primer]",
			pt = "Cartilha da Sociedade dos Boticários",
			ru = "Ученик фармацевтического общества",
			ko = "왕실 연금술 학회 지침서",
			cn = "药剂师的会社读本",
		},
	},
	[405946] = {
		readable = "Dusty Chest",
		model = 196988,
		text = {
			en = "Dusty Chest",
			es = "[Dusty Chest]",
			de = "Verstaubte Kiste",
			fr = "Coffre poussiéreux",
			it = "[Dusty Chest]",
			pt = "[Dusty Chest]",
			ru = "[Dusty Chest]",
			ko = "먼지투성이 상자",
			cn = "[Dusty Chest]",
		},
	},
	[406006] = {
		readable = "Idol",
		text = {
			en = "Idol",
			es = "Ídolo",
			de = "Götze",
			fr = "Idole",
			it = "[Idol]",
			pt = "Ídolo",
			ru = "Идол",
			ko = "우상",
			cn = "神像",
		},
	},
	[406736] = {
		readable = "Lost Stash",
		model = 196987,
		text = {
			en = "Lost Stash",
			es = "Alijo perdido",
			de = "Verlorene Kiste",
			fr = "Planque perdue",
			it = "[Lost Stash]",
			pt = "Estoque Perdido",
			ru = "Забытый тайник",
			ko = "잃어버린 은닉처",
			cn = "[Lost Stash]",
		},
	},
	[406918] = {
		readable = "Messenger Bag",
		text = {
			en = "Messenger Bag",
			es = "Bolsa de mensajero",
			de = "Kuriertasche",
			fr = "Sac de messager",
			it = "[Messenger Bag]",
			pt = "Bolsa de Mensageiro",
			ru = "Сумка посланника",
			ko = "배낭",
			cn = "信使行囊",
		},
	},
	[407117] = {
		readable = "Abandoned Snapjaw Nest",
		text = {
			en = "Abandoned Snapjaw Nest",
			es = "Nido de quijaforte abandonado",
			de = "Verlassenes Schnappkiefernest",
			fr = "Nid de gueule d’acier abandonné",
			it = "[Abandoned Snapjaw Nest]",
			pt = "[Abandoned Snapjaw Nest]",
			ru = "Заброшенное гнездо хрустогрыза",
			ko = "버려진 무쇠턱 둥지",
			cn = "[Abandoned Snapjaw Nest]",
		},
	},
	[407120] = {
		readable = "Empty Snapjaw Nest",
		text = {
			en = "Empty Snapjaw Nest",
			es = "Nido de quijaforte vacío",
			de = "Leeres Schnappkiefernest",
			fr = "Nid de gueule d’acier vide",
			it = "[Empty Snapjaw Nest]",
			pt = "Ninho de Mordelisca Vazio",
			ru = "Пустое гнездо хрустогрыза",
			ko = "텅 빈 무쇠턱 둥지",
			cn = "空荡荡的钳嘴龟的巢",
		},
	},
	[407247] = {
		readable = "Glade Flower",
		model = 219436,
		text = {
			en = "Glade Flower",
			es = "Flor del claro",
			de = "Lichtungsblume",
			fr = "Fleur de la clairière",
			it = "[Glade Flower]",
			pt = "Flor da Clareira",
			ru = "Цветок с поляны",
			ko = "공터꽃",
			cn = "林地花",
		},
	},
	[407289] = {
		readable = "Horde Warbanner",
		model = 200276,
		text = {
			en = "Horde Warbanner",
			es = "Estandarte de guerra de la Horda",
			de = "Kriegsbanner der Horde",
			fr = "Bannière de guerre de la Horde",
			it = "[Horde Warbanner]",
			pt = "Estandarte de Guerra da Horda",
			ru = "Боевой штандарт Орды",
			ko = "호드 전쟁 깃발",
			cn = "部落战旗",
		},
	},
	[407291] = {
		readable = "Alliance Warbanner",
		model = 200268,
		text = {
			en = "Alliance Warbanner",
			es = "Estandarte de guerra de la Alianza",
			de = "Kriegsbanner der Allianz",
			fr = "Bannière de guerre de l’Alliance",
			it = "[Alliance Warbanner]",
			pt = "[Alliance Warbanner]",
			ru = "[Alliance Warbanner]",
			ko = "[Alliance Warbanner]",
			cn = "[Alliance Warbanner]",
		},
	},
	[407312] = {
		readable = "Hungry Idol",
		text = {
			en = "Hungry Idol",
			es = "Ídolo hambriento",
			de = "Hungriger Götze",
			fr = "Idole affamée",
			it = "[Hungry Idol]",
			pt = "Ídolo Faminto",
			ru = "Голодный идол",
			ko = "굶주린 우상",
			cn = "饥饿神像",
		},
	},
	[407347] = {
		readable = "Altar of Thorns",
		model = 199989,
		text = {
			en = "Altar of Thorns",
			es = "Altar de espinas",
			de = "Altar der Dornen",
			fr = "Autel des épines",
			it = "[Altar of Thorns]",
			pt = "[Altar of Thorns]",
			ru = "Алтарь шипов",
			ko = "가시의 제단",
			cn = "荆棘祭坛",
		},
	},
	[407352] = {
		readable = "Gnarlpine Stash",
		model = 197063,
		text = {
			en = "Gnarlpine Stash",
			es = "[Gnarlpine Stash]",
			de = "Kiste der Knarzklauen",
			fr = "[Gnarlpine Stash]",
			it = "[Gnarlpine Stash]",
			pt = "[Gnarlpine Stash]",
			ru = "Тайник племени Кривой Сосны",
			ko = "[Gnarlpine Stash]",
			cn = "[Gnarlpine Stash]",
		},
	},
	[407453] = {
		readable = "Southsea Loot Stash",
		model = 196979,
		text = {
			en = "Southsea Loot Stash",
			es = "[Southsea Loot Stash]",
			de = "Südmeerbeutelager",
			fr = "Planque à butin des mers du Sud",
			it = "[Southsea Loot Stash]",
			pt = "[Southsea Loot Stash]",
			ru = "Тайник с добычей братства Южных Морей",
			ko = "[Southsea Loot Stash]",
			cn = "[Southsea Loot Stash]",
		},
	},
	[407454] = {
		readable = "Gunpowder Keg",
		model = 197463,
		text = {
			en = "Gunpowder Keg",
			es = "Barril de pólvora",
			de = "Schießpulverfass",
			fr = "Baril de poudre à canon",
			it = "[Gunpowder Keg]",
			pt = "[Gunpowder Keg]",
			ru = "Бочонок с порохом",
			ko = "화약통",
			cn = "火药桶",
		},
	},
	[407457] = {
		readable = "Stable Hand's Trunk",
		model = 196982,
		text = {
			en = "Stable Hand's Trunk",
			es = "Baúl del mozo de establo",
			de = "Stallburschenkoffer",
			fr = "Malle de palefrenier",
			it = "[Stable Hand's Trunk]",
			pt = "[Stable Hand's Trunk]",
			ru = "Сундучок смотрителя стойл",
			ko = "마구간지기의 사물함",
			cn = "马夫的箱子",
		},
	},
	[407505] = {
		readable = "Etched Carving",
		model = 199989,
		text = {
			en = "Etched Carving",
			es = "Talla grabada",
			de = "Geätzte Schnitzerei",
			fr = "Sculpture gravée",
			it = "[Etched Carving]",
			pt = "Entalhe Cinzelado",
			ru = "Резьба",
			ko = "새겨진 조각품",
			cn = "铭刻雕像",
		},
	},
	[407510] = {
		readable = "Etched Carving",
		model = 199989,
		text = {
			en = "Etched Carving",
			es = "Talla grabada",
			de = "Geätzte Schnitzerei",
			fr = "Sculpture gravée",
			it = "[Etched Carving]",
			pt = "Entalhe Cinzelado",
			ru = "Резьба",
			ko = "새겨진 조각품",
			cn = "铭刻雕像",
		},
	},
	[407566] = {
		readable = "Goblin Tome",
		text = {
			en = "Goblin Tome",
			es = "Tomo goblin",
			de = "Goblinfoliant",
			fr = "Tome gobelin",
			it = "[Goblin Tome]",
			pt = "Tomo Goblínico",
			ru = "Гоблинская книга",
			ko = "고블린어 고서",
			cn = "地精魔典",
		},
	},
	[407731] = {
		readable = "Stonemason's Toolbox",
		model = 197621,
		text = {
			en = "Stonemason's Toolbox",
			es = "Caja de herramientas de albañil",
			de = "Werkzeugkasten des Steinmetzes",
			fr = "Boîte à outils de maçon",
			it = "[Stonemason's Toolbox]",
			pt = "Caixa de Ferramentas do Alvanel",
			ru = "Ящик с инструментами каменщика",
			ko = "석공의 연장통",
			cn = "石匠的工具箱",
		},
	},
	[407734] = {
		readable = "Gnarlpine Cache",
		model = 196989,
		text = {
			en = "Gnarlpine Cache",
			es = "Alijo Tuercepinos",
			de = "Knarzklauenkiste",
			fr = "Cache pin-tordu",
			it = "[Gnarlpine Cache]",
			pt = "Baú Masca-pinho",
			ru = "Тайник Кривой Сосны",
			ko = "나무옹이 보관함",
			cn = "[Gnarlpine Cache]",
		},
	},
	[407850] = {
		readable = "Sunken Reliquary",
		model = 200953,
		text = {
			en = "Sunken Reliquary",
			es = "Relicario sumergido",
			de = "Versunkener Reliquienschrein",
			fr = "Reliquaire englouti",
			it = "[Sunken Reliquary]",
			pt = "[Sunken Reliquary]",
			ru = "Утонувший реликварий",
			ko = "물에 잠긴 성물함",
			cn = "[Sunken Reliquary]",
		},
	},
	[407918] = {
		readable = "Empty Trophy Display",
		text = {
			en = "Empty Trophy Display",
			es = "Expositor de trofeos vacío",
			de = "Leerer Trophäenkasten",
			fr = "Présentoir à trophées vide",
			it = "[Empty Trophy Display]",
			pt = "[Empty Trophy Display]",
			ru = "Пустая витрина для трофеев",
			ko = "[Empty Trophy Display]",
			cn = "[Empty Trophy Display]",
		},
	},
	[407983] = {
		readable = "Pile of Stolen Books",
		model = 198056,
		text = {
			en = "Pile of Stolen Books",
			es = "Pila de libros robados",
			de = "Haufen gestohlener Bücher",
			fr = "Pile de livres dérobés",
			it = "[Pile of Stolen Books]",
			pt = "Pilha de Livros Roubados",
			ru = "Куча украденных книг",
			ko = "훔친 책 더미",
			cn = "一堆遭窃的书",
		},
	},
	[408004] = {
		readable = "Tangled Blight Pile",
		model = 201087,
		text = {
			en = "Tangled Blight Pile",
			es = "[Tangled Blight Pile]",
			de = "Umschlungener Verseuchungsstapel",
			fr = "Pile de chancre enchevêtré",
			it = "[Tangled Blight Pile]",
			pt = "[Tangled Blight Pile]",
			ru = "Перемешанная куча гнили",
			ko = "뒤얽힌 역병 더미",
			cn = "[Tangled Blight Pile]",
		},
	},
	[408014] = {
		readable = "Gnomish Tome",
		text = {
			en = "Gnomish Tome",
			es = "Tomo gnómico",
			de = "Gnomenfoliant",
			fr = "Tome gnome",
			it = "[Gnomish Tome]",
			pt = "Tomo Gnômico",
			ru = "Гномья книга",
			ko = "노움어 고서",
			cn = "侏儒魔典",
		},
	},
	[408718] = {
		readable = "Equipment Stash",
		model = 196982,
		text = {
			en = "Equipment Stash",
			es = "Alijo de equipo",
			de = "Ausrüstungslager",
			fr = "Réserve d’équipement",
			it = "[Equipment Stash]",
			pt = "Estoque de Equipamentos",
			ru = "Тайник со снаряжением",
			ko = "장비 은닉처",
			cn = "装备贮藏",
		},
	},
	[408799] = {
		readable = "Idol of the Deep",
		model = 201452,
		text = {
			en = "Idol of the Deep",
			es = "Ídolo de las profundidades",
			de = "Götze der Tiefe",
			fr = "Idole des profondeurs",
			it = "[Idol of the Deep]",
			pt = "[Idol of the Deep]",
			ru = "Идол Глубин",
			ko = "[Idol of the Deep]",
			cn = "深渊神像",
		},
	},
	[408802] = {
		readable = "Gnarled Harpoon",
		model = 189097,
		text = {
			en = "Gnarled Harpoon",
			es = "Arpón nudoso",
			de = "Knorrige Harpune",
			fr = "Harpon noueux",
			it = "[Gnarled Harpoon]",
			pt = "Arpão Nodoso",
			ru = "Корявый гарпун",
			ko = "옹이진 작살",
			cn = "多节鱼叉",
		},
	},
	[409131] = {
		readable = "Rusty Chest",
		model = 196988,
		text = {
			en = "Rusty Chest",
			es = "[Rusty Chest]",
			de = "[Rusty Chest]",
			fr = "[Rusty Chest]",
			it = "[Rusty Chest]",
			pt = "[Rusty Chest]",
			ru = "[Rusty Chest]",
			ko = "[Rusty Chest]",
			cn = "[Rusty Chest]",
		},
	},
	[409289] = {
		readable = "Strange Orb",
		model = 201095,
		text = {
			en = "Strange Orb",
			es = "Orbe extraño",
			de = "Seltsame Kugel",
			fr = "Orbe étrange",
			it = "[Strange Orb]",
			pt = "Orbe Estranho",
			ru = "Странная сфера",
			ko = "기이한 보주",
			cn = "[Strange Orb]",
		},
	},
	[409311] = {
		readable = "Spear of Mannoroth",
		model = 201649,
		text = {
			en = "Spear of Mannoroth",
			es = "[Spear of Mannoroth]",
			de = "Speer von Mannoroth",
			fr = "Lance de Mannoroth",
			it = "[Spear of Mannoroth]",
			pt = "[Spear of Mannoroth]",
			ru = "Копье Маннорота",
			ko = "[Spear of Mannoroth]",
			cn = "[Spear of Mannoroth]",
		},
	},
	[409315] = {
		readable = "Shattered Orb",
		text = {
			en = "Shattered Orb",
			es = "[Shattered Orb]",
			de = "Zerschmetterte Kugel",
			fr = "Orbe fracassé",
			it = "[Shattered Orb]",
			pt = "[Shattered Orb]",
			ru = "Разбитая сфера",
			ko = "[Shattered Orb]",
			cn = "[Shattered Orb]",
		},
	},
	[409496] = {
		readable = "Scrolls",
		model = 198453,
		text = {
			en = "Scrolls",
			es = "Pergaminos",
			de = "Schriftrollen",
			fr = "Parchemins",
			it = "[Scrolls]",
			pt = "[Scrolls]",
			ru = "Свитки",
			ko = "두루마리",
			cn = "[Scrolls]",
		},
	},
	[409501] = {
		readable = "Dalaran Digest",
		model = 198036,
		text = {
			en = "Dalaran Digest",
			es = "Compendio de Dalaran",
			de = "Dalaranauswahl",
			fr = "Abrégé de Dalaran",
			it = "[Dalaran Digest]",
			pt = "[Dalaran Digest]",
			ru = "Даларанский справочник",
			ko = "[Dalaran Digest]",
			cn = "[Dalaran Digest]",
		},
	},
	[409562] = {
		readable = "Spellbook",
		text = {
			en = "Spellbook",
			es = "Libro de hechizos",
			de = "Zauberbuch",
			fr = "Grimoire",
			it = "[Spellbook]",
			pt = "Grimório",
			ru = "Книга заклинаний",
			ko = "마법책",
			cn = "法术书",
		},
	},
	[409692] = {
		readable = "Scrolls",
		model = 198453,
		text = {
			en = "Scrolls",
			es = "Pergaminos",
			de = "Schriftrollen",
			fr = "Parchemins",
			it = "[Scrolls]",
			pt = "Pergaminhos",
			ru = "Свитки",
			ko = "두루마리",
			cn = "卷轴",
		},
	},
	[409700] = {
		readable = "Manual",
		text = {
			en = "Manual",
			es = "Manual",
			de = "Handbuch",
			fr = "Manuel",
			it = "[Manual]",
			pt = "Manual",
			ru = "Руководство",
			ko = "안내서",
			cn = "手册",
		},
	},
	[409711] = {
		readable = "Scrolls",
		model = 198452,
		text = {
			en = "Scrolls",
			es = "Pergaminos",
			de = "Schriftrollen",
			fr = "Parchemins",
			it = "[Scrolls]",
			pt = "Pergaminhos",
			ru = "Свитки",
			ko = "두루마리",
			cn = "[Scrolls]",
		},
	},
	[409717] = {
		readable = "Scrolls",
		model = 198453,
		text = {
			en = "Scrolls",
			es = "Pergaminos",
			de = "Schriftrollen",
			fr = "Parchemins",
			it = "[Scrolls]",
			pt = "Pergaminhos",
			ru = "Свитки",
			ko = "두루마리",
			cn = "[Scrolls]",
		},
	},
	[409731] = {
		readable = "Scrolls",
		model = 198453,
		text = {
			en = "Scrolls",
			es = "[Scrolls]",
			de = "Schriftrollen",
			fr = "Parchemins",
			it = "[Scrolls]",
			pt = "[Scrolls]",
			ru = "Свитки",
			ko = "두루마리",
			cn = "[Scrolls]",
		},
	},
	[409735] = {
		readable = "Spellbook",
		text = {
			en = "Spellbook",
			es = "Libro de hechizos",
			de = "Zauberbuch",
			fr = "Grimoire",
			it = "[Spellbook]",
			pt = "[Spellbook]",
			ru = "Книга заклинаний",
			ko = "마법책",
			cn = "[Spellbook]",
		},
	},
	[409754] = {
		readable = "Wall-Mounted Shield",
		text = {
			en = "Wall-Mounted Shield",
			es = "Escudo montado en la pared",
			de = "Aufgehängter Schild",
			fr = "Bouclier mural",
			it = "[Wall-Mounted Shield]",
			pt = "[Wall-Mounted Shield]",
			ru = "[Wall-Mounted Shield]",
			ko = "벽걸이 방패",
			cn = "[Wall-Mounted Shield]",
		},
	},
	[409758] = {
		readable = "Discarded Helm",
		text = {
			en = "Discarded Helm",
			es = "Yelmo desechado",
			de = "Weggeworfener Helm",
			fr = "Heaume abandonné",
			it = "[Discarded Helm]",
			pt = "[Discarded Helm]",
			ru = "Выброшенный шлем",
			ko = "버려진 투구",
			cn = "[Discarded Helm]",
		},
	},
	[409942] = {
		readable = "Twin Owl Statue",
		text = {
			en = "Twin Owl Statue",
			es = "Estatua de búho gemelo",
			de = "Zwillingseulenstatue",
			fr = "Statue de chouettes jumelles",
			it = "[Twin Owl Statue]",
			pt = "[Twin Owl Statue]",
			ru = "Статуя одной из сов",
			ko = "[Twin Owl Statue]",
			cn = "[Twin Owl Statue]",
		},
	},
	[409949] = {
		readable = "Twin Owl Statue",
		text = {
			en = "Twin Owl Statue",
			es = "Estatua de búho gemelo",
			de = "Zwillingseulenstatue",
			fr = "Statue de chouettes jumelles",
			it = "[Twin Owl Statue]",
			pt = "Estátua de Coruja Gêmea",
			ru = "Статуя одной из сов",
			ko = "쌍둥이 올빼미 조각상",
			cn = "双子猫头鹰雕像",
		},
	},
	[410020] = {
		readable = "Owl Statue",
		text = {
			en = "Owl Statue",
			es = "Estatua de búho",
			de = "Eulenstatue",
			fr = "Statue de chouette",
			it = "[Owl Statue]",
			pt = "Estátua de Coruja",
			ru = "Статуя совы",
			ko = "올빼미 조각상",
			cn = "[Owl Statue]",
		},
	},
	[410299] = {
		readable = "Arcane Secrets",
		text = {
			en = "Arcane Secrets",
			es = "Secretos Arcanos",
			de = "Arkane Geheimnisse",
			fr = "Secrets arcaniques",
			it = "[Arcane Secrets]",
			pt = "[Arcane Secrets]",
			ru = "Секреты тайной магии",
			ko = "마법의 비밀",
			cn = "[Arcane Secrets]",
		},
	},
	[410369] = {
		readable = "Dead Drop",
		model = 196989,
		text = {
			en = "Dead Drop",
			es = "Escondite secreto",
			de = "Toter Briefkasten",
			fr = "Piquet boîte morte",
			it = "[Dead Drop]",
			pt = "[Dead Drop]",
			ru = "Тайник",
			ko = "비밀 접선 지점",
			cn = "秘密投放点",
		},
	},
	[410528] = {
		readable = "Ornamented Chest",
		model = 196987,
		text = {
			en = "Ornamented Chest",
			es = "[Ornamented Chest]",
			de = "Verzierte Truhe",
			fr = "[Ornamented Chest]",
			it = "[Ornamented Chest]",
			pt = "[Ornamented Chest]",
			ru = "Украшенный сундук",
			ko = "장식된 상자",
			cn = "[Ornamented Chest]",
		},
	},
	[410847] = {
		readable = "Rusty Safe",
		model = 203020,
		text = {
			en = "Rusty Safe",
			es = "Caja fuerte oxidada",
			de = "Rostiger Tresor",
			fr = "Coffre rouillé",
			it = "[Rusty Safe]",
			pt = "[Rusty Safe]",
			ru = "Ржавый сейф",
			ko = "녹슨 금고",
			cn = "生锈的保险箱",
		},
	},
	[411328] = {
		readable = "Slumbering Bones",
		text = {
			en = "Slumbering Bones",
			es = "Huesos adormilados",
			de = "Schlummernde Knochen",
			fr = "Os endormis",
			it = "[Slumbering Bones]",
			pt = "Ossos Adormecidos",
			ru = "Спящие кости",
			ko = "잠자는 뼈",
			cn = "[Slumbering Bones]",
		},
	},
	[411348] = {
		readable = "Dusty Coffer",
		model = 200953,
		text = {
			en = "Dusty Coffer",
			es = "Arca polvorienta",
			de = "Staubige Truhe",
			fr = "Coffre poussiéreux",
			it = "[Dusty Coffer]",
			pt = "Baú Poeirento",
			ru = "Пыльный сундук",
			ko = "먼지투성이 상자",
			cn = "尘封之匣",
		},
	},
	[411358] = {
		readable = "Artisan's Chest",
		model = 196987,
		text = {
			en = "Artisan's Chest",
			es = "[Artisan's Chest]",
			de = "Handwerkertruhe",
			fr = "Coffre d’artisan",
			it = "[Artisan's Chest]",
			pt = "[Artisan's Chest]",
			ru = "Сундук мастера",
			ko = "장인의 상자",
			cn = "[Artisan's Chest]",
		},
	},
	[411674] = {
		readable = "Prophecy of a King's Demise",
		model = 198455,
		text = {
			en = "Prophecy of a King's Demise",
			es = "Profecía sobre la muerte de un rey",
			de = "Prophezeiung des Tods eines Königs",
			fr = "Prophétie de la chute d’un roi",
			it = "[Prophecy of a King's Demise]",
			pt = "[Prophecy of a King's Demise]",
			ru = "[Prophecy of a King's Demise]",
			ko = "[Prophecy of a King's Demise]",
			cn = "[Prophecy of a King's Demise]",
		},
	},
	[411710] = {
		readable = "Demonic Reliquary",
		model = 196976,
		text = {
			en = "Demonic Reliquary",
			es = "Relicario demoníaco",
			de = "Dämonisches Reliquiar",
			fr = "[Demonic Reliquary]",
			it = "[Demonic Reliquary]",
			pt = "[Demonic Reliquary]",
			ru = "[Demonic Reliquary]",
			ko = "[Demonic Reliquary]",
			cn = "[Demonic Reliquary]",
		},
	},
	[411715] = {
		readable = "Bough of Altek",
		text = {
			en = "Bough of Altek",
			es = "Rama de Altek",
			de = "Alteks Zweig",
			fr = "Branche d’Altek",
			it = "[Bough of Altek]",
			pt = "[Bough of Altek]",
			ru = "[Bough of Altek]",
			ko = "알텍의 가지",
			cn = "[Bough of Altek]",
		},
	},
	[412224] = {
		readable = "Dark Ritual Stone",
		model = 201097,
		text = {
			en = "Dark Ritual Stone",
			es = "Piedra de ritual oscuro",
			de = "Dunkler Ritualstein",
			fr = "Pierre de rituel des ténèbres",
			it = "[Dark Ritual Stone]",
			pt = "[Dark Ritual Stone]",
			ru = "[Dark Ritual Stone]",
			ko = "암흑 의식용 돌",
			cn = "[Dark Ritual Stone]",
		},
	},
	[414532] = {
		readable = "Clliffspring Chest",
		model = 196989,
		text = {
			en = "Clliffspring Chest",
			es = "Cofre de Fonroca",
			de = "Cliffspring-Truhe",
			fr = "Coffre de la Bondissante",
			it = "[Clliffspring Chest]",
			pt = "Baú Fontescarpa",
			ru = "Сундук, найденный у реки Скалистой",
			ko = "폭포수 보관함",
			cn = "[Clliffspring Chest]",
		},
	},
	[414624] = {
		readable = "Lighthouse Stash",
		model = 204112,
		text = {
			en = "Lighthouse Stash",
			es = "Alijo del faro",
			de = "Leuchtturmvorrat",
			fr = "Planque du phare",
			it = "[Lighthouse Stash]",
			pt = "Esconderijo do Farol",
			ru = "Тайник в маяке",
			ko = "등대 은닉함",
			cn = "灯塔藏匿物",
		},
	},
	[414646] = {
		readable = "Remnant",
		text = {
			en = "Remnant",
			es = "Resto",
			de = "Überreste",
			fr = "Vestige",
			it = "[Remnant]",
			pt = "[Remnant]",
			ru = "[Remnant]",
			ko = "[Remnant]",
			cn = "[Remnant]",
		},
	},
	[414658] = {
		readable = "Rubble",
		model = 189478,
		text = {
			en = "Rubble",
			es = "[Rubble]",
			de = "Geröll",
			fr = "Débris",
			it = "[Rubble]",
			pt = "[Rubble]",
			ru = "[Rubble]",
			ko = "[Rubble]",
			cn = "[Rubble]",
		},
	},
	[414663] = {
		readable = "Shatterspear Idol",
		model = 190354,
		text = {
			en = "Shatterspear Idol",
			es = "Ídolo Rompelanzas",
			de = "Götze der Shatterspear",
			fr = "Idole Briselance",
			it = "[Shatterspear Idol]",
			pt = "Ídolo Lança Partida",
			ru = "Идол Пронзающего Копья",
			ko = "뾰족창부족 우상",
			cn = "[Shatterspear Idol]",
		},
	},
	[414713] = {
		readable = "Storage Locker",
		model = 196976,
		text = {
			en = "Storage Locker",
			es = "[Storage Locker]",
			de = "[Storage Locker]",
			fr = "Vestiaire",
			it = "[Storage Locker]",
			pt = "[Storage Locker]",
			ru = "[Storage Locker]",
			ko = "[Storage Locker]",
			cn = "[Storage Locker]",
		},
	},
	[415106] = {
		readable = "Burned-Out Remains",
		model = 197145,
		text = {
			en = "Burned-Out Remains",
			es = "Restos carbonizados",
			de = "Ausgebrannte Überreste",
			fr = "Restes brûlés",
			it = "[Burned-Out Remains]",
			pt = "Restos Queimados",
			ru = "Прогоревшие останки",
			ko = "불타버린 잔해",
			cn = "焦焚残骸",
		},
	},
	[415107] = {
		readable = "Burned-Out Remains",
		model = 197145,
		text = {
			en = "Burned-Out Remains",
			es = "Restos carbonizados",
			de = "Ausgebrannte Überreste",
			fr = "Restes brûlés",
			it = "[Burned-Out Remains]",
			pt = "Restos Queimados",
			ru = "Прогоревшие останки",
			ko = "불타버린 잔해",
			cn = "焦焚残骸",
		},
	},
	[415614] = {
		readable = "Mysterious Formulae",
		model = 198455,
		text = {
			en = "Mysterious Formulae",
			es = "Fórmulas misteriosas",
			de = "[Mysterious Formulae]",
			fr = "Formules mystérieuses",
			it = "[Mysterious Formulae]",
			pt = "[Mysterious Formulae]",
			ru = "Таинственные формулы",
			ko = "[Mysterious Formulae]",
			cn = "[Mysterious Formulae]",
		},
	},
	[417072] = {
		readable = "Nailed Plank",
		model = 200454,
		text = {
			en = "Nailed Plank",
			es = "Tablón claveteado",
			de = "Festgenagelte Planke",
			fr = "Planche à clous",
			it = "[Nailed Plank]",
			pt = "Tábua com Pregos",
			ru = "Доска с гвоздями",
			ko = "못으로 고정한 판자",
			cn = "镶钉木板",
		},
	},
	[417353] = {
		readable = "Extinguished Campfire",
		text = {
			en = "Extinguished Campfire",
			es = "Hoguera apagada",
			de = "Gelöschtes Lagerfeuer",
			fr = "Feu de camp éteint",
			it = "[Extinguished Campfire]",
			pt = "Fogueira de Acampamento Extinta",
			ru = "Потушенный костер",
			ko = "꺼진 모닥불",
			cn = "熄灭的营火",
		},
	},
	[418855] = {
		readable = "Illari's Loot Cache",
		model = 196976,
		text = {
			en = "Illari's Loot Cache",
			es = "Alijo de botín de Illari",
			de = "Illaris Beutetruhe",
			fr = "Cache de butin d’Illari",
			it = "[Illari's Loot Cache]",
			pt = "[Illari's Loot Cache]",
			ru = "Тайник Иллари",
			ko = "일라리의 전리품 은닉처",
			cn = "伊莱丽的战利品箱",
		},
	},
	[422483] = {
		readable = "The Salvagematic 9000",
		model = 201020,
		text = {
			en = "The Salvagematic 9000",
			es = "Reciclamatic 9000",
			de = "Der Wiederverwertungsmat 9000",
			fr = "Recycle-o-Matic 9000",
			it = "[The Salvagematic 9000]",
			pt = "[The Salvagematic 9000]",
			ru = "Утилитрон 9000",
			ko = "자동 수습기 9000",
			cn = "[The Salvagematic 9000]",
		},
	},
	[422911] = {
		readable = "Sealed Barrel",
		model = 199713,
		text = {
			en = "Sealed Barrel",
			es = "Barrica sellada",
			de = "Versiegeltes Fass",
			fr = "Tonneau scellé",
			it = "[Sealed Barrel]",
			pt = "Barril Lacrado",
			ru = "Запечатанная бочка",
			ko = "봉인된 통",
			cn = "密封的桶",
		},
	},
	[422919] = {
		readable = "Tapped Shadowforge Keg",
		text = {
			en = "Tapped Shadowforge Keg",
			es = "Barril de Forjatiniebla empezado",
			de = "Angezapftes Schattenschmiedefass",
			fr = "Fût ombreforge en perce",
			it = "[Tapped Shadowforge Keg]",
			pt = "[Tapped Shadowforge Keg]",
			ru = "Початый тенегорнский бочонок",
			ko = "꼭지 달린 어둠괴철로단 맥주통",
			cn = "[Tapped Shadowforge Keg]",
		},
	},
	[423569] = {
		readable = "Dropped Pouch",
		model = 200442,
		text = {
			en = "Dropped Pouch",
			es = "Bolsa extraviada",
			de = "Fallengelassener Beutel",
			fr = "Bourse perdue",
			it = "[Dropped Pouch]",
			pt = "[Dropped Pouch]",
			ru = "Потерянный мешочек",
			ko = "떨어진 주머니",
			cn = "丢下的袋子",
		},
	},
	[423695] = {
		readable = "Libram of Deliverance",
		model = 198036,
		text = {
			en = "Libram of Deliverance",
			es = "Tratado de Liberación",
			de = "Buchband der Erlösung",
			fr = "Libram de délivrance",
			it = "[Libram of Deliverance]",
			pt = "Incunábulo da Libertação",
			ru = "Манускрипт избавления",
			ko = "구원의 성서",
			cn = "解脱圣契",
		},
	},
	[423703] = {
		readable = "Broken Warhammer",
		model = 203177,
		text = {
			en = "Broken Warhammer",
			es = "[Broken Warhammer]",
			de = "[Broken Warhammer]",
			fr = "Marteau de guerre brisé",
			it = "[Broken Warhammer]",
			pt = "[Broken Warhammer]",
			ru = "[Broken Warhammer]",
			ko = "[Broken Warhammer]",
			cn = "[Broken Warhammer]",
		},
	},
	[423841] = {
		readable = "Frozen Remains",
		text = {
			en = "Frozen Remains",
			es = "[Frozen Remains]",
			de = "Gefrorene Überreste",
			fr = "Dépouille gelée",
			it = "[Frozen Remains]",
			pt = "[Frozen Remains]",
			ru = "Обледенелые останки",
			ko = "얼어붙은 잔해",
			cn = "[Frozen Remains]",
		},
	},
	[424005] = {
		readable = "Pocket Litter",
		model = 197641,
		text = {
			en = "Pocket Litter",
			es = "Basura de bolsillo",
			de = "Taschenmüll",
			fr = "Litière de poche",
			it = "[Pocket Litter]",
			pt = "Lixo de Bolso",
			ru = "Карманный мусор",
			ko = "휴대용 쓰레기통",
			cn = "垃圾袋",
		},
	},
	[424006] = {
		readable = "Hastily Rolled-Up Satchel",
		model = 203429,
		text = {
			en = "Hastily Rolled-Up Satchel",
			es = "Cartera enrollada a toda prisa",
			de = "Hastig eingerollter Beutel",
			fr = "Besace roulée à la hâte",
			it = "[Hastily Rolled-Up Satchel]",
			pt = "Algibeira Enrolada às Pressas",
			ru = "Наскоро завернутая сумка",
			ko = "황급히 만 주머니",
			cn = "草草收起的包裹",
		},
	},
	[424007] = {
		readable = "Carved Figurine",
		model = 200296,
		text = {
			en = "Carved Figurine",
			es = "Figurilla tallada",
			de = "Geschnitzte Figure",
			fr = "Figurine sculptée",
			it = "[Carved Figurine]",
			pt = "Estatueta Entalhada",
			ru = "Вырезанная статуэтка",
			ko = "조각상",
			cn = "雕刻塑像",
		},
	},
	[424010] = {
		readable = "Nailed Plank",
		model = 200454,
		text = {
			en = "Nailed Plank",
			es = "Tablón claveteado",
			de = "Planke mit Nagel",
			fr = "Planche clouée",
			it = "[Nailed Plank]",
			pt = "Tábua com Pregos",
			ru = "Доска с гвоздями",
			ko = "못으로 고정한 판자",
			cn = "镶钉木板",
		},
	},
	[424012] = {
		readable = "Mound of Dirt",
		model = 189528,
		text = {
			en = "Mound of Dirt",
			es = "Túmulo de barro",
			de = "Erdhaufen",
			fr = "Monticule de terre",
			it = "[Mound of Dirt]",
			pt = "Monturo de Terra",
			ru = "Куча грязи",
			ko = "흙무더기",
			cn = "一堆泥土",
		},
	},
	[424074] = {
		readable = "Quadrangulation Beacon 001",
		model = 197768,
		text = {
			en = "Quadrangulation Beacon 001",
			es = "Baliza de cuadrangulación 001",
			de = "Quadrangulationssignalgeber 001",
			fr = "Balise de quandrangulation 001",
			it = "[Quadrangulation Beacon 001]",
			pt = "Sinalizador de Quadrangulação 001",
			ru = "Квадрангуляционный маяк 001",
			ko = "사각 측량 신호기 001",
			cn = "四边定位信标001",
		},
	},
	[424075] = {
		readable = "Quadrangulation Beacon 002",
		model = 197768,
		text = {
			en = "Quadrangulation Beacon 002",
			es = "Baliza de cuadrangulación 002",
			de = "Quadrangulationssignalgeber 002",
			fr = "Balise de quandrangulation 002",
			it = "[Quadrangulation Beacon 002]",
			pt = "Sinalizador de Quadrangulação 002",
			ru = "Квадрангуляционный маяк 002",
			ko = "사각 측량 신호기 002",
			cn = "四边定位信标002",
		},
	},
	[424076] = {
		readable = "Quadrangulation Beacon 003",
		model = 197768,
		text = {
			en = "Quadrangulation Beacon 003",
			es = "Baliza de cuadrangulación 003",
			de = "Quadrangulationssignalgeber 003",
			fr = "Balise de quandrangulation 003",
			it = "[Quadrangulation Beacon 003]",
			pt = "Sinalizador de Quadrangulação 003",
			ru = "Квадрангуляционный маяк 003",
			ko = "사각 측량 신호기 003",
			cn = "四边定位信标003",
		},
	},
	[424077] = {
		readable = "Quadrangulation Beacon 004",
		model = 197768,
		text = {
			en = "Quadrangulation Beacon 004",
			es = "Baliza de cuadrangulación 004",
			de = "Quadrangulationssignalgeber 004",
			fr = "Balise de quandrangulation 004",
			it = "[Quadrangulation Beacon 004]",
			pt = "[Quadrangulation Beacon 004]",
			ru = "[Quadrangulation Beacon 004]",
			ko = "사각 측량 신호기 004",
			cn = "四边定位信标004",
		},
	},
	[433596] = {
		readable = "Spellbound War Chest",
		model = 196987,
		text = {
			en = "Spellbound War Chest",
			es = "[Spellbound War Chest]",
			de = "Verzauberte Kriegstruhe",
			fr = "Coffre de guerre envoûté",
			it = "[Spellbound War Chest]",
			pt = "[Spellbound War Chest]",
			ru = "[Spellbound War Chest]",
			ko = "[Spellbound War Chest]",
			cn = "[Spellbound War Chest]",
		},
	},
	[439557] = {
		readable = "Nightmare Moss",
		model = 219463,
		text = {
			en = "Nightmare Moss",
			es = "Musgo de la Pesadilla",
			de = "Alptraummoos",
			fr = "Mousse des cauchemars",
			it = "[Nightmare Moss]",
			pt = "Musgo do Pesadelo",
			ru = "[Nightmare Moss]",
			ko = "악몽 이끼",
			cn = "[Nightmare Moss]",
		},
	},
	[439558] = {
		readable = "Cold Iron Deposit",
		model = 219532,
		text = {
			en = "Cold Iron Deposit",
			es = "Depósito de hierro frío",
			de = "Kalteisenvorkommen",
			fr = "Gisement de fer froid",
			it = "[Cold Iron Deposit]",
			pt = "Depósito de Ferro Frio",
			ru = "[Cold Iron Deposit]",
			ko = "[Cold Iron Deposit]",
			cn = "[Cold Iron Deposit]",
		},
	},
	[439627] = {
		readable = "Dreamroot",
		model = 219469,
		text = {
			en = "Dreamroot",
			es = "Raíz del Sueño",
			de = "Traumwurzel",
			fr = "Oniracine",
			it = "[Dreamroot]",
			pt = "Raiz-de-sonho",
			ru = "Сон-корень",
			ko = "꿈뿌리",
			cn = "梦之根",
		},
	},
	[439628] = {
		readable = "Fool's Gold Vein",
		model = 219524,
		text = {
			en = "Fool's Gold Vein",
			es = "Filón de oro falso",
			de = "Katzengoldvorkommen",
			fr = "Filon de pyrite",
			it = "[Fool's Gold Vein]",
			pt = "Veio de Ouro de Tolo",
			ru = "Жила ложного золота",
			ko = "바보의 금 광맥",
			cn = "愚人金矿脉",
		},
	},
	[439762] = {
		readable = "Star Lotus",
		model = 219483,
		text = {
			en = "Star Lotus",
			es = "Loto estelar",
			de = "Sternenlotus",
			fr = "Lotus stellaire",
			it = "[Star Lotus]",
			pt = "[Star Lotus]",
			ru = "Звездный лотос",
			ko = "별빛연꽃",
			cn = "[Star Lotus]",
		},
	},
	[439778] = {
		readable = "Starsilver Vein",
		model = 219569,
		text = {
			en = "Starsilver Vein",
			es = "Filón de plataestelar",
			de = "Sternensilberader",
			fr = "Veine d’astrargent",
			it = "[Starsilver Vein]",
			pt = "[Starsilver Vein]",
			ru = "Жила звездного серебра",
			ko = "별빛은 광맥",
			cn = "[Starsilver Vein]",
		},
	},
	[439810] = {
		readable = "Moonroot",
		model = 219486,
		text = {
			en = "Moonroot",
			es = "Raíz lunar",
			de = "Mondwurzel",
			fr = "Racine lunaire",
			it = "[Moonroot]",
			pt = "Raiz-da-lua",
			ru = "Лунный корень",
			ko = "달뿌리",
			cn = "[Moonroot]",
		},
	},
	[439815] = {
		readable = "Greater Moonstone Formation",
		model = 190809,
		text = {
			en = "Greater Moonstone Formation",
			es = "Formación de piedra lunar superior",
			de = "Große Mondsteinformation",
			fr = "Formation de pierre de lune supérieure",
			it = "[Greater Moonstone Formation]",
			pt = "Formação de Pedras-da-lua Maiores",
			ru = "Отложение большого лунного камня",
			ko = "상급 월장석 형성물",
			cn = "[Greater Moonstone Formation]",
		},
	},
	[441113] = {
		readable = "Ogre Magi Text",
		model = 198021,
		text = {
			en = "Ogre Magi Text",
			es = "[Ogre Magi Text]",
			de = "Ogermagiertext",
			fr = "Texte de l’ogre magi",
			it = "[Ogre Magi Text]",
			pt = "Texto de Magus Ogro",
			ru = "[Ogre Magi Text]",
			ko = "[Ogre Magi Text]",
			cn = "[Ogre Magi Text]",
		},
	},
	[441114] = {
		readable = "Mysterious Box",
		model = 196976,
		text = {
			en = "Mysterious Box",
			es = "[Mysterious Box]",
			de = "Geheimnisvolle Kiste",
			fr = "Boîte mystérieuse",
			it = "[Mysterious Box]",
			pt = "Caixa Misteriosa",
			ru = "[Mysterious Box]",
			ko = "[Mysterious Box]",
			cn = "[Mysterious Box]",
		},
	},
	[441119] = {
		readable = "Unhatched Green Dragon Egg",
		model = 200964,
		text = {
			en = "Unhatched Green Dragon Egg",
			es = "[Unhatched Green Dragon Egg]",
			de = "Ungeschlüpftes grünes Drachenei",
			fr = "Œuf de dragon vert non-éclos",
			it = "[Unhatched Green Dragon Egg]",
			pt = "Ovo de Dragão Verde Choco",
			ru = "[Unhatched Green Dragon Egg]",
			ko = "[Unhatched Green Dragon Egg]",
			cn = "[Unhatched Green Dragon Egg]",
		},
	},
	[441124] = {
		readable = "Dream-Touched Dragon Egg",
		model = 200964,
		text = {
			en = "Dream-Touched Dragon Egg",
			es = "Huevo de dragón tocado por el Sueño",
			de = "Traumberührtes Drachenei",
			fr = "Œuf de dragon touché par le Rêve",
			it = "[Dream-Touched Dragon Egg]",
			pt = "Ovo de Dragão Tocado pelo Sonho",
			ru = "Усиленное Сном яйцо дракона",
			ko = "꿈에 물든 용의 알",
			cn = "梦触龙蛋",
		},
	},
	[441128] = {
		readable = "Vibrating Crate",
		model = 197150,
		text = {
			en = "Vibrating Crate",
			es = "Cajón vibrante",
			de = "Vibrierende Kiste",
			fr = "Caisse vibrante",
			it = "[Vibrating Crate]",
			pt = "Caixote Vibratório",
			ru = "Вибрирующий ящик",
			ko = "진동하는 상자",
			cn = "震动的箱子",
		},
	},
	[441129] = {
		readable = "Azsharan Prophecy",
		model = 198454,
		text = {
			en = "Azsharan Prophecy",
			es = "Profecía de Azshara",
			de = "Azsharische Prophezeiung",
			fr = "Prophétie d’Azshara",
			it = "[Azsharan Prophecy]",
			pt = "Profecia Azshariana",
			ru = "Азшарское пророчество",
			ko = "아즈샤라의 예언",
			cn = "[Azsharan Prophecy]",
		},
	},
	[441133] = {
		readable = "Star-Touched Dragon Egg",
		model = 200964,
		text = {
			en = "Star-Touched Dragon Egg",
			es = "Huevo de dragón tocado por las estrellas",
			de = "Sternenberührtes Drachenei",
			fr = "Œuf de dragon touché par les étoiles",
			it = "[Star-Touched Dragon Egg]",
			pt = "[Star-Touched Dragon Egg]",
			ru = "Усиленное звездами яйцо дракона",
			ko = "별에 물든 용의 알",
			cn = "[Star-Touched Dragon Egg]",
		},
	},
	[441140] = {
		readable = "Humming Box",
		model = 196989,
		text = {
			en = "Humming Box",
			es = "Caja zumbante",
			de = "Summender Kasten",
			fr = "Boîte bourdonnante",
			it = "[Humming Box]",
			pt = "[Humming Box]",
			ru = "Гудящая коробка",
			ko = "웅웅거리는 상자",
			cn = "[Humming Box]",
		},
	},
	[441141] = {
		readable = "Dreampearl",
		model = 198719,
		text = {
			en = "Dreampearl",
			es = "Perla onírica",
			de = "Traumperle",
			fr = "Perle onirique",
			it = "[Dreampearl]",
			pt = "[Dreampearl]",
			ru = "Жемчужина Сна",
			ko = "꿈진주",
			cn = "[Dreampearl]",
		},
	},
	[441222] = {
		readable = "Grave Mound",
		model = 219463,
		text = {
			en = "Grave Mound",
			es = "[Grave Mound]",
			de = "Grabhügel",
			fr = "Tumulus",
			it = "[Grave Mound]",
			pt = "[Grave Mound]",
			ru = "[Grave Mound]",
			ko = "[Grave Mound]",
			cn = "[Grave Mound]",
		},
	},
	[441310] = {
		readable = "Moonglow Dragon Egg",
		model = 200964,
		text = {
			en = "Moonglow Dragon Egg",
			es = "Huevo de dragón de resplandor lunar",
			de = "Mondscheindrachenei",
			fr = "Œuf de dragon lueur-de-lune",
			it = "[Moonglow Dragon Egg]",
			pt = "Ovo de Dragão do Brilho da Lua",
			ru = "Лунное яйцо дракона",
			ko = "달빛너울 용의 알",
			cn = "[Moonglow Dragon Egg]",
		},
	},
	[441312] = {
		readable = "Mad Keeper's Notes",
		model = 198036,
		text = {
			en = "Mad Keeper's Notes",
			es = "Notas del vigilante demente",
			de = "Notizen des wahnsinnigen Bewahrers",
			fr = "Notes du gardien fou",
			it = "[Mad Keeper's Notes]",
			pt = "Anotações do Guardião Louco",
			ru = "Записки безумного хранителя",
			ko = "광기 어린 수호자의 기록",
			cn = "[Mad Keeper's Notes]",
		},
	},
	[441314] = {
		readable = "Harpy Screed",
		model = 201113,
		text = {
			en = "Harpy Screed",
			es = "Desvaríos de arpía",
			de = "Harpyienschrift",
			fr = "Diatribe de harpie",
			it = "[Harpy Screed]",
			pt = "Escrito das Harpias",
			ru = "Бессвязные записи гарпии",
			ko = "하피의 장광설",
			cn = "[Harpy Screed]",
		},
	},
	[441848] = {
		readable = "Small Burrow",
		model = 189528,
		text = {
			en = "Small Burrow",
			es = "Madriguera pequeña",
			de = "Kleiner Bau",
			fr = "Petit terrier",
			it = "[Small Burrow]",
			pt = "[Small Burrow]",
			ru = "Маленькая яма",
			ko = "[Small Burrow]",
			cn = "小地洞",
		},
	},
	[441946] = {
		readable = "Shrine of the Moon",
		model = 201267,
		text = {
			en = "Shrine of the Moon",
			es = "Santuario de la luna",
			de = "Schrein des Mondes",
			fr = "Sanctuaire de la Lune",
			it = "[Shrine of the Moon]",
			pt = "[Shrine of the Moon]",
			ru = "Святилище луны",
			ko = "달의 제단",
			cn = "月亮神龛",
		},
	},
	[441947] = {
		readable = "Shrine of the Beast",
		model = 201267,
		text = {
			en = "Shrine of the Beast",
			es = "Santuario de la bestia",
			de = "Schrein des Tieres",
			fr = "Sanctuaire de la Bête",
			it = "[Shrine of the Beast]",
			pt = "Altar da Fera",
			ru = "Святилище зверя",
			ko = "야수의 제단",
			cn = "野兽神龛",
		},
	},
	[441948] = {
		readable = "Shrine of the Warden",
		model = 201267,
		text = {
			en = "Shrine of the Warden",
			es = "Santuario del celador",
			de = "Schrein des Wächters",
			fr = "Sanctuaire du gardien",
			it = "[Shrine of the Warden]",
			pt = "Altar do Guardião",
			ru = "Святилище стража",
			ko = "감시관의 제단",
			cn = "守护神龛",
		},
	},
	[455812] = {
		readable = "Squire Cuthbert's Sword",
		text = {
			en = "Squire Cuthbert's Sword",
			es = "[Squire Cuthbert's Sword]",
			de = "Schwert von Knappe Cuthbert",
			fr = "Épée de l’écuyer Cuthbert",
			it = "[Squire Cuthbert's Sword]",
			pt = "Espada do Escudeiro Cuteberto",
			ru = "Меч оруженосца Катберта",
			ko = "종자 쿠스베르트의 검",
			cn = "侍从库斯伯特之剑",
		},
	},
	[457088] = {
		readable = "Advanced Swordplay",
		model = 198028,
		text = {
			en = "Advanced Swordplay",
			es = "[Advanced Swordplay]",
			de = "Fortgeschrittener Schwertkampf",
			fr = "Maniement avancé de l’épée",
			it = "[Advanced Swordplay]",
			pt = "Esgrima Avançada",
			ru = "[Advanced Swordplay]",
			ko = "고급 검술",
			cn = "《进阶剑法》",
		},
	},
	[457089] = {
		readable = "The Shadow Connection",
		model = 198028,
		text = {
			en = "The Shadow Connection",
			es = "[The Shadow Connection]",
			de = "Die Schattenverbindung",
			fr = "Le lien de l’ombre",
			it = "[The Shadow Connection]",
			pt = "[The Shadow Connection]",
			ru = "[The Shadow Connection]",
			ko = "어둠의 유대",
			cn = "《暗影的联系》",
		},
	},
	[457090] = {
		readable = "Famous (and Infamous) Rangers of Azeroth",
		model = 198028,
		text = {
			en = "Famous (and Infamous) Rangers of Azeroth",
			es = "[Famous (and Infamous) Rangers of Azeroth]",
			de = "Berühmte (und berüchtigte) Waldläufer von Azeroth",
			fr = "Forestiers célèbres (et funestes) d’Azeroth",
			it = "[Famous (and Infamous) Rangers of Azeroth]",
			pt = "Famosos (e Infames) Patrulheiros de Azeroth",
			ru = "Прославленные (и бесславные) следопыты Азерота",
			ko = "아제로스의 유명한(혹은 악명 높은) 순찰자",
			cn = "《艾泽拉斯著名（与恶名）游侠列传》",
		},
	},
	[457091] = {
		readable = "Chen's Training Manual",
		model = 198028,
		text = {
			en = "Chen's Training Manual",
			es = "[Chen's Training Manual]",
			de = "Chens Trainingshandbuch",
			fr = "Manuel d’entraînement de Chen",
			it = "[Chen's Training Manual]",
			pt = "Manual de Treino de Chen",
			ru = "Боевое руководство Чэня",
			ko = "첸의 훈련 교범",
			cn = "《老陈的修炼秘诀》",
		},
	},
	[457092] = {
		readable = "The Fury of Stormrage",
		model = 198028,
		text = {
			en = "The Fury of Stormrage",
			es = "[The Fury of Stormrage]",
			de = "Der Furor von Sturmgrimm",
			fr = "La fureur de Hurlorage",
			it = "[The Fury of Stormrage]",
			pt = "A Fúria de Tempesfúria",
			ru = "Гнев Ярости Бури",
			ko = "스톰레이지의 격노",
			cn = "[The Fury of Stormrage]",
		},
	},
	[457093] = {
		readable = "Blunt Justice: A Dwarf's Tale",
		model = 198028,
		text = {
			en = "Blunt Justice: A Dwarf's Tale",
			es = "[Blunt Justice: A Dwarf's Tale]",
			de = "Schonungslose Gerechtigkeit: Die Geschichte eines Zwerges",
			fr = "Justice expéditive : l’histoire d’un Nain",
			it = "[Blunt Justice: A Dwarf's Tale]",
			pt = "[Blunt Justice: A Dwarf's Tale]",
			ru = "Ударное правосудие: история одного дворфа",
			ko = "무딘 정의: 드워프 이야기",
			cn = "《正义钝击：矮人传奇》",
		},
	},
	[457094] = {
		readable = "The True Nature of the Light",
		model = 198028,
		text = {
			en = "The True Nature of the Light",
			es = "[The True Nature of the Light]",
			de = "Die wahre Natur des Lichts",
			fr = "La véritable nature de la Lumière",
			it = "[The True Nature of the Light]",
			pt = "[The True Nature of the Light]",
			ru = "[The True Nature of the Light]",
			ko = "빛의 진정한 본질",
			cn = "[The True Nature of the Light]",
		},
	},
	[457095] = {
		readable = "Elements for Dummies Volume I: Frost",
		model = 198028,
		text = {
			en = "Elements for Dummies Volume I: Frost",
			es = "Elementos para torpes, volumen I: Escarcha",
			de = "Elemente für Dummies Band I: Frost",
			fr = "Les éléments pour les Nuls, vol. 1 : Givre",
			it = "[Elements for Dummies Volume I: Frost]",
			pt = "Elementos Para Leigos Volume I: Gelo",
			ru = "Стихии для чайников, том I: лед",
			ko = "왕초보도 이해하는 원소 마법 제1권: 냉기",
			cn = "《元素奥义傻瓜入门第I卷：冰霜》",
		},
	},
	[457096] = {
		readable = "Be First: A Brawler's Guide to Boxing",
		model = 198028,
		text = {
			en = "Be First: A Brawler's Guide to Boxing",
			es = "[Be First: A Brawler's Guide to Boxing]",
			de = "Erster sein: Das Boxhandbuch eines Muskelprotzes",
			fr = "Arriver premier : la boxe pour les bastonneurs",
			it = "[Be First: A Brawler's Guide to Boxing]",
			pt = "Seja o Primeiro: Guia de Boxe do Brigão",
			ru = "Стань первым: руководство по кулачному бою",
			ko = "누구보다 먼저: 싸움꾼의 권투 안내서",
			cn = "《先发制人：拳手搏击指南》",
		},
	},
	[457097] = {
		readable = "Elements for Dummies Volume II: Fire",
		model = 198028,
		text = {
			en = "Elements for Dummies Volume II: Fire",
			es = "Elementos para torpes, volumen II: Fuego",
			de = "Elemente für Dummies Band I: Feuer",
			fr = "Les éléments pour les Nuls, vol. 2 : Feu",
			it = "[Elements for Dummies Volume II: Fire]",
			pt = "Elementos Para Leigos Volume II: Fogo",
			ru = "Стихии для чайников, том II: огонь",
			ko = "왕초보도 이해하는 원소 마법 제2권: 화염",
			cn = "《元素奥义傻瓜入门第II卷：火焰》",
		},
	},
	[457098] = {
		readable = "Finding Your Inner Feline: A Guide to Modern Druidism",
		model = 198028,
		text = {
			en = "Finding Your Inner Feline: A Guide to Modern Druidism",
			es = "[Finding Your Inner Feline: A Guide to Modern Druidism]",
			de = "Die innere Katze finden: Ein Leitfaden für moderne Druidenkünste",
			fr = "Trouver votre félin intérieur : guide du druidisme moderne",
			it = "[Finding Your Inner Feline: A Guide to Modern Druidism]",
			pt = "[Finding Your Inner Feline: A Guide to Modern Druidism]",
			ru = "Душа кошки: руководство по современному друидизму",
			ko = "내면의 표범을 찾아서: 현대 드루이드학 안내서",
			cn = "《心若灵豹：当代德鲁伊指南》",
		},
	},
	[457099] = {
		readable = "Zirene's Guide to Getting Punched",
		model = 198028,
		text = {
			en = "Zirene's Guide to Getting Punched",
			es = "[Zirene's Guide to Getting Punched]",
			de = "Zirenes Leitfaden für den Schlagabtausch",
			fr = "Guide de l’encaissement des beignes, par Zirène",
			it = "[Zirene's Guide to Getting Punched]",
			pt = "Guia de Zerene para Levar Socos",
			ru = "Руководство Зайрина по выдерживанию тумаков",
			ko = "지렌의 맞는 법 강의",
			cn = "《吉勒内扛揍指南》",
		},
	},
	[457100] = {
		readable = "Renzik's Thoughts on \"Fair\" Fighting",
		model = 198028,
		text = {
			en = "Renzik's Thoughts on \"Fair\" Fighting",
			es = "[Renzik's Thoughts on \"Fair\" Fighting]",
			de = "Renziks Gedanken zu \"fairem\" Kämpfen",
			fr = "Réflexions de Renzik sur les combats « à la loyale »",
			it = "[Renzik's Thoughts on \"Fair\" Fighting]",
			pt = "Comentários de Renzik sobre a Luta \"Justa\"",
			ru = "Мысли Рензика о \"справедливых\" поединках",
			ko = "\"공정한\" 싸움에 대한 렌지크의 단상",
			cn = "《雷吉克的“公平”对决总结》",
		},
	},
	[457101] = {
		readable = "The Rites of Mak'Gora",
		model = 198028,
		text = {
			en = "The Rites of Mak'Gora",
			es = "[The Rites of Mak'Gora]",
			de = "Die Riten von Mak'Gora",
			fr = "Les rites de Mak’Gora",
			it = "[The Rites of Mak'Gora]",
			pt = "Os Ritos do Mak'Gora",
			ru = "[The Rites of Mak'Gora]",
			ko = "막고라 의례",
			cn = "《荣耀决斗仪式》",
		},
	},
	[457102] = {
		readable = "Elements for Dummies Volume III: Arcane",
		model = 198028,
		text = {
			en = "Elements for Dummies Volume III: Arcane",
			es = "[Elements for Dummies Volume III: Arcane]",
			de = "Elemente für Dummies Band I: Arkan",
			fr = "Les éléments pour les Nuls, vol. 3 : Arcanes",
			it = "[Elements for Dummies Volume III: Arcane]",
			pt = "Elementos Para Leigos Volume III: Arcano",
			ru = "[Elements for Dummies Volume III: Arcane]",
			ko = "왕초보도 이해하는 원소 마법 제3권: 비전",
			cn = "《元素奥义傻瓜入门第III卷：奥术》",
		},
	},
	[461639] = {
		readable = "Orthas' Hammer",
		model = 203177,
		text = {
			en = "Orthas' Hammer",
			es = "[Orthas' Hammer]",
			de = "Orthas' Hammer",
			fr = "[Orthas' Hammer]",
			it = "[Orthas' Hammer]",
			pt = "[Orthas' Hammer]",
			ru = "[Orthas' Hammer]",
			ko = "[Orthas' Hammer]",
			cn = "[Orthas' Hammer]",
		},
	},
	[462233] = {
		readable = "Shimmering Molten Crag",
		model = 219531,
		text = {
			en = "Shimmering Molten Crag",
			es = "Escoria fundida resplandeciente",
			de = "Schimmerndes geschmolzenes Gestein",
			fr = "Roche en fusion chatoyante",
			it = "[Shimmering Molten Crag]",
			pt = "Rochedo Derretido Cintilante",
			ru = "Сверкающая расплавленная скала",
			ko = "일렁이는 용암 암반",
			cn = "闪光的熔火岩块",
		},
	},
	[462236] = {
		readable = "Mysterious Chest",
		model = 219372,
		text = {
			en = "Mysterious Chest",
			es = "[Mysterious Chest]",
			de = "Mysteriöse Truhe",
			fr = "Coffre mystérieux",
			it = "[Mysterious Chest]",
			pt = "[Mysterious Chest]",
			ru = "[Mysterious Chest]",
			ko = "[Mysterious Chest]",
			cn = "[Mysterious Chest]",
		},
	},
})
do ObjectDB[objectID] = objectData; end