local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[439762] = {
		readable = "Star Lotus",
		model = 219483,
		text = {
			en = "Star Lotus",
			es = "Loto estelar",
			de = "Sternenlotus",
			fr = "Lotus stellaire",
			it = "[Star Lotus]",
			pt = "[Star Lotus]",
			ru = "[Star Lotus]",
			ko = "별빛연꽃",
			cn = "[Star Lotus]",
		},
	},
	[439778] = {
		readable = "Starsilver Vein",
		model = 219569,
		text = {
			en = "Starsilver Vein",
			es = "Filón de plataestelar",
			de = "Sternensilberader",
			fr = "Veine d’astrargent",
			it = "[Starsilver Vein]",
			pt = "[Starsilver Vein]",
			ru = "[Starsilver Vein]",
			ko = "별빛은 광맥",
			cn = "[Starsilver Vein]",
		},
	},
	[441133] = {
		readable = "Star-Touched Dragon Egg",
		model = 200964,
		text = {
			en = "Star-Touched Dragon Egg",
			es = "Huevo de dragón tocado por las estrellas",
			de = "Sternenberührtes Drachenei",
			fr = "Œuf de dragon touché par les étoiles",
			it = "[Star-Touched Dragon Egg]",
			pt = "[Star-Touched Dragon Egg]",
			ru = "[Star-Touched Dragon Egg]",
			ko = "별에 물든 용의 알",
			cn = "[Star-Touched Dragon Egg]",
		},
	},
	[441140] = {
		readable = "Humming Box",
		model = 196989,
		text = {
			en = "Humming Box",
			es = "Caja zumbante",
			de = "Summender Kasten",
			fr = "Boîte bourdonnante",
			it = "[Humming Box]",
			pt = "[Humming Box]",
			ru = "[Humming Box]",
			ko = "웅웅거리는 상자",
			cn = "[Humming Box]",
		},
	},
	[441141] = {
		readable = "Dreampearl",
		model = 198719,
		text = {
			en = "Dreampearl",
			es = "Perla onírica",
			de = "Traumperle",
			fr = "Perle onirique",
			it = "[Dreampearl]",
			pt = "[Dreampearl]",
			ru = "[Dreampearl]",
			ko = "꿈진주",
			cn = "[Dreampearl]",
		},
	},
})
do ObjectDB[objectID] = objectData; end