--------------------------------------------------
--    A C H I E V E M E N T S    M O D U L E    --
--------------------------------------------------
root(ROOTS.Achievements, achcat(ACHIEVEMENT_CATEGORY_DUNGEONS_AND_RAIDS, {
	achcat(ACHIEVEMENT_CATEGORY_GENERAL),
	achcat(ACHIEVEMENT_CATEGORY_CLASSIC_DR),
	achcat(ACHIEVEMENT_CATEGORY_THE_BURNING_CRUSADE_DR),
	achcat(ACHIEVEMENT_CATEGORY_LICH_KING_DUNGEON),
	achcat(ACHIEVEMENT_CATEGORY_LICH_KING_RAID),
	achcat(ACHIEVEMENT_CATEGORY_CATACLYSM_DUNGEON),
	achcat(ACHIEVEMENT_CATEGORY_CATACLYSM_RAID),
	achcat(ACHIEVEMENT_CATEGORY_PANDARIA_DUNGEON),
	achcat(ACHIEVEMENT_CATEGORY_PANDARIA_RAID),
	achcat(ACHIEVEMENT_CATEGORY_DRAENOR_DUNGEON),
	achcat(ACHIEVEMENT_CATEGORY_DRAENOR_RAID),
	achcat(ACHIEVEMENT_CATEGORY_LEGION_DUNGEON),
	achcat(ACHIEVEMENT_CATEGORY_LEGION_RAID),
	achcat(ACHIEVEMENT_CATEGORY_BATTLE_DUNGEON),
	achcat(ACHIEVEMENT_CATEGORY_BATTLE_RAID, {["timeline"] = { ADDED_BFA_REL }}),
	achcat(ACHIEVEMENT_CATEGORY_SHADOWLANDS_DUNGEON, {["timeline"] = { ADDED_9_0_2 }}),
	achcat(ACHIEVEMENT_CATEGORY_SHADOWLANDS_RAID, {["timeline"] = { ADDED_9_0_2 }}),
	achcat(ACHIEVEMENT_CATEGORY_DRAGONFLIGHT_DUNGEON, {["timeline"] = TIMELINE_DF_REL }),
	achcat(ACHIEVEMENT_CATEGORY_DRAGONFLIGHT_RAID, {["timeline"] = TIMELINE_DF_REL }),
}));