--------------------------------------------------
--    A C H I E V E M E N T S    M O D U L E    --
--------------------------------------------------

root(ROOTS.Achievements, achcat(ACHIEVEMENT_CATEGORY_EXPANSION_FEATURES, {
	achcat(ACHIEVEMENT_CATEGORY_ARGENT_TOURNAMENT),
	achcat(ACHIEVEMENT_CATEGORY_TOL_BARAD),
	achcat(ACHIEVEMENT_CATEGORY_PANDARIA_SCENARIOS),
	achcat(ACHIEVEMENT_CATEGORY_PROVING_GROUNDS),
	achcat(ACHIEVEMENT_CATEGORY_DRAENOR_GARRISON),
	achcat(ACHIEVEMENT_CATEGORY_LEGION_CLASS_HALL),
	achcat(ACHIEVEMENT_CATEGORY_ISLAND_EXPEDITIONS),
	achcat(ACHIEVEMENT_CATEGORY_WAR_EFFORT),
	achcat(ACHIEVEMENT_CATEGORY_HEART_OF_AZEROTH),
	achcat(ACHIEVEMENT_CATEGORY_VISIONS_OF_NZOTH),
	achcat(ACHIEVEMENT_CATEGORY_TORGHAST),
	achcat(ACHIEVEMENT_CATEGORY_COVENANT_SANCTUMS),
	achcat(ACHIEVEMENT_CATEGORY_DRAGON_ISLES),
	achcat(ACHIEVEMENT_CATEGORY_DRAGON_RACING),
	achcat(ACHIEVEMENT_CATEGORY_TUSKARR_FISHING),
	achcat(ACHIEVEMENT_CATEGORY_PRIMAL_STORMS),
	achcat(ACHIEVEMENT_CATEGORY_SHIKAAR_GRAND_HUNTS),
}));