-- NOT CURRENTLY USED!!!

-- This allowed the Parser to link various SkillID values to named global constants... but this is no longer performed anywhere
-- So this file serves as reference to the previous mappings

-- SKILLID_CONSTANTS = {
-- 	[2787] = "ABOMINABLE_STITCHING",
-- 	[171] = "ALCHEMY",
-- 	[2821] = "ARCANA_MANIPULATION",
-- 	[794] = "ARCHAEOLOGY",
-- 	[2791] = "ASCENSION_CRAFTING",
-- 	[164] = "BLACKSMITHING",
-- 	[185] = "COOKING",
-- 	[333] = "ENCHANTING",
-- 	[202] = "ENGINEERING",
-- 	[20222] = "GOBLIN_ENGINEERING",
-- 	[20219] = "GNOMISH_ENGINEERING",
-- 	[129] = "FIRST_AID",
-- 	[356] = "FISHING",
-- 	[182] = "HERBALISM",
-- 	[773] = "INSCRIPTION",
-- 	[755] = "JEWELCRAFTING",
-- 	[2720] = "JUNKYARD_TINKERING",
-- 	[165] = "LEATHERWORKING",
-- 	[633] = "LOCKPICKING",
-- 	[186] = "MINING",
-- 	[2819] = "PROTOFORM SYNTHESIS",
-- 	[960] = "RUNEFORGING",
-- 	[393] = "SKINNING",
-- 	[2777] = "SOUL_CYPHERING",
-- 	[2811] = "STYGIA_CRAFTING",
-- 	[2886] = "SUPPLY_SHIPMENTS",
-- 	[197] = "TAILORING",
-- 	[2847] = "TUSKARR_FISHING_GEAR",
-- }