-- This file is dynamically generated by Parser! DO NOT MODIFIY IT MANUALLY!
select(2, ...).RaceDB=
{
	["Blood Elf"] = 10,
	["BloodElf"] = 10,
	["Dark Iron Dwarf"] = 34,
	["DarkIronDwarf"] = 34,
	["Dracthyr"] = {
		["Alliance"] = 52,
		["Horde"] = 70,
	},
	["Draenei"] = 11,
	["Dwarf"] = 3,
	["Earthen"] = {
		["Alliance"] = 85,
		["Horde"] = 84,
	},
	["Gnome"] = 7,
	["Goblin"] = 9,
	["Highmountain Tauren"] = 28,
	["HighmountainTauren"] = 28,
	["Human"] = 1,
	["ID"] = {
		[1] = {
			["faction"] = 1,
			["gender"] = {
				[2] = {
					["icon"] = "Interface\\Icons\\achievement_character_human_male",
				},
				[3] = {
					["icon"] = "Interface\\Icons\\achievement_character_human_female",
				},
			},
		},
		[2] = {
			["faction"] = 2,
			["gender"] = {
				[2] = {
					["icon"] = "Interface\\Icons\\achievement_character_orc_male",
				},
				[3] = {
					["icon"] = "Interface\\Icons\\achievement_character_orc_female",
				},
			},
		},
		[3] = {
			["faction"] = 1,
			["gender"] = {
				[2] = {
					["icon"] = "Interface\\Icons\\achievement_character_dwarf_male",
				},
				[3] = {
					["icon"] = "Interface\\Icons\\achievement_character_dwarf_female",
				},
			},
		},
		[4] = {
			["faction"] = 1,
			["gender"] = {
				[2] = {
					["icon"] = "Interface\\Icons\\achievement_character_nightelf_male",
				},
				[3] = {
					["icon"] = "Interface\\Icons\\achievement_character_nightelf_female",
				},
			},
		},
		[5] = {
			["faction"] = 2,
			["gender"] = {
				[2] = {
					["icon"] = "Interface\\Icons\\achievement_character_undead_male",
				},
				[3] = {
					["icon"] = "Interface\\Icons\\achievement_character_undead_female",
				},
			},
		},
		[6] = {
			["faction"] = 2,
			["gender"] = {
				[2] = {
					["icon"] = "Interface\\Icons\\achievement_character_tauren_male",
				},
				[3] = {
					["icon"] = "Interface\\Icons\\achievement_character_tauren_female",
				},
			},
		},
		[7] = {
			["faction"] = 1,
			["gender"] = {
				[2] = {
					["icon"] = "Interface\\Icons\\achievement_character_gnome_male",
				},
				[3] = {
					["icon"] = "Interface\\Icons\\achievement_character_gnome_female",
				},
			},
		},
		[8] = {
			["faction"] = 2,
			["gender"] = {
				[2] = {
					["icon"] = "Interface\\Icons\\achievement_character_troll_male",
				},
				[3] = {
					["icon"] = "Interface\\Icons\\achievement_character_troll_female",
				},
			},
		},
		[9] = {
			["faction"] = 2,
			["gender"] = {
				[2] = {
					["icon"] = "Interface\\Icons\\achievement_goblinhead",
				},
				[3] = {
					["icon"] = "Interface\\Icons\\achievement_femalegoblinhead",
				},
			},
		},
		[10] = {
			["faction"] = 2,
			["gender"] = {
				[2] = {
					["icon"] = "Interface\\Icons\\achievement_character_bloodelf_male",
				},
				[3] = {
					["icon"] = "Interface\\Icons\\achievement_character_bloodelf_female",
				},
			},
		},
		[11] = {
			["faction"] = 1,
			["gender"] = {
				[2] = {
					["icon"] = "Interface\\Icons\\achievement_character_draenei_male",
				},
				[3] = {
					["icon"] = "Interface\\Icons\\achievement_character_draenei_female",
				},
			},
		},
		[22] = {
			["faction"] = 1,
			["icon"] = "Interface\\Icons\\achievement_worganhead",
		},
		[24] = {
			["icon"] = "Interface\\Icons\\achievement_character_pandaren_female",
		},
		[25] = {
			["faction"] = 1,
			["icon"] = "Interface\\Icons\\achievement_character_pandaren_female",
		},
		[26] = {
			["faction"] = 2,
			["icon"] = "Interface\\Icons\\achievement_character_pandaren_female",
		},
		[27] = {
			["faction"] = 2,
			["icon"] = "Interface\\Icons\\Achievement_alliedrace_nightborne",
		},
		[28] = {
			["faction"] = 2,
			["icon"] = "Interface\\Icons\\Achievement_alliedrace_highmountaintauren",
		},
		[29] = {
			["faction"] = 1,
			["icon"] = "Interface\\Icons\\Achievement_alliedrace_voidelf",
		},
		[30] = {
			["faction"] = 1,
			["icon"] = "Interface\\Icons\\Achievement_alliedrace_lightforgeddraenei",
		},
		[31] = {
			["faction"] = 2,
			["icon"] = "Interface\\Icons\\Achievement_alliedrace_zandalaritroll",
		},
		[32] = {
			["faction"] = 1,
			["icon"] = "Interface\\Icons\\Achievement_alliedrace_kultiranhuman",
		},
		[34] = {
			["faction"] = 1,
			["icon"] = "Interface\\Icons\\Achievement_alliedrace_darkirondwarf",
		},
		[35] = {
			["faction"] = 2,
			["icon"] = "Interface\\Icons\\Achievement_alliedrace_vulpera",
		},
		[36] = {
			["faction"] = 2,
			["icon"] = "Interface\\Icons\\Achievement_alliedrace_magharorc",
		},
		[37] = {
			["faction"] = 1,
			["icon"] = "Interface\\Icons\\Achievement_alliedrace_mechagnome",
		},
		[52] = {
			["faction"] = 1,
			["icon"] = "Interface\\Icons\\Ui_dracthyr",
		},
		[70] = {
			["faction"] = 2,
			["icon"] = "Interface\\Icons\\Ui_dracthyr",
		},
		[84] = {
			["faction"] = 2,
			["icon"] = "Interface\\Icons\\Inv_achievement_alliedrace_earthen",
		},
		[85] = {
			["faction"] = 1,
			["icon"] = "Interface\\Icons\\Inv_achievement_alliedrace_earthen",
		},
	},
	["Kul Tiran"] = 32,
	["KulTiran"] = 32,
	["Kul'Tiran"] = 32,
	["Lightforged Draenei"] = 30,
	["LightforgedDraenei"] = 30,
	["Mag har Orc"] = 36,
	["Mag'har Orc"] = 36,
	["MagharOrc"] = 36,
	["Mechagnome"] = 37,
	["Night Elf"] = 4,
	["Nightborne"] = 27,
	["NightElf"] = 4,
	["Orc"] = 2,
	["Pandaren"] = {
		["Alliance"] = 25,
		["Horde"] = 26,
		["Neutral"] = 24,
	},
	["Scourge"] = 5,
	["Tauren"] = 6,
	["Troll"] = 8,
	["Undead"] = 5,
	["Void Elf"] = 29,
	["VoidElf"] = 29,
	["Vulpera"] = 35,
	["Worgen"] = 22,
	["Zandalari Troll"] = 31,
	["ZandalariTroll"] = 31,
}