-------------------------------------------------------------------
--      E X P A N S I O N   F E A T U R E S    M O D U L E       --
-------------------------------------------------------------------
root(ROOTS.ExpansionFeatures, expansion(EXPANSION.TWW, bubbleDown({ ["timeline"] = { ADDED_11_0_1_LAUNCH } }, {
	n(ACHIEVEMENTS, {
        ach(40107, {	-- Harbinger of the Carved
            -- TODO
            -- ["timeline"] = { removed_when },
        }),
        ach(40115, {	-- Harbinger of the Runed
            -- TODO
            -- ["timeline"] = { removed_when },
        }),
        ach(40118, {	-- Harbinger of the Gilded
            -- TODO
            -- ["timeline"] = { removed_when },
        }),
    }),
})));