local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[405593] = {
		readable = "Azerothian Archives!",
		model = 4317329,
		text = {
			en = "Azerothian Archives!",
			es = "Azerothian Archives!",
			de = "Azerothian Archives!",
			fr = "Azerothian Archives!",
			it = "Azerothian Archives!",
			pt = "Azerothian Archives!",
			ru = "Azerothian Archives!",
			ko = "Azerothian Archives!",
			cn = "Azerothian Archives!",
		},
	},
	[421179] = {
		readable = "Kaldorei Bedroll",
		model = 4756260,
		text = {
			en = "Kaldorei Bedroll",
			es = "Kaldorei Bedroll",
			de = "Kaldorei Bedroll",
			fr = "Kaldorei Bedroll",
			it = "Kaldorei Bedroll",
			pt = "Kaldorei Bedroll",
			ru = "Kaldorei Bedroll",
			ko = "Kaldorei Bedroll",
			cn = "Kaldorei Bedroll",
		},
	},
	[421180] = {
		readable = "Kaldorei Backpack",
		text = {
			en = "Kaldorei Backpack",
			es = "Kaldorei Backpack",
			de = "Kaldorei Backpack",
			fr = "Kaldorei Backpack",
			it = "Kaldorei Backpack",
			pt = "Kaldorei Backpack",
			ru = "Kaldorei Backpack",
			ko = "Kaldorei Backpack",
			cn = "Kaldorei Backpack",
		},
	},
	[421181] = {
		readable = "Kaldorei Dagger",
		text = {
			en = "Kaldorei Dagger",
			es = "Kaldorei Dagger",
			de = "Kaldorei Dagger",
			fr = "Kaldorei Dagger",
			it = "Kaldorei Dagger",
			pt = "Kaldorei Dagger",
			ru = "Kaldorei Dagger",
			ko = "Kaldorei Dagger",
			cn = "Kaldorei Dagger",
		},
	},
	[421182] = {
		readable = "Kaldorei Horn",
		text = {
			en = "Kaldorei Horn",
			es = "Kaldorei Horn",
			de = "Kaldorei Horn",
			fr = "Kaldorei Horn",
			it = "Kaldorei Horn",
			pt = "Kaldorei Horn",
			ru = "Kaldorei Horn",
			ko = "Kaldorei Horn",
			cn = "Kaldorei Horn",
		},
	},
	[421183] = {
		readable = "Kaldorei Bag",
		text = {
			en = "Kaldorei Bag",
			es = "Kaldorei Bag",
			de = "Kaldorei Bag",
			fr = "Kaldorei Bag",
			it = "Kaldorei Bag",
			pt = "Kaldorei Bag",
			ru = "Kaldorei Bag",
			ko = "Kaldorei Bag",
			cn = "Kaldorei Bag",
		},
	},
	[421184] = {
		readable = "Kaldorei Shield",
		text = {
			en = "Kaldorei Shield",
			es = "Kaldorei Shield",
			de = "Kaldorei Shield",
			fr = "Kaldorei Shield",
			it = "Kaldorei Shield",
			pt = "Kaldorei Shield",
			ru = "Kaldorei Shield",
			ko = "Kaldorei Shield",
			cn = "Kaldorei Shield",
		},
	},
	[421185] = {
		readable = "Kaldorei Spear",
		text = {
			en = "Kaldorei Spear",
			es = "Kaldorei Spear",
			de = "Kaldorei Spear",
			fr = "Kaldorei Spear",
			it = "Kaldorei Spear",
			pt = "Kaldorei Spear",
			ru = "Kaldorei Spear",
			ko = "Kaldorei Spear",
			cn = "Kaldorei Spear",
		},
	},
	[421186] = {
		readable = "Kaldorei Spyglass",
		text = {
			en = "Kaldorei Spyglass",
			es = "Kaldorei Spyglass",
			de = "Kaldorei Spyglass",
			fr = "Kaldorei Spyglass",
			it = "Kaldorei Spyglass",
			pt = "Kaldorei Spyglass",
			ru = "Kaldorei Spyglass",
			ko = "Kaldorei Spyglass",
			cn = "Kaldorei Spyglass",
		},
	},
	[421338] = {
		readable = "Kaldorei Bag",
		text = {
			en = "Kaldorei Bag",
			es = "Kaldorei Bag",
			de = "Kaldorei Bag",
			fr = "Kaldorei Bag",
			it = "Kaldorei Bag",
			pt = "Kaldorei Bag",
			ru = "Kaldorei Bag",
			ko = "Kaldorei Bag",
			cn = "Kaldorei Bag",
		},
	},
	[421339] = {
		readable = "Kaldorei Horn",
		text = {
			en = "Kaldorei Horn",
			es = "Kaldorei Horn",
			de = "Kaldorei Horn",
			fr = "Kaldorei Horn",
			it = "Kaldorei Horn",
			pt = "Kaldorei Horn",
			ru = "Kaldorei Horn",
			ko = "Kaldorei Horn",
			cn = "Kaldorei Horn",
		},
	},
	[421555] = {
		readable = "Kaldorei Moon Bow",
		model = 2133380,
		text = {
			en = "Kaldorei Moon Bow",
			es = "Kaldorei Moon Bow",
			de = "Kaldorei Moon Bow",
			fr = "Kaldorei Moon Bow",
			it = "Kaldorei Moon Bow",
			pt = "Kaldorei Moon Bow",
			ru = "Kaldorei Moon Bow",
			ko = "Kaldorei Moon Bow",
			cn = "Kaldorei Moon Bow",
		},
	},
})
do ObjectDB[objectID] = objectData; end