local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[434527] = {
		readable = "Thimble's Cache",
		text = {
			en = "Thimble's Cache",
			es = "Thimble's Cache",
			de = "Thimble's Cache",
			fr = "Thimble's Cache",
			it = "Thimble's Cache",
			pt = "Thimble's Cache",
			ru = "Thimble's Cache",
			ko = "Thimble's Cache",
			cn = "Thimble's Cache",
		},
	},
	[453167] = {
		readable = "Disturbed Lynx Treasure",
		text = {
			en = "Disturbed Lynx Treasure",
			es = "Disturbed Lynx Treasure",
			de = "Disturbed Lynx Treasure",
			fr = "Disturbed Lynx Treasure",
			it = "Disturbed Lynx Treasure",
			pt = "Disturbed Lynx Treasure",
			ru = "Disturbed Lynx Treasure",
			ko = "Disturbed Lynx Treasure",
			cn = "Disturbed Lynx Treasure",
		},
	},
	[454331] = {
		readable = "Thimble's Cache",
		text = {
			en = "Thimble's Cache",
			es = "Thimble's Cache",
			de = "Thimble's Cache",
			fr = "Thimble's Cache",
			it = "Thimble's Cache",
			pt = "Thimble's Cache",
			ru = "Thimble's Cache",
			ko = "Thimble's Cache",
			cn = "Thimble's Cache",
		},
	},
	[455506] = {
		readable = "|cff1EFF00Sturdy Chest",
		model = 5128194,
		text = {
			en = "|cff1EFF00Sturdy Chest",
			es = "|cff1EFF00Cofre robusto",
			de = "|cff1EFF00Robuste Truhe",
			fr = "|cff1EFF00Coffre solide",
			it = "|cff1EFF00Cassa Resistente",
			pt = "|cff1EFF00Baú Resistente",
			ru = "|cff1EFF00Прочный сундук",
			ko = "|cff1EFF00Sturdy Chest",
			cn = "|cff1EFF00Sturdy Chest",
		},
	},
	[455531] = {
		readable = "|cff1EFF00Sturdy Chest",
		model = 5128194,
		text = {
			en = "|cff1EFF00Sturdy Chest",
			es = "|cff1EFF00Cofre robusto",
			de = "|cff1EFF00Robuste Truhe",
			fr = "|cff1EFF00Coffre solide",
			it = "|cff1EFF00Cassa Resistente",
			pt = "|cff1EFF00Baú Resistente",
			ru = "|cff1EFF00Прочный сундук",
			ko = "|cff1EFF00Sturdy Chest",
			cn = "|cff1EFF00Sturdy Chest",
		},
	},
})
do ObjectDB[objectID] = objectData; end