local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[445360] = {
		readable = "Pilfered Loot",
		model = 4621388,
		text = {
			en = "Pilfered Loot",
			es = "Botín birlado",
			de = "Gestohlene Beute",
			fr = "Butin dérobé",
			it = "Pilfered Loot",
			pt = "Saque Furtado",
			ru = "Украденные трофеи",
			ko = "Pilfered Loot",
			cn = "失窃的战利品",
			tw = "Pilfered Loot",
		},
	},
	[446435] = {
		readable = "Violet Thread",
		model = 5760601,
		text = {
			en = "Violet Thread",
			es = "Hilo violeta",
			de = "Violetter Faden",
			fr = "Fil violet",
			it = "Filo Viola",
			pt = "Fio Violeta",
			ru = "Аметистовая нить",
			ko = "보랏빛 실",
			cn = "紫色的线",
			tw = "Violet Thread",
		},
	},
	[446437] = {
		readable = "Crimson Thread",
		model = 5760602,
		text = {
			en = "Crimson Thread",
			es = "Hilo carmesí",
			de = "Blutroter Faden",
			fr = "Fil écarlate",
			it = "Filo Cremisi",
			pt = "Fio Carmesim",
			ru = "Багровая нить",
			ko = "진홍빛 실",
			cn = "猩红的线",
			tw = "Crimson Thread",
		},
	},
	[446438] = {
		readable = "Gold Thread",
		model = 5760603,
		text = {
			en = "Gold Thread",
			es = "Hilo dorado",
			de = "Goldener Faden",
			fr = "Fil d’or",
			it = "Filo Dorato",
			pt = "Fio de Ouro",
			ru = "Золотая нить",
			ko = "황금빛 실",
			cn = "金色的线",
			tw = "Gold Thread",
		},
	},
})
do ObjectDB[objectID] = objectData; end