local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[457271] = {
		readable = "Crabber Supplies",
		model = 2123117,
		text = {
			en = "Crabber Supplies",
			es = "Crabber Supplies",
			de = "Crabber Supplies",
			fr = "Crabber Supplies",
			it = "Crabber Supplies",
			pt = "Crabber Supplies",
			ru = "Crabber Supplies",
			ko = "Crabber Supplies",
			cn = "Crabber Supplies",
		},
	},
	[464938] = {
		readable = "Awakened Cache",
		model = 5128194,
		text = {
			en = "Awakened Cache",
			es = "Awakened Cache",
			de = "Awakened Cache",
			fr = "Awakened Cache",
			it = "Awakened Cache",
			pt = "Awakened Cache",
			ru = "Awakened Cache",
			ko = "Awakened Cache",
			cn = "Awakened Cache",
		},
	},
	[465241] = {
		readable = "Awakened Cache",
		model = 4323481,
		text = {
			en = "Awakened Cache",
			es = "Awakened Cache",
			de = "Awakened Cache",
			fr = "Awakened Cache",
			it = "Awakened Cache",
			pt = "Awakened Cache",
			ru = "Awakened Cache",
			ko = "Awakened Cache",
			cn = "Awakened Cache",
		},
	},
	[465242] = {
		readable = "Awakened Cache",
		model = 4323481,
		text = {
			en = "Awakened Cache",
			es = "Awakened Cache",
			de = "Awakened Cache",
			fr = "Awakened Cache",
			it = "Awakened Cache",
			pt = "Awakened Cache",
			ru = "Awakened Cache",
			ko = "Awakened Cache",
			cn = "Awakened Cache",
		},
	},
	[465243] = {
		readable = "Awakened Cache",
		model = 4323481,
		text = {
			en = "Awakened Cache",
			es = "Awakened Cache",
			de = "Awakened Cache",
			fr = "Awakened Cache",
			it = "Awakened Cache",
			pt = "Awakened Cache",
			ru = "Awakened Cache",
			ko = "Awakened Cache",
			cn = "Awakened Cache",
		},
	},
})
do ObjectDB[objectID] = objectData; end