local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[454207] = {
		readable = "|cff1EFF00Sturdy Chest",
		text = {
			en = "|cff1EFF00Sturdy Chest",
			es = "|cff1EFF00Sturdy Chest",
			de = "|cff1EFF00Sturdy Chest",
			fr = "|cff1EFF00Sturdy Chest",
			it = "|cff1EFF00Sturdy Chest",
			pt = "|cff1EFF00Sturdy Chest",
			ru = "|cff1EFF00Sturdy Chest",
			ko = "|cff1EFF00Sturdy Chest",
			cn = "|cff1EFF00Sturdy Chest",
		},
	},
	[455482] = {
		readable = "|cff1EFF00Sturdy Chest",
		text = {
			en = "|cff1EFF00Sturdy Chest",
			es = "|cff1EFF00Sturdy Chest",
			de = "|cff1EFF00Sturdy Chest",
			fr = "|cff1EFF00Sturdy Chest",
			it = "|cff1EFF00Sturdy Chest",
			pt = "|cff1EFF00Sturdy Chest",
			ru = "|cff1EFF00Sturdy Chest",
			ko = "|cff1EFF00Sturdy Chest",
			cn = "|cff1EFF00Sturdy Chest",
		},
	},
	[455484] = {
		readable = "|cff1EFF00Sturdy Chest",
		text = {
			en = "|cff1EFF00Sturdy Chest",
			es = "|cff1EFF00Sturdy Chest",
			de = "|cff1EFF00Sturdy Chest",
			fr = "|cff1EFF00Sturdy Chest",
			it = "|cff1EFF00Sturdy Chest",
			pt = "|cff1EFF00Sturdy Chest",
			ru = "|cff1EFF00Sturdy Chest",
			ko = "|cff1EFF00Sturdy Chest",
			cn = "|cff1EFF00Sturdy Chest",
		},
	},
	[455490] = {
		readable = "|cff1EFF00Sturdy Chest",
		text = {
			en = "|cff1EFF00Sturdy Chest",
			es = "|cff1EFF00Sturdy Chest",
			de = "|cff1EFF00Sturdy Chest",
			fr = "|cff1EFF00Sturdy Chest",
			it = "|cff1EFF00Sturdy Chest",
			pt = "|cff1EFF00Sturdy Chest",
			ru = "|cff1EFF00Sturdy Chest",
			ko = "|cff1EFF00Sturdy Chest",
			cn = "|cff1EFF00Sturdy Chest",
		},
	},
	[455503] = {
		readable = "|cff1EFF00Sturdy Chest",
		text = {
			en = "|cff1EFF00Sturdy Chest",
			es = "|cff1EFF00Sturdy Chest",
			de = "|cff1EFF00Sturdy Chest",
			fr = "|cff1EFF00Sturdy Chest",
			it = "|cff1EFF00Sturdy Chest",
			pt = "|cff1EFF00Sturdy Chest",
			ru = "|cff1EFF00Sturdy Chest",
			ko = "|cff1EFF00Sturdy Chest",
			cn = "|cff1EFF00Sturdy Chest",
		},
	},
	[455504] = {
		readable = "|cff1EFF00Sturdy Chest",
		text = {
			en = "|cff1EFF00Sturdy Chest",
			es = "|cff1EFF00Sturdy Chest",
			de = "|cff1EFF00Sturdy Chest",
			fr = "|cff1EFF00Sturdy Chest",
			it = "|cff1EFF00Sturdy Chest",
			pt = "|cff1EFF00Sturdy Chest",
			ru = "|cff1EFF00Sturdy Chest",
			ko = "|cff1EFF00Sturdy Chest",
			cn = "|cff1EFF00Sturdy Chest",
		},
	},
	[455512] = {
		readable = "|cff1EFF00Sturdy Chest",
		text = {
			en = "|cff1EFF00Sturdy Chest",
			es = "|cff1EFF00Sturdy Chest",
			de = "|cff1EFF00Sturdy Chest",
			fr = "|cff1EFF00Sturdy Chest",
			it = "|cff1EFF00Sturdy Chest",
			pt = "|cff1EFF00Sturdy Chest",
			ru = "|cff1EFF00Sturdy Chest",
			ko = "|cff1EFF00Sturdy Chest",
			cn = "|cff1EFF00Sturdy Chest",
		},
	},
	[455532] = {
		readable = "|cff1EFF00Sturdy Chest",
		text = {
			en = "|cff1EFF00Sturdy Chest",
			es = "|cff1EFF00Sturdy Chest",
			de = "|cff1EFF00Sturdy Chest",
			fr = "|cff1EFF00Sturdy Chest",
			it = "|cff1EFF00Sturdy Chest",
			pt = "|cff1EFF00Sturdy Chest",
			ru = "|cff1EFF00Sturdy Chest",
			ko = "|cff1EFF00Sturdy Chest",
			cn = "|cff1EFF00Sturdy Chest",
		},
	},
})
do ObjectDB[objectID] = objectData; end