local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[405525] = {
		readable = "Loose Dirt Mound",
		model = 189528,
		text = {
			en = "Loose Dirt Mound",
			es = "[Loose Dirt Mound]",
			de = "Lockerer Erdhaufen",
			fr = "[Loose Dirt Mound]",
			it = "[Loose Dirt Mound]",
			pt = "Monte de Terra Solta",
			ru = "[Loose Dirt Mound]",
			ko = "[Loose Dirt Mound]",
			cn = "[Loose Dirt Mound]",
		},
	},
	[405526] = {
		readable = "Loose Dirt Mound",
		model = 189528,
		text = {
			en = "Loose Dirt Mound",
			es = "[Loose Dirt Mound]",
			de = "Lockerer Erdhaufen",
			fr = "[Loose Dirt Mound]",
			it = "[Loose Dirt Mound]",
			pt = "Monte de Terra Solta",
			ru = "[Loose Dirt Mound]",
			ko = "[Loose Dirt Mound]",
			cn = "松软的泥土堆",
		},
	},
	[405529] = {
		readable = "Loose Dirt Mound",
		model = 193184,
		text = {
			en = "Loose Dirt Mound",
			es = "[Loose Dirt Mound]",
			de = "Lockerer Erdhaufen",
			fr = "[Loose Dirt Mound]",
			it = "[Loose Dirt Mound]",
			pt = "[Loose Dirt Mound]",
			ru = "Куча рыхлой земли",
			ko = "[Loose Dirt Mound]",
			cn = "[Loose Dirt Mound]",
		},
	},
	[405530] = {
		readable = "Loose Dirt Mound",
		model = 189528,
		text = {
			en = "Loose Dirt Mound",
			es = "[Loose Dirt Mound]",
			de = "Lockerer Erdhaufen",
			fr = "[Loose Dirt Mound]",
			it = "[Loose Dirt Mound]",
			pt = "[Loose Dirt Mound]",
			ru = "[Loose Dirt Mound]",
			ko = "[Loose Dirt Mound]",
			cn = "[Loose Dirt Mound]",
		},
	},
	[405531] = {
		readable = "Loose Dirt Mound",
		model = 189528,
		text = {
			en = "Loose Dirt Mound",
			es = "[Loose Dirt Mound]",
			de = "Lockerer Erdhaufen",
			fr = "[Loose Dirt Mound]",
			it = "[Loose Dirt Mound]",
			pt = "[Loose Dirt Mound]",
			ru = "Куча рыхлой земли",
			ko = "[Loose Dirt Mound]",
			cn = "[Loose Dirt Mound]",
		},
	},
	[405532] = {
		readable = "Loose Dirt Mound",
		model = 189528,
		text = {
			en = "Loose Dirt Mound",
			es = "Túmulo de barro suelto",
			de = "Lockerer Erdhaufen",
			fr = "Monticule de terre meuble",
			it = "[Loose Dirt Mound]",
			pt = "[Loose Dirt Mound]",
			ru = "Куча рыхлой земли",
			ko = "[Loose Dirt Mound]",
			cn = "[Loose Dirt Mound]",
		},
	},
	[405533] = {
		readable = "Loose Dirt Mound",
		model = 189528,
		text = {
			en = "Loose Dirt Mound",
			es = "[Loose Dirt Mound]",
			de = "[Loose Dirt Mound]",
			fr = "[Loose Dirt Mound]",
			it = "[Loose Dirt Mound]",
			pt = "[Loose Dirt Mound]",
			ru = "[Loose Dirt Mound]",
			ko = "[Loose Dirt Mound]",
			cn = "[Loose Dirt Mound]",
		},
	},
	[405535] = {
		readable = "Loose Dirt Mound",
		model = 189528,
		text = {
			en = "Loose Dirt Mound",
			es = "[Loose Dirt Mound]",
			de = "Lockerer Erdhaufen",
			fr = "[Loose Dirt Mound]",
			it = "[Loose Dirt Mound]",
			pt = "[Loose Dirt Mound]",
			ru = "Куча рыхлой земли",
			ko = "[Loose Dirt Mound]",
			cn = "[Loose Dirt Mound]",
		},
	},
	[405536] = {
		readable = "Loose Dirt Mound",
		model = 189528,
		text = {
			en = "Loose Dirt Mound",
			es = "[Loose Dirt Mound]",
			de = "[Loose Dirt Mound]",
			fr = "[Loose Dirt Mound]",
			it = "[Loose Dirt Mound]",
			pt = "[Loose Dirt Mound]",
			ru = "[Loose Dirt Mound]",
			ko = "[Loose Dirt Mound]",
			cn = "[Loose Dirt Mound]",
		},
	},
})
do ObjectDB[objectID] = objectData; end