local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[287941] = {
		readable = "Bag of Horse Treats",
		model = 1602312,
		text = {
			en = "Bag of Horse Treats",
			es = "Bolsa de premios para caballos",
			de = "Tasche mit Pferdeleckerli",
			fr = "Sac de friandises pour chevaux",
			it = "Sacca di Mangime per Cavalli",
			pt = "Saco de Petiscos para Cavalo",
			ru = "Сумка с лакомством для лошадей",
			ko = "말 간식 가방",
			cn = "一袋马粮",
		},
	},
	[287945] = {
		readable = "Suspicious Barrel",
		model = 1830405,
		text = {
			en = "Suspicious Barrel",
			es = "Barrica sospechosa",
			de = "Verdächtiges Fass",
			fr = "Tonneau suspect",
			it = "Barile Sospetto",
			pt = "Barril Suspeito",
			ru = "Подозрительная бочка",
			ko = "수상한 통",
			cn = "可疑的桶",
		},
	},
	[287955] = {
		readable = "7th Legion Supply Crate",
		model = 950767,
		text = {
			en = "7th Legion Supply Crate",
			es = "Cajón de suministros de la Séptima Legión",
			de = "Vorratskiste der 7. Legion",
			fr = "Caisse de fournitures de la 7e Légion",
			it = "Cassa di Rifornimenti della VII Legione",
			pt = "Caixote de Suprimentos da 7ª Legião",
			ru = "Ящик с припасами 7-го легиона",
			ko = "7군단 보급품 상자",
			cn = "[7th Legion Supply Crate]",
		},
	},
	[287956] = {
		readable = "Mysterious Stones",
		model = 1355114,
		text = {
			en = "Mysterious Stones",
			es = "[Mysterious Stones]",
			de = "[Mysterious Stones]",
			fr = "[Mysterious Stones]",
			it = "[Mysterious Stones]",
			pt = "[Mysterious Stones]",
			ru = "[Mysterious Stones]",
			ko = "[Mysterious Stones]",
			cn = "[Mysterious Stones]",
		},
	},
	[288151] = {
		readable = "Sack of Flour",
		model = 1709126,
		text = {
			en = "Sack of Flour",
			es = "Saco de harina",
			de = "Mehlsack",
			fr = "Sac de farine",
			it = "Sacco di Farina",
			pt = "Saca de Farinha",
			ru = "Мешок муки",
			ko = "밀가루 자루",
			cn = "一袋面粉",
		},
	},
	[288154] = {
		readable = "Idol of Binding",
		model = 794713,
		text = {
			en = "Idol of Binding",
			es = "Ídolo de vinculación",
			de = "Götze der Bindung",
			fr = "Idole de lien",
			it = "Idolo del Vincolo",
			pt = "Ídolo da Vinculação",
			ru = "Идол привязывания",
			ko = "속박의 우상",
			cn = "[Idol of Binding]",
		},
	},
	[288160] = {
		readable = "Sea Glass",
		model = 392119,
		text = {
			en = "Sea Glass",
			es = "Cristal marino",
			de = "Seeglas",
			fr = "Verre marin",
			it = "Vetro Marino",
			pt = "Vidro do Mar",
			ru = "Морское стекло",
			ko = "[Sea Glass]",
			cn = "[Sea Glass]",
		},
	},
	[288168] = {
		readable = "Sea Glass",
		model = 1345283,
		text = {
			en = "Sea Glass",
			es = "Cristal marino",
			de = "Seeglas",
			fr = "Verre marin",
			it = "Vetro Marino",
			pt = "Vidro do Mar",
			ru = "Морское стекло",
			ko = "[Sea Glass]",
			cn = "[Sea Glass]",
		},
	},
	[288169] = {
		readable = "Sea Glass",
		model = 1306822,
		text = {
			en = "Sea Glass",
			es = "Cristal marino",
			de = "Seeglas",
			fr = "Verre marin",
			it = "Vetro Marino",
			pt = "Vidro do Mar",
			ru = "Морское стекло",
			ko = "[Sea Glass]",
			cn = "[Sea Glass]",
		},
	},
	[288189] = {
		readable = "Bonebeak Scavenger Meat",
		model = 126278,
		text = {
			en = "Bonebeak Scavenger Meat",
			es = "Carne de carroñero Picohueso",
			de = "Knochenschnabelaas",
			fr = "Viande de charognard à bec d’ivoire",
			it = "Carne di Rapace Durobecco",
			pt = "Carne de Catador Bicossudo",
			ru = "Мясо твердоклювого падальщика",
			ko = "뼈부리 청소부 고기",
			cn = "骨喙食腐鸟肉",
		},
	},
	[288190] = {
		readable = "Bonebeak Scavenger Meat",
		model = 960874,
		text = {
			en = "Bonebeak Scavenger Meat",
			es = "Carne de carroñero Picohueso",
			de = "Knochenschnabelaas",
			fr = "Viande de charognard à bec d’ivoire",
			it = "Carne di Rapace Durobecco",
			pt = "Carne de Catador Bicossudo",
			ru = "Мясо твердоклювого падальщика",
			ko = "뼈부리 청소부 고기",
			cn = "骨喙食腐鸟肉",
		},
	},
	[288191] = {
		readable = "Brineclaw Meat",
		model = 1726290,
		text = {
			en = "Brineclaw Meat",
			es = "Carne de garrasalmuera",
			de = "Salzklauenfleisch",
			fr = "Viande de pincécume",
			it = "Carne di Zannabrina",
			pt = "Carne de Garrassalma",
			ru = "Мясо соленогого рака",
			ko = "[Brineclaw Meat]",
			cn = "咸爪龙虾人的肉",
		},
	},
	[288192] = {
		readable = "Brineclaw Meat",
		model = 1726287,
		text = {
			en = "Brineclaw Meat",
			es = "Carne de garrasalmuera",
			de = "Salzklauenfleisch",
			fr = "Viande de pincécume",
			it = "Carne di Zannabrina",
			pt = "Carne de Garrassalma",
			ru = "Мясо соленогого рака",
			ko = "[Brineclaw Meat]",
			cn = "咸爪龙虾人的肉",
		},
	},
	[288196] = {
		readable = "Alliance Banner",
		model = 1021317,
		text = {
			en = "Alliance Banner",
			es = "Estandarte de la Alianza",
			de = "Allianzbanner",
			fr = "Bannière de l’Alliance",
			it = "Stendardo dell'Alleanza",
			pt = "Estandarte da Aliança",
			ru = "Знамя Альянса",
			ko = "얼라이언스 깃발",
			cn = "[Alliance Banner]",
		},
	},
	[288214] = {
		readable = "Wanted Poster",
		model = 199426,
		text = {
			en = "Wanted Poster",
			es = "Cartel de Se busca",
			de = "Steckbrief",
			fr = "Avis de recherche",
			it = "Manifesto dei Ricercati",
			pt = "Cartaz de Procura-se",
			ru = "Плакат \"Разыскивается\"",
			ko = "현상 수배 전단",
			cn = "通缉布告",
		},
	},
	[288223] = {
		readable = "Weathered Bookcase",
		model = 198047,
		text = {
			en = "Weathered Bookcase",
			es = "[Weathered Bookcase]",
			de = "[Weathered Bookcase]",
			fr = "[Weathered Bookcase]",
			it = "[Weathered Bookcase]",
			pt = "[Weathered Bookcase]",
			ru = "[Weathered Bookcase]",
			ko = "[Weathered Bookcase]",
			cn = "[Weathered Bookcase]",
		},
	},
	[288240] = {
		readable = "Crate of Candles",
		model = 199634,
		text = {
			en = "Crate of Candles",
			es = "Cajón de velas",
			de = "Kiste mit Kerzen",
			fr = "Caisse de bougies",
			it = "[Crate of Candles]",
			pt = "Caixote de Velas",
			ru = "Ящик со свечами",
			ko = "[Crate of Candles]",
			cn = "蜡烛箱",
		},
	},
	[288241] = {
		readable = "Joseph Redpath's Monument",
		model = 189538,
		text = {
			en = "Joseph Redpath's Monument",
			es = "[Joseph Redpath's Monument]",
			de = "[Joseph Redpath's Monument]",
			fr = "[Joseph Redpath's Monument]",
			it = "[Joseph Redpath's Monument]",
			pt = "[Joseph Redpath's Monument]",
			ru = "[Joseph Redpath's Monument]",
			ko = "[Joseph Redpath's Monument]",
			cn = "[Joseph Redpath's Monument]",
		},
	},
	[288251] = {
		readable = "Invincible",
		model = 199985,
		text = {
			en = "Invincible",
			es = "Invencible",
			de = "Unbesiegbar",
			fr = "Invincible",
			it = "Invincibile",
			pt = "Invencível",
			ru = "Непобедимый",
			ko = "천하무적",
			cn = "无敌",
		},
	},
	[288257] = {
		readable = "Abandoned Outhouse",
		model = 190617,
		text = {
			en = "Abandoned Outhouse",
			es = "Letrina abandonada",
			de = "Verlassenes Plumpsklo",
			fr = "Toilettes abandonnées",
			it = "Latrina Abbandonata",
			pt = "Banheiro Abandonado",
			ru = "Заброшенный нужник",
			ko = "버려진 간이화장실",
			cn = "废弃的厕所",
		},
	},
	[288301] = {
		readable = "Uther the Lightbringer",
		model = 204142,
		text = {
			en = "Uther the Lightbringer",
			es = "[Uther the Lightbringer]",
			de = "[Uther the Lightbringer]",
			fr = "[Uther the Lightbringer]",
			it = "[Uther the Lightbringer]",
			pt = "[Uther the Lightbringer]",
			ru = "[Uther the Lightbringer]",
			ko = "[Uther the Lightbringer]",
			cn = "[Uther the Lightbringer]",
		},
	},
	[288310] = {
		readable = "Outhouse",
		model = 190617,
		text = {
			en = "Outhouse",
			es = "[Outhouse]",
			de = "[Outhouse]",
			fr = "[Outhouse]",
			it = "[Outhouse]",
			pt = "[Outhouse]",
			ru = "[Outhouse]",
			ko = "[Outhouse]",
			cn = "[Outhouse]",
		},
	},
	[288311] = {
		readable = "Lillith's Dinner Table",
		model = 198598,
		text = {
			en = "Lillith's Dinner Table",
			es = "Mesa de comedor de Lillith",
			de = "Lilliths Esstisch",
			fr = "Table de dîner de Lillith",
			it = "[Lillith's Dinner Table]",
			pt = "Mesa de Jantar da Lillith",
			ru = "Обеденный стол Лилит",
			ko = "릴리스의 제단",
			cn = "莉莉丝的餐桌",
		},
	},
	[288316] = {
		readable = "Gunther's Books",
		model = 198056,
		text = {
			en = "Gunther's Books",
			es = "Libros de Gunther",
			de = "Gunthers Bücher",
			fr = "Livres de Gunther",
			it = "[Gunther's Books]",
			pt = "Livros do Tertuliano",
			ru = "Книги Гюнтера",
			ko = "[Gunther's Books]",
			cn = "冈瑟尔的书籍",
		},
	},
})
do ObjectDB[objectID] = objectData; end