local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[411622] = {
		readable = "Machinist Plinth",
		model = 5422076,
		text = {
			en = "Machinist Plinth",
			es = "Pedestal de maquinista",
			de = "Maschinistensockel",
			fr = "Socle de machiniste",
			it = "Plinto del Macchinista",
			pt = "Pedestal de Maquinista",
			ru = "Механическое основание",
			ko = "기계공 대좌",
			cn = "机械师底座",
		},
	},
	[411623] = {
		readable = "Machinist Plinth",
		model = 5422076,
		text = {
			en = "Machinist Plinth",
			es = "Pedestal de maquinista",
			de = "Maschinistensockel",
			fr = "Socle de machiniste",
			it = "Plinto del Macchinista",
			pt = "Pedestal de Maquinista",
			ru = "Механическое основание",
			ko = "기계공 대좌",
			cn = "机械师底座",
		},
	},
	[411624] = {
		readable = "Machinist Plinth",
		model = 5422076,
		text = {
			en = "Machinist Plinth",
			es = "Pedestal de maquinista",
			de = "Maschinistensockel",
			fr = "Socle de machiniste",
			it = "Plinto del Macchinista",
			pt = "Pedestal de Maquinista",
			ru = "Механическое основание",
			ko = "기계공 대좌",
			cn = "机械师底座",
		},
	},
	[411878] = {
		readable = "Intriguing Scrap",
		model = 1016121,
		text = {
			en = "Intriguing Scrap",
			es = "Chatarra interesante",
			de = "Interessanter Schrott",
			fr = "Pièces intrigantes",
			it = "Intriguing Scrap",
			pt = "Sucata Intrigante",
			ru = "Любопытный обрезок",
			ko = "흥미로운 고철",
			cn = "有意思的残片",
		},
	},
	[417136] = {
		readable = "Intriguing Scrap",
		model = 955720,
		text = {
			en = "Intriguing Scrap",
			es = "Chatarra interesante",
			de = "Interessanter Schrott",
			fr = "Pièces intrigantes",
			it = "Intriguing Scrap",
			pt = "Sucata Intrigante",
			ru = "Любопытный обрезок",
			ko = "흥미로운 고철",
			cn = "有意思的残片",
		},
	},
	[417137] = {
		readable = "Intriguing Scrap",
		model = 996198,
		text = {
			en = "Intriguing Scrap",
			es = "Chatarra interesante",
			de = "Interessanter Schrott",
			fr = "Pièces intrigantes",
			it = "Intriguing Scrap",
			pt = "Sucata Intrigante",
			ru = "Любопытный обрезок",
			ko = "흥미로운 고철",
			cn = "有意思的残片",
		},
	},
	[417138] = {
		readable = "Intriguing Scrap",
		model = 959393,
		text = {
			en = "Intriguing Scrap",
			es = "Chatarra interesante",
			de = "Interessanter Schrott",
			fr = "Pièces intrigantes",
			it = "Intriguing Scrap",
			pt = "Sucata Intrigante",
			ru = "Любопытный обрезок",
			ko = "흥미로운 고철",
			cn = "有意思的残片",
		},
	},
	[421525] = {
		readable = "Shinies",
		model = 5408470,
		text = {
			en = "Shinies",
			es = "Shinies",
			de = "Leuchties",
			fr = "Qui-brille",
			it = "Shinies",
			pt = "Brilhinhos",
			ru = "Блестяшки",
			ko = "Shinies",
			cn = "亮闪闪",
		},
	},
	[421592] = {
		readable = "Life Savings",
		model = 5503818,
		text = {
			en = "Life Savings",
			es = "Life Savings",
			de = "Lebensersparnisse",
			fr = "Économies d’une vie",
			it = "Life Savings",
			pt = "Life Savings",
			ru = "Сбережения",
			ko = "Life Savings",
			cn = "毕生积蓄",
		},
	},
	[421594] = {
		readable = "Gainful Employment",
		model = 5169958,
		text = {
			en = "Gainful Employment",
			es = "Gainful Employment",
			de = "Einträgliche Anstellung",
			fr = "Emploi lucratif",
			it = "Gainful Employment",
			pt = "Gainful Employment",
			ru = "Оплачиваемая работа",
			ko = "Gainful Employment",
			cn = "收益雇佣",
		},
	},
	[421597] = {
		readable = "Village Center",
		model = 5347569,
		text = {
			en = "Village Center",
			es = "Village Center",
			de = "Dorfmitte",
			fr = "Centre du village",
			it = "Village Center",
			pt = "Village Center",
			ru = "Центр деревни",
			ko = "Village Center",
			cn = "村庄中心",
		},
	},
	[421599] = {
		readable = "Local Industry",
		model = 5355794,
		text = {
			en = "Local Industry",
			es = "Local Industry",
			de = "Lokale Industrie",
			fr = "Industrie locale",
			it = "Local Industry",
			pt = "Local Industry",
			ru = "Местная промышленность",
			ko = "Local Industry",
			cn = "本土工业",
		},
	},
	[421735] = {
		readable = "Prooftelling Flower",
		model = 5203126,
		text = {
			en = "Prooftelling Flower",
			es = "Prooftelling Flower",
			de = "Beweiskräftige Blume",
			fr = "Fleur de preuve",
			it = "Prooftelling Flower",
			pt = "Prooftelling Flower",
			ru = "Правдолюбивый цветок",
			ko = "Prooftelling Flower",
			cn = "显证之花",
		},
	},
	[428699] = {
		readable = "Sizzling Barrel",
		model = 5454456,
		text = {
			en = "Sizzling Barrel",
			es = "Barrica abrasadora",
			de = "Zischendes Fass",
			fr = "Tonneau grésillant",
			it = "Sizzling Barrel",
			pt = "Barril Sibilante",
			ru = "Шкворчащая бочка",
			ko = "지글거리는 통",
			cn = "灼热之桶",
		},
	},
	[436933] = {
		readable = "Softsnout's Favorite Shovel",
		model = 5355799,
		text = {
			en = "Softsnout's Favorite Shovel",
			es = "Softsnout's Favorite Shovel",
			de = "Weichschnauzes Lieblingsschaufel",
			fr = "Pelle favorite de Museau-doux",
			it = "Softsnout's Favorite Shovel",
			pt = "Softsnout's Favorite Shovel",
			ru = "Любимая лопатка Мягконосой",
			ko = "Softsnout's Favorite Shovel",
			cn = "柔鼻者最喜欢的铁铲",
		},
	},
})
do ObjectDB[objectID] = objectData; end