local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[455487] = {
		readable = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
		text = {
			en = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			es = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			de = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			fr = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			it = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			pt = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			ru = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			ko = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			cn = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
		},
	},
	[455492] = {
		readable = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
		text = {
			en = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			es = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			de = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			fr = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			it = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			pt = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			ru = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			ko = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			cn = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
		},
	},
	[455493] = {
		readable = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
		text = {
			en = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			es = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			de = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			fr = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			it = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			pt = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			ru = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			ko = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			cn = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
		},
	},
	[455509] = {
		readable = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
		text = {
			en = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			es = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			de = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			fr = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			it = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			pt = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			ru = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			ko = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			cn = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
		},
	},
	[455514] = {
		readable = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
		text = {
			en = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			es = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			de = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			fr = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			it = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			pt = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			ru = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			ko = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			cn = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
		},
	},
	[455533] = {
		readable = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
		text = {
			en = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			es = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			de = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			fr = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			it = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			pt = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			ru = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			ko = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			cn = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
		},
	},
})
do ObjectDB[objectID] = objectData; end