local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[286982] = {
		readable = "Lost Coin",
		model = 916276,
		text = {
			en = "Lost Coin",
			es = "[Lost Coin]",
			de = "[Lost Coin]",
			fr = "[Lost Coin]",
			it = "[Lost Coin]",
			pt = "[Lost Coin]",
			ru = "[Lost Coin]",
			ko = "[Lost Coin]",
			cn = "[Lost Coin]",
		},
	},
	[286983] = {
		readable = "Fire Lord's Cache",
		model = 519955,
		text = {
			en = "Fire Lord's Cache",
			es = "Alijo del Señor del Fuego",
			de = "Truhe des Feuerlords",
			fr = "Cache du seigneur du feu",
			it = "Cassa del Signore del Fuoco",
			pt = "Baú do Senhor do Fogo",
			ru = "Сундук повелителя огня",
			ko = "[Fire Lord's Cache]",
			cn = "[Fire Lord's Cache]",
		},
	},
	[286984] = {
		readable = "Fiery Chest",
		model = 519955,
		text = {
			en = "Fiery Chest",
			es = "Cofre ígneo",
			de = "Feurige Truhe",
			fr = "Coffre embrasé",
			it = "Cassa in Fiamme",
			pt = "Baú Flamejante",
			ru = "Пылающий ларец",
			ko = "타오르는 상자",
			cn = "炽炎宝箱",
		},
	},
	[286985] = {
		readable = "Gusting Chest",
		model = 253430,
		text = {
			en = "Gusting Chest",
			es = "Cofre de ráfaga",
			de = "Windige Truhe",
			fr = "Coffre enveloppé de vent",
			it = "Cassa Folgorante",
			pt = "Baú Lufante",
			ru = "Грозовой ларец",
			ko = "휘몰아치는 상자",
			cn = "风吹的箱子",
		},
	},
	[286986] = {
		readable = "Wind Lord's Cache",
		model = 253430,
		text = {
			en = "Wind Lord's Cache",
			es = "Alijo del Señor del Viento",
			de = "Truhe des Windlords",
			fr = "Cache du seigneur du vent",
			it = "Cassa del Signore del Vento",
			pt = "Baú do Senhor do Vento",
			ru = "Сундук повелителя ветра",
			ko = "[Wind Lord's Cache]",
			cn = "风领主的宝箱",
		},
	},
	[286987] = {
		readable = "Frozen Chest",
		model = 253441,
		text = {
			en = "Frozen Chest",
			es = "Cofre congelado",
			de = "Gefrorene Truhe",
			fr = "Coffre gelé",
			it = "Cassa Ghiacciata",
			pt = "Baú Congelado",
			ru = "Ледяной ларец",
			ko = "[Frozen Chest]",
			cn = "冰冻的箱子",
		},
	},
	[286988] = {
		readable = "Water Lord's Cache",
		model = 253441,
		text = {
			en = "Water Lord's Cache",
			es = "Alijo del Señor del Agua",
			de = "Truhe des Wasserlords",
			fr = "Cache de seigneur de l’eau",
			it = "Cassa del Signore dell'Acqua",
			pt = "Baú do Senhor da Água",
			ru = "Сундук повелителя воды",
			ko = "[Water Lord's Cache]",
			cn = "[Water Lord's Cache]",
		},
	},
	[286989] = {
		readable = "Stone Chest",
		model = 446679,
		text = {
			en = "Stone Chest",
			es = "Cofre de piedra",
			de = "Steintruhe",
			fr = "Coffre en pierre",
			it = "Cassa di Pietra",
			pt = "Baú de Pedra",
			ru = "Каменный ларец",
			ko = "돌 상자",
			cn = "石头箱子",
		},
	},
	[286990] = {
		readable = "Earth Lord's Cache",
		model = 446679,
		text = {
			en = "Earth Lord's Cache",
			es = "Alijo del Señor de la Tierra",
			de = "Truhe des Erdlords",
			fr = "Cache du seigneur de la terre",
			it = "[Earth Lord's Cache]",
			pt = "Baú do Senhor da Terra",
			ru = "Сундук повелителя земли",
			ko = "[Earth Lord's Cache]",
			cn = "[Earth Lord's Cache]",
		},
	},
	[287000] = {
		readable = "Mark of Ash",
		model = 1127328,
		text = {
			en = "Mark of Ash",
			es = "Marca de ceniza",
			de = "Eschenmal",
			fr = "Marque de cendres",
			it = "Marchio della Cenere",
			pt = "Marca de Cinzas",
			ru = "Метка ясеня",
			ko = "재의 징표",
			cn = "灰烬印记",
		},
	},
	[287001] = {
		readable = "Mark of Yew",
		model = 1127332,
		text = {
			en = "Mark of Yew",
			es = "Marca de tejo",
			de = "Eibenmal",
			fr = "Marque d’if",
			it = "Marchio del Tasso",
			pt = "Marca de Teixo",
			ru = "Метка тиса",
			ko = "주목의 징표",
			cn = "紫杉印记",
		},
	},
	[287002] = {
		readable = "Mark of Alder",
		model = 1127329,
		text = {
			en = "Mark of Alder",
			es = "Marca de aliso",
			de = "Erlenmal",
			fr = "Marque d’aulne",
			it = "Marchio dell'Ontano",
			pt = "Marca de Alder",
			ru = "Метка гадюки",
			ko = "자작나무의 징표",
			cn = "奥德尔印记",
		},
	},
	[287006] = {
		readable = "Faithless Weapon Rack",
		model = 1719861,
		text = {
			en = "Faithless Weapon Rack",
			es = "Expositor de armas de los infieles",
			de = "Waffenständer der Treulosen",
			fr = "Râtelier d’armes infidèles",
			it = "Rastrelliera delle Armi dei Senzafede",
			pt = "Cavalete de Armas de Ímpios",
			ru = "Оружейная стойка отступников",
			ko = "부정한 무기 선반",
			cn = "无信者武器架",
		},
	},
	[287048] = {
		readable = "Xibalan Fossil",
		model = 1566950,
		text = {
			en = "Xibalan Fossil",
			es = "Fósil de Xibala",
			de = "Fossil von Xibala",
			fr = "Fossile xibalani",
			it = "Fossile Xibalano",
			pt = "Fóssil Xibalano",
			ru = "Окаменелость Ксибалы",
			ko = "[Xibalan Fossil]",
			cn = "[Xibalan Fossil]",
		},
	},
	[287049] = {
		readable = "Xibalan Fossil",
		model = 1567242,
		text = {
			en = "Xibalan Fossil",
			es = "Fósil de Xibala",
			de = "Fossil von Xibala",
			fr = "Fossile xibalani",
			it = "Fossile Xibalano",
			pt = "Fóssil Xibalano",
			ru = "Окаменелость Ксибалы",
			ko = "[Xibalan Fossil]",
			cn = "[Xibalan Fossil]",
		},
	},
	[287050] = {
		readable = "Xibalan Fossil",
		model = 1567241,
		text = {
			en = "Xibalan Fossil",
			es = "Fósil de Xibala",
			de = "Fossil von Xibala",
			fr = "Fossile xibalani",
			it = "Fossile Xibalano",
			pt = "Fóssil Xibalano",
			ru = "Окаменелость Ксибалы",
			ko = "[Xibalan Fossil]",
			cn = "[Xibalan Fossil]",
		},
	},
	[287051] = {
		readable = "Xibalan Fossil",
		model = 1567244,
		text = {
			en = "Xibalan Fossil",
			es = "Fósil de Xibala",
			de = "Fossil von Xibala",
			fr = "Fossile xibalani",
			it = "Fossile Xibalano",
			pt = "Fóssil Xibalano",
			ru = "Окаменелость Ксибалы",
			ko = "[Xibalan Fossil]",
			cn = "[Xibalan Fossil]",
		},
	},
	[287052] = {
		readable = "Xibalan Fossil",
		model = 1566949,
		text = {
			en = "Xibalan Fossil",
			es = "Fósil de Xibala",
			de = "Fossil von Xibala",
			fr = "Fossile xibalani",
			it = "Fossile Xibalano",
			pt = "Fóssil Xibalano",
			ru = "Окаменелость Ксибалы",
			ko = "[Xibalan Fossil]",
			cn = "[Xibalan Fossil]",
		},
	},
	[287053] = {
		readable = "Xibalan Fossil",
		model = 1566947,
		text = {
			en = "Xibalan Fossil",
			es = "Fósil de Xibala",
			de = "Fossil von Xibala",
			fr = "Fossile xibalani",
			it = "Fossile Xibalano",
			pt = "Fóssil Xibalano",
			ru = "Окаменелость Ксибалы",
			ko = "[Xibalan Fossil]",
			cn = "[Xibalan Fossil]",
		},
	},
	[287054] = {
		readable = "Xibalan Fossil",
		model = 1563209,
		text = {
			en = "Xibalan Fossil",
			es = "Fósil de Xibala",
			de = "Fossil von Xibala",
			fr = "Fossile xibalani",
			it = "Fossile Xibalano",
			pt = "Fóssil Xibalano",
			ru = "Окаменелость Ксибалы",
			ko = "[Xibalan Fossil]",
			cn = "[Xibalan Fossil]",
		},
	},
	[287055] = {
		readable = "Xibalan Fossil",
		model = 1567243,
		text = {
			en = "Xibalan Fossil",
			es = "Fósil de Xibala",
			de = "Fossil von Xibala",
			fr = "Fossile xibalani",
			it = "Fossile Xibalano",
			pt = "Fóssil Xibalano",
			ru = "Окаменелость Ксибалы",
			ko = "[Xibalan Fossil]",
			cn = "[Xibalan Fossil]",
		},
	},
	[287057] = {
		readable = "Old Wooden Box",
		model = 446677,
		text = {
			en = "Old Wooden Box",
			es = "[Old Wooden Box]",
			de = "[Old Wooden Box]",
			fr = "[Old Wooden Box]",
			it = "[Old Wooden Box]",
			pt = "[Old Wooden Box]",
			ru = "[Old Wooden Box]",
			ko = "[Old Wooden Box]",
			cn = "[Old Wooden Box]",
		},
	},
	[287066] = {
		readable = "Morgrum's Device",
		model = 1019382,
		text = {
			en = "Morgrum's Device",
			es = "Dispositivo de Morgrum",
			de = "Mogrums Gerät",
			fr = "Appareil de Morgrum",
			it = "Dispositivo di Morgrum",
			pt = "Dispositivo de Morgrum",
			ru = "Устройство Моргрума",
			ko = "모르그럼의 장치",
			cn = "墨古姆的仪器",
		},
	},
	[287067] = {
		readable = "Morgrum's Device",
		model = 1019382,
		text = {
			en = "Morgrum's Device",
			es = "Dispositivo de Morgrum",
			de = "Mogrums Gerät",
			fr = "Appareil de Morgrum",
			it = "Dispositivo di Morgrum",
			pt = "Dispositivo de Morgrum",
			ru = "Устройство Моргрума",
			ko = "모르그럼의 장치",
			cn = "墨古姆的仪器",
		},
	},
	[287068] = {
		readable = "Morgrum's Device",
		model = 1019382,
		text = {
			en = "Morgrum's Device",
			es = "Dispositivo de Morgrum",
			de = "Mogrums Gerät",
			fr = "Appareil de Morgrum",
			it = "Dispositivo di Morgrum",
			pt = "Dispositivo de Morgrum",
			ru = "Устройство Моргрума",
			ko = "[Morgrum's Device]",
			cn = "墨古姆的仪器",
		},
	},
	[287070] = {
		readable = "Iron Stores",
		model = 1388069,
		text = {
			en = "Iron Stores",
			es = "Provisiones de hierro",
			de = "Eisenlager",
			fr = "Réserves de fer",
			it = "Scorte di Ferro",
			pt = "Reservas de Ferro",
			ru = "Запасы железа",
			ko = "철 저장고",
			cn = "铁矿贮藏",
		},
	},
	[287079] = {
		readable = "Iron Stores",
		model = 1388069,
		text = {
			en = "Iron Stores",
			es = "Provisiones de hierro",
			de = "Eisenlager",
			fr = "Réserves de fer",
			it = "Scorte di Ferro",
			pt = "Reservas de Ferro",
			ru = "Запасы железа",
			ko = "철 저장고",
			cn = "铁矿贮藏",
		},
	},
	[287086] = {
		readable = "Azerite Node",
		model = 1857376,
		text = {
			en = "Azerite Node",
			es = "Nodo de azerita",
			de = "Azeritvorkommen",
			fr = "Gisement d’azérite",
			it = "Giacimento d'Azerite",
			pt = "Veio de Azerita",
			ru = "Азеритовый выброс",
			ko = "아제라이트 암석",
			cn = "艾泽里特矿点",
		},
	},
	[287091] = {
		readable = "Bootleg Weapon Crate",
		model = 1602479,
		text = {
			en = "Bootleg Weapon Crate",
			es = "Cajón de armas de contrabando",
			de = "Kiste mit geschmuggelten Waffen",
			fr = "Caisse d’armes de contrebande",
			it = "Cassa d'Armi di Contrabbando",
			pt = "Caixote de Armas Contrabandeado",
			ru = "Контрабандный ящик с оружием",
			ko = "불법 무기 상자",
			cn = "[Bootleg Weapon Crate]",
		},
	},
	[287120] = {
		readable = "Gusting Portal",
		model = 166432,
		text = {
			en = "Gusting Portal",
			es = "Portal de ráfaga",
			de = "Brausendes Portal",
			fr = "Portail venteux",
			it = "Portale Vorticoso",
			pt = "Portal Lufante",
			ru = "Колышущийся портал",
			ko = "[Gusting Portal]",
			cn = "疾风传送门",
		},
	},
	[287140] = {
		readable = "Planning Map",
		model = 1852934,
		text = {
			en = "Planning Map",
			es = "[Planning Map]",
			de = "[Planning Map]",
			fr = "[Planning Map]",
			it = "[Planning Map]",
			pt = "[Planning Map]",
			ru = "[Planning Map]",
			ko = "[Planning Map]",
			cn = "[Planning Map]",
		},
	},
	[287159] = {
		readable = "Infused Trident Rack",
		model = 1096619,
		text = {
			en = "Infused Trident Rack",
			es = "Expositor de tridentes imbuidos",
			de = "Geladener Dreizackständer",
			fr = "Râtelier de tridents imprégnés",
			it = "Rastrelliera con Tridente Infuso",
			pt = "Cavalete de Tridente Imbuído",
			ru = "Стойка с наполненными силой трезубцами",
			ko = "마력 깃든 삼지창 선반",
			cn = "灌注力量的三叉戟武器架",
		},
	},
	[287160] = {
		readable = "Smuggled Goods",
		model = 310483,
		text = {
			en = "Smuggled Goods",
			es = "Bienes de contrabando",
			de = "Schmuggelwaren",
			fr = "Marchandises de contrebande",
			it = "Beni di Contrabbando",
			pt = "Produtos Contrabandeados",
			ru = "Контрабандные товары",
			ko = "밀수된 물품",
			cn = "走私的货物",
		},
	},
	[287161] = {
		readable = "Ancient Texts",
		model = 200640,
		text = {
			en = "Ancient Texts",
			es = "Textos antiguos",
			de = "Uralte Schriftstücke",
			fr = "Textes antiques",
			it = "Testi Antichi",
			pt = "Textos Antigos",
			ru = "Древние тексты",
			ko = "고대 문서",
			cn = "古代文献",
		},
	},
	[287163] = {
		readable = "Glowing Mushroom",
		model = 367357,
		text = {
			en = "Glowing Mushroom",
			es = "Champiñón resplandeciente",
			de = "Leuchtender Pilz",
			fr = "Champignon luminescent",
			it = "Fungo Luminoso",
			pt = "Cogumelo Brilhante",
			ru = "Светящийся гриб",
			ko = "빛나는 버섯",
			cn = "荧光蘑菇",
		},
	},
	[287164] = {
		readable = "Portal to Boralus",
		model = 2123273,
		text = {
			en = "Portal to Boralus",
			es = "Portal a Boralus",
			de = "Portal nach Boralus",
			fr = "Portail vers Boralus",
			it = "Portale per Boralus",
			pt = "Portal para Boralus",
			ru = "Портал в Боралус",
			ko = "보랄러스로 통하는 차원문",
			cn = "[Portal to Boralus]",
		},
	},
	[287165] = {
		readable = "Glowing Mushroom",
		model = 367365,
		text = {
			en = "Glowing Mushroom",
			es = "Champiñón resplandeciente",
			de = "Leuchtender Pilz",
			fr = "Champignon luminescent",
			it = "Fungo Luminoso",
			pt = "Cogumelo Brilhante",
			ru = "Светящийся гриб",
			ko = "빛나는 버섯",
			cn = "荧光蘑菇",
		},
	},
	[287180] = {
		readable = "Roast Boar",
		model = 198228,
		text = {
			en = "Roast Boar",
			es = "[Roast Boar]",
			de = "[Roast Boar]",
			fr = "[Roast Boar]",
			it = "[Roast Boar]",
			pt = "[Roast Boar]",
			ru = "[Roast Boar]",
			ko = "[Roast Boar]",
			cn = "[Roast Boar]",
		},
	},
	[287181] = {
		readable = "Colossal Cheese Wheel",
		model = 1115707,
		text = {
			en = "Colossal Cheese Wheel",
			es = "[Colossal Cheese Wheel]",
			de = "[Colossal Cheese Wheel]",
			fr = "[Colossal Cheese Wheel]",
			it = "[Colossal Cheese Wheel]",
			pt = "[Colossal Cheese Wheel]",
			ru = "[Colossal Cheese Wheel]",
			ko = "[Colossal Cheese Wheel]",
			cn = "[Colossal Cheese Wheel]",
		},
	},
	[287182] = {
		readable = "Basket of Eggs",
		model = 1709397,
		text = {
			en = "Basket of Eggs",
			es = "[Basket of Eggs]",
			de = "[Basket of Eggs]",
			fr = "[Basket of Eggs]",
			it = "[Basket of Eggs]",
			pt = "[Basket of Eggs]",
			ru = "[Basket of Eggs]",
			ko = "[Basket of Eggs]",
			cn = "[Basket of Eggs]",
		},
	},
	[287183] = {
		readable = "Keg of Applebrew",
		model = 929379,
		text = {
			en = "Keg of Applebrew",
			es = "[Keg of Applebrew]",
			de = "[Keg of Applebrew]",
			fr = "[Keg of Applebrew]",
			it = "[Keg of Applebrew]",
			pt = "[Keg of Applebrew]",
			ru = "[Keg of Applebrew]",
			ko = "[Keg of Applebrew]",
			cn = "[Keg of Applebrew]",
		},
	},
	[287184] = {
		readable = "Iron Cart",
		model = 984860,
		text = {
			en = "Iron Cart",
			es = "Vagoneta de hierro",
			de = "Eisenlore",
			fr = "Chariot en fer",
			it = "Carrello di Ferro",
			pt = "Carrinho de Ferro",
			ru = "Вагонетка с железом",
			ko = "철 수레",
			cn = "铁矿车",
		},
	},
	[287186] = {
		readable = "Ogre Supplies",
		model = 875614,
		text = {
			en = "Ogre Supplies",
			es = "[Ogre Supplies]",
			de = "[Ogre Supplies]",
			fr = "[Ogre Supplies]",
			it = "[Ogre Supplies]",
			pt = "[Ogre Supplies]",
			ru = "[Ogre Supplies]",
			ko = "[Ogre Supplies]",
			cn = "[Ogre Supplies]",
		},
	},
	[287187] = {
		readable = "Rebel Weaponry",
		model = 329805,
		text = {
			en = "Rebel Weaponry",
			es = "Armamento rebelde",
			de = "Rebellenwaffen",
			fr = "Armes des rebelles",
			it = "Armi dei Ribelli",
			pt = "Armamento dos Rebeldes",
			ru = "Оружие для партизан",
			ko = "저항군 무기",
			cn = "叛军武器",
		},
	},
	[287190] = {
		readable = "Rebel Weaponry",
		model = 189687,
		text = {
			en = "Rebel Weaponry",
			es = "Armamento rebelde",
			de = "Rebellenwaffen",
			fr = "Armes des rebelles",
			it = "Armi dei Ribelli",
			pt = "Armamento dos Rebeldes",
			ru = "Оружие для партизан",
			ko = "저항군 무기",
			cn = "叛军武器",
		},
	},
	[287191] = {
		readable = "Rebel Weaponry",
		model = 200604,
		text = {
			en = "Rebel Weaponry",
			es = "Armamento rebelde",
			de = "Rebellenwaffen",
			fr = "Armes des rebelles",
			it = "Armi dei Ribelli",
			pt = "Armamento dos Rebeldes",
			ru = "Оружие для партизан",
			ko = "저항군 무기",
			cn = "叛军武器",
		},
	},
	[287193] = {
		readable = "Rebel Weaponry",
		model = 199436,
		text = {
			en = "Rebel Weaponry",
			es = "Armamento rebelde",
			de = "Rebellenwaffen",
			fr = "Armes des rebelles",
			it = "Armi dei Ribelli",
			pt = "Armamento dos Rebeldes",
			ru = "Оружие для партизан",
			ko = "저항군 무기",
			cn = "叛军武器",
		},
	},
	[287195] = {
		readable = "Ball &amp; Chain",
		model = 1663793,
		text = {
			en = "Ball &amp; Chain",
			es = "Bola y cadena",
			de = "Kugelfessel",
			fr = "Boulets et chaînes",
			it = "Palla con Catena",
			pt = "Bola e Corrente",
			ru = "Ядро на цепи",
			ko = "족쇄",
			cn = "链球",
		},
	},
	[287196] = {
		readable = "Rebel Weaponry",
		model = 244232,
		text = {
			en = "Rebel Weaponry",
			es = "Armamento rebelde",
			de = "Rebellenwaffen",
			fr = "Armes des rebelles",
			it = "Armi dei Ribelli",
			pt = "Armamento dos Rebeldes",
			ru = "Оружие для партизан",
			ko = "저항군 무기",
			cn = "叛军武器",
		},
	},
	[287197] = {
		readable = "Carnivorous Flower",
		model = 1936556,
		text = {
			en = "Carnivorous Flower",
			es = "Flor carnívora",
			de = "Fleischfressende Blume",
			fr = "Fleur carnivore",
			it = "Fiore Carnivoro",
			pt = "Flor Carnívora",
			ru = "Плотоядный цветок",
			ko = "육식 꽃",
			cn = "食肉花朵",
		},
	},
	[287198] = {
		readable = "Azerite Node",
		model = 1857377,
		text = {
			en = "Azerite Node",
			es = "Nodo de azerita",
			de = "Azeritvorkommen",
			fr = "Gisement d’azérite",
			it = "Giacimento d'Azerite",
			pt = "Veio de Azerita",
			ru = "Азеритовый выброс",
			ko = "아제라이트 암석",
			cn = "艾泽里特矿点",
		},
	},
	[287238] = {
		readable = "Ancient Altar",
		model = 1729199,
		text = {
			en = "Ancient Altar",
			es = "Altar antiguo",
			de = "Uralter Altar",
			fr = "Ancien autel",
			it = "Antico Altare",
			pt = "Altar Ancestral",
			ru = "Древний алтарь",
			ko = "고대 제단",
			cn = "上古祭坛",
		},
	},
	[287314] = {
		readable = "Disturbed Sand",
		model = 367849,
		text = {
			en = "Disturbed Sand",
			es = "Arena revuelta",
			de = "Aufgewühlter Sand",
			fr = "Sable dérangé",
			it = "Sabbia Fremente",
			pt = "Areia Revolvida",
			ru = "Потревоженные пески",
			ko = "파헤쳐진 모래",
			cn = "翻过的泥土",
		},
	},
	[287315] = {
		readable = "Blazing Gateway",
		model = 516236,
		text = {
			en = "Blazing Gateway",
			es = "Portal llameante",
			de = "Loderndes Tor",
			fr = "Porte flambloyante",
			it = "Varco Fiammeggiante",
			pt = "Passagem Fulgurante",
			ru = "Пылающие врата",
			ko = "[Blazing Gateway]",
			cn = "灼光传送门",
		},
	},
	[287316] = {
		readable = "Swirling Postern",
		model = 418785,
		text = {
			en = "Swirling Postern",
			es = "Portal trasero arremolinado",
			de = "Strömende Pforte",
			fr = "Poterne tourbillonnante",
			it = "Manifesto Turbinante",
			pt = "Poterna Convoluta",
			ru = "Вихрящийся проход",
			ko = "[Swirling Postern]",
			cn = "回旋的暗道",
		},
	},
	[287317] = {
		readable = "Crystalline Ingress",
		model = 418797,
		text = {
			en = "Crystalline Ingress",
			es = "Acceso cristalino",
			de = "Kristalliner Durchgang",
			fr = "Entrée cristalline",
			it = "Ingresso Cristallino",
			pt = "Entrada Cristalina",
			ru = "Кристаллический вход",
			ko = "수정 진입로",
			cn = "[Crystalline Ingress]",
		},
	},
	[287330] = {
		readable = "Broken Wagon",
		model = 1721052,
		text = {
			en = "Broken Wagon",
			es = "Carreta rota",
			de = "Kaputter Wagen",
			fr = "Chariot cassé",
			it = "Carro Danneggiato",
			pt = "Carroça Destroçada",
			ru = "Сломанная повозка",
			ko = "망가진 수레",
			cn = "损坏的货车",
		},
	},
	[287331] = {
		readable = "Grain Sack",
		model = 949213,
		text = {
			en = "Grain Sack",
			es = "Saco de grano",
			de = "Getreidesack",
			fr = "Sac de grain",
			it = "Sacco di Grano",
			pt = "Saco de Grãos",
			ru = "Мешок зерна",
			ko = "곡식 자루",
			cn = "谷物袋",
		},
	},
	[287332] = {
		readable = "Mysterious Trashpile",
		model = 1255019,
		text = {
			en = "Mysterious Trashpile",
			es = "Montón de basura misteriosa",
			de = "Mysteriöser Müllhaufen",
			fr = "Tas de déchets mystérieux",
			it = "Pila di Rifiuti Misteriosa",
			pt = "Pilha de Lixo Misteriosa",
			ru = "Загадочная куча мусора",
			ko = "정체불명의 쓰레기 더미",
			cn = "神秘垃圾堆",
		},
	},
	[287337] = {
		readable = "Broken Wagon",
		model = 1721052,
		text = {
			en = "Broken Wagon",
			es = "[Broken Wagon]",
			de = "[Broken Wagon]",
			fr = "[Broken Wagon]",
			it = "[Broken Wagon]",
			pt = "[Broken Wagon]",
			ru = "[Broken Wagon]",
			ko = "[Broken Wagon]",
			cn = "[Broken Wagon]",
		},
	},
	[287342] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears001",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears001",
			es = "[Doodad_8DU_CityofGold_CeilingSpears001]",
			de = "Doodad_8DU_CityofGold_CeilingSpears001",
			fr = "Doodad_8DU_CityofGold_CeilingSpears001",
			it = "[Doodad_8DU_CityofGold_CeilingSpears001]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears001",
			ru = "Doodad_8DU_CityofGold_CeilingSpears001",
			ko = "Doodad_8DU_CityofGold_CeilingSpears001",
			cn = "Doodad_8DU_CityofGold_CeilingSpears001",
		},
	},
	[287343] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears002",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears002",
			es = "[Doodad_8DU_CityofGold_CeilingSpears002]",
			de = "Doodad_8DU_CityofGold_CeilingSpears002",
			fr = "Doodad_8DU_CityofGold_CeilingSpears002",
			it = "[Doodad_8DU_CityofGold_CeilingSpears002]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears002",
			ru = "Doodad_8DU_CityofGold_CeilingSpears002",
			ko = "Doodad_8DU_CityofGold_CeilingSpears002",
			cn = "Doodad_8DU_CityofGold_CeilingSpears002",
		},
	},
	[287344] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears003",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears003",
			es = "[Doodad_8DU_CityofGold_CeilingSpears003]",
			de = "Doodad_8DU_CityofGold_CeilingSpears003",
			fr = "Doodad_8DU_CityofGold_CeilingSpears003",
			it = "[Doodad_8DU_CityofGold_CeilingSpears003]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears003",
			ru = "Doodad_8DU_CityofGold_CeilingSpears003",
			ko = "Doodad_8DU_CityofGold_CeilingSpears003",
			cn = "Doodad_8DU_CityofGold_CeilingSpears003",
		},
	},
	[287345] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears004",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears004",
			es = "[Doodad_8DU_CityofGold_CeilingSpears004]",
			de = "Doodad_8DU_CityofGold_CeilingSpears004",
			fr = "Doodad_8DU_CityofGold_CeilingSpears004",
			it = "[Doodad_8DU_CityofGold_CeilingSpears004]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears004",
			ru = "Doodad_8DU_CityofGold_CeilingSpears004",
			ko = "Doodad_8DU_CityofGold_CeilingSpears004",
			cn = "Doodad_8DU_CityofGold_CeilingSpears004",
		},
	},
	[287346] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears005",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears005",
			es = "[Doodad_8DU_CityofGold_CeilingSpears005]",
			de = "Doodad_8DU_CityofGold_CeilingSpears005",
			fr = "Doodad_8DU_CityofGold_CeilingSpears005",
			it = "[Doodad_8DU_CityofGold_CeilingSpears005]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears005",
			ru = "Doodad_8DU_CityofGold_CeilingSpears005",
			ko = "Doodad_8DU_CityofGold_CeilingSpears005",
			cn = "Doodad_8DU_CityofGold_CeilingSpears005",
		},
	},
	[287347] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears006",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears006",
			es = "[Doodad_8DU_CityofGold_CeilingSpears006]",
			de = "Doodad_8DU_CityofGold_CeilingSpears006",
			fr = "Doodad_8DU_CityofGold_CeilingSpears006",
			it = "[Doodad_8DU_CityofGold_CeilingSpears006]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears006",
			ru = "Doodad_8DU_CityofGold_CeilingSpears006",
			ko = "Doodad_8DU_CityofGold_CeilingSpears006",
			cn = "Doodad_8DU_CityofGold_CeilingSpears006",
		},
	},
	[287348] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears007",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears007",
			es = "[Doodad_8DU_CityofGold_CeilingSpears007]",
			de = "Doodad_8DU_CityofGold_CeilingSpears007",
			fr = "Doodad_8DU_CityofGold_CeilingSpears007",
			it = "[Doodad_8DU_CityofGold_CeilingSpears007]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears007",
			ru = "Doodad_8DU_CityofGold_CeilingSpears007",
			ko = "Doodad_8DU_CityofGold_CeilingSpears007",
			cn = "Doodad_8DU_CityofGold_CeilingSpears007",
		},
	},
	[287349] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears008",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears008",
			es = "[Doodad_8DU_CityofGold_CeilingSpears008]",
			de = "Doodad_8DU_CityofGold_CeilingSpears008",
			fr = "Doodad_8DU_CityofGold_CeilingSpears008",
			it = "[Doodad_8DU_CityofGold_CeilingSpears008]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears008",
			ru = "Doodad_8DU_CityofGold_CeilingSpears008",
			ko = "Doodad_8DU_CityofGold_CeilingSpears008",
			cn = "Doodad_8DU_CityofGold_CeilingSpears008",
		},
	},
	[287350] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears009",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears009",
			es = "[Doodad_8DU_CityofGold_CeilingSpears009]",
			de = "Doodad_8DU_CityofGold_CeilingSpears009",
			fr = "Doodad_8DU_CityofGold_CeilingSpears009",
			it = "[Doodad_8DU_CityofGold_CeilingSpears009]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears009",
			ru = "Doodad_8DU_CityofGold_CeilingSpears009",
			ko = "Doodad_8DU_CityofGold_CeilingSpears009",
			cn = "Doodad_8DU_CityofGold_CeilingSpears009",
		},
	},
	[287351] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears010",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears010",
			es = "[Doodad_8DU_CityofGold_CeilingSpears010]",
			de = "Doodad_8DU_CityofGold_CeilingSpears010",
			fr = "Doodad_8DU_CityofGold_CeilingSpears010",
			it = "[Doodad_8DU_CityofGold_CeilingSpears010]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears010",
			ru = "Doodad_8DU_CityofGold_CeilingSpears010",
			ko = "Doodad_8DU_CityofGold_CeilingSpears010",
			cn = "Doodad_8DU_CityofGold_CeilingSpears010",
		},
	},
	[287352] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears011",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears011",
			es = "[Doodad_8DU_CityofGold_CeilingSpears011]",
			de = "Doodad_8DU_CityofGold_CeilingSpears011",
			fr = "Doodad_8DU_CityofGold_CeilingSpears011",
			it = "[Doodad_8DU_CityofGold_CeilingSpears011]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears011",
			ru = "Doodad_8DU_CityofGold_CeilingSpears011",
			ko = "Doodad_8DU_CityofGold_CeilingSpears011",
			cn = "Doodad_8DU_CityofGold_CeilingSpears011",
		},
	},
	[287353] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears012",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears012",
			es = "[Doodad_8DU_CityofGold_CeilingSpears012]",
			de = "Doodad_8DU_CityofGold_CeilingSpears012",
			fr = "Doodad_8DU_CityofGold_CeilingSpears012",
			it = "[Doodad_8DU_CityofGold_CeilingSpears012]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears012",
			ru = "Doodad_8DU_CityofGold_CeilingSpears012",
			ko = "Doodad_8DU_CityofGold_CeilingSpears012",
			cn = "Doodad_8DU_CityofGold_CeilingSpears012",
		},
	},
	[287354] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears013",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears013",
			es = "[Doodad_8DU_CityofGold_CeilingSpears013]",
			de = "Doodad_8DU_CityofGold_CeilingSpears013",
			fr = "Doodad_8DU_CityofGold_CeilingSpears013",
			it = "[Doodad_8DU_CityofGold_CeilingSpears013]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears013",
			ru = "Doodad_8DU_CityofGold_CeilingSpears013",
			ko = "Doodad_8DU_CityofGold_CeilingSpears013",
			cn = "Doodad_8DU_CityofGold_CeilingSpears013",
		},
	},
	[287355] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears014",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears014",
			es = "[Doodad_8DU_CityofGold_CeilingSpears014]",
			de = "Doodad_8DU_CityofGold_CeilingSpears014",
			fr = "Doodad_8DU_CityofGold_CeilingSpears014",
			it = "[Doodad_8DU_CityofGold_CeilingSpears014]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears014",
			ru = "Doodad_8DU_CityofGold_CeilingSpears014",
			ko = "Doodad_8DU_CityofGold_CeilingSpears014",
			cn = "Doodad_8DU_CityofGold_CeilingSpears014",
		},
	},
	[287356] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears015",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears015",
			es = "[Doodad_8DU_CityofGold_CeilingSpears015]",
			de = "Doodad_8DU_CityofGold_CeilingSpears015",
			fr = "Doodad_8DU_CityofGold_CeilingSpears015",
			it = "[Doodad_8DU_CityofGold_CeilingSpears015]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears015",
			ru = "Doodad_8DU_CityofGold_CeilingSpears015",
			ko = "Doodad_8DU_CityofGold_CeilingSpears015",
			cn = "Doodad_8DU_CityofGold_CeilingSpears015",
		},
	},
	[287357] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears016",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears016",
			es = "[Doodad_8DU_CityofGold_CeilingSpears016]",
			de = "Doodad_8DU_CityofGold_CeilingSpears016",
			fr = "Doodad_8DU_CityofGold_CeilingSpears016",
			it = "[Doodad_8DU_CityofGold_CeilingSpears016]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears016",
			ru = "Doodad_8DU_CityofGold_CeilingSpears016",
			ko = "Doodad_8DU_CityofGold_CeilingSpears016",
			cn = "Doodad_8DU_CityofGold_CeilingSpears016",
		},
	},
	[287358] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears017",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears017",
			es = "[Doodad_8DU_CityofGold_CeilingSpears017]",
			de = "Doodad_8DU_CityofGold_CeilingSpears017",
			fr = "Doodad_8DU_CityofGold_CeilingSpears017",
			it = "[Doodad_8DU_CityofGold_CeilingSpears017]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears017",
			ru = "Doodad_8DU_CityofGold_CeilingSpears017",
			ko = "Doodad_8DU_CityofGold_CeilingSpears017",
			cn = "Doodad_8DU_CityofGold_CeilingSpears017",
		},
	},
	[287359] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears018",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears018",
			es = "[Doodad_8DU_CityofGold_CeilingSpears018]",
			de = "Doodad_8DU_CityofGold_CeilingSpears018",
			fr = "Doodad_8DU_CityofGold_CeilingSpears018",
			it = "[Doodad_8DU_CityofGold_CeilingSpears018]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears018",
			ru = "Doodad_8DU_CityofGold_CeilingSpears018",
			ko = "Doodad_8DU_CityofGold_CeilingSpears018",
			cn = "Doodad_8DU_CityofGold_CeilingSpears018",
		},
	},
	[287360] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears019",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears019",
			es = "[Doodad_8DU_CityofGold_CeilingSpears019]",
			de = "Doodad_8DU_CityofGold_CeilingSpears019",
			fr = "Doodad_8DU_CityofGold_CeilingSpears019",
			it = "[Doodad_8DU_CityofGold_CeilingSpears019]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears019",
			ru = "Doodad_8DU_CityofGold_CeilingSpears019",
			ko = "Doodad_8DU_CityofGold_CeilingSpears019",
			cn = "Doodad_8DU_CityofGold_CeilingSpears019",
		},
	},
	[287361] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears020",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears020",
			es = "[Doodad_8DU_CityofGold_CeilingSpears020]",
			de = "Doodad_8DU_CityofGold_CeilingSpears020",
			fr = "Doodad_8DU_CityofGold_CeilingSpears020",
			it = "[Doodad_8DU_CityofGold_CeilingSpears020]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears020",
			ru = "Doodad_8DU_CityofGold_CeilingSpears020",
			ko = "Doodad_8DU_CityofGold_CeilingSpears020",
			cn = "Doodad_8DU_CityofGold_CeilingSpears020",
		},
	},
	[287362] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears021",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears021",
			es = "[Doodad_8DU_CityofGold_CeilingSpears021]",
			de = "Doodad_8DU_CityofGold_CeilingSpears021",
			fr = "Doodad_8DU_CityofGold_CeilingSpears021",
			it = "[Doodad_8DU_CityofGold_CeilingSpears021]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears021",
			ru = "Doodad_8DU_CityofGold_CeilingSpears021",
			ko = "Doodad_8DU_CityofGold_CeilingSpears021",
			cn = "Doodad_8DU_CityofGold_CeilingSpears021",
		},
	},
	[287363] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears022",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears022",
			es = "[Doodad_8DU_CityofGold_CeilingSpears022]",
			de = "Doodad_8DU_CityofGold_CeilingSpears022",
			fr = "Doodad_8DU_CityofGold_CeilingSpears022",
			it = "[Doodad_8DU_CityofGold_CeilingSpears022]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears022",
			ru = "Doodad_8DU_CityofGold_CeilingSpears022",
			ko = "Doodad_8DU_CityofGold_CeilingSpears022",
			cn = "Doodad_8DU_CityofGold_CeilingSpears022",
		},
	},
	[287364] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears023",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears023",
			es = "[Doodad_8DU_CityofGold_CeilingSpears023]",
			de = "Doodad_8DU_CityofGold_CeilingSpears023",
			fr = "Doodad_8DU_CityofGold_CeilingSpears023",
			it = "[Doodad_8DU_CityofGold_CeilingSpears023]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears023",
			ru = "Doodad_8DU_CityofGold_CeilingSpears023",
			ko = "Doodad_8DU_CityofGold_CeilingSpears023",
			cn = "Doodad_8DU_CityofGold_CeilingSpears023",
		},
	},
	[287365] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears024",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears024",
			es = "[Doodad_8DU_CityofGold_CeilingSpears024]",
			de = "Doodad_8DU_CityofGold_CeilingSpears024",
			fr = "Doodad_8DU_CityofGold_CeilingSpears024",
			it = "[Doodad_8DU_CityofGold_CeilingSpears024]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears024",
			ru = "Doodad_8DU_CityofGold_CeilingSpears024",
			ko = "Doodad_8DU_CityofGold_CeilingSpears024",
			cn = "Doodad_8DU_CityofGold_CeilingSpears024",
		},
	},
	[287366] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears025",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears025",
			es = "[Doodad_8DU_CityofGold_CeilingSpears025]",
			de = "Doodad_8DU_CityofGold_CeilingSpears025",
			fr = "Doodad_8DU_CityofGold_CeilingSpears025",
			it = "[Doodad_8DU_CityofGold_CeilingSpears025]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears025",
			ru = "Doodad_8DU_CityofGold_CeilingSpears025",
			ko = "Doodad_8DU_CityofGold_CeilingSpears025",
			cn = "Doodad_8DU_CityofGold_CeilingSpears025",
		},
	},
	[287367] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears026",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears026",
			es = "[Doodad_8DU_CityofGold_CeilingSpears026]",
			de = "Doodad_8DU_CityofGold_CeilingSpears026",
			fr = "Doodad_8DU_CityofGold_CeilingSpears026",
			it = "[Doodad_8DU_CityofGold_CeilingSpears026]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears026",
			ru = "Doodad_8DU_CityofGold_CeilingSpears026",
			ko = "Doodad_8DU_CityofGold_CeilingSpears026",
			cn = "Doodad_8DU_CityofGold_CeilingSpears026",
		},
	},
	[287368] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears027",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears027",
			es = "[Doodad_8DU_CityofGold_CeilingSpears027]",
			de = "Doodad_8DU_CityofGold_CeilingSpears027",
			fr = "Doodad_8DU_CityofGold_CeilingSpears027",
			it = "[Doodad_8DU_CityofGold_CeilingSpears027]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears027",
			ru = "Doodad_8DU_CityofGold_CeilingSpears027",
			ko = "Doodad_8DU_CityofGold_CeilingSpears027",
			cn = "Doodad_8DU_CityofGold_CeilingSpears027",
		},
	},
	[287369] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears028",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears028",
			es = "[Doodad_8DU_CityofGold_CeilingSpears028]",
			de = "Doodad_8DU_CityofGold_CeilingSpears028",
			fr = "Doodad_8DU_CityofGold_CeilingSpears028",
			it = "[Doodad_8DU_CityofGold_CeilingSpears028]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears028",
			ru = "Doodad_8DU_CityofGold_CeilingSpears028",
			ko = "Doodad_8DU_CityofGold_CeilingSpears028",
			cn = "Doodad_8DU_CityofGold_CeilingSpears028",
		},
	},
})
do ObjectDB[objectID] = objectData; end