local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[417381] = {
		readable = "Small Bag of Seeds",
		model = 4070769,
		text = {
			en = "Small Bag of Seeds",
			es = "[Small Bag of Seeds]",
			de = "[Small Bag of Seeds]",
			fr = "[Small Bag of Seeds]",
			it = "[Small Bag of Seeds]",
			pt = "[Small Bag of Seeds]",
			ru = "[Small Bag of Seeds]",
			ko = "[Small Bag of Seeds]",
			cn = "[Small Bag of Seeds]",
		},
	},
	[434554] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			es = "Radiant Remnant",
			de = "Radiant Remnant",
			fr = "Vestige radieux",
			it = "Radiant Remnant",
			pt = "Radiant Remnant",
			ru = "Radiant Remnant",
			ko = "Radiant Remnant",
			cn = "Radiant Remnant",
		},
	},
	[434561] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			es = "[Radiant Remnant]",
			de = "[Radiant Remnant]",
			fr = "[Radiant Remnant]",
			it = "[Radiant Remnant]",
			pt = "[Radiant Remnant]",
			ru = "[Radiant Remnant]",
			ko = "[Radiant Remnant]",
			cn = "[Radiant Remnant]",
		},
	},
	[434564] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			es = "Radiant Remnant",
			de = "Radiant Remnant",
			fr = "Vestige radieux",
			it = "Radiant Remnant",
			pt = "Radiant Remnant",
			ru = "Radiant Remnant",
			ko = "Radiant Remnant",
			cn = "Radiant Remnant",
		},
	},
	[435009] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			es = "Radiant Remnant",
			de = "Radiant Remnant",
			fr = "Radiant Remnant",
			it = "Radiant Remnant",
			pt = "Radiant Remnant",
			ru = "Radiant Remnant",
			ko = "Radiant Remnant",
			cn = "Radiant Remnant",
		},
	},
	[439473] = {
		readable = "Tenir and the Order of Night",
		model = 4298558,
		text = {
			en = "Tenir and the Order of Night",
			es = "Tenir and the Order of Night",
			de = "Tenir and the Order of Night",
			fr = "Tenir et l’Ordre de la nuit",
			it = "Tenir and the Order of Night",
			pt = "Tenir e a Ordem da Noite",
			ru = "Tenir and the Order of Night",
			ko = "Tenir and the Order of Night",
			cn = "Tenir and the Order of Night",
		},
	},
})
do ObjectDB[objectID] = objectData; end