local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[455978] = {
		readable = "Venomancer's Ink Well",
		model = 5244652,
		text = {
			en = "Venomancer's Ink Well",
			es = "[Venomancer's Ink Well]",
			de = "[Venomancer's Ink Well]",
			fr = "[Venomancer's Ink Well]",
			it = "[Venomancer's Ink Well]",
			pt = "[Venomancer's Ink Well]",
			ru = "[Venomancer's Ink Well]",
			ko = "[Venomancer's Ink Well]",
			cn = "[Venomancer's Ink Well]",
		},
	},
	[455979] = {
		readable = "Nerubian Texts",
		model = 5007027,
		text = {
			en = "Nerubian Texts",
			es = "[Nerubian Texts]",
			de = "[Nerubian Texts]",
			fr = "[Nerubian Texts]",
			it = "[Nerubian Texts]",
			pt = "[Nerubian Texts]",
			ru = "[Nerubian Texts]",
			ko = "[Nerubian Texts]",
			cn = "[Nerubian Texts]",
		},
	},
	[455980] = {
		readable = "Calligrapher's Chiselled Marker",
		model = 5175545,
		text = {
			en = "Calligrapher's Chiselled Marker",
			es = "Calligrapher's Chiselled Marker",
			de = "Gemeißelte Markierung des Kalligraphen",
			fr = "Marqueur ciselé de calligraphe",
			it = "Indicatore Cesellato del Calligrafo",
			pt = "Marcador Chanfrado do Calígrafo",
			ru = "Точная метка каллиграфа",
			ko = "서예가의 새김 표지",
			cn = "Calligrapher's Chiselled Marker",
		},
	},
	[455982] = {
		readable = "Blue Earthen Pigment",
		model = 5546882,
		text = {
			en = "Blue Earthen Pigment",
			es = "Blue Earthen Pigment",
			de = "Blue Earthen Pigment",
			fr = "Blue Earthen Pigment",
			it = "Blue Earthen Pigment",
			pt = "Corante Azul Terrano",
			ru = "Blue Earthen Pigment",
			ko = "Blue Earthen Pigment",
			cn = "Blue Earthen Pigment",
		},
	},
	[455983] = {
		readable = "Runic Scroll",
		model = 5502808,
		text = {
			en = "Runic Scroll",
			es = "Runic Scroll",
			de = "Runic Scroll",
			fr = "Runic Scroll",
			it = "Runic Scroll",
			pt = "Pergaminho Rúnico",
			ru = "Runic Scroll",
			ko = "Runic Scroll",
			cn = "Runic Scroll",
		},
	},
	[456010] = {
		readable = "Spiderling's Wire Brush",
		model = 5152459,
		text = {
			en = "Spiderling's Wire Brush",
			es = "Spiderling's Wire Brush",
			de = "Drahtbürste des Spinnlings",
			fr = "Spiderling's Wire Brush",
			it = "Spiderling's Wire Brush",
			pt = "Spiderling's Wire Brush",
			ru = "Spiderling's Wire Brush",
			ko = "Spiderling's Wire Brush",
			cn = "Spiderling's Wire Brush",
		},
	},
	[456011] = {
		readable = "Nerubian Smith's Kit",
		model = 5549342,
		text = {
			en = "Nerubian Smith's Kit",
			es = "Nerubian Smith's Kit",
			de = "Nerubische Schmiedeausrüstung",
			fr = "Nerubian Smith's Kit",
			it = "Nerubian Smith's Kit",
			pt = "Nerubian Smith's Kit",
			ru = "Nerubian Smith's Kit",
			ko = "Nerubian Smith's Kit",
			cn = "Nerubian Smith's Kit",
		},
	},
	[456012] = {
		readable = "Radiant Tongs",
		model = 5152457,
		text = {
			en = "Radiant Tongs",
			es = "Tenazas radiantes",
			de = "Strahlende Zange",
			fr = "Pinces rayonnantes",
			it = "Pinze Radiose",
			pt = "Tenazes Radiantes",
			ru = "Сияющие клещи",
			ko = "Radiant Tongs",
			cn = "Radiant Tongs",
		},
	},
	[456013] = {
		readable = "Holy Flame Forge",
		model = 5152463,
		text = {
			en = "Holy Flame Forge",
			es = "Holy Flame Forge",
			de = "Holy Flame Forge",
			fr = "Holy Flame Forge",
			it = "Holy Flame Forge",
			pt = "Holy Flame Forge",
			ru = "Holy Flame Forge",
			ko = "Holy Flame Forge",
			cn = "Holy Flame Forge",
		},
	},
	[456014] = {
		readable = "Earthen Chisels",
		model = 5175545,
		text = {
			en = "Earthen Chisels",
			es = "Earthen Chisels",
			de = "Meißel der Irdenen",
			fr = "Earthen Chisels",
			it = "Earthen Chisels",
			pt = "Cinzéis Terranos",
			ru = "Earthen Chisels",
			ko = "Earthen Chisels",
			cn = "Earthen Chisels",
		},
	},
})
do ObjectDB[objectID] = objectData; end