local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[138496] = {
		readable = "HornCover",
		model = 201468,
		text = {
			en = "HornCover",
			es = "HornCover",
			de = "Hornabdeckung",
			fr = "HornCover",
			it = "HornCover",
			pt = "CapaTrompa",
			ru = "Чехол для рогов",
			ko = "뿔피리",
			cn = "HornCover",
		},
	},
	[138497] = {
		readable = "Mouthpiece Mount",
		model = 201469,
		text = {
			en = "Mouthpiece Mount",
			es = "Soporte de boquilla",
			de = "Halterung des Mundstücks",
			fr = "Support d'embouchure",
			it = "Mouthpiece Mount",
			pt = "Montar Bocal",
			ru = "Взнузданный скакун",
			ko = "뿔피리 파이프",
			cn = "哨嘴",
		},
	},
	[139852] = {
		readable = "Memorial to Sully Balloo",
		model = 200971,
		text = {
			en = "Memorial to Sully Balloo",
			es = "Monumento a Sully Balloo",
			de = "Ehrenmal von Sully Balloo",
			fr = "Mémorial de Sully Balloo",
			it = "Monumento di Sully Balloo",
			pt = "Memorial de Floriano Caxias",
			ru = "Памятник Салли Балу",
			ko = "설리 발루의 기념비",
			cn = "苏利·巴鲁纪念碑",
		},
	},
	[140911] = {
		readable = "Spool of Light Chartreuse Silk Thread",
		model = 198131,
		text = {
			en = "Spool of Light Chartreuse Silk Thread",
			es = "Bobina de hilo de seda verde pistacho",
			de = "Rolle blassgelber Seidenfaden",
			fr = "Bobine de fil de soie chartreuse",
			it = "Rocchetta di Filo di Seta Verdastro",
			pt = "Bobina de Seda Chartreuse Leve",
			ru = "Катушка светло-оливковых шелковых ниток",
			ko = "밝은 황록색 비단 실타래",
			cn = "淡绿色丝线",
		},
	},
	[141596] = {
		readable = "Witch Doctor's Chest",
		model = 219372,
		text = {
			en = "Witch Doctor's Chest",
			es = "Cofre del médico brujo",
			de = "Hexendoktors Truhe",
			fr = "Coffre du féticheur",
			it = "Cassa del Taumaturgo",
			pt = "Baú do Mandingueiro",
			ru = "Сундук знахаря",
			ko = "의술사의 궤짝",
			cn = "巫医的箱子",
		},
	},
	[141609] = {
		readable = "Weegli's Barrel",
		model = 197463,
		text = {
			en = "Weegli's Barrel",
			es = "[Weegli's Barrel]",
			de = "[Weegli's Barrel]",
			fr = "[Weegli's Barrel]",
			it = "[Weegli's Barrel]",
			pt = "[Weegli's Barrel]",
			ru = "[Weegli's Barrel]",
			ko = "[Weegli's Barrel]",
			cn = "[Weegli's Barrel]",
		},
	},
	[141812] = {
		readable = "Stone of Binding",
		model = 201125,
		text = {
			en = "Stone of Binding",
			es = "Piedra de Vínculo",
			de = "Stein der Bindung",
			fr = "Pierre de lien",
			it = "[Stone of Binding]",
			pt = "[Stone of Binding]",
			ru = "Связывающий камень",
			ko = "봉인석",
			cn = "[Stone of Binding]",
		},
	},
	[141857] = {
		readable = "Stone of Binding",
		model = 201125,
		text = {
			en = "Stone of Binding",
			es = "Piedra de Vínculo",
			de = "Stein der Bindung",
			fr = "Pierre de lien",
			it = "[Stone of Binding]",
			pt = "[Stone of Binding]",
			ru = "Связывающий камень",
			ko = "[Stone of Binding]",
			cn = "[Stone of Binding]",
		},
	},
	[141858] = {
		readable = "Stone of Binding",
		model = 201125,
		text = {
			en = "Stone of Binding",
			es = "Piedra de Vínculo",
			de = "Stein der Bindung",
			fr = "Pierre de lien",
			it = "[Stone of Binding]",
			pt = "[Stone of Binding]",
			ru = "Связывающий камень",
			ko = "[Stone of Binding]",
			cn = "[Stone of Binding]",
		},
	},
	[141859] = {
		readable = "Stone of Binding",
		model = 201125,
		text = {
			en = "Stone of Binding",
			es = "Piedra de Vínculo",
			de = "Stein der Bindung",
			fr = "Pierre de lien",
			it = "[Stone of Binding]",
			pt = "[Stone of Binding]",
			ru = "Связывающий камень",
			ko = "[Stone of Binding]",
			cn = "[Stone of Binding]",
		},
	},
	[141860] = {
		readable = "Cannon",
		model = 200947,
		text = {
			en = "Cannon",
			es = "Cañón",
			de = "Kanone",
			fr = "Canon",
			it = "[Cannon]",
			pt = "[Cannon]",
			ru = "Пушка",
			ko = "[Cannon]",
			cn = "[Cannon]",
		},
	},
	[141861] = {
		readable = "Cannon",
		model = 200947,
		text = {
			en = "Cannon",
			es = "Cañón",
			de = "Kanone",
			fr = "Canon",
			it = "[Cannon]",
			pt = "[Cannon]",
			ru = "Пушка",
			ko = "[Cannon]",
			cn = "[Cannon]",
		},
	},
	[141862] = {
		readable = "Cannon",
		model = 200947,
		text = {
			en = "Cannon",
			es = "Cañón",
			de = "Kanone",
			fr = "Canon",
			it = "Cannone",
			pt = "Canhão",
			ru = "Пушка",
			ko = "대포",
			cn = "火炮",
		},
	},
	[141863] = {
		readable = "Cannon",
		model = 200947,
		text = {
			en = "Cannon",
			es = "Cañón",
			de = "Kanone",
			fr = "Canon",
			it = "Cannone",
			pt = "Canhão",
			ru = "Пушка",
			ko = "대포",
			cn = "火炮",
		},
	},
	[141872] = {
		readable = "Divino-matic Rod",
		model = 201056,
		text = {
			en = "Divino-matic Rod",
			es = "[Divino-matic Rod]",
			de = "[Divino-matic Rod]",
			fr = "[Divino-matic Rod]",
			it = "[Divino-matic Rod]",
			pt = "[Divino-matic Rod]",
			ru = "[Divino-matic Rod]",
			ko = "[Divino-matic Rod]",
			cn = "[Divino-matic Rod]",
		},
	},
	[141931] = {
		readable = "Hippogryph Egg",
		model = 201375,
		text = {
			en = "Hippogryph Egg",
			es = "Huevo de hipogrifo",
			de = "Hippogryphenei",
			fr = "Œuf d'hippogriffe",
			it = "Uovo di Ippogrifo",
			pt = "Ovo de Hipogrifo",
			ru = "Яйцо гиппогрифа",
			ko = "히포그리프 알",
			cn = "角鹰兽的蛋",
		},
	},
	[141980] = {
		readable = "Spectral Lockbox",
		model = 196976,
		text = {
			en = "Spectral Lockbox",
			es = "Arcón espectral",
			de = "Geisterhafte Schließkassette",
			fr = "Coffret spectral",
			it = "[Spectral Lockbox]",
			pt = "[Spectral Lockbox]",
			ru = "Призрачный сейф",
			ko = "[Spectral Lockbox]",
			cn = "[Spectral Lockbox]",
		},
	},
	[142076] = {
		readable = "Clara's Fresh Apples",
		model = 199734,
		text = {
			en = "Clara's Fresh Apples",
			es = "Manzanas Frescas de Clara",
			de = "Claras frische Äpfel",
			fr = "Pommes fraîches de Clara",
			it = "[Clara's Fresh Apples]",
			pt = "[Clara's Fresh Apples]",
			ru = "Свежие яблоки Клары",
			ko = "[Clara's Fresh Apples]",
			cn = "[Clara's Fresh Apples]",
		},
	},
	[142140] = {
		readable = "Purple Lotus",
		model = 219483,
		text = {
			en = "Purple Lotus",
			es = "Loto cárdeno",
			de = "Lila Lotus",
			fr = "Lotus pourpre",
			it = "Loto Purpureo",
			pt = "Lótus Roxo",
			ru = "Лиловый лотос",
			ko = "보라 연꽃",
			cn = "紫莲花",
		},
	},
	[142141] = {
		readable = "Arthas' Tears",
		model = 219436,
		text = {
			en = "Arthas' Tears",
			es = "Lágrimas de Arthas",
			de = "Arthas' Tränen",
			fr = "Larmes d'Arthas",
			it = "[Arthas' Tears]",
			pt = "[Arthas' Tears]",
			ru = "Слезы Артаса",
			ko = "아서스의 눈물",
			cn = "[Arthas' Tears]",
		},
	},
	[142142] = {
		readable = "Sungrass",
		model = 219496,
		text = {
			en = "Sungrass",
			es = "Solea",
			de = "Sonnengras",
			fr = "Soleillette",
			it = "Erbasole",
			pt = "Ervassol",
			ru = "Солнечник",
			ko = "태양풀",
			cn = "太阳草",
		},
	},
	[142143] = {
		readable = "Blindweed",
		model = 219438,
		text = {
			en = "Blindweed",
			es = "Carolina",
			de = "Blindkraut",
			fr = "Aveuglette",
			it = "Erbacieca",
			pt = "Ervacega",
			ru = "Пастушья сумка",
			ko = "실명초",
			cn = "盲目草",
		},
	},
	[142144] = {
		readable = "Ghost Mushroom",
		model = 219474,
		text = {
			en = "Ghost Mushroom",
			es = "Champiñón fantasma",
			de = "Geisterpilz",
			fr = "Champignon fantôme",
			it = "Fungo Fantasma",
			pt = "Cogumelo-fantasma",
			ru = "Призрачная поганка",
			ko = "유령버섯",
			cn = "幽灵菇",
		},
	},
	[142145] = {
		readable = "Gromsblood",
		model = 219464,
		text = {
			en = "Gromsblood",
			es = "Gromsanguina",
			de = "Gromsblut",
			fr = "Gromsang",
			it = "Sangue di Grommash",
			pt = "Sangue-de-grom",
			ru = "Кровь Грома",
			ko = "그롬의 피",
			cn = "格罗姆之血",
		},
	},
	[142147] = {
		readable = "Firework test",
		model = 200899,
		text = {
			en = "Firework test",
			es = "[Firework test]",
			de = "[Firework test]",
			fr = "[Firework test]",
			it = "[Firework test]",
			pt = "[Firework test]",
			ru = "[Firework test]",
			ko = "[Firework test]",
			cn = "[Firework test]",
		},
	},
	[142189] = {
		readable = "Inconspicuous Landmark",
		model = 200259,
		text = {
			en = "Inconspicuous Landmark",
			es = "Hito inadvertido",
			de = "Unauffälliger Orientierungspunkt",
			fr = "Monument dissimulé",
			it = "[Inconspicuous Landmark]",
			pt = "[Inconspicuous Landmark]",
			ru = "Не вызывающий подозрений ориентир",
			ko = "[Inconspicuous Landmark]",
			cn = "[Inconspicuous Landmark]",
		},
	},
	[142191] = {
		readable = "Horde Supply Crate",
		model = 199102,
		text = {
			en = "Horde Supply Crate",
			es = "Cajón de suministros de la Horda",
			de = "Vorratskiste der Horde",
			fr = "Caisse de ravitaillement de la Horde",
			it = "[Horde Supply Crate]",
			pt = "[Horde Supply Crate]",
			ru = "Ящик Орды с припасами",
			ko = "[Horde Supply Crate]",
			cn = "[Horde Supply Crate]",
		},
	},
	[142194] = {
		readable = "Pirate's Treasure!",
		model = 196976,
		text = {
			en = "Pirate's Treasure!",
			es = "¡Tesoro de pirata!",
			de = "Piratenschatz!",
			fr = "Trésor de pirates !",
			it = "[Pirate's Treasure!]",
			pt = "[Pirate's Treasure!]",
			ru = "Пиратское сокровище!",
			ko = "[Pirate's Treasure!]",
			cn = "[Pirate's Treasure!]",
		},
	},
	[142477] = {
		readable = "Thermaplugg's Safe",
		model = 196976,
		text = {
			en = "Thermaplugg's Safe",
			es = "Caja fuerte de Termochufe",
			de = "Thermadrahts Safe",
			fr = "Coffre de Thermojoncteur",
			it = "[Thermaplugg's Safe]",
			pt = "[Thermaplugg's Safe]",
			ru = "Предохранитель Термоштепселя",
			ko = "[Thermaplugg's Safe]",
			cn = "[Thermaplugg's Safe]",
		},
	},
	[142701] = {
		readable = "Venom Bottle",
		model = 198061,
		text = {
			en = "Venom Bottle",
			es = "[Venom Bottle]",
			de = "[Venom Bottle]",
			fr = "[Venom Bottle]",
			it = "[Venom Bottle]",
			pt = "[Venom Bottle]",
			ru = "[Venom Bottle]",
			ko = "[Venom Bottle]",
			cn = "[Venom Bottle]",
		},
	},
	[142703] = {
		readable = "Venom Bottle",
		model = 198061,
		text = {
			en = "Venom Bottle",
			es = "Botella de veneno",
			de = "Giftflasche",
			fr = "Bouteille de venin",
			it = "Bottiglia di Veleno",
			pt = "Garrafa de Peçonha",
			ru = "Флакон с ядом",
			ko = "독약병",
			cn = "毒液瓶",
		},
	},
	[142704] = {
		readable = "Venom Bottle",
		model = 198061,
		text = {
			en = "Venom Bottle",
			es = "Botella de veneno",
			de = "Giftflasche",
			fr = "Bouteille de venin",
			it = "Bottiglia di Veleno",
			pt = "Garrafa de Peçonha",
			ru = "Флакон с ядом",
			ko = "독약병",
			cn = "毒液瓶",
		},
	},
	[142705] = {
		readable = "Venom Bottle",
		model = 198061,
		text = {
			en = "Venom Bottle",
			es = "Botella de veneno",
			de = "Giftflasche",
			fr = "Bouteille de venin",
			it = "Bottiglia di Veleno",
			pt = "Garrafa de Peçonha",
			ru = "Флакон с ядом",
			ko = "독약병",
			cn = "[Venom Bottle]",
		},
	},
	[142706] = {
		readable = "Venom Bottle",
		model = 198061,
		text = {
			en = "Venom Bottle",
			es = "Botella de veneno",
			de = "Giftflasche",
			fr = "Bouteille de venin",
			it = "Bottiglia di Veleno",
			pt = "Garrafa de Peçonha",
			ru = "Флакон с ядом",
			ko = "독약병",
			cn = "[Venom Bottle]",
		},
	},
	[142707] = {
		readable = "Venom Bottle",
		model = 198061,
		text = {
			en = "Venom Bottle",
			es = "Botella de veneno",
			de = "Giftflasche",
			fr = "Bouteille de venin",
			it = "Bottiglia di Veleno",
			pt = "Garrafa de Peçonha",
			ru = "Флакон с ядом",
			ko = "독약병",
			cn = "毒液瓶",
		},
	},
	[142708] = {
		readable = "Venom Bottle",
		model = 198061,
		text = {
			en = "Venom Bottle",
			es = "[Venom Bottle]",
			de = "[Venom Bottle]",
			fr = "[Venom Bottle]",
			it = "[Venom Bottle]",
			pt = "[Venom Bottle]",
			ru = "[Venom Bottle]",
			ko = "[Venom Bottle]",
			cn = "[Venom Bottle]",
		},
	},
	[142709] = {
		readable = "Venom Bottle",
		model = 198061,
		text = {
			en = "Venom Bottle",
			es = "[Venom Bottle]",
			de = "[Venom Bottle]",
			fr = "[Venom Bottle]",
			it = "[Venom Bottle]",
			pt = "[Venom Bottle]",
			ru = "[Venom Bottle]",
			ko = "[Venom Bottle]",
			cn = "[Venom Bottle]",
		},
	},
	[142710] = {
		readable = "Venom Bottle",
		model = 198061,
		text = {
			en = "Venom Bottle",
			es = "[Venom Bottle]",
			de = "[Venom Bottle]",
			fr = "[Venom Bottle]",
			it = "[Venom Bottle]",
			pt = "[Venom Bottle]",
			ru = "Флакон с ядом",
			ko = "[Venom Bottle]",
			cn = "[Venom Bottle]",
		},
	},
	[142711] = {
		readable = "Venom Bottle",
		model = 198061,
		text = {
			en = "Venom Bottle",
			es = "[Venom Bottle]",
			de = "[Venom Bottle]",
			fr = "[Venom Bottle]",
			it = "[Venom Bottle]",
			pt = "[Venom Bottle]",
			ru = "Флакон с ядом",
			ko = "[Venom Bottle]",
			cn = "[Venom Bottle]",
		},
	},
	[142712] = {
		readable = "Venom Bottle",
		model = 198061,
		text = {
			en = "Venom Bottle",
			es = "Botella de veneno",
			de = "Giftflasche",
			fr = "Bouteille de venin",
			it = "Bottiglia di Veleno",
			pt = "Garrafa de Peçonha",
			ru = "Флакон с ядом",
			ko = "독약병",
			cn = "毒液瓶",
		},
	},
	[142713] = {
		readable = "Venom Bottle",
		model = 198061,
		text = {
			en = "Venom Bottle",
			es = "Botella de veneno",
			de = "Giftflasche",
			fr = "Bouteille de venin",
			it = "Bottiglia di Veleno",
			pt = "Garrafa de Peçonha",
			ru = "Флакон с ядом",
			ko = "독약병",
			cn = "毒液瓶",
		},
	},
	[142714] = {
		readable = "Venom Bottle",
		model = 198061,
		text = {
			en = "Venom Bottle",
			es = "Botella de veneno",
			de = "Giftflasche",
			fr = "Bouteille de venin",
			it = "Bottiglia di Veleno",
			pt = "Garrafa de Peçonha",
			ru = "Флакон с ядом",
			ko = "독약병",
			cn = "毒液瓶",
		},
	},
	[142715] = {
		readable = "Tablet of Theka",
		model = 200640,
		text = {
			en = "Tablet of Theka",
			es = "Tablilla de Theka",
			de = "Schrifttafel von Theka",
			fr = "Tablette de Theka",
			it = "Tavoletta di Theka",
			pt = "Tabuleta de Theka",
			ru = "Табличка Теки",
			ko = "데카의 서판",
			cn = "塞卡石板",
		},
	},
	[144053] = {
		readable = "Scrimshank's Surveying Gear",
		model = 197760,
		text = {
			en = "Scrimshank's Surveying Gear",
			es = "Equipo de análisis de Patagolpe",
			de = "Kieselschliffs Feldmesserausstattung",
			fr = "Equipement d'analyse de Scrimshank",
			it = "Equipaggiamento Topografico di Scrimshank",
			pt = "Aparelho de Inspeção do Anilhacido",
			ru = "Обозревательное устройство Холстомера",
			ko = "슈섕크의 측량 장비",
			cn = "[Scrimshank's Surveying Gear]",
		},
	},
	[144054] = {
		readable = "Shay's Chest",
		model = 196976,
		text = {
			en = "Shay's Chest",
			es = "Cofre de Shay",
			de = "Shays Truhe",
			fr = "Coffre de Shay",
			it = "[Shay's Chest]",
			pt = "[Shay's Chest]",
			ru = "Сундук Шаи",
			ko = "[Shay's Chest]",
			cn = "[Shay's Chest]",
		},
	},
	[144065] = {
		readable = "Explosive Charge",
		model = 200886,
		text = {
			en = "Explosive Charge",
			es = "Carga explosiva",
			de = "Sprengladung",
			fr = "Charge explosive",
			it = "Carica Esplosiva",
			pt = "Carga Explosiva",
			ru = "Взрывчатка",
			ko = "폭발물",
			cn = "爆炸品",
		},
	},
	[144070] = {
		readable = "Sharpbeak's Cage",
		model = 200937,
		text = {
			en = "Sharpbeak's Cage",
			es = "Jaula de Picoafilado",
			de = "Scharfschnabels Käfig",
			fr = "Cage de Bec-Tranchant",
			it = "Gabbia di Beccaguzzo",
			pt = "Gaiola do Bicoafiado",
			ru = "Клетка Остроклюва",
			ko = "뾰족부리의 우리",
			cn = "沙普比克的笼子",
		},
	},
	[144071] = {
		readable = "Highvale Records",
		model = 201113,
		text = {
			en = "Highvale Records",
			es = "Registros de Vallealto",
			de = "Hochtalaufzeichnungen",
			fr = "Registres du Haut-val",
			it = "[Highvale Records]",
			pt = "[Highvale Records]",
			ru = "Записи Высокодолья",
			ko = "[Highvale Records]",
			cn = "[Highvale Records]",
		},
	},
	[144072] = {
		readable = "Highvale Notes",
		model = 201113,
		text = {
			en = "Highvale Notes",
			es = "Notas de Vallealto",
			de = "Hochtalnotizen",
			fr = "Notes du Haut-val",
			it = "[Highvale Notes]",
			pt = "[Highvale Notes]",
			ru = "Заметки Высокодолья",
			ko = "[Highvale Notes]",
			cn = "[Highvale Notes]",
		},
	},
	[144073] = {
		readable = "Highvale Report",
		model = 201113,
		text = {
			en = "Highvale Report",
			es = "Informe de Vallealto",
			de = "Hochtalbericht",
			fr = "Rapport du Haut-val",
			it = "[Highvale Report]",
			pt = "[Highvale Report]",
			ru = "Отчет Высокодолья",
			ko = "[Highvale Report]",
			cn = "[Highvale Report]",
		},
	},
	[144181] = {
		readable = "Sword of the Barbarian King",
		model = 202935,
		text = {
			en = "Sword of the Barbarian King",
			es = "Espada del rey Bárbaro",
			de = "Schwert des Barbarenkönigs",
			fr = "Epée du roi barbare",
			it = "Spada del Re Barbaro",
			pt = "Espada do Rei Bárbaro",
			ru = "Меч варварского короля",
			ko = "야만용사의 검",
			cn = "蛮王之剑",
		},
	},
})
do ObjectDB[objectID] = objectData; end