local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[437060] = {
		readable = "Aspirant's Tribute",
		model = 5007034,
		text = {
			en = "Aspirant's Tribute",
			es = "Tributo del aspirante",
			de = "Tribut des Aspiranten",
			fr = "Tribut de l’aspirant",
			it = "Aspirant's Tribute",
			pt = "Tributo do Aspirante",
			ru = "Дар претендента",
			ko = "Aspirant's Tribute",
			cn = "候选者的供品",
		},
	},
	[437389] = {
		readable = "Forgotten Memorial",
		model = 4996091,
		text = {
			en = "Forgotten Memorial",
			es = "Monumento olvidado",
			de = "Vergessenes Denkmal",
			fr = "Mémorial oublié",
			it = "Memoriale Dimenticato",
			pt = "Memorial Abandonado",
			ru = "Забытый памятник",
			ko = "잊힌 기념비",
			cn = "被遗忘的纪念碑",
		},
	},
	[437767] = {
		readable = "Crate of Hallowfall Herbs",
		model = 5007037,
		text = {
			en = "Crate of Hallowfall Herbs",
			es = "Cajón de hierbas de Santificación",
			de = "Kiste voll Heilsturzkräuter",
			fr = "Caisse d’herbes de Sainte-Chute",
			it = "Cassa di Erbe dei Precipizi Sacri",
			pt = "Caixote de Plantas de Pouso Santo",
			ru = "Ящик с травами Тайносводья",
			ko = "신성한 협곡 약초 상자",
			cn = "Crate of Hallowfall Herbs",
		},
	},
	[455435] = {
		readable = "Aspirant's Tribute",
		model = 5007034,
		text = {
			en = "Aspirant's Tribute",
			es = "Tributo del aspirante",
			de = "Tribut des Aspiranten",
			fr = "Tribut de l’aspirant",
			it = "Aspirant's Tribute",
			pt = "Tributo do Aspirante",
			ru = "Дар претендента",
			ko = "Aspirant's Tribute",
			cn = "候选者的供品",
		},
	},
	[455436] = {
		readable = "Aspirant's Tribute",
		model = 5007034,
		text = {
			en = "Aspirant's Tribute",
			es = "Tributo del aspirante",
			de = "Tribut des Aspiranten",
			fr = "Tribut de l’aspirant",
			it = "Aspirant's Tribute",
			pt = "Tributo do Aspirante",
			ru = "Дар претендента",
			ko = "Aspirant's Tribute",
			cn = "候选者的供品",
		},
	},
	[455437] = {
		readable = "Aspirant's Tribute",
		model = 5007034,
		text = {
			en = "Aspirant's Tribute",
			es = "Tributo del aspirante",
			de = "Tribut des Aspiranten",
			fr = "Tribut de l’aspirant",
			it = "Aspirant's Tribute",
			pt = "Tributo do Aspirante",
			ru = "Дар претендента",
			ko = "Aspirant's Tribute",
			cn = "候选者的供品",
		},
	},
	[455439] = {
		readable = "Aspirant's Tribute",
		model = 5007034,
		text = {
			en = "Aspirant's Tribute",
			es = "Tributo del aspirante",
			de = "Tribut des Aspiranten",
			fr = "Tribut de l’aspirant",
			it = "Aspirant's Tribute",
			pt = "Tributo do Aspirante",
			ru = "Дар претендента",
			ko = "Aspirant's Tribute",
			cn = "候选者的供品",
		},
	},
	[455440] = {
		readable = "Aspirant's Tribute",
		model = 5007034,
		text = {
			en = "Aspirant's Tribute",
			es = "Tributo del aspirante",
			de = "Tribut des Aspiranten",
			fr = "Tribut de l’aspirant",
			it = "Aspirant's Tribute",
			pt = "Tributo do Aspirante",
			ru = "Дар претендента",
			ko = "Aspirant's Tribute",
			cn = "候选者的供品",
		},
	},
	[455442] = {
		readable = "Aspirant's Tribute",
		model = 5007034,
		text = {
			en = "Aspirant's Tribute",
			es = "Tributo del aspirante",
			de = "Tribut des Aspiranten",
			fr = "Tribut de l’aspirant",
			it = "Aspirant's Tribute",
			pt = "Tributo do Aspirante",
			ru = "Дар претендента",
			ko = "Aspirant's Tribute",
			cn = "候选者的供品",
		},
	},
	[455443] = {
		readable = "Aspirant's Tribute",
		model = 5007034,
		text = {
			en = "Aspirant's Tribute",
			es = "Tributo del aspirante",
			de = "Tribut des Aspiranten",
			fr = "Tribut de l’aspirant",
			it = "Aspirant's Tribute",
			pt = "Tributo do Aspirante",
			ru = "Дар претендента",
			ko = "Aspirant's Tribute",
			cn = "候选者的供品",
		},
	},
	[455444] = {
		readable = "Aspirant's Tribute",
		model = 5007034,
		text = {
			en = "Aspirant's Tribute",
			es = "Tributo del aspirante",
			de = "Tribut des Aspiranten",
			fr = "Tribut de l’aspirant",
			it = "Aspirant's Tribute",
			pt = "Tributo do Aspirante",
			ru = "Дар претендента",
			ko = "Aspirant's Tribute",
			cn = "候选者的供品",
		},
	},
	[455446] = {
		readable = "Aspirant's Tribute",
		model = 5007034,
		text = {
			en = "Aspirant's Tribute",
			es = "Tributo del aspirante",
			de = "Tribut des Aspiranten",
			fr = "Tribut de l’aspirant",
			it = "Aspirant's Tribute",
			pt = "Tributo do Aspirante",
			ru = "Дар претендента",
			ko = "Aspirant's Tribute",
			cn = "候选者的供品",
		},
	},
	[455445] = {
		readable = "Aspirant's Tribute",
		model = 5007034,
		text = {
			en = "Aspirant's Tribute",
			es = "Tributo del aspirante",
			de = "Tribut des Aspiranten",
			fr = "Tribut de l’aspirant",
			it = "Aspirant's Tribute",
			pt = "Tributo do Aspirante",
			ru = "Дар претендента",
			ko = "Aspirant's Tribute",
			cn = "候选者的供品",
		},
	},
})
do ObjectDB[objectID] = objectData; end