local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[28604] = {
		readable = "Scattered Crate",
		model = 200960,
		text = {
			en = "Scattered Crate",
			es = "Cajón destrozado",
			de = "Verstreute Kiste",
			fr = "Caisse éparpillée",
			it = "Scattered Crate",
			pt = "Scattered Crate",
			ru = "Разбитый ящик",
			ko = "Scattered Crate",
			cn = "Scattered Crate",
		},
	},
	[32569] = {
		readable = "Galen's Strongbox",
		model = 196976,
		text = {
			en = "Galen's Strongbox",
			es = "Caja fuerte de Galen",
			de = "Galens Geldkassette",
			fr = "Coffre de Galen",
			it = "Forziere di Galen",
			pt = "Cofre do Galen",
			ru = "Сейф Галена",
			ko = "갈렌의 금고",
			cn = "加林的保险箱",
		},
	},
	[404849] = {
		readable = "Dreadsquall Nest",
		model = 4532354,
		text = {
			en = "Dreadsquall Nest",
			es = "Nido de graznaterror",
			de = "Schreckenswindnest",
			fr = "Nid de corveffroi",
			it = "Nido di Nubetetra",
			pt = "Ninho de Berramedo",
			ru = "Гнездо грозного ворона",
			ko = "공포질풍 둥지",
			cn = "惧飑鸦之巢",
		},
	},
	[405593] = {
		readable = "Azerothian Archives!",
		model = 4317329,
		text = {
			en = "Azerothian Archives!",
			es = "¡Archivo de Azeroth!",
			de = "Archive von Azeroth!",
			fr = "Archives d’Azeroth !",
			it = "Archivi Azerothiani!",
			pt = "Arquivo Azerothiano!",
			ru = "Азеротские Архивы!",
			ko = "아제로스 기록 보관소!",
			cn = "艾泽拉斯档案馆！",
		},
	},
	[405943] = {
		readable = "Drakonid Scroll Case",
		model = 4298589,
		text = {
			en = "Drakonid Scroll Case",
			es = "Drakonid Scroll Case",
			de = "Drakonidischer Schriftrollenbehälter",
			fr = "Étui à parchemin drakônide",
			it = "Portapergamene Draconide",
			pt = "Estojo de Pergaminhos Draconídeo",
			ru = "Футляр для свитка драконидов",
			ko = "용기병 두루마리 보관함",
			cn = "Drakonid Scroll Case",
		},
	},
	[405996] = {
		readable = "Ancient Zaqali Trade-bond Tablet",
		model = 4420700,
		text = {
			en = "Ancient Zaqali Trade-bond Tablet",
			es = "Tablilla antigua de intercambio zaqali",
			de = "Uralte Bürgschaftstafel der Zaqali",
			fr = "Tablette de lien commercial zaqali antique",
			it = "Antica Tavoletta sul Commercio degli Zaqali",
			pt = "Tabuleta Vinculada ao Comércio Zaqali Antiga",
			ru = "Табличка древнего торговца закали",
			ko = "고대의 거래 구속 서판",
			cn = "Ancient Zaqali Trade-bond Tablet",
		},
	},
	[406383] = {
		readable = "Firelands Portal",
		model = 4640540,
		text = {
			en = "Firelands Portal",
			es = "Portal de las Tierras de Fuego",
			de = "Portal in die Feuerlande",
			fr = "Portail des terres de Feu",
			it = "Portale per le Terre del Fuoco",
			pt = "Portal das Terras do Fogo",
			ru = "Портал в Огненные Просторы",
			ko = "불의 땅 차원문",
			cn = "火焰之地传送门",
		},
	},
	[408107] = {
		readable = "Crystalline Glowblossom",
		model = 4895040,
		text = {
			en = "Crystalline Glowblossom",
			es = "Brillaflor cristalina",
			de = "Kristalline Leuchtblüte",
			fr = "Lumiflore cristalline",
			it = "Boccioluce Cristallino",
			pt = "Floraluz Cristalina",
			ru = "Кристаллический яркоцвет",
			ko = "수정 광채꽃",
			cn = "晶化莹花",
		},
	},
	[408706] = {
		readable = "Magical Bloom",
		model = 5247222,
		text = {
			en = "Magical Bloom",
			es = "Flor mágica",
			de = "Magische Blüte",
			fr = "Floraison magique",
			it = "Bocciolo Magico",
			pt = "Floração Mágica",
			ru = "Магический цветок",
			ko = "마법 꽃송이",
			cn = "魔法花朵",
		},
	},
	[408707] = {
		readable = "Odd Burl",
		model = 4255713,
		text = {
			en = "Odd Burl",
			es = "Nudo extraño",
			de = "Seltsame Knolle",
			fr = "Nœud étrange",
			it = "Strano Nodo",
			pt = "Saliência Estranha",
			ru = "Странный нарост",
			ko = "특이한 옹이",
			cn = "奇怪的树节",
		},
	},
	[408767] = {
		readable = "Dusty Bag",
		model = 4213278,
		text = {
			en = "Dusty Bag",
			es = "Dusty Bag",
			de = "Staubiger Beutel",
			fr = "Sac poussiéreux",
			it = "Dusty Bag",
			pt = "Bolsa Empoeirada",
			ru = "Пыльный мешок",
			ko = "Dusty Bag",
			cn = "Dusty Bag",
		},
	},
	[408934] = {
		readable = "Artificing Tools",
		model = 877007,
		text = {
			en = "Artificing Tools",
			es = "Artificing Tools",
			de = "Konstrukteurswerkzeuge",
			fr = "Outils d’artificier",
			it = "Artificing Tools",
			pt = "Artificing Tools",
			ru = "Инструменты механолога",
			ko = "Artificing Tools",
			cn = "Artificing Tools",
		},
	},
	[408954] = {
		readable = "Artificer's Lockbox",
		model = 875132,
		text = {
			en = "Artificer's Lockbox",
			es = "Artificer's Lockbox",
			de = "Schließkassette des Konstrukteurs",
			fr = "Artificer's Lockbox",
			it = "Artificer's Lockbox",
			pt = "Artificer's Lockbox",
			ru = "Сейф механолога",
			ko = "Artificer's Lockbox",
			cn = "Artificer's Lockbox",
		},
	},
	[408964] = {
		readable = "Satyr Totem",
		model = 1113720,
		text = {
			en = "Satyr Totem",
			es = "Satyr Totem",
			de = "Satyrtotem",
			fr = "Satyr Totem",
			it = "Satyr Totem",
			pt = "Satyr Totem",
			ru = "Тотем сатира",
			ko = "Satyr Totem",
			cn = "Satyr Totem",
		},
	},
	[408980] = {
		readable = "Tyr's Legacy",
		model = 4288162,
		text = {
			en = "Tyr's Legacy",
			es = "El legado de Tyr",
			de = "Tyrs Vermächtnis",
			fr = "L’Héritage de Tyr",
			it = "Retaggio di Tyr",
			pt = "Legado de Tyr",
			ru = "Наследие Тира",
			ko = "티르의 유산",
			cn = "提尔的遗产",
		},
	},
	[409077] = {
		readable = "Singed Leaflet",
		model = 929407,
		text = {
			en = "Singed Leaflet",
			es = "Folíolo chamuscado",
			de = "Angesengter Handzettel",
			fr = "Pamphlet roussi",
			it = "Volantino Bruciacchiato",
			pt = "Panfleto Chamuscado",
			ru = "Опаленный листок",
			ko = "그을린 유인물",
			cn = "Singed Leaflet",
		},
	},
	[409120] = {
		readable = "Cache of Cosmic Mysteries",
		model = 5338871,
		text = {
			en = "Cache of Cosmic Mysteries",
			es = "Alijo de misterios cósmicos",
			de = "Behälter voller kosmischer Mysterien",
			fr = "Cache des mystères cosmiques",
			it = "Cache of Cosmic Mysteries",
			pt = "Baú de Mistérios Cósmicos",
			ru = "Тайник космических секретов",
			ko = "우주의 수수께끼 보관함",
			cn = "Cache of Cosmic Mysteries",
		},
	},
	[409166] = {
		readable = "Titan Power Relay",
		model = 4663520,
		text = {
			en = "Titan Power Relay",
			es = "Repetidor de poder titánico",
			de = "Titanenkraftrelais",
			fr = "Relais de puissance des Titans",
			it = "Ripetitore Energetico dei Titani",
			pt = "Relé de Energia Titânica",
			ru = "Ретранслятор энергии титанов",
			ko = "티탄 동력 중계기",
			cn = "泰坦能量中继器",
		},
	},
	[409200] = {
		readable = "Broken Urn",
		model = 4609995,
		text = {
			en = "Broken Urn",
			es = "Urna rota",
			de = "Zerbrochene Urne",
			fr = "Urne brisée",
			it = "Broken Urn",
			pt = "Urna Quebrada",
			ru = "Разбитая урна",
			ko = "깨진 단지",
			cn = "破损的瓮",
		},
	},
	[409208] = {
		readable = "Broken Urn",
		model = 4609995,
		text = {
			en = "Broken Urn",
			es = "Urna rota",
			de = "Zerbrochene Urne",
			fr = "Urne brisée",
			it = "Broken Urn",
			pt = "Urna Quebrada",
			ru = "Разбитая урна",
			ko = "깨진 단지",
			cn = "破损的瓮",
		},
	},
	[409209] = {
		readable = "Broken Urn",
		model = 4609995,
		text = {
			en = "Broken Urn",
			es = "Urna rota",
			de = "Zerbrochene Urne",
			fr = "Urne brisée",
			it = "Broken Urn",
			pt = "Urna Quebrada",
			ru = "Разбитая урна",
			ko = "깨진 단지",
			cn = "破损的瓮",
		},
	},
	[409211] = {
		readable = "Broken Urn",
		model = 4609995,
		text = {
			en = "Broken Urn",
			es = "Urna rota",
			de = "Zerbrochene Urne",
			fr = "Urne brisée",
			it = "Broken Urn",
			pt = "Urna Quebrada",
			ru = "Разбитая урна",
			ko = "깨진 단지",
			cn = "破损的瓮",
		},
	},
	[409212] = {
		readable = "Broken Urn",
		model = 4609995,
		text = {
			en = "Broken Urn",
			es = "Urna rota",
			de = "Zerbrochene Urne",
			fr = "Urne brisée",
			it = "Broken Urn",
			pt = "Urna Quebrada",
			ru = "Разбитая урна",
			ko = "깨진 단지",
			cn = "破损的瓮",
		},
	},
	[409214] = {
		readable = "Broken Urn",
		model = 4609995,
		text = {
			en = "Broken Urn",
			es = "Urna rota",
			de = "Zerbrochene Urne",
			fr = "Urne brisée",
			it = "Broken Urn",
			pt = "Urna Quebrada",
			ru = "Разбитая урна",
			ko = "깨진 단지",
			cn = "破损的瓮",
		},
	},
	[409222] = {
		readable = "Boon of Ursol",
		model = 3522548,
		text = {
			en = "Boon of Ursol",
			es = "Bendición de Ursol",
			de = "Segen von Ursol",
			fr = "Bienfait d’Ursol",
			it = "Boon of Ursol",
			pt = "Bênção de Ursol",
			ru = "Дар Урсола",
			ko = "우르솔의 책",
			cn = "乌索尔的恩泽",
		},
	},
	[409320] = {
		readable = "Buried Object",
		model = 4539378,
		text = {
			en = "Buried Object",
			es = "Objeto enterrado",
			de = "Vergrabenes Objekt",
			fr = "Objet enterré",
			it = "Oggetto Sepolto",
			pt = "Objeto Enterrado",
			ru = "Закопанный предмет",
			ko = "파묻힌 물체",
			cn = "埋藏的物品",
		},
	},
	[409329] = {
		readable = "Buried Object",
		model = 4539378,
		text = {
			en = "Buried Object",
			es = "Objeto enterrado",
			de = "Vergrabenes Objekt",
			fr = "Objet enterré",
			it = "Oggetto Sepolto",
			pt = "Objeto Enterrado",
			ru = "Закопанный предмет",
			ko = "파묻힌 물체",
			cn = "埋藏的物品",
		},
	},
	[409333] = {
		readable = "Buried Object",
		model = 4539378,
		text = {
			en = "Buried Object",
			es = "Objeto enterrado",
			de = "Vergrabenes Objekt",
			fr = "Objet enterré",
			it = "Oggetto Sepolto",
			pt = "Objeto Enterrado",
			ru = "Закопанный предмет",
			ko = "파묻힌 물체",
			cn = "埋藏的物品",
		},
	},
	[409338] = {
		readable = "Washed-Up Pack",
		model = 4417702,
		text = {
			en = "Washed-Up Pack",
			es = "Mochila arrastrada a la orilla",
			de = "Angespültes Bündel",
			fr = "Sac échoué",
			it = "Zaino Affiorato",
			pt = "Pacote Acabado",
			ru = "Выброшенная на берег сумка",
			ko = "못 쓰게 된 꾸러미",
			cn = "Washed-Up Pack",
		},
	},
	[409440] = {
		readable = "Pineshrew Pile",
		model = 189528,
		text = {
			en = "Pineshrew Pile",
			es = "Montón de pinusarañas",
			de = "Pinienmaushaufen",
			fr = "Réserve de musaraigne des pins",
			it = "Pila di Soricide",
			pt = "Montinho de Ratopinho",
			ru = "Горка землехвойки",
			ko = "소나무도치 더미",
			cn = "一堆松鼩鼱",
		},
	},
	[409458] = {
		readable = "Lost Fishing Supplies",
		model = 953811,
		text = {
			en = "Lost Fishing Supplies",
			es = "Suministros de pesca perdidos",
			de = "Verlorener Angelbedarf",
			fr = "Fournitures de pêche perdues",
			it = "Forniture di Pesca Perdute",
			pt = "Suprimentos de Pesca Perdidos",
			ru = "Потерянные рыболовные снасти",
			ko = "잃어버린 낚시용품",
			cn = "失落的渔具",
		},
	},
	[409849] = {
		readable = "Ashwood Research Binder",
		model = 4914526,
		text = {
			en = "Ashwood Research Binder",
			es = "Archivador de investigación de fresno",
			de = "Eschenholzforschungsband",
			fr = "Classeur de recherches sur le frêne",
			it = "Faldone di Ricerca di Legno Secco",
			pt = "Atador de Pesquisa de Freixo",
			ru = "Папка с исследовательскими записями",
			ko = "잿빛나무 연구록",
			cn = "灰木研究活页夹",
		},
	},
	[409914] = {
		readable = "Mimiron's Booster Part",
		model = 2745106,
		text = {
			en = "Mimiron's Booster Part",
			es = "Pieza del propulsor de Mimiron",
			de = "Mimirons Boosterteil",
			fr = "Pièce du propulseur de Mimiron",
			it = "Parte di Potenziamento di Mimiron",
			pt = "Peça Propulsora de Mimiron",
			ru = "Часть усилителя Мимирона",
			ko = "미미론의 증폭기 부품",
			cn = "米米尔隆的助推器零件",
		},
	},
	[410045] = {
		readable = "Ageless Blossom",
		model = 5247212,
		text = {
			en = "Ageless Blossom",
			es = "Flor intemporal",
			de = "Alterslose Blüte",
			fr = "Fleur éternelle",
			it = "Bocciolo Senza Età",
			pt = "Flor Atemporal",
			ru = "Вековечный цветок",
			ko = "영원한 꽃",
			cn = "恒久花朵",
		},
	},
	[410046] = {
		readable = "Ageless Blossom",
		model = 5247218,
		text = {
			en = "Ageless Blossom",
			es = "Flor intemporal",
			de = "Alterslose Blüte",
			fr = "Fleur éternelle",
			it = "Bocciolo Senza Età",
			pt = "Flor Atemporal",
			ru = "Вековечный цветок",
			ko = "영원한 꽃",
			cn = "恒久花朵",
		},
	},
	[410048] = {
		readable = "Ageless Blossom",
		model = 5247222,
		text = {
			en = "Ageless Blossom",
			es = "Flor intemporal",
			de = "Alterslose Blüte",
			fr = "Fleur éternelle",
			it = "Bocciolo Senza Età",
			pt = "Flor Atemporal",
			ru = "Вековечный цветок",
			ko = "영원한 꽃",
			cn = "恒久花朵",
		},
	},
	[410426] = {
		readable = "Half-Filled Dreamless Sleep Potion",
		model = 2833934,
		text = {
			en = "Half-Filled Dreamless Sleep Potion",
			es = "Poción de letargo sin sueños a la mitad",
			de = "Halbvoller Trank des traumlosen Schlafs",
			fr = "Potion de sommeil sans rêve supérieure à moitié pleine",
			it = "Pozione Mezza Piena del Sonno Senza Sogni",
			pt = "Poção do Sono sem Sonhos pela Metade",
			ru = "Полупустое зелье сна без сновидений",
			ko = "반쯤 채운 숙면의 물약",
			cn = "装了一半的无梦睡眠药水",
		},
	},
	[410434] = {
		readable = "Splash Potion of Narcolepsy",
		model = 2833934,
		text = {
			en = "Splash Potion of Narcolepsy",
			es = "Poción salpicante de narcolepsia",
			de = "Spritztrank der Narkolepsie",
			fr = "Potion d’aspergement de narcolepsie",
			it = "Pozione a Spruzzo della Narcolessia",
			pt = "Poção Borrifante da Narcolepsia",
			ru = "Зелье всплеска нарколепсии",
			ko = "졸음병의 물보라 물약",
			cn = "飞溅昏睡药水",
		},
	},
	[410442] = {
		readable = "Root of the Problem",
		model = 4995252,
		text = {
			en = "Root of the Problem",
			es = "La raíz de los problemas",
			de = "Die Wurzel des Problems",
			fr = "Les racines du problème",
			it = "Radice del Problema",
			pt = "Raiz do Problema",
			ru = "Корень проблемы",
			ko = "문제의 뿌리",
			cn = "根本问题",
		},
	},
	[410456] = {
		readable = "Experimental Dreamcatcher",
		model = 2833991,
		text = {
			en = "Experimental Dreamcatcher",
			es = "Atrapasueños experimental",
			de = "Experimenteller Traumfänger",
			fr = "Capturêve experimental",
			it = "Acchiappasogni Sperimentale",
			pt = "Apanhador de Sonhos Experimental",
			ru = "Экспериментальный ловец снов",
			ko = "실험적인 꿈잡이",
			cn = "实验型捕梦网",
		},
	},
	[410458] = {
		readable = "Insomniotron",
		model = 2367468,
		text = {
			en = "Insomniotron",
			es = "Insomniotrón",
			de = "Schlaflositron",
			fr = "Insomniotron",
			it = "Insonniatron",
			pt = "Insoniatron",
			ru = "Бессонотрон",
			ko = "불면증 로봇",
			cn = "无眠机",
		},
	},
	[410469] = {
		readable = "Unhatched Battery",
		model = 2736566,
		text = {
			en = "Unhatched Battery",
			es = "Batería sin abrir",
			de = "Ungeschlüpfte Batterie",
			fr = "Batterie non éclose",
			it = "Batteria Non Schiusa",
			pt = "Pilha Choca",
			ru = "Непроклюнувшаяся батарея",
			ko = "개봉하지 않은 전지",
			cn = "没孵出的电池",
		},
	},
	[410475] = {
		readable = "Petrified Hope",
		model = 1037393,
		text = {
			en = "Petrified Hope",
			es = "Esperanza petrificada",
			de = "Versteinerte Hoffnung",
			fr = "Espoir pétrifié",
			it = "Speranza Pietrificata",
			pt = "Esperança Petrificada",
			ru = "Окаменевшая надежда",
			ko = "석화된 희망",
			cn = "石化希望",
		},
	},
	[410479] = {
		readable = "Unpolished Blemish",
		model = 3794106,
		text = {
			en = "Unpolished Blemish",
			es = "Defecto sin pulir",
			de = "Unpolierter Makel",
			fr = "Défaut non poli",
			it = "Imperfezione Rifinita",
			pt = "Nódoa Tosca",
			ru = "Неотполированный изъян",
			ko = "닦지 않은 잡티",
			cn = "没抛光过的瑕疵",
		},
	},
	[410484] = {
		readable = "Coalesced Dreamstone",
		model = 2438984,
		text = {
			en = "Coalesced Dreamstone",
			es = "Piedra del Sueño fusionada",
			de = "Verschmolzener Traumstein",
			fr = "Pierre onirique coalescente",
			it = "Pietra Onirica Condensata",
			pt = "Pedra dos Sonhos Coalescida",
			ru = "Сгустившийся камень снов",
			ko = "응축된 꿈결석",
			cn = "凝结的梦境石",
		},
	},
	[410529] = {
		readable = "Tuft of Dreamsaber Fur",
		model = 1334477,
		text = {
			en = "Tuft of Dreamsaber Fur",
			es = "Mechón de pelaje de sable onírico",
			de = "Büschel Traumsäblerfell",
			fr = "Touffe de poils de sabre de rêve",
			it = "Ciuffo di Pelliccia di Fieronirica",
			pt = "Tufo de Pelo de Sabre-do-sonho",
			ru = "Клок шерсти саблезуба из Сна",
			ko = "꿈표범 털 뭉치",
			cn = "一簇梦刃豹皮毛",
		},
	},
	[410534] = {
		readable = "Molted Faerie Dragon Scales",
		model = 1301126,
		text = {
			en = "Molted Faerie Dragon Scales",
			es = "Escamas de dragón feérico mudadas",
			de = "Abgeworfene Feendrachenschuppen",
			fr = "Mue d’écailles de dragon féerique",
			it = "Scaglie di Drago Fatato Fuse",
			pt = "Escamas de Muda de Dragoleta",
			ru = "Расплавленная чешуя чудесного дракончика",
			ko = "벗겨진 요정용의 비늘",
			cn = "蜕下的精灵龙之鳞",
		},
	},
	[410550] = {
		readable = "Dreamtalon Claw",
		model = 202801,
		text = {
			en = "Dreamtalon Claw",
			es = "Garra de garfasueño",
			de = "Traumkrallenklaue",
			fr = "Serre de serre de rêve",
			it = "Artiglio di Sognartiglio",
			pt = "Garra de Somnigarra",
			ru = "Коготь ящера из Сна",
			ko = "꿈갈퀴 발톱",
			cn = "梦爪獍之爪",
		},
	},
	[410574] = {
		readable = "Pure Dream Water",
		model = 4290523,
		text = {
			en = "Pure Dream Water",
			es = "Agua onírica pura",
			de = "Reines Traumwasser",
			fr = "Eau de rêve pure",
			it = "Acqua del Sogno Pura",
			pt = "Água Pura do Sonho",
			ru = "Чистая вода из Сна",
			ko = "순수한 꿈의 물",
			cn = "纯净的梦境之水",
		},
	},
	[410575] = {
		readable = "Everburning Core",
		model = 4508235,
		text = {
			en = "Everburning Core",
			es = "Núcleo de llama perpetua",
			de = "Immerflammenkern",
			fr = "Noyau semperardent",
			it = "Nucleo Inestinguibile",
			pt = "Núcleo do Ardor Perene",
			ru = "Вечнопылающий сердечник",
			ko = "영원히 타오르는 핵",
			cn = "永燃之核",
		},
	},
	[410582] = {
		readable = "Essence of Dreams",
		model = 4507691,
		text = {
			en = "Essence of Dreams",
			es = "Esencia de los sueños",
			de = "Essenz der Träume",
			fr = "Essence des rêves",
			it = "Essenza dei Sogni",
			pt = "Essência dos Sonhos",
			ru = "Сущность снов",
			ko = "꿈의 정수",
			cn = "梦境精华",
		},
	},
	[410786] = {
		readable = "Alydrus' Research Notes",
		model = 1367372,
		text = {
			en = "Alydrus' Research Notes",
			es = "Notas de investigación de Alydrus",
			de = "Alydrus' Forschungsnotizen",
			fr = "Notes de recherche d’Alydrus",
			it = "Appunti di Ricerca di Alydrus",
			pt = "Anotações de Pesquisa de Alydrus",
			ru = "Исследовательские записи Алидрии",
			ko = "Alydrus' Research Notes",
			cn = "Alydrus' Research Notes",
		},
	},
	[410833] = {
		readable = "The Reforging of the Tyr's Guard",
		model = 198017,
		text = {
			en = "The Reforging of the Tyr's Guard",
			es = "La reforja de la Guardia de Tyr",
			de = "Die Neuschmiedung von Tyrs Wache",
			fr = "Reforger la Garde de Tyr",
			it = "Riforgiatura della Guardia di Tyr",
			pt = "Reforja da Guarda de Tyr",
			ru = "Возрождение Стражей Тира",
			ko = "티르의 수호병 재결성",
			cn = "提尔近卫的重建",
		},
	},
	[410994] = {
		readable = "Map of Shadowfang Keep Security",
		model = 311986,
		text = {
			en = "Map of Shadowfang Keep Security",
			es = "Mapa de seguridad del Castillo de Colmillo Oscuro",
			de = "Karte der Sicherheitseinrichtungen von Burg Schattenfang",
			fr = "Carte de la sécurité du donjon d’Ombrecroc",
			it = "Mappa della Sicurezza del Forte di Zannascura",
			pt = "Mapa da Segurança da Bastilha da Presa Negra",
			ru = "План защиты крепости Темного Клыка",
			ko = "그림자송곳니 성채 경비 지도",
			cn = "影牙城堡安保地图",
		},
	},
	[410998] = {
		readable = "Formula: Intoxicating Toxic Perfume",
		model = 949621,
		text = {
			en = "Formula: Intoxicating Toxic Perfume",
			es = "Fórmula: perfume tóxico embriagador",
			de = "Formel: Berauschendes giftiges Parfüm",
			fr = "Formule : parfum entêtant toxique",
			it = "Formula: Profumo Tossico Inebriante",
			pt = "Fórmula: Perfume Tóxico Intoxicante",
			ru = "Формула: дурманящий ядовитый парфюм",
			ko = "주문식: 중독적인 독성 향수",
			cn = "公式：醉毒香水",
		},
	},
	[410999] = {
		readable = "Memo from Apothecary Hummel",
		model = 936413,
		text = {
			en = "Memo from Apothecary Hummel",
			es = "Nota del boticario Hummel",
			de = "Memo von Apotheker Hummel",
			fr = "Note de l’apothicaire Hummel",
			it = "Promemoria dello Speziale Hummel",
			pt = "Memorando do Boticário Humberto",
			ru = "Заметка аптекаря Хаммела",
			ko = "연금술사 훔멜의 쪽지",
			cn = "药剂师汉摩尔的备忘录",
		},
	},
	[411065] = {
		readable = "Boon of Ashamane",
		model = 3522548,
		text = {
			en = "Boon of Ashamane",
			es = "Boon of Ashamane",
			de = "Segen von Ashamane",
			fr = "Bienfait d’Ashamane",
			it = "Boon of Ashamane",
			pt = "Bênção de Ashamane",
			ru = "Дар Пеплошкурой",
			ko = "아샤메인의 은혜",
			cn = "阿莎曼的恩泽",
		},
	},
	[411066] = {
		readable = "Boon of Aviana",
		model = 3522548,
		text = {
			en = "Boon of Aviana",
			es = "Boon of Aviana",
			de = "Segen von Aviana",
			fr = "Bienfait d’Aviana",
			it = "Dono di Aviana",
			pt = "Bênção de Aviana",
			ru = "Дар Авианы",
			ko = "아비아나의 은혜",
			cn = "艾维娜的恩泽",
		},
	},
	[411067] = {
		readable = "Boon of Goldrinn",
		model = 3522548,
		text = {
			en = "Boon of Goldrinn",
			es = "Boon of Goldrinn",
			de = "Segen von Goldrinn",
			fr = "Bienfait de Goldrinn",
			it = "Boon of Goldrinn",
			pt = "Bênção de Goldrinn",
			ru = "Дар Голдринна",
			ko = "Boon of Goldrinn",
			cn = "戈德林的恩泽",
		},
	},
	[411168] = {
		readable = "Winnie's Notes on Flora and Fauna",
		model = 4298558,
		text = {
			en = "Winnie's Notes on Flora and Fauna",
			es = "Notas de Winnie sobre la flora y la fauna",
			de = "Winnies Notizen zu Flora und Fauna",
			fr = "Notes de Winnie sur la flore et la faune",
			it = "Appunti sulla Flora e sulla Fauna di Winnie",
			pt = "Observações do Puff sobre a Flora e a Fauna",
			ru = "Записки Винни о флоре и фауне",
			ko = "동식물에 관한 위니의 기록",
			cn = "威尼的动植物笔记",
		},
	},
	[411169] = {
		readable = "Grove Keeper's Pillar",
		model = 2357389,
		text = {
			en = "Grove Keeper's Pillar",
			es = "Pilar del guardián de la arboleda",
			de = "Säule des Hainhüters",
			fr = "Pilier du gardien du bosquet",
			it = "Pilastro del Custode del Bosco",
			pt = "Pilar do Guardião do Bosque",
			ru = "Колонна хранителя рощи",
			ko = "숲지기의 기둥",
			cn = "林地守护者之柱",
		},
	},
	[411170] = {
		readable = "Primalist Shadowbinding Rune",
		model = 4485591,
		text = {
			en = "Primalist Shadowbinding Rune",
			es = "Runa vinculasombras primalista",
			de = "Schattenbindungsrune der Primalisten",
			fr = "Rune d’ombrelien primaliste",
			it = "Runa del Vincolo d'Ombra Primalista",
			pt = "Runa de Grilhão de Sombra Primevista",
			ru = "Руна уз тьмы воинов стихий",
			ko = "원시술사 어둠결속 룬",
			cn = "拜荒者影缚符文",
		},
	},
	[411171] = {
		readable = "Exceedingly Soft Wildercloth",
		model = 4756260,
		text = {
			en = "Exceedingly Soft Wildercloth",
			es = "Tela salvaje extremadamente suave",
			de = "Enorm weicher Wildstoff",
			fr = "Trame-sauvage particulièrement douce",
			it = "Stoffabrada Estremamente Soffice",
			pt = "Selvatrama Extraordinariamente Macia",
			ru = "Необычайно мягкая ткань стихий",
			ko = "극도로 부드러운 야생천",
			cn = "极软的荒布",
		},
	},
	[411176] = {
		readable = "Plush Pillow",
		model = 5281468,
		text = {
			en = "Plush Pillow",
			es = "Almohada exuberante",
			de = "Flauschiges Kissen",
			fr = "Oreiller moelleux",
			it = "Cuscino Morbido",
			pt = "Travesseiro Fofinho",
			ru = "Плюшевая подушка",
			ko = "봉제 베개",
			cn = "绒枕",
		},
	},
	[411177] = {
		readable = "Snuggle Buddy",
		model = 3563973,
		text = {
			en = "Snuggle Buddy",
			es = "Coleguita peluchín",
			de = "Kuschelkumpel",
			fr = "Copain de câlin",
			it = "Compagno di Coccole",
			pt = "Abracito",
			ru = "Обнимашка",
			ko = "쿨쿨 친구",
			cn = "依偎伙伴",
		},
	},
	[411179] = {
		readable = "Amirdrassil Defender's Shield",
		model = 5157472,
		text = {
			en = "Amirdrassil Defender's Shield",
			es = "Escudo de defensor de Amirdrassil",
			de = "Schild der Verteidigerin von Amirdrassil",
			fr = "Bouclier de défenseur d’Amirdrassil",
			it = "Scudo del Difensore di Amirdrassil",
			pt = "Escudo de Defensor de Amirdrassil",
			ru = "Щит защитницы Амирдрассила",
			ko = "아미드랏실 수호병의 방패",
			cn = "阿梅达希尔防御者之盾",
		},
	},
	[411180] = {
		readable = "Deathstalker Chassis",
		model = 950715,
		text = {
			en = "Deathstalker Chassis",
			es = "Chasis de mortacechador",
			de = "Todespirscherchassis",
			fr = "Châssis de nécrotraqueur",
			it = "Telaio dell'Inseguitore della Morte",
			pt = "Chassi de Sicário",
			ru = "Каркас ловчего смерти",
			ko = "죽음추적자 골격",
			cn = "死亡猎手底盘",
		},
	},
	[411181] = {
		readable = "Flamesworn Render",
		model = 4576987,
		text = {
			en = "Flamesworn Render",
			es = "Desgarrador jurallamas",
			de = "Flammengebundener Reißer",
			fr = "Moissonneur flammelige",
			it = "Strappo del Giurafiamma",
			pt = "Dilacerador do Devoto da Chama",
			ru = "Раздиратель огненной клятвы",
			ko = "화염서약 분쇄자",
			cn = "焰誓碎裂者",
		},
	},
	[411447] = {
		readable = "Unwaking Echo",
		model = 1349621,
		text = {
			en = "Unwaking Echo",
			es = "Eco del despertar",
			de = "Nie erwachendes Echo",
			fr = "Écho non réveillé",
			it = "Eco del Non Risveglio",
			pt = "Eco Indesperto",
			ru = "Непробуждающийся отголосок",
			ko = "깨어나지 않는 메아리",
			cn = "酣眠回响",
		},
	},
	[411463] = {
		readable = "Unwaking Echo",
		model = 1349621,
		text = {
			en = "Unwaking Echo",
			es = "Eco del despertar",
			de = "Nie erwachendes Echo",
			fr = "Écho non réveillé",
			it = "Eco del Non Risveglio",
			pt = "Eco Indesperto",
			ru = "Непробуждающийся отголосок",
			ko = "깨어나지 않는 메아리",
			cn = "酣眠回响",
		},
	},
	[411465] = {
		readable = "Unwaking Echo",
		model = 1349621,
		text = {
			en = "Unwaking Echo",
			es = "Eco del despertar",
			de = "Nie erwachendes Echo",
			fr = "Écho non réveillé",
			it = "Eco del Non Risveglio",
			pt = "Eco Indesperto",
			ru = "Непробуждающийся отголосок",
			ko = "깨어나지 않는 메아리",
			cn = "酣眠回响",
		},
	},
	[411466] = {
		readable = "Unwaking Echo",
		model = 1349621,
		text = {
			en = "Unwaking Echo",
			es = "Eco del despertar",
			de = "Nie erwachendes Echo",
			fr = "Écho non réveillé",
			it = "Eco del Non Risveglio",
			pt = "Eco Indesperto",
			ru = "Непробуждающийся отголосок",
			ko = "깨어나지 않는 메아리",
			cn = "酣眠回响",
		},
	},
	[411560] = {
		readable = "Lavenbloom",
		model = 4289130,
		text = {
			en = "Lavenbloom",
			es = "Flor de lavanda",
			de = "Lavenblüte",
			fr = "Fleur de lavande",
			it = "Bocciolo di Lavanda",
			pt = "Flor de Lavanda",
			ru = "Любоцвет",
			ko = "라벤더 꽃",
			cn = "拉文之花",
		},
	},
	[411561] = {
		readable = "Sugar Orchid",
		model = 4000445,
		text = {
			en = "Sugar Orchid",
			es = "Orquídea dulce",
			de = "Zuckerorchidee",
			fr = "Orchidée en sucre",
			it = "Orchidea di Zucchero",
			pt = "Orquídea de Açúcar",
			ru = "Сахарная орхидея",
			ko = "설탕 난초",
			cn = "糖兰",
		},
	},
	[411562] = {
		readable = "Orange Illicium",
		model = 4000442,
		text = {
			en = "Orange Illicium",
			es = "Ilícium naranja",
			de = "Orangener Sternanis",
			fr = "Illicium orange",
			it = "Illicio Arancione",
			pt = "Illicium Laranja",
			ru = "Оранжевый бадьян",
			ko = "주황빛 대회향",
			cn = "橙八角",
		},
	},
	[411691] = {
		readable = "Shiny New Weapon",
		model = 4216583,
		text = {
			en = "Shiny New Weapon",
			es = "Arma nueva brillante",
			de = "Glänzende neue Waffe",
			fr = "Arme toute neuve",
			it = "Nuova Arma Lucente",
			pt = "Nova Arma Brilhante",
			ru = "Новенькое оружие",
			ko = "빛나는 새 무기",
			cn = "亮闪闪的新武器",
		},
	},
	[411778] = {
		readable = "Pollenfused Bristlebruin Fur Sample",
		model = 1334478,
		text = {
			en = "Pollenfused Bristlebruin Fur Sample",
			es = "Muestra de pelaje de erizapúas polinizado",
			de = "Pollenerfüllte Probe eines Borstenpetzpelzes",
			fr = "Échantillon de fourrure d’hoursute amalgamée de pollen",
			it = "Pollenfused Bristlebruin Fur Sample",
			pt = "Amostra de Pelo de Fuscocerdo Polenfuso",
			ru = "Образец шерсти опыленного лохматого косолапа",
			ko = "꽃가루주입 가시털불곰 모피 표본",
			cn = "Pollenfused Bristlebruin Fur Sample",
		},
	},
	[411936] = {
		readable = "Orb Location",
		model = 4485606,
		text = {
			en = "Orb Location",
			es = "Ubicación de orbe",
			de = "Kugelposition",
			fr = "Emplacement de l’orbe",
			it = "Orb Location",
			pt = "Local do Orbe",
			ru = "Местонахождение сферы",
			ko = "보주 위치",
			cn = "Orb Location",
		},
	},
	[412950] = {
		readable = "Moon-Blessed Claw",
		model = 202801,
		text = {
			en = "Moon-Blessed Claw",
			es = "Garra bendecida por la luna",
			de = "Mondgesegnete Klaue",
			fr = "Griffe bénie par la Lune",
			it = "Moon-Blessed Claw",
			pt = "Moon-Blessed Claw",
			ru = "Благословленный луной коготь",
			ko = "Moon-Blessed Claw",
			cn = "Moon-Blessed Claw",
		},
	},
	[412995] = {
		readable = "Small Box of Vials",
		model = 3917382,
		text = {
			en = "Small Box of Vials",
			es = "Caja pequeña de viales",
			de = "Kleine Schachtel mit Phiolen",
			fr = "Petite boîte de fioles",
			it = "Piccola Scatola di Fiale",
			pt = "Caixinha de Ampolas",
			ru = "Маленькая коробка с флаконами",
			ko = "작은 약병 상자",
			cn = "Small Box of Vials",
		},
	},
	[413126] = {
		readable = "Box of Artisanal Goods",
		model = 3917383,
		text = {
			en = "Box of Artisanal Goods",
			es = "Caja de bienes artesanales",
			de = "Kasten mit Handwerkswaren",
			fr = "Boîte de produits artisanaux",
			it = "Scatola di Beni Artigianali",
			pt = "Livro de Mercadorias Artesanais",
			ru = "Коробка с товарами ремесленников",
			ko = "장인 상품 상자",
			cn = "一箱工匠货物",
		},
	},
	[413774] = {
		readable = "The Legend of Elun'Ahir",
		model = 1124086,
		text = {
			en = "The Legend of Elun'Ahir",
			es = "La leyenda de Elun'ahir",
			de = "Die Legende von Elun'Ahir",
			fr = "La légende d’Élun’Ahir",
			it = "La Leggenda di Elun'ahir",
			pt = "Lenda de Elun'Ahir",
			ru = "Легенда об Элун'ахире",
			ko = "엘룬아히르의 전설",
			cn = "《艾露阿希的传说》",
		},
	},
	[413780] = {
		readable = "On the Nature of the Dream",
		model = 4861837,
		text = {
			en = "On the Nature of the Dream",
			es = "Sobre la naturaleza del Sueño",
			de = "Über das Wesen des Traums",
			fr = "De la nature du Rêve",
			it = "Sulla Natura del Sogno",
			pt = "Sobre a Natureza do Sonho",
			ru = "О природе Сна",
			ko = "꿈의 본질에 관하여",
			cn = "《论梦境的本质》",
		},
	},
	[413787] = {
		readable = "The Tragedy of Erinethria",
		model = 4861836,
		text = {
			en = "The Tragedy of Erinethria",
			es = "La tragedia de Erinethria",
			de = "Die Tragödie von Erinethria",
			fr = "La tragédie d’Érinéthria",
			it = "La Tragedia di Erinehria",
			pt = "A Tragédia de Erinethria",
			ru = "Трагедия Эринетрии",
			ko = "에리네스리아의 비극",
			cn = "《艾莉涅希亚的悲剧》",
		},
	},
	[414169] = {
		readable = "Mysterious Seeds",
		model = 902296,
		text = {
			en = "Mysterious Seeds",
			es = "Semillas misteriosas",
			de = "Geheimnisvolle Samen",
			fr = "Graines mystérieuses",
			it = "Semi Misteriosi",
			pt = "Sementes Misteriosas",
			ru = "Таинственные семена",
			ko = "신비한 씨앗",
			cn = "神秘之种",
		},
	},
	[415303] = {
		readable = "Magically-Sealed Parcel",
		model = 903887,
		text = {
			en = "Magically-Sealed Parcel",
			es = "Magically-Sealed Parcel",
			de = "Magisch versiegeltes Paket",
			fr = "Colis scellé par magie",
			it = "Magically-Sealed Parcel",
			pt = "Magically-Sealed Parcel",
			ru = "Посылка с магической печатью",
			ko = "Magically-Sealed Parcel",
			cn = "Magically-Sealed Parcel",
		},
	},
	[416448] = {
		readable = "Lush Lavenbloom",
		model = 4289130,
		text = {
			en = "Lush Lavenbloom",
			es = "Flor de lavanda exuberante",
			de = "Üppige Lavenblüte",
			fr = "Fleur de lavande luxuriante",
			it = "Bocciolo di Lavanda Rigoglioso",
			pt = "Flor de Lavanda Exuberante",
			ru = "Зрелый любоцвет",
			ko = "무성한 라벤더 꽃",
			cn = "繁茂的拉文之花",
		},
	},
	[416450] = {
		readable = "Lush Orange Illicium",
		model = 4000442,
		text = {
			en = "Lush Orange Illicium",
			es = "Ilícium naranja exuberante",
			de = "Üppiger orangener Sternanis",
			fr = "Illicium orange luxuriant",
			it = "Illicio Arancione Rigoglioso",
			pt = "Illicium Laranja Exuberante",
			ru = "Зрелый оранжевый бадьян",
			ko = "무성한 주황빛 대회향",
			cn = "繁茂的橙八角",
		},
	},
	[420019] = {
		readable = "Artificing Tools",
		model = 875382,
		text = {
			en = "Artificing Tools",
			es = "Artificing Tools",
			de = "Konstrukteurswerkzeuge",
			fr = "Outils d’artificière",
			it = "Artificing Tools",
			pt = "Artificing Tools",
			ru = "Инструменты механолога",
			ko = "Artificing Tools",
			cn = "Artificing Tools",
		},
	},
	[420039] = {
		readable = "Artificing Tools",
		model = 875382,
		text = {
			en = "Artificing Tools",
			es = "Artificing Tools",
			de = "Konstrukteurswerkzeuge",
			fr = "Outils d’artificière",
			it = "Artificing Tools",
			pt = "Artificing Tools",
			ru = "Инструменты механолога",
			ko = "Artificing Tools",
			cn = "Artificing Tools",
		},
	},
	[420040] = {
		readable = "Artificing Tools",
		model = 877007,
		text = {
			en = "Artificing Tools",
			es = "Artificing Tools",
			de = "Konstrukteurswerkzeuge",
			fr = "Outils d’artificière",
			it = "Artificing Tools",
			pt = "Artificing Tools",
			ru = "Инструменты механолога",
			ko = "Artificing Tools",
			cn = "Artificing Tools",
		},
	},
	[420195] = {
		readable = "Golden Egg Heirloom",
		model = 5456991,
		text = {
			en = "Golden Egg Heirloom",
			es = "Golden Egg Heirloom",
			de = "Golden Egg Heirloom",
			fr = "Golden Egg Heirloom",
			it = "Golden Egg Heirloom",
			pt = "Golden Egg Heirloom",
			ru = "Golden Egg Heirloom",
			ko = "Golden Egg Heirloom",
			cn = "Golden Egg Heirloom",
		},
	},
	[421179] = {
		readable = "Kaldorei Bedroll",
		model = 4756260,
		text = {
			en = "Kaldorei Bedroll",
			es = "Saco de dormir kaldorei",
			de = "Kaldoreischlafsack",
			fr = "Sac de couchage kaldorei",
			it = "Futon dei Kaldorei",
			pt = "Saco de Dormir Kaldorei",
			ru = "Калдорайская походная постель",
			ko = "칼도레이 침낭",
			cn = "Kaldorei Bedroll",
		},
	},
	[421180] = {
		readable = "Kaldorei Backpack",
		model = 5489255,
		text = {
			en = "Kaldorei Backpack",
			es = "Mochila kaldorei",
			de = "Kaldoreirucksack",
			fr = "Sac à dos kaldorei",
			it = "Zaino dei Kaldorei",
			pt = "Mochila Kaldorei",
			ru = "Калдорайский рюкзак",
			ko = "칼도레이 배낭",
			cn = "Kaldorei Backpack",
		},
	},
	[421181] = {
		readable = "Kaldorei Dagger",
		model = 5489281,
		text = {
			en = "Kaldorei Dagger",
			es = "Daga kaldorei",
			de = "Kaldoreidolch",
			fr = "Dague kaldorei",
			it = "Pugnale dei Kaldorei",
			pt = "Adaga Kaldorei",
			ru = "Калдорайский кинжал",
			ko = "칼도레이 단검",
			cn = "Kaldorei Dagger",
		},
	},
	[421182] = {
		readable = "Kaldorei Horn",
		model = 5489269,
		text = {
			en = "Kaldorei Horn",
			es = "Cuerno kaldorei",
			de = "Kaldoreihorn",
			fr = "Corne kaldorei",
			it = "Corno dei Kaldorei",
			pt = "Chifre Kaldorei",
			ru = "Калдорайский рог",
			ko = "칼도레이 뿔피리",
			cn = "Kaldorei Horn",
		},
	},
	[421183] = {
		readable = "Kaldorei Bag",
		model = 5489282,
		text = {
			en = "Kaldorei Bag",
			es = "Bolsa kaldorei",
			de = "Kaldoreitasche",
			fr = "Sac kaldorei",
			it = "Borsa dei Kaldorei",
			pt = "Bolsa Kaldorei",
			ru = "Калдорайская сумка",
			ko = "칼도레이 가방",
			cn = "Kaldorei Bag",
		},
	},
	[421184] = {
		readable = "Kaldorei Shield",
		model = 5489286,
		text = {
			en = "Kaldorei Shield",
			es = "Escudo kaldorei",
			de = "Kaldoreischild",
			fr = "Bouclier kaldorei",
			it = "Scudo dei Kaldorei",
			pt = "Escudo Kaldorei",
			ru = "Калдорайский щит",
			ko = "칼도레이 방패",
			cn = "Kaldorei Shield",
		},
	},
	[421185] = {
		readable = "Kaldorei Spear",
		model = 5489285,
		text = {
			en = "Kaldorei Spear",
			es = "Lanza kaldorei",
			de = "Kaldoreispeer",
			fr = "Lance kaldorei",
			it = "Lancia dei Kaldorei",
			pt = "Lança Kaldorei",
			ru = "Калдорайское копье",
			ko = "칼도레이 창",
			cn = "Kaldorei Spear",
		},
	},
	[421186] = {
		readable = "Kaldorei Spyglass",
		model = 5489284,
		text = {
			en = "Kaldorei Spyglass",
			es = "Catalejo kaldorei",
			de = "Kaldoreifernrohr",
			fr = "Longue-vue kaldorei",
			it = "Cannocchiale dei Kaldorei",
			pt = "Luneta Kaldorei",
			ru = "Калдорайская подзорная труба",
			ko = "칼도레이 망원경",
			cn = "Kaldorei Spyglass",
		},
	},
	[421338] = {
		readable = "Kaldorei Bag",
		model = 5489283,
		text = {
			en = "Kaldorei Bag",
			es = "Bolsa kaldorei",
			de = "Kaldoreitasche",
			fr = "Sac kaldorei",
			it = "Borsa dei Kaldorei",
			pt = "Bolsa Kaldorei",
			ru = "Калдорайская сумка",
			ko = "칼도레이 가방",
			cn = "Kaldorei Bag",
		},
	},
	[421339] = {
		readable = "Kaldorei Horn",
		model = 5489270,
		text = {
			en = "Kaldorei Horn",
			es = "Cuerno kaldorei",
			de = "Kaldoreihorn",
			fr = "Corne kaldorei",
			it = "Corno dei Kaldorei",
			pt = "Chifre Kaldorei",
			ru = "Калдорайский рог",
			ko = "칼도레이 뿔피리",
			cn = "Kaldorei Horn",
		},
	},
	[421360] = {
		readable = "Memorial Bouquet",
		model = 5282331,
		text = {
			en = "Memorial Bouquet",
			es = "Ramo conmemorativo",
			de = "Denkstättengebinde",
			fr = "Gerbe du souvenir",
			it = "Bouquet Commemorativo",
			pt = "Memorial Bouquet",
			ru = "Букет на памятник",
			ko = "추모의 꽃다발",
			cn = "Memorial Bouquet",
		},
	},
	[421555] = {
		readable = "Kaldorei Moon Bow",
		model = 2133380,
		text = {
			en = "Kaldorei Moon Bow",
			es = "Arco lunar kaldorei",
			de = "Kaldoreimondbogen",
			fr = "Arc de lune kaldorei",
			it = "Arco della Luna dei Kaldorei",
			pt = "Arco Lunar Kaldorei",
			ru = "Калдорайский лунный лук",
			ko = "칼도레이 달의 활",
			cn = "Kaldorei Moon Bow",
		},
	},
	[421718] = {
		readable = "Dragon Pepe",
		model = 5155018,
		text = {
			en = "Dragon Pepe",
			es = "Pepe dragón",
			de = "Pepe der Drache",
			fr = "Pépé le Dragon",
			it = "Pepe Drago",
			pt = "Pepe Dragão",
			ru = "Дракон Пепе",
			ko = "용 피프",
			cn = "巨龙佩佩",
		},
	},
	[421736] = {
		readable = "Explorer Pepe",
		model = 5155017,
		text = {
			en = "Explorer Pepe",
			es = "Pepe expedicionario",
			de = "Pepe der Entdecker",
			fr = "Pépé l’explorateur",
			it = "Pepe Esploratore",
			pt = "Pepe Explorador",
			ru = "Исследователь Пепе",
			ko = "탐험가 피프",
			cn = "探索者佩佩",
		},
	},
	[421740] = {
		readable = "Tuskarr Pepe",
		model = 5155016,
		text = {
			en = "Tuskarr Pepe",
			es = "Pepe colmillarr",
			de = "Pepe der Tuskarr",
			fr = "Pépé le Rohart",
			it = "Pepe Tuskarr",
			pt = "Pepe Morsano",
			ru = "Клыкарр Пепе",
			ko = "투스카르 피프",
			cn = "海象人佩佩",
		},
	},
	[424098] = {
		readable = "Golden Egg Heirloom",
		model = 5456991,
		text = {
			en = "Golden Egg Heirloom",
			es = "Golden Egg Heirloom",
			de = "Golden Egg Heirloom",
			fr = "Golden Egg Heirloom",
			it = "Golden Egg Heirloom",
			pt = "Golden Egg Heirloom",
			ru = "Golden Egg Heirloom",
			ko = "Golden Egg Heirloom",
			cn = "Golden Egg Heirloom",
		},
	},
})
do ObjectDB[objectID] = objectData; end