local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[430337] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			es = "Remanente radiante",
			de = "Strahlendes Überbleibsel",
			fr = "Vestige radieux",
			it = "Radiant Remnant",
			pt = "Resquício Radiante",
			ru = "Сияющие останки",
			ko = "Radiant Remnant",
			cn = "Radiant Remnant",
			tw = "Radiant Remnant",
		},
	},
	[430340] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			es = "Remanente radiante",
			de = "Strahlendes Überbleibsel",
			fr = "Vestige radieux",
			it = "Residuo Radioso",
			pt = "Resquício Radiante",
			ru = "Сияющие останки",
			ko = "Radiant Remnant",
			cn = "光耀残渣",
			tw = "Radiant Remnant",
		},
	},
	[430342] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			es = "Remanente radiante",
			de = "Strahlendes Überbleibsel",
			fr = "Vestige radieux",
			it = "Residuo Radioso",
			pt = "Resquício Radiante",
			ru = "Сияющие останки",
			ko = "Radiant Remnant",
			cn = "Radiant Remnant",
			tw = "Radiant Remnant",
		},
	},
	[430343] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			es = "Remanente radiante",
			de = "Strahlendes Überbleibsel",
			fr = "Vestige radieux",
			it = "Residuo Radioso",
			pt = "Resquício Radiante",
			ru = "Сияющие останки",
			ko = "Radiant Remnant",
			cn = "光耀残渣",
			tw = "Radiant Remnant",
		},
	},
	[454543] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			es = "Remanente radiante",
			de = "Strahlendes Überbleibsel",
			fr = "Vestige radieux",
			it = "Residuo Radioso",
			pt = "Resquício Radiante",
			ru = "Сияющие останки",
			ko = "광휘의 잔재",
			cn = "光耀残渣",
			tw = "Radiant Remnant",
		},
	},
})
do ObjectDB[objectID] = objectData; end