local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[441555] = {
		readable = "Wax-Drenched Sign",
		model = 198493,
		text = {
			en = "Wax-Drenched Sign",
			es = "Wax-Drenched Sign",
			de = "Wax-Drenched Sign",
			fr = "Wax-Drenched Sign",
			it = "Wax-Drenched Sign",
			pt = "Wax-Drenched Sign",
			ru = "Wax-Drenched Sign",
			ko = "Wax-Drenched Sign",
			cn = "Wax-Drenched Sign",
		},
	},
	[441563] = {
		readable = "Submerged Sign",
		model = 198493,
		text = {
			en = "Submerged Sign",
			es = "Submerged Sign",
			de = "Submerged Sign",
			fr = "Submerged Sign",
			it = "Submerged Sign",
			pt = "Submerged Sign",
			ru = "Submerged Sign",
			ko = "Submerged Sign",
			cn = "Submerged Sign",
		},
	},
	[441577] = {
		readable = "Warning: Collapsed Tunnel",
		model = 198493,
		text = {
			en = "Warning: Collapsed Tunnel",
			es = "Warning: Collapsed Tunnel",
			de = "Warning: Collapsed Tunnel",
			fr = "Warning: Collapsed Tunnel",
			it = "Warning: Collapsed Tunnel",
			pt = "Warning: Collapsed Tunnel",
			ru = "Warning: Collapsed Tunnel",
			ko = "Warning: Collapsed Tunnel",
			cn = "Warning: Collapsed Tunnel",
		},
	},
	[441578] = {
		readable = "Kobold Warning Sign",
		model = 198493,
		text = {
			en = "Kobold Warning Sign",
			es = "Kobold Warning Sign",
			de = "Kobold Warning Sign",
			fr = "Kobold Warning Sign",
			it = "Kobold Warning Sign",
			pt = "Kobold Warning Sign",
			ru = "Kobold Warning Sign",
			ko = "Kobold Warning Sign",
			cn = "Kobold Warning Sign",
		},
	},
	[455958] = {
		readable = "Regenerating Ore",
		text = {
			en = "Regenerating Ore",
			es = "Regenerating Ore",
			de = "Regenerating Ore",
			fr = "Regenerating Ore",
			it = "Regenerating Ore",
			pt = "Regenerating Ore",
			ru = "Regenerating Ore",
			ko = "Regenerating Ore",
			cn = "Regenerating Ore",
		},
	},
	[455959] = {
		readable = "Earthen Excavator's Shovel",
		text = {
			en = "Earthen Excavator's Shovel",
			es = "Earthen Excavator's Shovel",
			de = "Earthen Excavator's Shovel",
			fr = "Earthen Excavator's Shovel",
			it = "Earthen Excavator's Shovel",
			pt = "Earthen Excavator's Shovel",
			ru = "Earthen Excavator's Shovel",
			ko = "Earthen Excavator's Shovel",
			cn = "Earthen Excavator's Shovel",
		},
	},
	[455990] = {
		readable = "Fungarian Slicer's Knife",
		text = {
			en = "Fungarian Slicer's Knife",
			es = "Fungarian Slicer's Knife",
			de = "Fungarian Slicer's Knife",
			fr = "Fungarian Slicer's Knife",
			it = "Fungarian Slicer's Knife",
			pt = "Fungarian Slicer's Knife",
			ru = "Fungarian Slicer's Knife",
			ko = "Fungarian Slicer's Knife",
			cn = "Fungarian Slicer's Knife",
		},
	},
	[455991] = {
		readable = "Earthen Digging Fork",
		text = {
			en = "Earthen Digging Fork",
			es = "Earthen Digging Fork",
			de = "Earthen Digging Fork",
			fr = "Earthen Digging Fork",
			it = "Earthen Digging Fork",
			pt = "Earthen Digging Fork",
			ru = "Earthen Digging Fork",
			ko = "Earthen Digging Fork",
			cn = "Earthen Digging Fork",
		},
	},
})
do ObjectDB[objectID] = objectData; end