local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[454037] = {
		readable = "Stolen Supplies",
		model = 5048188,
		text = {
			en = "Stolen Supplies",
			es = "[Stolen Supplies]",
			de = "[Stolen Supplies]",
			fr = "[Stolen Supplies]",
			it = "[Stolen Supplies]",
			pt = "[Stolen Supplies]",
			ru = "[Stolen Supplies]",
			ko = "[Stolen Supplies]",
			cn = "[Stolen Supplies]",
		},
	},
	[454038] = {
		readable = "Stolen Supplies",
		model = 5048188,
		text = {
			en = "Stolen Supplies",
			es = "[Stolen Supplies]",
			de = "[Stolen Supplies]",
			fr = "[Stolen Supplies]",
			it = "[Stolen Supplies]",
			pt = "[Stolen Supplies]",
			ru = "[Stolen Supplies]",
			ko = "[Stolen Supplies]",
			cn = "[Stolen Supplies]",
		},
	},
	[454039] = {
		readable = "Stolen Supplies",
		model = 5048188,
		text = {
			en = "Stolen Supplies",
			es = "[Stolen Supplies]",
			de = "[Stolen Supplies]",
			fr = "[Stolen Supplies]",
			it = "[Stolen Supplies]",
			pt = "[Stolen Supplies]",
			ru = "[Stolen Supplies]",
			ko = "[Stolen Supplies]",
			cn = "[Stolen Supplies]",
		},
	},
	[455485] = {
		readable = "|cff1EFF00Sturdy Chest",
		model = 5128194,
		text = {
			en = "|cff1EFF00Sturdy Chest",
			es = "|cff1EFF00Cofre robusto",
			de = "|cff1EFF00Robuste Truhe",
			fr = "|cff1EFF00Coffre solide",
			it = "|cff1EFF00Cassa Resistente",
			pt = "|cff1EFF00Baú Resistente",
			ru = "|cff1EFF00Прочный сундук",
			ko = "|cff1EFF00Sturdy Chest",
			cn = "|cff1EFF00Sturdy Chest",
		},
	},
})
do ObjectDB[objectID] = objectData; end