local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[434527] = {
		readable = "Thimble's Cache",
		text = {
			en = "Thimble's Cache",
			es = "Thimble's Cache",
			de = "Thimble's Cache",
			fr = "Thimble's Cache",
			it = "Thimble's Cache",
			pt = "Thimble's Cache",
			ru = "Thimble's Cache",
			ko = "Thimble's Cache",
			cn = "Thimble's Cache",
		},
	},
	[453167] = {
		readable = "Disturbed Lynx Treasure",
		text = {
			en = "Disturbed Lynx Treasure",
			es = "Disturbed Lynx Treasure",
			de = "Disturbed Lynx Treasure",
			fr = "Disturbed Lynx Treasure",
			it = "Disturbed Lynx Treasure",
			pt = "Disturbed Lynx Treasure",
			ru = "Disturbed Lynx Treasure",
			ko = "Disturbed Lynx Treasure",
			cn = "Disturbed Lynx Treasure",
		},
	},
	[454331] = {
		readable = "Thimble's Cache",
		text = {
			en = "Thimble's Cache",
			es = "Thimble's Cache",
			de = "Thimble's Cache",
			fr = "Thimble's Cache",
			it = "Thimble's Cache",
			pt = "Thimble's Cache",
			ru = "Thimble's Cache",
			ko = "Thimble's Cache",
			cn = "Thimble's Cache",
		},
	},
	[455506] = {
		readable = "Sturdy Chest",
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			de = "Sturdy Chest",
			fr = "Sturdy Chest",
			it = "Sturdy Chest",
			pt = "Sturdy Chest",
			ru = "Sturdy Chest",
			ko = "Sturdy Chest",
			cn = "Sturdy Chest",
		},
	},
	[455531] = {
		readable = "Sturdy Chest",
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			de = "Sturdy Chest",
			fr = "Sturdy Chest",
			it = "Sturdy Chest",
			pt = "Sturdy Chest",
			ru = "Sturdy Chest",
			ko = "Sturdy Chest",
			cn = "Sturdy Chest",
		},
	},
})
do ObjectDB[objectID] = objectData; end