local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[401723] = {
		readable = "Candy Bucket",
		model = 200946,
		text = {
			en = "Candy Bucket",
			es = "Cubo de caramelos",
			de = "Eimer mit Süßigkeiten",
			fr = "Un seau de bonbons",
			it = "Secchio delle Caramelle",
			pt = "Balde de Doces",
			ru = "Кулек конфет",
			ko = "사탕 바구니",
			cn = "糖罐",
			tw = "Candy Bucket",
		},
	},
	[401724] = {
		readable = "Candy Bucket",
		model = 200946,
		text = {
			en = "Candy Bucket",
			es = "Cubo de caramelos",
			de = "Eimer mit Süßigkeiten",
			fr = "Un seau de bonbons",
			it = "Secchio delle Caramelle",
			pt = "Balde de Doces",
			ru = "Кулек конфет",
			ko = "사탕 바구니",
			cn = "糖罐",
			tw = "Candy Bucket",
		},
	},
	[401725] = {
		readable = "Candy Bucket",
		model = 200946,
		text = {
			en = "Candy Bucket",
			es = "Cubo de caramelos",
			de = "Eimer mit Süßigkeiten",
			fr = "Un seau de bonbons",
			it = "Secchio delle Caramelle",
			pt = "Balde de Doces",
			ru = "Кулек конфет",
			ko = "사탕 바구니",
			cn = "糖罐",
			tw = "Candy Bucket",
		},
	},
	[401726] = {
		readable = "Candy Bucket",
		model = 200946,
		text = {
			en = "Candy Bucket",
			es = "Cubo de caramelos",
			de = "Eimer mit Süßigkeiten",
			fr = "Un seau de bonbons",
			it = "Secchio delle Caramelle",
			pt = "Balde de Doces",
			ru = "Кулек конфет",
			ko = "사탕 바구니",
			cn = "糖罐",
			tw = "Candy Bucket",
		},
	},
	[401727] = {
		readable = "Candy Bucket",
		model = 200946,
		text = {
			en = "Candy Bucket",
			es = "Cubo de caramelos",
			de = "Eimer mit Süßigkeiten",
			fr = "Un seau de bonbons",
			it = "Secchio delle Caramelle",
			pt = "Balde de Doces",
			ru = "Кулек конфет",
			ko = "사탕 바구니",
			cn = "糖罐",
			tw = "Candy Bucket",
		},
	},
	[401728] = {
		readable = "Candy Bucket",
		model = 200946,
		text = {
			en = "Candy Bucket",
			es = "Cubo de caramelos",
			de = "Eimer mit Süßigkeiten",
			fr = "Un seau de bonbons",
			it = "Secchio delle Caramelle",
			pt = "Balde de Doces",
			ru = "Кулек конфет",
			ko = "사탕 바구니",
			cn = "糖罐",
			tw = "Candy Bucket",
		},
	},
	[401729] = {
		readable = "Candy Bucket",
		model = 200946,
		text = {
			en = "Candy Bucket",
			es = "Cubo de caramelos",
			de = "Eimer mit Süßigkeiten",
			fr = "Un seau de bonbons",
			it = "Secchio delle Caramelle",
			pt = "Balde de Doces",
			ru = "Кулек конфет",
			ko = "사탕 바구니",
			cn = "糖罐",
			tw = "Candy Bucket",
		},
	},
	[401730] = {
		readable = "Candy Bucket",
		model = 200946,
		text = {
			en = "Candy Bucket",
			es = "Cubo de caramelos",
			de = "Eimer mit Süßigkeiten",
			fr = "Un seau de bonbons",
			it = "Secchio delle Caramelle",
			pt = "Balde de Doces",
			ru = "Кулек конфет",
			ko = "사탕 바구니",
			cn = "糖罐",
			tw = "Candy Bucket",
		},
	},
	[401731] = {
		readable = "Candy Bucket",
		model = 200946,
		text = {
			en = "Candy Bucket",
			es = "Cubo de caramelos",
			de = "Eimer mit Süßigkeiten",
			fr = "Un seau de bonbons",
			it = "Secchio delle Caramelle",
			pt = "Balde de Doces",
			ru = "Кулек конфет",
			ko = "사탕 바구니",
			cn = "糖罐",
			tw = "Candy Bucket",
		},
	},
	[401732] = {
		readable = "Candy Bucket",
		model = 200946,
		text = {
			en = "Candy Bucket",
			es = "Cubo de caramelos",
			de = "Eimer mit Süßigkeiten",
			fr = "Un seau de bonbons",
			it = "Secchio delle Caramelle",
			pt = "Balde de Doces",
			ru = "Кулек конфет",
			ko = "사탕 바구니",
			cn = "糖罐",
			tw = "Candy Bucket",
		},
	},
	[401733] = {
		readable = "Candy Bucket",
		model = 200946,
		text = {
			en = "Candy Bucket",
			es = "Cubo de caramelos",
			de = "Eimer mit Süßigkeiten",
			fr = "Un seau de bonbons",
			it = "Secchio delle Caramelle",
			pt = "Balde de Doces",
			ru = "Кулек конфет",
			ko = "사탕 바구니",
			cn = "糖罐",
			tw = "Candy Bucket",
		},
	},
	[401734] = {
		readable = "Candy Bucket",
		model = 200946,
		text = {
			en = "Candy Bucket",
			es = "Cubo de caramelos",
			de = "Eimer mit Süßigkeiten",
			fr = "Un seau de bonbons",
			it = "Secchio delle Caramelle",
			pt = "Balde de Doces",
			ru = "Кулек конфет",
			ko = "사탕 바구니",
			cn = "糖罐",
			tw = "Candy Bucket",
		},
	},
	[401735] = {
		readable = "Candy Bucket",
		model = 200946,
		text = {
			en = "Candy Bucket",
			es = "Cubo de caramelos",
			de = "Eimer mit Süßigkeiten",
			fr = "Un seau de bonbons",
			it = "Secchio delle Caramelle",
			pt = "Balde de Doces",
			ru = "Кулек конфет",
			ko = "사탕 바구니",
			cn = "糖罐",
			tw = "Candy Bucket",
		},
	},
	[401736] = {
		readable = "Candy Bucket",
		model = 200946,
		text = {
			en = "Candy Bucket",
			es = "Cubo de caramelos",
			de = "Eimer mit Süßigkeiten",
			fr = "Un seau de bonbons",
			it = "Secchio delle Caramelle",
			pt = "Balde de Doces",
			ru = "Кулек конфет",
			ko = "사탕 바구니",
			cn = "糖罐",
			tw = "Candy Bucket",
		},
	},
	[401737] = {
		readable = "Candy Bucket",
		model = 200946,
		text = {
			en = "Candy Bucket",
			es = "Cubo de caramelos",
			de = "Eimer mit Süßigkeiten",
			fr = "Un seau de bonbons",
			it = "Secchio delle Caramelle",
			pt = "Balde de Doces",
			ru = "Кулек конфет",
			ko = "사탕 바구니",
			cn = "糖罐",
			tw = "Candy Bucket",
		},
	},
	[401738] = {
		readable = "Candy Bucket",
		model = 200946,
		text = {
			en = "Candy Bucket",
			es = "Cubo de caramelos",
			de = "Eimer mit Süßigkeiten",
			fr = "Un seau de bonbons",
			it = "Secchio delle Caramelle",
			pt = "Balde de Doces",
			ru = "Кулек конфет",
			ko = "사탕 바구니",
			cn = "糖罐",
			tw = "Candy Bucket",
		},
	},
	[401739] = {
		readable = "Candy Bucket",
		model = 200946,
		text = {
			en = "Candy Bucket",
			es = "Cubo de caramelos",
			de = "Eimer mit Süßigkeiten",
			fr = "Un seau de bonbons",
			it = "Secchio delle Caramelle",
			pt = "Balde de Doces",
			ru = "Кулек конфет",
			ko = "사탕 바구니",
			cn = "糖罐",
			tw = "Candy Bucket",
		},
	},
	[401740] = {
		readable = "Candy Bucket",
		model = 200946,
		text = {
			en = "Candy Bucket",
			es = "Cubo de caramelos",
			de = "Eimer mit Süßigkeiten",
			fr = "Un seau de bonbons",
			it = "Secchio delle Caramelle",
			pt = "Balde de Doces",
			ru = "Кулек конфет",
			ko = "사탕 바구니",
			cn = "糖罐",
			tw = "Candy Bucket",
		},
	},
	[401741] = {
		readable = "Candy Bucket",
		model = 200946,
		text = {
			en = "Candy Bucket",
			es = "Cubo de caramelos",
			de = "Eimer mit Süßigkeiten",
			fr = "Un seau de bonbons",
			it = "Secchio delle Caramelle",
			pt = "Balde de Doces",
			ru = "Кулек конфет",
			ko = "사탕 바구니",
			cn = "糖罐",
			tw = "Candy Bucket",
		},
	},
	[401742] = {
		readable = "Candy Bucket",
		model = 200946,
		text = {
			en = "Candy Bucket",
			es = "Cubo de caramelos",
			de = "Eimer mit Süßigkeiten",
			fr = "Un seau de bonbons",
			it = "Secchio delle Caramelle",
			pt = "Balde de Doces",
			ru = "Кулек конфет",
			ko = "사탕 바구니",
			cn = "糖罐",
			tw = "Candy Bucket",
		},
	},
	[401743] = {
		readable = "Candy Bucket",
		model = 200946,
		text = {
			en = "Candy Bucket",
			es = "Cubo de caramelos",
			de = "Eimer mit Süßigkeiten",
			fr = "Un seau de bonbons",
			it = "Secchio delle Caramelle",
			pt = "Balde de Doces",
			ru = "Кулек конфет",
			ko = "사탕 바구니",
			cn = "糖罐",
			tw = "Candy Bucket",
		},
	},
	[401744] = {
		readable = "Candy Bucket",
		model = 200946,
		text = {
			en = "Candy Bucket",
			es = "Cubo de caramelos",
			de = "Eimer mit Süßigkeiten",
			fr = "Un seau de bonbons",
			it = "Secchio delle Caramelle",
			pt = "Balde de Doces",
			ru = "Кулек конфет",
			ko = "사탕 바구니",
			cn = "糖罐",
			tw = "Candy Bucket",
		},
	},
	[401745] = {
		readable = "Candy Bucket",
		model = 200946,
		text = {
			en = "Candy Bucket",
			es = "Cubo de caramelos",
			de = "Eimer mit Süßigkeiten",
			fr = "Un seau de bonbons",
			it = "Secchio delle Caramelle",
			pt = "Balde de Doces",
			ru = "Кулек конфет",
			ko = "사탕 바구니",
			cn = "糖罐",
			tw = "Candy Bucket",
		},
	},
	[401746] = {
		readable = "Candy Bucket",
		model = 200946,
		text = {
			en = "Candy Bucket",
			es = "Cubo de caramelos",
			de = "Eimer mit Süßigkeiten",
			fr = "Un seau de bonbons",
			it = "Secchio delle Caramelle",
			pt = "Balde de Doces",
			ru = "Кулек конфет",
			ko = "사탕 바구니",
			cn = "糖罐",
			tw = "Candy Bucket",
		},
	},
	[401747] = {
		readable = "Candy Bucket",
		model = 200946,
		text = {
			en = "Candy Bucket",
			es = "Cubo de caramelos",
			de = "Eimer mit Süßigkeiten",
			fr = "Un seau de bonbons",
			it = "Secchio delle Caramelle",
			pt = "Balde de Doces",
			ru = "Кулек конфет",
			ko = "사탕 바구니",
			cn = "糖罐",
			tw = "Candy Bucket",
		},
	},
	[401748] = {
		readable = "Candy Bucket",
		model = 200946,
		text = {
			en = "Candy Bucket",
			es = "Cubo de caramelos",
			de = "Eimer mit Süßigkeiten",
			fr = "Un seau de bonbons",
			it = "Secchio delle Caramelle",
			pt = "Balde de Doces",
			ru = "Кулек конфет",
			ko = "사탕 바구니",
			cn = "糖罐",
			tw = "Candy Bucket",
		},
	},
	[401749] = {
		readable = "Candy Bucket",
		model = 200946,
		text = {
			en = "Candy Bucket",
			es = "Cubo de caramelos",
			de = "Eimer mit Süßigkeiten",
			fr = "Un seau de bonbons",
			it = "Secchio delle Caramelle",
			pt = "Balde de Doces",
			ru = "Кулек конфет",
			ko = "사탕 바구니",
			cn = "糖罐",
			tw = "Candy Bucket",
		},
	},
	[401750] = {
		readable = "Candy Bucket",
		model = 200946,
		text = {
			en = "Candy Bucket",
			es = "Cubo de caramelos",
			de = "Eimer mit Süßigkeiten",
			fr = "Un seau de bonbons",
			it = "Secchio delle Caramelle",
			pt = "Balde de Doces",
			ru = "Кулек конфет",
			ko = "사탕 바구니",
			cn = "糖罐",
			tw = "Candy Bucket",
		},
	},
	[401751] = {
		readable = "Candy Bucket",
		model = 200946,
		text = {
			en = "Candy Bucket",
			es = "Cubo de caramelos",
			de = "Eimer mit Süßigkeiten",
			fr = "Un seau de bonbons",
			it = "Secchio delle Caramelle",
			pt = "Balde de Doces",
			ru = "Кулек конфет",
			ko = "사탕 바구니",
			cn = "糖罐",
			tw = "Candy Bucket",
		},
	},
	[401753] = {
		readable = "Candy Bucket",
		model = 200946,
		text = {
			en = "Candy Bucket",
			es = "Cubo de caramelos",
			de = "Eimer mit Süßigkeiten",
			fr = "Un seau de bonbons",
			it = "Secchio delle Caramelle",
			pt = "Balde de Doces",
			ru = "Кулек конфет",
			ko = "사탕 바구니",
			cn = "糖罐",
			tw = "Candy Bucket",
		},
	},
	[401754] = {
		readable = "Candy Bucket",
		model = 200946,
		text = {
			en = "Candy Bucket",
			es = "Cubo de caramelos",
			de = "Eimer mit Süßigkeiten",
			fr = "Un seau de bonbons",
			it = "Secchio delle Caramelle",
			pt = "Balde de Doces",
			ru = "Кулек конфет",
			ko = "사탕 바구니",
			cn = "糖罐",
			tw = "Candy Bucket",
		},
	},
	[401755] = {
		readable = "Candy Bucket",
		model = 200946,
		text = {
			en = "Candy Bucket",
			es = "Cubo de caramelos",
			de = "Eimer mit Süßigkeiten",
			fr = "Un seau de bonbons",
			it = "Secchio delle Caramelle",
			pt = "Balde de Doces",
			ru = "Кулек конфет",
			ko = "Candy Bucket",
			cn = "糖罐",
			tw = "Candy Bucket",
		},
	},
	[401756] = {
		readable = "Candy Bucket",
		model = 200946,
		text = {
			en = "Candy Bucket",
			es = "Cubo de caramelos",
			de = "Eimer mit Süßigkeiten",
			fr = "Un seau de bonbons",
			it = "Secchio delle Caramelle",
			pt = "Balde de Doces",
			ru = "Кулек конфет",
			ko = "사탕 바구니",
			cn = "糖罐",
			tw = "Candy Bucket",
		},
	},
	[401757] = {
		readable = "Candy Bucket",
		model = 200946,
		text = {
			en = "Candy Bucket",
			es = "Cubo de caramelos",
			de = "Eimer mit Süßigkeiten",
			fr = "Un seau de bonbons",
			it = "Secchio delle Caramelle",
			pt = "Balde de Doces",
			ru = "Кулек конфет",
			ko = "사탕 바구니",
			cn = "糖罐",
			tw = "Candy Bucket",
		},
	},
	[407048] = {
		readable = "Candy Bucket",
		model = 200946,
		text = {
			en = "Candy Bucket",
			es = "Cubo de caramelos",
			de = "Eimer mit Süßigkeiten",
			fr = "Un seau de bonbons",
			it = "Secchio delle Caramelle",
			pt = "Balde de Doces",
			ru = "Кулек конфет",
			ko = "사탕 바구니",
			cn = "糖罐",
			tw = "Candy Bucket",
		},
	},
})
do ObjectDB[objectID] = objectData; end