local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[386691] = {
		readable = "Library Book",
		model = 198017,
		text = {
			en = "Library Book",
			es = "[Library Book]",
			de = "Bibliotheksbuch",
			fr = "Livre de la bibliothèque",
			it = "[Library Book]",
			pt = "[Library Book]",
			ru = "Книга из библиотеки",
			ko = "[Library Book]",
			cn = "图书馆书籍",
		},
	},
	[386759] = {
		readable = "Library Book",
		model = 198036,
		text = {
			en = "Library Book",
			es = "Libro de la biblioteca",
			de = "Bibliotheksbuch",
			fr = "Livre de la bibliothèque",
			it = "[Library Book]",
			pt = "[Library Book]",
			ru = "Книга из библиотеки",
			ko = "도서관 책",
			cn = "图书馆书籍",
		},
	},
	[405149] = {
		readable = "Mural of Ta'zo",
		model = 200337,
		text = {
			en = "Mural of Ta'zo",
			es = "Mural de Ta'zo",
			de = "Wandgemälde von Ta'zo",
			fr = "Fresque de Ta’zo",
			it = "[Mural of Ta'zo]",
			pt = "[Mural of Ta'zo]",
			ru = "Фреска с Та'зо",
			ko = "타조의 벽화",
			cn = "塔佐的浮雕",
		},
	},
	[405879] = {
		readable = "Apothecary Society Primer",
		model = 198025,
		text = {
			en = "Apothecary Society Primer",
			es = "Manual de la Sociedad de Boticarios",
			de = "Fibel der Apothekervereinigung",
			fr = "Manuel de la Société des apothicaires",
			it = "[Apothecary Society Primer]",
			pt = "Cartilha da Sociedade dos Boticários",
			ru = "Ученик фармацевтического общества",
			ko = "왕실 연금술 학회 지침서",
			cn = "药剂师的会社读本",
		},
	},
	[407566] = {
		readable = "Goblin Tome",
		model = 198039,
		text = {
			en = "Goblin Tome",
			es = "Tomo goblin",
			de = "Goblinfoliant",
			fr = "Tome gobelin",
			it = "[Goblin Tome]",
			pt = "[Goblin Tome]",
			ru = "Гоблинская книга",
			ko = "고블린어 고서",
			cn = "地精魔典",
		},
	},
	[408014] = {
		readable = "Gnomish Tome",
		model = 198039,
		text = {
			en = "Gnomish Tome",
			es = "Tomo gnómico",
			de = "Gnomenfoliant",
			fr = "Tome gnome",
			it = "[Gnomish Tome]",
			pt = "Tomo Gnômico",
			ru = "Гномья книга",
			ko = "노움어 고서",
			cn = "[Gnomish Tome]",
		},
	},
	[409496] = {
		readable = "Scrolls",
		model = 198453,
		text = {
			en = "Scrolls",
			es = "[Scrolls]",
			de = "Schriftrollen",
			fr = "Parchemins",
			it = "[Scrolls]",
			pt = "[Scrolls]",
			ru = "Свитки",
			ko = "[Scrolls]",
			cn = "[Scrolls]",
		},
	},
	[409501] = {
		readable = "Dalaran Digest",
		model = 198036,
		text = {
			en = "Dalaran Digest",
			es = "Compendio de Dalaran",
			de = "Dalaranauswahl",
			fr = "Abrégé de Dalaran",
			it = "[Dalaran Digest]",
			pt = "[Dalaran Digest]",
			ru = "[Dalaran Digest]",
			ko = "[Dalaran Digest]",
			cn = "[Dalaran Digest]",
		},
	},
	[409692] = {
		readable = "Scrolls",
		model = 198453,
		text = {
			en = "Scrolls",
			es = "Pergaminos",
			de = "Schriftrollen",
			fr = "Parchemins",
			it = "[Scrolls]",
			pt = "[Scrolls]",
			ru = "Свитки",
			ko = "두루마리",
			cn = "卷轴",
		},
	},
	[409700] = {
		readable = "Manual",
		model = 198039,
		text = {
			en = "Manual",
			es = "Manual",
			de = "Handbuch",
			fr = "Manuel",
			it = "[Manual]",
			pt = "[Manual]",
			ru = "Руководство",
			ko = "[Manual]",
			cn = "[Manual]",
		},
	},
	[409711] = {
		readable = "Scrolls",
		model = 198452,
		text = {
			en = "Scrolls",
			es = "[Scrolls]",
			de = "Schriftrollen",
			fr = "Parchemins",
			it = "[Scrolls]",
			pt = "[Scrolls]",
			ru = "Свитки",
			ko = "두루마리",
			cn = "[Scrolls]",
		},
	},
	[409717] = {
		readable = "Scrolls",
		model = 198453,
		text = {
			en = "Scrolls",
			es = "Pergaminos",
			de = "Schriftrollen",
			fr = "Parchemins",
			it = "[Scrolls]",
			pt = "[Scrolls]",
			ru = "[Scrolls]",
			ko = "[Scrolls]",
			cn = "[Scrolls]",
		},
	},
	[409731] = {
		readable = "Scrolls",
		model = 198453,
		text = {
			en = "Scrolls",
			es = "[Scrolls]",
			de = "Schriftrollen",
			fr = "Parchemins",
			it = "[Scrolls]",
			pt = "[Scrolls]",
			ru = "Свитки",
			ko = "두루마리",
			cn = "[Scrolls]",
		},
	},
	[409735] = {
		readable = "Spellbook",
		model = 198038,
		text = {
			en = "Spellbook",
			es = "[Spellbook]",
			de = "Zauberbuch",
			fr = "Grimoire",
			it = "[Spellbook]",
			pt = "[Spellbook]",
			ru = "Книга заклинаний",
			ko = "[Spellbook]",
			cn = "[Spellbook]",
		},
	},
	[410299] = {
		readable = "Arcane Secrets",
		model = 198039,
		text = {
			en = "Arcane Secrets",
			es = "Secretos Arcanos",
			de = "Arkane Geheimnisse",
			fr = "Secrets arcaniques",
			it = "[Arcane Secrets]",
			pt = "[Arcane Secrets]",
			ru = "Секреты тайной магии",
			ko = "[Arcane Secrets]",
			cn = "[Arcane Secrets]",
		},
	},
})
do ObjectDB[objectID] = objectData; end