local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[444261] = {
		readable = "Purchase Bluesberry Blast - 5 Silver",
		model = 200936,
		text = {
			en = "Purchase Bluesberry Blast - 5 Silver",
			es = "Comprar bomba de bayazul - 5 de plata",
			de = "Blaubeerenexplosion kaufen - 5 Silber",
			fr = "Acheter du Banana Bam : 5 pièces d’argent",
			it = "Acquista Bomba al Mirtillo - 5 Argento",
			pt = "Comprar Bomba de Mirtilo - 5 de Prata",
			ru = "Купить \"Черничный чемпион\" – 5 серебра",
			ko = "생푸른열매 작렬 구매 - 5 실버",
			cn = "购买蓝莓轰击 - 5银币",
			tw = "Purchase Bluesberry Blast - 5 Silver",
		},
	},
	[444275] = {
		readable = "Purchase Mangoro Madness - 5 Silver",
		model = 200936,
		text = {
			en = "Purchase Mangoro Madness - 5 Silver",
			es = "Comprar majadería de mangoro - 5 de plata",
			de = "Mangorowahnsinn kaufen - 5 Silber",
			fr = "Acheter du Mangoro Mania : 5 pièces d’argent",
			it = "Acquista Mangoro Mania - 5 Argento",
			pt = "Comprar Maluquice de Mangoro - 5 de Prata",
			ru = "Купить \"Манифест Ман'Горо\" – 5 серебра",
			ko = "팡당팡당 망고 도취 구매 - 5 실버",
			cn = "购买曼古鲁之狂 - 5银币",
			tw = "Purchase Mangoro Madness - 5 Silver",
		},
	},
	[444276] = {
		readable = "Purchase Orange O-pocalypse - 5 Silver",
		model = 200936,
		text = {
			en = "Purchase Orange O-pocalypse - 5 Silver",
			es = "Comprar napalm de naranja - 5 de plata",
			de = "Ultraorange kaufen - 5 Silber",
			fr = "Acheter de l’Orange O-pocalypse : 5 pièces d’argent",
			it = "Acquista O-pocalisse all'Arancia - 5 Argento",
			pt = "Comprar O-pocalipse de Laranja - 5 de Prata",
			ru = "Купить \"Апельсиновый апокалипсис\" – 5 серебра",
			ko = "각성의 오렌지 구매 - 5 실버",
			cn = "购买香橙启示录 - 5银币",
			tw = "Purchase Orange O-pocalypse - 5 Silver",
		},
	},
	[444277] = {
		readable = "Purchase Oyster Outbreak - 5 Silver",
		model = 200936,
		text = {
			en = "Purchase Oyster Outbreak - 5 Silver",
			es = "Comprar oleada de ostras - 5 de plata",
			de = "Meeresausbruch kaufen - 5 Silber",
			fr = "Acheter de l’Urtic’Huître : 5 pièces d’argent",
			it = "Acquista Ostricola- 5 Argento",
			pt = "Comprar Ostra O-strondosa - 5 de Prata",
			ru = "Купить \"Устричную усладу\" – 5 серебра",
			ko = "팡파짐 굴 폭탄 - 5 실버",
			cn = "购买牡蛎爆发 - 5银币",
			tw = "Purchase Oyster Outbreak - 5 Silver",
		},
	},
})
do ObjectDB[objectID] = objectData; end