local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[123214] = {
		readable = "Duskwood Chest",
		model = 196979,
		text = {
			en = "Duskwood Chest",
			es = "Cofre de Bosque del Ocaso",
			de = "Dämmerwaldtruhe",
			fr = "Coffre du bois de la Pénombre",
			it = "[Duskwood Chest]",
			pt = "[Duskwood Chest]",
			ru = "Сундук Сумеречного леса",
			ko = "[Duskwood Chest]",
			cn = "[Duskwood Chest]",
		},
	},
	[123228] = {
		readable = "Containment Coffer TEST",
		model = 201014,
		text = {
			en = "Containment Coffer TEST",
			es = "[Containment Coffer TEST]",
			de = "[Containment Coffer TEST]",
			fr = "[Containment Coffer TEST]",
			it = "[Containment Coffer TEST]",
			pt = "[Containment Coffer TEST]",
			ru = "[Containment Coffer TEST]",
			ko = "[Containment Coffer TEST]",
			cn = "[Containment Coffer TEST]",
		},
	},
	[123308] = {
		readable = "Ooze Covered Arcanite Lode",
		model = 219553,
		text = {
			en = "Ooze Covered Arcanite Lode",
			es = "[Ooze Covered Arcanite Lode]",
			de = "[Ooze Covered Arcanite Lode]",
			fr = "[Ooze Covered Arcanite Lode]",
			it = "[Ooze Covered Arcanite Lode]",
			pt = "[Ooze Covered Arcanite Lode]",
			ru = "[Ooze Covered Arcanite Lode]",
			ko = "[Ooze Covered Arcanite Lode]",
			cn = "[Ooze Covered Arcanite Lode]",
		},
	},
	[123309] = {
		readable = "Ooze Covered Truesilver Deposit",
		model = 219553,
		text = {
			en = "Ooze Covered Truesilver Deposit",
			es = "Depósito de veraplata cubierta de moco",
			de = "Schlammbedecktes Echtsilbervorkommen",
			fr = "Gisement de vrai-argent couvert de vase",
			it = "Deposito di Verargento Coperto di Melma",
			pt = "Depósito de Veraprata Coberto de Gosma",
			ru = "Покрытые слизью залежи истинного серебра",
			ko = "[Ooze Covered Truesilver Deposit]",
			cn = "[Ooze Covered Truesilver Deposit]",
		},
	},
	[123310] = {
		readable = "Ooze Covered Mithril Deposit",
		model = 219553,
		text = {
			en = "Ooze Covered Mithril Deposit",
			es = "Depósito de mitril cubierto de moco",
			de = "Schlammbedeckte Mithrilablagerung",
			fr = "Gisement de mithril couvert de vase",
			it = "[Ooze Covered Mithril Deposit]",
			pt = "[Ooze Covered Mithril Deposit]",
			ru = "Покрытые слизью мифриловые залежи",
			ko = "[Ooze Covered Mithril Deposit]",
			cn = "[Ooze Covered Mithril Deposit]",
		},
	},
	[123311] = {
		readable = "Thieves' Tool Rack",
		model = 189204,
		text = {
			en = "Thieves' Tool Rack",
			es = "[Thieves' Tool Rack]",
			de = "[Thieves' Tool Rack]",
			fr = "[Thieves' Tool Rack]",
			it = "[Thieves' Tool Rack]",
			pt = "[Thieves' Tool Rack]",
			ru = "[Thieves' Tool Rack]",
			ko = "[Thieves' Tool Rack]",
			cn = "[Thieves' Tool Rack]",
		},
	},
	[123330] = {
		readable = "Buccaneer's Strongbox",
		model = 196976,
		text = {
			en = "Buccaneer's Strongbox",
			es = "Caja fuerte de bucanero",
			de = "Geldkassette des Bukaniers",
			fr = "Coffre du boucanier",
			it = "Forziere del Bucaniere",
			pt = "Caixa-forte dos Bucaneiros",
			ru = "Сейф буканьера",
			ko = "해적의 금고",
			cn = "海盗的保险箱",
		},
	},
	[123331] = {
		readable = "Buccaneer's Strongbox",
		model = 196976,
		text = {
			en = "Buccaneer's Strongbox",
			es = "Caja fuerte de bucanero",
			de = "Geldkassette des Bukaniers",
			fr = "Coffre du boucanier",
			it = "[Buccaneer's Strongbox]",
			pt = "Caixa-forte dos Bucaneiros",
			ru = "Сейф буканьера",
			ko = "해적의 금고",
			cn = "海盗的保险箱",
		},
	},
	[123332] = {
		readable = "Buccaneer's Strongbox",
		model = 196976,
		text = {
			en = "Buccaneer's Strongbox",
			es = "Caja fuerte de bucanero",
			de = "Geldkassette des Bukaniers",
			fr = "Coffre du boucanier",
			it = "Forziere del Bucaniere",
			pt = "Caixa-forte dos Bucaneiros",
			ru = "Сейф буканьера",
			ko = "해적의 금고",
			cn = "[Buccaneer's Strongbox]",
		},
	},
	[123333] = {
		readable = "Buccaneer's Strongbox",
		model = 196976,
		text = {
			en = "Buccaneer's Strongbox",
			es = "Caja fuerte de bucanero",
			de = "Geldkassette des Bukaniers",
			fr = "Coffre du boucanier",
			it = "[Buccaneer's Strongbox]",
			pt = "Caixa-forte dos Bucaneiros",
			ru = "Сейф буканьера",
			ko = "[Buccaneer's Strongbox]",
			cn = "[Buccaneer's Strongbox]",
		},
	},
	[123461] = {
		readable = "Ironforge",
		model = 197044,
		text = {
			en = "Ironforge",
			es = "[Ironforge]",
			de = "[Ironforge]",
			fr = "[Ironforge]",
			it = "[Ironforge]",
			pt = "[Ironforge]",
			ru = "[Ironforge]",
			ko = "[Ironforge]",
			cn = "[Ironforge]",
		},
	},
	[123462] = {
		readable = "The Jewel of the Southsea",
		model = 196982,
		text = {
			en = "The Jewel of the Southsea",
			es = "La joya de los Mares del Sur",
			de = "Das Juwel der Südlichen Meere",
			fr = "Le Joyau des mers du Sud",
			it = "Il Gioiello di Mari del Sud",
			pt = "A Joia dos Mares do Sul",
			ru = "Драгоценный камень Южных морей",
			ko = "남쪽바다 해적단 보석",
			cn = "南海宝珠",
		},
	},
	[123463] = {
		readable = "Baelog's Journal",
		model = 200913,
		text = {
			en = "Baelog's Journal",
			es = "Diario de Baelog",
			de = "Baelogs Tagebuch",
			fr = "Journal de Baelog",
			it = "Diario di Baelog",
			pt = "Diário de Baelog",
			ru = "Дневник Бейлога",
			ko = "밸로그의 일지",
			cn = "巴尔洛戈的日记",
		},
	},
	[123468] = {
		readable = "Teleport to Violet Stand",
		model = 194232,
		text = {
			en = "Teleport to Violet Stand",
			es = "[Teleport to Violet Stand ]",
			de = "[Teleport to Violet Stand ]",
			fr = "[Teleport to Violet Stand ]",
			it = "[Teleport to Violet Stand ]",
			pt = "[Teleport to Violet Stand ]",
			ru = "[Teleport to Violet Stand ]",
			ko = "[Teleport to Violet Stand ]",
			cn = "[Teleport to Violet Stand ]",
		},
	},
	[123469] = {
		readable = "Teleport to Dalaran",
		model = 194232,
		text = {
			en = "Teleport to Dalaran",
			es = "[Teleport to Dalaran]",
			de = "[Teleport to Dalaran]",
			fr = "[Teleport to Dalaran]",
			it = "[Teleport to Dalaran]",
			pt = "[Teleport to Dalaran]",
			ru = "[Teleport to Dalaran]",
			ko = "[Teleport to Dalaran]",
			cn = "[Teleport to Dalaran]",
		},
	},
	[123848] = {
		readable = "Ooze Covered Thorium Vein",
		model = 219553,
		text = {
			en = "Ooze Covered Thorium Vein",
			es = "Filón de torio cubierto de moco",
			de = "Schlammbedeckte Thoriumader",
			fr = "Filon de thorium couvert de limon",
			it = "Vena di Torio Coperta di Melma",
			pt = "Veio de Tório Coberto de Gosma",
			ru = "Покрытая слизью ториевая жила",
			ko = "진흙으로 덮인 토륨 광맥",
			cn = "软泥覆盖的瑟银矿脉",
		},
	},
	[124374] = {
		readable = "Horatio Montgomery, M.D.",
		model = 190929,
		text = {
			en = "Horatio Montgomery, M.D.",
			es = "Horatio Montgomery, M.D.",
			de = "Dr. Horatio Montgomery",
			fr = "Horatio Montgomery, médecin",
			it = "Horatio Montgomery, M.D.",
			pt = "Doutor Horacio Monteiro",
			ru = "Доктор Горацио Монтгомери",
			ko = "호레이쇼 몽고메리, M.D.",
			cn = "霍拉迪·蒙特高莫，医学博士",
		},
	},
	[128293] = {
		readable = "Magenta Cap Clusters",
		model = 201860,
		text = {
			en = "Magenta Cap Clusters",
			es = "Setas magenta",
			de = "Magenta Kappengruppen",
			fr = "Champignons magenta",
			it = "Funghi Magenta",
			pt = "Colônia de Campânulas Magenta",
			ru = "Семейка грибов-малиновиков",
			ko = "자홍버섯",
			cn = "紫色蘑菇",
		},
	},
	[128308] = {
		readable = "Shallow Grave",
		model = 201032,
		text = {
			en = "Shallow Grave",
			es = "Tumba poco profunda",
			de = "Flaches Grab",
			fr = "Tombe peu profonde",
			it = "Loculo Dissacrato",
			pt = "Cova Rasa",
			ru = "Неглубокая могила",
			ko = "얕은 무덤",
			cn = "浅墓穴",
		},
	},
	[128403] = {
		readable = "Shallow Grave",
		model = 201032,
		text = {
			en = "Shallow Grave",
			es = "Tumba poco profunda",
			de = "Flaches Grab",
			fr = "Tombe peu profonde",
			it = "Loculo Dissacrato",
			pt = "Cova Rasa",
			ru = "Неглубокая могила",
			ko = "얕은 무덤",
			cn = "浅墓穴",
		},
	},
	[131978] = {
		readable = "Large Mithril Bound Chest",
		model = 219372,
		text = {
			en = "Large Mithril Bound Chest",
			es = "Cofre reforzado con mitril grande",
			de = "Große mithrilbeschlagene Truhe",
			fr = "Grand coffre cerclé de mithril",
			it = "Grossa Cassa Rinforzata di Ferro",
			pt = "Baú Grande Reforçado com Mithril",
			ru = "Окованный мифрилом большой сундук",
			ko = "큰 미스릴 궤짝",
			cn = "大型秘银储物箱",
		},
	},
	[133737] = {
		readable = "Event's Portal",
		model = 197042,
		text = {
			en = "Event's Portal",
			es = "[Event's Portal]",
			de = "[Event's Portal]",
			fr = "[Event's Portal]",
			it = "[Event's Portal]",
			pt = "[Event's Portal]",
			ru = "[Event's Portal]",
			ko = "[Event's Portal]",
			cn = "[Event's Portal]",
		},
	},
})
do ObjectDB[objectID] = objectData; end