local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[434527] = {
		readable = "Thimble's Cache",
		text = {
			en = "Thimble's Cache",
			es = "Thimble's Cache",
			de = "Thimble's Cache",
			fr = "Thimble's Cache",
			it = "Thimble's Cache",
			pt = "Thimble's Cache",
			ru = "Thimble's Cache",
			ko = "Thimble's Cache",
			cn = "Thimble's Cache",
		},
	},
	[453167] = {
		readable = "Disturbed Lynx Treasure",
		text = {
			en = "Disturbed Lynx Treasure",
			es = "Disturbed Lynx Treasure",
			de = "Disturbed Lynx Treasure",
			fr = "Disturbed Lynx Treasure",
			it = "Disturbed Lynx Treasure",
			pt = "Disturbed Lynx Treasure",
			ru = "Disturbed Lynx Treasure",
			ko = "Disturbed Lynx Treasure",
			cn = "Disturbed Lynx Treasure",
		},
	},
	[454331] = {
		readable = "Thimble's Cache",
		text = {
			en = "Thimble's Cache",
			es = "Thimble's Cache",
			de = "Thimble's Cache",
			fr = "Thimble's Cache",
			it = "Thimble's Cache",
			pt = "Thimble's Cache",
			ru = "Thimble's Cache",
			ko = "Thimble's Cache",
			cn = "Thimble's Cache",
		},
	},
	[455506] = {
		readable = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
		text = {
			en = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			es = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			de = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			fr = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			it = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			pt = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			ru = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			ko = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			cn = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
		},
	},
	[455531] = {
		readable = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
		text = {
			en = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			es = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			de = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			fr = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			it = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			pt = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			ru = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			ko = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
			cn = "<span style=\"color: #1EFF00\">Sturdy Chest</span>",
		},
	},
})
do ObjectDB[objectID] = objectData; end