local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[454404] = {
		readable = "Hathlaz's Plaque",
		model = 199987,
		text = {
			en = "Hathlaz's Plaque",
			es = "Hathlaz's Plaque",
			de = "Hathlaz's Plaque",
			fr = "Hathlaz's Plaque",
			it = "Hathlaz's Plaque",
			pt = "Hathlaz's Plaque",
			ru = "Hathlaz's Plaque",
			ko = "Hathlaz's Plaque",
			cn = "Hathlaz's Plaque",
		},
	},
	[454405] = {
		readable = "Attwogaz's Plaque",
		model = 199987,
		text = {
			en = "Attwogaz's Plaque",
			es = "Attwogaz's Plaque",
			de = "Attwogaz's Plaque",
			fr = "Attwogaz's Plaque",
			it = "Attwogaz's Plaque",
			pt = "Attwogaz's Plaque",
			ru = "Attwogaz's Plaque",
			ko = "Attwogaz's Plaque",
			cn = "Attwogaz's Plaque",
		},
	},
	[454406] = {
		readable = "Krattdaz's Plaque",
		model = 199983,
		text = {
			en = "Krattdaz's Plaque",
			es = "Krattdaz's Plaque",
			de = "Krattdaz's Plaque",
			fr = "Krattdaz's Plaque",
			it = "Krattdaz's Plaque",
			pt = "Krattdaz's Plaque",
			ru = "Krattdaz's Plaque",
			ko = "Krattdaz's Plaque",
			cn = "Krattdaz's Plaque",
		},
	},
	[454407] = {
		readable = "Uisgaz's Plaque",
		model = 199983,
		text = {
			en = "Uisgaz's Plaque",
			es = "Uisgaz's Plaque",
			de = "Uisgaz's Plaque",
			fr = "Uisgaz's Plaque",
			it = "Uisgaz's Plaque",
			pt = "Uisgaz's Plaque",
			ru = "Uisgaz's Plaque",
			ko = "Uisgaz's Plaque",
			cn = "Uisgaz's Plaque",
		},
	},
	[454408] = {
		readable = "Venedaz's Plaque",
		model = 199987,
		text = {
			en = "Venedaz's Plaque",
			es = "Venedaz's Plaque",
			de = "Venedaz's Plaque",
			fr = "Venedaz's Plaque",
			it = "Venedaz's Plaque",
			pt = "Venedaz's Plaque",
			ru = "Venedaz's Plaque",
			ko = "Venedaz's Plaque",
			cn = "Venedaz's Plaque",
		},
	},
	[454412] = {
		readable = "Merunth's Plaque",
		model = 199987,
		text = {
			en = "Merunth's Plaque",
			es = "Merunth's Plaque",
			de = "Merunth's Plaque",
			fr = "Merunth's Plaque",
			it = "Merunth's Plaque",
			pt = "Merunth's Plaque",
			ru = "Merunth's Plaque",
			ko = "Merunth's Plaque",
			cn = "Merunth's Plaque",
		},
	},
	[454414] = {
		readable = "Varerko's Plaque",
		model = 959595,
		text = {
			en = "Varerko's Plaque",
			es = "Varerko's Plaque",
			de = "Varerko's Plaque",
			fr = "Varerko's Plaque",
			it = "Varerko's Plaque",
			pt = "Varerko's Plaque",
			ru = "Varerko's Plaque",
			ko = "Varerko's Plaque",
			cn = "Varerko's Plaque",
		},
	},
	[454416] = {
		readable = "Alfritha's Plaque",
		model = 199983,
		text = {
			en = "Alfritha's Plaque",
			es = "Alfritha's Plaque",
			de = "Alfritha's Plaque",
			fr = "Alfritha's Plaque",
			it = "Alfritha's Plaque",
			pt = "Alfritha's Plaque",
			ru = "Alfritha's Plaque",
			ko = "Alfritha's Plaque",
			cn = "Alfritha's Plaque",
		},
	},
	[454417] = {
		readable = "Gundrig's Plaque",
		model = 959595,
		text = {
			en = "Gundrig's Plaque",
			es = "Gundrig's Plaque",
			de = "Gundrig's Plaque",
			fr = "Gundrig's Plaque",
			it = "Gundrig's Plaque",
			pt = "Gundrig's Plaque",
			ru = "Gundrig's Plaque",
			ko = "Gundrig's Plaque",
			cn = "Gundrig's Plaque",
		},
	},
	[454418] = {
		readable = "Sathilga's Plaque",
		model = 199987,
		text = {
			en = "Sathilga's Plaque",
			es = "Sathilga's Plaque",
			de = "Sathilga's Plaque",
			fr = "Sathilga's Plaque",
			it = "Sathilga's Plaque",
			pt = "Sathilga's Plaque",
			ru = "Sathilga's Plaque",
			ko = "Sathilga's Plaque",
			cn = "Sathilga's Plaque",
		},
	},
})
do ObjectDB[objectID] = objectData; end