local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[411571] = {
		readable = "Freydrin's Shillelagh",
		model = 4539355,
		text = {
			en = "Freydrin's Shillelagh",
			es = "Porra de madera de Freydrin",
			de = "Freydrins Shillelagh",
			fr = "Shillelagh de Freydrin",
			it = "Shillelagh di Freydrin",
			pt = "Shillelagh de Freydrin",
			ru = "Трость Фрейдрин",
			ko = "프레이드린의 곤봉",
			cn = "芙蕾德林的橡木棍",
		},
	},
	[413246] = {
		readable = "Elemental Silt Mound",
		model = 5486311,
		text = {
			en = "Elemental Silt Mound",
			es = "Montículo de cieno elemental",
			de = "Elementarer Schlickhügel",
			fr = "Tas de vase élémentaire",
			it = "Mucchio di Limo Elementale",
			pt = "Monte de Sedimento Elemental",
			ru = "Горка ила стихий",
			ko = "정령 토사 둔덕",
			cn = "元素淤泥堆",
		},
	},
	[423596] = {
		readable = "Sand Pile",
		model = 5486311,
		text = {
			en = "Sand Pile",
			es = "Montón de arena",
			de = "Sandhaufen",
			fr = "Tas de sable",
			it = "Cumulo di Sabbia",
			pt = "Monte de Areia",
			ru = "Кучка песка",
			ko = "모래 더미",
			cn = "沙堆",
		},
	},
	[423602] = {
		readable = "Sand Pile",
		model = 5486311,
		text = {
			en = "Sand Pile",
			es = "Montón de arena",
			de = "Sandhaufen",
			fr = "Tas de sable",
			it = "Cumulo di Sabbia",
			pt = "Monte de Areia",
			ru = "Кучка песка",
			ko = "모래 더미",
			cn = "沙堆",
		},
	},
	[423603] = {
		readable = "Sand Pile",
		model = 5486311,
		text = {
			en = "Sand Pile",
			es = "Montón de arena",
			de = "Sandhaufen",
			fr = "Tas de sable",
			it = "Cumulo di Sabbia",
			pt = "Monte de Areia",
			ru = "Кучка песка",
			ko = "모래 더미",
			cn = "沙堆",
		},
	},
	[423612] = {
		readable = "Titan Artifacts",
		model = 4609985,
		text = {
			en = "Titan Artifacts",
			es = "Artefactos titánicos",
			de = "Titanenartefakte",
			fr = "Artéfacts des Titans",
			it = "Manufatti dei Titani",
			pt = "Artefatos Titânicos",
			ru = "Артефакты титанов",
			ko = "티탄 유물",
			cn = "泰坦神器",
		},
	},
	[423688] = {
		readable = "Titan Device",
		model = 4485607,
		text = {
			en = "Titan Device",
			es = "Dispositivo de los titanes",
			de = "Titanengerät",
			fr = "Appareil des Titans",
			it = "Dispositivo dei Titani",
			pt = "Dispositivo Titânico",
			ru = "Устройство титанов",
			ko = "티탄 장치",
			cn = "泰坦装置",
		},
	},
	[455170] = {
		readable = "Crumbling Ironwood Parchment",
		model = 4324473,
		text = {
			en = "Crumbling Ironwood Parchment",
			es = "Papiro de maderaférrea en mal estado",
			de = "Zerbröselndes Eisenholzpergament",
			fr = "Papyrus en bois de fer effrité",
			it = "Cartapecora di Legnoduro Accartocciata",
			pt = "Pergaminho de Pau-ferro Esfacelado",
			ru = "Рассыпающийся лист железного дерева",
			ko = "바스러지는 강철나무 양피지",
			cn = "破碎铁木羊皮纸",
		},
	},
})
do ObjectDB[objectID] = objectData; end