local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[411560] = {
		readable = "Lavenbloom",
		model = 4289130,
		text = {
			en = "Lavenbloom",
			es = "Flor de lavanda",
			de = "Lavenblüte",
			fr = "Fleur de lavande",
			it = "Bocciolo di Lavanda",
			pt = "Flor de Lavanda",
			ru = "Любоцвет",
			ko = "라벤더 꽃",
			cn = "拉文之花",
		},
	},
	[411561] = {
		readable = "Sugar Orchid",
		model = 4000445,
		text = {
			en = "Sugar Orchid",
			es = "Orquídea dulce",
			de = "Zuckerorchidee",
			fr = "Orchidée en sucre",
			it = "Orchidea di Zucchero",
			pt = "Orquídea de Açúcar",
			ru = "Сахарная орхидея",
			ko = "설탕 난초",
			cn = "糖兰",
		},
	},
	[411562] = {
		readable = "Orange Illicium",
		model = 4000442,
		text = {
			en = "Orange Illicium",
			es = "Ilícium naranja",
			de = "Orangener Sternanis",
			fr = "Illicium orange",
			it = "Illicio Arancione",
			pt = "Illicium Laranja",
			ru = "Оранжевый бадьян",
			ko = "주황빛 대회향",
			cn = "橙八角",
		},
	},
	[416448] = {
		readable = "Lush Lavenbloom",
		model = 4289130,
		text = {
			en = "Lush Lavenbloom",
			es = "Flor de lavanda exuberante",
			de = "Üppige Lavenblüte",
			fr = "Fleur de lavande luxuriante",
			it = "Bocciolo di Lavanda Rigoglioso",
			pt = "Flor de Lavanda Exuberante",
			ru = "Зрелый любоцвет",
			ko = "무성한 라벤더 꽃",
			cn = "繁茂的拉文之花",
		},
	},
	[416450] = {
		readable = "Lush Orange Illicium",
		model = 4000442,
		text = {
			en = "Lush Orange Illicium",
			es = "Ilícium naranja exuberante",
			de = "Üppiger orangener Sternanis",
			fr = "Illicium orange luxuriant",
			it = "Illicio Arancione Rigoglioso",
			pt = "Illicium Laranja Exuberante",
			ru = "Зрелый оранжевый бадьян",
			ko = "무성한 주황빛 대회향",
			cn = "繁茂的橙八角",
		},
	},
})
do ObjectDB[objectID] = objectData; end