local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[104564] = {
		readable = "Bingles's Toolbucket",
		model = 197640,
		text = {
			en = "Bingles's Toolbucket",
			es = "Cubo de herramientas de Bingles",
			de = "Bingles’ Werkzeugeimer",
			fr = "Seau d'outils de Bingles",
			it = "Bingles's Toolbucket",
			pt = "Balde de Ferramentas do Bingles",
			ru = "Ведро с инструментами Бинглза",
			ko = "빙글스의 공구통",
			cn = "宾格斯的工具箱",
		},
	},
	[104569] = {
		readable = "Bingles's Toolbucket",
		model = 197641,
		text = {
			en = "Bingles's Toolbucket",
			es = "Cubo de herramientas de Bingles",
			de = "Bingles’ Werkzeugeimer",
			fr = "Seau d'outils de Bingles",
			it = "Bingles's Toolbucket",
			pt = "Balde de Ferramentas do Bingles",
			ru = "Ведро с инструментами Бинглза",
			ko = "빙글스의 공구통",
			cn = "宾格斯的工具箱",
		},
	},
	[104574] = {
		readable = "Bingles's Toolbucket",
		model = 197642,
		text = {
			en = "Bingles's Toolbucket",
			es = "Cubo de herramientas de Bingles",
			de = "Bingles’ Werkzeugeimer",
			fr = "Seau d'outils de Bingles",
			it = "Bingles's Toolbucket",
			pt = "Balde de Ferramentas do Bingles",
			ru = "Ведро с инструментами Бинглза",
			ko = "빙글스의 공구통",
			cn = "宾格斯的工具箱",
		},
	},
	[104575] = {
		readable = "Bingles's Blastencapper",
		model = 197464,
		text = {
			en = "Bingles's Blastencapper",
			es = "Cartucho de Bingles",
			de = "Bingles Superspreng",
			fr = "Capsuleur soufflant de Bingles",
			it = "Bingles's Blastencapper",
			pt = "Detona-cuca do Gomez",
			ru = "Сорвиголовка Бинглза",
			ko = "빙글스의 깡그리싸그리 폭탄",
			cn = "宾格斯的气压炸弹",
		},
	},
})
do ObjectDB[objectID] = objectData; end