local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[276616] = {
		readable = "Monelite Deposit",
		model = 2031162,
		text = {
			en = "Monelite Deposit",
			es = "Depósito de monelita",
			de = "Monelitvorkommen",
			fr = "Gisement de monélite",
			it = "Deposito di Monelite",
			pt = "Depósito de Monelita",
			ru = "Залежи монелита",
			ko = "모네라이트 광맥",
			cn = "镍铜矿脉",
		},
	},
	[276617] = {
		readable = "Storm Silver Deposit",
		model = 2019658,
		text = {
			en = "Storm Silver Deposit",
			es = "Depósito de plata de tormenta",
			de = "Sturmsilbervorkommen",
			fr = "Gisement de foudrargent",
			it = "Deposito di Argento della Tempesta",
			pt = "Depósito de Prata Procelosa",
			ru = "Залежи штормового серебра",
			ko = "폭풍 은 광맥",
			cn = "雷银矿脉",
		},
	},
	[276618] = {
		readable = "Platinum Deposit",
		model = 2019856,
		text = {
			en = "Platinum Deposit",
			es = "Depósito de platino",
			de = "Platinvorkommen",
			fr = "Gisement de platine",
			it = "Deposito di Platino",
			pt = "Depósito de Platina",
			ru = "Залежи платины",
			ko = "백금 광맥",
			cn = "白金矿脉",
		},
	},
	[276619] = {
		readable = "Monelite Seam",
		model = 2031164,
		text = {
			en = "Monelite Seam",
			es = "Veta de monelita",
			de = "Monelitflöz",
			fr = "Veine de monélite",
			it = "Vena di Monelite",
			pt = "Jazida de Monelita",
			ru = "Пласт монелита",
			ko = "모네라이트 융기",
			cn = "镍铜矿层",
		},
	},
	[276620] = {
		readable = "Storm Silver Seam",
		model = 2021566,
		text = {
			en = "Storm Silver Seam",
			es = "Veta de plata de tormenta",
			de = "Sturmsilberflöz",
			fr = "Veine de foudrargent",
			it = "Vena di Argento della Tempesta",
			pt = "Jazida de Prata Procelosa",
			ru = "Пласт штормового серебра",
			ko = "폭풍 은 융기",
			cn = "雷银矿层",
		},
	},
	[276621] = {
		readable = "Rich Monelite Deposit",
		model = 2031158,
		text = {
			en = "Rich Monelite Deposit",
			es = "Depósito de monelita rico",
			de = "Reiches Monelitvorkommen",
			fr = "Riche gisement de monélite",
			it = "Deposito Ricco di Monelite",
			pt = "Depósito de Monelita Abundante",
			ru = "Богатые залежи монелита",
			ko = "풍부한 모네라이트 광맥",
			cn = "富镍铜矿脉",
		},
	},
	[276622] = {
		readable = "Rich Storm Silver Deposit",
		model = 2019659,
		text = {
			en = "Rich Storm Silver Deposit",
			es = "Depósito de plata de tormenta rico",
			de = "Reiches Sturmsilbervorkommen",
			fr = "Riche gisement de foudrargent",
			it = "Deposito Ricco di Argento della Tempesta",
			pt = "Depósito de Prata Procelosa Abundante",
			ru = "Богатые залежи штормового серебра",
			ko = "풍부한 폭풍 은 광맥",
			cn = "富雷银矿脉",
		},
	},
})
do ObjectDB[objectID] = objectData; end