local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[455970] = {
		readable = "Nerubian Bench Blocks",
		model = 4996085,
		text = {
			en = "Nerubian Bench Blocks",
			es = "Nerubian Bench Blocks",
			de = "Nerubian Bench Blocks",
			fr = "Nerubian Bench Blocks",
			it = "Nerubian Bench Blocks",
			pt = "Nerubian Bench Blocks",
			ru = "Nerubian Bench Blocks",
			ko = "Nerubian Bench Blocks",
			cn = "Nerubian Bench Blocks",
		},
	},
	[455971] = {
		readable = "Ritual Caster's Crystal",
		model = 5778208,
		text = {
			en = "Ritual Caster's Crystal",
			es = "Ritual Caster's Crystal",
			de = "Ritual Caster's Crystal",
			fr = "Ritual Caster's Crystal",
			it = "Ritual Caster's Crystal",
			pt = "Ritual Caster's Crystal",
			ru = "Ritual Caster's Crystal",
			ko = "Ritual Caster's Crystal",
			cn = "Ritual Caster's Crystal",
		},
	},
	[455973] = {
		readable = "Arathi Sizing Gauges",
		model = 5725602,
		text = {
			en = "Arathi Sizing Gauges",
			es = "Arathi Sizing Gauges",
			de = "Arathi Sizing Gauges",
			fr = "Arathi Sizing Gauges",
			it = "Arathi Sizing Gauges",
			pt = "Arathi Sizing Gauges",
			ru = "Arathi Sizing Gauges",
			ko = "Arathi Sizing Gauges",
			cn = "Arathi Sizing Gauges",
		},
	},
	[455977] = {
		readable = "Gentle Jewel Hammer",
		model = 5383286,
		text = {
			en = "Gentle Jewel Hammer",
			es = "Gentle Jewel Hammer",
			de = "Behutsamer Juwelenhammer",
			fr = "Gentle Jewel Hammer",
			it = "Martelletto per Gioielli",
			pt = "Gentle Jewel Hammer",
			ru = "Gentle Jewel Hammer",
			ko = "Gentle Jewel Hammer",
			cn = "Gentle Jewel Hammer",
		},
	},
})
do ObjectDB[objectID] = objectData; end