local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[455947] = {
		readable = "Nerubian's Slicking Iron",
		model = 5155026,
		text = {
			en = "Nerubian's Slicking Iron",
			es = "Nerubian's Slicking Iron",
			de = "Nerubian's Slicking Iron",
			fr = "Fer de tannage nérubien",
			it = "Nerubian's Slicking Iron",
			pt = "Nerubian's Slicking Iron",
			ru = "Нерубский шлифовальный нож",
			ko = "Nerubian's Slicking Iron",
			cn = "Nerubian's Slicking Iron",
		},
	},
	[455984] = {
		readable = "Historian's Dip Pen",
		model = 5546880,
		text = {
			en = "Historian's Dip Pen",
			es = "Historian's Dip Pen",
			de = "Historian's Dip Pen",
			fr = "Historian's Dip Pen",
			it = "Historian's Dip Pen",
			pt = "Pena de Caligrafia do Historiador",
			ru = "Historian's Dip Pen",
			ko = "Historian's Dip Pen",
			cn = "Historian's Dip Pen",
		},
	},
	[455985] = {
		readable = "Dornogal Scribe's Quill",
		model = 5546881,
		text = {
			en = "Dornogal Scribe's Quill",
			es = "Dornogal Scribe's Quill",
			de = "Federkiel des Schreibers aus Dornogal",
			fr = "Dornogal Scribe's Quill",
			it = "Dornogal Scribe's Quill",
			pt = "Pena do Escriba de Dornogal",
			ru = "Dornogal Scribe's Quill",
			ko = "Dornogal Scribe's Quill",
			cn = "Dornogal Scribe's Quill",
		},
	},
	[419657] = {
		readable = "Abandoned Tools",
		model = 5204877,
		text = {
			en = "Abandoned Tools",
			es = "[Abandoned Tools]",
			de = "[Abandoned Tools]",
			fr = "[Abandoned Tools]",
			it = "[Abandoned Tools]",
			pt = "[Abandoned Tools]",
			ru = "[Abandoned Tools]",
			ko = "[Abandoned Tools]",
			cn = "[Abandoned Tools]",
		},
	},
	[455508] = {
		readable = "|cff1EFF00Sturdy Chest",
		model = 5128194,
		text = {
			en = "|cff1EFF00Sturdy Chest",
			es = "|cff1EFF00Cofre robusto",
			de = "|cff1EFF00Robuste Truhe",
			fr = "|cff1EFF00Coffre solide",
			it = "|cff1EFF00Cassa Resistente",
			pt = "|cff1EFF00Baú Resistente",
			ru = "|cff1EFF00Прочный сундук",
			ko = "|cff1EFF00Sturdy Chest",
			cn = "|cff1EFF00Sturdy Chest",
		},
	},
})
do ObjectDB[objectID] = objectData; end