local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[410395] = {
		readable = "Siegehold Records",
		model = 5007025,
		text = {
			en = "Siegehold Records",
			es = "Siegehold Records",
			de = "Dokumente der Belagerungsfeste",
			fr = "Registres du bastion du Siège",
			it = "Siegehold Records",
			pt = "Registros do Forte do Cerco",
			ru = "Siegehold Records",
			ko = "Siegehold Records",
			cn = "Siegehold Records",
		},
	},
	[411102] = {
		readable = "Airship Rubble",
		model = 5010352,
		text = {
			en = "Airship Rubble",
			es = "Airship Rubble",
			de = "Luftschifftrümmer",
			fr = "Décombres d’aéronef",
			it = "Airship Rubble",
			pt = "Escombros de Aeronau",
			ru = "Обломки воздушного судна",
			ko = "Airship Rubble",
			cn = "Airship Rubble",
		},
	},
	[411104] = {
		readable = "Well-Bleached Bones",
		model = 3036605,
		text = {
			en = "Well-Bleached Bones",
			es = "Well-Bleached Bones",
			de = "Stark ausgebleichte Knochen",
			fr = "Os bien blanchis",
			it = "Well-Bleached Bones",
			pt = "Ossos Bem-alvejados",
			ru = "Выцветшие добела кости",
			ko = "Well-Bleached Bones",
			cn = "Well-Bleached Bones",
		},
	},
	[411106] = {
		readable = "Weathered Cloth",
		model = 1608338,
		text = {
			en = "Weathered Cloth",
			es = "Weathered Cloth",
			de = "Verwitterter Stoff",
			fr = "Tissu abîmé",
			it = "Weathered Cloth",
			pt = "Tecido Desgastado",
			ru = "Weathered Cloth",
			ko = "Weathered Cloth",
			cn = "Weathered Cloth",
		},
	},
	[411930] = {
		readable = "Blackpowder Barrel",
		model = 4891997,
		text = {
			en = "Blackpowder Barrel",
			es = "Blackpowder Barrel",
			de = "Schwarzpulverfass",
			fr = "Tonneau de poudre noire",
			it = "Blackpowder Barrel",
			pt = "Barril de Pólvora",
			ru = "Blackpowder Barrel",
			ko = "Blackpowder Barrel",
			cn = "Blackpowder Barrel",
		},
	},
	[414113] = {
		readable = "Sivstone Deposit",
		model = 984875,
		text = {
			en = "Sivstone Deposit",
			es = "Sivstone Deposit",
			de = "Sivsteinvorkommen",
			fr = "Dépôt de sivpierre",
			it = "Sivstone Deposit",
			pt = "Depósito de Sivolita",
			ru = "Sivstone Deposit",
			ko = "Sivstone Deposit",
			cn = "Sivstone Deposit",
		},
	},
	[424436] = {
		readable = "Order of Night Propaganda",
		model = 5386357,
		text = {
			en = "Order of Night Propaganda",
			es = "Order of Night Propaganda",
			de = "Propaganda des Ordens der Nacht",
			fr = "Propagande de l’Ordre de la nuit",
			it = "Order of Night Propaganda",
			pt = "Propaganda da Ordem da Noite",
			ru = "Order of Night Propaganda",
			ko = "Order of Night Propaganda",
			cn = "Order of Night Propaganda",
		},
	},
	[428814] = {
		readable = "Inconspicuous Box",
		model = 5007036,
		text = {
			en = "Inconspicuous Box",
			es = "Inconspicuous Box",
			de = "Unverdächtige Kiste",
			fr = "Boîte anodine",
			it = "Inconspicuous Box",
			pt = "Caixa Inconspícua",
			ru = "Inconspicuous Box",
			ko = "Inconspicuous Box",
			cn = "Inconspicuous Box",
		},
	},
	[433907] = {
		readable = "Order of Night Propaganda",
		model = 3166135,
		text = {
			en = "Order of Night Propaganda",
			es = "Order of Night Propaganda",
			de = "Propaganda des Ordens der Nacht",
			fr = "Propagande de l’Ordre de la nuit",
			it = "Order of Night Propaganda",
			pt = "Propaganda da Ordem da Noite.",
			ru = "Order of Night Propaganda",
			ko = "Order of Night Propaganda",
			cn = "Order of Night Propaganda",
		},
	},
	[441585] = {
		readable = "Burning Venom Flask",
		model = 5201700,
		text = {
			en = "Burning Venom Flask",
			es = "Burning Venom Flask",
			de = "Brennendes Giftfläschchen",
			fr = "Flacon de venin brûlant",
			it = "Burning Venom Flask",
			pt = "Frasco de Peçonha Ardente",
			ru = "Burning Venom Flask",
			ko = "Burning Venom Flask",
			cn = "Burning Venom Flask",
		},
	},
	[441586] = {
		readable = "Military Correspondence",
		model = 5007028,
		text = {
			en = "Military Correspondence",
			es = "Military Correspondence",
			de = "Militärkorrespondenz",
			fr = "Correspondance militaire",
			it = "Military Correspondence",
			pt = "Correspondência Militar",
			ru = "Military Correspondence",
			ko = "Military Correspondence",
			cn = "Military Correspondence",
		},
	},
	[441587] = {
		readable = "Crate of Emptied Vials",
		model = 5007037,
		text = {
			en = "Crate of Emptied Vials",
			es = "Crate of Emptied Vials",
			de = "Kiste mit leeren Phiolen",
			fr = "Caisse de flacons vides",
			it = "Crate of Emptied Vials",
			pt = "Caixote de Ampolas Vazias",
			ru = "Crate of Emptied Vials",
			ko = "Crate of Emptied Vials",
			cn = "Crate of Emptied Vials",
		},
	},
	[441588] = {
		readable = "Confiscated Weapons",
		model = 4996086,
		text = {
			en = "Confiscated Weapons",
			es = "Confiscated Weapons",
			de = "Konfiszierte Waffen",
			fr = "Armes confisquées",
			it = "Confiscated Weapons",
			pt = "Armas Confiscadas",
			ru = "Confiscated Weapons",
			ko = "Confiscated Weapons",
			cn = "Confiscated Weapons",
		},
	},
	[455938] = {
		readable = "Nerubian's Pincushion",
		model = 5736938,
		text = {
			en = "Nerubian's Pincushion",
			es = "Nerubian's Pincushion",
			de = "Nadelkissen der Neruber",
			fr = "Nerubian's Pincushion",
			it = "Nerubian's Pincushion",
			pt = "Nerubian's Pincushion",
			ru = "Nerubian's Pincushion",
			ko = "Nerubian's Pincushion",
			cn = "Nerubian's Pincushion",
		},
	},
})
do ObjectDB[objectID] = objectData; end