local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[404849] = {
		readable = "Dreadsquall Nest",
		model = 4532354,
		text = {
			en = "Dreadsquall Nest",
			es = "Nido de graznaterror",
			de = "Schreckenswindnest",
			fr = "Nid de corveffroi",
			it = "Nido di Nubetetra",
			pt = "Ninho de Berramedo",
			ru = "Гнездо грозного ворона",
			ko = "공포질풍 둥지",
			cn = "惧飑鸦之巢",
		},
	},
	[405593] = {
		readable = "Azerothian Archives!",
		model = 4317329,
		text = {
			en = "Azerothian Archives!",
			es = "¡Archivo de Azeroth!",
			de = "Archive von Azeroth!",
			fr = "Archives d’Azeroth !",
			it = "Archivi Azerothiani!",
			pt = "Arquivo Azerothiano!",
			ru = "Азеротские Архивы!",
			ko = "아제로스 기록 보관소!",
			cn = "艾泽拉斯档案馆！",
		},
	},
	[405943] = {
		readable = "Drakonid Scroll Case",
		model = 4298589,
		text = {
			en = "Drakonid Scroll Case",
			es = "[Drakonid Scroll Case]",
			de = "Drakonidischer Schriftrollenbehälter",
			fr = "Étui à parchemin drakônide",
			it = "Portapergamene Draconide",
			pt = "Estojo de Pergaminhos Draconídeo",
			ru = "Футляр для свитка драконидов",
			ko = "용기병 두루마리 보관함",
			cn = "[Drakonid Scroll Case]",
		},
	},
	[405996] = {
		readable = "Ancient Zaqali Trade-bond Tablet",
		model = 4420700,
		text = {
			en = "Ancient Zaqali Trade-bond Tablet",
			es = "Tablilla antigua de intercambio zaqali",
			de = "Uralte Bürgschaftstafel der Zaqali",
			fr = "Tablette de lien commercial zaqali antique",
			it = "Antica Tavoletta sul Commercio degli Zaqali",
			pt = "Tabuleta Vinculada ao Comércio Zaqali Antiga",
			ru = "Табличка древнего торговца закали",
			ko = "고대의 거래 구속 서판",
			cn = "[Ancient Zaqali Trade-bond Tablet]",
		},
	},
	[410994] = {
		readable = "Map of Shadowfang Keep Security",
		model = 311986,
		text = {
			en = "Map of Shadowfang Keep Security",
			es = "Mapa de seguridad del Castillo de Colmillo Oscuro",
			de = "Karte der Sicherheitseinrichtungen von Burg Schattenfang",
			fr = "Carte de la sécurité du donjon d’Ombrecroc",
			it = "Mappa della Sicurezza del Forte di Zannascura",
			pt = "Mapa da Segurança da Bastilha da Presa Negra",
			ru = "План защиты крепости Темного Клыка",
			ko = "그림자송곳니 성채 경비 지도",
			cn = "影牙城堡安保地图",
		},
	},
	[410998] = {
		readable = "Formula: Intoxicating Toxic Perfume",
		model = 949621,
		text = {
			en = "Formula: Intoxicating Toxic Perfume",
			es = "Fórmula: perfume tóxico embriagador",
			de = "Formel: Berauschendes giftiges Parfüm",
			fr = "Formule : parfum entêtant toxique",
			it = "Formula: Profumo Tossico Inebriante",
			pt = "Fórmula: Perfume Tóxico Intoxicante",
			ru = "Формула: дурманящий ядовитый парфюм",
			ko = "주문식: 중독적인 독성 향수",
			cn = "公式：醉毒香水",
		},
	},
	[410999] = {
		readable = "Memo from Apothecary Hummel",
		model = 936413,
		text = {
			en = "Memo from Apothecary Hummel",
			es = "Nota del boticario Hummel",
			de = "Memo von Apotheker Hummel",
			fr = "Note de l’apothicaire Hummel",
			it = "Promemoria dello Speziale Hummel",
			pt = "Memorando do Boticário Humberto",
			ru = "Заметка аптекаря Хаммела",
			ko = "연금술사 훔멜의 쪽지",
			cn = "药剂师汉摩尔的备忘录",
		},
	},
	[411691] = {
		readable = "Shiny New Weapon",
		model = 4216583,
		text = {
			en = "Shiny New Weapon",
			es = "Arma nueva brillante",
			de = "Glänzende neue Waffe",
			fr = "Arme toute neuve",
			it = "Nuova Arma Lucente",
			pt = "Nova Arma Brilhante",
			ru = "Новенькое оружие",
			ko = "빛나는 새 무기",
			cn = "亮闪闪的新武器",
		},
	},
	[413126] = {
		readable = "Box of Artisanal Goods",
		model = 3917383,
		text = {
			en = "Box of Artisanal Goods",
			es = "Caja de bienes artesanales",
			de = "Kasten mit Handwerkswaren",
			fr = "Boîte de produits artisanaux",
			it = "Scatola di Beni Artigianali",
			pt = "Livro de Mercadorias Artesanais",
			ru = "Коробка с товарами ремесленников",
			ko = "장인 상품 상자",
			cn = "一箱工匠货物",
		},
	},
	[421179] = {
		readable = "Kaldorei Bedroll",
		model = 4756260,
		text = {
			en = "Kaldorei Bedroll",
			es = "Saco de dormir kaldorei",
			de = "Kaldoreischlafsack",
			fr = "Sac de couchage kaldorei",
			it = "Futon dei Kaldorei",
			pt = "Saco de Dormir Kaldorei",
			ru = "Калдорайская походная постель",
			ko = "칼도레이 침낭",
			cn = "[Kaldorei Bedroll]",
		},
	},
	[421180] = {
		readable = "Kaldorei Backpack",
		model = 5489255,
		text = {
			en = "Kaldorei Backpack",
			es = "Mochila kaldorei",
			de = "Kaldoreirucksack",
			fr = "Sac à dos kaldorei",
			it = "Zaino dei Kaldorei",
			pt = "Mochila Kaldorei",
			ru = "Калдорайский рюкзак",
			ko = "칼도레이 배낭",
			cn = "[Kaldorei Backpack]",
		},
	},
	[421181] = {
		readable = "Kaldorei Dagger",
		model = 5489281,
		text = {
			en = "Kaldorei Dagger",
			es = "Daga kaldorei",
			de = "Kaldoreidolch",
			fr = "Dague kaldorei",
			it = "Pugnale dei Kaldorei",
			pt = "Adaga Kaldorei",
			ru = "Калдорайский кинжал",
			ko = "칼도레이 단검",
			cn = "[Kaldorei Dagger]",
		},
	},
	[421182] = {
		readable = "Kaldorei Horn",
		model = 5489269,
		text = {
			en = "Kaldorei Horn",
			es = "Cuerno kaldorei",
			de = "Kaldoreihorn",
			fr = "Corne kaldorei",
			it = "Corno dei Kaldorei",
			pt = "Chifre Kaldorei",
			ru = "Калдорайский рог",
			ko = "칼도레이 뿔피리",
			cn = "[Kaldorei Horn]",
		},
	},
	[421183] = {
		readable = "Kaldorei Bag",
		model = 5489282,
		text = {
			en = "Kaldorei Bag",
			es = "Bolsa kaldorei",
			de = "Kaldoreitasche",
			fr = "Sac kaldorei",
			it = "Borsa dei Kaldorei",
			pt = "Bolsa Kaldorei",
			ru = "Калдорайская сумка",
			ko = "칼도레이 가방",
			cn = "[Kaldorei Bag]",
		},
	},
	[421184] = {
		readable = "Kaldorei Shield",
		model = 5489286,
		text = {
			en = "Kaldorei Shield",
			es = "Escudo kaldorei",
			de = "Kaldoreischild",
			fr = "Bouclier kaldorei",
			it = "Scudo dei Kaldorei",
			pt = "Escudo Kaldorei",
			ru = "Калдорайский щит",
			ko = "칼도레이 방패",
			cn = "[Kaldorei Shield]",
		},
	},
	[421185] = {
		readable = "Kaldorei Spear",
		model = 5489285,
		text = {
			en = "Kaldorei Spear",
			es = "Lanza kaldorei",
			de = "Kaldoreispeer",
			fr = "Lance kaldorei",
			it = "Lancia dei Kaldorei",
			pt = "Lança Kaldorei",
			ru = "Калдорайское копье",
			ko = "칼도레이 창",
			cn = "[Kaldorei Spear]",
		},
	},
	[421186] = {
		readable = "Kaldorei Spyglass",
		model = 5489284,
		text = {
			en = "Kaldorei Spyglass",
			es = "Catalejo kaldorei",
			de = "Kaldoreifernrohr",
			fr = "Longue-vue kaldorei",
			it = "Cannocchiale dei Kaldorei",
			pt = "Luneta Kaldorei",
			ru = "Калдорайская подзорная труба",
			ko = "칼도레이 망원경",
			cn = "[Kaldorei Spyglass]",
		},
	},
	[421338] = {
		readable = "Kaldorei Bag",
		model = 5489283,
		text = {
			en = "Kaldorei Bag",
			es = "Bolsa kaldorei",
			de = "Kaldoreitasche",
			fr = "Sac kaldorei",
			it = "Borsa dei Kaldorei",
			pt = "Bolsa Kaldorei",
			ru = "Калдорайская сумка",
			ko = "칼도레이 가방",
			cn = "[Kaldorei Bag]",
		},
	},
	[421339] = {
		readable = "Kaldorei Horn",
		model = 5489270,
		text = {
			en = "Kaldorei Horn",
			es = "Cuerno kaldorei",
			de = "Kaldoreihorn",
			fr = "Corne kaldorei",
			it = "Corno dei Kaldorei",
			pt = "Chifre Kaldorei",
			ru = "Калдорайский рог",
			ko = "칼도레이 뿔피리",
			cn = "[Kaldorei Horn]",
		},
	},
	[421360] = {
		readable = "Memorial Bouquet",
		model = 5282331,
		text = {
			en = "Memorial Bouquet",
			es = "Ramo conmemorativo",
			de = "Denkstättengebinde",
			fr = "Gerbe du souvenir",
			it = "Bouquet Commemorativo",
			pt = "[Memorial Bouquet]",
			ru = "Букет на памятник",
			ko = "추모의 꽃다발",
			cn = "[Memorial Bouquet]",
		},
	},
	[421555] = {
		readable = "Kaldorei Moon Bow",
		model = 2133380,
		text = {
			en = "Kaldorei Moon Bow",
			es = "Arco lunar kaldorei",
			de = "Kaldoreimondbogen",
			fr = "Arc de lune kaldorei",
			it = "Arco della Luna dei Kaldorei",
			pt = "Arco Lunar Kaldorei",
			ru = "Калдорайский лунный лук",
			ko = "칼도레이 달의 활",
			cn = "[Kaldorei Moon Bow]",
		},
	},
})
do ObjectDB[objectID] = objectData; end