local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[441628] = {
		readable = "Captain's Chest",
		text = {
			en = "Captain's Chest",
			es = "Captain's Chest",
			de = "Captain's Chest",
			fr = "Captain's Chest",
			it = "Captain's Chest",
			pt = "Captain's Chest",
			ru = "Captain's Chest",
			ko = "Captain's Chest",
			cn = "Captain's Chest",
		},
	},
	[441633] = {
		readable = "A Worn Down Book",
		text = {
			en = "A Worn Down Book",
			es = "A Worn Down Book",
			de = "A Worn Down Book",
			fr = "A Worn Down Book",
			it = "A Worn Down Book",
			pt = "A Worn Down Book",
			ru = "A Worn Down Book",
			ko = "A Worn Down Book",
			cn = "A Worn Down Book",
		},
	},
	[441688] = {
		readable = "A Tattered Note",
		text = {
			en = "A Tattered Note",
			es = "A Tattered Note",
			de = "A Tattered Note",
			fr = "A Tattered Note",
			it = "A Tattered Note",
			pt = "A Tattered Note",
			ru = "A Tattered Note",
			ko = "A Tattered Note",
			cn = "A Tattered Note",
		},
	},
	[441720] = {
		readable = "A Scout's Journal",
		text = {
			en = "A Scout's Journal",
			es = "A Scout's Journal",
			de = "A Scout's Journal",
			fr = "A Scout's Journal",
			it = "A Scout's Journal",
			pt = "A Scout's Journal",
			ru = "A Scout's Journal",
			ko = "A Scout's Journal",
			cn = "A Scout's Journal",
		},
	},
	[453741] = {
		readable = "Loremaster's Reward",
		text = {
			en = "Loremaster's Reward",
			es = "Loremaster's Reward",
			de = "Loremaster's Reward",
			fr = "Loremaster's Reward",
			it = "Loremaster's Reward",
			pt = "Loremaster's Reward",
			ru = "Loremaster's Reward",
			ko = "Loremaster's Reward",
			cn = "Loremaster's Reward",
		},
	},
	[453752] = {
		readable = "Shadow Curfew Guidelines",
		text = {
			en = "Shadow Curfew Guidelines",
			es = "Shadow Curfew Guidelines",
			de = "Shadow Curfew Guidelines",
			fr = "Shadow Curfew Guidelines",
			it = "Shadow Curfew Guidelines",
			pt = "Shadow Curfew Guidelines",
			ru = "Shadow Curfew Guidelines",
			ko = "Shadow Curfew Guidelines",
			cn = "Shadow Curfew Guidelines",
		},
	},
	[453753] = {
		readable = "Beledar- The Emperor's Vision",
		text = {
			en = "Beledar- The Emperor's Vision",
			es = "Beledar- The Emperor's Vision",
			de = "Beledar- The Emperor's Vision",
			fr = "Beledar- The Emperor's Vision",
			it = "Beledar- The Emperor's Vision",
			pt = "Beledar- The Emperor's Vision",
			ru = "Beledar- The Emperor's Vision",
			ko = "Beledar- The Emperor's Vision",
			cn = "Beledar- The Emperor's Vision",
		},
	},
	[453754] = {
		readable = "The Song of Renilash",
		text = {
			en = "The Song of Renilash",
			es = "The Song of Renilash",
			de = "The Song of Renilash",
			fr = "The Song of Renilash",
			it = "The Song of Renilash",
			pt = "The Song of Renilash",
			ru = "The Song of Renilash",
			ko = "The Song of Renilash",
			cn = "The Song of Renilash",
		},
	},
	[453755] = {
		readable = "The Big Book of Arathi Idioms",
		text = {
			en = "The Big Book of Arathi Idioms",
			es = "The Big Book of Arathi Idioms",
			de = "The Big Book of Arathi Idioms",
			fr = "The Big Book of Arathi Idioms",
			it = "The Big Book of Arathi Idioms",
			pt = "The Big Book of Arathi Idioms",
			ru = "The Big Book of Arathi Idioms",
			ko = "The Big Book of Arathi Idioms",
			cn = "The Big Book of Arathi Idioms",
		},
	},
	[455038] = {
		readable = "Light's Gambit Playbook",
		text = {
			en = "Light's Gambit Playbook",
			es = "Light's Gambit Playbook",
			de = "Light's Gambit Playbook",
			fr = "Light's Gambit Playbook",
			it = "Light's Gambit Playbook",
			pt = "Light's Gambit Playbook",
			ru = "Light's Gambit Playbook",
			ko = "Light's Gambit Playbook",
			cn = "Light's Gambit Playbook",
		},
	},
	[455948] = {
		readable = "Arathi Craftsman's Spokeshave",
		text = {
			en = "Arathi Craftsman's Spokeshave",
			es = "Arathi Craftsman's Spokeshave",
			de = "Arathi Craftsman's Spokeshave",
			fr = "Arathi Craftsman's Spokeshave",
			it = "Arathi Craftsman's Spokeshave",
			pt = "Arathi Craftsman's Spokeshave",
			ru = "Arathi Craftsman's Spokeshave",
			ko = "Arathi Craftsman's Spokeshave",
			cn = "Arathi Craftsman's Spokeshave",
		},
	},
	[455964] = {
		readable = "Arathi Leather Burnisher",
		text = {
			en = "Arathi Leather Burnisher",
			es = "Arathi Leather Burnisher",
			de = "Arathi Leather Burnisher",
			fr = "Arathi Leather Burnisher",
			it = "Arathi Leather Burnisher",
			pt = "Arathi Leather Burnisher",
			ru = "Arathi Leather Burnisher",
			ko = "Arathi Leather Burnisher",
			cn = "Arathi Leather Burnisher",
		},
	},
	[455965] = {
		readable = "Arathi Beveler Set",
		text = {
			en = "Arathi Beveler Set",
			es = "Arathi Beveler Set",
			de = "Arathi Beveler Set",
			fr = "Arathi Beveler Set",
			it = "Arathi Beveler Set",
			pt = "Arathi Beveler Set",
			ru = "Arathi Beveler Set",
			ko = "Arathi Beveler Set",
			cn = "Arathi Beveler Set",
		},
	},
})
do ObjectDB[objectID] = objectData; end