local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[454323] = {
		readable = "Thimble's Cache",
		model = 5007036,
		text = {
			en = "Thimble's Cache",
			es = "Thimble's Cache",
			de = "Fingerhuts Vorräte",
			fr = "Cachette de Croquette",
			it = "Thimble's Cache",
			pt = "Thimble's Cache",
			ru = "Тайник Наперстика",
			ko = "Thimble's Cache",
			cn = "Thimble's Cache",
			tw = "Thimble's Cache",
		},
	},
	[454327] = {
		readable = "Thimble's Cache",
		model = 5007036,
		text = {
			en = "Thimble's Cache",
			es = "Alijo de Dedal",
			de = "Fingerhuts Vorräte",
			fr = "Cachette de Croquette",
			it = "Cassa di Tessitino",
			pt = "Thimble's Cache",
			ru = "Тайник Наперстика",
			ko = "팀블의 은닉처",
			cn = "顶针的箱子",
			tw = "Thimble's Cache",
		},
	},
	[454339] = {
		readable = "Thimble's Cache",
		model = 5007036,
		text = {
			en = "Thimble's Cache",
			es = "Alijo de Dedal",
			de = "Fingerhuts Vorräte",
			fr = "Cachette de Croquette",
			it = "Cassa di Tessitino",
			pt = "Thimble's Cache",
			ru = "Тайник Наперстика",
			ko = "Thimble's Cache",
			cn = "Thimble's Cache",
			tw = "Thimble's Cache",
		},
	},
})
do ObjectDB[objectID] = objectData; end