local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[454313] = {
		readable = "Queen Xekatha",
		text = {
			en = "Queen Xekatha",
			es = "Queen Xekatha",
			de = "Queen Xekatha",
			fr = "Queen Xekatha",
			it = "Queen Xekatha",
			pt = "Queen Xekatha",
			ru = "Queen Xekatha",
			ko = "Queen Xekatha",
			cn = "Queen Xekatha",
		},
	},
	[454316] = {
		readable = "Queen Zaltra",
		text = {
			en = "Queen Zaltra",
			es = "Queen Zaltra",
			de = "Queen Zaltra",
			fr = "Queen Zaltra",
			it = "Queen Zaltra",
			pt = "Queen Zaltra",
			ru = "Queen Zaltra",
			ko = "Queen Zaltra",
			cn = "Queen Zaltra",
		},
	},
	[454320] = {
		readable = "Queen Anub'izek",
		text = {
			en = "Queen Anub'izek",
			es = "Queen Anub'izek",
			de = "Queen Anub'izek",
			fr = "Queen Anub'izek",
			it = "Queen Anub'izek",
			pt = "Queen Anub'izek",
			ru = "Queen Anub'izek",
			ko = "Queen Anub'izek",
			cn = "Queen Anub'izek",
		},
	},
	[454328] = {
		readable = "Strands of Memory",
		text = {
			en = "Strands of Memory",
			es = "Strands of Memory",
			de = "Strands of Memory",
			fr = "Strands of Memory",
			it = "Strands of Memory",
			pt = "Strands of Memory",
			ru = "Strands of Memory",
			ko = "Strands of Memory",
			cn = "Strands of Memory",
		},
	},
	[454330] = {
		readable = "Treatise on Forms: Skitterlings",
		text = {
			en = "Treatise on Forms: Skitterlings",
			es = "Treatise on Forms: Skitterlings",
			de = "Treatise on Forms: Skitterlings",
			fr = "Treatise on Forms: Skitterlings",
			it = "Treatise on Forms: Skitterlings",
			pt = "Treatise on Forms: Skitterlings",
			ru = "Treatise on Forms: Skitterlings",
			ko = "Treatise on Forms: Skitterlings",
			cn = "Treatise on Forms: Skitterlings",
		},
	},
	[454332] = {
		readable = "Treatise on Forms: Sages",
		text = {
			en = "Treatise on Forms: Sages",
			es = "Treatise on Forms: Sages",
			de = "Treatise on Forms: Sages",
			fr = "Treatise on Forms: Sages",
			it = "Treatise on Forms: Sages",
			pt = "Treatise on Forms: Sages",
			ru = "Treatise on Forms: Sages",
			ko = "Treatise on Forms: Sages",
			cn = "Treatise on Forms: Sages",
		},
	},
	[454343] = {
		readable = "Ethos of War, Part 1",
		text = {
			en = "Ethos of War, Part 1",
			es = "Ethos of War, Part 1",
			de = "Ethos of War, Part 1",
			fr = "Ethos of War, Part 1",
			it = "Ethos of War, Part 1",
			pt = "Ethos of War, Part 1",
			ru = "Ethos of War, Part 1",
			ko = "Ethos of War, Part 1",
			cn = "Ethos of War, Part 1",
		},
	},
	[454344] = {
		readable = "Ethos of War, Part 2",
		text = {
			en = "Ethos of War, Part 2",
			es = "Ethos of War, Part 2",
			de = "Ethos of War, Part 2",
			fr = "Ethos of War, Part 2",
			it = "Ethos of War, Part 2",
			pt = "Ethos of War, Part 2",
			ru = "Ethos of War, Part 2",
			ko = "Ethos of War, Part 2",
			cn = "Ethos of War, Part 2",
		},
	},
	[454348] = {
		readable = "Ethos of War, Part 3",
		text = {
			en = "Ethos of War, Part 3",
			es = "Ethos of War, Part 3",
			de = "Ethos of War, Part 3",
			fr = "Ethos of War, Part 3",
			it = "Ethos of War, Part 3",
			pt = "Ethos of War, Part 3",
			ru = "Ethos of War, Part 3",
			ko = "Ethos of War, Part 3",
			cn = "Ethos of War, Part 3",
		},
	},
	[454350] = {
		readable = "Ethos of War, Part 4",
		text = {
			en = "Ethos of War, Part 4",
			es = "Ethos of War, Part 4",
			de = "Ethos of War, Part 4",
			fr = "Ethos of War, Part 4",
			it = "Ethos of War, Part 4",
			pt = "Ethos of War, Part 4",
			ru = "Ethos of War, Part 4",
			ko = "Ethos of War, Part 4",
			cn = "Ethos of War, Part 4",
		},
	},
	[456927] = {
		readable = "Treatise on Forms: Lords",
		text = {
			en = "Treatise on Forms: Lords",
			es = "Treatise on Forms: Lords",
			de = "Treatise on Forms: Lords",
			fr = "Treatise on Forms: Lords",
			it = "Treatise on Forms: Lords",
			pt = "Treatise on Forms: Lords",
			ru = "Treatise on Forms: Lords",
			ko = "Treatise on Forms: Lords",
			cn = "Treatise on Forms: Lords",
		},
	},
	[456928] = {
		readable = "Treatise on Forms: Ascended",
		text = {
			en = "Treatise on Forms: Ascended",
			es = "Treatise on Forms: Ascended",
			de = "Treatise on Forms: Ascended",
			fr = "Treatise on Forms: Ascended",
			it = "Treatise on Forms: Ascended",
			pt = "Treatise on Forms: Ascended",
			ru = "Treatise on Forms: Ascended",
			ko = "Treatise on Forms: Ascended",
			cn = "Treatise on Forms: Ascended",
		},
	},
})
do ObjectDB[objectID] = objectData; end