local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[410475] = {
		readable = "Petrified Hope",
		model = 1037393,
		text = {
			en = "Petrified Hope",
			es = "Petrified Hope",
			de = "Petrified Hope",
			fr = "Petrified Hope",
			it = "Petrified Hope",
			pt = "Petrified Hope",
			ru = "Petrified Hope",
			ko = "Petrified Hope",
			cn = "Petrified Hope",
		},
	},
	[410479] = {
		readable = "Unpolished Blemish",
		text = {
			en = "Unpolished Blemish",
			es = "Unpolished Blemish",
			de = "Unpolished Blemish",
			fr = "Unpolished Blemish",
			it = "Unpolished Blemish",
			pt = "Unpolished Blemish",
			ru = "Unpolished Blemish",
			ko = "Unpolished Blemish",
			cn = "Unpolished Blemish",
		},
	},
	[410484] = {
		readable = "Coalesced Dreamstone",
		text = {
			en = "Coalesced Dreamstone",
			es = "Coalesced Dreamstone",
			de = "Coalesced Dreamstone",
			fr = "Coalesced Dreamstone",
			it = "Coalesced Dreamstone",
			pt = "Coalesced Dreamstone",
			ru = "Coalesced Dreamstone",
			ko = "Coalesced Dreamstone",
			cn = "Coalesced Dreamstone",
		},
	},
	[411171] = {
		readable = "Exceedingly Soft Wildercloth",
		text = {
			en = "Exceedingly Soft Wildercloth",
			es = "Exceedingly Soft Wildercloth",
			de = "Exceedingly Soft Wildercloth",
			fr = "Exceedingly Soft Wildercloth",
			it = "Exceedingly Soft Wildercloth",
			pt = "Exceedingly Soft Wildercloth",
			ru = "Exceedingly Soft Wildercloth",
			ko = "Exceedingly Soft Wildercloth",
			cn = "Exceedingly Soft Wildercloth",
		},
	},
	[411176] = {
		readable = "Plush Pillow",
		text = {
			en = "Plush Pillow",
			es = "Plush Pillow",
			de = "Plush Pillow",
			fr = "Plush Pillow",
			it = "Plush Pillow",
			pt = "Plush Pillow",
			ru = "Plush Pillow",
			ko = "Plush Pillow",
			cn = "Plush Pillow",
		},
	},
	[411177] = {
		readable = "Snuggle Buddy",
		model = 3563973,
		text = {
			en = "Snuggle Buddy",
			es = "Snuggle Buddy",
			de = "Snuggle Buddy",
			fr = "Snuggle Buddy",
			it = "Snuggle Buddy",
			pt = "Snuggle Buddy",
			ru = "Snuggle Buddy",
			ko = "Snuggle Buddy",
			cn = "Snuggle Buddy",
		},
	},
})
do ObjectDB[objectID] = objectData; end