local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[423987] = {
		readable = "Dropped Package",
		text = {
			en = "Dropped Package",
			es = "Dropped Package",
			de = "Dropped Package",
			fr = "Dropped Package",
			it = "Dropped Package",
			pt = "Dropped Package",
			ru = "Dropped Package",
			ko = "Dropped Package",
			cn = "Dropped Package",
		},
	},
	[428135] = {
		readable = "Discarded Botanist Notes",
		model = 4324473,
		text = {
			en = "Discarded Botanist Notes",
			es = "Discarded Botanist Notes",
			de = "Discarded Botanist Notes",
			fr = "Discarded Botanist Notes",
			it = "Discarded Botanist Notes",
			pt = "Discarded Botanist Notes",
			ru = "Discarded Botanist Notes",
			ko = "Discarded Botanist Notes",
			cn = "Discarded Botanist Notes",
		},
	},
	[443638] = {
		readable = "Mosswool Flower",
		model = 3882683,
		text = {
			en = "Mosswool Flower",
			es = "Mosswool Flower",
			de = "Mosswool Flower",
			fr = "Mosswool Flower",
			it = "Mosswool Flower",
			pt = "Mosswool Flower",
			ru = "Mosswool Flower",
			ko = "Mosswool Flower",
			cn = "Mosswool Flower",
		},
	},
	[444065] = {
		readable = "Elemental Geode",
		text = {
			en = "Elemental Geode",
			es = "Elemental Geode",
			de = "Elemental Geode",
			fr = "Elemental Geode",
			it = "Elemental Geode",
			pt = "Elemental Geode",
			ru = "Elemental Geode",
			ko = "Elemental Geode",
			cn = "Elemental Geode",
		},
	},
	[444137] = {
		readable = "Thak's Treasure",
		text = {
			en = "Thak's Treasure",
			es = "Thak's Treasure",
			de = "Thak's Treasure",
			fr = "Thak's Treasure",
			it = "Thak's Treasure",
			pt = "Thak's Treasure",
			ru = "Thak's Treasure",
			ko = "Thak's Treasure",
			cn = "Thak's Treasure",
		},
	},
	[444773] = {
		readable = "Jade Pearl",
		text = {
			en = "Jade Pearl",
			es = "Jade Pearl",
			de = "Jade Pearl",
			fr = "Jade Pearl",
			it = "Jade Pearl",
			pt = "Jade Pearl",
			ru = "Jade Pearl",
			ko = "Jade Pearl",
			cn = "Jade Pearl",
		},
	},
	[444894] = {
		readable = "Shimmering Opal Lily",
		model = 1146686,
		text = {
			en = "Shimmering Opal Lily",
			es = "Shimmering Opal Lily",
			de = "Shimmering Opal Lily",
			fr = "Shimmering Opal Lily",
			it = "Shimmering Opal Lily",
			pt = "Shimmering Opal Lily",
			ru = "Shimmering Opal Lily",
			ko = "Shimmering Opal Lily",
			cn = "Shimmering Opal Lily",
		},
	},
	[444899] = {
		readable = "Kobold Axe",
		text = {
			en = "Kobold Axe",
			es = "Kobold Axe",
			de = "Kobold Axe",
			fr = "Kobold Axe",
			it = "Kobold Axe",
			pt = "Kobold Axe",
			ru = "Kobold Axe",
			ko = "Kobold Axe",
			cn = "Kobold Axe",
		},
	},
	[446473] = {
		readable = "Infused Cinderbrew",
		text = {
			en = "Infused Cinderbrew",
			es = "Infused Cinderbrew",
			de = "Infused Cinderbrew",
			fr = "Infused Cinderbrew",
			it = "Infused Cinderbrew",
			pt = "Infused Cinderbrew",
			ru = "Infused Cinderbrew",
			ko = "Infused Cinderbrew",
			cn = "Infused Cinderbrew",
		},
	},
	[446476] = {
		readable = "Web-wrapped Axe",
		text = {
			en = "Web-wrapped Axe",
			es = "Web-wrapped Axe",
			de = "Web-wrapped Axe",
			fr = "Web-wrapped Axe",
			it = "Web-wrapped Axe",
			pt = "Web-wrapped Axe",
			ru = "Web-wrapped Axe",
			ko = "Web-wrapped Axe",
			cn = "Web-wrapped Axe",
		},
	},
})
do ObjectDB[objectID] = objectData; end