local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[420053] = {
		readable = "Webbed Knapsack",
		model = 1254446,
		text = {
			en = "Webbed Knapsack",
			es = "Webbed Knapsack",
			de = "Webbed Knapsack",
			fr = "Webbed Knapsack",
			it = "Webbed Knapsack",
			pt = "Webbed Knapsack",
			ru = "Webbed Knapsack",
			ko = "Webbed Knapsack",
			cn = "Webbed Knapsack",
		},
	},
	[423581] = {
		readable = "Broodmother's Egg",
		model = 3026077,
		text = {
			en = "Broodmother's Egg",
			es = "Broodmother's Egg",
			de = "Broodmother's Egg",
			fr = "Broodmother's Egg",
			it = "Broodmother's Egg",
			pt = "Broodmother's Egg",
			ru = "Broodmother's Egg",
			ko = "Broodmother's Egg",
			cn = "Broodmother's Egg",
		},
	},
	[433733] = {
		readable = "Forgotten Treasure",
		text = {
			en = "Forgotten Treasure",
			es = "Forgotten Treasure",
			de = "Forgotten Treasure",
			fr = "Forgotten Treasure",
			it = "Forgotten Treasure",
			pt = "Forgotten Treasure",
			ru = "Forgotten Treasure",
			ko = "Forgotten Treasure",
			cn = "Forgotten Treasure",
		},
	},
	[433757] = {
		readable = "Buried Treasure",
		text = {
			en = "Buried Treasure",
			es = "Buried Treasure",
			de = "Buried Treasure",
			fr = "Buried Treasure",
			it = "Buried Treasure",
			pt = "Buried Treasure",
			ru = "Buried Treasure",
			ko = "Buried Treasure",
			cn = "Buried Treasure",
		},
	},
	[433773] = {
		readable = "Buried Treasure",
		text = {
			en = "Buried Treasure",
			es = "Buried Treasure",
			de = "Buried Treasure",
			fr = "Buried Treasure",
			it = "Buried Treasure",
			pt = "Buried Treasure",
			ru = "Buried Treasure",
			ko = "Buried Treasure",
			cn = "Buried Treasure",
		},
	},
	[433774] = {
		readable = "Buried Treasure",
		text = {
			en = "Buried Treasure",
			es = "Buried Treasure",
			de = "Buried Treasure",
			fr = "Buried Treasure",
			it = "Buried Treasure",
			pt = "Buried Treasure",
			ru = "Buried Treasure",
			ko = "Buried Treasure",
			cn = "Buried Treasure",
		},
	},
	[433776] = {
		readable = "Buried Treasure",
		text = {
			en = "Buried Treasure",
			es = "Buried Treasure",
			de = "Buried Treasure",
			fr = "Buried Treasure",
			it = "Buried Treasure",
			pt = "Buried Treasure",
			ru = "Buried Treasure",
			ko = "Buried Treasure",
			cn = "Buried Treasure",
		},
	},
	[443532] = {
		readable = "Rusted Lever",
		text = {
			en = "Rusted Lever",
			es = "Rusted Lever",
			de = "Rusted Lever",
			fr = "Rusted Lever",
			it = "Rusted Lever",
			pt = "Rusted Lever",
			ru = "Rusted Lever",
			ko = "Rusted Lever",
			cn = "Rusted Lever",
		},
	},
	[444071] = {
		readable = "Cursed Pickaxe",
		text = {
			en = "Cursed Pickaxe",
			es = "Cursed Pickaxe",
			de = "Cursed Pickaxe",
			fr = "Cursed Pickaxe",
			it = "Cursed Pickaxe",
			pt = "Cursed Pickaxe",
			ru = "Cursed Pickaxe",
			ko = "Cursed Pickaxe",
			cn = "Cursed Pickaxe",
		},
	},
	[444087] = {
		readable = "Munderut's Forgotten Stash",
		text = {
			en = "Munderut's Forgotten Stash",
			es = "Munderut's Forgotten Stash",
			de = "Munderut's Forgotten Stash",
			fr = "Munderut's Forgotten Stash",
			it = "Munderut's Forgotten Stash",
			pt = "Munderut's Forgotten Stash",
			ru = "Munderut's Forgotten Stash",
			ko = "Munderut's Forgotten Stash",
			cn = "Munderut's Forgotten Stash",
		},
	},
	[444115] = {
		readable = "Discarded Toolbox",
		text = {
			en = "Discarded Toolbox",
			es = "Discarded Toolbox",
			de = "Discarded Toolbox",
			fr = "Discarded Toolbox",
			it = "Discarded Toolbox",
			pt = "Discarded Toolbox",
			ru = "Discarded Toolbox",
			ko = "Discarded Toolbox",
			cn = "Discarded Toolbox",
		},
	},
	[445403] = {
		readable = "Scary Dark Chest",
		text = {
			en = "Scary Dark Chest",
			es = "Scary Dark Chest",
			de = "Scary Dark Chest",
			fr = "Scary Dark Chest",
			it = "Scary Dark Chest",
			pt = "Scary Dark Chest",
			ru = "Scary Dark Chest",
			ko = "Scary Dark Chest",
			cn = "Scary Dark Chest",
		},
	},
	[446100] = {
		readable = "Blocked Intake",
		text = {
			en = "Blocked Intake",
			es = "Blocked Intake",
			de = "Blocked Intake",
			fr = "Blocked Intake",
			it = "Blocked Intake",
			pt = "Blocked Intake",
			ru = "Blocked Intake",
			ko = "Blocked Intake",
			cn = "Blocked Intake",
		},
	},
	[446151] = {
		readable = "Dislodged Blockage",
		text = {
			en = "Dislodged Blockage",
			es = "Dislodged Blockage",
			de = "Dislodged Blockage",
			fr = "Dislodged Blockage",
			it = "Dislodged Blockage",
			pt = "Dislodged Blockage",
			ru = "Dislodged Blockage",
			ko = "Dislodged Blockage",
			cn = "Dislodged Blockage",
		},
	},
	[446341] = {
		readable = "Dusty Prospector's Chest",
		text = {
			en = "Dusty Prospector's Chest",
			es = "Dusty Prospector's Chest",
			de = "Dusty Prospector's Chest",
			fr = "Dusty Prospector's Chest",
			it = "Dusty Prospector's Chest",
			pt = "Dusty Prospector's Chest",
			ru = "Dusty Prospector's Chest",
			ko = "Dusty Prospector's Chest",
			cn = "Dusty Prospector's Chest",
		},
	},
	[446495] = {
		readable = "Pile of Refuse",
		model = 1255023,
		text = {
			en = "Pile of Refuse",
			es = "Pile of Refuse",
			de = "Pile of Refuse",
			fr = "Pile of Refuse",
			it = "Pile of Refuse",
			pt = "Pile of Refuse",
			ru = "Pile of Refuse",
			ko = "Pile of Refuse",
			cn = "Pile of Refuse",
		},
	},
	[452696] = {
		readable = "Machine Speaker's Reliquary",
		text = {
			en = "Machine Speaker's Reliquary",
			es = "Machine Speaker's Reliquary",
			de = "Machine Speaker's Reliquary",
			fr = "Machine Speaker's Reliquary",
			it = "Machine Speaker's Reliquary",
			pt = "Machine Speaker's Reliquary",
			ru = "Machine Speaker's Reliquary",
			ko = "Machine Speaker's Reliquary",
			cn = "Machine Speaker's Reliquary",
		},
	},
	[452706] = {
		readable = "Deep-Lost Satchel",
		model = 3936818,
		text = {
			en = "Deep-Lost Satchel",
			es = "Deep-Lost Satchel",
			de = "Deep-Lost Satchel",
			fr = "Deep-Lost Satchel",
			it = "Deep-Lost Satchel",
			pt = "Deep-Lost Satchel",
			ru = "Deep-Lost Satchel",
			ko = "Deep-Lost Satchel",
			cn = "Deep-Lost Satchel",
		},
	},
	[452710] = {
		readable = "Brimming Deep-Lost Satchel",
		model = 4070769,
		text = {
			en = "Brimming Deep-Lost Satchel",
			es = "Brimming Deep-Lost Satchel",
			de = "Brimming Deep-Lost Satchel",
			fr = "Brimming Deep-Lost Satchel",
			it = "Brimming Deep-Lost Satchel",
			pt = "Brimming Deep-Lost Satchel",
			ru = "Brimming Deep-Lost Satchel",
			ko = "Brimming Deep-Lost Satchel",
			cn = "Brimming Deep-Lost Satchel",
		},
	},
	[455890] = {
		readable = "Waterlogged Refuse",
		model = 1254955,
		text = {
			en = "Waterlogged Refuse",
			es = "Waterlogged Refuse",
			de = "Waterlogged Refuse",
			fr = "Waterlogged Refuse",
			it = "Waterlogged Refuse",
			pt = "Waterlogged Refuse",
			ru = "Waterlogged Refuse",
			ko = "Waterlogged Refuse",
			cn = "Waterlogged Refuse",
		},
	},
})
do ObjectDB[objectID] = objectData; end