local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[441637] = {
		readable = "A Weathered Tome",
		text = {
			en = "A Weathered Tome",
			es = "A Weathered Tome",
			de = "A Weathered Tome",
			fr = "A Weathered Tome",
			it = "A Weathered Tome",
			pt = "A Weathered Tome",
			ru = "A Weathered Tome",
			ko = "A Weathered Tome",
			cn = "A Weathered Tome",
		},
	},
	[454201] = {
		readable = "Sturdy Chest",
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			de = "Sturdy Chest",
			fr = "Sturdy Chest",
			it = "Sturdy Chest",
			pt = "Sturdy Chest",
			ru = "Sturdy Chest",
			ko = "Sturdy Chest",
			cn = "Sturdy Chest",
		},
	},
	[454202] = {
		readable = "Sturdy Chest",
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			de = "Sturdy Chest",
			fr = "Sturdy Chest",
			it = "Sturdy Chest",
			pt = "Sturdy Chest",
			ru = "Sturdy Chest",
			ko = "Sturdy Chest",
			cn = "Sturdy Chest",
		},
	},
	[455486] = {
		readable = "Sturdy Chest",
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			de = "Sturdy Chest",
			fr = "Sturdy Chest",
			it = "Sturdy Chest",
			pt = "Sturdy Chest",
			ru = "Sturdy Chest",
			ko = "Sturdy Chest",
			cn = "Sturdy Chest",
		},
	},
	[455491] = {
		readable = "Sturdy Chest",
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			de = "Sturdy Chest",
			fr = "Sturdy Chest",
			it = "Sturdy Chest",
			pt = "Sturdy Chest",
			ru = "Sturdy Chest",
			ko = "Sturdy Chest",
			cn = "Sturdy Chest",
		},
	},
	[455494] = {
		readable = "Sturdy Chest",
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			de = "Sturdy Chest",
			fr = "Sturdy Chest",
			it = "Sturdy Chest",
			pt = "Sturdy Chest",
			ru = "Sturdy Chest",
			ko = "Sturdy Chest",
			cn = "Sturdy Chest",
		},
	},
	[455497] = {
		readable = "Sturdy Chest",
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			de = "Sturdy Chest",
			fr = "Sturdy Chest",
			it = "Sturdy Chest",
			pt = "Sturdy Chest",
			ru = "Sturdy Chest",
			ko = "Sturdy Chest",
			cn = "Sturdy Chest",
		},
	},
	[455505] = {
		readable = "Sturdy Chest",
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			de = "Sturdy Chest",
			fr = "Sturdy Chest",
			it = "Sturdy Chest",
			pt = "Sturdy Chest",
			ru = "Sturdy Chest",
			ko = "Sturdy Chest",
			cn = "Sturdy Chest",
		},
	},
	[455513] = {
		readable = "Sturdy Chest",
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			de = "Sturdy Chest",
			fr = "Sturdy Chest",
			it = "Sturdy Chest",
			pt = "Sturdy Chest",
			ru = "Sturdy Chest",
			ko = "Sturdy Chest",
			cn = "Sturdy Chest",
		},
	},
	[455517] = {
		readable = "Sturdy Chest",
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			de = "Sturdy Chest",
			fr = "Sturdy Chest",
			it = "Sturdy Chest",
			pt = "Sturdy Chest",
			ru = "Sturdy Chest",
			ko = "Sturdy Chest",
			cn = "Sturdy Chest",
		},
	},
	[455522] = {
		readable = "Sturdy Chest",
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			de = "Sturdy Chest",
			fr = "Sturdy Chest",
			it = "Sturdy Chest",
			pt = "Sturdy Chest",
			ru = "Sturdy Chest",
			ko = "Sturdy Chest",
			cn = "Sturdy Chest",
		},
	},
	[455525] = {
		readable = "Sturdy Chest",
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			de = "Sturdy Chest",
			fr = "Sturdy Chest",
			it = "Sturdy Chest",
			pt = "Sturdy Chest",
			ru = "Sturdy Chest",
			ko = "Sturdy Chest",
			cn = "Sturdy Chest",
		},
	},
	[455526] = {
		readable = "Sturdy Chest",
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			de = "Sturdy Chest",
			fr = "Sturdy Chest",
			it = "Sturdy Chest",
			pt = "Sturdy Chest",
			ru = "Sturdy Chest",
			ko = "Sturdy Chest",
			cn = "Sturdy Chest",
		},
	},
	[455534] = {
		readable = "Sturdy Chest",
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			de = "Sturdy Chest",
			fr = "Sturdy Chest",
			it = "Sturdy Chest",
			pt = "Sturdy Chest",
			ru = "Sturdy Chest",
			ko = "Sturdy Chest",
			cn = "Sturdy Chest",
		},
	},
	[455914] = {
		readable = "Mislaid Curiosity",
		model = 3936818,
		text = {
			en = "Mislaid Curiosity",
			es = "Mislaid Curiosity",
			de = "Mislaid Curiosity",
			fr = "Mislaid Curiosity",
			it = "Mislaid Curiosity",
			pt = "Mislaid Curiosity",
			ru = "Mislaid Curiosity",
			ko = "Mislaid Curiosity",
			cn = "Mislaid Curiosity",
		},
	},
})
do ObjectDB[objectID] = objectData; end