local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[429303] = {
		readable = "Angrily-Scrawled Poster",
		text = {
			en = "Angrily-Scrawled Poster",
			es = "Angrily-Scrawled Poster",
			de = "Angrily-Scrawled Poster",
			fr = "Angrily-Scrawled Poster",
			it = "Angrily-Scrawled Poster",
			pt = "Angrily-Scrawled Poster",
			ru = "Angrily-Scrawled Poster",
			ko = "Angrily-Scrawled Poster",
			cn = "Angrily-Scrawled Poster",
		},
	},
	[455690] = {
		readable = "DELVER'S CALL: Mycomancer Cavern",
		text = {
			en = "DELVER'S CALL: Mycomancer Cavern",
			es = "DELVER'S CALL: Mycomancer Cavern",
			de = "DELVER'S CALL: Mycomancer Cavern",
			fr = "DELVER'S CALL: Mycomancer Cavern",
			it = "DELVER'S CALL: Mycomancer Cavern",
			pt = "DELVER'S CALL: Mycomancer Cavern",
			ru = "DELVER'S CALL: Mycomancer Cavern",
			ko = "DELVER'S CALL: Mycomancer Cavern",
			cn = "DELVER'S CALL: Mycomancer Cavern",
		},
	},
	[455694] = {
		readable = "DELVER'S CALL: Skittering Breach",
		text = {
			en = "DELVER'S CALL: Skittering Breach",
			es = "DELVER'S CALL: Skittering Breach",
			de = "DELVER'S CALL: Skittering Breach",
			fr = "DELVER'S CALL: Skittering Breach",
			it = "DELVER'S CALL: Skittering Breach",
			pt = "DELVER'S CALL: Skittering Breach",
			ru = "DELVER'S CALL: Skittering Breach",
			ko = "DELVER'S CALL: Skittering Breach",
			cn = "DELVER'S CALL: Skittering Breach",
		},
	},
	[456002] = {
		readable = "Void Shard",
		model = 1058987,
		text = {
			en = "Void Shard",
			es = "Void Shard",
			de = "Void Shard",
			fr = "Void Shard",
			it = "Void Shard",
			pt = "Void Shard",
			ru = "Void Shard",
			ko = "Void Shard",
			cn = "Void Shard",
		},
	},
	[456003] = {
		readable = "Book of Dark Magic",
		text = {
			en = "Book of Dark Magic",
			es = "Book of Dark Magic",
			de = "Book of Dark Magic",
			fr = "Book of Dark Magic",
			it = "Book of Dark Magic",
			pt = "Book of Dark Magic",
			ru = "Book of Dark Magic",
			ko = "Book of Dark Magic",
			cn = "Book of Dark Magic",
		},
	},
	[456005] = {
		readable = "Essence of Holy Fire",
		text = {
			en = "Essence of Holy Fire",
			es = "Essence of Holy Fire",
			de = "Essence of Holy Fire",
			fr = "Essence of Holy Fire",
			it = "Essence of Holy Fire",
			pt = "Essence of Holy Fire",
			ru = "Essence of Holy Fire",
			ko = "Essence of Holy Fire",
			cn = "Essence of Holy Fire",
		},
	},
	[456007] = {
		readable = "Soot-Coated Orb",
		model = 4214138,
		text = {
			en = "Soot-Coated Orb",
			es = "Soot-Coated Orb",
			de = "Soot-Coated Orb",
			fr = "Soot-Coated Orb",
			it = "Soot-Coated Orb",
			pt = "Soot-Coated Orb",
			ru = "Soot-Coated Orb",
			ko = "Soot-Coated Orb",
			cn = "Soot-Coated Orb",
		},
	},
	[456008] = {
		readable = "Silver Dornogal Rod",
		model = 929389,
		text = {
			en = "Silver Dornogal Rod",
			es = "Silver Dornogal Rod",
			de = "Silver Dornogal Rod",
			fr = "Silver Dornogal Rod",
			it = "Silver Dornogal Rod",
			pt = "Silver Dornogal Rod",
			ru = "Silver Dornogal Rod",
			ko = "Silver Dornogal Rod",
			cn = "Silver Dornogal Rod",
		},
	},
	[456018] = {
		readable = "Dark Apothecary's Vial",
		text = {
			en = "Dark Apothecary's Vial",
			es = "Dark Apothecary's Vial",
			de = "Dark Apothecary's Vial",
			fr = "Dark Apothecary's Vial",
			it = "Dark Apothecary's Vial",
			pt = "Dark Apothecary's Vial",
			ru = "Dark Apothecary's Vial",
			ko = "Dark Apothecary's Vial",
			cn = "Dark Apothecary's Vial",
		},
	},
	[456019] = {
		readable = "Nerubian Mixing Salts",
		model = 1310395,
		text = {
			en = "Nerubian Mixing Salts",
			es = "Nerubian Mixing Salts",
			de = "Nerubian Mixing Salts",
			fr = "Nerubian Mixing Salts",
			it = "Nerubian Mixing Salts",
			pt = "Nerubian Mixing Salts",
			ru = "Nerubian Mixing Salts",
			ko = "Nerubian Mixing Salts",
			cn = "Nerubian Mixing Salts",
		},
	},
	[456020] = {
		readable = "Sanctified Mortar and Pestle",
		model = 1240452,
		text = {
			en = "Sanctified Mortar and Pestle",
			es = "Sanctified Mortar and Pestle",
			de = "Sanctified Mortar and Pestle",
			fr = "Sanctified Mortar and Pestle",
			it = "Sanctified Mortar and Pestle",
			pt = "Sanctified Mortar and Pestle",
			ru = "Sanctified Mortar and Pestle",
			ko = "Sanctified Mortar and Pestle",
			cn = "Sanctified Mortar and Pestle",
		},
	},
	[456021] = {
		readable = "Chemist's Purified Water",
		text = {
			en = "Chemist's Purified Water",
			es = "Chemist's Purified Water",
			de = "Chemist's Purified Water",
			fr = "Chemist's Purified Water",
			it = "Chemist's Purified Water",
			pt = "Chemist's Purified Water",
			ru = "Chemist's Purified Water",
			ko = "Chemist's Purified Water",
			cn = "Chemist's Purified Water",
		},
	},
	[456023] = {
		readable = "Reinforced Beaker",
		text = {
			en = "Reinforced Beaker",
			es = "Reinforced Beaker",
			de = "Reinforced Beaker",
			fr = "Reinforced Beaker",
			it = "Reinforced Beaker",
			pt = "Reinforced Beaker",
			ru = "Reinforced Beaker",
			ko = "Reinforced Beaker",
			cn = "Reinforced Beaker",
		},
	},
})
do ObjectDB[objectID] = objectData; end