local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[455183] = {
		readable = "Shadow Curfew Journal",
		model = 5387323,
		text = {
			en = "Shadow Curfew Journal",
			es = "Diario de toque de queda sombrío",
			de = "Journal der Schattensperrstunde",
			fr = "Journal du couvre-feu de l’ombre",
			it = "Diario del Coprifuoco d'Ombra",
			pt = "Diário do Toque de Recolher das Sombras",
			ru = "Журнал теневого комендантского часа",
			ko = "어둠 통행 금지 일지",
			cn = "《暗影宵禁日志》",
		},
	},
	[455269] = {
		readable = "Notes On The Machine Speakers: Fragment I",
		model = 3978480,
		text = {
			en = "Notes On The Machine Speakers: Fragment I",
			es = "Notas sobre los Mecaoradores: fragmento I",
			de = "Notizen zu den Maschinenflüsterern: Fragment I",
			fr = "Notes sur les mandataires des machines : fragment I",
			it = "Appunti sugli Oratori delle Macchine: Frammento I",
			pt = "Anotações Sobre os Mensageiros Mecânicos: Fragmento I",
			ru = "Записи о глашатаях механизмов: фрагмент I",
			ko = "기계 대변자 기록: 파편 I",
			cn = "机语者记事：碎片I",
		},
	},
	[455274] = {
		readable = "Notes On The Machine Speakers: Fragment II",
		model = 3978480,
		text = {
			en = "Notes On The Machine Speakers: Fragment II",
			es = "Notas sobre los Mecaoradores: fragmento II",
			de = "Notizen zu den Maschinenflüsterern: Fragment II",
			fr = "Notes sur les mandataires des machines : fragment II",
			it = "Appunti sugli Oratori delle Macchine: Frammento II",
			pt = "Anotações Sobre os Mensageiros Mecânicos: Fragmento II",
			ru = "Записи о глашатаях механизмов: фрагмент II",
			ko = "기계 대변자 기록: 파편 II",
			cn = "机语者记事：碎片II",
		},
	},
	[455275] = {
		readable = "Notes On The Machine Speakers: Fragment III",
		model = 3978480,
		text = {
			en = "Notes On The Machine Speakers: Fragment III",
			es = "Notas sobre los Mecaoradores: fragmento III",
			de = "Notizen zu den Maschinenflüsterern: Fragment III",
			fr = "Notes sur les mandataires des machines : fragment III",
			it = "Appunti sugli Oratori delle Macchine: Frammento III",
			pt = "Anotações Sobre os Mensageiros Mecânicos: Fragmento III",
			ru = "Записи о глашатаях механизмов: фрагмент III",
			ko = "기계 대변자 기록: 파편 III",
			cn = "机语者记事：碎片III",
		},
	},
	[455276] = {
		readable = "Notes On The Machine Speakers: Fragment IV",
		model = 3978480,
		text = {
			en = "Notes On The Machine Speakers: Fragment IV",
			es = "Notas sobre los Mecaoradores: fragmento IV",
			de = "Notizen zu den Maschinenflüsterern: Fragment IV",
			fr = "Notes sur les mandataires des machines : fragment IV",
			it = "Appunti sugli Oratori delle Macchine: Frammento IV",
			pt = "Anotações Sobre os Mensageiros Mecânicos: Fragmento IV",
			ru = "Записи о глашатаях механизмов: фрагмент IV",
			ko = "기계 대변자 기록: 파편 IV",
			cn = "机语者记事：碎片IV",
		},
	},
	[455277] = {
		readable = "Notes On The Machine Speakers: Fragment V",
		model = 3978480,
		text = {
			en = "Notes On The Machine Speakers: Fragment V",
			es = "Notas sobre los Mecaoradores: fragmento V",
			de = "Notizen zu den Maschinenflüsterern: Fragment V",
			fr = "Notes sur les mandataires des machines : fragment V",
			it = "Appunti sugli Oratori delle Macchine: Frammento V",
			pt = "Anotações Sobre os Mensageiros Mecânicos: Fragmento V",
			ru = "Записи о глашатаях механизмов: фрагмент V",
			ko = "기계 대변자 기록: 파편 V",
			cn = "机语者记事：碎片V",
		},
	},
	[455278] = {
		readable = "Notes On The Machine Speakers: Fragment VI",
		model = 3978480,
		text = {
			en = "Notes On The Machine Speakers: Fragment VI",
			es = "Notas sobre los Mecaoradores: fragmento VI",
			de = "Notizen zu den Maschinenflüsterern: Fragment VI",
			fr = "Notes sur les mandataires des machines : fragment VI",
			it = "Appunti sugli Oratori delle Macchine: Frammento VI",
			pt = "Anotações Sobre os Mensageiros Mecânicos: Fragmento VI",
			ru = "Записи о глашатаях механизмов: фрагмент VI",
			ko = "기계 대변자 기록: 파편 VI",
			cn = "机语者记事：碎片VI",
		},
	},
})
do ObjectDB[objectID] = objectData; end