local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[419695] = {
		readable = "Spore-Covered Coffer",
		text = {
			en = "Spore-Covered Coffer",
			es = "Spore-Covered Coffer",
			de = "Spore-Covered Coffer",
			fr = "Spore-Covered Coffer",
			it = "Spore-Covered Coffer",
			pt = "Spore-Covered Coffer",
			ru = "Spore-Covered Coffer",
			ko = "Spore-Covered Coffer",
			cn = "Spore-Covered Coffer",
		},
	},
	[424347] = {
		readable = "Empty Crab Cage",
		model = 1611366,
		text = {
			en = "Empty Crab Cage",
			es = "Empty Crab Cage",
			de = "Empty Crab Cage",
			fr = "Empty Crab Cage",
			it = "Empty Crab Cage",
			pt = "Empty Crab Cage",
			ru = "Empty Crab Cage",
			ko = "Empty Crab Cage",
			cn = "Empty Crab Cage",
		},
	},
	[430581] = {
		readable = "Egg Basket",
		model = 1709396,
		text = {
			en = "Egg Basket",
			es = "Egg Basket",
			de = "Egg Basket",
			fr = "Egg Basket",
			it = "Egg Basket",
			pt = "Egg Basket",
			ru = "Egg Basket",
			ko = "Egg Basket",
			cn = "Egg Basket",
		},
	},
	[437211] = {
		readable = "Illuminated Footlocker",
		text = {
			en = "Illuminated Footlocker",
			es = "Illuminated Footlocker",
			de = "Illuminated Footlocker",
			fr = "Illuminated Footlocker",
			it = "Illuminated Footlocker",
			pt = "Illuminated Footlocker",
			ru = "Illuminated Footlocker",
			ko = "Illuminated Footlocker",
			cn = "Illuminated Footlocker",
		},
	},
	[437302] = {
		readable = "Fisherman's Pouch",
		text = {
			en = "Fisherman's Pouch",
			es = "Fisherman's Pouch",
			de = "Fisherman's Pouch",
			fr = "Fisherman's Pouch",
			it = "Fisherman's Pouch",
			pt = "Fisherman's Pouch",
			ru = "Fisherman's Pouch",
			ko = "Fisherman's Pouch",
			cn = "Fisherman's Pouch",
		},
	},
	[441606] = {
		readable = "Jewel of the Cliffs",
		text = {
			en = "Jewel of the Cliffs",
			es = "Jewel of the Cliffs",
			de = "Jewel of the Cliffs",
			fr = "Jewel of the Cliffs",
			it = "Jewel of the Cliffs",
			pt = "Jewel of the Cliffs",
			ru = "Jewel of the Cliffs",
			ko = "Jewel of the Cliffs",
			cn = "Jewel of the Cliffs",
		},
	},
	[441611] = {
		readable = "Windswept Satchel",
		text = {
			en = "Windswept Satchel",
			es = "Windswept Satchel",
			de = "Windswept Satchel",
			fr = "Windswept Satchel",
			it = "Windswept Satchel",
			pt = "Windswept Satchel",
			ru = "Windswept Satchel",
			ko = "Windswept Satchel",
			cn = "Windswept Satchel",
		},
	},
	[441638] = {
		readable = "Lost Memento",
		model = 4551443,
		text = {
			en = "Lost Memento",
			es = "Lost Memento",
			de = "Lost Memento",
			fr = "Lost Memento",
			it = "Lost Memento",
			pt = "Lost Memento",
			ru = "Lost Memento",
			ko = "Lost Memento",
			cn = "Lost Memento",
		},
	},
	[441740] = {
		readable = "The Light's Call",
		text = {
			en = "The Light's Call",
			es = "The Light's Call",
			de = "The Light's Call",
			fr = "The Light's Call",
			it = "The Light's Call",
			pt = "The Light's Call",
			ru = "The Light's Call",
			ko = "The Light's Call",
			cn = "The Light's Call",
		},
	},
	[444798] = {
		readable = "Arathi Treasure Hoard",
		text = {
			en = "Arathi Treasure Hoard",
			es = "Arathi Treasure Hoard",
			de = "Arathi Treasure Hoard",
			fr = "Arathi Treasure Hoard",
			it = "Arathi Treasure Hoard",
			pt = "Arathi Treasure Hoard",
			ru = "Arathi Treasure Hoard",
			ko = "Arathi Treasure Hoard",
			cn = "Arathi Treasure Hoard",
		},
	},
	[444801] = {
		readable = "Brimming Arathi Treasure Hoard",
		text = {
			en = "Brimming Arathi Treasure Hoard",
			es = "Brimming Arathi Treasure Hoard",
			de = "Brimming Arathi Treasure Hoard",
			fr = "Brimming Arathi Treasure Hoard",
			it = "Brimming Arathi Treasure Hoard",
			pt = "Brimming Arathi Treasure Hoard",
			ru = "Brimming Arathi Treasure Hoard",
			ko = "Brimming Arathi Treasure Hoard",
			cn = "Brimming Arathi Treasure Hoard",
		},
	},
	[444802] = {
		readable = "Kobyss Ritual Cache",
		text = {
			en = "Kobyss Ritual Cache",
			es = "Kobyss Ritual Cache",
			de = "Kobyss Ritual Cache",
			fr = "Kobyss Ritual Cache",
			it = "Kobyss Ritual Cache",
			pt = "Kobyss Ritual Cache",
			ru = "Kobyss Ritual Cache",
			ko = "Kobyss Ritual Cache",
			cn = "Kobyss Ritual Cache",
		},
	},
	[444804] = {
		readable = "Concentrated Shadow",
		model = 4681253,
		text = {
			en = "Concentrated Shadow",
			es = "Concentrated Shadow",
			de = "Concentrated Shadow",
			fr = "Concentrated Shadow",
			it = "Concentrated Shadow",
			pt = "Concentrated Shadow",
			ru = "Concentrated Shadow",
			ko = "Concentrated Shadow",
			cn = "Concentrated Shadow",
		},
	},
	[453283] = {
		readable = "Smuggler's Treasure",
		text = {
			en = "Smuggler's Treasure",
			es = "Smuggler's Treasure",
			de = "Smuggler's Treasure",
			fr = "Smuggler's Treasure",
			it = "Smuggler's Treasure",
			pt = "Smuggler's Treasure",
			ru = "Smuggler's Treasure",
			ko = "Smuggler's Treasure",
			cn = "Smuggler's Treasure",
		},
	},
	[453359] = {
		readable = "Dark Ritual",
		text = {
			en = "Dark Ritual",
			es = "Dark Ritual",
			de = "Dark Ritual",
			fr = "Dark Ritual",
			it = "Dark Ritual",
			pt = "Dark Ritual",
			ru = "Dark Ritual",
			ko = "Dark Ritual",
			cn = "Dark Ritual",
		},
	},
	[453374] = {
		readable = "Shadowed Essence",
		model = 4681253,
		text = {
			en = "Shadowed Essence",
			es = "Shadowed Essence",
			de = "Shadowed Essence",
			fr = "Shadowed Essence",
			it = "Shadowed Essence",
			pt = "Shadowed Essence",
			ru = "Shadowed Essence",
			ko = "Shadowed Essence",
			cn = "Shadowed Essence",
		},
	},
	[453749] = {
		readable = "Palawltar's Codex of Dimensional Structure",
		text = {
			en = "Palawltar's Codex of Dimensional Structure",
			es = "Palawltar's Codex of Dimensional Structure",
			de = "Palawltar's Codex of Dimensional Structure",
			fr = "Palawltar's Codex of Dimensional Structure",
			it = "Palawltar's Codex of Dimensional Structure",
			pt = "Palawltar's Codex of Dimensional Structure",
			ru = "Palawltar's Codex of Dimensional Structure",
			ko = "Palawltar's Codex of Dimensional Structure",
			cn = "Palawltar's Codex of Dimensional Structure",
		},
	},
	[453751] = {
		readable = "Care and Feeding of the Imperial Lynx",
		text = {
			en = "Care and Feeding of the Imperial Lynx",
			es = "Care and Feeding of the Imperial Lynx",
			de = "Care and Feeding of the Imperial Lynx",
			fr = "Care and Feeding of the Imperial Lynx",
			it = "Care and Feeding of the Imperial Lynx",
			pt = "Care and Feeding of the Imperial Lynx",
			ru = "Care and Feeding of the Imperial Lynx",
			ko = "Care and Feeding of the Imperial Lynx",
			cn = "Care and Feeding of the Imperial Lynx",
		},
	},
	[455704] = {
		readable = "DELVER'S CALL: The Sinkhole",
		text = {
			en = "DELVER'S CALL: The Sinkhole",
			es = "DELVER'S CALL: The Sinkhole",
			de = "DELVER'S CALL: The Sinkhole",
			fr = "DELVER'S CALL: The Sinkhole",
			it = "DELVER'S CALL: The Sinkhole",
			pt = "DELVER'S CALL: The Sinkhole",
			ru = "DELVER'S CALL: The Sinkhole",
			ko = "DELVER'S CALL: The Sinkhole",
			cn = "DELVER'S CALL: The Sinkhole",
		},
	},
})
do ObjectDB[objectID] = objectData; end