local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[455956] = {
		readable = "Devout Archaeologist's Excavator",
		text = {
			en = "Devout Archaeologist's Excavator",
			es = "Devout Archaeologist's Excavator",
			de = "Devout Archaeologist's Excavator",
			fr = "Devout Archaeologist's Excavator",
			it = "Devout Archaeologist's Excavator",
			pt = "Devout Archaeologist's Excavator",
			ru = "Devout Archaeologist's Excavator",
			ko = "Devout Archaeologist's Excavator",
			cn = "Devout Archaeologist's Excavator",
		},
	},
	[455957] = {
		readable = "Arathi Precision Drill",
		text = {
			en = "Arathi Precision Drill",
			es = "Arathi Precision Drill",
			de = "Arathi Precision Drill",
			fr = "Arathi Precision Drill",
			it = "Arathi Precision Drill",
			pt = "Arathi Precision Drill",
			ru = "Arathi Precision Drill",
			ko = "Arathi Precision Drill",
			cn = "Arathi Precision Drill",
		},
	},
	[455960] = {
		readable = "Dornogal Chisel",
		text = {
			en = "Dornogal Chisel",
			es = "Dornogal Chisel",
			de = "Dornogal Chisel",
			fr = "Dornogal Chisel",
			it = "Dornogal Chisel",
			pt = "Dornogal Chisel",
			ru = "Dornogal Chisel",
			ko = "Dornogal Chisel",
			cn = "Dornogal Chisel",
		},
	},
	[455961] = {
		readable = "Earthen Miner's Gavel",
		text = {
			en = "Earthen Miner's Gavel",
			es = "Earthen Miner's Gavel",
			de = "Earthen Miner's Gavel",
			fr = "Earthen Miner's Gavel",
			it = "Earthen Miner's Gavel",
			pt = "Earthen Miner's Gavel",
			ru = "Earthen Miner's Gavel",
			ko = "Earthen Miner's Gavel",
			cn = "Earthen Miner's Gavel",
		},
	},
	[455988] = {
		readable = "Arathi Herb Pruner",
		text = {
			en = "Arathi Herb Pruner",
			es = "Arathi Herb Pruner",
			de = "Arathi Herb Pruner",
			fr = "Arathi Herb Pruner",
			it = "Arathi Herb Pruner",
			pt = "Arathi Herb Pruner",
			ru = "Arathi Herb Pruner",
			ko = "Arathi Herb Pruner",
			cn = "Arathi Herb Pruner",
		},
	},
	[455989] = {
		readable = "Arathi Garden Trowel",
		text = {
			en = "Arathi Garden Trowel",
			es = "Arathi Garden Trowel",
			de = "Arathi Garden Trowel",
			fr = "Arathi Garden Trowel",
			it = "Arathi Garden Trowel",
			pt = "Arathi Garden Trowel",
			ru = "Arathi Garden Trowel",
			ko = "Arathi Garden Trowel",
			cn = "Arathi Garden Trowel",
		},
	},
	[455992] = {
		readable = "Dornogal Gardening Scythe",
		text = {
			en = "Dornogal Gardening Scythe",
			es = "Dornogal Gardening Scythe",
			de = "Dornogal Gardening Scythe",
			fr = "Dornogal Gardening Scythe",
			it = "Dornogal Gardening Scythe",
			pt = "Dornogal Gardening Scythe",
			ru = "Dornogal Gardening Scythe",
			ko = "Dornogal Gardening Scythe",
			cn = "Dornogal Gardening Scythe",
		},
	},
	[455993] = {
		readable = "Ancient Flower",
		text = {
			en = "Ancient Flower",
			es = "Ancient Flower",
			de = "Ancient Flower",
			fr = "Ancient Flower",
			it = "Ancient Flower",
			pt = "Ancient Flower",
			ru = "Ancient Flower",
			ko = "Ancient Flower",
			cn = "Ancient Flower",
		},
	},
})
do ObjectDB[objectID] = objectData; end