local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[409120] = {
		readable = "Cache of Cosmic Mysteries",
		model = 5338871,
		text = {
			en = "Cache of Cosmic Mysteries",
			es = "[Cache of Cosmic Mysteries]",
			de = "[Cache of Cosmic Mysteries]",
			fr = "[Cache of Cosmic Mysteries]",
			it = "[Cache of Cosmic Mysteries]",
			pt = "[Cache of Cosmic Mysteries]",
			ru = "[Cache of Cosmic Mysteries]",
			ko = "[Cache of Cosmic Mysteries]",
			cn = "[Cache of Cosmic Mysteries]",
		},
	},
	[409208] = {
		readable = "Broken Urn",
		model = 4609995,
		text = {
			en = "Broken Urn",
			es = "[Broken Urn]",
			de = "[Broken Urn]",
			fr = "[Broken Urn]",
			it = "[Broken Urn]",
			pt = "[Broken Urn]",
			ru = "[Broken Urn]",
			ko = "[Broken Urn]",
			cn = "[Broken Urn]",
		},
	},
	[409209] = {
		readable = "Broken Urn",
		model = 4609995,
		text = {
			en = "Broken Urn",
			es = "[Broken Urn]",
			de = "[Broken Urn]",
			fr = "[Broken Urn]",
			it = "[Broken Urn]",
			pt = "[Broken Urn]",
			ru = "[Broken Urn]",
			ko = "[Broken Urn]",
			cn = "[Broken Urn]",
		},
	},
	[409211] = {
		readable = "Broken Urn",
		model = 4609995,
		text = {
			en = "Broken Urn",
			es = "[Broken Urn]",
			de = "[Broken Urn]",
			fr = "[Broken Urn]",
			it = "[Broken Urn]",
			pt = "[Broken Urn]",
			ru = "[Broken Urn]",
			ko = "[Broken Urn]",
			cn = "[Broken Urn]",
		},
	},
	[409212] = {
		readable = "Broken Urn",
		model = 4609995,
		text = {
			en = "Broken Urn",
			es = "[Broken Urn]",
			de = "[Broken Urn]",
			fr = "[Broken Urn]",
			it = "[Broken Urn]",
			pt = "[Broken Urn]",
			ru = "[Broken Urn]",
			ko = "[Broken Urn]",
			cn = "[Broken Urn]",
		},
	},
	[409214] = {
		readable = "Broken Urn",
		model = 4609995,
		text = {
			en = "Broken Urn",
			es = "[Broken Urn]",
			de = "[Broken Urn]",
			fr = "[Broken Urn]",
			it = "[Broken Urn]",
			pt = "[Broken Urn]",
			ru = "[Broken Urn]",
			ko = "[Broken Urn]",
			cn = "[Broken Urn]",
		},
	},
})
do ObjectDB[objectID] = objectData; end