local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[444215] = {
		readable = "Mysterious Orb",
		model = 1450066,
		text = {
			en = "Mysterious Orb",
			es = "Mysterious Orb",
			de = "Mysterious Orb",
			fr = "Mysterious Orb",
			it = "Mysterious Orb",
			pt = "Mysterious Orb",
			ru = "Mysterious Orb",
			ko = "Mysterious Orb",
			cn = "Mysterious Orb",
		},
	},
	[454463] = {
		readable = "Wanted: The Boroughbreaker",
		text = {
			en = "Wanted: The Boroughbreaker",
			es = "Wanted: The Boroughbreaker",
			de = "Wanted: The Boroughbreaker",
			fr = "Wanted: The Boroughbreaker",
			it = "Wanted: The Boroughbreaker",
			pt = "Wanted: The Boroughbreaker",
			ru = "Wanted: The Boroughbreaker",
			ko = "Wanted: The Boroughbreaker",
			cn = "Wanted: The Boroughbreaker",
		},
	},
	[455713] = {
		readable = "DELVER'S CALL: Kriegval's Rest",
		text = {
			en = "DELVER'S CALL: Kriegval's Rest",
			es = "DELVER'S CALL: Kriegval's Rest",
			de = "DELVER'S CALL: Kriegval's Rest",
			fr = "DELVER'S CALL: Kriegval's Rest",
			it = "DELVER'S CALL: Kriegval's Rest",
			pt = "DELVER'S CALL: Kriegval's Rest",
			ru = "DELVER'S CALL: Kriegval's Rest",
			ko = "DELVER'S CALL: Kriegval's Rest",
			cn = "DELVER'S CALL: Kriegval's Rest",
		},
	},
	[455716] = {
		readable = "DELVER'S CALL: Fungal Folly",
		text = {
			en = "DELVER'S CALL: Fungal Folly",
			es = "DELVER'S CALL: Fungal Folly",
			de = "DELVER'S CALL: Fungal Folly",
			fr = "DELVER'S CALL: Fungal Folly",
			it = "DELVER'S CALL: Fungal Folly",
			pt = "DELVER'S CALL: Fungal Folly",
			ru = "DELVER'S CALL: Fungal Folly",
			ko = "DELVER'S CALL: Fungal Folly",
			cn = "DELVER'S CALL: Fungal Folly",
		},
	},
	[455951] = {
		readable = "Artisan's Drawing Knife",
		text = {
			en = "Artisan's Drawing Knife",
			es = "Artisan's Drawing Knife",
			de = "Artisan's Drawing Knife",
			fr = "Artisan's Drawing Knife",
			it = "Artisan's Drawing Knife",
			pt = "Artisan's Drawing Knife",
			ru = "Artisan's Drawing Knife",
			ko = "Artisan's Drawing Knife",
			cn = "Artisan's Drawing Knife",
		},
	},
	[455952] = {
		readable = "Earthen Worker's Beams",
		text = {
			en = "Earthen Worker's Beams",
			es = "Earthen Worker's Beams",
			de = "Earthen Worker's Beams",
			fr = "Earthen Worker's Beams",
			it = "Earthen Worker's Beams",
			pt = "Earthen Worker's Beams",
			ru = "Earthen Worker's Beams",
			ko = "Earthen Worker's Beams",
			cn = "Earthen Worker's Beams",
		},
	},
	[455953] = {
		readable = "Dornogal Carving Knife",
		text = {
			en = "Dornogal Carving Knife",
			es = "Dornogal Carving Knife",
			de = "Dornogal Carving Knife",
			fr = "Dornogal Carving Knife",
			it = "Dornogal Carving Knife",
			pt = "Dornogal Carving Knife",
			ru = "Dornogal Carving Knife",
			ko = "Dornogal Carving Knife",
			cn = "Dornogal Carving Knife",
		},
	},
	[455967] = {
		readable = "Underground Stropping Compound",
		model = 1310395,
		text = {
			en = "Underground Stropping Compound",
			es = "Underground Stropping Compound",
			de = "Underground Stropping Compound",
			fr = "Underground Stropping Compound",
			it = "Underground Stropping Compound",
			pt = "Underground Stropping Compound",
			ru = "Underground Stropping Compound",
			ko = "Underground Stropping Compound",
			cn = "Underground Stropping Compound",
		},
	},
	[455968] = {
		readable = "Dornogal Craftsman's Flat Knife",
		text = {
			en = "Dornogal Craftsman's Flat Knife",
			es = "Dornogal Craftsman's Flat Knife",
			de = "Dornogal Craftsman's Flat Knife",
			fr = "Dornogal Craftsman's Flat Knife",
			it = "Dornogal Craftsman's Flat Knife",
			pt = "Dornogal Craftsman's Flat Knife",
			ru = "Dornogal Craftsman's Flat Knife",
			ko = "Dornogal Craftsman's Flat Knife",
			cn = "Dornogal Craftsman's Flat Knife",
		},
	},
	[455969] = {
		readable = "Earthen Lacing Tools",
		text = {
			en = "Earthen Lacing Tools",
			es = "Earthen Lacing Tools",
			de = "Earthen Lacing Tools",
			fr = "Earthen Lacing Tools",
			it = "Earthen Lacing Tools",
			pt = "Earthen Lacing Tools",
			ru = "Earthen Lacing Tools",
			ko = "Earthen Lacing Tools",
			cn = "Earthen Lacing Tools",
		},
	},
	[456208] = {
		readable = "The Catalyst",
		text = {
			en = "The Catalyst",
			es = "The Catalyst",
			de = "The Catalyst",
			fr = "The Catalyst",
			it = "The Catalyst",
			pt = "The Catalyst",
			ru = "The Catalyst",
			ko = "The Catalyst",
			cn = "The Catalyst",
		},
	},
})
do ObjectDB[objectID] = objectData; end