local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[414199] = {
		readable = "Pile of Earthen Belongings",
		model = 5348714,
		text = {
			en = "Pile of Earthen Belongings",
			es = "Montón de pertenencias de los terráneos",
			de = "Haufen Irdeneneigentum",
			fr = "Tas de possessions terrestres",
			it = "Mucchio di Beni Terrigeni",
			pt = "Pilha de Pertences de Terrano",
			ru = "Куча вещей земельников",
			ko = "토석인 소지품 더미",
			cn = "一堆土灵所有物",
		},
	},
	[429301] = {
		readable = "Shipment Crate",
		model = 5128195,
		text = {
			en = "Shipment Crate",
			es = "Caja de transporte",
			de = "Lieferkiste",
			fr = "Caisse de cargaison",
			it = "Cassa di Spedizioni",
			pt = "Caixote do Carregamento",
			ru = "Груз ящиков",
			ko = "화물 상자",
			cn = "货箱",
		},
	},
	[430215] = {
		readable = "Molten Wax",
		model = 5465249,
		text = {
			en = "Molten Wax",
			es = "Cera derretida",
			de = "Geschmolzenes Wachs",
			fr = "Cire fondue",
			it = "Cera Fusa",
			pt = "Cera Derretida",
			ru = "Расплавленный воск",
			ko = "타오르는 밀랍",
			cn = "熔化蜡油",
		},
	},
	[430551] = {
		readable = "Coal Shipment",
		model = 5408535,
		text = {
			en = "Coal Shipment",
			es = "Coal Shipment",
			de = "Kohlelieferung",
			fr = "Coal Shipment",
			it = "Coal Shipment",
			pt = "Coal Shipment",
			ru = "Груз угля",
			ko = "Coal Shipment",
			cn = "Coal Shipment",
		},
	},
	[432893] = {
		readable = "Shipment Crate",
		model = 5128195,
		text = {
			en = "Shipment Crate",
			es = "Caja de transporte",
			de = "Lieferkiste",
			fr = "Caisse de cargaison",
			it = "Cassa di Spedizioni",
			pt = "Caixote do Carregamento",
			ru = "Груз ящиков",
			ko = "화물 상자",
			cn = "货箱",
		},
	},
	[432894] = {
		readable = "Shipment Crate",
		model = 5128195,
		text = {
			en = "Shipment Crate",
			es = "Caja de transporte",
			de = "Lieferkiste",
			fr = "Caisse de cargaison",
			it = "Cassa di Spedizioni",
			pt = "Caixote do Carregamento",
			ru = "Груз ящиков",
			ko = "화물 상자",
			cn = "货箱",
		},
	},
	[433090] = {
		readable = "Infused Underclay",
		model = 3851915,
		text = {
			en = "Infused Underclay",
			es = "Sotoarcilla imbuida",
			de = "Energieerfüllter Unterton",
			fr = "Argile imprégnée",
			it = "Sottostrato Argilloso Infuso",
			pt = "Subargila Infusa",
			ru = "Зачарованная глина",
			ko = "주입된 지하점토",
			cn = "注能幽泥",
		},
	},
	[433101] = {
		readable = "Bag of Glowing Shards",
		model = 5209191,
		text = {
			en = "Bag of Glowing Shards",
			es = "Bolsa de fragmentos resplandecientes",
			de = "Tasche mit leuchtenden Splittern",
			fr = "Sac d’éclats luminescents",
			it = "Borsa di Schegge Luminose",
			pt = "Bolsa de Estilhaços Brilhantes",
			ru = "Мешок светящихся осколков",
			ko = "빛나는 조각 가방",
			cn = "一袋发光碎片",
		},
	},
	[433102] = {
		readable = "Bundle of Receipts",
		model = 5409332,
		text = {
			en = "Bundle of Receipts",
			es = "Fardo de recibos",
			de = "Belegbündel",
			fr = "Liasse de reçus",
			it = "Mucchio di Ricevute",
			pt = "Monte de Recibos",
			ru = "Стопка квитанций",
			ko = "영수증 묶음",
			cn = "一叠收据",
		},
	},
	[433109] = {
		readable = "Nerubian Silk Ropes",
		model = 5516435,
		text = {
			en = "Nerubian Silk Ropes",
			es = "Cuerdas de seda nerubianas",
			de = "Nerubische Seidenseile",
			fr = "Cordes en soie nérubienne",
			it = "Corde di Seta dei Nerubiani",
			pt = "Corda de Seda Nerubiana",
			ru = "Нерубские шелковые веревки",
			ko = "네루비안 비단 밧줄",
			cn = "蛛魔丝绳",
		},
	},
	[455945] = {
		readable = "Dornogal Seam Ripper",
		model = 5205910,
		text = {
			en = "Dornogal Seam Ripper",
			es = "Abridor de costuras de Dornogal",
			de = "Trennmesser aus Dornogal",
			fr = "Découd-vite de Dornogal",
			it = "Taglia Asole di Dornogal",
			pt = "Dornogal Seam Ripper",
			ru = "Дорногальский вспарыватель",
			ko = "Dornogal Seam Ripper",
			cn = "多恩诺嘉尔拆线刀",
		},
	},
})
do ObjectDB[objectID] = objectData; end