local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[322469] = {
		readable = "Pungent Meat",
		model = 1924206,
		text = {
			en = "Pungent Meat",
			es = "Carne acre",
			de = "Stinkendes Fleisch",
			fr = "Viande faisandée",
			it = "Carne Acre",
			pt = "[Pungent Meat]",
			ru = "Зловонное мясо",
			ko = "[Pungent Meat]",
			cn = "[Pungent Meat]",
		},
	},
	[322588] = {
		readable = "Waygate Console",
		model = 1939122,
		text = {
			en = "Waygate Console",
			es = "Consola de puerta",
			de = "Torkonsole",
			fr = "Console du portail",
			it = "Console del Portale di Traslocazione",
			pt = "Console do Pórtico",
			ru = "Панель управления путевых врат",
			ko = "차원문 제어장치",
			cn = "[Waygate Console]",
		},
	},
	[322592] = {
		readable = "Rune of Sacrifice",
		model = 1661570,
		text = {
			en = "Rune of Sacrifice",
			es = "[Rune of Sacrifice]",
			de = "Rune der Opferung",
			fr = "Rune de sacrifice",
			it = "[Rune of Sacrifice]",
			pt = "[Rune of Sacrifice]",
			ru = "Руна жертвенности",
			ko = "[Rune of Sacrifice]",
			cn = "[Rune of Sacrifice]",
		},
	},
	[322593] = {
		readable = "Rune of the Bloodguard",
		model = 1664903,
		text = {
			en = "Rune of the Bloodguard",
			es = "[Rune of the Bloodguard]",
			de = "Rune der Blutwache",
			fr = "Rune de la garde de sang",
			it = "[Rune of the Bloodguard]",
			pt = "[Rune of the Bloodguard]",
			ru = "Руна кровавого стража",
			ko = "[Rune of the Bloodguard]",
			cn = "[Rune of the Bloodguard]",
		},
	},
	[322594] = {
		readable = "Rune of Oblivion",
		model = 1664904,
		text = {
			en = "Rune of Oblivion",
			es = "[Rune of Oblivion]",
			de = "Rune der Vergessenheit",
			fr = "Rune de l’oubli",
			it = "[Rune of Oblivion]",
			pt = "[Rune of Oblivion]",
			ru = "Руна забвения",
			ko = "[Rune of Oblivion]",
			cn = "[Rune of Oblivion]",
		},
	},
	[322595] = {
		readable = "Rune of Bloodshed",
		model = 1661569,
		text = {
			en = "Rune of Bloodshed",
			es = "[Rune of Bloodshed]",
			de = "Rune des Blutvergießens",
			fr = "Rune de l’effusion de sang",
			it = "[Rune of Bloodshed]",
			pt = "[Rune of Bloodshed]",
			ru = "Руна кровопролития",
			ko = "[Rune of Bloodshed]",
			cn = "[Rune of Bloodshed]",
		},
	},
	[322601] = {
		readable = "Bloodbound Ledger",
		model = 1344470,
		text = {
			en = "Bloodbound Ledger",
			es = "Libro de promesas de sangre",
			de = "Blutgebundenes Register",
			fr = "Grand livre lié par le sang",
			it = "Libro Mastro dei Vincolasangue",
			pt = "Livro de Registro Sanguino",
			ru = "Реестр кровавой связи",
			ko = "혈속박 장부",
			cn = "血缚契约书",
		},
	},
	[322604] = {
		readable = "Precious Geode",
		model = 219422,
		text = {
			en = "Precious Geode",
			es = "Geoda preciosa",
			de = "Wertvolle Geode",
			fr = "Géode précieuse",
			it = "[Precious Geode]",
			pt = "Geodo Precioso",
			ru = "Драгоценная жеода",
			ko = "[Precious Geode]",
			cn = "[Precious Geode]",
		},
	},
	[322614] = {
		readable = "Waygate",
		model = 240933,
		text = {
			en = "Waygate",
			es = "Puerta",
			de = "Tor",
			fr = "Portail d’accès",
			it = "Portale di Traslocazione",
			pt = "Pórtico",
			ru = "Путевые врата",
			ko = "차원문",
			cn = "[Waygate]",
		},
	},
	[322615] = {
		readable = "Precious Geode",
		model = 219422,
		text = {
			en = "Precious Geode",
			es = "Geoda preciosa",
			de = "Wertvolle Geode",
			fr = "Géode précieuse",
			it = "[Precious Geode]",
			pt = "Geodo Precioso",
			ru = "Драгоценная жеода",
			ko = "[Precious Geode]",
			cn = "[Precious Geode]",
		},
	},
	[322616] = {
		readable = "Precious Geode",
		model = 219422,
		text = {
			en = "Precious Geode",
			es = "Geoda preciosa",
			de = "Wertvolle Geode",
			fr = "Géode précieuse",
			it = "[Precious Geode]",
			pt = "Geodo Precioso",
			ru = "Драгоценная жеода",
			ko = "[Precious Geode]",
			cn = "[Precious Geode]",
		},
	},
	[322617] = {
		readable = "Precious Geode",
		model = 219422,
		text = {
			en = "Precious Geode",
			es = "Geoda preciosa",
			de = "Wertvolle Geode",
			fr = "Géode précieuse",
			it = "[Precious Geode]",
			pt = "Geodo Precioso",
			ru = "Драгоценная жеода",
			ko = "[Precious Geode]",
			cn = "[Precious Geode]",
		},
	},
	[322618] = {
		readable = "Precious Geode",
		model = 219422,
		text = {
			en = "Precious Geode",
			es = "Geoda preciosa",
			de = "Wertvolle Geode",
			fr = "Géode précieuse",
			it = "[Precious Geode]",
			pt = "[Precious Geode]",
			ru = "Драгоценная жеода",
			ko = "[Precious Geode]",
			cn = "[Precious Geode]",
		},
	},
	[322619] = {
		readable = "Precious Geode",
		model = 219422,
		text = {
			en = "Precious Geode",
			es = "[Precious Geode]",
			de = "Wertvolle Geode",
			fr = "Géode précieuse",
			it = "[Precious Geode]",
			pt = "Geodo Precioso",
			ru = "Драгоценная жеода",
			ko = "[Precious Geode]",
			cn = "[Precious Geode]",
		},
	},
	[322620] = {
		readable = "Storeroom Keys",
		model = 970208,
		text = {
			en = "Storeroom Keys",
			es = "Llaves del almacén",
			de = "Lagerschlüssel",
			fr = "Clé de l’entrepôt",
			it = "[Storeroom Keys]",
			pt = "Chaves da Despensa",
			ru = "Ключи от хранилища",
			ko = "창고 열쇠",
			cn = "[Storeroom Keys]",
		},
	},
	[322629] = {
		readable = "Bondo's Strongbox",
		model = 953811,
		text = {
			en = "Bondo's Strongbox",
			es = "Caja fuerte de Bondo",
			de = "Bondos Schließkassette",
			fr = "Coffre de Bondo",
			it = "Forziere di Bondo",
			pt = "Caixa-forte do Bitola",
			ru = "Сейф Бондо",
			ko = "본도의 금고",
			cn = "邦多的保险箱",
		},
	},
	[322636] = {
		readable = "Worn Collar",
		model = 969733,
		text = {
			en = "Worn Collar",
			es = "Collar desgastado",
			de = "Abgetragenes Halsband",
			fr = "Collier usé",
			it = "[Worn Collar]",
			pt = "Coleira Usada",
			ru = "Поношенный ошейник",
			ko = "낡은 목줄",
			cn = "[Worn Collar]",
		},
	},
	[322637] = {
		readable = "Squeaky Toy",
		model = 969758,
		text = {
			en = "Squeaky Toy",
			es = "Juguete de goma",
			de = "Quietschspielzeug",
			fr = "Jouet qui couine",
			it = "[Squeaky Toy]",
			pt = "Brinquedinho Guinchante",
			ru = "Игрушка-пищалка",
			ko = "소리 나는 장난감",
			cn = "[Squeaky Toy]",
		},
	},
	[322638] = {
		readable = "Gnawed Bone",
		model = 969729,
		text = {
			en = "Gnawed Bone",
			es = "Hueso mordisqueado",
			de = "Abgenagter Knochen",
			fr = "Os rongé",
			it = "[Gnawed Bone]",
			pt = "Osso Roído",
			ru = "Изгрызенная кость",
			ko = "갉아먹은 뼈다귀",
			cn = "[Gnawed Bone]",
		},
	},
	[322644] = {
		readable = "Portal to Orgrimmar",
		model = 197047,
		text = {
			en = "Portal to Orgrimmar",
			es = "Portal a Orgrimmar",
			de = "Portal nach Orgrimmar",
			fr = "Portail vers Orgrimmar",
			it = "Portale per Orgrimmar",
			pt = "Portal para Orgrimmar",
			ru = "Портал в Оргриммар",
			ko = "오그리마로 통하는 차원문",
			cn = "到奥格瑞玛的传送门",
		},
	},
	[322651] = {
		readable = "Storage Crate",
		model = 1806318,
		text = {
			en = "Storage Crate",
			es = "Cofre de almacenamiento",
			de = "Vorratstruhe",
			fr = "Caisse de stockage",
			it = "[Storage Crate]",
			pt = "Caixote de Armazenamento",
			ru = "Складской сундук",
			ko = "보관 상자",
			cn = "[Storage Crate]",
		},
	},
	[322659] = {
		readable = "Spirit Offering",
		model = 1322311,
		text = {
			en = "Spirit Offering",
			es = "Ofrenda espritiual",
			de = "Geisteropfergabe",
			fr = "Offrande spirituelle",
			it = "[Spirit Offering]",
			pt = "[Spirit Offering]",
			ru = "Подношение духам",
			ko = "[Spirit Offering]",
			cn = "[Spirit Offering]",
		},
	},
	[322665] = {
		readable = "Cleaning Fluid",
		model = 304794,
		text = {
			en = "Cleaning Fluid",
			es = "Líquido de limpieza",
			de = "Reinigungsmittel",
			fr = "Fluide nettoyant",
			it = "Fluido per Pulizie",
			pt = "Fluido de Limpeza",
			ru = "Чистящее средство",
			ko = "정화액",
			cn = "清洁液",
		},
	},
	[322666] = {
		readable = "Explosives",
		model = 1305538,
		text = {
			en = "Explosives",
			es = "Explosivos",
			de = "Sprengstoff",
			fr = "Explosifs",
			it = "Esplosivi",
			pt = "Explosivos",
			ru = "Взрывчатка",
			ko = "폭발물",
			cn = "炸药",
		},
	},
	[322669] = {
		readable = "Batteries",
		model = 309919,
		text = {
			en = "Batteries",
			es = "Baterías",
			de = "Batterien",
			fr = "Batteries",
			it = "Batterie",
			pt = "Baterias",
			ru = "Батареи",
			ko = "전지",
			cn = "电池",
		},
	},
	[322671] = {
		readable = "Cogs and Springs",
		model = 2068146,
		text = {
			en = "Cogs and Springs",
			es = "Piñones y muelles",
			de = "Zahnräder und Federn",
			fr = "Rouages et ressorts",
			it = "Pignoni e Molle",
			pt = "Rodas Dentadas e Molas",
			ru = "Пружины и шестеренки",
			ko = "톱니와 용수철",
			cn = "齿轮与弹簧",
		},
	},
	[322675] = {
		readable = "Volatile Liquid",
		model = 200877,
		text = {
			en = "Volatile Liquid",
			es = "Líquido volátil",
			de = "Flüchtige Flüssigkeit",
			fr = "Liquide instable",
			it = "Liquido Instabile",
			pt = "Líquido Volátil",
			ru = "Нестабильная жидкость",
			ko = "불안정한 액체",
			cn = "挥发性液体",
		},
	},
	[322677] = {
		readable = "Suspicious Correspondence",
		model = 311987,
		text = {
			en = "Suspicious Correspondence",
			es = "Correspondencia sospechosa",
			de = "Verdächtige Korrespondenz",
			fr = "Correspondance suspecte",
			it = "Corrispondenza Sospetta",
			pt = "Correspondência Suspeita",
			ru = "Подозрительное послание",
			ko = "수상한 서신",
			cn = "[Suspicious Correspondence]",
		},
	},
	[322678] = {
		readable = "Suspicious Correspondence",
		model = 311987,
		text = {
			en = "Suspicious Correspondence",
			es = "Correspondencia sospechosa",
			de = "Verdächtige Korrespondenz",
			fr = "Correspondance suspecte",
			it = "Corrispondenza Sospetta",
			pt = "Correspondência Suspeita",
			ru = "Подозрительное послание",
			ko = "수상한 서신",
			cn = "[Suspicious Correspondence]",
		},
	},
	[322679] = {
		readable = "Suspicious Correspondence",
		model = 311987,
		text = {
			en = "Suspicious Correspondence",
			es = "Correspondencia sospechosa",
			de = "Verdächtige Korrespondenz",
			fr = "Correspondance suspecte",
			it = "Corrispondenza Sospetta",
			pt = "Correspondência Suspeita",
			ru = "Подозрительное послание",
			ko = "수상한 서신",
			cn = "[Suspicious Correspondence]",
		},
	},
	[322680] = {
		readable = "Suspicious Correspondence",
		model = 311987,
		text = {
			en = "Suspicious Correspondence",
			es = "Correspondencia sospechosa",
			de = "Verdächtige Korrespondenz",
			fr = "Correspondance suspecte",
			it = "Corrispondenza Sospetta",
			pt = "Correspondência Suspeita",
			ru = "Подозрительное послание",
			ko = "수상한 서신",
			cn = "[Suspicious Correspondence]",
		},
	},
	[322684] = {
		readable = "RCV Control Switch",
		model = 2628252,
		text = {
			en = "RCV Control Switch",
			es = "Interruptor de control RCV",
			de = "Fernsteuerung",
			fr = "Interrupteur de VTG",
			it = "[RCV Control Switch]",
			pt = "[RCV Control Switch]",
			ru = "Переключатель управления РБМ",
			ko = "[RCV Control Switch]",
			cn = "[RCV Control Switch]",
		},
	},
	[322689] = {
		readable = "SI:7 Spyglass",
		model = 1052603,
		text = {
			en = "SI:7 Spyglass",
			es = "Catalejo de la IV:7",
			de = "Fernglas des SI:7",
			fr = "Longue-vue du SI:7",
			it = "Cannocchiale dell'IR:7",
			pt = "Luneta da AVIN",
			ru = "Подзорная труба ШРУ",
			ko = "SI:7 망원경",
			cn = "[SI:7 Spyglass]",
		},
	},
	[322695] = {
		readable = "Teleportation Pad",
		model = 252934,
		text = {
			en = "Teleportation Pad",
			es = "Plataforma de teletransporte",
			de = "Teleportationsplattform",
			fr = "Plateforme de téléportation",
			it = "Piattaforma di Teletrasporto",
			pt = "Plataforma de Teleporte",
			ru = "Площадка телепортера",
			ko = "[Teleportation Pad]",
			cn = "[Teleportation Pad]",
		},
	},
	[322706] = {
		readable = "Stabilization Matrix Node",
		model = 255210,
		text = {
			en = "Stabilization Matrix Node",
			es = "Nodo de matriz de estabilización",
			de = "Stabilisierungsmatrixknoten",
			fr = "Nœud de matrice de stabilisation",
			it = "Nodo della Matrice di Stabilizzazione",
			pt = "Nodo da Matriz de Estabilização",
			ru = "Узел матрицы стабилизации",
			ko = "[Stabilization Matrix Node]",
			cn = "[Stabilization Matrix Node]",
		},
	},
	[322708] = {
		readable = "Rowboat",
		model = 1659376,
		text = {
			en = "Rowboat",
			es = "Bote de remos",
			de = "Ruderboot",
			fr = "Chaloupe",
			it = "[Rowboat]",
			pt = "Barco a Remo",
			ru = "Гребная шлюпка",
			ko = "나룻배",
			cn = "划艇",
		},
	},
	[322710] = {
		readable = "DO NOT PUSH THIS BUTTON!",
		model = 251641,
		text = {
			en = "DO NOT PUSH THIS BUTTON!",
			es = "¡NO PULSAR ESTE BOTÓN!",
			de = "DIESEN KNOPF NICHT DRÜCKEN!",
			fr = "NE PAS APPUYER SUR CE BOUTON !",
			it = "NON PREMERE QUESTO BOTTONE!",
			pt = "NÃO APERTE ESTE BOTÃO!",
			ru = "НЕ НАЖИМАЙТЕ ЭТУ КНОПКУ!",
			ko = "[DO NOT PUSH THIS BUTTON!]",
			cn = "[DO NOT PUSH THIS BUTTON!]",
		},
	},
	[322713] = {
		readable = "Console",
		model = 243958,
		text = {
			en = "Console",
			es = "Consola",
			de = "Konsole",
			fr = "Console",
			it = "Console",
			pt = "Console",
			ru = "Консоль",
			ko = "[Console]",
			cn = "[Console]",
		},
	},
	[322725] = {
		readable = "SI:7 Listening Device",
		model = 2132111,
		text = {
			en = "SI:7 Listening Device",
			es = "Dispositivo de escucha del IV:7",
			de = "Abhöranlage des SI:7",
			fr = "Système d’écoute du SI:7",
			it = "Dispositivo d'Ascolto dell'IR:7",
			pt = "Dispositivo de Escuta da AVIN",
			ru = "Подслушивающее устройство ШРУ",
			ko = "SI:7 도청 장치",
			cn = "军情七处监听装置",
		},
	},
	[322726] = {
		readable = "Teleportation Pad",
		model = 252934,
		text = {
			en = "Teleportation Pad",
			es = "Plataforma de teletransporte",
			de = "Teleportationsplattform",
			fr = "Plateforme de téléportation",
			it = "Piattaforma di Teletrasporto",
			pt = "Plataforma de Teleporte",
			ru = "Площадка телепортера",
			ko = "[Teleportation Pad]",
			cn = "[Teleportation Pad]",
		},
	},
	[322729] = {
		readable = "Teleportation Pad",
		model = 252934,
		text = {
			en = "Teleportation Pad",
			es = "Plataforma de teletransporte",
			de = "Teleportationsplattform",
			fr = "Plateforme de téléportation",
			it = "Piattaforma di Teletrasporto",
			pt = "Plataforma de Teleporte",
			ru = "Площадка телепортера",
			ko = "[Teleportation Pad]",
			cn = "[Teleportation Pad]",
		},
	},
	[322731] = {
		readable = "Thunderspark",
		model = 1282671,
		text = {
			en = "Thunderspark",
			es = "Chispatrueno",
			de = "Donnerfunke",
			fr = "Étincelle du tonnerre",
			it = "Scintilla Tonante",
			pt = "Trovarraio",
			ru = "Грозовая искра",
			ko = "[Thunderspark]",
			cn = "[Thunderspark]",
		},
	},
	[322737] = {
		readable = "Ceremonial Tauren Garb",
		model = 2429562,
		text = {
			en = "Ceremonial Tauren Garb",
			es = "Atuendo ceremonial tauren",
			de = "Zeremoniengewand der Tauren",
			fr = "Tenue de cérémonie taurène",
			it = "Abiti Cerimoniali dei Tauren",
			pt = "Vestes Taurenas Cerimoniais",
			ru = "Церемониальное облачение тауренов",
			ko = "타우렌 의식용 의상",
			cn = "牛头人仪式装束",
		},
	},
	[322743] = {
		readable = "Painpuff Sponge",
		model = 2180556,
		text = {
			en = "Painpuff Sponge",
			es = "Esponja malsoplo",
			de = "Qualquastenschwamm",
			fr = "Éponge gonfle-épic",
			it = "Spugna Sbuffamale",
			pt = "Esponja Dolorincha",
			ru = "Жгучая дымогубка",
			ko = "[Painpuff Sponge]",
			cn = "[Painpuff Sponge]",
		},
	},
	[322745] = {
		readable = "Signal Conch",
		model = 1316199,
		text = {
			en = "Signal Conch",
			es = "Caracola de señalización",
			de = "Signalmuschel",
			fr = "Conque de signal",
			it = "Spilla di Segnalazione",
			pt = "Concha Sinalizadora",
			ru = "Сигнальная раковина",
			ko = "[Signal Conch]",
			cn = "[Signal Conch]",
		},
	},
	[322748] = {
		readable = "Destroyed Security Turret",
		model = 2929686,
		text = {
			en = "Destroyed Security Turret",
			es = "Torreta de seguridad destruida",
			de = "Zerstörter Geschützturm",
			fr = "Tourelle de sécurité détruite",
			it = "Torretta di Sicurezza Distrutta",
			pt = "Torreta de Segurança Destruída",
			ru = "Уничтоженная защитная турель",
			ko = "파괴된 보안 포탑",
			cn = "被毁的安全炮塔",
		},
	},
	[322752] = {
		readable = "Mechanical Flotsam",
		model = 1033000,
		text = {
			en = "Mechanical Flotsam",
			es = "Derrelicto mecánico",
			de = "Mechanisches Treibgut",
			fr = "Débris mécaniques flottants",
			it = "Rottami Meccanici",
			pt = "Destroços Mecânicos",
			ru = "Обломки механизмов",
			ko = "기계 표류물",
			cn = "机械漂浮物",
		},
	},
	[322753] = {
		readable = "Mechanical Flotsam",
		model = 950732,
		text = {
			en = "Mechanical Flotsam",
			es = "Derrelicto mecánico",
			de = "Mechanisches Treibgut",
			fr = "Débris mécaniques flottants",
			it = "Rottami Meccanici",
			pt = "Destroços Mecânicos",
			ru = "Обломки механизмов",
			ko = "기계 표류물",
			cn = "机械漂浮物",
		},
	},
	[322754] = {
		readable = "Mechanical Flotsam",
		model = 955693,
		text = {
			en = "Mechanical Flotsam",
			es = "Derrelicto mecánico",
			de = "Mechanisches Treibgut",
			fr = "Débris mécaniques flottants",
			it = "Rottami Meccanici",
			pt = "Destroços Mecânicos",
			ru = "Обломки механизмов",
			ko = "기계 표류물",
			cn = "机械漂浮物",
		},
	},
	[322755] = {
		readable = "Mechanical Flotsam",
		model = 2068148,
		text = {
			en = "Mechanical Flotsam",
			es = "Derrelicto mecánico",
			de = "Mechanisches Treibgut",
			fr = "Débris mécaniques flottants",
			it = "Rottami Meccanici",
			pt = "Destroços Mecânicos",
			ru = "Обломки механизмов",
			ko = "기계 표류물",
			cn = "机械漂浮物",
		},
	},
	[322756] = {
		readable = "Mechanical Flotsam",
		model = 1842467,
		text = {
			en = "Mechanical Flotsam",
			es = "Derrelicto mecánico",
			de = "Mechanisches Treibgut",
			fr = "Débris mécaniques flottants",
			it = "Rottami Meccanici",
			pt = "Destroços Mecânicos",
			ru = "Обломки механизмов",
			ko = "기계 표류물",
			cn = "机械漂浮物",
		},
	},
	[322757] = {
		readable = "Mechanical Flotsam",
		model = 949527,
		text = {
			en = "Mechanical Flotsam",
			es = "Derrelicto mecánico",
			de = "Mechanisches Treibgut",
			fr = "Débris mécaniques flottants",
			it = "Rottami Meccanici",
			pt = "Destroços Mecânicos",
			ru = "Обломки механизмов",
			ko = "기계 표류물",
			cn = "机械漂浮物",
		},
	},
	[322758] = {
		readable = "Mechanical Flotsam",
		model = 987255,
		text = {
			en = "Mechanical Flotsam",
			es = "Derrelicto mecánico",
			de = "Mechanisches Treibgut",
			fr = "Débris mécaniques flottants",
			it = "Rottami Meccanici",
			pt = "Destroços Mecânicos",
			ru = "Обломки механизмов",
			ko = "기계 표류물",
			cn = "机械漂浮物",
		},
	},
	[322762] = {
		readable = "Destroyed Security Alarm",
		model = 2316619,
		text = {
			en = "Destroyed Security Alarm",
			es = "Alarma de seguridad destruida",
			de = "Zerstörter Sicherheitsalarm",
			fr = "Alarme de sécurité détruite",
			it = "Allarme di Sicurezza Distrutto",
			pt = "Alarme de Segurança Destruído",
			ru = "Поврежденное сигнальное устройство",
			ko = "파괴된 보안 경보",
			cn = "被毁的安全警报器",
		},
	},
	[322763] = {
		readable = "Dud Missile",
		model = 2394185,
		text = {
			en = "Dud Missile",
			es = "Misil defectuoso",
			de = "Raketenblindgänger",
			fr = "Missile détraqué",
			it = "Missile Difettoso",
			pt = "Míssil Não Detonado",
			ru = "Холостая ракета",
			ko = "불발 미사일",
			cn = "失效的飞弹",
		},
	},
	[322764] = {
		readable = "Destroyed Scraphound",
		model = 2828022,
		text = {
			en = "Destroyed Scraphound",
			es = "Can de chatarra destruido",
			de = "Zerstörter Schrotthund",
			fr = "Molosse-o-tron détruit",
			it = "Segugio di Scarti Distrutto",
			pt = "Cão-sucata Destruído",
			ru = "Утилизированный утильхаунд",
			ko = "부서진 고철사냥개",
			cn = "被毁的废钢猎犬",
		},
	},
	[322765] = {
		readable = "Rowboat",
		model = 1659376,
		text = {
			en = "Rowboat",
			es = "Bote de remos",
			de = "[Rowboat]",
			fr = "[Rowboat]",
			it = "[Rowboat]",
			pt = "[Rowboat]",
			ru = "[Rowboat]",
			ko = "[Rowboat]",
			cn = "[Rowboat]",
		},
	},
	[322766] = {
		readable = "Rigging",
		model = 1671639,
		text = {
			en = "Rigging",
			es = "Jarcia",
			de = "Winde",
			fr = "Gréement",
			it = "[Rigging]",
			pt = "Cordame",
			ru = "Такелаж",
			ko = "삭구",
			cn = "索具",
		},
	},
	[322768] = {
		readable = "Captain's Helm",
		model = 1852931,
		text = {
			en = "Captain's Helm",
			es = "Timón",
			de = "Steuerrad des Kapitäns",
			fr = "Barre du navire",
			it = "[Captain's Helm]",
			pt = "Timão do Capitão",
			ru = "Штурвал капитана",
			ko = "선장의 키",
			cn = "船长的舵柄",
		},
	},
	[322771] = {
		readable = "Delormi's Synchronous Thread",
		model = 2490701,
		text = {
			en = "Delormi's Synchronous Thread",
			es = "Hilo sincrónico de Delormi",
			de = "Delormis Synchronfaden",
			fr = "Fil synchrone de Delormi",
			it = "Filo Sincronico di Delormi",
			pt = "Linha Sincrônica de Delormi",
			ru = "Хрононить Делорми",
			ko = "[Delormi's Synchronous Thread]",
			cn = "德洛尔米的共时之线",
		},
	},
	[322787] = {
		readable = "Shrine of Torcali",
		model = 1667622,
		text = {
			en = "Shrine of Torcali",
			es = "Santuario de Torcali",
			de = "Schrein von Torcali",
			fr = "Sanctuaire de Torcali",
			it = "Santuario di Torcali",
			pt = "Santuário de Torcali",
			ru = "Святилище Торкали",
			ko = "토르칼리의 제단",
			cn = "[Shrine of Torcali]",
		},
	},
	[322789] = {
		readable = "Path of Torcali",
		model = 1269397,
		text = {
			en = "Path of Torcali",
			es = "Senda de Torcali",
			de = "Torcalis Pfad",
			fr = "Voie de Torcali",
			it = "Sentiero di Torcali",
			pt = "Caminho de Torcali",
			ru = "Путь Торкали",
			ko = "토르칼리의 길",
			cn = "[Path of Torcali]",
		},
	},
	[322790] = {
		readable = "Path of Torcali",
		model = 1269397,
		text = {
			en = "Path of Torcali",
			es = "Senda de Torcali",
			de = "Torcalis Pfad",
			fr = "Voie de Torcali",
			it = "Sentiero di Torcali",
			pt = "Caminho de Torcali",
			ru = "Путь Торкали",
			ko = "토르칼리의 길",
			cn = "[Path of Torcali]",
		},
	},
	[322791] = {
		readable = "Kelpberry",
		model = 2322526,
		text = {
			en = "Kelpberry",
			es = "Baya del mar",
			de = "Kelpbeere",
			fr = "Baie de varech",
			it = "Algabacca",
			pt = "Algarola",
			ru = "Водорослика",
			ko = "물풀딸기",
			cn = "藻莓",
		},
	},
	[322792] = {
		readable = "Path of Torcali",
		model = 1269397,
		text = {
			en = "Path of Torcali",
			es = "Senda de Torcali",
			de = "Torcalis Pfad",
			fr = "Voie de Torcali",
			it = "Sentiero di Torcali",
			pt = "Caminho de Torcali",
			ru = "Путь Торкали",
			ko = "토르칼리의 길",
			cn = "[Path of Torcali]",
		},
	},
	[322793] = {
		readable = "Path of Torcali",
		model = 1269397,
		text = {
			en = "Path of Torcali",
			es = "Senda de Torcali",
			de = "Torcalis Pfad",
			fr = "Voie de Torcali",
			it = "Sentiero di Torcali",
			pt = "Caminho de Torcali",
			ru = "Путь Торкали",
			ko = "토르칼리의 길",
			cn = "[Path of Torcali]",
		},
	},
	[322794] = {
		readable = "Drum of Primal Might",
		model = 1372935,
		text = {
			en = "Drum of Primal Might",
			es = "Tambor de poderío primigenio",
			de = "Trommel der Urmacht",
			fr = "Tambour de pouvoir primordial",
			it = "Tamburo della Forza Primordiale",
			pt = "Tambor do Poder Primevo",
			ru = "Барабан первобытной мощи",
			ko = "힘의 근원 북",
			cn = "[Drum of Primal Might]",
		},
	},
	[322796] = {
		readable = "Circuit Breaker",
		model = 2745103,
		text = {
			en = "Circuit Breaker",
			es = "Disyuntor",
			de = "Trennschalter",
			fr = "Disjoncteur",
			it = "Interruttore",
			pt = "Quebra-circuito",
			ru = "Автоматический выключатель",
			ko = "회로 차단기",
			cn = "断路器",
		},
	},
	[322800] = {
		readable = "Object",
		model = 1681368,
		text = {
			en = "Object",
			es = "Objeto",
			de = "Objekt",
			fr = "Objet",
			it = "Oggetto",
			pt = "Objeto",
			ru = "Объект",
			ko = "물체",
			cn = "物品",
		},
	},
	[322803] = {
		readable = "Kelpberry",
		model = 2756691,
		text = {
			en = "Kelpberry",
			es = "Baya del mar",
			de = "Kelpbeere",
			fr = "Baie de varech",
			it = "Algabacca",
			pt = "Algarola",
			ru = "Водорослика",
			ko = "물풀딸기",
			cn = "藻莓",
		},
	},
	[322804] = {
		readable = "Portal to Stormwind",
		model = 197051,
		text = {
			en = "Portal to Stormwind",
			es = "Portal a Ventormenta",
			de = "Portal nach Sturmwind",
			fr = "Portail vers Hurlevent",
			it = "Portale per Roccavento",
			pt = "Portal para Ventobravo",
			ru = "Портал в Штормград",
			ko = "스톰윈드로 통하는 차원문",
			cn = "到暴风城的传送门",
		},
	},
	[322805] = {
		readable = "Calling Conch",
		model = 2913549,
		text = {
			en = "Calling Conch",
			es = "Caracola de llamada",
			de = "Anrufmuschel",
			fr = "Conque d’appel",
			it = "Conchiglia Richiamante",
			pt = "Concha de Convocação",
			ru = "Сигнальная раковина",
			ko = "부름의 소라고둥",
			cn = "召唤海螺",
		},
	},
	[323323] = {
		readable = "Drum of Primal Might",
		model = 1372935,
		text = {
			en = "Drum of Primal Might",
			es = "[Drum of Primal Might]",
			de = "Trommel der Urmacht",
			fr = "Tambour de pouvoir primordial",
			it = "[Drum of Primal Might]",
			pt = "Tambor do Poder Primevo",
			ru = "Барабан первобытной мощи",
			ko = "[Drum of Primal Might]",
			cn = "[Drum of Primal Might]",
		},
	},
	[323324] = {
		readable = "Drum of Primal Might",
		model = 1372935,
		text = {
			en = "Drum of Primal Might",
			es = "[Drum of Primal Might]",
			de = "Trommel der Urmacht",
			fr = "[Drum of Primal Might]",
			it = "[Drum of Primal Might]",
			pt = "Tambor do Poder Primevo",
			ru = "Барабан первобытной мощи",
			ko = "[Drum of Primal Might]",
			cn = "[Drum of Primal Might]",
		},
	},
	[323325] = {
		readable = "Drum of Primal Might",
		model = 1372935,
		text = {
			en = "Drum of Primal Might",
			es = "[Drum of Primal Might]",
			de = "Trommel der Urmacht",
			fr = "[Drum of Primal Might]",
			it = "[Drum of Primal Might]",
			pt = "Tambor do Poder Primevo",
			ru = "Барабан первобытной мощи",
			ko = "[Drum of Primal Might]",
			cn = "[Drum of Primal Might]",
		},
	},
	[323326] = {
		readable = "Drum of Primal Might",
		model = 1372935,
		text = {
			en = "Drum of Primal Might",
			es = "[Drum of Primal Might]",
			de = "Trommel der Urmacht",
			fr = "Tambour de pouvoir primordial",
			it = "[Drum of Primal Might]",
			pt = "Tambor do Poder Primevo",
			ru = "Барабан первобытной мощи",
			ko = "[Drum of Primal Might]",
			cn = "[Drum of Primal Might]",
		},
	},
	[323327] = {
		readable = "Drum of Primal Might",
		model = 1372935,
		text = {
			en = "Drum of Primal Might",
			es = "[Drum of Primal Might]",
			de = "Trommel der Urmacht",
			fr = "Tambour de pouvoir primordial",
			it = "[Drum of Primal Might]",
			pt = "Tambor do Poder Primevo",
			ru = "Барабан первобытной мощи",
			ko = "[Drum of Primal Might]",
			cn = "[Drum of Primal Might]",
		},
	},
	[323328] = {
		readable = "Drum of Primal Might",
		model = 1372935,
		text = {
			en = "Drum of Primal Might",
			es = "[Drum of Primal Might]",
			de = "Trommel der Urmacht",
			fr = "Tambour de pouvoir primordial",
			it = "[Drum of Primal Might]",
			pt = "Tambor do Poder Primevo",
			ru = "Барабан первобытной мощи",
			ko = "[Drum of Primal Might]",
			cn = "[Drum of Primal Might]",
		},
	},
	[323329] = {
		readable = "Drum of Primal Might",
		model = 1372935,
		text = {
			en = "Drum of Primal Might",
			es = "Tambor de poderío primigenio",
			de = "Trommel der Urmacht",
			fr = "[Drum of Primal Might]",
			it = "[Drum of Primal Might]",
			pt = "[Drum of Primal Might]",
			ru = "Барабан первобытной мощи",
			ko = "[Drum of Primal Might]",
			cn = "[Drum of Primal Might]",
		},
	},
	[323330] = {
		readable = "Drum of Primal Might",
		model = 1372935,
		text = {
			en = "Drum of Primal Might",
			es = "Tambor de poderío primigenio",
			de = "Trommel der Urmacht",
			fr = "[Drum of Primal Might]",
			it = "[Drum of Primal Might]",
			pt = "[Drum of Primal Might]",
			ru = "Барабан первобытной мощи",
			ko = "[Drum of Primal Might]",
			cn = "[Drum of Primal Might]",
		},
	},
	[323331] = {
		readable = "Drum of Primal Might",
		model = 1372935,
		text = {
			en = "Drum of Primal Might",
			es = "Tambor de poderío primigenio",
			de = "Trommel der Urmacht",
			fr = "[Drum of Primal Might]",
			it = "[Drum of Primal Might]",
			pt = "[Drum of Primal Might]",
			ru = "Барабан первобытной мощи",
			ko = "[Drum of Primal Might]",
			cn = "[Drum of Primal Might]",
		},
	},
	[323332] = {
		readable = "Drum of Primal Might",
		model = 1372935,
		text = {
			en = "Drum of Primal Might",
			es = "Tambor de poderío primigenio",
			de = "Trommel der Urmacht",
			fr = "[Drum of Primal Might]",
			it = "[Drum of Primal Might]",
			pt = "[Drum of Primal Might]",
			ru = "Барабан первобытной мощи",
			ko = "[Drum of Primal Might]",
			cn = "[Drum of Primal Might]",
		},
	},
	[323333] = {
		readable = "Drum of Primal Might",
		model = 1372935,
		text = {
			en = "Drum of Primal Might",
			es = "Tambor de poderío primigenio",
			de = "Trommel der Urmacht",
			fr = "[Drum of Primal Might]",
			it = "[Drum of Primal Might]",
			pt = "[Drum of Primal Might]",
			ru = "Барабан первобытной мощи",
			ko = "[Drum of Primal Might]",
			cn = "[Drum of Primal Might]",
		},
	},
	[323334] = {
		readable = "Drum of Primal Might",
		model = 1372935,
		text = {
			en = "Drum of Primal Might",
			es = "Tambor de poderío primigenio",
			de = "Trommel der Urmacht",
			fr = "[Drum of Primal Might]",
			it = "[Drum of Primal Might]",
			pt = "[Drum of Primal Might]",
			ru = "Барабан первобытной мощи",
			ko = "[Drum of Primal Might]",
			cn = "[Drum of Primal Might]",
		},
	},
	[323348] = {
		readable = "Drum of Primal Might",
		model = 1372935,
		text = {
			en = "Drum of Primal Might",
			es = "Tambor de poderío primigenio",
			de = "Trommel der Urmacht",
			fr = "Tambour de pouvoir primordial",
			it = "Tamburo della Forza Primordiale",
			pt = "Tambor do Poder Primevo",
			ru = "Барабан первобытной мощи",
			ko = "힘의 근원 북",
			cn = "原始之力战鼓",
		},
	},
	[323351] = {
		readable = "Anima Hoard",
		model = 166432,
		text = {
			en = "Anima Hoard",
			es = "Tesoro de ánima",
			de = "Animaschatz",
			fr = "Réserve d’anima",
			it = "Scorta di Animum",
			pt = "Estoque de Ânima",
			ru = "Тайник с анимой",
			ko = "령 비축물",
			cn = "心能储藏",
		},
	},
	[323361] = {
		readable = "Eye of Dazar",
		model = 942851,
		text = {
			en = "Eye of Dazar",
			es = "[Eye of Dazar]",
			de = "Auge von Dazar",
			fr = "[Eye of Dazar]",
			it = "[Eye of Dazar]",
			pt = "Olho de Dazar",
			ru = "Око Дазара",
			ko = "[Eye of Dazar]",
			cn = "[Eye of Dazar]",
		},
	},
	[323370] = {
		readable = "Ionized Minnows",
		model = 219406,
		text = {
			en = "Ionized Minnows",
			es = "Pececillos ionizados",
			de = "Ionisierte Elritzen",
			fr = "Vairons ionisés",
			it = "Tinche Ionizzate",
			pt = "Manjubinha Ionizada",
			ru = "Ионизированные миноги",
			ko = "이온화된 송사리 떼",
			cn = "离子化的鲦鱼",
		},
	},
	[323383] = {
		readable = "Pail of Scales",
		model = 1709140,
		text = {
			en = "Pail of Scales",
			es = "Cubo de escamas",
			de = "Behälter mit Schuppen",
			fr = "Seau d’écailles",
			it = "Secchio di Scaglie",
			pt = "Balde de Escamas",
			ru = "Ведро чешуи",
			ko = "비늘이 든 양동이",
			cn = "一桶鳞片",
		},
	},
	[323505] = {
		readable = "Ancient Journal Transcription",
		model = 985161,
		text = {
			en = "Ancient Journal Transcription",
			es = "[Ancient Journal Transcription]",
			de = "Abschrift eines uralten Tagebuchs",
			fr = "[Ancient Journal Transcription]",
			it = "[Ancient Journal Transcription]",
			pt = "Transcrição do Diário Ancestral",
			ru = "Перевод древнего дневника",
			ko = "[Ancient Journal Transcription]",
			cn = "[Ancient Journal Transcription]",
		},
	},
	[323537] = {
		readable = "Locked Chest",
		model = 446671,
		text = {
			en = "Locked Chest",
			es = "Cofre cerrado",
			de = "Verschlossene Truhe",
			fr = "Coffre verrouillé",
			it = "Cassa Chiusa",
			pt = "Baú Trancado",
			ru = "Запертый сундук",
			ko = "잠긴 상자",
			cn = "锁住的箱子",
		},
	},
	[323548] = {
		readable = "Crate of Bones",
		model = 1709052,
		text = {
			en = "Crate of Bones",
			es = "Cajón de huesos",
			de = "Kiste mit Knochen",
			fr = "Caisse d’ossements",
			it = "Cassa di Ossa",
			pt = "Caixote de Ossos",
			ru = "Ящик костей",
			ko = "해골 상자",
			cn = "一箱骨头",
		},
	},
	[323835] = {
		readable = "Lens",
		model = 333562,
		text = {
			en = "Lens",
			es = "Lente",
			de = "Linse",
			fr = "Lentille",
			it = "Lente",
			pt = "Lente",
			ru = "Линза",
			ko = "렌즈",
			cn = "焦镜",
		},
	},
	[323840] = {
		readable = "Portal to Stormshield, Ashran",
		model = 2746853,
		text = {
			en = "Portal to Stormshield, Ashran",
			es = "Portal a Escudo de Tormenta, Ashran",
			de = "Portal zum Sturmschild, Ashran",
			fr = "Portail vers Bouclier-des-Tempêtes, A’shran",
			it = "Portale per Scudo del Vento, Ashran",
			pt = "Portal para Escudo Tonante, Ashran",
			ru = "Портал в Преграду Ветров на Ашране",
			ko = "아쉬란의 푹풍방패로 통하는 차원문",
			cn = "通往暴风之盾（阿什兰）的传送门",
		},
	},
	[323841] = {
		readable = "Portal to Azsuna",
		model = 2746854,
		text = {
			en = "Portal to Azsuna",
			es = "Portal a Azsuna",
			de = "Portal nach Azsuna",
			fr = "Portail vers Azsuna",
			it = "Portale per Azsuna",
			pt = "Portal para Azsuna",
			ru = "Портал в Азсуну",
			ko = "아즈스나로 통하는 차원문",
			cn = "通往阿苏纳的传送门",
		},
	},
	[323842] = {
		readable = "Portal to Dalaran, Crystalsong Forest",
		model = 2746855,
		text = {
			en = "Portal to Dalaran, Crystalsong Forest",
			es = "Portal a Dalaran, Bosque Canto de Cristal",
			de = "Portal nach Dalaran, Kristallsangwald",
			fr = "Portail vers Dalaran, forêt du Chant de cristal",
			it = "Portale per Dalaran, Foresta di Cristallo",
			pt = "Portal para Dalaran, Floresta do Canto Cristalino",
			ru = "Портал в Даларан над лесом Хрустальной Песни",
			ko = "수정노래 숲의 달라란으로 통하는 차원문",
			cn = "通往达拉然（晶歌森林）的传送门",
		},
	},
	[323843] = {
		readable = "Portal to the Exodar",
		model = 2746856,
		text = {
			en = "Portal to the Exodar",
			es = "Portal a El Exodar",
			de = "Portal zur Exodar",
			fr = "Portail vers l’Exodar",
			it = "Portale per Exodar",
			pt = "Portal para Exodar",
			ru = "Портал в Экзодар",
			ko = "엑소다르로 통하는 차원문",
			cn = "通往埃索达的传送门",
		},
	},
	[323844] = {
		readable = "Portal to Jade Forest",
		model = 2746857,
		text = {
			en = "Portal to Jade Forest",
			es = "Portal al Bosque de Jade",
			de = "Portal zum Jadewald",
			fr = "Portail vers la forêt de Jade",
			it = "Portale per la Foresta di Giada",
			pt = "Portal para a Floresta de Jade",
			ru = "Портал в Нефритовый лес",
			ko = "비취 숲으로 통하는 차원문",
			cn = "通往翡翠林的传送门",
		},
	},
	[323845] = {
		readable = "Portal to Boralus",
		model = 2746858,
		text = {
			en = "Portal to Boralus",
			es = "Portal a Boralus",
			de = "Portal nach Boralus",
			fr = "Portail vers Boralus",
			it = "Portale per Boralus",
			pt = "Portal para Boralus",
			ru = "Портал в Боралус",
			ko = "보랄러스로 통하는 차원문",
			cn = "通往伯拉勒斯的传送门",
		},
	},
	[323846] = {
		readable = "Portal to Shattrath",
		model = 2746859,
		text = {
			en = "Portal to Shattrath",
			es = "Portal a Shattrath",
			de = "Portal nach Shattrath",
			fr = "Portail vers Shattrath",
			it = "Portale per Shattrath",
			pt = "Portal para Shattrath",
			ru = "Портал в Шаттрат",
			ko = "샤트라스로 통하는 차원문",
			cn = "通往沙塔斯的传送门",
		},
	},
	[323849] = {
		readable = "Portal to Warspear, Ashran",
		model = 2746853,
		text = {
			en = "Portal to Warspear, Ashran",
			es = "Portal a Lanza de Guerra, Ashran",
			de = "Portal zum Kriegsspeer, Ashran",
			fr = "Portail vers Fer-de-Lance, A’shran",
			it = "Portale per Lancia da Guerra, Ashran",
			pt = "Portal para Lança de Guerra, Ashran",
			ru = "Портал на аванпост Копья Войны на Ашране",
			ko = "아쉬란의 전쟁의 창으로 통하는 차원문",
			cn = "通往战争之矛（阿什兰）的传送门",
		},
	},
	[323850] = {
		readable = "Portal to Azsuna",
		model = 2746854,
		text = {
			en = "Portal to Azsuna",
			es = "Portal a Azsuna",
			de = "Portal nach Azsuna",
			fr = "Portail vers Azsuna",
			it = "Portale per Azsuna",
			pt = "Portal para Azsuna",
			ru = "Портал в Азсуну",
			ko = "아즈스나로 통하는 차원문",
			cn = "通往阿苏纳的传送门",
		},
	},
	[323851] = {
		readable = "Portal to Dalaran, Crystalsong Forest",
		model = 2746855,
		text = {
			en = "Portal to Dalaran, Crystalsong Forest",
			es = "Portal a Dalaran, Bosque Canto de Cristal",
			de = "Portal nach Dalaran, Kristallsangwald",
			fr = "Portail vers Dalaran, forêt du Chant de cristal",
			it = "Portale per Dalaran, Foresta di Cristallo",
			pt = "Portal para Dalaran, Floresta do Canto Cristalino",
			ru = "Портал в Даларан над лесом Хрустальной Песни",
			ko = "수정노래 숲의 달라란으로 통하는 차원문",
			cn = "通往达拉然（晶歌森林）的传送门",
		},
	},
	[323852] = {
		readable = "Portal to Jade Forest",
		model = 2746857,
		text = {
			en = "Portal to Jade Forest",
			es = "Portal al Bosque de Jade",
			de = "Portal zum Jadewald",
			fr = "Portail vers la forêt de Jade",
			it = "Portale per la Foresta di Giada",
			pt = "Portal para a Floresta de Jade",
			ru = "Портал в Нефритовый лес",
			ko = "비취 숲으로 통하는 차원문",
			cn = "通往翡翠林的传送门",
		},
	},
	[323853] = {
		readable = "Portal to Shattrath",
		model = 2746859,
		text = {
			en = "Portal to Shattrath",
			es = "Portal a Shattrath",
			de = "Portal nach Shattrath",
			fr = "Portail vers Shattrath",
			it = "Portale per Shattrath",
			pt = "Portal para Shattrath",
			ru = "Портал в Шаттрат",
			ko = "샤트라스로 통하는 차원문",
			cn = "通往沙塔斯的传送门",
		},
	},
	[323854] = {
		readable = "Portal to Silvermoon",
		model = 2746860,
		text = {
			en = "Portal to Silvermoon",
			es = "Portal a Lunargenta",
			de = "Portal nach Silbermond",
			fr = "Portail vers Lune-d’Argent",
			it = "Portale per Lunargenta",
			pt = "Portal para Luaprata",
			ru = "Портал в Луносвет",
			ko = "실버문으로 통하는 차원문",
			cn = "通往银月城的传送门",
		},
	},
	[323855] = {
		readable = "Portal to Zuldazar",
		model = 2746861,
		text = {
			en = "Portal to Zuldazar",
			es = "Portal a Zuldazar",
			de = "Portal nach Zuldazar",
			fr = "Portail vers Zuldazar",
			it = "Portale per Zuldazar",
			pt = "Portal para Zuldazar",
			ru = "Портал в Зулдазар",
			ko = "줄다자르로 통하는 차원문",
			cn = "通往祖达萨的传送门",
		},
	},
	[323965] = {
		readable = "Musquash Root",
		model = 190384,
		text = {
			en = "Musquash Root",
			es = "[Musquash Root]",
			de = "[Musquash Root]",
			fr = "[Musquash Root]",
			it = "[Musquash Root]",
			pt = "[Musquash Root]",
			ru = "[Musquash Root]",
			ko = "[Musquash Root]",
			cn = "[Musquash Root]",
		},
	},
	[324027] = {
		readable = "Spirit Offering",
		model = 1327188,
		text = {
			en = "Spirit Offering",
			es = "[Spirit Offering]",
			de = "Geisteropfergabe",
			fr = "[Spirit Offering]",
			it = "[Spirit Offering]",
			pt = "[Spirit Offering]",
			ru = "Подношение духам",
			ko = "[Spirit Offering]",
			cn = "[Spirit Offering]",
		},
	},
	[324028] = {
		readable = "Elven Cookpot",
		model = 191999,
		text = {
			en = "Elven Cookpot",
			es = "Olla élfica",
			de = "Elfischer Kochtopf",
			fr = "Marmite elfique",
			it = "Pentola Elfica",
			pt = "Panela Élfica",
			ru = "Эльфийский котелок",
			ko = "엘프 요리 단지",
			cn = "精灵烹锅",
		},
	},
	[324030] = {
		readable = "Anima Cell",
		model = 166432,
		text = {
			en = "Anima Cell",
			es = "Celda de ánima",
			de = "Animazelle",
			fr = "Cellule d’anima",
			it = "Cella d'Animum",
			pt = "Célula de Ânima",
			ru = "Клетка с анимой",
			ko = "령 저장기",
			cn = "心能单元",
		},
	},
	[324031] = {
		readable = "Anima Hoard",
		model = 166432,
		text = {
			en = "Anima Hoard",
			es = "Tesoro de ánima",
			de = "Animaschatz",
			fr = "Réserve d’anima",
			it = "Scorta di Animum",
			pt = "Estoque de Ânima",
			ru = "Тайник с анимой",
			ko = "령 비축물",
			cn = "心能储藏",
		},
	},
	[324032] = {
		readable = "Anima Agglomeration",
		model = 166432,
		text = {
			en = "Anima Agglomeration",
			es = "Aglomeración de ánima",
			de = "Animaanhäufung",
			fr = "Agglomérat d’anima",
			it = "Agglomerato di Animum",
			pt = "Aglomeração de Ânima",
			ru = "Скопление анимы",
			ko = "령 응집물",
			cn = "心能凝块",
		},
	},
	[324034] = {
		readable = "Naga Cage",
		model = 1118155,
		text = {
			en = "Naga Cage",
			es = "Jaula naga",
			de = "Nagakäfig",
			fr = "Cage naga",
			it = "Gabbia dei Naga",
			pt = "Jaula Naga",
			ru = "Клетка наг",
			ko = "나가 우리",
			cn = "纳迦牢笼",
		},
	},
	[324039] = {
		readable = "Petrified Dragon Scale",
		model = 3004065,
		text = {
			en = "Petrified Dragon Scale",
			es = "Escama de dragón petrificada",
			de = "Versteinerte Drachenschuppe",
			fr = "Écaille de dragon pétrifiée",
			it = "Scaglia di Drago Pietrificata",
			pt = "Escama de Dragão Petrificada",
			ru = "Окаменевшая чешуйка дракона",
			ko = "석화된 용 비늘",
			cn = "石化龙鳞",
		},
	},
	[324040] = {
		readable = "War Supply Chest",
		model = 341746,
		text = {
			en = "War Supply Chest",
			es = "Cofre de suministros de guerra",
			de = "Kiste mit Kriegsvorräten",
			fr = "Coffre de fournitures de guerre",
			it = "[War Supply Chest]",
			pt = "Baú de Suprimentos de Guerra",
			ru = "Сундук с военными припасами",
			ko = "[War Supply Chest]",
			cn = "战争补给箱",
		},
	},
	[324041] = {
		readable = "War Supply Chest",
		model = 341746,
		text = {
			en = "War Supply Chest",
			es = "Cofre de suministros de guerra",
			de = "Kiste mit Kriegsvorräten",
			fr = "Coffre de fournitures de guerre",
			it = "[War Supply Chest]",
			pt = "Baú de Suprimentos de Guerra",
			ru = "Сундук с военными припасами",
			ko = "[War Supply Chest]",
			cn = "[War Supply Chest]",
		},
	},
	[324042] = {
		readable = "War Supply Chest",
		model = 341746,
		text = {
			en = "War Supply Chest",
			es = "[War Supply Chest]",
			de = "Kiste mit Kriegsvorräten",
			fr = "Coffre de fournitures de guerre",
			it = "[War Supply Chest]",
			pt = "Baú de Suprimentos de Guerra",
			ru = "Сундук с военными припасами",
			ko = "[War Supply Chest]",
			cn = "[War Supply Chest]",
		},
	},
	[324043] = {
		readable = "War Supply Chest",
		model = 341746,
		text = {
			en = "War Supply Chest",
			es = "Cofre de suministros de guerra",
			de = "Kiste mit Kriegsvorräten",
			fr = "Coffre de fournitures de guerre",
			it = "[War Supply Chest]",
			pt = "Baú de Suprimentos de Guerra",
			ru = "Сундук с военными припасами",
			ko = "전쟁 보급품 상자",
			cn = "战争补给箱",
		},
	},
	[324044] = {
		readable = "War Supply Chest",
		model = 341746,
		text = {
			en = "War Supply Chest",
			es = "Cofre de suministros de guerra",
			de = "Kiste mit Kriegsvorräten",
			fr = "Coffre de fournitures de guerre",
			it = "Cassa di Rifornimenti da Guerra",
			pt = "Baú de Suprimentos de Guerra",
			ru = "Сундук с военными припасами",
			ko = "전쟁 보급품 상자",
			cn = "战争补给箱",
		},
	},
	[324049] = {
		readable = "War Supply Chest",
		model = 341870,
		text = {
			en = "War Supply Chest",
			es = "Cofre de suministros de guerra",
			de = "Kiste mit Kriegsvorräten",
			fr = "Coffre de fournitures de guerre",
			it = "Cassa di Rifornimenti da Guerra",
			pt = "Baú de Suprimentos de Guerra",
			ru = "Сундук с военными припасами",
			ko = "[War Supply Chest]",
			cn = "战争补给箱",
		},
	},
	[324050] = {
		readable = "War Supply Chest",
		model = 341870,
		text = {
			en = "War Supply Chest",
			es = "Cofre de suministros de guerra",
			de = "Kiste mit Kriegsvorräten",
			fr = "Coffre de fournitures de guerre",
			it = "Cassa di Rifornimenti da Guerra",
			pt = "Baú de Suprimentos de Guerra",
			ru = "Сундук с военными припасами",
			ko = "[War Supply Chest]",
			cn = "战争补给箱",
		},
	},
	[324051] = {
		readable = "War Supply Chest",
		model = 341870,
		text = {
			en = "War Supply Chest",
			es = "Cofre de suministros de guerra",
			de = "Kiste mit Kriegsvorräten",
			fr = "Coffre de fournitures de guerre",
			it = "Cassa di Rifornimenti da Guerra",
			pt = "Baú de Suprimentos de Guerra",
			ru = "Сундук с военными припасами",
			ko = "전쟁 보급품 상자",
			cn = "战争补给箱",
		},
	},
	[324052] = {
		readable = "War Supply Chest",
		model = 341870,
		text = {
			en = "War Supply Chest",
			es = "Cofre de suministros de guerra",
			de = "Kiste mit Kriegsvorräten",
			fr = "Coffre de fournitures de guerre",
			it = "[War Supply Chest]",
			pt = "[War Supply Chest]",
			ru = "Сундук с военными припасами",
			ko = "[War Supply Chest]",
			cn = "[War Supply Chest]",
		},
	},
	[324053] = {
		readable = "War Supply Chest",
		model = 341870,
		text = {
			en = "War Supply Chest",
			es = "Cofre de suministros de guerra",
			de = "Kiste mit Kriegsvorräten",
			fr = "Coffre de fournitures de guerre",
			it = "Cassa di Rifornimenti da Guerra",
			pt = "Baú de Suprimentos de Guerra",
			ru = "Сундук с военными припасами",
			ko = "[War Supply Chest]",
			cn = "[War Supply Chest]",
		},
	},
	[324070] = {
		readable = "Emerald Shard",
		model = 1572128,
		text = {
			en = "Emerald Shard",
			es = "Fragmento esmeralda",
			de = "Smaragdsplitter",
			fr = "Éclat d’émeraude",
			it = "Scheggia di Smeraldo",
			pt = "Estilhaço de Esmeralda",
			ru = "Изумрудный осколок",
			ko = "에메랄드 파편",
			cn = "翡翠碎片",
		},
	},
	[324072] = {
		readable = "Bucket of Hides",
		model = 850798,
		text = {
			en = "Bucket of Hides",
			es = "Cubo de pellejos",
			de = "Behälter mit Bälgen",
			fr = "Seau de peaux",
			it = "[Bucket of Hides]",
			pt = "[Bucket of Hides]",
			ru = "Ведро из шкур",
			ko = "[Bucket of Hides]",
			cn = "[Bucket of Hides]",
		},
	},
	[324073] = {
		readable = "Pail of Scales",
		model = 1044333,
		text = {
			en = "Pail of Scales",
			es = "Cubo de escamas",
			de = "Behälter mit Schuppen",
			fr = "Seau d’écailles",
			it = "[Pail of Scales]",
			pt = "[Pail of Scales]",
			ru = "Ведро чешуи",
			ko = "[Pail of Scales]",
			cn = "[Pail of Scales]",
		},
	},
	[324074] = {
		readable = "Crate of Bones",
		model = 1834972,
		text = {
			en = "Crate of Bones",
			es = "Cajón de huesos",
			de = "Kiste mit Knochen",
			fr = "Caisse d’ossements",
			it = "[Crate of Bones]",
			pt = "[Crate of Bones]",
			ru = "Ящик костей",
			ko = "[Crate of Bones]",
			cn = "[Crate of Bones]",
		},
	},
	[324075] = {
		readable = "Crate of Bones",
		model = 192653,
		text = {
			en = "Crate of Bones",
			es = "Cajón de huesos",
			de = "Kiste mit Knochen",
			fr = "Caisse d’ossements",
			it = "[Crate of Bones]",
			pt = "[Crate of Bones]",
			ru = "Ящик костей",
			ko = "[Crate of Bones]",
			cn = "[Crate of Bones]",
		},
	},
	[324410] = {
		readable = "Reforged Emerald Essence",
		model = 192134,
		text = {
			en = "Reforged Emerald Essence",
			es = "Esencia de esmeralda reforjada",
			de = "Neugeschmiedete Smaragdessenz",
			fr = "Essence d’émeraude reconstituée",
			it = "Essenza di Smeraldo Riforgiata",
			pt = "Essência Esmeralda Reforjada",
			ru = "Восстановленная изумрудная сущность",
			ko = "재련된 에메랄드 정수",
			cn = "重铸的翡翠精华",
		},
	},
	[324413] = {
		readable = "Amathet Cache",
		model = 253445,
		text = {
			en = "Amathet Cache",
			es = "Alijo amathet",
			de = "Truhe der Amathet",
			fr = "Cache amathet",
			it = "Cassa degli Amathet",
			pt = "Depósito Amatet",
			ru = "Тайник аматетов",
			ko = "아마셋 보관함",
			cn = "阿玛赛特之箱",
		},
	},
	[324414] = {
		readable = "Slimy Cocoon",
		model = 1412880,
		text = {
			en = "Slimy Cocoon",
			es = "Crisálida babosa",
			de = "Schleimiger Kokon",
			fr = "Cocon visqueux",
			it = "[Slimy Cocoon]",
			pt = "Casulo Gosmento",
			ru = "Склизкий кокон",
			ko = "끈적끈적한 고치",
			cn = "[Slimy Cocoon]",
		},
	},
	[324415] = {
		readable = "Slimy Cocoon",
		model = 1412880,
		text = {
			en = "Slimy Cocoon",
			es = "Crisálida babosa",
			de = "Schleimiger Kokon",
			fr = "Cocon visqueux",
			it = "[Slimy Cocoon]",
			pt = "Casulo Gosmento",
			ru = "Склизкий кокон",
			ko = "끈적끈적한 고치",
			cn = "[Slimy Cocoon]",
		},
	},
	[324416] = {
		readable = "Slimy Cocoon",
		model = 1412880,
		text = {
			en = "Slimy Cocoon",
			es = "Crisálida babosa",
			de = "Schleimiger Kokon",
			fr = "Cocon visqueux",
			it = "Bozzolo Viscido",
			pt = "Casulo Gosmento",
			ru = "Склизкий кокон",
			ko = "끈적끈적한 고치",
			cn = "[Slimy Cocoon]",
		},
	},
	[324417] = {
		readable = "Slimy Cocoon",
		model = 1412880,
		text = {
			en = "Slimy Cocoon",
			es = "Crisálida babosa",
			de = "Schleimiger Kokon",
			fr = "Cocon visqueux",
			it = "[Slimy Cocoon]",
			pt = "Casulo Gosmento",
			ru = "Склизкий кокон",
			ko = "끈적끈적한 고치",
			cn = "粘糊糊的茧",
		},
	},
	[325061] = {
		readable = "Waters of Farseeing",
		model = 201115,
		text = {
			en = "Waters of Farseeing",
			es = "Aguas de Clarividencia",
			de = "Wasser der Weitsicht",
			fr = "Eaux de longue-vision",
			it = "Acque della Lungimiranza",
			pt = "Águas da Vidência",
			ru = "Воды предвидения",
			ko = "통찰력의 물",
			cn = "先知之水",
		},
	},
	[325080] = {
		readable = "Mailbox",
		model = 199999,
		text = {
			en = "Mailbox",
			es = "Buzón",
			de = "Briefkasten",
			fr = "Boîte aux lettres",
			it = "Cassetta della Posta",
			pt = "Caixa de Correio",
			ru = "Почтовый ящик",
			ko = "우체통",
			cn = "邮箱",
		},
	},
	[325392] = {
		readable = "Box of Harvested Bones",
		model = 199101,
		text = {
			en = "Box of Harvested Bones",
			es = "[Box of Harvested Bones]",
			de = "Kiste mit aufgesammelten Knochen",
			fr = "Boîte d’ossements collectés",
			it = "[Box of Harvested Bones]",
			pt = "Caixa de Ossos Coletados",
			ru = "Ящик с собранными костями",
			ko = "[Box of Harvested Bones]",
			cn = "[Box of Harvested Bones]",
		},
	},
	[325393] = {
		readable = "Box of Harvested Bones",
		model = 197150,
		text = {
			en = "Box of Harvested Bones",
			es = "Caja de huesos recogidos",
			de = "Kiste mit aufgesammelten Knochen",
			fr = "[Box of Harvested Bones]",
			it = "[Box of Harvested Bones]",
			pt = "Caixa de Ossos Coletados",
			ru = "Ящик с собранными костями",
			ko = "[Box of Harvested Bones]",
			cn = "[Box of Harvested Bones]",
		},
	},
	[325397] = {
		readable = "Suntouched Obelisk",
		model = 396436,
		text = {
			en = "Suntouched Obelisk",
			es = "Obelisco fúlgido",
			de = "Sonnenberührter Obelisk",
			fr = "Obélisque solegrâce",
			it = "Obelisco dei Toccasole",
			pt = "Obelisco Tocado pelo Sol",
			ru = "Обелиск Светозарных",
			ko = "태양손길 방첨탑",
			cn = "日灼方尖碑",
		},
	},
	[325414] = {
		readable = "Ancient Sundial",
		model = 431773,
		text = {
			en = "Ancient Sundial",
			es = "Reloj de sol antiguo",
			de = "Uralte Sonnenuhr",
			fr = "Cadran solaire ancien",
			it = "Meridiana Antica",
			pt = "Relógio de Sol Antigo",
			ru = "Древние солнечные часы",
			ko = "고대의 해시계",
			cn = "古老的日晷",
		},
	},
	[325418] = {
		readable = "Boiling Cauldron",
		model = 1695011,
		text = {
			en = "Boiling Cauldron",
			es = "Caldera en ebullición",
			de = "Kochender Kessel",
			fr = "Chaudron bouillonnant",
			it = "Calderone Rovente",
			pt = "Caldeirão Fervente",
			ru = "Кипящий котел",
			ko = "끓는 가마솥",
			cn = "沸腾大锅",
		},
	},
	[325419] = {
		readable = "Purse",
		model = 1306556,
		text = {
			en = "Purse",
			es = "Bolso",
			de = "Geldbeutel",
			fr = "Bourse",
			it = "Borsellino",
			pt = "Bolsa",
			ru = "Кошелек",
			ko = "[Purse]",
			cn = "[Purse]",
		},
	},
	[325420] = {
		readable = "Stack of Scrolls",
		model = 2819573,
		text = {
			en = "Stack of Scrolls",
			es = "Montón de pergaminos",
			de = "Stapel mit Schriftrollen",
			fr = "Pile de parchemins",
			it = "Pila di Pergamene",
			pt = "Pilha de Pergaminhos",
			ru = "Стопка свитков",
			ko = "두루마리 더미",
			cn = "一堆卷轴",
		},
	},
	[325425] = {
		readable = "Wanderer's Wayshrine",
		model = 1667622,
		text = {
			en = "Wanderer's Wayshrine",
			es = "Santuario del errante",
			de = "Wegschrein des Wanderers",
			fr = "Sanctuaire de la Montagne errante",
			it = "Santuario della Nomade",
			pt = "Altar do Andarilho",
			ru = "Алтарь путников",
			ko = "[Wanderer's Wayshrine]",
			cn = "[Wanderer's Wayshrine]",
		},
	},
	[325426] = {
		readable = "Wanderer's Wayshrine",
		model = 1667622,
		text = {
			en = "Wanderer's Wayshrine",
			es = "Santuario del errante",
			de = "Wegschrein des Wanderers",
			fr = "Sanctuaire de la Montagne errante",
			it = "Santuario della Nomade",
			pt = "Altar do Andarilho",
			ru = "Алтарь путников",
			ko = "[Wanderer's Wayshrine]",
			cn = "[Wanderer's Wayshrine]",
		},
	},
	[325427] = {
		readable = "Wanderer's Wayshrine",
		model = 1667622,
		text = {
			en = "Wanderer's Wayshrine",
			es = "Santuario del errante",
			de = "Wegschrein des Wanderers",
			fr = "Sanctuaire de la Montagne errante",
			it = "Santuario della Nomade",
			pt = "Altar do Andarilho",
			ru = "Алтарь путников",
			ko = "[Wanderer's Wayshrine]",
			cn = "[Wanderer's Wayshrine]",
		},
	},
	[325436] = {
		readable = "Wanderer's Wayshrine",
		model = 1667622,
		text = {
			en = "Wanderer's Wayshrine",
			es = "Santuario de la Errante",
			de = "Wegschrein des Wanderers",
			fr = "Sanctuaire de la Montagne errante",
			it = "Santuario della Nomade",
			pt = "Altar do Andarilho",
			ru = "Алтарь путников",
			ko = "방랑자의 길목신단",
			cn = "流浪者道龛",
		},
	},
	[325456] = {
		readable = "Eye of N'Zoth",
		model = 2322102,
		text = {
			en = "Eye of N'Zoth",
			es = "Ojo de N'Zoth",
			de = "Auge von N'Zoth",
			fr = "Œil de N’Zoth",
			it = "[Eye of N'Zoth]",
			pt = "Olho de N'Zoth",
			ru = "Око Н'Зота",
			ko = "[Eye of N'Zoth]",
			cn = "[Eye of N'Zoth]",
		},
	},
	[325461] = {
		readable = "Eye of N'Zoth",
		model = 2322102,
		text = {
			en = "Eye of N'Zoth",
			es = "Ojo de N'Zoth",
			de = "Auge von N'Zoth",
			fr = "Œil de N’Zoth",
			it = "[Eye of N'Zoth]",
			pt = "Olho de N'Zoth",
			ru = "Око Н'Зота",
			ko = "[Eye of N'Zoth]",
			cn = "[Eye of N'Zoth]",
		},
	},
	[325471] = {
		readable = "Boiling Cauldron",
		model = 985294,
		text = {
			en = "Boiling Cauldron",
			es = "Caldera en ebullición",
			de = "Kochender Kessel",
			fr = "Chaudron bouillonnant",
			it = "Calderone Rovente",
			pt = "Caldeirão Fervente",
			ru = "Кипящий котел",
			ko = "끓는 가마솥",
			cn = "沸腾大锅",
		},
	},
	[325476] = {
		readable = "Direbloom",
		model = 1723302,
		text = {
			en = "Direbloom",
			es = "Flornefasta",
			de = "Schreckensblüte",
			fr = "Navrepousse",
			it = "Sbocciacupo",
			pt = "Floratroz",
			ru = "Лютоцвет",
			ko = "공포초",
			cn = "恐花",
		},
	},
	[325477] = {
		readable = "Amathet Idol",
		model = 410781,
		text = {
			en = "Amathet Idol",
			es = "Ídolo amathet",
			de = "Götze der Amathet",
			fr = "Idole amathet",
			it = "Idolo degli Amathet",
			pt = "Ídolo Amatet",
			ru = "Идол аматетов",
			ko = "아마셋 우상",
			cn = "阿玛赛特神像",
		},
	},
	[325478] = {
		readable = "Direbloom",
		model = 1723302,
		text = {
			en = "Direbloom",
			es = "Floratroz",
			de = "Schreckensblüte",
			fr = "Navrepousse",
			it = "Sbocciacupo",
			pt = "Floratroz",
			ru = "Лютоцвет",
			ko = "[Direbloom]",
			cn = "[Direbloom]",
		},
	},
	[325481] = {
		readable = "Amathet Armaments",
		model = 661571,
		text = {
			en = "Amathet Armaments",
			es = "Armamento amathet",
			de = "Waffen der Amathet",
			fr = "Armes amathet",
			it = "Armamenti degli Amathet",
			pt = "Armamentos Amatet",
			ru = "Боеприпасы аматетов",
			ko = "아마셋 무기",
			cn = "阿玛赛特武器",
		},
	},
	[325482] = {
		readable = "Energy Cell",
		model = 2736566,
		text = {
			en = "Energy Cell",
			es = "Célula de energía",
			de = "Energiezelle",
			fr = "Cellule énergétique",
			it = "Cella d'Energia",
			pt = "Bateria",
			ru = "Аккумулятор",
			ko = "마력 전지",
			cn = "能量电池",
		},
	},
	[325483] = {
		readable = "Object",
		model = 1119128,
		text = {
			en = "Object",
			es = "Objeto",
			de = "Objekt",
			fr = "Objet",
			it = "Oggetto",
			pt = "Objeto",
			ru = "Объект",
			ko = "물체",
			cn = "物品",
		},
	},
	[325484] = {
		readable = "Object",
		model = 166432,
		text = {
			en = "Object",
			es = "Objeto",
			de = "Objekt",
			fr = "Objet",
			it = "Oggetto",
			pt = "Objeto",
			ru = "Объект",
			ko = "물체",
			cn = "物品",
		},
	},
	[325485] = {
		readable = "Object",
		model = 1265200,
		text = {
			en = "Object",
			es = "Objeto",
			de = "Objekt",
			fr = "Objet",
			it = "Oggetto",
			pt = "Objeto",
			ru = "Объект",
			ko = "물체",
			cn = "物品",
		},
	},
	[325486] = {
		readable = "Empty Energy Cell",
		model = 2736566,
		text = {
			en = "Empty Energy Cell",
			es = "Célula de energía descargada",
			de = "Leere Energiezelle",
			fr = "Cellule énergétique vide",
			it = "Cella d'Energia Scarica",
			pt = "Bateria Descarregada",
			ru = "Разряженный аккумулятор",
			ko = "고갈된 마력 전지",
			cn = "空的能量电池",
		},
	},
	[325487] = {
		readable = "Spare Parts",
		model = 2068146,
		text = {
			en = "Spare Parts",
			es = "Piezas de repuesto",
			de = "Ersatzteile",
			fr = "Pièces détachées",
			it = "Pezzi di Ricambio",
			pt = "Peças Sobressalentes",
			ru = "Запасные части",
			ko = "예비 부품",
			cn = "备用零件",
		},
	},
	[325489] = {
		readable = "Deathshroom",
		model = 1728706,
		text = {
			en = "Deathshroom",
			es = "[Deathshroom]",
			de = "Todespilz",
			fr = "Champignon de la mort",
			it = "[Deathshroom]",
			pt = "[Deathshroom]",
			ru = "Смертевик",
			ko = "[Deathshroom]",
			cn = "[Deathshroom]",
		},
	},
	[325490] = {
		readable = "Deathshroom",
		model = 1728706,
		text = {
			en = "Deathshroom",
			es = "Hongoletal",
			de = "Todespilz",
			fr = "Champignon de la mort",
			it = "Fungo della Morte",
			pt = "Cogumorte",
			ru = "Смертевик",
			ko = "[Deathshroom]",
			cn = "[Deathshroom]",
		},
	},
	[325496] = {
		readable = "Object",
		model = 1096324,
		text = {
			en = "Object",
			es = "Objeto",
			de = "Objekt",
			fr = "Objet",
			it = "Oggetto",
			pt = "Objeto",
			ru = "Объект",
			ko = "물체",
			cn = "物品",
		},
	},
	[325497] = {
		readable = "Object",
		model = 1118049,
		text = {
			en = "Object",
			es = "Objeto",
			de = "Objekt",
			fr = "Objet",
			it = "Oggetto",
			pt = "Objeto",
			ru = "Объект",
			ko = "물체",
			cn = "物品",
		},
	},
	[325505] = {
		readable = "Amathet War Banner",
		model = 429166,
		text = {
			en = "Amathet War Banner",
			es = "Estandarte de guerra amathet",
			de = "Kriegsbanner der Amathet",
			fr = "Bannière de guerre amathet",
			it = "Stendardo di Guerra degli Amathet",
			pt = "Estandarte de Guerra Amatet",
			ru = "Боевое знамя аматетов",
			ko = "아마셋 전투 깃발",
			cn = "阿玛赛特战旗",
		},
	},
	[325561] = {
		readable = "Object",
		model = 2178314,
		text = {
			en = "Object",
			es = "Objeto",
			de = "Objekt",
			fr = "Objet",
			it = "Oggetto",
			pt = "Objeto",
			ru = "Объект",
			ko = "물체",
			cn = "物品",
		},
	},
	[325562] = {
		readable = "Object",
		model = 343855,
		text = {
			en = "Object",
			es = "Objeto",
			de = "Objekt",
			fr = "Objet",
			it = "Oggetto",
			pt = "Objeto",
			ru = "Объект",
			ko = "물체",
			cn = "物品",
		},
	},
	[325615] = {
		readable = "Brinestone Deposit",
		model = 1851971,
		text = {
			en = "Brinestone Deposit",
			es = "Depósito de petrosalmuera",
			de = "Salzsteinvorkommen",
			fr = "Gisement de salinite",
			it = "Deposito di Salmastrite",
			pt = "Depósito de Salmorita",
			ru = "Залежи соляника",
			ko = "염수석 광맥",
			cn = "卤岩矿脉",
		},
	},
	[325616] = {
		readable = "The Last Menethil",
		model = 936411,
		text = {
			en = "The Last Menethil",
			es = "La última Menethil",
			de = "Der letzte der Menethils",
			fr = "Le dernier Menethil",
			it = "L'Ultimo dei Menethil",
			pt = "O Último Menethil",
			ru = "Последняя из Менетилов",
			ko = "마지막 후계자",
			cn = "米奈希尔末代王储",
		},
	},
	[325618] = {
		readable = "Titan Artifact",
		model = 1019382,
		text = {
			en = "Titan Artifact",
			es = "Artefacto titánico",
			de = "Titanenartefakt",
			fr = "Artéfact des Titans",
			it = "Manufatto dei Titani",
			pt = "Artefato Titânico",
			ru = "Артефакт титанов",
			ko = "티탄 유물",
			cn = "泰坦神器",
		},
	},
	[325619] = {
		readable = "Titan Artifact",
		model = 1255595,
		text = {
			en = "Titan Artifact",
			es = "Artefacto titánico",
			de = "Titanenartefakt",
			fr = "Artéfact des Titans",
			it = "Manufatto dei Titani",
			pt = "Artefato Titânico",
			ru = "Артефакт титанов",
			ko = "티탄 유물",
			cn = "泰坦神器",
		},
	},
	[325620] = {
		readable = "Titan Artifact",
		model = 950737,
		text = {
			en = "Titan Artifact",
			es = "Artefacto titánico",
			de = "Titanenartefakt",
			fr = "Artéfact des Titans",
			it = "Manufatto dei Titani",
			pt = "Artefato Titânico",
			ru = "Артефакт титанов",
			ko = "티탄 유물",
			cn = "泰坦神器",
		},
	},
	[325622] = {
		readable = "The Cursed Old Wolf",
		model = 936411,
		text = {
			en = "The Cursed Old Wolf",
			es = "El viejo lobo maldito",
			de = "Der verfluchte alte Wolf",
			fr = "Le Vieux Loup maudit",
			it = "Il Vecchio Lupo Maledetto",
			pt = "O Velho Lobo Amaldiçoado",
			ru = "Проклятый старый волк",
			ko = "늙고 저주받은 늑대",
			cn = "被诅咒的老狼",
		},
	},
	[325623] = {
		readable = "The Traitor King",
		model = 936411,
		text = {
			en = "The Traitor King",
			es = "El rey traidor",
			de = "Verräterkönig",
			fr = "Le Roi traître",
			it = "Il Re Traditore",
			pt = "O Rei Traidor",
			ru = "Король-предатель",
			ko = "배신자 왕",
			cn = "叛徒国王",
		},
	},
	[325624] = {
		readable = "The Would-Be Queen",
		model = 936411,
		text = {
			en = "The Would-Be Queen",
			es = "La aspirante a reina",
			de = "Die Möchtegernkönigin",
			fr = "La reine en puissance",
			it = "L'Aspirante Regina",
			pt = "A Candidata a Rainha",
			ru = "Королева, которую мы потеряли",
			ko = "여왕이 되려던 자",
			cn = "失落的女王",
		},
	},
	[325626] = {
		readable = "Amathet Reliquary",
		model = 253445,
		text = {
			en = "Amathet Reliquary",
			es = "Relicario amathet",
			de = "Reliquiar der Amathet",
			fr = "Reliquaire amathet",
			it = "Reliquiario degli Amathet",
			pt = "Relicário Amatet",
			ru = "Реликварий аматетов",
			ko = "아마셋 성물함",
			cn = "阿玛赛特圣箱",
		},
	},
	[325629] = {
		readable = "Object",
		model = 1800373,
		text = {
			en = "Object",
			es = "Objeto",
			de = "Objekt",
			fr = "Objet",
			it = "Oggetto",
			pt = "Objeto",
			ru = "Объект",
			ko = "물체",
			cn = "物品",
		},
	},
	[325632] = {
		readable = "Burial Mound",
		model = 605598,
		text = {
			en = "Burial Mound",
			es = "Túmulo Funerario",
			de = "Grabhügel",
			fr = "Tertre funéraire",
			it = "Tumulo Sepolcrale",
			pt = "Monte Mortuário",
			ru = "Погребальный холм",
			ko = "[Burial Mound]",
			cn = "[Burial Mound]",
		},
	},
	[325655] = {
		readable = "Brinestone Deposit",
		model = 1851971,
		text = {
			en = "Brinestone Deposit",
			es = "Depósito de petrosalmuera",
			de = "Salzsteinvorkommen",
			fr = "Gisement de salinite",
			it = "Deposito di Salmastrite",
			pt = "Depósito de Salmorita",
			ru = "Залежи соляника",
			ko = "염수석 광맥",
			cn = "卤岩矿脉",
		},
	},
	[325656] = {
		readable = "Brinestone Deposit",
		model = 1851971,
		text = {
			en = "Brinestone Deposit",
			es = "Depósito de petrosalmuera",
			de = "Salzsteinvorkommen",
			fr = "Gisement de salinite",
			it = "Deposito di Salmastrite",
			pt = "Depósito de Salmorita",
			ru = "Залежи соляника",
			ko = "염수석 광맥",
			cn = "卤岩矿脉",
		},
	},
	[325657] = {
		readable = "Brinestone Deposit",
		model = 1851971,
		text = {
			en = "Brinestone Deposit",
			es = "Depósito de petrosalmuera",
			de = "Salzsteinvorkommen",
			fr = "Gisement de salinite",
			it = "Deposito di Salmastrite",
			pt = "Depósito de Salmorita",
			ru = "Залежи соляника",
			ko = "염수석 광맥",
			cn = "卤岩矿脉",
		},
	},
	[325658] = {
		readable = "Brinestone Deposit",
		model = 1851971,
		text = {
			en = "Brinestone Deposit",
			es = "Depósito de petrosalmuera",
			de = "Salzsteinvorkommen",
			fr = "Gisement de salinite",
			it = "Deposito di Salmastrite",
			pt = "Depósito de Salmorita",
			ru = "Залежи соляника",
			ko = "염수석 광맥",
			cn = "卤岩矿脉",
		},
	},
	[325721] = {
		readable = "Portal to Gol Koval",
		model = 166523,
		text = {
			en = "Portal to Gol Koval",
			es = "[Portal to Gol Koval]",
			de = "Portal nach Gol Koval",
			fr = "Portail vers Gol Koval",
			it = "[Portal to Gol Koval]",
			pt = "Portal para Gol Koval",
			ru = "Портал в Гол Ковал",
			ko = "[Portal to Gol Koval]",
			cn = "通往戈尔科瓦尔的传送门",
		},
	},
	[325722] = {
		readable = "Titan Translocator",
		model = 1970909,
		text = {
			en = "Titan Translocator",
			es = "Trasladador titánico",
			de = "Titanentranslokator",
			fr = "Transposeur des Titans",
			it = "Traslocatore dei Titani",
			pt = "Translocador Titânico",
			ru = "Транслокатор титанов",
			ko = "티탄 위치변환기",
			cn = "泰坦传送器",
		},
	},
	[325736] = {
		readable = "Naga War Supplies",
		model = 1096638,
		text = {
			en = "Naga War Supplies",
			es = "Suministros de guerra nagas",
			de = "Kriegsvorräte der Naga",
			fr = "Fournitures de guerre naga",
			it = "Rifornimenti di Guerra dei Naga",
			pt = "Suprimentos de Guerra das Nagas",
			ru = "Припасы наг",
			ko = "나가 전쟁 보급품",
			cn = "[Naga War Supplies]",
		},
	},
	[325740] = {
		readable = "Plundered Anima",
		model = 166432,
		text = {
			en = "Plundered Anima",
			es = "Ánima saqueada",
			de = "Geplünderte Anima",
			fr = "Anima pillé",
			it = "Animum Saccheggiato",
			pt = "Ânima Saqueada",
			ru = "Краденая анима",
			ko = "약탈당한 령",
			cn = "掠夺来的心能",
		},
	},
	[325752] = {
		readable = "Venture Co. Boosters",
		model = 1979994,
		text = {
			en = "Venture Co. Boosters",
			es = "Propulsores de Ventura y Cía.",
			de = "Schubdüsen der Venture Co.",
			fr = "Propulseurs de la KapitalRisk",
			it = "Potenziatori della S.P.R. &amp; Co.",
			pt = "Propulsores da Empreendimentos S.A.",
			ru = "Ускорители Торговой компании",
			ko = "투자개발회사 부스터",
			cn = "风险投资公司扩爆器",
		},
	},
	[325756] = {
		readable = "Azerite-Infused Munitions",
		model = 1984116,
		text = {
			en = "Azerite-Infused Munitions",
			es = "Munición imbuida de azerita",
			de = "Azeritversetzte Munition",
			fr = "Munitions imprégnées d’azérite",
			it = "Munizioni Infuse d'Azerite",
			pt = "Munições Imbuídas em Azerita",
			ru = "Обогащенные азеритом боеприпасы",
			ko = "아제라이트가 주입된 탄약",
			cn = "灌注艾泽里特的军火",
		},
	},
	[325758] = {
		readable = "Prisoner's Anima",
		model = 166432,
		text = {
			en = "Prisoner's Anima",
			es = "Ánima de prisionero",
			de = "Anima eines Gefangenen",
			fr = "Anima de prisonnier",
			it = "Animum del Prigioniero",
			pt = "Ânima do Prisioneiro",
			ru = "Анима узника",
			ko = "죄수의 령",
			cn = "囚犯的心能",
		},
	},
	[325759] = {
		readable = "Mana-Infused Clam",
		model = 311491,
		text = {
			en = "Mana-Infused Clam",
			es = "Almeja imbuida de maná",
			de = "Manaversetzte Muschel",
			fr = "Palourde imprégnée de mana",
			it = "Bivalve Infuso di mana",
			pt = "Concha Imbuída de Mana",
			ru = "Наполненная маной раковина",
			ko = "마나 깃든 조개",
			cn = "灌魔之蚌",
		},
	},
	[325760] = {
		readable = "Doodad_8DU_Mechagon_ArenaDrillTrim001",
		model = 2835978,
		text = {
			en = "Doodad_8DU_Mechagon_ArenaDrillTrim001",
			es = "[Doodad_8DU_Mechagon_ArenaDrillTrim001]",
			de = "Doodad_8DU_Mechagon_ArenaDrillTrim001",
			fr = "[Doodad_8DU_Mechagon_ArenaDrillTrim001]",
			it = "[Doodad_8DU_Mechagon_ArenaDrillTrim001]",
			pt = "Doodad_8DU_Mechagon_ArenaDrillTrim001",
			ru = "Doodad_8DU_Mechagon_ArenaDrillTrim001",
			ko = "Doodad_8DU_Mechagon_ArenaDrillTrim001",
			cn = "Doodad_8DU_Mechagon_ArenaDrillTrim001",
		},
	},
	[325761] = {
		readable = "Doodad_8DU_Mechagon_ArenaDrillTrim002",
		model = 2835978,
		text = {
			en = "Doodad_8DU_Mechagon_ArenaDrillTrim002",
			es = "[Doodad_8DU_Mechagon_ArenaDrillTrim002]",
			de = "Doodad_8DU_Mechagon_ArenaDrillTrim002",
			fr = "[Doodad_8DU_Mechagon_ArenaDrillTrim002]",
			it = "[Doodad_8DU_Mechagon_ArenaDrillTrim002]",
			pt = "Doodad_8DU_Mechagon_ArenaDrillTrim002",
			ru = "Doodad_8DU_Mechagon_ArenaDrillTrim002",
			ko = "Doodad_8DU_Mechagon_ArenaDrillTrim002",
			cn = "Doodad_8DU_Mechagon_ArenaDrillTrim002",
		},
	},
	[325762] = {
		readable = "Doodad_8DU_Mechagon_ArenaDrillTrim003",
		model = 2835978,
		text = {
			en = "Doodad_8DU_Mechagon_ArenaDrillTrim003",
			es = "[Doodad_8DU_Mechagon_ArenaDrillTrim003]",
			de = "Doodad_8DU_Mechagon_ArenaDrillTrim003",
			fr = "[Doodad_8DU_Mechagon_ArenaDrillTrim003]",
			it = "[Doodad_8DU_Mechagon_ArenaDrillTrim003]",
			pt = "Doodad_8DU_Mechagon_ArenaDrillTrim003",
			ru = "Doodad_8DU_Mechagon_ArenaDrillTrim003",
			ko = "Doodad_8DU_Mechagon_ArenaDrillTrim003",
			cn = "Doodad_8DU_Mechagon_ArenaDrillTrim003",
		},
	},
	[325763] = {
		readable = "Doodad_8DU_Mechagon_ArenaDrillTrim004",
		model = 2835978,
		text = {
			en = "Doodad_8DU_Mechagon_ArenaDrillTrim004",
			es = "[Doodad_8DU_Mechagon_ArenaDrillTrim004]",
			de = "Doodad_8DU_Mechagon_ArenaDrillTrim004",
			fr = "[Doodad_8DU_Mechagon_ArenaDrillTrim004]",
			it = "[Doodad_8DU_Mechagon_ArenaDrillTrim004]",
			pt = "Doodad_8DU_Mechagon_ArenaDrillTrim004",
			ru = "Doodad_8DU_Mechagon_ArenaDrillTrim004",
			ko = "Doodad_8DU_Mechagon_ArenaDrillTrim004",
			cn = "Doodad_8DU_Mechagon_ArenaDrillTrim004",
		},
	},
	[325764] = {
		readable = "Doodad_8DU_Mechagon_ArenaDrillTrim005",
		model = 2835978,
		text = {
			en = "Doodad_8DU_Mechagon_ArenaDrillTrim005",
			es = "[Doodad_8DU_Mechagon_ArenaDrillTrim005]",
			de = "Doodad_8DU_Mechagon_ArenaDrillTrim005",
			fr = "[Doodad_8DU_Mechagon_ArenaDrillTrim005]",
			it = "[Doodad_8DU_Mechagon_ArenaDrillTrim005]",
			pt = "Doodad_8DU_Mechagon_ArenaDrillTrim005",
			ru = "Doodad_8DU_Mechagon_ArenaDrillTrim005",
			ko = "Doodad_8DU_Mechagon_ArenaDrillTrim005",
			cn = "Doodad_8DU_Mechagon_ArenaDrillTrim005",
		},
	},
	[325765] = {
		readable = "Doodad_8DU_Mechagon_ArenaDrillTrim006",
		model = 2835978,
		text = {
			en = "Doodad_8DU_Mechagon_ArenaDrillTrim006",
			es = "[Doodad_8DU_Mechagon_ArenaDrillTrim006]",
			de = "Doodad_8DU_Mechagon_ArenaDrillTrim006",
			fr = "[Doodad_8DU_Mechagon_ArenaDrillTrim006]",
			it = "[Doodad_8DU_Mechagon_ArenaDrillTrim006]",
			pt = "Doodad_8DU_Mechagon_ArenaDrillTrim006",
			ru = "Doodad_8DU_Mechagon_ArenaDrillTrim006",
			ko = "Doodad_8DU_Mechagon_ArenaDrillTrim006",
			cn = "Doodad_8DU_Mechagon_ArenaDrillTrim006",
		},
	},
	[325766] = {
		readable = "Doodad_8DU_Mechagon_ArenaDrillTrim007",
		model = 2835978,
		text = {
			en = "Doodad_8DU_Mechagon_ArenaDrillTrim007",
			es = "[Doodad_8DU_Mechagon_ArenaDrillTrim007]",
			de = "Doodad_8DU_Mechagon_ArenaDrillTrim007",
			fr = "[Doodad_8DU_Mechagon_ArenaDrillTrim007]",
			it = "[Doodad_8DU_Mechagon_ArenaDrillTrim007]",
			pt = "Doodad_8DU_Mechagon_ArenaDrillTrim007",
			ru = "Doodad_8DU_Mechagon_ArenaDrillTrim007",
			ko = "Doodad_8DU_Mechagon_ArenaDrillTrim007",
			cn = "Doodad_8DU_Mechagon_ArenaDrillTrim007",
		},
	},
	[325767] = {
		readable = "Doodad_8DU_Mechagon_ArenaDrillTrim008",
		model = 2835978,
		text = {
			en = "Doodad_8DU_Mechagon_ArenaDrillTrim008",
			es = "[Doodad_8DU_Mechagon_ArenaDrillTrim008]",
			de = "Doodad_8DU_Mechagon_ArenaDrillTrim008",
			fr = "[Doodad_8DU_Mechagon_ArenaDrillTrim008]",
			it = "[Doodad_8DU_Mechagon_ArenaDrillTrim008]",
			pt = "Doodad_8DU_Mechagon_ArenaDrillTrim008",
			ru = "Doodad_8DU_Mechagon_ArenaDrillTrim008",
			ko = "Doodad_8DU_Mechagon_ArenaDrillTrim008",
			cn = "Doodad_8DU_Mechagon_ArenaDrillTrim008",
		},
	},
	[325768] = {
		readable = "Doodad_8DU_Mechagon_ArenaDrillTrim009",
		model = 2835978,
		text = {
			en = "Doodad_8DU_Mechagon_ArenaDrillTrim009",
			es = "[Doodad_8DU_Mechagon_ArenaDrillTrim009]",
			de = "Doodad_8DU_Mechagon_ArenaDrillTrim009",
			fr = "[Doodad_8DU_Mechagon_ArenaDrillTrim009]",
			it = "[Doodad_8DU_Mechagon_ArenaDrillTrim009]",
			pt = "Doodad_8DU_Mechagon_ArenaDrillTrim009",
			ru = "Doodad_8DU_Mechagon_ArenaDrillTrim009",
			ko = "Doodad_8DU_Mechagon_ArenaDrillTrim009",
			cn = "Doodad_8DU_Mechagon_ArenaDrillTrim009",
		},
	},
	[325769] = {
		readable = "Doodad_8DU_Mechagon_ArenaDrillTrim010",
		model = 2835978,
		text = {
			en = "Doodad_8DU_Mechagon_ArenaDrillTrim010",
			es = "[Doodad_8DU_Mechagon_ArenaDrillTrim010]",
			de = "Doodad_8DU_Mechagon_ArenaDrillTrim010",
			fr = "[Doodad_8DU_Mechagon_ArenaDrillTrim010]",
			it = "[Doodad_8DU_Mechagon_ArenaDrillTrim010]",
			pt = "Doodad_8DU_Mechagon_ArenaDrillTrim010",
			ru = "Doodad_8DU_Mechagon_ArenaDrillTrim010",
			ko = "Doodad_8DU_Mechagon_ArenaDrillTrim010",
			cn = "Doodad_8DU_Mechagon_ArenaDrillTrim010",
		},
	},
	[325770] = {
		readable = "Doodad_8DU_Mechagon_ArenaDrillTrim011",
		model = 2835978,
		text = {
			en = "Doodad_8DU_Mechagon_ArenaDrillTrim011",
			es = "[Doodad_8DU_Mechagon_ArenaDrillTrim011]",
			de = "Doodad_8DU_Mechagon_ArenaDrillTrim011",
			fr = "[Doodad_8DU_Mechagon_ArenaDrillTrim011]",
			it = "[Doodad_8DU_Mechagon_ArenaDrillTrim011]",
			pt = "Doodad_8DU_Mechagon_ArenaDrillTrim011",
			ru = "Doodad_8DU_Mechagon_ArenaDrillTrim011",
			ko = "Doodad_8DU_Mechagon_ArenaDrillTrim011",
			cn = "Doodad_8DU_Mechagon_ArenaDrillTrim011",
		},
	},
	[325771] = {
		readable = "Doodad_8DU_Mechagon_ArenaDrillTrim012",
		model = 2835978,
		text = {
			en = "Doodad_8DU_Mechagon_ArenaDrillTrim012",
			es = "[Doodad_8DU_Mechagon_ArenaDrillTrim012]",
			de = "Doodad_8DU_Mechagon_ArenaDrillTrim012",
			fr = "[Doodad_8DU_Mechagon_ArenaDrillTrim012]",
			it = "[Doodad_8DU_Mechagon_ArenaDrillTrim012]",
			pt = "Doodad_8DU_Mechagon_ArenaDrillTrim012",
			ru = "Doodad_8DU_Mechagon_ArenaDrillTrim012",
			ko = "Doodad_8DU_Mechagon_ArenaDrillTrim012",
			cn = "Doodad_8DU_Mechagon_ArenaDrillTrim012",
		},
	},
	[325772] = {
		readable = "Doodad_8DU_Mechagon_ArenaDrillTrim013",
		model = 2835978,
		text = {
			en = "Doodad_8DU_Mechagon_ArenaDrillTrim013",
			es = "[Doodad_8DU_Mechagon_ArenaDrillTrim013]",
			de = "Doodad_8DU_Mechagon_ArenaDrillTrim013",
			fr = "[Doodad_8DU_Mechagon_ArenaDrillTrim013]",
			it = "[Doodad_8DU_Mechagon_ArenaDrillTrim013]",
			pt = "Doodad_8DU_Mechagon_ArenaDrillTrim013",
			ru = "Doodad_8DU_Mechagon_ArenaDrillTrim013",
			ko = "Doodad_8DU_Mechagon_ArenaDrillTrim013",
			cn = "Doodad_8DU_Mechagon_ArenaDrillTrim013",
		},
	},
	[325773] = {
		readable = "Doodad_8DU_Mechagon_ArenaDrillTrim014",
		model = 2835978,
		text = {
			en = "Doodad_8DU_Mechagon_ArenaDrillTrim014",
			es = "[Doodad_8DU_Mechagon_ArenaDrillTrim014]",
			de = "Doodad_8DU_Mechagon_ArenaDrillTrim014",
			fr = "[Doodad_8DU_Mechagon_ArenaDrillTrim014]",
			it = "[Doodad_8DU_Mechagon_ArenaDrillTrim014]",
			pt = "Doodad_8DU_Mechagon_ArenaDrillTrim014",
			ru = "Doodad_8DU_Mechagon_ArenaDrillTrim014",
			ko = "Doodad_8DU_Mechagon_ArenaDrillTrim014",
			cn = "Doodad_8DU_Mechagon_ArenaDrillTrim014",
		},
	},
	[325774] = {
		readable = "Doodad_8DU_Mechagon_ArenaDrillTrim015",
		model = 2835978,
		text = {
			en = "Doodad_8DU_Mechagon_ArenaDrillTrim015",
			es = "[Doodad_8DU_Mechagon_ArenaDrillTrim015]",
			de = "Doodad_8DU_Mechagon_ArenaDrillTrim015",
			fr = "[Doodad_8DU_Mechagon_ArenaDrillTrim015]",
			it = "[Doodad_8DU_Mechagon_ArenaDrillTrim015]",
			pt = "Doodad_8DU_Mechagon_ArenaDrillTrim015",
			ru = "Doodad_8DU_Mechagon_ArenaDrillTrim015",
			ko = "Doodad_8DU_Mechagon_ArenaDrillTrim015",
			cn = "Doodad_8DU_Mechagon_ArenaDrillTrim015",
		},
	},
	[325775] = {
		readable = "Doodad_8DU_Mechagon_ArenaDrillTrim016",
		model = 2835978,
		text = {
			en = "Doodad_8DU_Mechagon_ArenaDrillTrim016",
			es = "[Doodad_8DU_Mechagon_ArenaDrillTrim016]",
			de = "Doodad_8DU_Mechagon_ArenaDrillTrim016",
			fr = "[Doodad_8DU_Mechagon_ArenaDrillTrim016]",
			it = "[Doodad_8DU_Mechagon_ArenaDrillTrim016]",
			pt = "Doodad_8DU_Mechagon_ArenaDrillTrim016",
			ru = "Doodad_8DU_Mechagon_ArenaDrillTrim016",
			ko = "Doodad_8DU_Mechagon_ArenaDrillTrim016",
			cn = "Doodad_8DU_Mechagon_ArenaDrillTrim016",
		},
	},
	[325776] = {
		readable = "Doodad_8DU_Mechagon_ArenaDrillTrim017",
		model = 2835978,
		text = {
			en = "Doodad_8DU_Mechagon_ArenaDrillTrim017",
			es = "[Doodad_8DU_Mechagon_ArenaDrillTrim017]",
			de = "Doodad_8DU_Mechagon_ArenaDrillTrim017",
			fr = "[Doodad_8DU_Mechagon_ArenaDrillTrim017]",
			it = "[Doodad_8DU_Mechagon_ArenaDrillTrim017]",
			pt = "Doodad_8DU_Mechagon_ArenaDrillTrim017",
			ru = "Doodad_8DU_Mechagon_ArenaDrillTrim017",
			ko = "Doodad_8DU_Mechagon_ArenaDrillTrim017",
			cn = "Doodad_8DU_Mechagon_ArenaDrillTrim017",
		},
	},
	[325777] = {
		readable = "Doodad_8DU_Mechagon_ArenaDrillTrim018",
		model = 2835978,
		text = {
			en = "Doodad_8DU_Mechagon_ArenaDrillTrim018",
			es = "[Doodad_8DU_Mechagon_ArenaDrillTrim018]",
			de = "Doodad_8DU_Mechagon_ArenaDrillTrim018",
			fr = "[Doodad_8DU_Mechagon_ArenaDrillTrim018]",
			it = "[Doodad_8DU_Mechagon_ArenaDrillTrim018]",
			pt = "Doodad_8DU_Mechagon_ArenaDrillTrim018",
			ru = "Doodad_8DU_Mechagon_ArenaDrillTrim018",
			ko = "Doodad_8DU_Mechagon_ArenaDrillTrim018",
			cn = "Doodad_8DU_Mechagon_ArenaDrillTrim018",
		},
	},
	[325778] = {
		readable = "Doodad_8DU_Mechagon_ArenaDrillTrim019",
		model = 2835978,
		text = {
			en = "Doodad_8DU_Mechagon_ArenaDrillTrim019",
			es = "[Doodad_8DU_Mechagon_ArenaDrillTrim019]",
			de = "Doodad_8DU_Mechagon_ArenaDrillTrim019",
			fr = "[Doodad_8DU_Mechagon_ArenaDrillTrim019]",
			it = "[Doodad_8DU_Mechagon_ArenaDrillTrim019]",
			pt = "Doodad_8DU_Mechagon_ArenaDrillTrim019",
			ru = "Doodad_8DU_Mechagon_ArenaDrillTrim019",
			ko = "Doodad_8DU_Mechagon_ArenaDrillTrim019",
			cn = "Doodad_8DU_Mechagon_ArenaDrillTrim019",
		},
	},
	[325779] = {
		readable = "Doodad_8DU_Mechagon_ArenaDrillTrim020",
		model = 2835978,
		text = {
			en = "Doodad_8DU_Mechagon_ArenaDrillTrim020",
			es = "[Doodad_8DU_Mechagon_ArenaDrillTrim020]",
			de = "Doodad_8DU_Mechagon_ArenaDrillTrim020",
			fr = "[Doodad_8DU_Mechagon_ArenaDrillTrim020]",
			it = "[Doodad_8DU_Mechagon_ArenaDrillTrim020]",
			pt = "Doodad_8DU_Mechagon_ArenaDrillTrim020",
			ru = "Doodad_8DU_Mechagon_ArenaDrillTrim020",
			ko = "Doodad_8DU_Mechagon_ArenaDrillTrim020",
			cn = "Doodad_8DU_Mechagon_ArenaDrillTrim020",
		},
	},
	[325780] = {
		readable = "Doodad_8DU_Mechagon_ArenaDrillTrim021",
		model = 2835978,
		text = {
			en = "Doodad_8DU_Mechagon_ArenaDrillTrim021",
			es = "[Doodad_8DU_Mechagon_ArenaDrillTrim021]",
			de = "Doodad_8DU_Mechagon_ArenaDrillTrim021",
			fr = "[Doodad_8DU_Mechagon_ArenaDrillTrim021]",
			it = "[Doodad_8DU_Mechagon_ArenaDrillTrim021]",
			pt = "Doodad_8DU_Mechagon_ArenaDrillTrim021",
			ru = "Doodad_8DU_Mechagon_ArenaDrillTrim021",
			ko = "Doodad_8DU_Mechagon_ArenaDrillTrim021",
			cn = "Doodad_8DU_Mechagon_ArenaDrillTrim021",
		},
	},
	[325781] = {
		readable = "Doodad_8DU_Mechagon_ArenaDrillTrim022",
		model = 2835978,
		text = {
			en = "Doodad_8DU_Mechagon_ArenaDrillTrim022",
			es = "[Doodad_8DU_Mechagon_ArenaDrillTrim022]",
			de = "Doodad_8DU_Mechagon_ArenaDrillTrim022",
			fr = "[Doodad_8DU_Mechagon_ArenaDrillTrim022]",
			it = "[Doodad_8DU_Mechagon_ArenaDrillTrim022]",
			pt = "Doodad_8DU_Mechagon_ArenaDrillTrim022",
			ru = "Doodad_8DU_Mechagon_ArenaDrillTrim022",
			ko = "Doodad_8DU_Mechagon_ArenaDrillTrim022",
			cn = "Doodad_8DU_Mechagon_ArenaDrillTrim022",
		},
	},
	[325782] = {
		readable = "Doodad_8DU_Mechagon_ArenaDrillTrim023",
		model = 2835978,
		text = {
			en = "Doodad_8DU_Mechagon_ArenaDrillTrim023",
			es = "[Doodad_8DU_Mechagon_ArenaDrillTrim023]",
			de = "Doodad_8DU_Mechagon_ArenaDrillTrim023",
			fr = "[Doodad_8DU_Mechagon_ArenaDrillTrim023]",
			it = "[Doodad_8DU_Mechagon_ArenaDrillTrim023]",
			pt = "Doodad_8DU_Mechagon_ArenaDrillTrim023",
			ru = "Doodad_8DU_Mechagon_ArenaDrillTrim023",
			ko = "Doodad_8DU_Mechagon_ArenaDrillTrim023",
			cn = "Doodad_8DU_Mechagon_ArenaDrillTrim023",
		},
	},
	[325783] = {
		readable = "Doodad_8DU_Mechagon_ArenaDrillTrim024",
		model = 2835978,
		text = {
			en = "Doodad_8DU_Mechagon_ArenaDrillTrim024",
			es = "[Doodad_8DU_Mechagon_ArenaDrillTrim024]",
			de = "Doodad_8DU_Mechagon_ArenaDrillTrim024",
			fr = "[Doodad_8DU_Mechagon_ArenaDrillTrim024]",
			it = "[Doodad_8DU_Mechagon_ArenaDrillTrim024]",
			pt = "Doodad_8DU_Mechagon_ArenaDrillTrim024",
			ru = "Doodad_8DU_Mechagon_ArenaDrillTrim024",
			ko = "Doodad_8DU_Mechagon_ArenaDrillTrim024",
			cn = "Doodad_8DU_Mechagon_ArenaDrillTrim024",
		},
	},
	[325784] = {
		readable = "Place Scarab Figurine",
		model = 315528,
		text = {
			en = "Place Scarab Figurine",
			es = "Colocar figurilla de escarabajo",
			de = "Juwelenbesetzte Skarabäusfigur platzieren",
			fr = "[Place Scarab Figurine]",
			it = "[Place Scarab Figurine]",
			pt = "[Place Scarab Figurine]",
			ru = "Возложить фигурку скарабея",
			ko = "[Place Scarab Figurine]",
			cn = "[Place Scarab Figurine]",
		},
	},
	[325788] = {
		readable = "Bootleg Armor Plating",
		model = 1349034,
		text = {
			en = "Bootleg Armor Plating",
			es = "Coraza de armadura de contrabando",
			de = "Geschmuggelte Panzerung",
			fr = "Plaque d’armure de contrebande",
			it = "Piastre Rinforzate di Contrabbando",
			pt = "Blindagem Pirata",
			ru = "Нелегальная обшивка",
			ko = "불법 판금 갑옷",
			cn = "偷运的机甲外壳",
		},
	},
	[325789] = {
		readable = "Rubble",
		model = 200950,
		text = {
			en = "Rubble",
			es = "Escombros",
			de = "Geröll",
			fr = "Décombres",
			it = "Detrito",
			pt = "Escombros",
			ru = "Обломки",
			ko = "돌무더기",
			cn = "碎石",
		},
	},
	[325790] = {
		readable = "Molted Shell",
		model = 2845751,
		text = {
			en = "Molted Shell",
			es = "Caparazón mudado",
			de = "Abgeworfener Panzer",
			fr = "Exuvie",
			it = "Carapace di Muta",
			pt = "Carapaça de Muda",
			ru = "Сброшенный панцирь",
			ko = "탈피된 껍질",
			cn = "蜕下的壳",
		},
	},
	[325791] = {
		readable = "Rough Fire Spinel",
		model = 1282666,
		text = {
			en = "Rough Fire Spinel",
			es = "[Rough Fire Spinel]",
			de = "Rauer Feuerspinell",
			fr = "Spinelle de feu brut",
			it = "[Rough Fire Spinel]",
			pt = "Espinélio-de-fogo Bruto",
			ru = "Грубая огненная шпинель",
			ko = "[Rough Fire Spinel]",
			cn = "[Rough Fire Spinel]",
		},
	},
	[325799] = {
		readable = "Pile of Flotsam",
		model = 1091569,
		text = {
			en = "Pile of Flotsam",
			es = "Montón de restos flotantes",
			de = "Haufen Treibgut",
			fr = "Tas de débris",
			it = "Mucchio di Rottami",
			pt = "Pilha de Destroços",
			ru = "Куча обломков",
			ko = "표류물 더미",
			cn = "一堆漂浮物",
		},
	},
	[393963] = {
		readable = "Prisoner Transfer Notes",
		model = 936429,
		text = {
			en = "Prisoner Transfer Notes",
			es = "Órdenes de traslado de prisioneros",
			de = "Gefangenentransferbefehle",
			fr = "Notes de transfert de prisonniers",
			it = "Appunti sul Trasferimento del Prigioniero",
			pt = "Notas de Transferência de Prisioneiro",
			ru = "Записи о переводе заключенных",
			ko = "포로 호송 기록",
			cn = "[Prisoner Transfer Notes]",
		},
	},
})
do ObjectDB[objectID] = objectData; end