local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[409120] = {
		readable = "Cache of Cosmic Mysteries",
		model = 5338871,
		text = {
			en = "Cache of Cosmic Mysteries",
			es = "Alijo de misterios cósmicos",
			de = "Behälter voller kosmischer Mysterien",
			fr = "Cache des mystères cosmiques",
			it = "[Cache of Cosmic Mysteries]",
			pt = "Baú de Mistérios Cósmicos",
			ru = "Тайник космических секретов",
			ko = "[Cache of Cosmic Mysteries]",
			cn = "[Cache of Cosmic Mysteries]",
		},
	},
	[409166] = {
		readable = "Titan Power Relay",
		model = 4663520,
		text = {
			en = "Titan Power Relay",
			es = "Repetidor de poder titánico",
			de = "Titanenkraftrelais",
			fr = "Relais de puissance des Titans",
			it = "Ripetitore Energetico dei Titani",
			pt = "Relé de Energia Titânica",
			ru = "Ретранслятор энергии титанов",
			ko = "티탄 동력 중계기",
			cn = "泰坦能量中继器",
		},
	},
	[409200] = {
		readable = "Broken Urn",
		model = 4609995,
		text = {
			en = "Broken Urn",
			es = "Urna rota",
			de = "Zerbrochene Urne",
			fr = "Urne brisée",
			it = "[Broken Urn]",
			pt = "Urna Quebrada",
			ru = "Разбитая урна",
			ko = "[Broken Urn]",
			cn = "破损的瓮",
		},
	},
	[409208] = {
		readable = "Broken Urn",
		model = 4609995,
		text = {
			en = "Broken Urn",
			es = "Urna rota",
			de = "Zerbrochene Urne",
			fr = "Urne brisée",
			it = "[Broken Urn]",
			pt = "Urna Quebrada",
			ru = "Разбитая урна",
			ko = "[Broken Urn]",
			cn = "破损的瓮",
		},
	},
	[409209] = {
		readable = "Broken Urn",
		model = 4609995,
		text = {
			en = "Broken Urn",
			es = "Urna rota",
			de = "Zerbrochene Urne",
			fr = "Urne brisée",
			it = "[Broken Urn]",
			pt = "Urna Quebrada",
			ru = "Разбитая урна",
			ko = "깨진 단지",
			cn = "破损的瓮",
		},
	},
	[409211] = {
		readable = "Broken Urn",
		model = 4609995,
		text = {
			en = "Broken Urn",
			es = "Urna rota",
			de = "Zerbrochene Urne",
			fr = "Urne brisée",
			it = "[Broken Urn]",
			pt = "Urna Quebrada",
			ru = "Разбитая урна",
			ko = "깨진 단지",
			cn = "破损的瓮",
		},
	},
	[409212] = {
		readable = "Broken Urn",
		model = 4609995,
		text = {
			en = "Broken Urn",
			es = "Urna rota",
			de = "Zerbrochene Urne",
			fr = "Urne brisée",
			it = "[Broken Urn]",
			pt = "Urna Quebrada",
			ru = "Разбитая урна",
			ko = "[Broken Urn]",
			cn = "破损的瓮",
		},
	},
	[409214] = {
		readable = "Broken Urn",
		model = 4609995,
		text = {
			en = "Broken Urn",
			es = "Urna rota",
			de = "Zerbrochene Urne",
			fr = "Urne brisée",
			it = "[Broken Urn]",
			pt = "Urna Quebrada",
			ru = "Разбитая урна",
			ko = "깨진 단지",
			cn = "破损的瓮",
		},
	},
	[409914] = {
		readable = "Mimiron's Booster Part",
		model = 2745106,
		text = {
			en = "Mimiron's Booster Part",
			es = "Pieza del propulsor de Mimiron",
			de = "Mimirons Boosterteil",
			fr = "Pièce du propulseur de Mimiron",
			it = "Parte di Potenziamento di Mimiron",
			pt = "Peça Propulsora de Mimiron",
			ru = "Часть усилителя Мимирона",
			ko = "미미론의 증폭기 부품",
			cn = "米米尔隆的助推器零件",
		},
	},
	[410426] = {
		readable = "Half-Filled Dreamless Sleep Potion",
		model = 2833934,
		text = {
			en = "Half-Filled Dreamless Sleep Potion",
			es = "Poción de letargo sin sueños a la mitad",
			de = "Halbvoller Trank des traumlosen Schlafs",
			fr = "Potion de sommeil sans rêve supérieure à moitié pleine",
			it = "Pozione Mezza Piena del Sonno Senza Sogni",
			pt = "Poção do Sono sem Sonhos pela Metade",
			ru = "Полупустое зелье сна без сновидений",
			ko = "반쯤 채운 숙면의 물약",
			cn = "装了一半的无梦睡眠药水",
		},
	},
	[410434] = {
		readable = "Splash Potion of Narcolepsy",
		model = 2833934,
		text = {
			en = "Splash Potion of Narcolepsy",
			es = "Poción salpicante de narcolepsia",
			de = "Spritztrank der Narkolepsie",
			fr = "Potion d’aspergement de narcolepsie",
			it = "Pozione a Spruzzo della Narcolessia",
			pt = "Poção Borrifante da Narcolepsia",
			ru = "Зелье всплеска нарколепсии",
			ko = "졸음병의 물보라 물약",
			cn = "飞溅昏睡药水",
		},
	},
	[410456] = {
		readable = "Experimental Dreamcatcher",
		model = 2833991,
		text = {
			en = "Experimental Dreamcatcher",
			es = "Atrapasueños experimental",
			de = "Experimenteller Traumfänger",
			fr = "Capturêve experimental",
			it = "Acchiappasogni Sperimentale",
			pt = "Apanhador de Sonhos Experimental",
			ru = "Экспериментальный ловец снов",
			ko = "실험적인 꿈잡이",
			cn = "实验型捕梦网",
		},
	},
	[410458] = {
		readable = "Insomniotron",
		model = 2367468,
		text = {
			en = "Insomniotron",
			es = "Insomniotrón",
			de = "Schlaflositron",
			fr = "Insomniotron",
			it = "Insonniatron",
			pt = "Insoniatron",
			ru = "Бессонотрон",
			ko = "불면증 로봇",
			cn = "无眠机",
		},
	},
	[410469] = {
		readable = "Unhatched Battery",
		model = 2736566,
		text = {
			en = "Unhatched Battery",
			es = "Batería sin abrir",
			de = "Ungeschlüpfte Batterie",
			fr = "Batterie non éclose",
			it = "Batteria Non Schiusa",
			pt = "Pilha Choca",
			ru = "Непроклюнувшаяся батарея",
			ko = "개봉하지 않은 전지",
			cn = "没孵出的电池",
		},
	},
	[410475] = {
		readable = "Petrified Hope",
		model = 1037393,
		text = {
			en = "Petrified Hope",
			es = "Esperanza petrificada",
			de = "Versteinerte Hoffnung",
			fr = "Espoir pétrifié",
			it = "Speranza Pietrificata",
			pt = "Esperança Petrificada",
			ru = "Окаменевшая надежда",
			ko = "석화된 희망",
			cn = "石化希望",
		},
	},
	[410529] = {
		readable = "Tuft of Dreamsaber Fur",
		model = 1334477,
		text = {
			en = "Tuft of Dreamsaber Fur",
			es = "Mechón de pelaje de sable onírico",
			de = "Büschel Traumsäblerfell",
			fr = "Touffe de poils de sabre de rêve",
			it = "Ciuffo di Pelliccia di Fieronirica",
			pt = "Tufo de Pelo de Sabre-do-sonho",
			ru = "Клок шерсти саблезуба из Сна",
			ko = "꿈표범 털 뭉치",
			cn = "一簇梦刃豹皮毛",
		},
	},
	[410534] = {
		readable = "Molted Faerie Dragon Scales",
		model = 1301126,
		text = {
			en = "Molted Faerie Dragon Scales",
			es = "Escamas de dragón feérico mudadas",
			de = "Abgeworfene Feendrachenschuppen",
			fr = "Mue d’écailles de dragon féerique",
			it = "Scaglie di Drago Fatato Fuse",
			pt = "Escamas de Muda de Dragoleta",
			ru = "Расплавленная чешуя чудесного дракончика",
			ko = "벗겨진 요정용의 비늘",
			cn = "蜕下的精灵龙之鳞",
		},
	},
	[410550] = {
		readable = "Dreamtalon Claw",
		model = 202801,
		text = {
			en = "Dreamtalon Claw",
			es = "Garra de garfasueño",
			de = "Traumkrallenklaue",
			fr = "Serre de serre de rêve",
			it = "Artiglio di Sognartiglio",
			pt = "Garra de Somnigarra",
			ru = "Коготь ящера из Сна",
			ko = "꿈갈퀴 발톱",
			cn = "梦爪獍之爪",
		},
	},
	[410575] = {
		readable = "Everburning Core",
		model = 4508235,
		text = {
			en = "Everburning Core",
			es = "Núcleo de llama perpetua",
			de = "Immerflammenkern",
			fr = "Noyau semperardent",
			it = "Nucleo Inestinguibile",
			pt = "Núcleo do Ardor Perene",
			ru = "Вечнопылающий сердечник",
			ko = "영원히 타오르는 핵",
			cn = "永燃之核",
		},
	},
	[410786] = {
		readable = "Alydrus' Research Notes",
		model = 1367372,
		text = {
			en = "Alydrus' Research Notes",
			es = "Notas de investigación de Alydrus",
			de = "Alydrus' Forschungsnotizen",
			fr = "Notes de recherche d’Alydrus",
			it = "Appunti di Ricerca di Alydrus",
			pt = "Anotações de Pesquisa de Alydrus",
			ru = "Исследовательские записи Алидрии",
			ko = "[Alydrus' Research Notes]",
			cn = "[Alydrus' Research Notes]",
		},
	},
	[410833] = {
		readable = "The Reforging of the Tyr's Guard",
		model = 198017,
		text = {
			en = "The Reforging of the Tyr's Guard",
			es = "La reforja de la Guardia de Tyr",
			de = "Die Neuschmiedung von Tyrs Wache",
			fr = "Reforger la Garde de Tyr",
			it = "Riforgiatura della Guardia di Tyr",
			pt = "Reforja da Guarda de Tyr",
			ru = "Возрождение Стражей Тира",
			ko = "티르의 수호병 재결성",
			cn = "提尔近卫的重建",
		},
	},
	[411065] = {
		readable = "Boon of Ashamane",
		model = 3522548,
		text = {
			en = "Boon of Ashamane",
			es = "Boon of Ashamane",
			de = "Segen von Ashamane",
			fr = "Bienfait d’Ashamane",
			it = "[Boon of Ashamane]",
			pt = "Bênção de Ashamane",
			ru = "Дар Пеплошкурой",
			ko = "아샤메인의 은혜",
			cn = "阿莎曼的恩泽",
		},
	},
	[411168] = {
		readable = "Winnie's Notes on Flora and Fauna",
		model = 4298558,
		text = {
			en = "Winnie's Notes on Flora and Fauna",
			es = "Notas de Winnie sobre la flora y la fauna",
			de = "Winnies Notizen zu Flora und Fauna",
			fr = "Notes de Winnie sur la flore et la faune",
			it = "Appunti sulla Flora e sulla Fauna di Winnie",
			pt = "Observações do Puff sobre a Flora e a Fauna",
			ru = "Записки Винни о флоре и фауне",
			ko = "동식물에 관한 위니의 기록",
			cn = "威尼的动植物笔记",
		},
	},
	[411170] = {
		readable = "Primalist Shadowbinding Rune",
		model = 4485591,
		text = {
			en = "Primalist Shadowbinding Rune",
			es = "Runa vinculasombras primalista",
			de = "Schattenbindungsrune der Primalisten",
			fr = "Rune d’ombrelien primaliste",
			it = "Runa del Vincolo d'Ombra Primalista",
			pt = "Runa de Grilhão de Sombra Primevista",
			ru = "Руна уз тьмы воинов стихий",
			ko = "원시술사 어둠결속 룬",
			cn = "拜荒者影缚符文",
		},
	},
	[411177] = {
		readable = "Snuggle Buddy",
		model = 3563973,
		text = {
			en = "Snuggle Buddy",
			es = "Coleguita peluchín",
			de = "Kuschelkumpel",
			fr = "Copain de câlin",
			it = "Compagno di Coccole",
			pt = "Abracito",
			ru = "Обнимашка",
			ko = "쿨쿨 친구",
			cn = "依偎伙伴",
		},
	},
	[411180] = {
		readable = "Deathstalker Chassis",
		model = 950715,
		text = {
			en = "Deathstalker Chassis",
			es = "Chasis de mortacechador",
			de = "Todespirscherchassis",
			fr = "Châssis de nécrotraqueur",
			it = "Telaio dell'Inseguitore della Morte",
			pt = "Chassi de Sicário",
			ru = "Каркас ловчего смерти",
			ko = "죽음추적자 골격",
			cn = "死亡猎手底盘",
		},
	},
	[411181] = {
		readable = "Flamesworn Render",
		model = 4576987,
		text = {
			en = "Flamesworn Render",
			es = "Desgarrador jurallamas",
			de = "Flammengebundener Reißer",
			fr = "Moissonneur flammelige",
			it = "Strappo del Giurafiamma",
			pt = "Dilacerador do Devoto da Chama",
			ru = "Раздиратель огненной клятвы",
			ko = "화염서약 분쇄자",
			cn = "焰誓碎裂者",
		},
	},
	[411466] = {
		readable = "Unwaking Echo",
		model = 1349621,
		text = {
			en = "Unwaking Echo",
			es = "Eco del despertar",
			de = "Nie erwachendes Echo",
			fr = "Écho non réveillé",
			it = "Eco del Non Risveglio",
			pt = "Eco Indesperto",
			ru = "Непробуждающийся отголосок",
			ko = "깨어나지 않는 메아리",
			cn = "酣眠回响",
		},
	},
	[411936] = {
		readable = "Orb Location",
		model = 4485606,
		text = {
			en = "Orb Location",
			es = "Ubicación de orbe",
			de = "Kugelposition",
			fr = "Emplacement de l’orbe",
			it = "[Orb Location]",
			pt = "Local do Orbe",
			ru = "Местонахождение сферы",
			ko = "[Orb Location]",
			cn = "[Orb Location]",
		},
	},
	[412950] = {
		readable = "Moon-Blessed Claw",
		model = 202801,
		text = {
			en = "Moon-Blessed Claw",
			es = "Garra bendecida por la luna",
			de = "Mondgesegnete Klaue",
			fr = "Griffe bénie par la Lune",
			it = "[Moon-Blessed Claw]",
			pt = "[Moon-Blessed Claw]",
			ru = "Благословленный луной коготь",
			ko = "[Moon-Blessed Claw]",
			cn = "[Moon-Blessed Claw]",
		},
	},
	[412995] = {
		readable = "Small Box of Vials",
		model = 3917382,
		text = {
			en = "Small Box of Vials",
			es = "Caja pequeña de viales",
			de = "Kleine Schachtel mit Phiolen",
			fr = "Petite boîte de fioles",
			it = "Piccola Scatola di Fiale",
			pt = "Caixinha de Ampolas",
			ru = "Маленькая коробка с флаконами",
			ko = "작은 약병 상자",
			cn = "[Small Box of Vials]",
		},
	},
	[413774] = {
		readable = "The Legend of Elun'Ahir",
		model = 1124086,
		text = {
			en = "The Legend of Elun'Ahir",
			es = "La leyenda de Elun'ahir",
			de = "Die Legende von Elun'Ahir",
			fr = "La légende d’Élun’Ahir",
			it = "La Leggenda di Elun'ahir",
			pt = "Lenda de Elun'Ahir",
			ru = "Легенда об Элун'ахире",
			ko = "엘룬아히르의 전설",
			cn = "《艾露阿希的传说》",
		},
	},
	[413780] = {
		readable = "On the Nature of the Dream",
		model = 4861837,
		text = {
			en = "On the Nature of the Dream",
			es = "Sobre la naturaleza del Sueño",
			de = "Über das Wesen des Traums",
			fr = "De la nature du Rêve",
			it = "Sulla Natura del Sogno",
			pt = "Sobre a Natureza do Sonho",
			ru = "О природе Сна",
			ko = "꿈의 본질에 관하여",
			cn = "《论梦境的本质》",
		},
	},
	[413787] = {
		readable = "The Tragedy of Erinethria",
		model = 4861836,
		text = {
			en = "The Tragedy of Erinethria",
			es = "La tragedia de Erinethria",
			de = "Die Tragödie von Erinethria",
			fr = "La tragédie d’Érinéthria",
			it = "La Tragedia di Erinehria",
			pt = "A Tragédia de Erinethria",
			ru = "Трагедия Эринетрии",
			ko = "에리네스리아의 비극",
			cn = "《艾莉涅希亚的悲剧》",
		},
	},
})
do ObjectDB[objectID] = objectData; end