local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[105169] = {
		readable = "Agamand Weapon Rack",
		model = 198636,
		text = {
			en = "Agamand Weapon Rack",
			es = "Portaarmas de Agamand",
			de = "Agamands Waffenregal",
			fr = "Râtelier d'armes Agamand",
			it = "Agamand Weapon Rack",
			pt = "Cavalete de Armas dos Agamand",
			ru = "Оружейная стойка Агамонда",
			ko = "아가만드 무기 선반",
			cn = "[Agamand Weapon Rack]",
		},
	},
	[105170] = {
		readable = "Agamand Weapon Rack",
		model = 198636,
		text = {
			en = "Agamand Weapon Rack",
			es = "Portaarmas de Agamand",
			de = "Agamands Waffenregal",
			fr = "Râtelier d'armes Agamand",
			it = "Agamand Weapon Rack",
			pt = "Cavalete de Armas dos Agamand",
			ru = "Оружейная стойка Агамонда",
			ko = "아가만드 무기 선반",
			cn = "[Agamand Weapon Rack]",
		},
	},
	[105171] = {
		readable = "Agamand Weapon Rack",
		model = 198636,
		text = {
			en = "Agamand Weapon Rack",
			es = "Portaarmas de Agamand",
			de = "Agamands Waffenregal",
			fr = "Râtelier d'armes Agamand",
			it = "Agamand Weapon Rack",
			pt = "Cavalete de Armas dos Agamand",
			ru = "Оружейная стойка Агамонда",
			ko = "아가만드 무기 선반",
			cn = "[Agamand Weapon Rack]",
		},
	},
	[105172] = {
		readable = "Agamand Weapon Rack",
		model = 198636,
		text = {
			en = "Agamand Weapon Rack",
			es = "Portaarmas de Agamand",
			de = "Agamands Waffenregal",
			fr = "Râtelier d'armes Agamand",
			it = "Agamand Weapon Rack",
			pt = "Cavalete de Armas dos Agamand",
			ru = "Оружейная стойка Агамонда",
			ko = "아가만드 무기 선반",
			cn = "[Agamand Weapon Rack]",
		},
	},
})
do ObjectDB[objectID] = objectData; end