local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[454313] = {
		readable = "Queen Xekatha",
		model = 5760596,
		text = {
			en = "Queen Xekatha",
			es = "Reina Xekatha",
			de = "Königin Xekatha",
			fr = "Reine Xekatha",
			it = "Regina Xekatha",
			pt = "Rainha Xekatha",
			ru = "Королева Зеката",
			ko = "여왕 제카타",
			cn = "泽卡莎女王",
		},
	},
	[454316] = {
		readable = "Queen Zaltra",
		model = 5760596,
		text = {
			en = "Queen Zaltra",
			es = "Reina Zaltra",
			de = "Königin Zavra",
			fr = "Reine Zaltra",
			it = "Regina Zaltra",
			pt = "Rainha Zaltra",
			ru = "Королева Залтра",
			ko = "여왕 잘트라",
			cn = "扎特拉女王",
		},
	},
	[454320] = {
		readable = "Queen Anub'izek",
		model = 5760596,
		text = {
			en = "Queen Anub'izek",
			es = "Reina Anub'izek",
			de = "Königin Anub'izek",
			fr = "Reine Anub’izek",
			it = "Regina Anub'izek",
			pt = "Rainha Anub'izek",
			ru = "Королева Ануб'изек",
			ko = "여왕 아눕이제크",
			cn = "阿努比泽克女王",
		},
	},
	[454328] = {
		readable = "Strands of Memory",
		model = 5760596,
		text = {
			en = "Strands of Memory",
			es = "Hebras de memoria",
			de = "Stränge der Erinnerung",
			fr = "Filaments de souvenir",
			it = "Filamenti di Ricordo",
			pt = "Fios da Memória",
			ru = "Нити памяти",
			ko = "기억의 가닥",
			cn = "记忆丝弦",
		},
	},
	[454330] = {
		readable = "Treatise on Forms: Skitterlings",
		model = 5760596,
		text = {
			en = "Treatise on Forms: Skitterlings",
			es = "Tratado sobre las formas: arañuelas",
			de = "Abhandlung über Gestalten: Huscher",
			fr = "Traité sur les formes : grouilleurs",
			it = "Trattato sulle Forme: Artropodi",
			pt = "Tratado sobre Formas: Aracnitos",
			ru = "Атлас форм: быстролапы",
			ko = "형상 논문: 땅거미족",
			cn = "《形态论述：掠行蛴》",
		},
	},
	[454331] = {
		readable = "Thimble's Cache",
		model = 5007036,
		text = {
			en = "Thimble's Cache",
			es = "Alijo de Dedal",
			de = "Fingerhuts Vorräte",
			fr = "Cachette de Croquette",
			it = "Cassa di Tessitino",
			pt = "Thimble's Cache",
			ru = "Тайник Наперстика",
			ko = "Thimble's Cache",
			cn = "Thimble's Cache",
		},
	},
	[454332] = {
		readable = "Treatise on Forms: Sages",
		model = 5760596,
		text = {
			en = "Treatise on Forms: Sages",
			es = "Tratado sobre las formas: sabios",
			de = "Abhandlung über Gestalten: Weise",
			fr = "Traité sur les formes : sages",
			it = "Trattato sulle Forme: Saggi",
			pt = "Tratado sobre Formas: Sábios",
			ru = "Атлас форм: мудрецы",
			ko = "형상 논문: 현자",
			cn = "《形态论述：贤者》",
		},
	},
	[454335] = {
		readable = "Entomological Essay on Grubs, Volume 1",
		model = 5007025,
		text = {
			en = "Entomological Essay on Grubs, Volume 1",
			es = "Ensayos etimológicos sobre larvas, volumen 1",
			de = "Entomologische Abhandlung über Maden, Band 1",
			fr = "Essai entomologique sur les vers, volume 1",
			it = "Saggio Entomologico sulle Larve, Volume 1",
			pt = "Ensaio Entomológico sobre Larvas, Volume 1",
			ru = "Энтомологическое эссе о личинках, том 1",
			ko = "땅벌레에 관한 곤충학적 소론, 1권",
			cn = "《关于肉虫的昆虫学论文：第1卷》",
		},
	},
	[454336] = {
		readable = "Entomological Essay on Grubs, Volume 2",
		model = 5007025,
		text = {
			en = "Entomological Essay on Grubs, Volume 2",
			es = "Ensayos etimológicos sobre larvas, volumen 2",
			de = "Entomologische Abhandlung über Maden, Band 2",
			fr = "Essai entomologique sur les vers, volume 2",
			it = "Saggio Entomologico sulle Larve, Volume 2",
			pt = "Ensaio Entomológico sobre Larvas, Volume 2",
			ru = "Энтомологическое эссе о личинках, том 2",
			ko = "땅벌레에 관한 곤충학적 소론, 2권",
			cn = "《关于肉虫的昆虫学论文：第2卷》",
		},
	},
	[454337] = {
		readable = "Thimble's Cache",
		model = 5007036,
		text = {
			en = "Thimble's Cache",
			es = "Alijo de Dedal",
			de = "Fingerhuts Vorräte",
			fr = "Cachette de Croquette",
			it = "Cassa di Tessitino",
			pt = "Thimble's Cache",
			ru = "Тайник Наперстика",
			ko = "팀블의 은닉처",
			cn = "Thimble's Cache",
		},
	},
	[454338] = {
		readable = "Entomological Essay on Grubs, Volume 3",
		model = 5007025,
		text = {
			en = "Entomological Essay on Grubs, Volume 3",
			es = "Ensayos etimológicos sobre larvas, volumen 3",
			de = "Entomologische Abhandlung über Maden, Band 3",
			fr = "Essai entomologique sur les vers, volume 3",
			it = "Saggio Entomologico sulle Larve, Volume 3",
			pt = "Ensaio Entomológico sobre Larvas, Volume 3",
			ru = "Энтомологическое эссе о личинках, том 3",
			ko = "땅벌레에 관한 곤충학적 소론, 3권",
			cn = "《关于肉虫的昆虫学论文：第3卷》",
		},
	},
	[454340] = {
		readable = "Thimble's Cache",
		model = 5007036,
		text = {
			en = "Thimble's Cache",
			es = "Thimble's Cache",
			de = "Fingerhuts Vorräte",
			fr = "Cachette de Croquette",
			it = "Cassa di Tessitino",
			pt = "Thimble's Cache",
			ru = "Тайник Наперстика",
			ko = "Thimble's Cache",
			cn = "Thimble's Cache",
		},
	},
	[454342] = {
		readable = "Thimble's Cache",
		model = 5007036,
		text = {
			en = "Thimble's Cache",
			es = "Thimble's Cache",
			de = "Fingerhuts Vorräte",
			fr = "Cachette de Croquette",
			it = "Cassa di Tessitino",
			pt = "Depósito de Aracninha",
			ru = "Тайник Наперстика",
			ko = "팀블의 은닉처",
			cn = "顶针的箱子",
		},
	},
	[454343] = {
		readable = "Ethos of War, Part 1",
		model = 5007027,
		text = {
			en = "Ethos of War, Part 1",
			es = "La ética de la guerra, parte 1",
			de = "Ethos des Krieges, Teil 1",
			fr = "Éthos de la guerre, partie 1",
			it = "Ethos della Guerra, Parte 1",
			pt = "Ethos de Guerra, Parte 1",
			ru = "Законы войны, часть 1",
			ko = "전쟁의 기풍, 1부",
			cn = "《战争理念：第1部》",
		},
	},
	[454344] = {
		readable = "Ethos of War, Part 2",
		model = 5007027,
		text = {
			en = "Ethos of War, Part 2",
			es = "La ética de la guerra, parte 2",
			de = "Ethos des Krieges, Teil 2",
			fr = "Éthos de la guerre, partie 2",
			it = "Ethos della Guerra, Parte 2",
			pt = "Ethos de Guerra, Parte 2",
			ru = "Законы войны, часть 2",
			ko = "전쟁의 기풍, 2부",
			cn = "《战争理念：第2部》",
		},
	},
	[454348] = {
		readable = "Ethos of War, Part 3",
		model = 5007027,
		text = {
			en = "Ethos of War, Part 3",
			es = "La ética de la guerra, parte 3",
			de = "Ethos des Krieges, Teil 3",
			fr = "Éthos de la guerre, partie 3",
			it = "Ethos della Guerra, Parte 3",
			pt = "Ethos de Guerra, Parte 3",
			ru = "Законы войны, часть 3",
			ko = "전쟁의 기풍, 3부",
			cn = "《战争理念：第3部》",
		},
	},
	[454350] = {
		readable = "Ethos of War, Part 4",
		model = 5007027,
		text = {
			en = "Ethos of War, Part 4",
			es = "La ética de la guerra, parte 4",
			de = "Ethos des Krieges, Teil 4",
			fr = "Éthos de la guerre, partie 4",
			it = "Ethos della Guerra, Parte 4",
			pt = "Ethos de Guerra, Parte 4",
			ru = "Законы войны, часть 4",
			ko = "전쟁의 기풍, 4부",
			cn = "《战争理念：第4部》",
		},
	},
	[454404] = {
		readable = "Hathlaz's Plaque",
		model = 199987,
		text = {
			en = "Hathlaz's Plaque",
			es = "Placa de Hathlaz",
			de = "Hathlaz' Plakette",
			fr = "Plaque d’Hathlaz",
			it = "Placca di Hathlaz",
			pt = "Placa de Hathlaz",
			ru = "Табличка Хатлаза",
			ko = "하슬라즈의 명판",
			cn = "哈斯拉兹的铭牌",
		},
	},
	[454405] = {
		readable = "Attwogaz's Plaque",
		model = 199987,
		text = {
			en = "Attwogaz's Plaque",
			es = "Placa de Attwogaz",
			de = "Attwogaz' Plakette",
			fr = "Plaque d’Attwogaz",
			it = "Placca di Attwogaz",
			pt = "Placa de Attwogaz",
			ru = "Табличка Аттвогаза",
			ko = "아토가즈의 명판",
			cn = "阿托加兹的铭牌",
		},
	},
	[454406] = {
		readable = "Krattdaz's Plaque",
		model = 199983,
		text = {
			en = "Krattdaz's Plaque",
			es = "Placa de Krattdaz",
			de = "Krattdaz' Plakette",
			fr = "Plaque de Krattdaz",
			it = "Placca di Krattdaz",
			pt = "Placa de Krattdaz",
			ru = "Табличка Краттдаза",
			ko = "크랏다즈의 명판",
			cn = "克拉特达兹的铭牌",
		},
	},
	[454407] = {
		readable = "Uisgaz's Plaque",
		model = 199983,
		text = {
			en = "Uisgaz's Plaque",
			es = "Placa de Uisgaz",
			de = "Uisgaz' Plakette",
			fr = "Plaque d’Uisgaz",
			it = "Placca di Uisgaz",
			pt = "Placa de Uisgaz",
			ru = "Табличка Юйсгаза",
			ko = "위스가즈의 명판",
			cn = "威斯加兹的铭牌",
		},
	},
	[454408] = {
		readable = "Venedaz's Plaque",
		model = 199987,
		text = {
			en = "Venedaz's Plaque",
			es = "Placa de Venedaz",
			de = "Venedaz' Plakette",
			fr = "Plaque de Venedaz",
			it = "Placca di Venedaz",
			pt = "Placa de Venedaz",
			ru = "Табличка Венедаза",
			ko = "베네다즈의 명판",
			cn = "维尼达兹的铭牌",
		},
	},
	[454412] = {
		readable = "Merunth's Plaque",
		model = 199987,
		text = {
			en = "Merunth's Plaque",
			es = "Placa de Merunth",
			de = "Merunths Plakette",
			fr = "Plaque de Merunth",
			it = "Placca di Merunth",
			pt = "Placa de Merunth",
			ru = "Табличка Мерунф",
			ko = "메룬스의 명판",
			cn = "玫伦兹的铭牌",
		},
	},
	[454414] = {
		readable = "Varerko's Plaque",
		model = 959595,
		text = {
			en = "Varerko's Plaque",
			es = "Placa de Varerko",
			de = "Varerkos Plakette",
			fr = "Plaque de Varerko",
			it = "Placca di Varerko",
			pt = "Placa de Varerko",
			ru = "Табличка Варерко",
			ko = "바렐코의 명판",
			cn = "瓦雷尔科的铭牌",
		},
	},
	[454416] = {
		readable = "Alfritha's Plaque",
		model = 199983,
		text = {
			en = "Alfritha's Plaque",
			es = "Placa de Alfritha",
			de = "Alfrithas Plakette",
			fr = "Plaque d’Alfritha",
			it = "Placca di Alfritha",
			pt = "Placa de Alfrita",
			ru = "Табличка Алвриты",
			ko = "알프리타의 명판",
			cn = "阿弗里莎的铭牌",
		},
	},
	[454417] = {
		readable = "Gundrig's Plaque",
		model = 959595,
		text = {
			en = "Gundrig's Plaque",
			es = "Placa de Gundrig",
			de = "Gundrigs Plakette",
			fr = "Plaque de Gundrig",
			it = "Placca di Gundrig",
			pt = "Placa de Gundriga",
			ru = "Табличка Гундриг",
			ko = "군드리그의 명판",
			cn = "冈德利格的铭牌",
		},
	},
	[454418] = {
		readable = "Sathilga's Plaque",
		model = 199987,
		text = {
			en = "Sathilga's Plaque",
			es = "Placa de Sathilga",
			de = "Sathilgas Plakette",
			fr = "Plaque de Sathilga",
			it = "Placca di Sathilga",
			pt = "Placa de Satilga",
			ru = "Табличка Сатильги",
			ko = "사틸가의 명판",
			cn = "萨希尔加的铭牌",
		},
	},
	[454463] = {
		readable = "Wanted: The Boroughbreaker",
		model = 5409330,
		text = {
			en = "Wanted: The Boroughbreaker",
			es = "Se busca: El Quebrantaburgos",
			de = "Gesucht: der Gemeindebrecher",
			fr = "Avis de recherche : brise-quartier",
			it = "Ricercato: Sfondaborghi",
			pt = "Procura-se: Quebra-burgo",
			ru = "Разыскивается: попиратель",
			ko = "현상 수배: 자치구파괴자",
			cn = "通缉：碎枝者",
		},
	},
	[454797] = {
		readable = "From the Depths They Come",
		model = 5387323,
		text = {
			en = "From the Depths They Come",
			es = "Vienen de las profundidades",
			de = "Sie kommen aus den Tiefen",
			fr = "Des profondeurs ils émergent",
			it = "Dagli Abissi Essi Giungono",
			pt = "Eles Vêm das Profundezas",
			ru = "Они приходят из глубин",
			ko = "심연에서 나타난 자들",
			cn = "《深渊来客》",
		},
	},
	[455038] = {
		readable = "Light's Gambit Playbook",
		model = 5387323,
		text = {
			en = "Light's Gambit Playbook",
			es = "Compendio de Gambito de la Luz",
			de = "\"Schachzug des Lichts\"-Strategien",
			fr = "Règles du Gambit de la Lumière",
			it = "Manuale di Lotta per la Luce",
			pt = "Livro de Jogadas de Gambito da Luz",
			ru = "Правила игры в Гамбит Света",
			ko = "빛의 승부수 안내서",
			cn = "《“圣光奇兵”规则书》",
		},
	},
})
do ObjectDB[objectID] = objectData; end