local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[410529] = {
		readable = "Tuft of Dreamsaber Fur",
		model = 1334477,
		text = {
			en = "Tuft of Dreamsaber Fur",
			es = "Tuft of Dreamsaber Fur",
			de = "Tuft of Dreamsaber Fur",
			fr = "Tuft of Dreamsaber Fur",
			it = "Tuft of Dreamsaber Fur",
			pt = "Tuft of Dreamsaber Fur",
			ru = "Tuft of Dreamsaber Fur",
			ko = "Tuft of Dreamsaber Fur",
			cn = "Tuft of Dreamsaber Fur",
		},
	},
	[410534] = {
		readable = "Molted Faerie Dragon Scales",
		model = 1301126,
		text = {
			en = "Molted Faerie Dragon Scales",
			es = "Molted Faerie Dragon Scales",
			de = "Molted Faerie Dragon Scales",
			fr = "Molted Faerie Dragon Scales",
			it = "Molted Faerie Dragon Scales",
			pt = "Molted Faerie Dragon Scales",
			ru = "Molted Faerie Dragon Scales",
			ko = "Molted Faerie Dragon Scales",
			cn = "Molted Faerie Dragon Scales",
		},
	},
	[410550] = {
		readable = "Dreamtalon Claw",
		model = 202801,
		text = {
			en = "Dreamtalon Claw",
			es = "Dreamtalon Claw",
			de = "Dreamtalon Claw",
			fr = "Dreamtalon Claw",
			it = "Dreamtalon Claw",
			pt = "Dreamtalon Claw",
			ru = "Dreamtalon Claw",
			ko = "Dreamtalon Claw",
			cn = "Dreamtalon Claw",
		},
	},
	[411466] = {
		readable = "Unwaking Echo",
		model = 1349621,
		text = {
			en = "Unwaking Echo",
			es = "Unwaking Echo",
			de = "Unwaking Echo",
			fr = "Unwaking Echo",
			it = "Unwaking Echo",
			pt = "Unwaking Echo",
			ru = "Unwaking Echo",
			ko = "Unwaking Echo",
			cn = "Unwaking Echo",
		},
	},
})
do ObjectDB[objectID] = objectData; end