local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[50935] = {
		readable = "Sack of Corn",
		model = 190015,
		text = {
			en = "Sack of Corn",
			es = "Saco de maíz",
			de = "Sack Korn",
			fr = "Sac de maïs",
			it = "Sack of Corn",
			pt = "Saco de Milho",
			ru = "Мешок кукурузы",
			ko = "옥수수 부대",
			cn = "一袋玉米",
		},
	},
	[50936] = {
		readable = "Sack of Barley",
		model = 197608,
		text = {
			en = "Sack of Barley",
			es = "Saco de cebada",
			de = "Sack Gerste",
			fr = "Sac d'orge",
			it = "Sack of Barley",
			pt = "Saco de Cevada",
			ru = "Мешок ячменя",
			ko = "보리 부대",
			cn = "一袋大麦",
		},
	},
	[50937] = {
		readable = "Sack of Rye",
		model = 190015,
		text = {
			en = "Sack of Rye",
			es = "Saco de centeno",
			de = "Sack Roggen",
			fr = "Sac de seigle",
			it = "Sack of Rye",
			pt = "Saco de Centeio",
			ru = "Мешок ржи",
			ko = "호밀 부대",
			cn = "一袋黑麦",
		},
	},
	[50982] = {
		readable = "The Charred Oak",
		model = 189260,
		text = {
			en = "The Charred Oak",
			es = "El Roble Carbonizado",
			de = "Die verbrannte Eiche",
			fr = "Le chêne carbonisé",
			it = "The Charred Oak",
			pt = "O Carvalho Calcinado",
			ru = "Опаленный дуб",
			ko = "참나무 숯",
			cn = "烧焦的橡木",
		},
	},
})
do ObjectDB[objectID] = objectData; end