local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[112877] = {
		readable = "Talvash's Scrying Bowl",
		model = 201115,
		text = {
			en = "Talvash's Scrying Bowl",
			es = "Cuenco de visión de Talvash",
			de = "Talvashs Wahrsageschale",
			fr = "Coupe de divination de Talvash",
			it = "Talvash's Scrying Bowl",
			pt = "Bacia de Vidência do Didiê",
			ru = "Гадальная чаша Талваша",
			ko = "탈바쉬의 수정점 그릇",
			cn = "塔瓦斯德的占卜之碗",
		},
	},
	[113531] = {
		readable = "Cannon",
		model = 200947,
		text = {
			en = "Cannon",
			es = "Cañón",
			de = "Kanone",
			fr = "Canon",
			it = "Cannon",
			pt = "Canhão",
			ru = "Пушка",
			ko = "대포",
			cn = "火炮",
		},
	},
	[113769] = {
		readable = "Brightly Colored Egg",
		model = 199693,
		text = {
			en = "Brightly Colored Egg",
			es = "Huevo de color vivo",
			de = "Osterei",
			fr = "Oeuf de Pâques",
			it = "Brightly Colored Egg",
			pt = "[Brightly Colored Egg]",
			ru = "Ярко окрашенное яйцо",
			ko = "오색찬란한 알",
			cn = "复活节彩蛋",
		},
	},
	[113770] = {
		readable = "Brightly Colored Egg",
		model = 199695,
		text = {
			en = "Brightly Colored Egg",
			es = "Huevo de color vivo",
			de = "Osterei",
			fr = "Oeuf de Pâques",
			it = "Brightly Colored Egg",
			pt = "[Brightly Colored Egg]",
			ru = "Ярко окрашенное яйцо",
			ko = "오색찬란한 알",
			cn = "复活节彩蛋",
		},
	},
	[113771] = {
		readable = "Brightly Colored Egg",
		model = 199697,
		text = {
			en = "Brightly Colored Egg",
			es = "Huevo de color vivo",
			de = "Osterei",
			fr = "Oeuf de Pâques",
			it = "Brightly Colored Egg",
			pt = "[Brightly Colored Egg]",
			ru = "Ярко окрашенное яйцо",
			ko = "오색찬란한 알",
			cn = "复活节彩蛋",
		},
	},
	[113772] = {
		readable = "Brightly Colored Egg",
		model = 199699,
		text = {
			en = "Brightly Colored Egg",
			es = "Huevo de color vivo",
			de = "Osterei (böse)",
			fr = "Oeuf de Pâques",
			it = "Brightly Colored Egg",
			pt = "[Brightly Colored Egg]",
			ru = "Ярко окрашенное яйцо",
			ko = "[Brightly Colored Egg]",
			cn = "[Brightly Colored Egg]",
		},
	},
})
do ObjectDB[objectID] = objectData; end