local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[410426] = {
		readable = "Half-Filled Dreamless Sleep Potion",
		model = 2833934,
		text = {
			en = "Half-Filled Dreamless Sleep Potion",
			es = "Half-Filled Dreamless Sleep Potion",
			de = "Half-Filled Dreamless Sleep Potion",
			fr = "Half-Filled Dreamless Sleep Potion",
			it = "Half-Filled Dreamless Sleep Potion",
			pt = "Half-Filled Dreamless Sleep Potion",
			ru = "Half-Filled Dreamless Sleep Potion",
			ko = "Half-Filled Dreamless Sleep Potion",
			cn = "Half-Filled Dreamless Sleep Potion",
		},
	},
	[410442] = {
		readable = "Root of the Problem",
		text = {
			en = "Root of the Problem",
			es = "Root of the Problem",
			de = "Root of the Problem",
			fr = "Root of the Problem",
			it = "Root of the Problem",
			pt = "Root of the Problem",
			ru = "Root of the Problem",
			ko = "Root of the Problem",
			cn = "Root of the Problem",
		},
	},
	[410458] = {
		readable = "Insomniotron",
		model = 2367468,
		text = {
			en = "Insomniotron",
			es = "Insomniotron",
			de = "Insomniotron",
			fr = "Insomniotron",
			it = "Insomniotron",
			pt = "Insomniotron",
			ru = "Insomniotron",
			ko = "Insomniotron",
			cn = "Insomniotron",
		},
	},
	[410469] = {
		readable = "Unhatched Battery",
		model = 2736566,
		text = {
			en = "Unhatched Battery",
			es = "Unhatched Battery",
			de = "Unhatched Battery",
			fr = "Unhatched Battery",
			it = "Unhatched Battery",
			pt = "Unhatched Battery",
			ru = "Unhatched Battery",
			ko = "Unhatched Battery",
			cn = "Unhatched Battery",
		},
	},
	[410574] = {
		readable = "Pure Dream Water",
		text = {
			en = "Pure Dream Water",
			es = "Pure Dream Water",
			de = "Pure Dream Water",
			fr = "Pure Dream Water",
			it = "Pure Dream Water",
			pt = "Pure Dream Water",
			ru = "Pure Dream Water",
			ko = "Pure Dream Water",
			cn = "Pure Dream Water",
		},
	},
	[410575] = {
		readable = "Everburning Core",
		model = 4508235,
		text = {
			en = "Everburning Core",
			es = "Everburning Core",
			de = "Everburning Core",
			fr = "Everburning Core",
			it = "Everburning Core",
			pt = "Everburning Core",
			ru = "Everburning Core",
			ko = "Everburning Core",
			cn = "Everburning Core",
		},
	},
	[410582] = {
		readable = "Essence of Dreams",
		text = {
			en = "Essence of Dreams",
			es = "Essence of Dreams",
			de = "Essence of Dreams",
			fr = "Essence of Dreams",
			it = "Essence of Dreams",
			pt = "Essence of Dreams",
			ru = "Essence of Dreams",
			ko = "Essence of Dreams",
			cn = "Essence of Dreams",
		},
	},
	[411168] = {
		readable = "Winnie's Notes on Flora and Fauna",
		model = 4298558,
		text = {
			en = "Winnie's Notes on Flora and Fauna",
			es = "Winnie's Notes on Flora and Fauna",
			de = "Winnie's Notes on Flora and Fauna",
			fr = "Winnie's Notes on Flora and Fauna",
			it = "Winnie's Notes on Flora and Fauna",
			pt = "Winnie's Notes on Flora and Fauna",
			ru = "Winnie's Notes on Flora and Fauna",
			ko = "Winnie's Notes on Flora and Fauna",
			cn = "Winnie's Notes on Flora and Fauna",
		},
	},
	[411169] = {
		readable = "Grove Keeper's Pillar",
		text = {
			en = "Grove Keeper's Pillar",
			es = "Grove Keeper's Pillar",
			de = "Grove Keeper's Pillar",
			fr = "Grove Keeper's Pillar",
			it = "Grove Keeper's Pillar",
			pt = "Grove Keeper's Pillar",
			ru = "Grove Keeper's Pillar",
			ko = "Grove Keeper's Pillar",
			cn = "Grove Keeper's Pillar",
		},
	},
	[411170] = {
		readable = "Primalist Shadowbinding Rune",
		model = 4485591,
		text = {
			en = "Primalist Shadowbinding Rune",
			es = "Primalist Shadowbinding Rune",
			de = "Primalist Shadowbinding Rune",
			fr = "Primalist Shadowbinding Rune",
			it = "Primalist Shadowbinding Rune",
			pt = "Primalist Shadowbinding Rune",
			ru = "Primalist Shadowbinding Rune",
			ko = "Primalist Shadowbinding Rune",
			cn = "Primalist Shadowbinding Rune",
		},
	},
})
do ObjectDB[objectID] = objectData; end