local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[386777] = {
		readable = "Dusty Chest",
		model = 219372,
		text = {
			en = "Dusty Chest",
			es = "Cofre cubierto de polvo",
			de = "Verstaubte Kiste",
			fr = "Coffre poussiéreux",
			it = "[Dusty Chest]",
			pt = "[Dusty Chest]",
			ru = "Пыльный сундук",
			ko = "먼지투성이 상자",
			cn = "尘封的宝箱",
		},
	},
	[404830] = {
		readable = "Dusty Chest",
		model = 196988,
		text = {
			en = "Dusty Chest",
			es = "[Dusty Chest]",
			de = "[Dusty Chest]",
			fr = "Coffre poussiéreux",
			it = "[Dusty Chest]",
			pt = "[Dusty Chest]",
			ru = "[Dusty Chest]",
			ko = "[Dusty Chest]",
			cn = "[Dusty Chest]",
		},
	},
	[405201] = {
		readable = "Shipwreck Cache",
		model = 196989,
		text = {
			en = "Shipwreck Cache",
			es = "[Shipwreck Cache]",
			de = "[Shipwreck Cache]",
			fr = "Cache de l’épave",
			it = "[Shipwreck Cache]",
			pt = "[Shipwreck Cache]",
			ru = "[Shipwreck Cache]",
			ko = "[Shipwreck Cache]",
			cn = "[Shipwreck Cache]",
		},
	},
	[405946] = {
		readable = "Dusty Chest",
		model = 196988,
		text = {
			en = "Dusty Chest",
			es = "[Dusty Chest]",
			de = "[Dusty Chest]",
			fr = "Coffre poussiéreux",
			it = "[Dusty Chest]",
			pt = "[Dusty Chest]",
			ru = "[Dusty Chest]",
			ko = "먼지투성이 상자",
			cn = "[Dusty Chest]",
		},
	},
	[407352] = {
		readable = "Gnarlpine Stash",
		model = 197063,
		text = {
			en = "Gnarlpine Stash",
			es = "[Gnarlpine Stash]",
			de = "Kiste der Knarzklauen",
			fr = "[Gnarlpine Stash]",
			it = "[Gnarlpine Stash]",
			pt = "[Gnarlpine Stash]",
			ru = "Тайник племени Кривой Сосны",
			ko = "[Gnarlpine Stash]",
			cn = "[Gnarlpine Stash]",
		},
	},
})
do ObjectDB[objectID] = objectData; end