local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[423959] = {
		readable = "Faded Supply Chest",
		model = 2123117,
		text = {
			en = "Faded Supply Chest",
			es = "Faded Supply Chest",
			de = "Faded Supply Chest",
			fr = "Coffre de fournitures estompé",
			it = "Faded Supply Chest",
			pt = "Baú de Suprimentos Desvanecido",
			ru = "Faded Supply Chest",
			ko = "Faded Supply Chest",
			cn = "Faded Supply Chest",
		},
	},
	[434926] = {
		readable = "Radiant Remnant",
		model = 5869303,
		text = {
			en = "Radiant Remnant",
			es = "Radiant Remnant",
			de = "Radiant Remnant",
			fr = "Vestige radieux",
			it = "Radiant Remnant",
			pt = "Resquício Radiante",
			ru = "Radiant Remnant",
			ko = "Radiant Remnant",
			cn = "Radiant Remnant",
		},
	},
	[439890] = {
		readable = "Grave Offering Location",
		model = 5546879,
		text = {
			en = "Grave Offering Location",
			es = "[Grave Offering Location]",
			de = "[Grave Offering Location]",
			fr = "[Grave Offering Location]",
			it = "[Grave Offering Location]",
			pt = "[Grave Offering Location]",
			ru = "[Grave Offering Location]",
			ko = "[Grave Offering Location]",
			cn = "[Grave Offering Location]",
		},
	},
	[457062] = {
		readable = "Sky-Captain Lancekat's Curse",
		model = 4323821,
		text = {
			en = "Sky-Captain Lancekat's Curse",
			es = "Sky-Captain Lancekat's Curse",
			de = "Himmelskapitänin Lancekats Fluch",
			fr = "Malédiction du capitaine des cieux Lancekat",
			it = "Sky-Captain Lancekat's Curse",
			pt = "Maldição da Capitã Celeste Lancecata",
			ru = "Проклятие небесного капитана Ланцекат",
			ko = "Sky-Captain Lancekat's Curse",
			cn = "Sky-Captain Lancekat's Curse",
		},
	},
})
do ObjectDB[objectID] = objectData; end