local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[416401] = {
		readable = "Kobyss Spear",
		model = 5204672,
		text = {
			en = "Kobyss Spear",
			es = "Lanza kobismal",
			de = "Speer der Kobyss",
			fr = "Lance kobyss",
			it = "Lancia Kobyss",
			pt = "Lança Kobyss",
			ru = "Копье кобисса",
			ko = "코비스 창",
			cn = "蜃鱼人之矛",
		},
	},
	[422560] = {
		readable = "Maevest's Compass",
		model = 5546879,
		text = {
			en = "Maevest's Compass",
			es = "Brújula de Maevest",
			de = "Maevests Kompass",
			fr = "Boussole de Maevest",
			it = "Bussola di Maevest",
			pt = "Bússola de Mevesta",
			ru = "Компас Мейвест",
			ko = "Maevest's Compass",
			cn = "Maevest's Compass",
		},
	},
	[444028] = {
		readable = "Light-Bathed Lotus",
		model = 5175407,
		text = {
			en = "Light-Bathed Lotus",
			es = "Loto bañado en luz",
			de = "Lichtgebadeter Lotus",
			fr = "Lotus baigné de lumière",
			it = "Loto Bagnato di Luce",
			pt = "Lótus Banhado em Luz",
			ru = "Омытый светом лотос",
			ko = "빛에 물든 연꽃",
			cn = "Light-Bathed Lotus",
		},
	},
	[444029] = {
		readable = "Light-Bathed Lotus",
		model = 4688599,
		text = {
			en = "Light-Bathed Lotus",
			es = "Loto bañado en luz",
			de = "Lichtgebadeter Lotus",
			fr = "Lotus baigné de lumière",
			it = "Loto Bagnato di Luce",
			pt = "Lótus Banhado em Luz",
			ru = "Омытый светом лотос",
			ko = "빛에 물든 연꽃",
			cn = "Light-Bathed Lotus",
		},
	},
	[444030] = {
		readable = "Light-Bathed Lotus",
		model = 5175408,
		text = {
			en = "Light-Bathed Lotus",
			es = "Loto bañado en luz",
			de = "Lichtgebadeter Lotus",
			fr = "Lotus baigné de lumière",
			it = "Loto Bagnato di Luce",
			pt = "Lótus Banhado em Luz",
			ru = "Омытый светом лотос",
			ko = "빛에 물든 연꽃",
			cn = "Light-Bathed Lotus",
		},
	},
	[451538] = {
		readable = "Sludge Pile",
		model = 1255023,
		text = {
			en = "Sludge Pile",
			es = "[Sludge Pile]",
			de = "[Sludge Pile]",
			fr = "[Sludge Pile]",
			it = "[Sludge Pile]",
			pt = "[Sludge Pile]",
			ru = "[Sludge Pile]",
			ko = "[Sludge Pile]",
			cn = "[Sludge Pile]",
		},
	},
})
do ObjectDB[objectID] = objectData; end