local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[415296] = {
		readable = "Repair Kit",
		model = 4252793,
		text = {
			en = "Repair Kit",
			es = "Repair Kit",
			de = "Repair Kit",
			fr = "Trousse de réparation",
			it = "Repair Kit",
			pt = "Repair Kit",
			ru = "Repair Kit",
			ko = "Repair Kit",
			cn = "Repair Kit",
		},
	},
	[455944] = {
		readable = "Earthen Tape Measure",
		model = 5546875,
		text = {
			en = "Earthen Tape Measure",
			es = "Cinta métrica terránea",
			de = "Maßband der Irdenen",
			fr = "Mètre ruban terrestre",
			it = "Metro a Nastro Terrigeno",
			pt = "Earthen Tape Measure",
			ru = "Метр земельников",
			ko = "Earthen Tape Measure",
			cn = "土灵卷尺",
		},
	},
	[455949] = {
		readable = "Arathi Tanning Agent",
		model = 5351166,
		text = {
			en = "Arathi Tanning Agent",
			es = "Arathi Tanning Agent",
			de = "Arathi Tanning Agent",
			fr = "Agent de tannage arathi",
			it = "Arathi Tanning Agent",
			pt = "Arathi Tanning Agent",
			ru = "Аратийское дубильное вещество",
			ko = "Arathi Tanning Agent",
			cn = "Arathi Tanning Agent",
		},
	},
	[455974] = {
		readable = "Jeweler's Delicate Drill",
		model = 5546876,
		text = {
			en = "Jeweler's Delicate Drill",
			es = "Jeweler's Delicate Drill",
			de = "Feiner Bohrer des Juweliers",
			fr = "Jeweler's Delicate Drill",
			it = "Jeweler's Delicate Drill",
			pt = "Jeweler's Delicate Drill",
			ru = "Jeweler's Delicate Drill",
			ko = "Jeweler's Delicate Drill",
			cn = "Jeweler's Delicate Drill",
		},
	},
	[455975] = {
		readable = "Carved Stone File",
		model = 5175545,
		text = {
			en = "Carved Stone File",
			es = "Carved Stone File",
			de = "Gemeißelte Steinakte",
			fr = "Carved Stone File",
			it = "Lima di Pietra Scolpita",
			pt = "Carved Stone File",
			ru = "Carved Stone File",
			ko = "Carved Stone File",
			cn = "Carved Stone File",
		},
	},
	[455976] = {
		readable = "Earthen Gem Pliers",
		model = 5175546,
		text = {
			en = "Earthen Gem Pliers",
			es = "Earthen Gem Pliers",
			de = "Edelsteinzange der Irdenen",
			fr = "Pince à gemmes terrestre",
			it = "Pinze per Gemme Terrigene",
			pt = "Earthen Gem Pliers",
			ru = "Плоскогубцы земельников для самоцветов",
			ko = "Earthen Gem Pliers",
			cn = "Earthen Gem Pliers",
		},
	},
	[455981] = {
		readable = "Informant's Fountain Pen",
		model = 5546880,
		text = {
			en = "Informant's Fountain Pen",
			es = "Informant's Fountain Pen",
			de = "Füllhalter des Informanten",
			fr = "Informant's Fountain Pen",
			it = "Informant's Fountain Pen",
			pt = "Caneta Tinteiro do Informante",
			ru = "Informant's Fountain Pen",
			ko = "Informant's Fountain Pen",
			cn = "Informant's Fountain Pen",
		},
	},
	[456015] = {
		readable = "Ringing Hammer Vise",
		model = 5204877,
		text = {
			en = "Ringing Hammer Vise",
			es = "Ringing Hammer Vise",
			de = "Klemme des schallenden Hammers",
			fr = "Ringing Hammer Vise",
			it = "Ringing Hammer Vise",
			pt = "Torno do Martelo Sonante",
			ru = "Тиски звенящего молота",
			ko = "Ringing Hammer Vise",
			cn = "Ringing Hammer Vise",
		},
	},
	[456016] = {
		readable = "Dornogal Hammer",
		model = 5280302,
		text = {
			en = "Dornogal Hammer",
			es = "Martillo de Dornogal",
			de = "Hammer aus Dornogal",
			fr = "Marteau de Dornogal",
			it = "Martello di Dornogal",
			pt = "Martelo de Dornogal",
			ru = "Дорногальский молот",
			ko = "Dornogal Hammer",
			cn = "Dornogal Hammer",
		},
	},
	[456017] = {
		readable = "Ancient Earthen Anvil",
		model = 5199472,
		text = {
			en = "Ancient Earthen Anvil",
			es = "Ancient Earthen Anvil",
			de = "Uralter Amboss der Irdenen",
			fr = "Enclume terrestre ancienne",
			it = "Ancient Earthen Anvil",
			pt = "Bigorna Terrana Ancestral",
			ru = "Ancient Earthen Anvil",
			ko = "Ancient Earthen Anvil",
			cn = "Ancient Earthen Anvil",
		},
	},
	[456022] = {
		readable = "Engraved Stirring Rod",
		model = 3305391,
		text = {
			en = "Engraved Stirring Rod",
			es = "Engraved Stirring Rod",
			de = "Gravierter Rührstab",
			fr = "Touillette gravée",
			it = "Engraved Stirring Rod",
			pt = "Engraved Stirring Rod",
			ru = "Engraved Stirring Rod",
			ko = "Engraved Stirring Rod",
			cn = "Engraved Stirring Rod",
		},
	},
	[456024] = {
		readable = "Metal Dornogal Frame",
		model = 5203800,
		text = {
			en = "Metal Dornogal Frame",
			es = "Metal Dornogal Frame",
			de = "Metallrahmen aus Dornogal",
			fr = "Cadre de Dornogal en métal",
			it = "Struttura di Metallo di Dornogal",
			pt = "Quadro Metálico de Dornogal",
			ru = "Дорногальская металлическая рамка",
			ko = "Metal Dornogal Frame",
			cn = "Metal Dornogal Frame",
		},
	},
})
do ObjectDB[objectID] = objectData; end