local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[408964] = {
		readable = "Satyr Totem",
		model = 1113720,
		text = {
			en = "Satyr Totem",
			es = "[Satyr Totem]",
			de = "[Satyr Totem]",
			fr = "[Satyr Totem]",
			it = "[Satyr Totem]",
			pt = "[Satyr Totem]",
			ru = "[Satyr Totem]",
			ko = "[Satyr Totem]",
			cn = "[Satyr Totem]",
		},
	},
	[415303] = {
		readable = "Magically-Sealed Parcel",
		model = 903887,
		text = {
			en = "Magically-Sealed Parcel",
			es = "[Magically-Sealed Parcel]",
			de = "[Magically-Sealed Parcel]",
			fr = "[Magically-Sealed Parcel]",
			it = "[Magically-Sealed Parcel]",
			pt = "[Magically-Sealed Parcel]",
			ru = "[Magically-Sealed Parcel]",
			ko = "[Magically-Sealed Parcel]",
			cn = "[Magically-Sealed Parcel]",
		},
	},
	[420019] = {
		readable = "Artificing Tools",
		model = 875382,
		text = {
			en = "Artificing Tools",
			es = "[Artificing Tools]",
			de = "[Artificing Tools]",
			fr = "[Artificing Tools]",
			it = "[Artificing Tools]",
			pt = "[Artificing Tools]",
			ru = "[Artificing Tools]",
			ko = "[Artificing Tools]",
			cn = "[Artificing Tools]",
		},
	},
	[420040] = {
		readable = "Artificing Tools",
		model = 877007,
		text = {
			en = "Artificing Tools",
			es = "[Artificing Tools]",
			de = "[Artificing Tools]",
			fr = "[Artificing Tools]",
			it = "[Artificing Tools]",
			pt = "[Artificing Tools]",
			ru = "[Artificing Tools]",
			ko = "[Artificing Tools]",
			cn = "[Artificing Tools]",
		},
	},
})
do ObjectDB[objectID] = objectData; end