local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[408060] = {
		readable = "The First Clue",
		model = 4324473,
		text = {
			en = "The First Clue",
			es = "[The First Clue]",
			de = "[The First Clue]",
			fr = "[The First Clue]",
			it = "[The First Clue]",
			pt = "[The First Clue]",
			ru = "[The First Clue]",
			ko = "[The First Clue]",
			cn = "[The First Clue]",
		},
	},
	[408076] = {
		readable = "The Second Clue",
		model = 4324473,
		text = {
			en = "The Second Clue",
			es = "[The Second Clue]",
			de = "[The Second Clue]",
			fr = "[The Second Clue]",
			it = "[The Second Clue]",
			pt = "[The Second Clue]",
			ru = "[The Second Clue]",
			ko = "[The Second Clue]",
			cn = "[The Second Clue]",
		},
	},
	[408079] = {
		readable = "The Third Clue",
		model = 4324473,
		text = {
			en = "The Third Clue",
			es = "[The Third Clue]",
			de = "[The Third Clue]",
			fr = "[The Third Clue]",
			it = "[The Third Clue]",
			pt = "[The Third Clue]",
			ru = "[The Third Clue]",
			ko = "[The Third Clue]",
			cn = "[The Third Clue]",
		},
	},
	[408080] = {
		readable = "A Partial Fourth Clue",
		model = 4324473,
		text = {
			en = "A Partial Fourth Clue",
			es = "[A Partial Fourth Clue]",
			de = "[A Partial Fourth Clue]",
			fr = "[A Partial Fourth Clue]",
			it = "[A Partial Fourth Clue]",
			pt = "[A Partial Fourth Clue]",
			ru = "[A Partial Fourth Clue]",
			ko = "[A Partial Fourth Clue]",
			cn = "[A Partial Fourth Clue]",
		},
	},
	[408081] = {
		readable = "A Partial Fourth Clue",
		model = 4324473,
		text = {
			en = "A Partial Fourth Clue",
			es = "[A Partial Fourth Clue]",
			de = "[A Partial Fourth Clue]",
			fr = "[A Partial Fourth Clue]",
			it = "[A Partial Fourth Clue]",
			pt = "[A Partial Fourth Clue]",
			ru = "[A Partial Fourth Clue]",
			ko = "[A Partial Fourth Clue]",
			cn = "[A Partial Fourth Clue]",
		},
	},
	[408082] = {
		readable = "A Partial Fourth Clue",
		model = 4324473,
		text = {
			en = "A Partial Fourth Clue",
			es = "[A Partial Fourth Clue]",
			de = "[A Partial Fourth Clue]",
			fr = "[A Partial Fourth Clue]",
			it = "[A Partial Fourth Clue]",
			pt = "[A Partial Fourth Clue]",
			ru = "[A Partial Fourth Clue]",
			ko = "[A Partial Fourth Clue]",
			cn = "[A Partial Fourth Clue]",
		},
	},
	[408083] = {
		readable = "A Partial Fourth Clue",
		model = 4324473,
		text = {
			en = "A Partial Fourth Clue",
			es = "[A Partial Fourth Clue]",
			de = "[A Partial Fourth Clue]",
			fr = "[A Partial Fourth Clue]",
			it = "[A Partial Fourth Clue]",
			pt = "[A Partial Fourth Clue]",
			ru = "[A Partial Fourth Clue]",
			ko = "[A Partial Fourth Clue]",
			cn = "[A Partial Fourth Clue]",
		},
	},
})
do ObjectDB[objectID] = objectData; end