local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[385961] = {
		readable = "Rumble Coin Bag",
		model = 3936818,
		text = {
			en = "Rumble Coin Bag",
			es = "[Rumble Coin Bag]",
			de = "Rumble-Münzenbeutel",
			fr = "[Rumble Coin Bag]",
			it = "[Rumble Coin Bag]",
			pt = "[Rumble Coin Bag]",
			ru = "Мешочек с монетами Rumble",
			ko = "[Rumble Coin Bag]",
			cn = "魔兽游戏币袋",
		},
	},
	[386138] = {
		readable = "Rumble Coin Bag",
		model = 3936818,
		text = {
			en = "Rumble Coin Bag",
			es = "[Rumble Coin Bag]",
			de = "Rumble-Münzenbeutel",
			fr = "[Rumble Coin Bag]",
			it = "[Rumble Coin Bag]",
			pt = "[Rumble Coin Bag]",
			ru = "Мешочек с монетами Rumble",
			ko = "[Rumble Coin Bag]",
			cn = "魔兽游戏币袋",
		},
	},
	[386139] = {
		readable = "Rumble Coin Bag",
		model = 3936818,
		text = {
			en = "Rumble Coin Bag",
			es = "[Rumble Coin Bag]",
			de = "Rumble-Münzenbeutel",
			fr = "[Rumble Coin Bag]",
			it = "[Rumble Coin Bag]",
			pt = "[Rumble Coin Bag]",
			ru = "Мешочек с монетами Rumble",
			ko = "[Rumble Coin Bag]",
			cn = "魔兽游戏币袋",
		},
	},
	[387695] = {
		readable = "Rumble Coin Bag",
		model = 3936818,
		text = {
			en = "Rumble Coin Bag",
			es = "Bolsa de monedas de Warcraft Rumble",
			de = "Rumble-Münzenbeutel",
			fr = "Sac de pièces Rumble",
			it = "[Rumble Coin Bag]",
			pt = "Bolsa de Moedas de Rumble",
			ru = "Мешочек с монетами Rumble",
			ko = "[Rumble Coin Bag]",
			cn = "魔兽游戏币袋",
		},
	},
	[387697] = {
		readable = "Rumble Coin Bag",
		model = 3936818,
		text = {
			en = "Rumble Coin Bag",
			es = "Bolsa de monedas de Warcraft Rumble",
			de = "Rumble-Münzenbeutel",
			fr = "Sac de pièces Rumble",
			it = "Borsa di Monete di Rumble",
			pt = "Bolsa de Moedas de Rumble",
			ru = "Мешочек с монетами Rumble",
			ko = "[Rumble Coin Bag]",
			cn = "魔兽游戏币袋",
		},
	},
	[387718] = {
		readable = "Rumble Foil Bag",
		model = 4070769,
		text = {
			en = "Rumble Foil Bag",
			es = "Caja de brillos de Warcraft Rumble",
			de = "Rumble-Folientasche",
			fr = "Sac de Rumble métallisés",
			it = "Borsa di Fogli di Rumble",
			pt = "Bolsa de Metalizados de Rumble",
			ru = "Мешочек с оберткой Rumble",
			ko = "[Rumble Foil Bag]",
			cn = "魔兽游戏箔纸袋",
		},
	},
	[387720] = {
		readable = "Rumble Foil Bag",
		model = 4070769,
		text = {
			en = "Rumble Foil Bag",
			es = "[Rumble Foil Bag]",
			de = "Rumble-Folientasche",
			fr = "[Rumble Foil Bag]",
			it = "[Rumble Foil Bag]",
			pt = "[Rumble Foil Bag]",
			ru = "Мешочек с оберткой Rumble",
			ko = "[Rumble Foil Bag]",
			cn = "魔兽游戏箔纸袋",
		},
	},
	[387721] = {
		readable = "Rumble Foil Bag",
		model = 4070769,
		text = {
			en = "Rumble Foil Bag",
			es = "[Rumble Foil Bag]",
			de = "Rumble-Folientasche",
			fr = "[Rumble Foil Bag]",
			it = "[Rumble Foil Bag]",
			pt = "[Rumble Foil Bag]",
			ru = "Мешочек с оберткой Rumble",
			ko = "[Rumble Foil Bag]",
			cn = "魔兽游戏箔纸袋",
		},
	},
	[387722] = {
		readable = "Rumble Foil Bag",
		model = 4070769,
		text = {
			en = "Rumble Foil Bag",
			es = "[Rumble Foil Bag]",
			de = "Rumble-Folientasche",
			fr = "[Rumble Foil Bag]",
			it = "[Rumble Foil Bag]",
			pt = "[Rumble Foil Bag]",
			ru = "Мешочек с оберткой Rumble",
			ko = "[Rumble Foil Bag]",
			cn = "魔兽游戏箔纸袋",
		},
	},
	[392031] = {
		readable = "Rumble Foil Bag",
		model = 4070769,
		text = {
			en = "Rumble Foil Bag",
			es = "[Rumble Foil Bag]",
			de = "Rumble-Folientasche",
			fr = "[Rumble Foil Bag]",
			it = "[Rumble Foil Bag]",
			pt = "[Rumble Foil Bag]",
			ru = "Мешочек с оберткой Rumble",
			ko = "[Rumble Foil Bag]",
			cn = "魔兽游戏箔纸袋",
		},
	},
	[392032] = {
		readable = "Rumble Foil Bag",
		model = 4070769,
		text = {
			en = "Rumble Foil Bag",
			es = "[Rumble Foil Bag]",
			de = "Rumble-Folientasche",
			fr = "[Rumble Foil Bag]",
			it = "[Rumble Foil Bag]",
			pt = "[Rumble Foil Bag]",
			ru = "Мешочек с оберткой Rumble",
			ko = "[Rumble Foil Bag]",
			cn = "魔兽游戏箔纸袋",
		},
	},
	[405584] = {
		readable = "Rumble Foil Bag",
		model = 4070769,
		text = {
			en = "Rumble Foil Bag",
			es = "Bolsa de brillos de Rumble",
			de = "Rumble-Folientasche",
			fr = "Sac de Rumble métallisés",
			it = "[Rumble Foil Bag]",
			pt = "Bolsa de Metalizados de Rumble",
			ru = "Мешочек с оберткой Rumble",
			ko = "[Rumble Foil Bag]",
			cn = "魔兽游戏箔纸袋",
		},
	},
	[405585] = {
		readable = "Rumble Foil Bag",
		model = 4070769,
		text = {
			en = "Rumble Foil Bag",
			es = "[Rumble Foil Bag]",
			de = "Rumble-Folientasche",
			fr = "[Rumble Foil Bag]",
			it = "[Rumble Foil Bag]",
			pt = "[Rumble Foil Bag]",
			ru = "Мешочек с оберткой Rumble",
			ko = "[Rumble Foil Bag]",
			cn = "魔兽游戏箔纸袋",
		},
	},
	[405586] = {
		readable = "Rumble Foil Bag",
		model = 4070769,
		text = {
			en = "Rumble Foil Bag",
			es = "[Rumble Foil Bag]",
			de = "Rumble-Folientasche",
			fr = "[Rumble Foil Bag]",
			it = "[Rumble Foil Bag]",
			pt = "[Rumble Foil Bag]",
			ru = "Мешочек с оберткой Rumble",
			ko = "[Rumble Foil Bag]",
			cn = "魔兽游戏箔纸袋",
		},
	},
	[405587] = {
		readable = "Rumble Foil Bag",
		model = 4070769,
		text = {
			en = "Rumble Foil Bag",
			es = "[Rumble Foil Bag]",
			de = "Rumble-Folientasche",
			fr = "[Rumble Foil Bag]",
			it = "[Rumble Foil Bag]",
			pt = "[Rumble Foil Bag]",
			ru = "Мешочек с оберткой Rumble",
			ko = "[Rumble Foil Bag]",
			cn = "魔兽游戏箔纸袋",
		},
	},
})
do ObjectDB[objectID] = objectData; end