local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[416310] = {
		readable = "Kobyss Chest",
		model = 5204694,
		text = {
			en = "Kobyss Chest",
			es = "Kobyss Chest",
			de = "Truhe der Kobyss",
			fr = "Coffre kobyss",
			it = "Kobyss Chest",
			pt = "Baú Kobyss",
			ru = "Kobyss Chest",
			ko = "Kobyss Chest",
			cn = "Kobyss Chest",
		},
	},
	[423958] = {
		readable = "Arathi Chest",
		model = 5154231,
		text = {
			en = "Arathi Chest",
			es = "Arathi Chest",
			de = "Arathikiste",
			fr = "Arathi Chest",
			it = "Arathi Chest",
			pt = "Baú Arathi",
			ru = "Arathi Chest",
			ko = "Arathi Chest",
			cn = "Arathi Chest",
		},
	},
	[423977] = {
		readable = "Kobyss Chest",
		model = 5204694,
		text = {
			en = "Kobyss Chest",
			es = "Kobyss Chest",
			de = "Truhe der Kobyss",
			fr = "Coffre kobyss",
			it = "Kobyss Chest",
			pt = "Baú Kobyss",
			ru = "Kobyss Chest",
			ko = "Kobyss Chest",
			cn = "Kobyss Chest",
		},
	},
	[423978] = {
		readable = "Kobyss Chest",
		model = 5204694,
		text = {
			en = "Kobyss Chest",
			es = "Kobyss Chest",
			de = "Truhe der Kobyss",
			fr = "Coffre kobyss",
			it = "Kobyss Chest",
			pt = "Baú Kobyss",
			ru = "Сундук кобиссов",
			ko = "Kobyss Chest",
			cn = "Kobyss Chest",
		},
	},
	[423979] = {
		readable = "Kobyss Chest",
		model = 5204694,
		text = {
			en = "Kobyss Chest",
			es = "Kobyss Chest",
			de = "Truhe der Kobyss",
			fr = "Coffre kobyss",
			it = "Kobyss Chest",
			pt = "Baú Kobyss",
			ru = "Сундук кобиссов",
			ko = "Kobyss Chest",
			cn = "Kobyss Chest",
		},
	},
	[424343] = {
		readable = "Medical Supplies",
		model = 5048188,
		text = {
			en = "Medical Supplies",
			es = "Medical Supplies",
			de = "Medizinische Vorräte",
			fr = "Fournitures médicales",
			it = "Medical Supplies",
			pt = "Suprimentos Médicos",
			ru = "Медикаменты",
			ko = "Medical Supplies",
			cn = "Medical Supplies",
		},
	},
	[437025] = {
		readable = "Sludge Pile",
		model = 1255023,
		text = {
			en = "Sludge Pile",
			es = "[Sludge Pile]",
			de = "[Sludge Pile]",
			fr = "[Sludge Pile]",
			it = "[Sludge Pile]",
			pt = "[Sludge Pile]",
			ru = "[Sludge Pile]",
			ko = "[Sludge Pile]",
			cn = "[Sludge Pile]",
		},
	},
})
do ObjectDB[objectID] = objectData; end