local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[404337] = {
		readable = "Bar Tab Barrel",
		model = 526102,
		text = {
			en = "Bar Tab Barrel",
			es = "Barril de la cuenta",
			de = "Schankfass",
			fr = "Tonneau d’ardoise de bar",
			it = "Barilotto",
			pt = "Barril na Conta",
			ru = "Полная бочка",
			ko = "술집 외상 통",
			cn = "熟客酒桶",
			tw = "Bar Tab Barrel",
		},
	},
	[404981] = {
		readable = "Bar Tab Barrel",
		model = 526102,
		text = {
			en = "Bar Tab Barrel",
			es = "Barril de la cuenta",
			de = "Schankfass",
			fr = "Tonneau d’ardoise de bar",
			it = "Barilotto",
			pt = "Barril na Conta",
			ru = "Полная бочка",
			ko = "술집 외상 통",
			cn = "熟客酒桶",
			tw = "Bar Tab Barrel",
		},
	},
	[404982] = {
		readable = "Bar Tab Barrel",
		model = 526102,
		text = {
			en = "Bar Tab Barrel",
			es = "Barril de la cuenta",
			de = "Schankfass",
			fr = "Tonneau d’ardoise de bar",
			it = "Barilotto",
			pt = "Barril na Conta",
			ru = "Полная бочка",
			ko = "술집 외상 통",
			cn = "熟客酒桶",
			tw = "Bar Tab Barrel",
		},
	},
	[404987] = {
		readable = "Bar Tab Barrel",
		model = 526102,
		text = {
			en = "Bar Tab Barrel",
			es = "Barril de la cuenta",
			de = "Schankfass",
			fr = "Tonneau d’ardoise de bar",
			it = "Barilotto",
			pt = "Barril na Conta",
			ru = "Полная бочка",
			ko = "술집 외상 통",
			cn = "熟客酒桶",
			tw = "Bar Tab Barrel",
		},
	},
	[404992] = {
		readable = "Bar Tab Barrel",
		model = 526102,
		text = {
			en = "Bar Tab Barrel",
			es = "Barril de la cuenta",
			de = "Schankfass",
			fr = "Tonneau d’ardoise de bar",
			it = "Barilotto",
			pt = "Barril na Conta",
			ru = "Полная бочка",
			ko = "술집 외상 통",
			cn = "熟客酒桶",
			tw = "Bar Tab Barrel",
		},
	},
	[405009] = {
		readable = "Bar Tab Barrel",
		model = 526102,
		text = {
			en = "Bar Tab Barrel",
			es = "Barril de la cuenta",
			de = "Schankfass",
			fr = "Tonneau d’ardoise de bar",
			it = "Barilotto",
			pt = "Barril na Conta",
			ru = "Полная бочка",
			ko = "술집 외상 통",
			cn = "Bar Tab Barrel",
			tw = "Bar Tab Barrel",
		},
	},
	[405012] = {
		readable = "Bar Tab Barrel",
		model = 526102,
		text = {
			en = "Bar Tab Barrel",
			es = "Barril de la cuenta",
			de = "Schankfass",
			fr = "Tonneau d’ardoise de bar",
			it = "Barilotto",
			pt = "Barril na Conta",
			ru = "Полная бочка",
			ko = "술집 외상 통",
			cn = "熟客酒桶",
			tw = "Bar Tab Barrel",
		},
	},
	[407186] = {
		readable = "Bar Tab Barrel",
		model = 526102,
		text = {
			en = "Bar Tab Barrel",
			es = "Barril de la cuenta",
			de = "Schankfass",
			fr = "Tonneau d’ardoise de bar",
			it = "Barilotto",
			pt = "Barril na Conta",
			ru = "Полная бочка",
			ko = "술집 외상 통",
			cn = "熟客酒桶",
			tw = "Bar Tab Barrel",
		},
	},
	[407192] = {
		readable = "Bar Tab Barrel",
		model = 526102,
		text = {
			en = "Bar Tab Barrel",
			es = "Barril de la cuenta",
			de = "Schankfass",
			fr = "Tonneau d’ardoise de bar",
			it = "Barilotto",
			pt = "Barril na Conta",
			ru = "Полная бочка",
			ko = "술집 외상 통",
			cn = "Bar Tab Barrel",
			tw = "Bar Tab Barrel",
		},
	},
	[407199] = {
		readable = "Bar Tab Barrel",
		model = 526102,
		text = {
			en = "Bar Tab Barrel",
			es = "Barril de la cuenta",
			de = "Schankfass",
			fr = "Tonneau d’ardoise de bar",
			it = "Barilotto",
			pt = "Barril na Conta",
			ru = "Полная бочка",
			ko = "술집 외상 통",
			cn = "Bar Tab Barrel",
			tw = "Bar Tab Barrel",
		},
	},
	[407201] = {
		readable = "Bar Tab Barrel",
		model = 526102,
		text = {
			en = "Bar Tab Barrel",
			es = "Barril de la cuenta",
			de = "Schankfass",
			fr = "Tonneau d’ardoise de bar",
			it = "Barilotto",
			pt = "Barril na Conta",
			ru = "Полная бочка",
			ko = "술집 외상 통",
			cn = "Bar Tab Barrel",
			tw = "Bar Tab Barrel",
		},
	},
})
do ObjectDB[objectID] = objectData; end