local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[284408] = {
		readable = "Treasure Chest",
		model = 1777743,
		text = {
			en = "Treasure Chest",
			es = "Arqueta",
			de = "Schatztruhe",
			fr = "Coffre au trésor",
			it = "Cassa del Tesoro",
			pt = "Baú do Tesouro",
			ru = "Сундук с сокровищами",
			ko = "보물 상자",
			cn = "宝箱",
		},
	},
	[284409] = {
		readable = "Treasure Chest",
		model = 1777743,
		text = {
			en = "Treasure Chest",
			es = "Arqueta",
			de = "Schatztruhe",
			fr = "Coffre au trésor",
			it = "Cassa del Tesoro",
			pt = "Baú do Tesouro",
			ru = "Сундук с сокровищами",
			ko = "보물 상자",
			cn = "宝箱",
		},
	},
	[284410] = {
		readable = "Treasure Chest",
		model = 1712385,
		text = {
			en = "Treasure Chest",
			es = "Arqueta",
			de = "Schatztruhe",
			fr = "Coffre au trésor",
			it = "Cassa del Tesoro",
			pt = "Baú do Tesouro",
			ru = "Сундук с сокровищами",
			ko = "보물 상자",
			cn = "宝箱",
		},
	},
	[284411] = {
		readable = "Treasure Chest",
		model = 1712385,
		text = {
			en = "Treasure Chest",
			es = "Arqueta",
			de = "Schatztruhe",
			fr = "Coffre au trésor",
			it = "Cassa del Tesoro",
			pt = "Baú do Tesouro",
			ru = "Сундук с сокровищами",
			ko = "보물 상자",
			cn = "宝箱",
		},
	},
	[284412] = {
		readable = "Treasure Chest",
		model = 1706189,
		text = {
			en = "Treasure Chest",
			es = "Arqueta",
			de = "Schatztruhe",
			fr = "Coffre au trésor",
			it = "Cassa del Tesoro",
			pt = "Baú do Tesouro",
			ru = "Сундук с сокровищами",
			ko = "보물 상자",
			cn = "宝箱",
		},
	},
	[284413] = {
		readable = "Treasure Chest",
		model = 1712385,
		text = {
			en = "Treasure Chest",
			es = "Arqueta",
			de = "Schatztruhe",
			fr = "Coffre au trésor",
			it = "Cassa del Tesoro",
			pt = "Baú do Tesouro",
			ru = "Сундук с сокровищами",
			ko = "보물 상자",
			cn = "宝箱",
		},
	},
	[284414] = {
		readable = "Treasure Chest",
		model = 1806318,
		text = {
			en = "Treasure Chest",
			es = "Arqueta",
			de = "Schatztruhe",
			fr = "Coffre au trésor",
			it = "Cassa del Tesoro",
			pt = "Baú do Tesouro",
			ru = "Сундук с сокровищами",
			ko = "보물 상자",
			cn = "宝箱",
		},
	},
	[284415] = {
		readable = "Treasure Chest",
		model = 1777743,
		text = {
			en = "Treasure Chest",
			es = "Arqueta",
			de = "Schatztruhe",
			fr = "Coffre au trésor",
			it = "Cassa del Tesoro",
			pt = "Baú do Tesouro",
			ru = "Сундук с сокровищами",
			ko = "보물 상자",
			cn = "宝箱",
		},
	},
	[284416] = {
		readable = "Treasure Chest",
		model = 1712385,
		text = {
			en = "Treasure Chest",
			es = "Arqueta",
			de = "Schatztruhe",
			fr = "Coffre au trésor",
			it = "Cassa del Tesoro",
			pt = "Baú do Tesouro",
			ru = "Сундук с сокровищами",
			ko = "보물 상자",
			cn = "宝箱",
		},
	},
	[284417] = {
		readable = "Treasure Chest",
		model = 1712385,
		text = {
			en = "Treasure Chest",
			es = "Arqueta",
			de = "Schatztruhe",
			fr = "Coffre au trésor",
			it = "Cassa del Tesoro",
			pt = "Baú do Tesouro",
			ru = "Сундук с сокровищами",
			ko = "보물 상자",
			cn = "[Treasure Chest]",
		},
	},
	[284418] = {
		readable = "Treasure Chest",
		model = 1777743,
		text = {
			en = "Treasure Chest",
			es = "Arqueta",
			de = "Schatztruhe",
			fr = "Coffre au trésor",
			it = "Cassa del Tesoro",
			pt = "Baú do Tesouro",
			ru = "Сундук с сокровищами",
			ko = "보물 상자",
			cn = "宝箱",
		},
	},
	[284419] = {
		readable = "Treasure Chest",
		model = 1777743,
		text = {
			en = "Treasure Chest",
			es = "Arqueta",
			de = "Schatztruhe",
			fr = "Coffre au trésor",
			it = "Cassa del Tesoro",
			pt = "Baú do Tesouro",
			ru = "Сундук с сокровищами",
			ko = "보물 상자",
			cn = "宝箱",
		},
	},
	[284420] = {
		readable = "Treasure Chest",
		model = 1777743,
		text = {
			en = "Treasure Chest",
			es = "Arqueta",
			de = "Schatztruhe",
			fr = "Coffre au trésor",
			it = "Cassa del Tesoro",
			pt = "Baú do Tesouro",
			ru = "Сундук с сокровищами",
			ko = "보물 상자",
			cn = "宝箱",
		},
	},
	[284421] = {
		readable = "Treasure Chest",
		model = 1777743,
		text = {
			en = "Treasure Chest",
			es = "Arqueta",
			de = "Schatztruhe",
			fr = "Coffre au trésor",
			it = "Cassa del Tesoro",
			pt = "Baú do Tesouro",
			ru = "Сундук с сокровищами",
			ko = "보물 상자",
			cn = "宝箱",
		},
	},
	[284422] = {
		readable = "Crate of Azerite",
		model = 1018096,
		text = {
			en = "Crate of Azerite",
			es = "Cajón de azerita",
			de = "Kiste mit Azerit",
			fr = "Caisse d’azérite",
			it = "Cassa d'Azerite",
			pt = "Caixote de Azerita",
			ru = "Ящик с азеритом",
			ko = "아제라이트가 든 궤짝",
			cn = "一箱艾泽里特",
		},
	},
	[284423] = {
		readable = "Glowing Seed",
		model = 1056771,
		text = {
			en = "Glowing Seed",
			es = "Semilla resplandeciente",
			de = "Leuchtender Samen",
			fr = "Graine luminescente",
			it = "Seme Luminoso",
			pt = "Semente Chamejante",
			ru = "Сияющее семя",
			ko = "빛나는 씨앗",
			cn = "发光的种子",
		},
	},
	[284424] = {
		readable = "Giant Flower",
		model = 436511,
		text = {
			en = "Giant Flower",
			es = "Flor gigante",
			de = "Riesenblume",
			fr = "Fleur gigantesque",
			it = "Fiore Gigante",
			pt = "Flor Gigante",
			ru = "Гигантский цветок",
			ko = "거대한 꽃",
			cn = "巨型花朵",
		},
	},
	[284427] = {
		readable = "Heavy Crate",
		model = 1029607,
		text = {
			en = "Heavy Crate",
			es = "Cajón pesado",
			de = "Schwere Kiste",
			fr = "Caisse lourde",
			it = "Cassa Pesante",
			pt = "Caixote Pesado",
			ru = "Тяжелый ящик",
			ko = "[Heavy Crate]",
			cn = "沉重的箱子",
		},
	},
	[284428] = {
		readable = "Bright Lantern",
		model = 1379251,
		text = {
			en = "Bright Lantern",
			es = "Farol brillante",
			de = "Helle Laterne",
			fr = "Lanterne brillante",
			it = "Lanterna Luminosa",
			pt = "Lanterna Reluzente",
			ru = "Яркий фонарь",
			ko = "밝은 등불",
			cn = "明亮的灯笼",
		},
	},
	[284429] = {
		readable = "Animal Trap",
		model = 1576320,
		text = {
			en = "Animal Trap",
			es = "Cepo para animales",
			de = "Tierfalle",
			fr = "Piège à animaux",
			it = "Trappola per Animali",
			pt = "Armadilha de Animal",
			ru = "Капкан зверолова",
			ko = "동물용 덫",
			cn = "动物陷阱",
		},
	},
	[284430] = {
		readable = "Portal to Drustvar",
		model = 166523,
		text = {
			en = "Portal to Drustvar",
			es = "[Portal to Drustvar]",
			de = "[Portal to Drustvar]",
			fr = "[Portal to Drustvar]",
			it = "[Portal to Drustvar]",
			pt = "[Portal to Drustvar]",
			ru = "[Portal to Drustvar]",
			ko = "[Portal to Drustvar]",
			cn = "[Portal to Drustvar]",
		},
	},
	[284431] = {
		readable = "Portal to Zuldazar",
		model = 2123281,
		text = {
			en = "Portal to Zuldazar",
			es = "Portal a Zuldazar",
			de = "Portal nach Zuldazar",
			fr = "Portail vers Zuldazar",
			it = "Portale per Zuldazar",
			pt = "Portal para Zuldazar",
			ru = "Портал в Зулдазар",
			ko = "줄다자르로 통하는 차원문",
			cn = "通往祖达萨的传送门",
		},
	},
	[284451] = {
		readable = "Pirate Grog",
		model = 1852964,
		text = {
			en = "Pirate Grog",
			es = "Grog de pirata",
			de = "Piratengrog",
			fr = "Grog pirate",
			it = "Grog dei Pirati",
			pt = "Grogue Pirata",
			ru = "Пиратский грог",
			ko = "해적 그로그주",
			cn = "海盗烈酒",
		},
	},
	[284452] = {
		readable = "Cannon",
		model = 653241,
		text = {
			en = "Cannon",
			es = "Cañón",
			de = "Kanone",
			fr = "Canon",
			it = "Cannone",
			pt = "Canhão",
			ru = "Пушка",
			ko = "대포",
			cn = "火炮",
		},
	},
	[284456] = {
		readable = "Incense",
		model = 974438,
		text = {
			en = "Incense",
			es = "Incienso",
			de = "Räucherwerk",
			fr = "Encens",
			it = "Incenso",
			pt = "Incenso",
			ru = "Благовония",
			ko = "향",
			cn = "熏香",
		},
	},
	[284461] = {
		readable = "Outlaw Cannon",
		model = 1659536,
		text = {
			en = "Outlaw Cannon",
			es = "Cañón de forajido",
			de = "Gesetzlosenkanone",
			fr = "Canon de hors-la-loi",
			it = "Cannone dei Fuorilegge",
			pt = "Canhão do Fora da Lei",
			ru = "Разбойничья пушка",
			ko = "무법자 대포",
			cn = "狂徒火炮",
		},
	},
	[284468] = {
		readable = "7th Legion Supply Crate",
		model = 950767,
		text = {
			en = "7th Legion Supply Crate",
			es = "Cajón de suministros de la Séptima Legión",
			de = "Vorratskiste der 7. Legion",
			fr = "Caisse de fournitures de la 7e Légion",
			it = "Cassa di Rifornimenti della VII Legione",
			pt = "Caixote de Suprimentos da 7ª Legião",
			ru = "Ящик с припасами 7-го легиона",
			ko = "7군단 보급품 상자",
			cn = "第七军团补给箱",
		},
	},
	[284469] = {
		readable = "Small Treasure Chest",
		model = 2120294,
		text = {
			en = "Small Treasure Chest",
			es = "Arqueta pequeña",
			de = "Kleine Schatztruhe",
			fr = "Petit coffre au trésor",
			it = "Cassa del Tesoro Piccola",
			pt = "Baú do Tesouro Pequeno",
			ru = "Маленький сундук с сокровищами",
			ko = "작은 보물 상자",
			cn = "小宝箱",
		},
	},
	[284471] = {
		readable = "Guntha's Peace Offering",
		model = 1608206,
		text = {
			en = "Guntha's Peace Offering",
			es = "Ofrenda de paz de Guntha",
			de = "Gunthas Friedensangebot",
			fr = "Offrande de paix de Guntha",
			it = "Offerta di Pace di Guntha",
			pt = "Oferta de Paz do Guntha",
			ru = "Мирное подношение Гунты",
			ko = "군타의 평화 공물",
			cn = "古恩萨的议和礼物",
		},
	},
	[284473] = {
		readable = "Plundered Supplies",
		model = 446677,
		text = {
			en = "Plundered Supplies",
			es = "Suministros expoliados",
			de = "Geplünderte Vorräte",
			fr = "Fournitures pillées",
			it = "Rifornimenti Saccheggiati",
			pt = "Suprimentos Roubados",
			ru = "Награбленные припасы",
			ko = "약탈당한 보급품",
			cn = "抢来的补给",
		},
	},
	[284504] = {
		readable = "Totem of Ruumbo",
		model = 194719,
		text = {
			en = "Totem of Ruumbo",
			es = "[Totem of Ruumbo]",
			de = "[Totem of Ruumbo]",
			fr = "[Totem of Ruumbo]",
			it = "[Totem of Ruumbo]",
			pt = "[Totem of Ruumbo]",
			ru = "[Totem of Ruumbo]",
			ko = "[Totem of Ruumbo]",
			cn = "[Totem of Ruumbo]",
		},
	},
	[284547] = {
		readable = "Beached Sea Turtle",
		model = 201475,
		text = {
			en = "Beached Sea Turtle",
			es = "[Beached Sea Turtle]",
			de = "[Beached Sea Turtle]",
			fr = "[Beached Sea Turtle]",
			it = "[Beached Sea Turtle]",
			pt = "[Beached Sea Turtle]",
			ru = "[Beached Sea Turtle]",
			ko = "[Beached Sea Turtle]",
			cn = "[Beached Sea Turtle]",
		},
	},
	[284572] = {
		readable = "Buzzbox 411",
		model = 197760,
		text = {
			en = "Buzzbox 411",
			es = "Caja mecánica 411",
			de = "Dröhnkiste 411",
			fr = "Bigobox 411",
			it = "Transanalizzatore 411",
			pt = "Caixazorra 411",
			ru = "Жужжалка 411",
			ko = "윙윙상자 411",
			cn = "[Buzzbox 411]",
		},
	},
	[284608] = {
		readable = "Skeletal Sea Turtle",
		model = 201475,
		text = {
			en = "Skeletal Sea Turtle",
			es = "Tortuga marina esquelética",
			de = "Skelettierte Meeresschildkröte",
			fr = "Squelette de tortue de mer",
			it = "Scheletro di Tartaruga Marina",
			pt = "Tartaruga Marinha Descarnada",
			ru = "Скелет морской черепахи",
			ko = "[Skeletal Sea Turtle]",
			cn = "[Skeletal Sea Turtle]",
		},
	},
	[284627] = {
		readable = "Beached Sea Creature",
		model = 201573,
		text = {
			en = "Beached Sea Creature",
			es = "Criatura marina varada",
			de = "Gestrandete Meereskreatur",
			fr = "Créature marine échouée",
			it = "Creatura Marina Arenata",
			pt = "Criatura Marinha Encalhada",
			ru = "Выброшенная на берег морская тварь",
			ko = "[Beached Sea Creature]",
			cn = "[Beached Sea Creature]",
		},
	},
	[284631] = {
		readable = "Beached Sea Turtle",
		model = 201475,
		text = {
			en = "Beached Sea Turtle",
			es = "Tortuga marina varada",
			de = "Gestrandete Meeresschildkröte",
			fr = "Tortue de mer échouée",
			it = "Tartaruga Marina Arenata",
			pt = "Tartaruga Marinha Encalhada",
			ru = "Выбросившаяся на берег морская черепаха",
			ko = "떠밀려 온 바다거북",
			cn = "搁浅的海龟",
		},
	},
	[284633] = {
		readable = "Buzzbox 525",
		model = 197760,
		text = {
			en = "Buzzbox 525",
			es = "[Buzzbox 525]",
			de = "[Buzzbox 525]",
			fr = "[Buzzbox 525]",
			it = "[Buzzbox 525]",
			pt = "[Buzzbox 525]",
			ru = "[Buzzbox 525]",
			ko = "[Buzzbox 525]",
			cn = "[Buzzbox 525]",
		},
	},
	[284635] = {
		readable = "Beached Sea Creature",
		model = 201568,
		text = {
			en = "Beached Sea Creature",
			es = "[Beached Sea Creature]",
			de = "[Beached Sea Creature]",
			fr = "[Beached Sea Creature]",
			it = "[Beached Sea Creature]",
			pt = "[Beached Sea Creature]",
			ru = "[Beached Sea Creature]",
			ko = "[Beached Sea Creature]",
			cn = "[Beached Sea Creature]",
		},
	},
	[284646] = {
		readable = "Buzzbox 827",
		model = 197760,
		text = {
			en = "Buzzbox 827",
			es = "Caja mecánica 827",
			de = "Dröhnkiste 827",
			fr = "Bigobox 827",
			it = "Transanalizzatore 827",
			pt = "Caixazorra 827",
			ru = "Жужжалка 827",
			ko = "윙윙상자 827",
			cn = "[Buzzbox 827]",
		},
	},
	[284658] = {
		readable = "Ancient Flame",
		model = 198836,
		text = {
			en = "Ancient Flame",
			es = "[Ancient Flame]",
			de = "[Ancient Flame]",
			fr = "[Ancient Flame]",
			it = "[Ancient Flame]",
			pt = "[Ancient Flame]",
			ru = "[Ancient Flame]",
			ko = "[Ancient Flame]",
			cn = "[Ancient Flame]",
		},
	},
	[284675] = {
		readable = "Potion of Wildfire",
		model = 198058,
		text = {
			en = "Potion of Wildfire",
			es = "[Potion of Wildfire]",
			de = "[Potion of Wildfire]",
			fr = "[Potion of Wildfire]",
			it = "[Potion of Wildfire]",
			pt = "[Potion of Wildfire]",
			ru = "[Potion of Wildfire]",
			ko = "[Potion of Wildfire]",
			cn = "[Potion of Wildfire]",
		},
	},
	[286952] = {
		readable = "Lichen-Covered Chest",
		model = 1806318,
		text = {
			en = "Lichen-Covered Chest",
			es = "Cofre cubierto de liquen",
			de = "Flechtenüberzogene Truhe",
			fr = "Coffre couvert de lichen",
			it = "Cassa Coperta di Licheni",
			pt = "Baú Coberto de Líquen",
			ru = "Заросший лишайником сундук",
			ko = "이끼투성이 상자",
			cn = "长满地衣的宝箱",
		},
	},
	[286953] = {
		readable = "Rod of Tides",
		model = 353152,
		text = {
			en = "Rod of Tides",
			es = "Vara de las Mareas",
			de = "Rute der Gezeiten",
			fr = "Bâton des marées",
			it = "Verga delle Maree",
			pt = "Bastão das Marés",
			ru = "Жезл приливов",
			ko = "파도의 봉",
			cn = "潮汐法杖",
		},
	},
	[286954] = {
		readable = "Bot Buster Bomb",
		model = 254419,
		text = {
			en = "Bot Buster Bomb",
			es = "Bomba destruyerrobots",
			de = "Botbrecherbombe",
			fr = "Bombe anti-robot",
			it = "Bomba Robodemolitrice",
			pt = "Bomba-robô Pressurizada",
			ru = "Противоботовая бомба",
			ko = "로봇 퇴치 폭탄",
			cn = "机械爆破弹",
		},
	},
	[286966] = {
		readable = "Plaque",
		model = 959595,
		text = {
			en = "Plaque",
			es = "Placa",
			de = "Plakette",
			fr = "Plaque",
			it = "Placca",
			pt = "Placa",
			ru = "Табличка",
			ko = "명판",
			cn = "铭牌",
		},
	},
})
do ObjectDB[objectID] = objectData; end