local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[455487] = {
		readable = "Sturdy Chest",
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			de = "Sturdy Chest",
			fr = "Sturdy Chest",
			it = "Sturdy Chest",
			pt = "Sturdy Chest",
			ru = "Sturdy Chest",
			ko = "Sturdy Chest",
			cn = "Sturdy Chest",
		},
	},
	[455492] = {
		readable = "Sturdy Chest",
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			de = "Sturdy Chest",
			fr = "Sturdy Chest",
			it = "Sturdy Chest",
			pt = "Sturdy Chest",
			ru = "Sturdy Chest",
			ko = "Sturdy Chest",
			cn = "Sturdy Chest",
		},
	},
	[455493] = {
		readable = "Sturdy Chest",
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			de = "Sturdy Chest",
			fr = "Sturdy Chest",
			it = "Sturdy Chest",
			pt = "Sturdy Chest",
			ru = "Sturdy Chest",
			ko = "Sturdy Chest",
			cn = "Sturdy Chest",
		},
	},
	[455509] = {
		readable = "Sturdy Chest",
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			de = "Sturdy Chest",
			fr = "Sturdy Chest",
			it = "Sturdy Chest",
			pt = "Sturdy Chest",
			ru = "Sturdy Chest",
			ko = "Sturdy Chest",
			cn = "Sturdy Chest",
		},
	},
	[455514] = {
		readable = "Sturdy Chest",
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			de = "Sturdy Chest",
			fr = "Sturdy Chest",
			it = "Sturdy Chest",
			pt = "Sturdy Chest",
			ru = "Sturdy Chest",
			ko = "Sturdy Chest",
			cn = "Sturdy Chest",
		},
	},
	[455533] = {
		readable = "Sturdy Chest",
		text = {
			en = "Sturdy Chest",
			es = "Sturdy Chest",
			de = "Sturdy Chest",
			fr = "Sturdy Chest",
			it = "Sturdy Chest",
			pt = "Sturdy Chest",
			ru = "Sturdy Chest",
			ko = "Sturdy Chest",
			cn = "Sturdy Chest",
		},
	},
})
do ObjectDB[objectID] = objectData; end