local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[437216] = {
		readable = "Sureki Shadecaster",
		model = 5516443,
		text = {
			en = "Sureki Shadecaster",
			es = "Proyector de sombras sureki",
			de = "Schattenwerfer der Sureki",
			fr = "Lance-ombre sureki",
			it = "Gettaombre dei Sureki",
			pt = "Umbrovisor Sureki",
			ru = "Теневещатель суреки",
			ko = "수레키 그늘투영기",
			cn = "苏雷吉映影仪",
			tw = "Sureki Shadecaster",
		},
	},
	[438037] = {
		readable = "Black Blood Vessel",
		model = 5248827,
		text = {
			en = "Black Blood Vessel",
			es = "Black Blood Vessel",
			de = "Schwarzblutgefäß",
			fr = "Réceptacle de Sang noir",
			it = "Black Blood Vessel",
			pt = "Receptáculo de Sangue Negro",
			ru = "Сосуд с черной кровью",
			ko = "Black Blood Vessel",
			cn = "黑血器皿",
			tw = "Black Blood Vessel",
		},
	},
	[439334] = {
		readable = "Sureki Shadecaster",
		model = 5516443,
		text = {
			en = "Sureki Shadecaster",
			es = "Proyector de sombras sureki",
			de = "Schattenwerfer der Sureki",
			fr = "Lance-ombre sureki",
			it = "Gettaombre dei Sureki",
			pt = "Umbrovisor Sureki",
			ru = "Теневещатель суреки",
			ko = "수레키 그늘투영기",
			cn = "Sureki Shadecaster",
			tw = "Sureki Shadecaster",
		},
	},
	[439339] = {
		readable = "Sureki Shadecaster",
		model = 5516443,
		text = {
			en = "Sureki Shadecaster",
			es = "Proyector de sombras sureki",
			de = "Schattenwerfer der Sureki",
			fr = "Lance-ombre sureki",
			it = "Sureki Shadecaster",
			pt = "Umbrovisor Sureki",
			ru = "Теневещатель суреки",
			ko = "Sureki Shadecaster",
			cn = "苏雷吉映影仪",
			tw = "Sureki Shadecaster",
		},
	},
})
do ObjectDB[objectID] = objectData; end