local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[408107] = {
		readable = "Crystalline Glowblossom",
		model = 4895040,
		text = {
			en = "Crystalline Glowblossom",
			es = "Brillaflor cristalina",
			de = "Kristalline Leuchtblüte",
			fr = "Lumiflore cristalline",
			it = "Boccioluce Cristallino",
			pt = "Floraluz Cristalina",
			ru = "Кристаллический яркоцвет",
			ko = "수정 광채꽃",
			cn = "晶化莹花",
		},
	},
	[408706] = {
		readable = "Magical Bloom",
		model = 5247222,
		text = {
			en = "Magical Bloom",
			es = "Flor mágica",
			de = "Magische Blüte",
			fr = "Floraison magique",
			it = "[Magical Bloom]",
			pt = "Floração Mágica",
			ru = "Магический цветок",
			ko = "마법 꽃송이",
			cn = "魔法花朵",
		},
	},
	[408707] = {
		readable = "Odd Burl",
		model = 4255713,
		text = {
			en = "Odd Burl",
			es = "Nudo extraño",
			de = "Seltsame Knolle",
			fr = "Nœud étrange",
			it = "Strano Nodo",
			pt = "Saliência Estranha",
			ru = "Странный нарост",
			ko = "특이한 옹이",
			cn = "奇怪的树节",
		},
	},
	[408980] = {
		readable = "Tyr's Legacy",
		model = 4288162,
		text = {
			en = "Tyr's Legacy",
			es = "El legado de Tyr",
			de = "Tyrs Vermächtnis",
			fr = "L’Héritage de Tyr",
			it = "Retaggio di Tyr",
			pt = "Legado de Tyr",
			ru = "Наследие Тира",
			ko = "[Tyr's Legacy]",
			cn = "提尔的遗产",
		},
	},
	[409077] = {
		readable = "Singed Leaflet",
		model = 929407,
		text = {
			en = "Singed Leaflet",
			es = "Folíolo chamuscado",
			de = "Angesengter Handzettel",
			fr = "Pamphlet roussi",
			it = "Volantino Bruciacchiato",
			pt = "Panfleto Chamuscado",
			ru = "Опаленный листок",
			ko = "그을린 유인물",
			cn = "[Singed Leaflet]",
		},
	},
	[409222] = {
		readable = "Boon of Ursol",
		model = 3522548,
		text = {
			en = "Boon of Ursol",
			es = "Boon of Ursol",
			de = "Boon of Ursol",
			fr = "Boon of Ursol",
			it = "Boon of Ursol",
			pt = "Boon of Ursol",
			ru = "Boon of Ursol",
			ko = "우르솔의 책",
			cn = "乌索尔的恩泽",
		},
	},
	[409320] = {
		readable = "Buried Object",
		model = 4539378,
		text = {
			en = "Buried Object",
			es = "Objeto enterrado",
			de = "Vergrabenes Objekt",
			fr = "Objet enterré",
			it = "Oggetto Sepolto",
			pt = "Objeto Enterrado",
			ru = "Закопанный предмет",
			ko = "[Buried Object]",
			cn = "埋藏的物品",
		},
	},
	[409329] = {
		readable = "Buried Object",
		model = 4539378,
		text = {
			en = "Buried Object",
			es = "Objeto enterrado",
			de = "Vergrabenes Objekt",
			fr = "Objet enterré",
			it = "Oggetto Sepolto",
			pt = "Objeto Enterrado",
			ru = "Закопанный предмет",
			ko = "[Buried Object]",
			cn = "埋藏的物品",
		},
	},
	[409333] = {
		readable = "Buried Object",
		model = 4539378,
		text = {
			en = "Buried Object",
			es = "Objeto enterrado",
			de = "Vergrabenes Objekt",
			fr = "Objet enterré",
			it = "Oggetto Sepolto",
			pt = "Objeto Enterrado",
			ru = "Закопанный предмет",
			ko = "[Buried Object]",
			cn = "埋藏的物品",
		},
	},
	[409440] = {
		readable = "Pineshrew Cache",
		model = 189528,
		text = {
			en = "Pineshrew Cache",
			es = "Alijo de pinusaraña",
			de = "Pinienmauslager",
			fr = "Réserve de musaraigne des pins",
			it = "Cassa di Soricidi",
			pt = "Depósito de Ratopinho",
			ru = "Тайник землехвойки",
			ko = "소나무도치 은닉처",
			cn = "松鼩鼱之箱",
		},
	},
	[409849] = {
		readable = "Ashwood Research Binder",
		model = 4914526,
		text = {
			en = "Ashwood Research Binder",
			es = "Archivador de investigación de fresno",
			de = "Eschenholzforschungsband",
			fr = "Classeur de recherches sur le frêne",
			it = "Faldone di Ricerca di Legno Secco",
			pt = "Atador de Pesquisa de Freixo",
			ru = "Папка с исследовательскими записями",
			ko = "잿빛나무 연구록",
			cn = "灰木研究活页夹",
		},
	},
	[410442] = {
		readable = "Root of the Problem",
		model = 4995252,
		text = {
			en = "Root of the Problem",
			es = "La raíz de los problemas",
			de = "Die Wurzel des Problems",
			fr = "Les racines du problème",
			it = "Radice del Problema",
			pt = "Raiz do Problema",
			ru = "Корень проблемы",
			ko = "문제의 뿌리",
			cn = "根本问题",
		},
	},
	[410479] = {
		readable = "Unpolished Blemish",
		model = 3794106,
		text = {
			en = "Unpolished Blemish",
			es = "Defecto sin pulir",
			de = "Unpolierter Makel",
			fr = "Défaut non poli",
			it = "Imperfezione Rifinita",
			pt = "Nódoa Tosca",
			ru = "Неотполированный изъян",
			ko = "닦지 않은 잡티",
			cn = "没抛光过的瑕疵",
		},
	},
	[410484] = {
		readable = "Coalesced Dreamstone",
		model = 2438984,
		text = {
			en = "Coalesced Dreamstone",
			es = "Piedra del Sueño fusionada",
			de = "Verschmolzener Traumstein",
			fr = "Pierre onirique coalescente",
			it = "Pietra Onirica Condensata",
			pt = "Pedra dos Sonhos Coalescida",
			ru = "Сгустившийся камень снов",
			ko = "응축된 꿈결석",
			cn = "凝结的梦境石",
		},
	},
	[410574] = {
		readable = "Pure Dream Water",
		model = 4290523,
		text = {
			en = "Pure Dream Water",
			es = "Agua onírica pura",
			de = "Reines Traumwasser",
			fr = "Eau de rêve pure",
			it = "Acqua del Sogno Pura",
			pt = "Água Pura do Sonho",
			ru = "Чистая вода из Сна",
			ko = "순수한 꿈의 물",
			cn = "纯净的梦境之水",
		},
	},
	[410582] = {
		readable = "Essence of Dreams",
		model = 4507691,
		text = {
			en = "Essence of Dreams",
			es = "Esencia de los sueños",
			de = "Essenz der Träume",
			fr = "Essence des rêves",
			it = "Essenza dei Sogni",
			pt = "Essência dos Sonhos",
			ru = "Сущность снов",
			ko = "꿈의 정수",
			cn = "梦境精华",
		},
	},
	[411066] = {
		readable = "Boon of Aviana",
		model = 3522548,
		text = {
			en = "Boon of Aviana",
			es = "Boon of Aviana",
			de = "Boon of Aviana",
			fr = "Boon of Aviana",
			it = "Boon of Aviana",
			pt = "Boon of Aviana",
			ru = "Boon of Aviana",
			ko = "아비아나의 은혜",
			cn = "艾维娜的恩泽",
		},
	},
	[411067] = {
		readable = "Boon of Goldrinn",
		model = 3522548,
		text = {
			en = "Boon of Goldrinn",
			es = "Boon of Goldrinn",
			de = "Boon of Goldrinn",
			fr = "Boon of Goldrinn",
			it = "[Boon of Goldrinn]",
			pt = "[Boon of Goldrinn]",
			ru = "Boon of Goldrinn",
			ko = "[Boon of Goldrinn]",
			cn = "戈德林的恩泽",
		},
	},
	[411169] = {
		readable = "Grove Keeper's Pillar",
		model = 2357389,
		text = {
			en = "Grove Keeper's Pillar",
			es = "Pilar del guardián de la arboleda",
			de = "Säule des Hainhüters",
			fr = "Pilier du gardien du bosquet",
			it = "Pilastro del Custode del Bosco",
			pt = "Pilar do Guardião do Bosque",
			ru = "Колонна хранителя рощи",
			ko = "숲지기의 기둥",
			cn = "林地守护者之柱",
		},
	},
	[411171] = {
		readable = "Exceedingly Soft Wildercloth",
		model = 4756260,
		text = {
			en = "Exceedingly Soft Wildercloth",
			es = "Tela salvaje extremadamente suave",
			de = "Enorm weicher Wildstoff",
			fr = "Trame-sauvage particulièrement douce",
			it = "Stoffabrada Estremamente Soffice",
			pt = "Selvatrama Extraordinariamente Macia",
			ru = "Необычайно мягкая ткань стихий",
			ko = "극도로 부드러운 야생천",
			cn = "极软的荒布",
		},
	},
	[411176] = {
		readable = "Plush Pillow",
		model = 5281468,
		text = {
			en = "Plush Pillow",
			es = "Almohada exuberante",
			de = "Flauschiges Kissen",
			fr = "Oreiller moelleux",
			it = "Cuscino Morbido",
			pt = "Travesseiro Fofinho",
			ru = "Плюшевая подушка",
			ko = "봉제 베개",
			cn = "[Plush Pillow]",
		},
	},
	[411179] = {
		readable = "Amirdrassil Defender's Shield",
		model = 5157472,
		text = {
			en = "Amirdrassil Defender's Shield",
			es = "Escudo de defensor de Amirdrassil",
			de = "Schild der Verteidigerin von Amirdrassil",
			fr = "Bouclier de défenseur d’Amirdrassil",
			it = "Scudo del Difensore di Amirdrassil",
			pt = "Escudo de Defensor de Amirdrassil",
			ru = "Щит защитницы Амирдрассила",
			ko = "아미드랏실 수호병의 방패",
			cn = "[Amirdrassil Defender's Shield]",
		},
	},
	[411447] = {
		readable = "Unwaking Echo",
		model = 1349621,
		text = {
			en = "Unwaking Echo",
			es = "Eco del despertar",
			de = "Nie erwachendes Echo",
			fr = "Écho non réveillé",
			it = "Eco del Non Risveglio",
			pt = "Eco Indesperto",
			ru = "Непробуждающийся отголосок",
			ko = "깨어나지 않는 메아리",
			cn = "酣眠回响",
		},
	},
	[411463] = {
		readable = "Unwaking Echo",
		model = 1349621,
		text = {
			en = "Unwaking Echo",
			es = "Eco del despertar",
			de = "Nie erwachendes Echo",
			fr = "Écho non réveillé",
			it = "Eco del Non Risveglio",
			pt = "Eco Indesperto",
			ru = "Непробуждающийся отголосок",
			ko = "깨어나지 않는 메아리",
			cn = "酣眠回响",
		},
	},
	[411465] = {
		readable = "Unwaking Echo",
		model = 1349621,
		text = {
			en = "Unwaking Echo",
			es = "Eco del despertar",
			de = "Nie erwachendes Echo",
			fr = "Écho non réveillé",
			it = "Eco del Non Risveglio",
			pt = "Eco Indesperto",
			ru = "Непробуждающийся отголосок",
			ko = "깨어나지 않는 메아리",
			cn = "酣眠回响",
		},
	},
	[411778] = {
		readable = "Pollenfused Bristlebruin Fur Sample",
		model = 1334478,
		text = {
			en = "Pollenfused Bristlebruin Fur Sample",
			es = "Muestra de pelaje de erizapúas polinizado",
			de = "Pollenerfüllte Probe eines Borstenpetzpelzes",
			fr = "Échantillon de fourrure d’hoursute amalgamée de pollen",
			it = "[Pollenfused Bristlebruin Fur Sample]",
			pt = "Amostra de Pelo de Fuscocerdo Polenfuso",
			ru = "Образец шерсти опыленного лохматого косолапа",
			ko = "꽃가루주입 가시털불곰 모피 표본",
			cn = "[Pollenfused Bristlebruin Fur Sample]",
		},
	},
})
do ObjectDB[objectID] = objectData; end