local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[441637] = {
		readable = "A Weathered Tome",
		text = {
			en = "A Weathered Tome",
			es = "A Weathered Tome",
			de = "A Weathered Tome",
			fr = "A Weathered Tome",
			it = "A Weathered Tome",
			pt = "A Weathered Tome",
			ru = "A Weathered Tome",
			ko = "A Weathered Tome",
			cn = "A Weathered Tome",
		},
	},
	[454201] = {
		readable = "|cff1EFF00Sturdy Chest",
		model = 5128194,
		text = {
			en = "|cff1EFF00Sturdy Chest",
			es = "|cff1EFF00Cofre robusto",
			de = "|cff1EFF00Robuste Truhe",
			fr = "|cff1EFF00Coffre solide",
			it = "|cff1EFF00Cassa Resistente",
			pt = "|cff1EFF00Baú Resistente",
			ru = "|cff1EFF00Прочный сундук",
			ko = "|cff1EFF00Sturdy Chest",
			cn = "|cff1EFF00Sturdy Chest",
		},
	},
	[454202] = {
		readable = "|cff1EFF00Sturdy Chest",
		model = 5128194,
		text = {
			en = "|cff1EFF00Sturdy Chest",
			es = "|cff1EFF00Cofre robusto",
			de = "|cff1EFF00Robuste Truhe",
			fr = "|cff1EFF00Coffre solide",
			it = "|cff1EFF00Cassa Resistente",
			pt = "|cff1EFF00Baú Resistente",
			ru = "|cff1EFF00Прочный сундук",
			ko = "|cff1EFF00Sturdy Chest",
			cn = "|cff1EFF00Sturdy Chest",
		},
	},
	[455486] = {
		readable = "|cff1EFF00Sturdy Chest",
		model = 5128194,
		text = {
			en = "|cff1EFF00Sturdy Chest",
			es = "|cff1EFF00Cofre robusto",
			de = "|cff1EFF00Robuste Truhe",
			fr = "|cff1EFF00Coffre solide",
			it = "|cff1EFF00Cassa Resistente",
			pt = "|cff1EFF00Baú Resistente",
			ru = "|cff1EFF00Прочный сундук",
			ko = "|cff1EFF00Sturdy Chest",
			cn = "|cff1EFF00Sturdy Chest",
		},
	},
	[455491] = {
		readable = "|cff1EFF00Sturdy Chest",
		model = 5128194,
		text = {
			en = "|cff1EFF00Sturdy Chest",
			es = "|cff1EFF00Cofre robusto",
			de = "|cff1EFF00Robuste Truhe",
			fr = "|cff1EFF00Coffre solide",
			it = "|cff1EFF00Cassa Resistente",
			pt = "|cff1EFF00Baú Resistente",
			ru = "|cff1EFF00Прочный сундук",
			ko = "|cff1EFF00Sturdy Chest",
			cn = "|cff1EFF00Sturdy Chest",
		},
	},
	[455494] = {
		readable = "|cff1EFF00Sturdy Chest",
		model = 5128194,
		text = {
			en = "|cff1EFF00Sturdy Chest",
			es = "|cff1EFF00Cofre robusto",
			de = "|cff1EFF00Robuste Truhe",
			fr = "|cff1EFF00Coffre solide",
			it = "|cff1EFF00Cassa Resistente",
			pt = "|cff1EFF00Baú Resistente",
			ru = "|cff1EFF00Прочный сундук",
			ko = "|cff1EFF00Sturdy Chest",
			cn = "|cff1EFF00Sturdy Chest",
		},
	},
	[455497] = {
		readable = "|cff1EFF00Sturdy Chest",
		model = 5128194,
		text = {
			en = "|cff1EFF00Sturdy Chest",
			es = "|cff1EFF00Cofre robusto",
			de = "|cff1EFF00Robuste Truhe",
			fr = "|cff1EFF00Coffre solide",
			it = "|cff1EFF00Cassa Resistente",
			pt = "|cff1EFF00Baú Resistente",
			ru = "|cff1EFF00Прочный сундук",
			ko = "|cff1EFF00Sturdy Chest",
			cn = "|cff1EFF00Sturdy Chest",
		},
	},
	[455505] = {
		readable = "|cff1EFF00Sturdy Chest",
		model = 5128194,
		text = {
			en = "|cff1EFF00Sturdy Chest",
			es = "|cff1EFF00Cofre robusto",
			de = "|cff1EFF00Robuste Truhe",
			fr = "|cff1EFF00Coffre solide",
			it = "|cff1EFF00Cassa Resistente",
			pt = "|cff1EFF00Baú Resistente",
			ru = "|cff1EFF00Прочный сундук",
			ko = "|cff1EFF00Sturdy Chest",
			cn = "|cff1EFF00Sturdy Chest",
		},
	},
	[455513] = {
		readable = "|cff1EFF00Sturdy Chest",
		model = 5128194,
		text = {
			en = "|cff1EFF00Sturdy Chest",
			es = "|cff1EFF00Cofre robusto",
			de = "|cff1EFF00Robuste Truhe",
			fr = "|cff1EFF00Coffre solide",
			it = "|cff1EFF00Cassa Resistente",
			pt = "|cff1EFF00Baú Resistente",
			ru = "|cff1EFF00Прочный сундук",
			ko = "|cff1EFF00Sturdy Chest",
			cn = "|cff1EFF00Sturdy Chest",
		},
	},
	[455517] = {
		readable = "|cff1EFF00Sturdy Chest",
		model = 5128194,
		text = {
			en = "|cff1EFF00Sturdy Chest",
			es = "|cff1EFF00Cofre robusto",
			de = "|cff1EFF00Robuste Truhe",
			fr = "|cff1EFF00Coffre solide",
			it = "|cff1EFF00Cassa Resistente",
			pt = "|cff1EFF00Baú Resistente",
			ru = "|cff1EFF00Прочный сундук",
			ko = "|cff1EFF00Sturdy Chest",
			cn = "|cff1EFF00Sturdy Chest",
		},
	},
	[455522] = {
		readable = "|cff1EFF00Sturdy Chest",
		model = 5128194,
		text = {
			en = "|cff1EFF00Sturdy Chest",
			es = "|cff1EFF00Cofre robusto",
			de = "|cff1EFF00Robuste Truhe",
			fr = "|cff1EFF00Coffre solide",
			it = "|cff1EFF00Cassa Resistente",
			pt = "|cff1EFF00Baú Resistente",
			ru = "|cff1EFF00Прочный сундук",
			ko = "|cff1EFF00Sturdy Chest",
			cn = "|cff1EFF00Sturdy Chest",
		},
	},
	[455525] = {
		readable = "|cff1EFF00Sturdy Chest",
		model = 5128194,
		text = {
			en = "|cff1EFF00Sturdy Chest",
			es = "|cff1EFF00Cofre robusto",
			de = "|cff1EFF00Robuste Truhe",
			fr = "|cff1EFF00Coffre solide",
			it = "|cff1EFF00Cassa Resistente",
			pt = "|cff1EFF00Baú Resistente",
			ru = "|cff1EFF00Прочный сундук",
			ko = "|cff1EFF00Sturdy Chest",
			cn = "|cff1EFF00Sturdy Chest",
		},
	},
	[455526] = {
		readable = "|cff1EFF00Sturdy Chest",
		model = 5128194,
		text = {
			en = "|cff1EFF00Sturdy Chest",
			es = "|cff1EFF00Cofre robusto",
			de = "|cff1EFF00Robuste Truhe",
			fr = "|cff1EFF00Coffre solide",
			it = "|cff1EFF00Cassa Resistente",
			pt = "|cff1EFF00Baú Resistente",
			ru = "|cff1EFF00Прочный сундук",
			ko = "|cff1EFF00Sturdy Chest",
			cn = "|cff1EFF00Sturdy Chest",
		},
	},
	[455534] = {
		readable = "|cff1EFF00Sturdy Chest",
		model = 5128194,
		text = {
			en = "|cff1EFF00Sturdy Chest",
			es = "|cff1EFF00Cofre robusto",
			de = "|cff1EFF00Robuste Truhe",
			fr = "|cff1EFF00Coffre solide",
			it = "|cff1EFF00Cassa Resistente",
			pt = "|cff1EFF00Baú Resistente",
			ru = "|cff1EFF00Прочный сундук",
			ko = "|cff1EFF00Sturdy Chest",
			cn = "|cff1EFF00Sturdy Chest",
		},
	},
	[455914] = {
		readable = "Mislaid Curiosity",
		model = 3936818,
		text = {
			en = "Mislaid Curiosity",
			es = "Mislaid Curiosity",
			de = "Mislaid Curiosity",
			fr = "Mislaid Curiosity",
			it = "Mislaid Curiosity",
			pt = "Mislaid Curiosity",
			ru = "Mislaid Curiosity",
			ko = "Mislaid Curiosity",
			cn = "Mislaid Curiosity",
		},
	},
})
do ObjectDB[objectID] = objectData; end