local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[287370] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears029",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears029",
			es = "[Doodad_8DU_CityofGold_CeilingSpears029]",
			de = "Doodad_8DU_CityofGold_CeilingSpears029",
			fr = "Doodad_8DU_CityofGold_CeilingSpears029",
			it = "[Doodad_8DU_CityofGold_CeilingSpears029]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears029",
			ru = "Doodad_8DU_CityofGold_CeilingSpears029",
			ko = "Doodad_8DU_CityofGold_CeilingSpears029",
			cn = "Doodad_8DU_CityofGold_CeilingSpears029",
		},
	},
	[287371] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears030",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears030",
			es = "[Doodad_8DU_CityofGold_CeilingSpears030]",
			de = "Doodad_8DU_CityofGold_CeilingSpears030",
			fr = "Doodad_8DU_CityofGold_CeilingSpears030",
			it = "[Doodad_8DU_CityofGold_CeilingSpears030]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears030",
			ru = "Doodad_8DU_CityofGold_CeilingSpears030",
			ko = "Doodad_8DU_CityofGold_CeilingSpears030",
			cn = "Doodad_8DU_CityofGold_CeilingSpears030",
		},
	},
	[287372] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears031",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears031",
			es = "[Doodad_8DU_CityofGold_CeilingSpears031]",
			de = "Doodad_8DU_CityofGold_CeilingSpears031",
			fr = "Doodad_8DU_CityofGold_CeilingSpears031",
			it = "[Doodad_8DU_CityofGold_CeilingSpears031]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears031",
			ru = "Doodad_8DU_CityofGold_CeilingSpears031",
			ko = "Doodad_8DU_CityofGold_CeilingSpears031",
			cn = "Doodad_8DU_CityofGold_CeilingSpears031",
		},
	},
	[287373] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears032",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears032",
			es = "[Doodad_8DU_CityofGold_CeilingSpears032]",
			de = "Doodad_8DU_CityofGold_CeilingSpears032",
			fr = "Doodad_8DU_CityofGold_CeilingSpears032",
			it = "[Doodad_8DU_CityofGold_CeilingSpears032]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears032",
			ru = "Doodad_8DU_CityofGold_CeilingSpears032",
			ko = "Doodad_8DU_CityofGold_CeilingSpears032",
			cn = "Doodad_8DU_CityofGold_CeilingSpears032",
		},
	},
	[287374] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears033",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears033",
			es = "[Doodad_8DU_CityofGold_CeilingSpears033]",
			de = "Doodad_8DU_CityofGold_CeilingSpears033",
			fr = "Doodad_8DU_CityofGold_CeilingSpears033",
			it = "[Doodad_8DU_CityofGold_CeilingSpears033]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears033",
			ru = "Doodad_8DU_CityofGold_CeilingSpears033",
			ko = "Doodad_8DU_CityofGold_CeilingSpears033",
			cn = "Doodad_8DU_CityofGold_CeilingSpears033",
		},
	},
	[287375] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears034",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears034",
			es = "[Doodad_8DU_CityofGold_CeilingSpears034]",
			de = "Doodad_8DU_CityofGold_CeilingSpears034",
			fr = "Doodad_8DU_CityofGold_CeilingSpears034",
			it = "[Doodad_8DU_CityofGold_CeilingSpears034]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears034",
			ru = "Doodad_8DU_CityofGold_CeilingSpears034",
			ko = "Doodad_8DU_CityofGold_CeilingSpears034",
			cn = "Doodad_8DU_CityofGold_CeilingSpears034",
		},
	},
	[287376] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears035",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears035",
			es = "[Doodad_8DU_CityofGold_CeilingSpears035]",
			de = "Doodad_8DU_CityofGold_CeilingSpears035",
			fr = "Doodad_8DU_CityofGold_CeilingSpears035",
			it = "[Doodad_8DU_CityofGold_CeilingSpears035]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears035",
			ru = "Doodad_8DU_CityofGold_CeilingSpears035",
			ko = "Doodad_8DU_CityofGold_CeilingSpears035",
			cn = "Doodad_8DU_CityofGold_CeilingSpears035",
		},
	},
	[287377] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears036",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears036",
			es = "[Doodad_8DU_CityofGold_CeilingSpears036]",
			de = "Doodad_8DU_CityofGold_CeilingSpears036",
			fr = "Doodad_8DU_CityofGold_CeilingSpears036",
			it = "[Doodad_8DU_CityofGold_CeilingSpears036]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears036",
			ru = "Doodad_8DU_CityofGold_CeilingSpears036",
			ko = "Doodad_8DU_CityofGold_CeilingSpears036",
			cn = "Doodad_8DU_CityofGold_CeilingSpears036",
		},
	},
	[287378] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears037",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears037",
			es = "[Doodad_8DU_CityofGold_CeilingSpears037]",
			de = "Doodad_8DU_CityofGold_CeilingSpears037",
			fr = "Doodad_8DU_CityofGold_CeilingSpears037",
			it = "[Doodad_8DU_CityofGold_CeilingSpears037]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears037",
			ru = "Doodad_8DU_CityofGold_CeilingSpears037",
			ko = "Doodad_8DU_CityofGold_CeilingSpears037",
			cn = "Doodad_8DU_CityofGold_CeilingSpears037",
		},
	},
	[287379] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears038",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears038",
			es = "[Doodad_8DU_CityofGold_CeilingSpears038]",
			de = "Doodad_8DU_CityofGold_CeilingSpears038",
			fr = "Doodad_8DU_CityofGold_CeilingSpears038",
			it = "[Doodad_8DU_CityofGold_CeilingSpears038]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears038",
			ru = "Doodad_8DU_CityofGold_CeilingSpears038",
			ko = "Doodad_8DU_CityofGold_CeilingSpears038",
			cn = "Doodad_8DU_CityofGold_CeilingSpears038",
		},
	},
	[287380] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears039",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears039",
			es = "[Doodad_8DU_CityofGold_CeilingSpears039]",
			de = "Doodad_8DU_CityofGold_CeilingSpears039",
			fr = "Doodad_8DU_CityofGold_CeilingSpears039",
			it = "[Doodad_8DU_CityofGold_CeilingSpears039]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears039",
			ru = "Doodad_8DU_CityofGold_CeilingSpears039",
			ko = "Doodad_8DU_CityofGold_CeilingSpears039",
			cn = "Doodad_8DU_CityofGold_CeilingSpears039",
		},
	},
	[287381] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears040",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears040",
			es = "[Doodad_8DU_CityofGold_CeilingSpears040]",
			de = "Doodad_8DU_CityofGold_CeilingSpears040",
			fr = "Doodad_8DU_CityofGold_CeilingSpears040",
			it = "[Doodad_8DU_CityofGold_CeilingSpears040]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears040",
			ru = "Doodad_8DU_CityofGold_CeilingSpears040",
			ko = "Doodad_8DU_CityofGold_CeilingSpears040",
			cn = "Doodad_8DU_CityofGold_CeilingSpears040",
		},
	},
	[287382] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears041",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears041",
			es = "[Doodad_8DU_CityofGold_CeilingSpears041]",
			de = "Doodad_8DU_CityofGold_CeilingSpears041",
			fr = "Doodad_8DU_CityofGold_CeilingSpears041",
			it = "[Doodad_8DU_CityofGold_CeilingSpears041]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears041",
			ru = "Doodad_8DU_CityofGold_CeilingSpears041",
			ko = "Doodad_8DU_CityofGold_CeilingSpears041",
			cn = "Doodad_8DU_CityofGold_CeilingSpears041",
		},
	},
	[287383] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears042",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears042",
			es = "[Doodad_8DU_CityofGold_CeilingSpears042]",
			de = "Doodad_8DU_CityofGold_CeilingSpears042",
			fr = "Doodad_8DU_CityofGold_CeilingSpears042",
			it = "[Doodad_8DU_CityofGold_CeilingSpears042]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears042",
			ru = "Doodad_8DU_CityofGold_CeilingSpears042",
			ko = "Doodad_8DU_CityofGold_CeilingSpears042",
			cn = "Doodad_8DU_CityofGold_CeilingSpears042",
		},
	},
	[287384] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears043",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears043",
			es = "[Doodad_8DU_CityofGold_CeilingSpears043]",
			de = "Doodad_8DU_CityofGold_CeilingSpears043",
			fr = "Doodad_8DU_CityofGold_CeilingSpears043",
			it = "[Doodad_8DU_CityofGold_CeilingSpears043]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears043",
			ru = "Doodad_8DU_CityofGold_CeilingSpears043",
			ko = "Doodad_8DU_CityofGold_CeilingSpears043",
			cn = "Doodad_8DU_CityofGold_CeilingSpears043",
		},
	},
	[287385] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears044",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears044",
			es = "[Doodad_8DU_CityofGold_CeilingSpears044]",
			de = "Doodad_8DU_CityofGold_CeilingSpears044",
			fr = "Doodad_8DU_CityofGold_CeilingSpears044",
			it = "[Doodad_8DU_CityofGold_CeilingSpears044]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears044",
			ru = "Doodad_8DU_CityofGold_CeilingSpears044",
			ko = "Doodad_8DU_CityofGold_CeilingSpears044",
			cn = "Doodad_8DU_CityofGold_CeilingSpears044",
		},
	},
	[287386] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears045",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears045",
			es = "[Doodad_8DU_CityofGold_CeilingSpears045]",
			de = "Doodad_8DU_CityofGold_CeilingSpears045",
			fr = "Doodad_8DU_CityofGold_CeilingSpears045",
			it = "[Doodad_8DU_CityofGold_CeilingSpears045]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears045",
			ru = "Doodad_8DU_CityofGold_CeilingSpears045",
			ko = "Doodad_8DU_CityofGold_CeilingSpears045",
			cn = "Doodad_8DU_CityofGold_CeilingSpears045",
		},
	},
	[287387] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears046",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears046",
			es = "[Doodad_8DU_CityofGold_CeilingSpears046]",
			de = "Doodad_8DU_CityofGold_CeilingSpears046",
			fr = "Doodad_8DU_CityofGold_CeilingSpears046",
			it = "[Doodad_8DU_CityofGold_CeilingSpears046]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears046",
			ru = "Doodad_8DU_CityofGold_CeilingSpears046",
			ko = "Doodad_8DU_CityofGold_CeilingSpears046",
			cn = "Doodad_8DU_CityofGold_CeilingSpears046",
		},
	},
	[287388] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears047",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears047",
			es = "[Doodad_8DU_CityofGold_CeilingSpears047]",
			de = "Doodad_8DU_CityofGold_CeilingSpears047",
			fr = "Doodad_8DU_CityofGold_CeilingSpears047",
			it = "[Doodad_8DU_CityofGold_CeilingSpears047]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears047",
			ru = "Doodad_8DU_CityofGold_CeilingSpears047",
			ko = "Doodad_8DU_CityofGold_CeilingSpears047",
			cn = "Doodad_8DU_CityofGold_CeilingSpears047",
		},
	},
	[287389] = {
		readable = "Doodad_8DU_CityofGold_CeilingSpears048",
		model = 1954506,
		text = {
			en = "Doodad_8DU_CityofGold_CeilingSpears048",
			es = "[Doodad_8DU_CityofGold_CeilingSpears048]",
			de = "Doodad_8DU_CityofGold_CeilingSpears048",
			fr = "Doodad_8DU_CityofGold_CeilingSpears048",
			it = "[Doodad_8DU_CityofGold_CeilingSpears048]",
			pt = "Doodad_8DU_CityofGold_CeilingSpears048",
			ru = "Doodad_8DU_CityofGold_CeilingSpears048",
			ko = "Doodad_8DU_CityofGold_CeilingSpears048",
			cn = "Doodad_8DU_CityofGold_CeilingSpears048",
		},
	},
	[287402] = {
		readable = "Logs",
		model = 943646,
		text = {
			en = "Logs",
			es = "Troncos",
			de = "Holzscheite",
			fr = "Bûches",
			it = "Mucchio di Tronchi",
			pt = "Troncos",
			ru = "Поленья",
			ko = "통나무들",
			cn = "原木",
		},
	},
	[287403] = {
		readable = "Water Bucket",
		model = 1709138,
		text = {
			en = "Water Bucket",
			es = "Cubo de agua",
			de = "Wassereimer",
			fr = "Seau d’eau",
			it = "Secchio d'Acqua",
			pt = "Balde d'Água",
			ru = "Ведро с водой",
			ko = "물동이",
			cn = "水桶",
		},
	},
	[287404] = {
		readable = "Riverbottom Nest",
		model = 1279713,
		text = {
			en = "Riverbottom Nest",
			es = "Nido Fondorrío",
			de = "Flussgrundnest",
			fr = "Nid de fond-de-rive",
			it = "Nido dei Fondali",
			pt = "Ninho de Bicafundo",
			ru = "Гнездо донного охотника",
			ko = "강바닥 둥지",
			cn = "河沙巢穴",
		},
	},
	[287443] = {
		readable = "Cook Pot",
		model = 1321592,
		text = {
			en = "Cook Pot",
			es = "Olla de cocina",
			de = "Kochtopf",
			fr = "Marmite",
			it = "Pentolone da Cucina",
			pt = "Panela de Cozinheiro",
			ru = "Котелок",
			ko = "요리 냄비",
			cn = "烹饪锅",
		},
	},
	[287444] = {
		readable = "Fallen Log",
		model = 1109563,
		text = {
			en = "Fallen Log",
			es = "Tronco caído",
			de = "Umgefallener Baumstamm",
			fr = "Rondin tombé",
			it = "Tronco Caduto",
			pt = "Tora Caída",
			ru = "Упавшее бревно",
			ko = "[Fallen Log]",
			cn = "倒下的原木",
		},
	},
	[287445] = {
		readable = "Heavy Beam",
		model = 879780,
		text = {
			en = "Heavy Beam",
			es = "Haz pesado",
			de = "Schwerer Balken",
			fr = "Poutre lourde",
			it = "Trave Pesante",
			pt = "Viga Pesada",
			ru = "Тяжелая балка",
			ko = "[Heavy Beam]",
			cn = "重型木梁",
		},
	},
	[287446] = {
		readable = "Stake",
		model = 874901,
		text = {
			en = "Stake",
			es = "Poste",
			de = "Pfahl",
			fr = "Piquet",
			it = "Paletto",
			pt = "Estaca",
			ru = "Костыль",
			ko = "말뚝",
			cn = "桩子",
		},
	},
	[287447] = {
		readable = "Strangling Vines",
		model = 197122,
		text = {
			en = "Strangling Vines",
			es = "Cepas estranguladoras",
			de = "Würgeranken",
			fr = "Lierre étrangleur",
			it = "Viticci Strangolanti",
			pt = "Vinhas Estranguladoras",
			ru = "Удушающие лозы",
			ko = "교살의 덩굴",
			cn = "窒息之藤",
		},
	},
	[287448] = {
		readable = "Entangling Roots",
		model = 251902,
		text = {
			en = "Entangling Roots",
			es = "Raíces enredadoras",
			de = "Wucherwurzeln",
			fr = "Sarments",
			it = "Radici Avvolgenti",
			pt = "Raízes Enredantes",
			ru = "Гнев деревьев",
			ko = "휘감는 뿌리",
			cn = "纠缠根须",
		},
	},
	[287449] = {
		readable = "Block of Ice",
		model = 338495,
		text = {
			en = "Block of Ice",
			es = "Bloque de hielo",
			de = "Eisblock",
			fr = "Bloc de glace",
			it = "Blocco di Ghiaccio",
			pt = "Bloco de Gelo",
			ru = "Глыба льда",
			ko = "얼음 덩어리",
			cn = "[Block of Ice]",
		},
	},
	[287451] = {
		readable = "Carnivorous Plant",
		model = 1936566,
		text = {
			en = "Carnivorous Plant",
			es = "Planta carnívora",
			de = "Fleischfressende Pflanze",
			fr = "Plante carnivore",
			it = "Pianta Carnivora",
			pt = "Planta Carnívora",
			ru = "Хищное растение",
			ko = "육식 식물",
			cn = "食肉植物",
		},
	},
	[287452] = {
		readable = "Dead Greatfrog",
		model = 166432,
		text = {
			en = "Dead Greatfrog",
			es = "Gran rana muerta",
			de = "Schreckensgroßfrosch",
			fr = "Grenouille morte",
			it = "Granrana Morta",
			pt = "Grande Sapo Morto",
			ru = "Мертвая жаба",
			ko = "[Dead Greatfrog]",
			cn = "[Dead Greatfrog]",
		},
	},
	[287453] = {
		readable = "Dirt Pile",
		model = 204112,
		text = {
			en = "Dirt Pile",
			es = "Montón de tierra",
			de = "Erdhaufen",
			fr = "Tas de terre",
			it = "Cumulo di Terra",
			pt = "Monte de Terra",
			ru = "Куча земли",
			ko = "흙더미",
			cn = "泥土堆",
		},
	},
	[287454] = {
		readable = "Huge Rock",
		model = 1045776,
		text = {
			en = "Huge Rock",
			es = "Roca enorme",
			de = "Riesiger Felsen",
			fr = "Gigantesque rocher",
			it = "Roccia Enorme",
			pt = "Rocha Enorme",
			ru = "Большой камень",
			ko = "커다란 바위",
			cn = "巨石",
		},
	},
	[287456] = {
		readable = "Metal Cage",
		model = 1416598,
		text = {
			en = "Metal Cage",
			es = "Jaula metálica",
			de = "Metallkäfig",
			fr = "Cage en métal",
			it = "Gabbia di Metallo",
			pt = "Jaula de Metal",
			ru = "Металлическая клетка",
			ko = "[Metal Cage]",
			cn = "[Metal Cage]",
		},
	},
	[287457] = {
		readable = "Reinforced Cage",
		model = 195417,
		text = {
			en = "Reinforced Cage",
			es = "Jaula reforzada",
			de = "Verstärkter Käfig",
			fr = "Cage renforcée",
			it = "Gabbia Rinforzata",
			pt = "Jaula Reforçada",
			ru = "Укрепленная клетка",
			ko = "강화 우리",
			cn = "加固的牢笼",
		},
	},
	[287458] = {
		readable = "Volatile Cure-all",
		model = 243479,
		text = {
			en = "Volatile Cure-all",
			es = "Panacea volátil",
			de = "Unbeständiges Allheilmittel",
			fr = "Remède instable",
			it = "Curatutto Instabile",
			pt = "Panaceia Volátil",
			ru = "Нестабильная панацея",
			ko = "휘발성 만병통치약",
			cn = "不稳定的万能药剂",
		},
	},
	[287459] = {
		readable = "Pickaxe",
		model = 984881,
		text = {
			en = "Pickaxe",
			es = "Piqueta",
			de = "Spitzhacke",
			fr = "Pioche",
			it = "Piccone",
			pt = "Picareta",
			ru = "Кирка",
			ko = "곡괭이",
			cn = "矿锄",
		},
	},
	[287460] = {
		readable = "Leafy Poultice",
		model = 571710,
		text = {
			en = "Leafy Poultice",
			es = "Cataplasma de hojas",
			de = "Blattwickel",
			fr = "Cataplasme à base de feuilles",
			it = "Intruglio Frondoso",
			pt = "Cataplasma Folhoso",
			ru = "Припарка из листьев",
			ko = "나뭇잎 찜질약",
			cn = "叶子膏药",
		},
	},
	[287461] = {
		readable = "Rope Coil",
		model = 1616076,
		text = {
			en = "Rope Coil",
			es = "Bobina de cuerda",
			de = "Aufgerolltes Seil",
			fr = "Rouleau de corde",
			it = "Spira di Corda",
			pt = "Espiral de Corda",
			ru = "Моток веревки",
			ko = "밧줄 고리",
			cn = "[Rope Coil]",
		},
	},
	[287463] = {
		readable = "Old Ship Part",
		model = 1611302,
		text = {
			en = "Old Ship Part",
			es = "Pieza de barco vieja",
			de = "Altes Wrackteil",
			fr = "Vieille pièce de navire",
			it = "Vecchia Parte di Nave",
			pt = "Peça de Navio Velha",
			ru = "Обломок старого корабля",
			ko = "낡은 배 부품",
			cn = "老旧轮船零件",
		},
	},
	[287464] = {
		readable = "Doodad_8DU_NazmirRaid_Elevator001",
		text = {
			en = "Doodad_8DU_NazmirRaid_Elevator001",
			es = "[Doodad_8DU_NazmirRaid_Elevator001]",
			de = "Doodad_8DU_NazmirRaid_Elevator001",
			fr = "Doodad_8DU_NazmirRaid_Elevator001",
			it = "[Doodad_8DU_NazmirRaid_Elevator001]",
			pt = "Doodad_8DU_NazmirRaid_Elevator001",
			ru = "Doodad_8DU_NazmirRaid_Elevator001",
			ko = "Doodad_8DU_NazmirRaid_Elevator001",
			cn = "Doodad_8DU_NazmirRaid_Elevator001",
		},
	},
	[287466] = {
		readable = "Old Ship Part",
		model = 1119128,
		text = {
			en = "Old Ship Part",
			es = "Pieza de barco vieja",
			de = "Altes Wrackteil",
			fr = "Vieille pièce de navire",
			it = "Vecchia Parte di Nave",
			pt = "Peça de Navio Velha",
			ru = "Обломок старого корабля",
			ko = "낡은 배 부품",
			cn = "老旧轮船零件",
		},
	},
	[287467] = {
		readable = "Old Ship Part",
		model = 1956756,
		text = {
			en = "Old Ship Part",
			es = "Pieza de barco vieja",
			de = "Altes Wrackteil",
			fr = "Vieille pièce de navire",
			it = "Vecchia Parte di Nave",
			pt = "Peça de Navio Velha",
			ru = "Обломок старого корабля",
			ko = "낡은 배 부품",
			cn = "老旧轮船零件",
		},
	},
	[287468] = {
		readable = "Old Ship Part",
		model = 1121294,
		text = {
			en = "Old Ship Part",
			es = "Pieza de barco vieja",
			de = "Altes Wrackteil",
			fr = "Vieille pièce de navire",
			it = "Vecchia Parte di Nave",
			pt = "Peça de Navio Velha",
			ru = "Обломок старого корабля",
			ko = "낡은 배 부품",
			cn = "老旧轮船零件",
		},
	},
	[287490] = {
		readable = "Cursed Treasure",
		model = 1254955,
		text = {
			en = "Cursed Treasure",
			es = "Tesoro maldito",
			de = "Verfluchter Schatz",
			fr = "Trésor maudit",
			it = "Tesoro Maledetto",
			pt = "Tesouro Amaldiçoado",
			ru = "Проклятое сокровище",
			ko = "저주받은 보물",
			cn = "[Cursed Treasure]",
		},
	},
	[287493] = {
		readable = "Cursed Treasure",
		model = 1254446,
		text = {
			en = "Cursed Treasure",
			es = "Tesoro maldito",
			de = "Verfluchter Schatz",
			fr = "Trésor maudit",
			it = "Tesoro Maledetto",
			pt = "Tesouro Amaldiçoado",
			ru = "Проклятое сокровище",
			ko = "저주받은 보물",
			cn = "[Cursed Treasure]",
		},
	},
	[287495] = {
		readable = "Pirate Hat",
		model = 426042,
		text = {
			en = "Pirate Hat",
			es = "Sombrero de pirata",
			de = "Piratenhut",
			fr = "Chapeau de pirate",
			it = "Cappello da Pirata",
			pt = "Chapéu de Pirata",
			ru = "Шляпа пирата",
			ko = "해적 모자",
			cn = "海盗帽",
		},
	},
	[287496] = {
		readable = "Treasure Map",
		model = 791609,
		text = {
			en = "Treasure Map",
			es = "Mapa del tesoro",
			de = "Schatzkarte",
			fr = "Carte au trésor",
			it = "Mappa del Tesoro",
			pt = "Mapa do Tesouro",
			ru = "Карта сокровищ",
			ko = "보물 지도",
			cn = "藏宝图",
		},
	},
	[287497] = {
		readable = "Azerite Chunk",
		model = 1857375,
		text = {
			en = "Azerite Chunk",
			es = "Trozo de azerita",
			de = "Azeritklumpen",
			fr = "Morceau d’azérite",
			it = "Pezzo d'Azerite",
			pt = "Pedaço de Azerita",
			ru = "Глыба азерита",
			ko = "아제라이트 덩어리",
			cn = "大块艾泽里特",
		},
	},
	[287498] = {
		readable = "Zem'lan Blackeye Brew",
		model = 1608207,
		text = {
			en = "Zem'lan Blackeye Brew",
			es = "Brebaje Ojonegro de Zem'lan",
			de = "Zem'lans Veilchenbräu",
			fr = "Breuvage d’Oeil-Noir",
			it = "Birra Occhionero di Zem'lan",
			pt = "Cerveja Zem'lan Olho-Roxo",
			ru = "Черный отвар Зем'лана",
			ko = "젬란 멍든눈술",
			cn = "泽姆兰黑眼佳酿",
		},
	},
	[287531] = {
		readable = "Small Treasure Chest",
		model = 2120294,
		text = {
			en = "Small Treasure Chest",
			es = "Arqueta pequeña",
			de = "Kleine Schatztruhe",
			fr = "Petit coffre au trésor",
			it = "Cassa del Tesoro Piccola",
			pt = "Baú do Tesouro Pequeno",
			ru = "Маленький сундук с сокровищами",
			ko = "작은 보물 상자",
			cn = "小宝箱",
		},
	},
})
do ObjectDB[objectID] = objectData; end