local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[148418] = {
		readable = "Eternal Flame",
		model = 200934,
		text = {
			en = "Eternal Flame",
			es = "Llama eterna",
			de = "Ewige Flamme",
			fr = "Flamme éternelle",
			it = "Fiamma Eterna",
			pt = "Chama Eterna",
			ru = "Неугасимое пламя",
			ko = "영원의 불꽃",
			cn = "永恒之火",
		},
	},
	[148419] = {
		readable = "Eternal Flame",
		model = 200934,
		text = {
			en = "Eternal Flame",
			es = "Llama eterna",
			de = "Ewige Flamme",
			fr = "Flamme éternelle",
			it = "Fiamma Eterna",
			pt = "Chama Eterna",
			ru = "Неугасимое пламя",
			ko = "영원의 불꽃",
			cn = "永恒之火",
		},
	},
	[148420] = {
		readable = "Eternal Flame",
		model = 200934,
		text = {
			en = "Eternal Flame",
			es = "Llama eterna",
			de = "Ewige Flamme",
			fr = "Flamme éternelle",
			it = "Fiamma Eterna",
			pt = "Chama Eterna",
			ru = "Неугасимое пламя",
			ko = "영원의 불꽃",
			cn = "永恒之火",
		},
	},
	[148421] = {
		readable = "Eternal Flame",
		model = 200934,
		text = {
			en = "Eternal Flame",
			es = "Llama eterna",
			de = "Ewige Flamme",
			fr = "Flamme éternelle",
			it = "Fiamma Eterna",
			pt = "Chama Eterna",
			ru = "Неугасимое пламя",
			ko = "영원의 불꽃",
			cn = "永恒之火",
		},
	},
	[148498] = {
		readable = "Altar of Suntara",
		model = 189280,
		text = {
			en = "Altar of Suntara",
			es = "Altar de Suntara",
			de = "Altar von Suntara",
			fr = "Autel de Suntara",
			it = "Altare di Suntara",
			pt = "Altar de Suntara",
			ru = "Алтарь Сунтары",
			ko = "선타라의 제단",
			cn = "苏塔拉祭坛",
		},
	},
	[148499] = {
		readable = "Felix's Box",
		model = 190013,
		text = {
			en = "Felix's Box",
			es = "Caja de Félix",
			de = "Felix' Kasten",
			fr = "Boîte de Felix",
			it = "Scatola di Felix",
			pt = "Caixa do Félix",
			ru = "Ящик Феликса",
			ko = "[Felix's Box]",
			cn = "[Felix's Box]",
		},
	},
	[148506] = {
		readable = "Twilight Artifact",
		model = 202136,
		text = {
			en = "Twilight Artifact",
			es = "Artefacto Crepuscular",
			de = "Schattenhammerartefakt",
			fr = "Artéfact du Crépuscule",
			it = "Manufatto Crepuscolare",
			pt = "Artefato do Crepúsculo",
			ru = "Сумеречный Артефакт",
			ko = "황혼의 유물",
			cn = "暮光神器",
		},
	},
	[148512] = {
		readable = "Essence Font",
		model = 201422,
		text = {
			en = "Essence Font",
			es = "Fuente de esencia",
			de = "Essenz-Born",
			fr = "Réceptacle d'essence",
			it = "[Essence Font]",
			pt = "[Essence Font]",
			ru = "Купель сущности",
			ko = "[Essence Font]",
			cn = "[Essence Font]",
		},
	},
	[148830] = {
		readable = "Atal'ai Statue",
		model = 190304,
		text = {
			en = "Atal'ai Statue",
			es = "Estatua Atal'ai",
			de = "Statue der Atal'ai",
			fr = "Statue atal'ai",
			it = "[Atal'ai Statue]",
			pt = "[Atal'ai Statue]",
			ru = "Статуя Аталаи",
			ko = "[Atal'ai Statue]",
			cn = "[Atal'ai Statue]",
		},
	},
	[148831] = {
		readable = "Atal'ai Statue",
		model = 190304,
		text = {
			en = "Atal'ai Statue",
			es = "Estatua Atal'ai",
			de = "Statue der Atal'ai",
			fr = "Statue atal'ai",
			it = "[Atal'ai Statue]",
			pt = "[Atal'ai Statue]",
			ru = "Статуя Аталаи",
			ko = "[Atal'ai Statue]",
			cn = "[Atal'ai Statue]",
		},
	},
	[148832] = {
		readable = "Atal'ai Statue",
		model = 190304,
		text = {
			en = "Atal'ai Statue",
			es = "Estatua Atal'ai",
			de = "Statue der Atal'ai",
			fr = "Statue atal'ai",
			it = "[Atal'ai Statue]",
			pt = "[Atal'ai Statue]",
			ru = "Статуя Аталаи",
			ko = "[Atal'ai Statue]",
			cn = "[Atal'ai Statue]",
		},
	},
	[148833] = {
		readable = "Atal'ai Statue",
		model = 190304,
		text = {
			en = "Atal'ai Statue",
			es = "Estatua Atal'ai",
			de = "Statue der Atal'ai",
			fr = "Statue atal'ai",
			it = "[Atal'ai Statue]",
			pt = "[Atal'ai Statue]",
			ru = "Статуя Аталаи",
			ko = "[Atal'ai Statue]",
			cn = "[Atal'ai Statue]",
		},
	},
	[148834] = {
		readable = "Atal'ai Statue",
		model = 190304,
		text = {
			en = "Atal'ai Statue",
			es = "Estatua Atal'ai",
			de = "Statue der Atal'ai",
			fr = "Statue atal'ai",
			it = "[Atal'ai Statue]",
			pt = "[Atal'ai Statue]",
			ru = "Статуя Аталаи",
			ko = "[Atal'ai Statue]",
			cn = "[Atal'ai Statue]",
		},
	},
	[148835] = {
		readable = "Atal'ai Statue",
		model = 190304,
		text = {
			en = "Atal'ai Statue",
			es = "Estatua Atal'ai",
			de = "Statue der Atal'ai",
			fr = "Statue atal'ai",
			it = "[Atal'ai Statue]",
			pt = "[Atal'ai Statue]",
			ru = "Статуя Аталаи",
			ko = "[Atal'ai Statue]",
			cn = "[Atal'ai Statue]",
		},
	},
	[148836] = {
		readable = "Altar of Hakkar",
		model = 190363,
		text = {
			en = "Altar of Hakkar",
			es = "Altar de Hakkar",
			de = "Altar von Hakkar",
			fr = "Autel d'Hakkar",
			it = "[Altar of Hakkar]",
			pt = "[Altar of Hakkar]",
			ru = "Алтарь Хаккара",
			ko = "[Altar of Hakkar]",
			cn = "[Altar of Hakkar]",
		},
	},
	[148838] = {
		readable = "Idol of Hakkar",
		model = 190304,
		text = {
			en = "Idol of Hakkar",
			es = "Ídolo de Hakkar",
			de = "Götze von Hakkar",
			fr = "Idole d'Hakkar",
			it = "[Idol of Hakkar]",
			pt = "[Idol of Hakkar]",
			ru = "Идол Хаккара",
			ko = "[Idol of Hakkar]",
			cn = "[Idol of Hakkar]",
		},
	},
	[148842] = {
		readable = "Roland's Mana Gem",
		model = 190807,
		text = {
			en = "Roland's Mana Gem",
			es = "[Roland's Mana Gem]",
			de = "Ronalds Manaedelstein",
			fr = "[Roland's Mana Gem]",
			it = "[Roland's Mana Gem]",
			pt = "[Roland's Mana Gem]",
			ru = "Самоцвет маны Роланда",
			ko = "[Roland's Mana Gem]",
			cn = "[Roland's Mana Gem]",
		},
	},
	[148917] = {
		readable = "Gong",
		model = 201028,
		text = {
			en = "Gong",
			es = "Gong",
			de = "Gong",
			fr = "Gong",
			it = "Gong",
			pt = "Gongo",
			ru = "Гонг",
			ko = "징",
			cn = "铜锣",
		},
	},
	[148998] = {
		readable = "Evil God Summoning Circle",
		model = 201104,
		text = {
			en = "Evil God Summoning Circle",
			es = "Círculo de Invocación del Dios malvado",
			de = "Böser Gott Beschwörungskreis",
			fr = "Cercle d'invocation du dieu malfaisant",
			it = "[Evil God Summoning Circle]",
			pt = "[Evil God Summoning Circle]",
			ru = "Круг Призыва Злого Бога",
			ko = "[Evil God Summoning Circle]",
			cn = "[Evil God Summoning Circle]",
		},
	},
	[149025] = {
		readable = "Sentry Brazier",
		model = 201422,
		text = {
			en = "Sentry Brazier",
			es = "Blandón de avizor",
			de = "Wachpostenkohlenpfanne",
			fr = "Brasero de sentinelle",
			it = "Braciere della Sentinella",
			pt = "Braseiro Sentinela",
			ru = "Жаровня на башне",
			ko = "감시의 화롯불",
			cn = "哨岗火盆",
		},
	},
	[149030] = {
		readable = "Sentry Brazier",
		model = 201422,
		text = {
			en = "Sentry Brazier",
			es = "Blandón de avizor",
			de = "Wachpostenkohlenpfanne",
			fr = "Brasero de sentinelle",
			it = "Braciere della Sentinella",
			pt = "Braseiro Sentinela",
			ru = "Жаровня на башне",
			ko = "감시의 화롯불",
			cn = "哨岗火盆",
		},
	},
	[149031] = {
		readable = "Sentry Brazier",
		model = 201422,
		text = {
			en = "Sentry Brazier",
			es = "Blandón de avizor",
			de = "Wachpostenkohlenpfanne",
			fr = "Brasero de sentinelle",
			it = "Braciere della Sentinella",
			pt = "Braseiro Sentinela",
			ru = "Жаровня на башне",
			ko = "감시의 화롯불",
			cn = "哨岗火盆",
		},
	},
	[149032] = {
		readable = "Sentry Brazier",
		model = 201422,
		text = {
			en = "Sentry Brazier",
			es = "Blandón de avizor",
			de = "Wachpostenkohlenpfanne",
			fr = "Brasero de sentinelle",
			it = "Braciere della Sentinella",
			pt = "Braseiro Sentinela",
			ru = "Жаровня на башне",
			ko = "감시의 화롯불",
			cn = "哨岗火盆",
		},
	},
	[149045] = {
		readable = "Scaffold Cars",
		model = 198191,
		text = {
			en = "Scaffold Cars",
			es = "Carretillas",
			de = "Gerüstwagen",
			fr = "Chariots",
			it = "Elevatori",
			pt = "Vagões do Andaime",
			ru = "Передвижные леса",
			ko = "이동발판",
			cn = "绞刑车",
		},
	},
	[149046] = {
		readable = "Scaffold Cars",
		model = 198191,
		text = {
			en = "Scaffold Cars",
			es = "Carretillas",
			de = "Gerüstwagen",
			fr = "Chariots",
			it = "Elevatori",
			pt = "Vagões do Andaime",
			ru = "Передвижные леса",
			ko = "이동발판",
			cn = "绞刑车",
		},
	},
	[149047] = {
		readable = "Torch of Retribution",
		model = 198655,
		text = {
			en = "Torch of Retribution",
			es = "Antorcha de reprensión",
			de = "Fackel der Vergeltung",
			fr = "Torche de vindicte",
			it = "[Torch of Retribution]",
			pt = "[Torch of Retribution]",
			ru = "Факел воздаяния",
			ko = "[Torch of Retribution]",
			cn = "[Torch of Retribution]",
		},
	},
	[149420] = {
		readable = "Ani",
		model = 189337,
		text = {
			en = "Ani",
			es = "Ani",
			de = "Ani",
			fr = "Ani",
			it = "[Ani]",
			pt = "[Ani]",
			ru = "Ани",
			ko = "[Ani]",
			cn = "[Ani]",
		},
	},
	[149480] = {
		readable = "Rune of Jin'yael",
		model = 199976,
		text = {
			en = "Rune of Jin'yael",
			es = "Runa de Jin'yael",
			de = "Rune von Jin'yael",
			fr = "Rune de Jin'yael",
			it = "[Rune of Jin'yael]",
			pt = "[Rune of Jin'yael]",
			ru = "Руна Джин'яэль",
			ko = "[Rune of Jin'yael]",
			cn = "[Rune of Jin'yael]",
		},
	},
	[149481] = {
		readable = "Rune of Beth'Amara",
		model = 199976,
		text = {
			en = "Rune of Beth'Amara",
			es = "Runa de Beth'Amara",
			de = "Rune von Beth'Amara",
			fr = "Rune de Beth'Amara",
			it = "[Rune of Beth'Amara]",
			pt = "[Rune of Beth'Amara]",
			ru = "Руна Бет'Амары",
			ko = "[Rune of Beth'Amara]",
			cn = "[Rune of Beth'Amara]",
		},
	},
	[149482] = {
		readable = "Rune of Markri",
		model = 199976,
		text = {
			en = "Rune of Markri",
			es = "Runa de Markri",
			de = "Rune von Markri",
			fr = "Rune de Markri",
			it = "[Rune of Markri]",
			pt = "[Rune of Markri]",
			ru = "Руна Маркри",
			ko = "[Rune of Markri]",
			cn = "[Rune of Markri]",
		},
	},
	[149483] = {
		readable = "Rune of Sael'hai",
		model = 199976,
		text = {
			en = "Rune of Sael'hai",
			es = "Runa de Sael'hai",
			de = "Rune von Sael'hai",
			fr = "Rune de Sael'hai",
			it = "[Rune of Sael'hai]",
			pt = "[Rune of Sael'hai]",
			ru = "Руна Саэл'Хаи",
			ko = "[Rune of Sael'hai]",
			cn = "[Rune of Sael'hai]",
		},
	},
})
do ObjectDB[objectID] = objectData; end