local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[455269] = {
		readable = "Notes On The Machine Speakers: Fragment I",
		model = 3978480,
		text = {
			en = "Notes On The Machine Speakers: Fragment I",
			es = "Notes On The Machine Speakers: Fragment I",
			de = "Notes On The Machine Speakers: Fragment I",
			fr = "Notes On The Machine Speakers: Fragment I",
			it = "Notes On The Machine Speakers: Fragment I",
			pt = "Notes On The Machine Speakers: Fragment I",
			ru = "Notes On The Machine Speakers: Fragment I",
			ko = "Notes On The Machine Speakers: Fragment I",
			cn = "Notes On The Machine Speakers: Fragment I",
		},
	},
	[455274] = {
		readable = "Notes On The Machine Speakers: Fragment II",
		model = 3978480,
		text = {
			en = "Notes On The Machine Speakers: Fragment II",
			es = "Notes On The Machine Speakers: Fragment II",
			de = "Notes On The Machine Speakers: Fragment II",
			fr = "Notes On The Machine Speakers: Fragment II",
			it = "Notes On The Machine Speakers: Fragment II",
			pt = "Notes On The Machine Speakers: Fragment II",
			ru = "Notes On The Machine Speakers: Fragment II",
			ko = "Notes On The Machine Speakers: Fragment II",
			cn = "Notes On The Machine Speakers: Fragment II",
		},
	},
	[455275] = {
		readable = "Notes On The Machine Speakers: Fragment III",
		model = 3978480,
		text = {
			en = "Notes On The Machine Speakers: Fragment III",
			es = "Notes On The Machine Speakers: Fragment III",
			de = "Notes On The Machine Speakers: Fragment III",
			fr = "Notes On The Machine Speakers: Fragment III",
			it = "Notes On The Machine Speakers: Fragment III",
			pt = "Notes On The Machine Speakers: Fragment III",
			ru = "Notes On The Machine Speakers: Fragment III",
			ko = "Notes On The Machine Speakers: Fragment III",
			cn = "Notes On The Machine Speakers: Fragment III",
		},
	},
	[455276] = {
		readable = "Notes On The Machine Speakers: Fragment IV",
		model = 3978480,
		text = {
			en = "Notes On The Machine Speakers: Fragment IV",
			es = "Notes On The Machine Speakers: Fragment IV",
			de = "Notes On The Machine Speakers: Fragment IV",
			fr = "Notes On The Machine Speakers: Fragment IV",
			it = "Notes On The Machine Speakers: Fragment IV",
			pt = "Notes On The Machine Speakers: Fragment IV",
			ru = "Notes On The Machine Speakers: Fragment IV",
			ko = "Notes On The Machine Speakers: Fragment IV",
			cn = "Notes On The Machine Speakers: Fragment IV",
		},
	},
	[455277] = {
		readable = "Notes On The Machine Speakers: Fragment V",
		model = 3978480,
		text = {
			en = "Notes On The Machine Speakers: Fragment V",
			es = "Notes On The Machine Speakers: Fragment V",
			de = "Notes On The Machine Speakers: Fragment V",
			fr = "Notes On The Machine Speakers: Fragment V",
			it = "Notes On The Machine Speakers: Fragment V",
			pt = "Notes On The Machine Speakers: Fragment V",
			ru = "Notes On The Machine Speakers: Fragment V",
			ko = "Notes On The Machine Speakers: Fragment V",
			cn = "Notes On The Machine Speakers: Fragment V",
		},
	},
	[455278] = {
		readable = "Notes On The Machine Speakers: Fragment VI",
		model = 3978480,
		text = {
			en = "Notes On The Machine Speakers: Fragment VI",
			es = "Notes On The Machine Speakers: Fragment VI",
			de = "Notes On The Machine Speakers: Fragment VI",
			fr = "Notes On The Machine Speakers: Fragment VI",
			it = "Notes On The Machine Speakers: Fragment VI",
			pt = "Notes On The Machine Speakers: Fragment VI",
			ru = "Notes On The Machine Speakers: Fragment VI",
			ko = "Notes On The Machine Speakers: Fragment VI",
			cn = "Notes On The Machine Speakers: Fragment VI",
		},
	},
	[461482] = {
		readable = "Hidden Trove",
		model = 5869302,
		text = {
			en = "Hidden Trove",
			es = "Hidden Trove",
			de = "Hidden Trove",
			fr = "Hidden Trove",
			it = "Hidden Trove",
			pt = "Hidden Trove",
			ru = "Hidden Trove",
			ko = "Hidden Trove",
			cn = "Hidden Trove",
		},
	},
})
do ObjectDB[objectID] = objectData; end