local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[451967] = {
		readable = "Hillhelm Lunchbox",
		model = 197617,
		text = {
			en = "Hillhelm Lunchbox",
			es = "Fiambrera de Yelmocolina",
			de = "Vesperdose des Hügelpinnenhofs",
			fr = "Boîte à repas de Heaume-Colline",
			it = "Cestino della Merenda di Elmocolle",
			pt = "Lancheira de Montelmo",
			ru = "Коробка с обедом Хиллхельм",
			ko = "힐헬름 도시락",
			cn = "希尔海姆午餐盒",
		},
	},
	[451993] = {
		readable = "Nerubian Device",
		model = 5128439,
		text = {
			en = "Nerubian Device",
			es = "Nerubian Device",
			de = "Nerubisches Gerät",
			fr = "Appareil nérubien",
			it = "Dispositivo Nerubiano",
			pt = "Dispositivo Nerubiano",
			ru = "Нерубское устройство",
			ko = "Nerubian Device",
			cn = "蛛魔的装置",
		},
	},
	[452005] = {
		readable = "Lil Piggy",
		model = 125420,
		text = {
			en = "Lil Piggy",
			es = "Lil Piggy",
			de = "Kleines Schweinchen",
			fr = "P’tit Groin",
			it = "Lil Piggy",
			pt = "Lil Piggy",
			ru = "Поросеночек",
			ko = "Lil Piggy",
			cn = "Lil Piggy",
		},
	},
	[452438] = {
		readable = "Half-Buried Dog Bowl",
		model = 955688,
		text = {
			en = "Half-Buried Dog Bowl",
			es = "Cuenco de perro semienterrado",
			de = "Halb vergrabener Hundenapf",
			fr = "Gamelle pour chien partiellement enterrée",
			it = "Scodella per Cani Mezza Sepolta",
			pt = "Tigela de Cachorro Semienterrada",
			ru = "Полузакопанная собачья миска",
			ko = "반쯤 묻힌 개 밥그릇",
			cn = "Half-Buried Dog Bowl",
		},
	},
	[452696] = {
		readable = "Machine Speaker's Reliquary",
		model = 5128194,
		text = {
			en = "Machine Speaker's Reliquary",
			es = "Relicario de mecaorador",
			de = "Reliquiar des Maschinenflüsterers",
			fr = "Reliquaire du mandataire des machines",
			it = "Reliquiario dell'Oratore delle Macchine",
			pt = "Relicário do Mensageiro Mecânico",
			ru = "Реликварий глашатая механизмов",
			ko = "기계 대변자의 성물",
			cn = "机语者圣匣",
		},
	},
	[452706] = {
		readable = "Deep-Lost Satchel",
		model = 3936818,
		text = {
			en = "Deep-Lost Satchel",
			es = "Bolsa perdida en lo profundo",
			de = "In den Tiefen verlorenes Säckchen",
			fr = "Sacoche perdue dans l’abîme",
			it = "Borsa Perduta",
			pt = "Algibeira Perdida nas Profundezas",
			ru = "Сумка из глубин",
			ko = "잊힌 심연의 주머니",
			cn = "深渊失落小包",
		},
	},
	[452708] = {
		readable = "\"Weaving Supplies\"",
		model = 5545988,
		text = {
			en = "\"Weaving Supplies\"",
			es = "\"Suministros para tejer\"",
			de = "\"Webereivorräte\"",
			fr = "« Fournitures de tissage »",
			it = "\"Rifornimenti di Tessitura\"",
			pt = "\"Suprimentos de Tecelagem\"",
			ru = "\"Припасы для ткачей\"",
			ko = "\"직조 보급품\"",
			cn = "“纺织材料”",
		},
	},
	[452710] = {
		readable = "Brimming Deep-Lost Satchel",
		model = 4070769,
		text = {
			en = "Brimming Deep-Lost Satchel",
			es = "Bolsa perdida en lo profundo rebosante",
			de = "In den Tiefen verlorenes überquellendes Säckchen",
			fr = "Sacoche débordante perdue dans l’abîme",
			it = "Borsa Perduta Stracolma",
			pt = "Algibeira Perdida nas Profundezas Cheia",
			ru = "Переполненная сумка из глубин",
			ko = "가득 찬 잊힌 심연의 주머니",
			cn = "满溢的深渊失落小包",
		},
	},
	[453167] = {
		readable = "Disturbed Lynx Treasure",
		model = 5659419,
		text = {
			en = "Disturbed Lynx Treasure",
			es = "Tesoro de lince perturbado",
			de = "Aufgewühlter Luchsschatz",
			fr = "Trésor du lynx perturbé",
			it = "Tesoro Smosso di Lince",
			pt = "Tesouro do Lince Remexido",
			ru = "Потревоженное сокровище рыси",
			ko = "흐트러진 스라소니 보물",
			cn = "被惊扰的山猫宝藏",
		},
	},
	[453186] = {
		readable = "Nightfarm Growthling",
		model = 5095674,
		text = {
			en = "Nightfarm Growthling",
			es = "Crecimiento de granja nocturna",
			de = "Nachthofwuchsling",
			fr = "Croissancile de nocteferme",
			it = "Piantina Coltivanotte",
			pt = "Tumorito Noturno",
			ru = "Росток с Ночной фермы",
			ko = "Nightfarm Growthling",
			cn = "Nightfarm Growthling",
		},
	},
	[453283] = {
		readable = "Smuggler's Treasure",
		model = 5154231,
		text = {
			en = "Smuggler's Treasure",
			es = "Tesoro de contrabandista",
			de = "Schmugglerschatz",
			fr = "Trésor du contrebandier",
			it = "Tesoro del Contrabbandiere",
			pt = "Tesouro do Contrabandista",
			ru = "Сокровище контрабандиста",
			ko = "밀수업자의 보물",
			cn = "走私者的财宝",
		},
	},
	[453359] = {
		readable = "Dark Ritual",
		model = 5387323,
		text = {
			en = "Dark Ritual",
			es = "Ritual oscuro",
			de = "Dunkles Ritual",
			fr = "Rituel des ténèbres",
			it = "Rituale Oscuro",
			pt = "Ritual das Trevas",
			ru = "Темный ритуал",
			ko = "암흑의 의식",
			cn = "黑暗仪式",
		},
	},
	[453374] = {
		readable = "Shadowed Essence",
		model = 4681253,
		text = {
			en = "Shadowed Essence",
			es = "Esencia ensombrecida",
			de = "Schattige Essenz",
			fr = "Essence ombreuse",
			it = "Essenza Adombrata",
			pt = "Essência Sombria",
			ru = "Затененная сущность",
			ko = "어둠에 물든 정수",
			cn = "缀影精华",
		},
	},
	[453741] = {
		readable = "Loremaster's Reward",
		model = 5154231,
		text = {
			en = "Loremaster's Reward",
			es = "Recompensa de maestro cultural",
			de = "Belohnung des Meisters der Lehren",
			fr = "Récompense du maître des traditions",
			it = "Ricompensa dello Storico",
			pt = "Recompensa do Mestre Historiador",
			ru = "Награда хранителя истории",
			ko = "현자의 보상",
			cn = "博学者的奖赏",
		},
	},
	[453749] = {
		readable = "Palawltar's Codex of Dimensional Structure",
		model = 5334701,
		text = {
			en = "Palawltar's Codex of Dimensional Structure",
			es = "Códice de estructura dimensional de Palawltar",
			de = "Palawltars Kodex der dimensionalen Struktur",
			fr = "Codex de structure dimensionnelle de Paloltar",
			it = "Codice di Palawltar della Struttura Dimensionale",
			pt = "Códice de Estrutura Dimensional de Palawltar",
			ru = "Манускрипт Палавлтара о структуре измерений",
			ko = "팔라왈타르의 차원 구조 전서",
			cn = "《帕劳塔的维度结构法典》",
		},
	},
	[453751] = {
		readable = "Care and Feeding of the Imperial Lynx",
		model = 5334700,
		text = {
			en = "Care and Feeding of the Imperial Lynx",
			es = "Alimentación y cuidado del lince imperial",
			de = "Pflege und Ernährung des Kaiserluchses",
			fr = "Soins et alimentation du lynx impérial",
			it = "Cura e Nutrimento della Lince Imperiale",
			pt = "Cuidado e Nutrição do Lince Imperial",
			ru = "Императорская рысь: уход и кормление",
			ko = "제국 스라소니 사육 및 먹이",
			cn = "《帝国山猫照看和饲养》",
		},
	},
	[453752] = {
		readable = "Shadow Curfew Guidelines",
		model = 5334701,
		text = {
			en = "Shadow Curfew Guidelines",
			es = "Normas del toque de queda sombrío",
			de = "Richtlinien der Schattensperrstunde",
			fr = "Directives du couvre-feu de l’ombre",
			it = "Linee Guida del Coprifuoco d'Ombra",
			pt = "Normas do Toque de Recolher das Sombras",
			ru = "Правила теневого комендантского часа",
			ko = "어둠 통행 금지 지침",
			cn = "《暗影宵禁指南》",
		},
	},
	[453753] = {
		readable = "Beledar- The Emperor's Vision",
		model = 5334702,
		text = {
			en = "Beledar- The Emperor's Vision",
			es = "Beledar: Visión del Emperador",
			de = "Beledar - Vision des Kaisers",
			fr = "Beledar – la Vision de l’empereur",
			it = "Beledar - La Visione dell'Imperatore",
			pt = "Beledar – A Visão do Imperador",
			ru = "Беледар: видение императора",
			ko = "벨레다르 - 황제의 환영",
			cn = "《贝雷达尔 - 帝皇幻象》",
		},
	},
	[453754] = {
		readable = "The Song of Renilash",
		model = 5387324,
		text = {
			en = "The Song of Renilash",
			es = "La canción de Renilash",
			de = "Das Lied von Renilash",
			fr = "Le Chant de Renilash",
			it = "Canto del Renilash",
			pt = "A Canção do Renilace",
			ru = "Песнь Ренилаша",
			ko = "레닐래쉬의 노래",
			cn = "《雷尼拉什之歌》",
		},
	},
	[453755] = {
		readable = "The Big Book of Arathi Idioms",
		model = 5334703,
		text = {
			en = "The Big Book of Arathi Idioms",
			es = "El gran libro de expresiones arathi",
			de = "Das große Buch über die Idiome der Arathi",
			fr = "Le Grand Livre des expressions arathies",
			it = "Il Gran Tomo degli Idiomi Arathi",
			pt = "Enciclopédia de Expressões Arathi",
			ru = "Большая книга аратийских идиом",
			ko = "아라시 관용구 대사전",
			cn = "《阿拉希习语全集》",
		},
	},
	[453937] = {
		readable = "500 Dishes Using Cave Fish and Mushrooms",
		model = 5334700,
		text = {
			en = "500 Dishes Using Cave Fish and Mushrooms",
			es = "500 recetas con peces cavernícolas y setas",
			de = "500 Gerichte mit Höhlenfischen und Pilzen",
			fr = "500 plats avec des champignons et des poissons des grottes",
			it = "500 Piatti con Pesce di Caverna e Funghi",
			pt = "500 Pratos com Peixes e Cogumelos de Caverna",
			ru = "500 блюд из пещерной рыбы и грибов",
			ko = "동굴 생선과 버섯을 이용한 요리 500선",
			cn = "《500道洞穴鱼类和蘑菇食谱》",
		},
	},
	[454037] = {
		readable = "Stolen Supplies",
		model = 5048188,
		text = {
			en = "Stolen Supplies",
			es = "Stolen Supplies",
			de = "Stolen Supplies",
			fr = "Stolen Supplies",
			it = "Stolen Supplies",
			pt = "Stolen Supplies",
			ru = "Украденные припасы",
			ko = "Stolen Supplies",
			cn = "Stolen Supplies",
		},
	},
	[454038] = {
		readable = "Stolen Supplies",
		model = 5048188,
		text = {
			en = "Stolen Supplies",
			es = "Stolen Supplies",
			de = "Gestohlene Vorräte",
			fr = "Fournitures volées",
			it = "Stolen Supplies",
			pt = "Stolen Supplies",
			ru = "Украденные припасы",
			ko = "Stolen Supplies",
			cn = "Stolen Supplies",
		},
	},
	[454039] = {
		readable = "Stolen Supplies",
		model = 5048188,
		text = {
			en = "Stolen Supplies",
			es = "Stolen Supplies",
			de = "Gestohlene Vorräte",
			fr = "Fournitures volées",
			it = "Stolen Supplies",
			pt = "Stolen Supplies",
			ru = "Stolen Supplies",
			ko = "Stolen Supplies",
			cn = "Stolen Supplies",
		},
	},
})
do ObjectDB[objectID] = objectData; end