local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[437058] = {
		readable = "Forgotten Memorial",
		text = {
			en = "Forgotten Memorial",
			es = "Forgotten Memorial",
			de = "Forgotten Memorial",
			fr = "Forgotten Memorial",
			it = "Forgotten Memorial",
			pt = "Forgotten Memorial",
			ru = "Forgotten Memorial",
			ko = "Forgotten Memorial",
			cn = "Forgotten Memorial",
		},
	},
	[437191] = {
		readable = "Forgotten Memorial",
		text = {
			en = "Forgotten Memorial",
			es = "Forgotten Memorial",
			de = "Forgotten Memorial",
			fr = "Forgotten Memorial",
			it = "Forgotten Memorial",
			pt = "Forgotten Memorial",
			ru = "Forgotten Memorial",
			ko = "Forgotten Memorial",
			cn = "Forgotten Memorial",
		},
	},
	[444797] = {
		readable = "Threadspun Cache",
		text = {
			en = "Threadspun Cache",
			es = "Threadspun Cache",
			de = "Threadspun Cache",
			fr = "Threadspun Cache",
			it = "Threadspun Cache",
			pt = "Threadspun Cache",
			ru = "Threadspun Cache",
			ko = "Threadspun Cache",
			cn = "Threadspun Cache",
		},
	},
	[444800] = {
		readable = "Sureki Strongbox",
		text = {
			en = "Sureki Strongbox",
			es = "Sureki Strongbox",
			de = "Sureki Strongbox",
			fr = "Sureki Strongbox",
			it = "Sureki Strongbox",
			pt = "Sureki Strongbox",
			ru = "Sureki Strongbox",
			ko = "Sureki Strongbox",
			cn = "Sureki Strongbox",
		},
	},
	[444844] = {
		readable = "Stashed Loot",
		model = 4182533,
		text = {
			en = "Stashed Loot",
			es = "Stashed Loot",
			de = "Stashed Loot",
			fr = "Stashed Loot",
			it = "Stashed Loot",
			pt = "Stashed Loot",
			ru = "Stashed Loot",
			ko = "Stashed Loot",
			cn = "Stashed Loot",
		},
	},
	[445277] = {
		readable = "Hunters Threadspun Cache",
		text = {
			en = "Hunters Threadspun Cache",
			es = "Hunters Threadspun Cache",
			de = "Hunters Threadspun Cache",
			fr = "Hunters Threadspun Cache",
			it = "Hunters Threadspun Cache",
			pt = "Hunters Threadspun Cache",
			ru = "Hunters Threadspun Cache",
			ko = "Hunters Threadspun Cache",
			cn = "Hunters Threadspun Cache",
		},
	},
	[446097] = {
		readable = "Disturbed Soil",
		model = 5319119,
		text = {
			en = "Disturbed Soil",
			es = "Disturbed Soil",
			de = "Disturbed Soil",
			fr = "Disturbed Soil",
			it = "Disturbed Soil",
			pt = "Disturbed Soil",
			ru = "Disturbed Soil",
			ko = "Disturbed Soil",
			cn = "Disturbed Soil",
		},
	},
	[446101] = {
		readable = "Nerubian Offerings",
		text = {
			en = "Nerubian Offerings",
			es = "Nerubian Offerings",
			de = "Nerubian Offerings",
			fr = "Nerubian Offerings",
			it = "Nerubian Offerings",
			pt = "Nerubian Offerings",
			ru = "Nerubian Offerings",
			ko = "Nerubian Offerings",
			cn = "Nerubian Offerings",
		},
	},
	[446135] = {
		readable = "Niffen Stash",
		model = 977074,
		text = {
			en = "Niffen Stash",
			es = "Niffen Stash",
			de = "Niffen Stash",
			fr = "Niffen Stash",
			it = "Niffen Stash",
			pt = "Niffen Stash",
			ru = "Niffen Stash",
			ko = "Niffen Stash",
			cn = "Niffen Stash",
		},
	},
	[446140] = {
		readable = "Missing Scouts Pack",
		text = {
			en = "Missing Scouts Pack",
			es = "Missing Scouts Pack",
			de = "Missing Scouts Pack",
			fr = "Missing Scouts Pack",
			it = "Missing Scouts Pack",
			pt = "Missing Scouts Pack",
			ru = "Missing Scouts Pack",
			ko = "Missing Scouts Pack",
			cn = "Missing Scouts Pack",
		},
	},
	[446299] = {
		readable = "Silk-spun Supplies",
		text = {
			en = "Silk-spun Supplies",
			es = "Silk-spun Supplies",
			de = "Silk-spun Supplies",
			fr = "Silk-spun Supplies",
			it = "Silk-spun Supplies",
			pt = "Silk-spun Supplies",
			ru = "Silk-spun Supplies",
			ko = "Silk-spun Supplies",
			cn = "Silk-spun Supplies",
		},
	},
	[446404] = {
		readable = "Memory Cache",
		text = {
			en = "Memory Cache",
			es = "Memory Cache",
			de = "Memory Cache",
			fr = "Memory Cache",
			it = "Memory Cache",
			pt = "Memory Cache",
			ru = "Memory Cache",
			ko = "Memory Cache",
			cn = "Memory Cache",
		},
	},
	[446419] = {
		readable = "Concealed Contraband",
		text = {
			en = "Concealed Contraband",
			es = "Concealed Contraband",
			de = "Concealed Contraband",
			fr = "Concealed Contraband",
			it = "Concealed Contraband",
			pt = "Concealed Contraband",
			ru = "Concealed Contraband",
			ko = "Concealed Contraband",
			cn = "Concealed Contraband",
		},
	},
	[446421] = {
		readable = "Trapped Trove",
		text = {
			en = "Trapped Trove",
			es = "Trapped Trove",
			de = "Trapped Trove",
			fr = "Trapped Trove",
			it = "Trapped Trove",
			pt = "Trapped Trove",
			ru = "Trapped Trove",
			ko = "Trapped Trove",
			cn = "Trapped Trove",
		},
	},
	[446423] = {
		readable = "Nest Egg",
		text = {
			en = "Nest Egg",
			es = "Nest Egg",
			de = "Nest Egg",
			fr = "Nest Egg",
			it = "Nest Egg",
			pt = "Nest Egg",
			ru = "Nest Egg",
			ko = "Nest Egg",
			cn = "Nest Egg",
		},
	},
	[451595] = {
		readable = "Forgotten Memorial",
		text = {
			en = "Forgotten Memorial",
			es = "Forgotten Memorial",
			de = "Forgotten Memorial",
			fr = "Forgotten Memorial",
			it = "Forgotten Memorial",
			pt = "Forgotten Memorial",
			ru = "Forgotten Memorial",
			ko = "Forgotten Memorial",
			cn = "Forgotten Memorial",
		},
	},
	[451596] = {
		readable = "Forgotten Memorial",
		text = {
			en = "Forgotten Memorial",
			es = "Forgotten Memorial",
			de = "Forgotten Memorial",
			fr = "Forgotten Memorial",
			it = "Forgotten Memorial",
			pt = "Forgotten Memorial",
			ru = "Forgotten Memorial",
			ko = "Forgotten Memorial",
			cn = "Forgotten Memorial",
		},
	},
	[451597] = {
		readable = "Forgotten Memorial",
		text = {
			en = "Forgotten Memorial",
			es = "Forgotten Memorial",
			de = "Forgotten Memorial",
			fr = "Forgotten Memorial",
			it = "Forgotten Memorial",
			pt = "Forgotten Memorial",
			ru = "Forgotten Memorial",
			ko = "Forgotten Memorial",
			cn = "Forgotten Memorial",
		},
	},
	[451599] = {
		readable = "Forgotten Memorial",
		text = {
			en = "Forgotten Memorial",
			es = "Forgotten Memorial",
			de = "Forgotten Memorial",
			fr = "Forgotten Memorial",
			it = "Forgotten Memorial",
			pt = "Forgotten Memorial",
			ru = "Forgotten Memorial",
			ko = "Forgotten Memorial",
			cn = "Forgotten Memorial",
		},
	},
	[451600] = {
		readable = "Forgotten Memorial",
		text = {
			en = "Forgotten Memorial",
			es = "Forgotten Memorial",
			de = "Forgotten Memorial",
			fr = "Forgotten Memorial",
			it = "Forgotten Memorial",
			pt = "Forgotten Memorial",
			ru = "Forgotten Memorial",
			ko = "Forgotten Memorial",
			cn = "Forgotten Memorial",
		},
	},
	[451601] = {
		readable = "Forgotten Memorial",
		text = {
			en = "Forgotten Memorial",
			es = "Forgotten Memorial",
			de = "Forgotten Memorial",
			fr = "Forgotten Memorial",
			it = "Forgotten Memorial",
			pt = "Forgotten Memorial",
			ru = "Forgotten Memorial",
			ko = "Forgotten Memorial",
			cn = "Forgotten Memorial",
		},
	},
	[451602] = {
		readable = "Forgotten Memorial",
		text = {
			en = "Forgotten Memorial",
			es = "Forgotten Memorial",
			de = "Forgotten Memorial",
			fr = "Forgotten Memorial",
			it = "Forgotten Memorial",
			pt = "Forgotten Memorial",
			ru = "Forgotten Memorial",
			ko = "Forgotten Memorial",
			cn = "Forgotten Memorial",
		},
	},
	[451603] = {
		readable = "Forgotten Memorial",
		text = {
			en = "Forgotten Memorial",
			es = "Forgotten Memorial",
			de = "Forgotten Memorial",
			fr = "Forgotten Memorial",
			it = "Forgotten Memorial",
			pt = "Forgotten Memorial",
			ru = "Forgotten Memorial",
			ko = "Forgotten Memorial",
			cn = "Forgotten Memorial",
		},
	},
	[452708] = {
		readable = "\"Weaving Supplies\"",
		text = {
			en = "\"Weaving Supplies\"",
			es = "\"Weaving Supplies\"",
			de = "\"Weaving Supplies\"",
			fr = "\"Weaving Supplies\"",
			it = "\"Weaving Supplies\"",
			pt = "\"Weaving Supplies\"",
			ru = "\"Weaving Supplies\"",
			ko = "\"Weaving Supplies\"",
			cn = "\"Weaving Supplies\"",
		},
	},
	[454342] = {
		readable = "Thimble's Cache",
		text = {
			en = "Thimble's Cache",
			es = "Thimble's Cache",
			de = "Thimble's Cache",
			fr = "Thimble's Cache",
			it = "Thimble's Cache",
			pt = "Thimble's Cache",
			ru = "Thimble's Cache",
			ko = "Thimble's Cache",
			cn = "Thimble's Cache",
		},
	},
	[455720] = {
		readable = "DELVER'S CALL: Tak-Rethan Abyss",
		text = {
			en = "DELVER'S CALL: Tak-Rethan Abyss",
			es = "DELVER'S CALL: Tak-Rethan Abyss",
			de = "DELVER'S CALL: Tak-Rethan Abyss",
			fr = "DELVER'S CALL: Tak-Rethan Abyss",
			it = "DELVER'S CALL: Tak-Rethan Abyss",
			pt = "DELVER'S CALL: Tak-Rethan Abyss",
			ru = "DELVER'S CALL: Tak-Rethan Abyss",
			ko = "DELVER'S CALL: Tak-Rethan Abyss",
			cn = "DELVER'S CALL: Tak-Rethan Abyss",
		},
	},
})
do ObjectDB[objectID] = objectData; end