local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[455994] = {
		readable = "Emptied Venom Canister",
		text = {
			en = "Emptied Venom Canister",
			es = "Emptied Venom Canister",
			de = "Emptied Venom Canister",
			fr = "Emptied Venom Canister",
			it = "Emptied Venom Canister",
			pt = "Emptied Venom Canister",
			ru = "Emptied Venom Canister",
			ko = "Emptied Venom Canister",
			cn = "Emptied Venom Canister",
		},
	},
	[455995] = {
		readable = "Puppeted Mechanical Spider",
		model = 242794,
		text = {
			en = "Puppeted Mechanical Spider",
			es = "Puppeted Mechanical Spider",
			de = "Puppeted Mechanical Spider",
			fr = "Puppeted Mechanical Spider",
			it = "Puppeted Mechanical Spider",
			pt = "Puppeted Mechanical Spider",
			ru = "Puppeted Mechanical Spider",
			ko = "Puppeted Mechanical Spider",
			cn = "Puppeted Mechanical Spider",
		},
	},
	[455996] = {
		readable = "Arathi Safety Gloves",
		text = {
			en = "Arathi Safety Gloves",
			es = "Arathi Safety Gloves",
			de = "Arathi Safety Gloves",
			fr = "Arathi Safety Gloves",
			it = "Arathi Safety Gloves",
			pt = "Arathi Safety Gloves",
			ru = "Arathi Safety Gloves",
			ko = "Arathi Safety Gloves",
			cn = "Arathi Safety Gloves",
		},
	},
	[455997] = {
		readable = "Holy Firework Dud",
		text = {
			en = "Holy Firework Dud",
			es = "Holy Firework Dud",
			de = "Holy Firework Dud",
			fr = "Holy Firework Dud",
			it = "Holy Firework Dud",
			pt = "Holy Firework Dud",
			ru = "Holy Firework Dud",
			ko = "Holy Firework Dud",
			cn = "Holy Firework Dud",
		},
	},
	[455998] = {
		readable = "Earthen Construct Blueprints",
		text = {
			en = "Earthen Construct Blueprints",
			es = "Earthen Construct Blueprints",
			de = "Earthen Construct Blueprints",
			fr = "Earthen Construct Blueprints",
			it = "Earthen Construct Blueprints",
			pt = "Earthen Construct Blueprints",
			ru = "Earthen Construct Blueprints",
			ko = "Earthen Construct Blueprints",
			cn = "Earthen Construct Blueprints",
		},
	},
	[455999] = {
		readable = "Inert Mining Bomb",
		text = {
			en = "Inert Mining Bomb",
			es = "Inert Mining Bomb",
			de = "Inert Mining Bomb",
			fr = "Inert Mining Bomb",
			it = "Inert Mining Bomb",
			pt = "Inert Mining Bomb",
			ru = "Inert Mining Bomb",
			ko = "Inert Mining Bomb",
			cn = "Inert Mining Bomb",
		},
	},
	[456000] = {
		readable = "Dornogal Spectacles",
		text = {
			en = "Dornogal Spectacles",
			es = "Dornogal Spectacles",
			de = "Dornogal Spectacles",
			fr = "Dornogal Spectacles",
			it = "Dornogal Spectacles",
			pt = "Dornogal Spectacles",
			ru = "Dornogal Spectacles",
			ko = "Dornogal Spectacles",
			cn = "Dornogal Spectacles",
		},
	},
})
do ObjectDB[objectID] = objectData; end