local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[182484] = {
		readable = "Warmaul Prison",
		text = {
			en = "Warmaul Prison",
			-- TODO: de = "",
			es = "Prisión de Mazo de Guerra",
			mx = "Prisión de Mazo de Guerra",
			fr = "Prison des Cogneguerre",
			-- TODO: it = "",
			-- TODO: pt = "",
			ru = "Тюрьма Боевого Молота",
			-- TODO: ko = "",
			cn = "战槌监狱",
			-- TODO: tw = "",
		},
	},
	[182486] = {
		readable = "Warmaul Prison",
		text = {
			en = "Warmaul Prison",
			-- TODO: de = "",
			es = "Prisión de Mazo de Guerra",
			mx = "Prisión de Mazo de Guerra",
			fr = "Prison des Cogneguerre",
			-- TODO: it = "",
			-- TODO: pt = "",
			ru = "Тюрьма Боевого Молота",
			-- TODO: ko = "",
			cn = "战槌监狱",
			-- TODO: tw = "",
		},
	},
	[182487] = {
		readable = "Warmaul Prison",
		text = {
			en = "Warmaul Prison",
			-- TODO: de = "",
			es = "Prisión de Mazo de Guerra",
			mx = "Prisión de Mazo de Guerra",
			fr = "Prison des Cogneguerre",
			-- TODO: it = "",
			-- TODO: pt = "",
			ru = "Тюрьма Боевого Молота",
			-- TODO: ko = "",
			cn = "战槌监狱",
			-- TODO: tw = "",
		},
	},
	[182488] = {
		readable = "Warmaul Prison",
		text = {
			en = "Warmaul Prison",
			-- TODO: de = "",
			es = "Prisión de Mazo de Guerra",
			mx = "Prisión de Mazo de Guerra",
			fr = "Prison des Cogneguerre",
			-- TODO: it = "",
			-- TODO: pt = "",
			ru = "Тюрьма Боевого Молота",
			-- TODO: ko = "",
			cn = "战槌监狱",
			-- TODO: tw = "",
		},
	},
	[182489] = {
		readable = "Warmaul Prison",
		text = {
			en = "Warmaul Prison",
			-- TODO: de = "",
			es = "Prisión de Mazo de Guerra",
			mx = "Prisión de Mazo de Guerra",
			fr = "Prison des Cogneguerre",
			-- TODO: it = "",
			-- TODO: pt = "",
			ru = "Тюрьма Боевого Молота",
			-- TODO: ko = "",
			cn = "战槌监狱",
			-- TODO: tw = "",
		},
	},
	[182490] = {
		readable = "Warmaul Prison",
		text = {
			en = "Warmaul Prison",
			-- TODO: de = "",
			es = "Prisión de Mazo de Guerra",
			mx = "Prisión de Mazo de Guerra",
			fr = "Prison des Cogneguerre",
			-- TODO: it = "",
			-- TODO: pt = "",
			ru = "Тюрьма Боевого Молота",
			-- TODO: ko = "",
			cn = "战槌监狱",
			-- TODO: tw = "",
		},
	},
	[182491] = {
		readable = "Warmaul Prison",
		text = {
			en = "Warmaul Prison",
			-- TODO: de = "",
			es = "Prisión de Mazo de Guerra",
			mx = "Prisión de Mazo de Guerra",
			fr = "Prison des Cogneguerre",
			-- TODO: it = "",
			-- TODO: pt = "",
			ru = "Тюрьма Боевого Молота",
			-- TODO: ko = "",
			cn = "战槌监狱",
			-- TODO: tw = "",
		},
	},
	[182492] = {
		readable = "Warmaul Prison",
		text = {
			en = "Warmaul Prison",
			-- TODO: de = "",
			es = "Prisión de Mazo de Guerra",
			mx = "Prisión de Mazo de Guerra",
			fr = "Prison des Cogneguerre",
			-- TODO: it = "",
			-- TODO: pt = "",
			ru = "Тюрьма Боевого Молота",
			-- TODO: ko = "",
			cn = "战槌监狱",
			-- TODO: tw = "",
		},
	},
	[182493] = {
		readable = "Warmaul Prison",
		text = {
			en = "Warmaul Prison",
			-- TODO: de = "",
			es = "Prisión de Mazo de Guerra",
			mx = "Prisión de Mazo de Guerra",
			fr = "Prison des Cogneguerre",
			-- TODO: it = "",
			-- TODO: pt = "",
			ru = "Тюрьма Боевого Молота",
			-- TODO: ko = "",
			cn = "战槌监狱",
			-- TODO: tw = "",
		},
	},
	[182494] = {
		readable = "Warmaul Prison",
		text = {
			en = "Warmaul Prison",
			-- TODO: de = "",
			es = "Prisión de Mazo de Guerra",
			mx = "Prisión de Mazo de Guerra",
			fr = "Prison des Cogneguerre",
			-- TODO: it = "",
			-- TODO: pt = "",
			ru = "Тюрьма Боевого Молота",
			-- TODO: ko = "",
			cn = "战槌监狱",
			-- TODO: tw = "",
		},
	},
	[182495] = {
		readable = "Warmaul Prison",
		text = {
			en = "Warmaul Prison",
			-- TODO: de = "",
			es = "Prisión de Mazo de Guerra",
			mx = "Prisión de Mazo de Guerra",
			fr = "Prison des Cogneguerre",
			-- TODO: it = "",
			-- TODO: pt = "",
			ru = "Тюрьма Боевого Молота",
			-- TODO: ko = "",
			cn = "战槌监狱",
			-- TODO: tw = "",
		},
	},
	[182496] = {
		readable = "Warmaul Prison",
		text = {
			en = "Warmaul Prison",
			-- TODO: de = "",
			es = "Prisión de Mazo de Guerra",
			mx = "Prisión de Mazo de Guerra",
			fr = "Prison des Cogneguerre",
			-- TODO: it = "",
			-- TODO: pt = "",
			ru = "Тюрьма Боевого Молота",
			-- TODO: ko = "",
			cn = "战槌监狱",
			-- TODO: tw = "",
		},
	},
	[182497] = {
		readable = "Warmaul Prison",
		text = {
			en = "Warmaul Prison",
			-- TODO: de = "",
			es = "Prisión de Mazo de Guerra",
			mx = "Prisión de Mazo de Guerra",
			fr = "Prison des Cogneguerre",
			-- TODO: it = "",
			-- TODO: pt = "",
			ru = "Тюрьма Боевого Молота",
			-- TODO: ko = "",
			cn = "战槌监狱",
			-- TODO: tw = "",
		},
	},
	[182498] = {
		readable = "Warmaul Prison",
		text = {
			en = "Warmaul Prison",
			-- TODO: de = "",
			es = "Prisión de Mazo de Guerra",
			mx = "Prisión de Mazo de Guerra",
			fr = "Prison des Cogneguerre",
			-- TODO: it = "",
			-- TODO: pt = "",
			ru = "Тюрьма Боевого Молота",
			-- TODO: ko = "",
			cn = "战槌监狱",
			-- TODO: tw = "",
		},
	},
	[182499] = {
		readable = "Warmaul Prison",
		text = {
			en = "Warmaul Prison",
			-- TODO: de = "",
			es = "Prisión de Mazo de Guerra",
			mx = "Prisión de Mazo de Guerra",
			fr = "Prison des Cogneguerre",
			-- TODO: it = "",
			-- TODO: pt = "",
			ru = "Тюрьма Боевого Молота",
			-- TODO: ko = "",
			cn = "战槌监狱",
			-- TODO: tw = "",
		},
	},
	[182500] = {
		readable = "Warmaul Prison",
		text = {
			en = "Warmaul Prison",
			-- TODO: de = "",
			es = "Prisión de Mazo de Guerra",
			mx = "Prisión de Mazo de Guerra",
			fr = "Prison des Cogneguerre",
			-- TODO: it = "",
			-- TODO: pt = "",
			ru = "Тюрьма Боевого Молота",
			-- TODO: ko = "",
			cn = "战槌监狱",
			-- TODO: tw = "",
		},
	},
	[182501] = {
		readable = "Warmaul Prison",
		text = {
			en = "Warmaul Prison",
			-- TODO: de = "",
			es = "Prisión de Mazo de Guerra",
			mx = "Prisión de Mazo de Guerra",
			fr = "Prison des Cogneguerre",
			-- TODO: it = "",
			-- TODO: pt = "",
			ru = "Тюрьма Боевого Молота",
			-- TODO: ko = "",
			cn = "战槌监狱",
			-- TODO: tw = "",
		},
	},
	[182502] = {
		readable = "Warmaul Prison",
		text = {
			en = "Warmaul Prison",
			-- TODO: de = "",
			es = "Prisión de Mazo de Guerra",
			mx = "Prisión de Mazo de Guerra",
			fr = "Prison des Cogneguerre",
			-- TODO: it = "",
			-- TODO: pt = "",
			ru = "Тюрьма Боевого Молота",
			-- TODO: ko = "",
			cn = "战槌监狱",
			-- TODO: tw = "",
		},
	},
	[182503] = {
		readable = "Warmaul Prison",
		text = {
			en = "Warmaul Prison",
			-- TODO: de = "",
			es = "Prisión de Mazo de Guerra",
			mx = "Prisión de Mazo de Guerra",
			fr = "Prison des Cogneguerre",
			-- TODO: it = "",
			-- TODO: pt = "",
			ru = "Тюрьма Боевого Молота",
			-- TODO: ko = "",
			cn = "战槌监狱",
			-- TODO: tw = "",
		},
	},
	[182504] = {
		readable = "Warmaul Prison",
		text = {
			en = "Warmaul Prison",
			-- TODO: de = "",
			es = "Prisión de Mazo de Guerra",
			mx = "Prisión de Mazo de Guerra",
			fr = "Prison des Cogneguerre",
			-- TODO: it = "",
			-- TODO: pt = "",
			ru = "Тюрьма Боевого Молота",
			-- TODO: ko = "",
			cn = "战槌监狱",
			-- TODO: tw = "",
		},
	},
	[185890] = {
		readable = "Apexis Relic",
		text = {
			en = "Apexis Relic",
			de = "Apexisrelikt",
			es = "Reliquia apexis",
			mx = "Reliquia de ápices",
			fr = "Relique apogide",
			it = "Reliquia Apexis",
			pt = "Relíquia Apexis",
			ru = "Апекситовая реликвия",
			ko = "에펙시스 유물",
			cn = "埃匹希斯圣物",
			tw = "頂尖聖物",
		},
	},
})
do ObjectDB[objectID] = objectData; end
