-- This file is dynamically generated by Parser! DO NOT MODIFIY IT MANUALLY!
select(2, ...).RaceDB=
{
	["Blood Elf"] = 10,
	["BloodElf"] = 10,
	["Dark Iron Dwarf"] = 34,
	["DarkIronDwarf"] = 34,
	["Dracthyr"] = {
		["Alliance"] = 52,
		["Horde"] = 70,
	},
	["Draenei"] = 11,
	["Dwarf"] = 3,
	["Earthen"] = {
		["Alliance"] = 85,
		["Horde"] = 84,
	},
	["Gnome"] = 7,
	["Goblin"] = 9,
	["Highmountain Tauren"] = 28,
	["HighmountainTauren"] = 28,
	["Human"] = 1,
	["ID"] = {
		[1] = {
			["faction"] = 1,
			["gender"] = {
				[2] = {
					["icon"] = 236448,
				},
				[3] = {
					["icon"] = 236447,
				},
			},
		},
		[2] = {
			["faction"] = 2,
			["gender"] = {
				[2] = {
					["icon"] = 236452,
				},
				[3] = {
					["icon"] = 236451,
				},
			},
		},
		[3] = {
			["faction"] = 1,
			["gender"] = {
				[2] = {
					["icon"] = 236444,
				},
				[3] = {
					["icon"] = 236443,
				},
			},
		},
		[4] = {
			["faction"] = 1,
			["gender"] = {
				[2] = {
					["icon"] = 236450,
				},
				[3] = {
					["icon"] = 236449,
				},
			},
		},
		[5] = {
			["faction"] = 2,
			["gender"] = {
				[2] = {
					["icon"] = 236458,
				},
				[3] = {
					["icon"] = 236457,
				},
			},
		},
		[6] = {
			["faction"] = 2,
			["gender"] = {
				[2] = {
					["icon"] = 236454,
				},
				[3] = {
					["icon"] = 236453,
				},
			},
		},
		[7] = {
			["faction"] = 1,
			["gender"] = {
				[2] = {
					["icon"] = 236446,
				},
				[3] = {
					["icon"] = 236445,
				},
			},
		},
		[8] = {
			["faction"] = 2,
			["gender"] = {
				[2] = {
					["icon"] = 236456,
				},
				[3] = {
					["icon"] = 236455,
				},
			},
		},
		[9] = {
			["faction"] = 2,
			["gender"] = {
				[2] = {
					["icon"] = 463874,
				},
				[3] = {
					["icon"] = 632354,
				},
			},
		},
		[10] = {
			["faction"] = 2,
			["gender"] = {
				[2] = {
					["icon"] = 236440,
				},
				[3] = {
					["icon"] = 236439,
				},
			},
		},
		[11] = {
			["faction"] = 1,
			["gender"] = {
				[2] = {
					["icon"] = 236442,
				},
				[3] = {
					["icon"] = 236441,
				},
			},
		},
		[22] = {
			["faction"] = 1,
			["icon"] = 463876,
		},
		[24] = {
			["icon"] = 626190,
		},
		[25] = {
			["faction"] = 1,
			["icon"] = 626190,
		},
		[26] = {
			["faction"] = 2,
			["icon"] = 626190,
		},
		[27] = {
			["faction"] = 2,
			["icon"] = 1786421,
		},
		[28] = {
			["faction"] = 2,
			["icon"] = 1786419,
		},
		[29] = {
			["faction"] = 1,
			["icon"] = 1786422,
		},
		[30] = {
			["faction"] = 1,
			["icon"] = 1786420,
		},
		[31] = {
			["faction"] = 2,
			["icon"] = 1851465,
		},
		[32] = {
			["faction"] = 1,
			["icon"] = 2447785,
		},
		[34] = {
			["faction"] = 1,
			["icon"] = 1851464,
		},
		[35] = {
			["faction"] = 2,
			["icon"] = 3208033,
		},
		[36] = {
			["faction"] = 2,
			["icon"] = 1989713,
		},
		[37] = {
			["faction"] = 1,
			["icon"] = 3208032,
		},
		[52] = {
			["faction"] = 1,
			["icon"] = 4696175,
		},
		[70] = {
			["faction"] = 2,
			["icon"] = 4696175,
		},
		[84] = {
			["faction"] = 2,
			["icon"] = 5930319,
		},
		[85] = {
			["faction"] = 1,
			["icon"] = 5930319,
		},
	},
	["Kul Tiran"] = 32,
	["KulTiran"] = 32,
	["Kul'Tiran"] = 32,
	["Lightforged Draenei"] = 30,
	["LightforgedDraenei"] = 30,
	["Mag har Orc"] = 36,
	["Mag'har Orc"] = 36,
	["MagharOrc"] = 36,
	["Mechagnome"] = 37,
	["Night Elf"] = 4,
	["Nightborne"] = 27,
	["NightElf"] = 4,
	["Orc"] = 2,
	["Pandaren"] = {
		["Alliance"] = 25,
		["Horde"] = 26,
		["Neutral"] = 24,
	},
	["Scourge"] = 5,
	["Tauren"] = 6,
	["Troll"] = 8,
	["Undead"] = 5,
	["Void Elf"] = 29,
	["VoidElf"] = 29,
	["Vulpera"] = 35,
	["Worgen"] = 22,
	["Zandalari Troll"] = 31,
	["ZandalariTroll"] = 31,
}