root("ObjectDB", {
	[241641] = {
		readable = "Foxflower",
		model = 1303238,
		text = {
			en = "Foxflower",
			es = "Flor de raposa",
			de = "Fuchsblume",
			fr = "Vulpille",
			it = "Fiorvolpe",
			pt = "Flor-de-raposa",
			ru = "Лисоцвет",
			ko = "여우꽃",
			cn = "狐尾花",
		},
	},
	[244774] = {
		readable = "Aethril",
		model = 1391548,
		text = {
			en = "Aethril",
			es = "Aethril",
			de = "Aethril",
			fr = "Aethril",
			it = "Aethril",
			pt = "Aethril",
			ru = "Айтрил",
			ko = "에이트릴",
			cn = "安瑟瑞尔花",
		},
	},
	[244775] = {
		readable = "Dreamleaf",
		model = 1369688,
		text = {
			en = "Dreamleaf",
			es = "Frondasueño",
			de = "Traumlaub",
			fr = "Songefeuille",
			it = "Erbonirica",
			pt = "Folha-de-sonho",
			ru = "Грезолист",
			ko = "꿈잎사귀",
			cn = "入梦叶",
		},
	},
	[244776] = {
		readable = "Dreamleaf",
		model = 1370949,
		text = {
			en = "Dreamleaf",
			es = "Frondasueño",
			de = "Traumlaub",
			fr = "Songefeuille",
			it = "Erbonirica",
			pt = "Folha-de-sonho",
			ru = "Грезолист",
			ko = "꿈잎사귀",
			cn = "入梦叶",
		},
	},
	[244777] = {
		readable = "Fjarnskaggl",
		model = 1282724,
		text = {
			en = "Fjarnskaggl",
			es = "Fjarnskaggl",
			de = "Fjarnskaggl",
			fr = "Fjarnskaggl",
			it = "Fjarnskaggl",
			pt = "Fjarnskaggl",
			ru = "Фьярнскаггл",
			ko = "피아른스카글",
			cn = "夏斯卡格草",
		},
	},
	[244778] = {
		readable = "Starlight Rose",
		model = 1357601,
		text = {
			en = "Starlight Rose",
			es = "Rosa luz estelar",
			de = "Sternlichtrose",
			fr = "Rose lumétoile",
			it = "Rosa Lucestellare",
			pt = "Rosa-da-luz-estelar",
			ru = "Звездная роза",
			ko = "별빛 장미",
			cn = "星光玫瑰",
		},
	},
	[244786] = {
		readable = "Felwort",
		model = 1284877,
		text = {
			en = "Felwort",
			es = "Matojo vil",
			de = "Teufelswurz",
			fr = "Gangrèche",
			it = "Vilpianta",
			pt = "Maltevil",
			ru = "Зверобой Скверны",
			ko = "[Felwort]",
			cn = "[Felwort]",
		},
	},
	[245324] = {
		readable = "Rich Leystone Deposit",
		model = 1244490,
		text = {
			en = "Rich Leystone Deposit",
			es = "Depósito rico en piedra Ley",
			de = "Reiches Leysteinvorkommen",
			fr = "Riche gisement de tellurium",
			it = "Deposito Ricco di Fagliaroccia",
			pt = "Depósito Rico de Pedra de Meridiano",
			ru = "Богатые залежи силового камня",
			ko = "풍부한 지맥석 광맥",
			cn = "富魔石矿脉",
		},
	},
	[245325] = {
		readable = "Rich Felslate Deposit",
		model = 1244488,
		text = {
			en = "Rich Felslate Deposit",
			es = "Depósito rico en pizarra vil",
			de = "Reiches Teufelsschiefervorkommen",
			fr = "Riche gisement de gangreschiste",
			it = "Deposito Ricco di Vilardesia",
			pt = "Depósito Rico de Vilardósia",
			ru = "Богатые залежи сланца Скверны",
			ko = "풍부한 지옥판암 광맥",
			cn = "富邪能页岩矿脉",
		},
	},
	[247999] = {
		readable = "Felwort",
		model = 1284877,
		text = {
			en = "Felwort",
			es = "Matojo vil",
			de = "Teufelswurz",
			fr = "Gangrèche",
			it = "Vilpianta",
			pt = "Maltevil",
			ru = "Зверобой Скверны",
			ko = "지옥나물",
			cn = "邪能球茎",
		},
	},
	[248000] = {
		readable = "Felwort",
		model = 1284877,
		text = {
			en = "Felwort",
			es = "Matojo vil",
			de = "Teufelswurz",
			fr = "Gangrèche",
			it = "Vilpianta",
			pt = "Maltevil",
			ru = "Зверобой Скверны",
			ko = "[Felwort]",
			cn = "[Felwort]",
		},
	},
	[248001] = {
		readable = "Felwort",
		model = 1284877,
		text = {
			en = "Felwort",
			es = "Matojo vil",
			de = "Teufelswurz",
			fr = "Gangrèche",
			it = "Vilpianta",
			pt = "Maltevil",
			ru = "Зверобой Скверны",
			ko = "[Felwort]",
			cn = "邪能球茎",
		},
	},
	[248002] = {
		readable = "Felwort",
		model = 1284877,
		text = {
			en = "Felwort",
			es = "Matojo vil",
			de = "Teufelswurz",
			fr = "Gangrèche",
			it = "Vilpianta",
			pt = "Maltevil",
			ru = "Зверобой Скверны",
			ko = "지옥나물",
			cn = "邪能球茎",
		},
	},
	[248003] = {
		readable = "Felwort",
		model = 1284877,
		text = {
			en = "Felwort",
			es = "Matojo vil",
			de = "Teufelswurz",
			fr = "Gangrèche",
			it = "Vilpianta",
			pt = "Maltevil",
			ru = "Зверобой Скверны",
			ko = "지옥나물",
			cn = "[Felwort]",
		},
	},
	[248004] = {
		readable = "Felwort",
		model = 1284877,
		text = {
			en = "Felwort",
			es = "Matojo vil",
			de = "Teufelswurz",
			fr = "Gangrèche",
			it = "Vilpianta",
			pt = "Maltevil",
			ru = "Зверобой Скверны",
			ko = "[Felwort]",
			cn = "[Felwort]",
		},
	},
	[248005] = {
		readable = "Felwort",
		model = 1284877,
		text = {
			en = "Felwort",
			es = "Matojo vil",
			de = "Teufelswurz",
			fr = "Gangrèche",
			it = "Vilpianta",
			pt = "Maltevil",
			ru = "Зверобой Скверны",
			ko = "[Felwort]",
			cn = "[Felwort]",
		},
	},
	[248006] = {
		readable = "Felwort",
		model = 1284877,
		text = {
			en = "Felwort",
			es = "Matojo vil",
			de = "Teufelswurz",
			fr = "Gangrèche",
			it = "Vilpianta",
			pt = "Maltevil",
			ru = "Зверобой Скверны",
			ko = "지옥나물",
			cn = "[Felwort]",
		},
	},
	[248007] = {
		readable = "Felwort",
		model = 1284877,
		text = {
			en = "Felwort",
			es = "Matojo vil",
			de = "Teufelswurz",
			fr = "Gangrèche",
			it = "Vilpianta",
			pt = "Maltevil",
			ru = "Зверобой Скверны",
			ko = "지옥나물",
			cn = "[Felwort]",
		},
	},
	[248008] = {
		readable = "Felwort",
		model = 1284877,
		text = {
			en = "Felwort",
			es = "Matojo vil",
			de = "Teufelswurz",
			fr = "Gangrèche",
			it = "Vilpianta",
			pt = "Maltevil",
			ru = "Зверобой Скверны",
			ko = "[Felwort]",
			cn = "邪能球茎",
		},
	},
	[248009] = {
		readable = "Felwort",
		model = 1284877,
		text = {
			en = "Felwort",
			es = "Matojo vil",
			de = "Teufelswurz",
			fr = "Gangrèche",
			it = "Vilpianta",
			pt = "Maltevil",
			ru = "Зверобой Скверны",
			ko = "[Felwort]",
			cn = "[Felwort]",
		},
	},
	[248010] = {
		readable = "Felwort",
		model = 1284877,
		text = {
			en = "Felwort",
			es = "Matojo vil",
			de = "Teufelswurz",
			fr = "Gangrèche",
			it = "Vilpianta",
			pt = "Maltevil",
			ru = "Зверобой Скверны",
			ko = "지옥나물",
			cn = "[Felwort]",
		},
	},
	[248011] = {
		readable = "Felwort",
		model = 1284877,
		text = {
			en = "Felwort",
			es = "Hierba vil",
			de = "Teufelswurz",
			fr = "Gangrèche",
			it = "Vilpianta",
			pt = "Maltevil",
			ru = "Зверобой Скверны",
			ko = "[Felwort]",
			cn = "邪能球茎",
		},
	},
	[248012] = {
		readable = "Felwort",
		model = 1284877,
		text = {
			en = "Felwort",
			es = "Matojo vil",
			de = "Teufelswurz",
			fr = "Gangrèche",
			it = "Vilpianta",
			pt = "Maltevil",
			ru = "Зверобой Скверны",
			ko = "지옥나물",
			cn = "邪能球茎",
		},
	},
	[252404] = {
		readable = "Felwort",
		model = 1284877,
		text = {
			en = "Felwort",
			es = "Matojo vil",
			de = "Teufelswurz",
			fr = "Gangrèche",
			it = "Vilpianta",
			pt = "Maltevil",
			ru = "Зверобой Скверны",
			ko = "[Felwort]",
			cn = "[Felwort]",
		},
	},
	[272778] = {
		readable = "Rich Empyrium Deposit",
		model = 1692857,
		text = {
			en = "Rich Empyrium Deposit",
			es = "Depósito rico en empirium",
			de = "Reiches Empyriumvorkommen",
			fr = "Riche gisement d'empyrium",
			it = "Deposito Ricco d'Empirio",
			pt = "Depósito de Empirita Abundante",
			ru = "Богатые залежи эмпиреита",
			ko = "풍부한 창천석 광맥",
			cn = "富天界金矿脉",
		},
	},
	[272782] = {
		readable = "Astral Glory",
		model = 1685295,
		text = {
			en = "Astral Glory",
			es = "Gloria astral",
			de = "Astralwinde",
			fr = "Astralée",
			it = "Gloria Astrale",
			pt = "Glória-astral",
			ru = "Астральный вьюнок",
			ko = "천공의 영광",
			cn = "星辰之耀",
		},
	},
	[273052] = {
		readable = "Fel-Encrusted Herb",
		model = 1616103,
		text = {
			en = "Fel-Encrusted Herb",
			es = "Hierba con costra vil",
			de = "Teufelsverkrustetes Kraut",
			fr = "Herbe incrustée de corruption",
			it = "Erba Vilincrostata",
			pt = "Erva Incrustada de Vileza",
			ru = "Покрытая Скверной трава",
			ko = "지옥 마력으로 덮인 약초",
			cn = "被邪能包裹的草药",
		},
	},
	[273053] = {
		readable = "Fel-Encrusted Herb Cluster",
		model = 1616102,
		text = {
			en = "Fel-Encrusted Herb Cluster",
			es = "Manojo de hierba con costra vil",
			de = "Teufelsverkrustetes Kräuterbüschel",
			fr = "Touffe d’herbe incrustée de corruption",
			it = "Fascio d'Erba Vilincrostata",
			pt = "Feixe de Ervas Incrustadas de Vileza",
			ru = "Пучок покрытой Скверной травы",
			ko = "지옥 마력으로 덮인 약초 덤불",
			cn = "被邪能包裹的草药丛",
		},
	},
	[276234] = {
		readable = "Riverbud",
		model = 1784467,
		text = {
			en = "Riverbud",
			es = "Brotarrío",
			de = "Flussknospe",
			fr = "Rivebulbe",
			it = "Baccello Fluviale",
			pt = "Broto-do-rio",
			ru = "Речной горох",
			ko = "강봉오리",
			cn = "流波花苞",
		},
	},
	[276236] = {
		readable = "Star Moss",
		model = 1794519,
		text = {
			en = "Star Moss",
			es = "Musgo estelar",
			de = "Sternmoos",
			fr = "Mousse étoilée",
			it = "Muschio Stellare",
			pt = "Musgo-estrela",
			ru = "Звездный мох",
			ko = "별이끼",
			cn = "星光苔",
		},
	},
	[276237] = {
		readable = "Akunda's Bite",
		model = 1785284,
		text = {
			en = "Akunda's Bite",
			es = "Mordisco de Akunda",
			de = "Akundas Biss",
			fr = "Mâche d’Akunda",
			it = "Morso di Akunda",
			pt = "Mordida de Akunda",
			ru = "Укус Акунды",
			ko = "아쿤다의 이빨",
			cn = "阿昆达之噬",
		},
	},
	[276238] = {
		readable = "Winter's Kiss",
		model = 1780102,
		text = {
			en = "Winter's Kiss",
			es = "Beso gélido",
			de = "Winterkuss",
			fr = "Bise-d’hiver",
			it = "Bacio dell'Inverno",
			pt = "Beijo-do-inverno",
			ru = "Поцелуй зимы",
			ko = "겨울의 입맞춤",
			cn = "凛冬之吻",
		},
	},
	[276239] = {
		readable = "Siren's Sting",
		model = 1882354,
		text = {
			en = "Siren's Sting",
			es = "Picadura de sirena",
			de = "Sirenendorn",
			fr = "Épine de sirène",
			it = "Pruno di Sirena",
			pt = "Picada da Sereia",
			ru = "Укус сирены",
			ko = "세이렌의 맹독약초",
			cn = "海妖之刺",
		},
	},
	[276240] = {
		readable = "Sea Stalks",
		model = 1890602,
		text = {
			en = "Sea Stalks",
			es = "Tallomares",
			de = "Meeresstängel",
			fr = "Brins-de-mer",
			it = "Steli Marini",
			pt = "Talo-marinho",
			ru = "Морской стебель",
			ko = "바다 줄기",
			cn = "海潮茎杆",
		},
	},
	[276242] = {
		readable = "Anchor Weed",
		model = 1907780,
		text = {
			en = "Anchor Weed",
			es = "Alga de ancla",
			de = "Ankerkraut",
			fr = "Ancoracée",
			it = "Alga d'Ancora",
			pt = "Erva-ancorina",
			ru = "Якорь-трава",
			ko = "닻풀",
			cn = "锚草",
		},
	},
	[281079] = {
		readable = "Star Moss",
		model = 1794518,
		text = {
			en = "Star Moss",
			es = "Musgo estelar",
			de = "Sternmoos",
			fr = "Mousse étoilée",
			it = "Muschio Stellare",
			pt = "Musgo-estrela",
			ru = "Звездный мох",
			ko = "별이끼",
			cn = "星光苔",
		},
	},
	[281867] = {
		readable = "Star Moss",
		model = 1794521,
		text = {
			en = "Star Moss",
			es = "Musgo estelar",
			de = "Sternmoos",
			fr = "Mousse étoilée",
			it = "Muschio Stellare",
			pt = "Musgo-estrela",
			ru = "Звездный мох",
			ko = "별이끼",
			cn = "星光苔",
		},
	},
	[281868] = {
		readable = "Star Moss",
		model = 1794520,
		text = {
			en = "Star Moss",
			es = "Musgo estelar",
			de = "Sternmoos",
			fr = "Mousse étoilée",
			it = "Muschio Stellare",
			pt = "Musgo-estrela",
			ru = "Звездный мох",
			ko = "별이끼",
			cn = "星光苔",
		},
	},
	[281869] = {
		readable = "Siren's Sting",
		model = 1882352,
		text = {
			en = "Siren's Sting",
			es = "Picadura de sirena",
			de = "Sirenendorn",
			fr = "Épine de sirène",
			it = "Pruno di Sirena",
			pt = "Agulha-de-sereia",
			ru = "Укус сирены",
			ko = "세이렌의 맹독약초",
			cn = "海妖之刺",
		},
	},
	[281870] = {
		readable = "Riverbud",
		model = 1784466,
		text = {
			en = "Riverbud",
			es = "Brotarrío",
			de = "Flussknospe",
			fr = "Rivebulbe",
			it = "Baccello Fluviale",
			pt = "Broto-do-rio",
			ru = "Речной горох",
			ko = "강봉오리",
			cn = "流波花苞",
		},
	},
	[281872] = {
		readable = "Sea Stalks",
		model = 1890600,
		text = {
			en = "Sea Stalks",
			es = "Tallomares",
			de = "Meeresstängel",
			fr = "Brins-de-mer",
			it = "Steli Marini",
			pt = "Talo-marinho",
			ru = "Морской стебель",
			ko = "바다 줄기",
			cn = "海潮茎杆",
		},
	},
	[294125] = {
		readable = "Anchor Weed",
		model = 2108571,
		text = {
			en = "Anchor Weed",
			es = "Alga de ancla",
			de = "Ankerkraut",
			fr = "Ancoracée",
			it = "Alga d'Ancora",
			pt = "Erva-ancorina",
			ru = "Якорь-трава",
			ko = "닻풀",
			cn = "锚草",
		},
	},
	[326598] = {
		readable = "Zin'anthid",
		model = 2563954,
		text = {
			en = "Zin'anthid",
			es = "Zin'anthid",
			de = "Zin'anthide",
			fr = "Zin’anthide",
			it = "Zin'anthid",
			pt = "Zin'antida",
			ru = "Зин'антария",
			ko = "진모래말미꽃",
			cn = "龙眼珊瑚",
		},
	},
	[375241] = {
		readable = "Bubble Poppy",
		model = 4498019,
		text = {
			en = "Bubble Poppy",
			es = "Amapola burbuja",
			de = "Blasenmohn",
			fr = "Pavot à bulle",
			it = "Papavero Bolla",
			pt = "Papoula Borbulhante",
			ru = "Пузырчатый мак",
			ko = "거품 백일홍",
			cn = "泡粟花",
		},
	},
	[375242] = {
		readable = "Titan-Touched Bubble Poppy",
		model = 4498019,
		text = {
			en = "Titan-Touched Bubble Poppy",
			es = "Amapola burbuja tocada por los titanes",
			de = "Titanenberührter Blasenmohn",
			fr = "Pavot à bulle touché par les Titans",
			it = "Papavero Bolla Toccato dai Titani",
			pt = "Papoula Borbulhante Tocada por Titãs",
			ru = "Осененный титанами пузырчатый мак",
			ko = "티탄에 물든 거품 백일홍",
			cn = "泰坦点化的泡粟花",
		},
	},
	[375243] = {
		readable = "Infurious Bubble Poppy",
		model = 4498019,
		text = {
			en = "Infurious Bubble Poppy",
			es = "Amapola burbuja furiosa",
			de = "Wutentbrannter Blasenmohn",
			fr = "Pavot à bulle ardent",
			it = "Papavero Bolla Impetuoso",
			pt = "Papoula Borbulhante em Fúria",
			ru = "Ярый пузырчатый мак",
			ko = "분노의 거품 백일홍",
			cn = "[Infurious Bubble Poppy]",
		},
	},
	[375244] = {
		readable = "Frigid Bubble Poppy",
		model = 4498019,
		text = {
			en = "Frigid Bubble Poppy",
			es = "Amapola burbuja gélida",
			de = "Eisiger Blasenmohn",
			fr = "Pavot à bulle algide",
			it = "Papavero Bolla Gelato",
			pt = "Papoula Borbulhante Frígida",
			ru = "Морозный пузырчатый мак",
			ko = "혹한의 거품 백일홍",
			cn = "冷冽泡粟花",
		},
	},
	[375245] = {
		readable = "Windswept Bubble Poppy",
		model = 4498019,
		text = {
			en = "Windswept Bubble Poppy",
			es = "Amapola burbuja aventada",
			de = "Windgepeitschter Blasenmohn",
			fr = "Pavot à bulle balayé par le vent",
			it = "Papavero Bolla Scompigliato",
			pt = "Papoula Borbulhante Levada pelo Vento",
			ru = "Обветренный пузырчатый мак",
			ko = "바람결 거품 백일홍",
			cn = "啸风泡粟花",
		},
	},
	[375246] = {
		readable = "Decayed Bubble Poppy",
		model = 4498020,
		text = {
			en = "Decayed Bubble Poppy",
			es = "Amapola burbuja descompuesta",
			de = "Verrotteter Blasenmohn",
			fr = "Pavot à bulle décomposé",
			it = "Papavero Bolla Decaduto",
			pt = "Papoula Borbulhante Decrépita",
			ru = "Сгнивший пузырчатый мак",
			ko = "부패한 거품 백일홍",
			cn = "腐朽泡粟花",
		},
	},
	[381154] = {
		readable = "Writhebark",
		model = 4546834,
		text = {
			en = "Writhebark",
			es = "Pino retorcido",
			de = "Krümmrinde",
			fr = "Écorce tordue",
			it = "Scorzatorta",
			pt = "Casca Retorcida",
			ru = "Витая кора",
			ko = "격통껍질",
			cn = "歪扭树皮",
		},
	},
	[381196] = {
		readable = "Titan-Touched Writhebark",
		model = 4546834,
		text = {
			en = "Titan-Touched Writhebark",
			es = "Pino retorcido tocado por los titanes",
			de = "Titanenberührte Krümmrinde",
			fr = "Écorce tordue touchée par les Titans",
			it = "Scorzatorta Toccata dai Titani",
			pt = "Casca Retorcida Tocada pelos Titãs",
			ru = "Осененная титанами витая кора",
			ko = "티탄에 물든 격통껍질",
			cn = "泰坦点化的歪扭树皮",
		},
	},
	[381197] = {
		readable = "Infurious Writhebark",
		model = 4546834,
		text = {
			en = "Infurious Writhebark",
			es = "Pino retorcido furioso",
			de = "Wutentbrannte Krümmrinde",
			fr = "Écorce tordue ardente",
			it = "Scorzatorta Impetuosa",
			pt = "Casca Retorcida em Fúria",
			ru = "Ярая витая кора",
			ko = "분노의 격통껍질",
			cn = "[Infurious Writhebark]",
		},
	},
	[381198] = {
		readable = "Decayed Writhebark",
		model = 4546836,
		text = {
			en = "Decayed Writhebark",
			es = "Pino retorcido descompuesto",
			de = "Verrottete Krümmrinde",
			fr = "Écorce tordue décomposée",
			it = "Scorzatorta Decaduta",
			pt = "Casca Retorcida Decrépita",
			ru = "Сгнившая витая кора",
			ko = "부패한 격통껍질",
			cn = "腐朽歪扭树皮",
		},
	},
	[381199] = {
		readable = "Windswept Writhebark",
		model = 4546834,
		text = {
			en = "Windswept Writhebark",
			es = "Pino retorcido arrastrado por el viento",
			de = "Windgepeitschte Krümmrinde",
			fr = "Écorce tordue balayée par le vent",
			it = "Scorzatorta Scompigliata",
			pt = "Casca Retorcida Levada pelo Vento",
			ru = "Обветренная витая кора",
			ko = "바람결 격통껍질",
			cn = "啸风歪扭树皮",
		},
	},
	[381200] = {
		readable = "Frigid Writhebark",
		model = 4546834,
		text = {
			en = "Frigid Writhebark",
			es = "Pino retorcido gélido",
			de = "Eisige Krümmrinde",
			fr = "Écorce tordue algide",
			it = "Scorzatorta Gelata",
			pt = "Casca Retorcida Frígida",
			ru = "Морозная витая кора",
			ko = "혹한의 격통껍질",
			cn = "冷冽歪扭树皮",
		},
	},
	[381201] = {
		readable = "Frigid Saxifrage",
		model = 4558389,
		text = {
			en = "Frigid Saxifrage",
			es = "Saxifraga gélida",
			de = "Eisiges Steinbrich",
			fr = "Saxifrage algide",
			it = "Sassifraga Gelata",
			pt = "Quebra-pedra Frígida",
			ru = "Ледяная камнеломка",
			ko = "혹한의 다년초",
			cn = "冷冽虎耳草",
		},
	},
	[381202] = {
		readable = "Windswept Saxifrage",
		model = 4558389,
		text = {
			en = "Windswept Saxifrage",
			es = "Saxifraga arrastrada por el viento",
			de = "Windgepeitschtes Steinbrich",
			fr = "Saxifrage balayée par le vent",
			it = "Sassifraga Scompigliata",
			pt = "Quebra-pedra Levada pelo Vento",
			ru = "Обветренная камнеломка",
			ko = "바람결 다년초",
			cn = "啸风虎耳草",
		},
	},
	[381203] = {
		readable = "Decayed Saxifrage",
		model = 4558389,
		text = {
			en = "Decayed Saxifrage",
			es = "Saxifraga descompuesta",
			de = "Verrottetes Steinbrich",
			fr = "Saxifrage décomposée",
			it = "Sassifraga Decaduta",
			pt = "Quebra-pedra Decrépita",
			ru = "Сгнившая камнеломка",
			ko = "부패한 다년초",
			cn = "腐朽虎耳草",
		},
	},
	[381204] = {
		readable = "Infurious Saxifrage",
		model = 4558389,
		text = {
			en = "Infurious Saxifrage",
			es = "Saxifraga furiosa",
			de = "Wutentbranntes Steinbrich",
			fr = "Saxifrage ardente",
			it = "Sassifraga Impetuosa",
			pt = "Quebra-pedra em Fúria",
			ru = "Ярая камнеломка",
			ko = "분노의 다년초",
			cn = "[Infurious Saxifrage]",
		},
	},
	[381205] = {
		readable = "Titan-Touched Saxifrage",
		model = 4558389,
		text = {
			en = "Titan-Touched Saxifrage",
			es = "Saxifraga tocada por los titanes",
			de = "Titanenberührtes Steinbrich",
			fr = "Saxifrage touchée par les Titans",
			it = "Sassifraga Toccata dai Titani",
			pt = "Quebra-pedra Tocada pelos Titãs",
			ru = "Осененная титанами камнеломка",
			ko = "티탄에 물든 다년초",
			cn = "泰坦点化的虎耳草",
		},
	},
	[381207] = {
		readable = "Saxifrage",
		model = 4558389,
		text = {
			en = "Saxifrage",
			es = "Saxifraga",
			de = "Steinbrich",
			fr = "Saxifrage",
			it = "Sassifraga",
			pt = "Quebra-pedra",
			ru = "Камнеломка",
			ko = "다년초",
			cn = "虎耳草",
		},
	},
	[381210] = {
		readable = "Titan-Touched Hochenblume",
		model = 4537051,
		text = {
			en = "Titan-Touched Hochenblume",
			es = "Lumbreflor tocada por los titanes",
			de = "Titanenberührte Hochblume",
			fr = "Hochenblume touchée par les Titans",
			it = "Altofiore Toccato dai Titani",
			pt = "Hochenblume Tocado pelos Titãs",
			ru = "Осененный титанами хоэнвейс",
			ko = "티탄에 물든 장대꽃",
			cn = "泰坦点化的霍亨布墨花",
		},
	},
	[381211] = {
		readable = "Infurious Hochenblume",
		model = 4537051,
		text = {
			en = "Infurious Hochenblume",
			es = "Lumbreflor furiosa",
			de = "Wutentbrannte Hochblume",
			fr = "Hochenblume ardente",
			it = "Altofiore Impetuoso",
			pt = "Hochenblume em Fúria",
			ru = "Ярый хоэнвейс",
			ko = "분노의 장대꽃",
			cn = "[Infurious Hochenblume]",
		},
	},
	[381212] = {
		readable = "Decayed Hochenblume",
		model = 4537264,
		text = {
			en = "Decayed Hochenblume",
			es = "Lumbreflor descompuesta",
			de = "Verrottete Hochblume",
			fr = "Hochenblume décomposée",
			it = "Altofiore Decaduto",
			pt = "Hochenblume Decrépito",
			ru = "Сгнивший хоэнвейс",
			ko = "부패한 장대꽃",
			cn = "腐朽霍亨布墨花",
		},
	},
	[381213] = {
		readable = "Windswept Hochenblume",
		model = 4537051,
		text = {
			en = "Windswept Hochenblume",
			es = "Lumbreflor arrastrada por el viento",
			de = "Windgepeitschte Hochblume",
			fr = "Hochenblume balayée par le vent",
			it = "Altofiore Scompigliato",
			pt = "Hochenblume Levado pelo Vento",
			ru = "Обветренный хоэнвейс",
			ko = "바람결 장대꽃",
			cn = "啸风霍亨布墨花",
		},
	},
	[381214] = {
		readable = "Frigid Hochenblume",
		model = 4537051,
		text = {
			en = "Frigid Hochenblume",
			es = "Lumbreflor gélida",
			de = "Eisige Hochblume",
			fr = "Hochenblume algide",
			it = "Altofiore Gelato",
			pt = "Hochenblume Frígido",
			ru = "Ледяной хоэнвейс",
			ko = "혹한의 장대꽃",
			cn = "冷冽霍亨布墨花",
		},
	},
	[381957] = {
		readable = "Lush Bubble Poppy",
		model = 4498021,
		text = {
			en = "Lush Bubble Poppy",
			es = "Amapola burbuja exuberante",
			de = "Üppiger Blasenmohn",
			fr = "Pavot à bulle luxuriant",
			it = "Papavero Bolla Lussureggiante",
			pt = "Papoula Borbulhante Exuberante",
			ru = "Зрелый пузырчатый мак",
			ko = "무성한 거품 백일홍",
			cn = "繁茂的泡粟花",
		},
	},
	[381958] = {
		readable = "Lush Writhebark",
		model = 4546835,
		text = {
			en = "Lush Writhebark",
			es = "Pino retorcido exuberante",
			de = "Üppige Krümmrinde",
			fr = "Écorce tordue luxuriante",
			it = "Scorzatorta Lussureggiante",
			pt = "Casca Retorcida Exuberante",
			ru = "Зрелая витая кора",
			ko = "무성한 격통껍질",
			cn = "繁茂的歪扭树皮",
		},
	},
	[381959] = {
		readable = "Lush Saxifrage",
		model = 4558390,
		text = {
			en = "Lush Saxifrage",
			es = "Saxifraga exuberante",
			de = "Üppiges Steinbrich",
			fr = "Saxifrage luxuriante",
			it = "Sassifraga Lussureggiante",
			pt = "Quebra-pedra Exuberante",
			ru = "Зрелая камнеломка",
			ko = "무성한 다년초",
			cn = "繁茂的虎耳草",
		},
	},
	[381960] = {
		readable = "Lush Hochenblume",
		model = 4537107,
		text = {
			en = "Lush Hochenblume",
			es = "Lumbreflor exuberante",
			de = "Üppige Hochblume",
			fr = "Hochenblume luxuriante",
			it = "Altofiore Lussureggiante",
			pt = "Hochenblume Exuberante",
			ru = "Зрелый хоэнвейс",
			ko = "무성한 장대꽃",
			cn = "繁茂的霍亨布墨花",
		},
	},
	[390139] = {
		readable = "Lambent Hochenblume",
		model = 5091436,
		text = {
			en = "Lambent Hochenblume",
			es = "Lumbreflor luminiscente",
			de = "Flackernde Hochblume",
			fr = "Hochenblume diaprée",
			it = "Altofiore Tremolante",
			pt = "Hochenblume Bruxuleante",
			ru = "Сияющий хоэнвейс",
			ko = "희미한 장대꽃",
			cn = "柔光霍亨布墨花",
		},
	},
	[390140] = {
		readable = "Lambent Saxifrage",
		model = 5091440,
		text = {
			en = "Lambent Saxifrage",
			es = "Saxifraga luminiscente",
			de = "Flackerndes Steinbrich",
			fr = "Saxifrage diaprée",
			it = "Sassifraga Tremolante",
			pt = "Quebra-pedra Bruxuleante",
			ru = "Сияющая камнеломка",
			ko = "희미한 다년초",
			cn = "[Lambent Saxifrage]",
		},
	},
	[390141] = {
		readable = "Lambent Writhebark",
		model = 5091442,
		text = {
			en = "Lambent Writhebark",
			es = "Pino retorcido luminiscente",
			de = "Flackernde Krümmrinde",
			fr = "Écorce tordue diaprée",
			it = "Scorzatorta Tremolante",
			pt = "Casca Retorcida Bruxuleante",
			ru = "Сияющая витая кора",
			ko = "희미한 격통껍질",
			cn = "[Lambent Writhebark]",
		},
	},
	[390142] = {
		readable = "Lambent Bubble Poppy",
		model = 5091434,
		text = {
			en = "Lambent Bubble Poppy",
			es = "Amapola burbuja luminiscente",
			de = "Flackernder Blasenmohn",
			fr = "Pavot à bulle diapré",
			it = "Papavero Bolla Tremolante",
			pt = "Papoula Borbulhante Bruxuleante",
			ru = "Сияющий пузырчатый мак",
			ko = "[Lambent Bubble Poppy]",
			cn = "[Lambent Bubble Poppy]",
		},
	},
	[398751] = {
		readable = "Lush Bubble Poppy",
		model = 5091435,
		text = {
			en = "Lush Bubble Poppy",
			es = "Amapola burbuja exuberante",
			de = "Üppiger Blasenmohn",
			fr = "Pavot à bulle luxuriant",
			it = "Papavero Bolla Lussureggiante",
			pt = "Papoula Borbulhante Exuberante",
			ru = "Зрелый пузырчатый мак",
			ko = "무성한 거품 백일홍",
			cn = "[Lush Bubble Poppy]",
		},
	},
	[398752] = {
		readable = "Lush Writhebark",
		model = 5091443,
		text = {
			en = "Lush Writhebark",
			es = "Pino retorcido exuberante",
			de = "Üppige Krümmrinde",
			fr = "Écorce tordue luxuriante",
			it = "Scorzatorta Lussureggiante",
			pt = "Casca Retorcida Exuberante",
			ru = "Зрелая витая кора",
			ko = "무성한 격통껍질",
			cn = "[Lush Writhebark]",
		},
	},
	[398753] = {
		readable = "Lush Hochenblume",
		model = 5091439,
		text = {
			en = "Lush Hochenblume",
			es = "Lumbreflor exuberante",
			de = "Üppige Hochblume",
			fr = "Hochenblume luxuriante",
			it = "Altofiore Lussureggiante",
			pt = "Hochenblume Exuberante",
			ru = "Зрелый хоэнвейс",
			ko = "무성한 장대꽃",
			cn = "繁茂的霍亨布墨花",
		},
	},
	[398754] = {
		readable = "Lush Saxifrage",
		model = 5091441,
		text = {
			en = "Lush Saxifrage",
			es = "Saxifraga exuberante",
			de = "Üppiges Steinbrich",
			fr = "Saxifrage luxuriante",
			it = "Sassifraga Lussureggiante",
			pt = "Quebra-pedra Exuberante",
			ru = "Зрелая камнеломка",
			ko = "무성한 다년초",
			cn = "繁茂的虎耳草",
		},
	},
	[398755] = {
		readable = "Bubble Poppy",
		model = 5091434,
		text = {
			en = "Bubble Poppy",
			es = "Amapola burbuja",
			de = "Blasenmohn",
			fr = "Pavot à bulle",
			it = "Papavero Bolla",
			pt = "Papoula Borbulhante",
			ru = "Пузырчатый мак",
			ko = "거품 백일홍",
			cn = "泡粟花",
		},
	},
	[398756] = {
		readable = "Writhebark",
		model = 5091442,
		text = {
			en = "Writhebark",
			es = "Pino retorcido",
			de = "Krümmrinde",
			fr = "Écorce tordue",
			it = "Scorzatorta",
			pt = "Casca Retorcida",
			ru = "Витая кора",
			ko = "격통껍질",
			cn = "歪扭树皮",
		},
	},
	[398758] = {
		readable = "Saxifrage",
		model = 5091440,
		text = {
			en = "Saxifrage",
			es = "Saxifraga",
			de = "Steinbrich",
			fr = "Saxifrage",
			it = "Sassifraga",
			pt = "Quebra-pedra",
			ru = "Камнеломка",
			ko = "다년초",
			cn = "虎耳草",
		},
	},
	[398759] = {
		readable = "Titan-Touched Bubble Poppy",
		model = 5091434,
		text = {
			en = "Titan-Touched Bubble Poppy",
			es = "Amapola burbuja tocada por los titanes",
			de = "Titanenberührter Blasenmohn",
			fr = "Pavot à bulle touché par les Titans",
			it = "Papavero Bolla Toccato dai Titani",
			pt = "Papoula Borbulhante Tocada pelos Titãs",
			ru = "Осененный титанами пузырчатый мак",
			ko = "[Titan-Touched Bubble Poppy]",
			cn = "[Titan-Touched Bubble Poppy]",
		},
	},
	[398760] = {
		readable = "Titan-Touched Writhebark",
		model = 5091442,
		text = {
			en = "Titan-Touched Writhebark",
			es = "Pino retorcido tocado por los titanes",
			de = "Titanenberührte Krümmrinde",
			fr = "Écorce tordue touchée par les Titans",
			it = "Scorzatorta Toccata dai Titani",
			pt = "Casca Retorcida Tocada pelos Titãs",
			ru = "Осененная титанами витая кора",
			ko = "[Titan-Touched Writhebark]",
			cn = "[Titan-Touched Writhebark]",
		},
	},
	[398761] = {
		readable = "Titan-Touched Hochenblume",
		model = 5091436,
		text = {
			en = "Titan-Touched Hochenblume",
			es = "Lumbreflor tocada por los titanes",
			de = "Titanenberührte Hochblume",
			fr = "Hochenblume touchée par les Titans",
			it = "Altofiore Toccato dai Titani",
			pt = "Hochenblume Tocado pelos Titãs",
			ru = "Осененный титанами хоэнвейс",
			ko = "티탄에 물든 장대꽃",
			cn = "[Titan-Touched Hochenblume]",
		},
	},
	[398762] = {
		readable = "Titan-Touched Saxifrage",
		model = 5091440,
		text = {
			en = "Titan-Touched Saxifrage",
			es = "Saxifraga tocada por los titanes",
			de = "Titanenberührtes Steinbrich",
			fr = "Saxifrage touchée par les Titans",
			it = "[Titan-Touched Saxifrage]",
			pt = "Quebra-pedra Tocada pelos Titãs",
			ru = "Осененная титанами камнеломка",
			ko = "[Titan-Touched Saxifrage]",
			cn = "[Titan-Touched Saxifrage]",
		},
	},
	[398764] = {
		readable = "Infurious Bubble Poppy",
		model = 5091434,
		text = {
			en = "Infurious Bubble Poppy",
			es = "Amapola burbuja furiosa",
			de = "Wutentbrannter Blasenmohn",
			fr = "Pavot à bulle ardent",
			it = "[Infurious Bubble Poppy]",
			pt = "Papoula Borbulhante em Fúria",
			ru = "Ярый пузырчатый мак",
			ko = "[Infurious Bubble Poppy]",
			cn = "[Infurious Bubble Poppy]",
		},
	},
	[398765] = {
		readable = "Infurious Writhebark",
		model = 5091442,
		text = {
			en = "Infurious Writhebark",
			es = "Pino retorcido furioso",
			de = "Wutentbrannte Krümmrinde",
			fr = "Écorce tordue ardente",
			it = "[Infurious Writhebark]",
			pt = "Casca Retorcida em Fúria",
			ru = "Ярая витая кора",
			ko = "[Infurious Writhebark]",
			cn = "[Infurious Writhebark]",
		},
	},
	[398766] = {
		readable = "Infurious Hochenblume",
		model = 5091436,
		text = {
			en = "Infurious Hochenblume",
			es = "Lumbreflor furiosa",
			de = "Wutentbrannte Hochblume",
			fr = "Hochenblume ardente",
			it = "[Infurious Hochenblume]",
			pt = "Hochenblume em Fúria",
			ru = "Ярый хоэнвейс",
			ko = "[Infurious Hochenblume]",
			cn = "[Infurious Hochenblume]",
		},
	},
	[398767] = {
		readable = "Infurious Saxifrage",
		model = 5091440,
		text = {
			en = "Infurious Saxifrage",
			es = "Saxifraga furiosa",
			de = "Wutentbranntes Steinbrich",
			fr = "Saxifrage ardente",
			it = "[Infurious Saxifrage]",
			pt = "Quebra-pedra em Fúria",
			ru = "Ярая камнеломка",
			ko = "[Infurious Saxifrage]",
			cn = "[Infurious Saxifrage]",
		},
	},
});