--------------------------------------------------
--    A C H I E V E M E N T S    M O D U L E    --
--------------------------------------------------

-- Leave Empty, Parser fills
root(ROOTS.Achievements, achcat(ACHIEVEMENT_CATEGORY_WORLD_EVENTS, {
	achcat(ACHIEVEMENT_CATEGORY_LUNAR_FESTIVAL),
	achcat(ACHIEVEMENT_CATEGORY_LOVE_IS_IN_THE_AIR),
	achcat(ACHIEVEMENT_CATEGORY_NOBLEGARDEN),
	achcat(ACHIEVEMENT_CATEGORY_CHILDRENS_WEEK),
	achcat(ACHIEVEMENT_CATEGORY_MIDSUMMER),
	achcat(ACHIEVEMENT_CATEGORY_BREWFEST),
	achcat(ACHIEVEMENT_CATEGORY_HALLOWS_END),
	achcat(ACHIEVEMENT_CATEGORY_PILGRIMS_BOUNTY),
	achcat(ACHIEVEMENT_CATEGORY_WINTER_VEIL),
	achcat(ACHIEVEMENT_CATEGORY_DARKMOON_FAIRE),
	achcat(ACHIEVEMENT_CATEGORY_TIMEWALKING),
}));