-- This file is dynamically generated by Parser! DO NOT MODIFIY IT MANUALLY!
select(2, ...).FlightPathDB=
{
	["FlightPathMapIDs"] = {
		1209,
		1208,
		1467,
		1384,
		1923,
		1922,
		993,
		994,
		1011,
		1014,
		1504,
		1647,
		1409,
		2046,
		2057,
		2055,
		2149,
		2175,
		2241,
		2276
	},
}