"Parser.exe" config=".config/classic/01 - Classic Era.config"
"Parser.exe" config=".config/classic/01 - Classic SOD.config"
"Parser.exe" config=".config/classic/02 - TBC.config"
"Parser.exe" config=".config/classic/03 - Wrath.config"
"Parser.exe" config=".config/classic/04 - Cataclysm.config"