--------------------------------------------------
--    A C H I E V E M E N T S    M O D U L E    --
--------------------------------------------------
root(ROOTS.Achievements, achcat(ACHIEVEMENT_CATEGORY_EXPLORATION, {
	achcat(ACHIEVEMENT_CATEGORY_GENERAL),
	achcat(ACHIEVEMENT_CATEGORY_EASTERN_KINGDOMS_EXP),
	achcat(ACHIEVEMENT_CATEGORY_KALIMDOR_EXP),
	achcat(ACHIEVEMENT_CATEGORY_OUTLAND_EXP),
	achcat(ACHIEVEMENT_CATEGORY_NORTHREND_EXP),
	achcat(ACHIEVEMENT_CATEGORY_CATACLYSM_EXP),
	achcat(ACHIEVEMENT_CATEGORY_PANDARIA_EXP),
	achcat(ACHIEVEMENT_CATEGORY_DRAENOR_EXP),
	achcat(ACHIEVEMENT_CATEGORY_LEGION_EXP),
	achcat(ACHIEVEMENT_CATEGORY_BATTLE_FOR_AZEROTH_EXP),
	achcat(ACHIEVEMENT_CATEGORY_SHADOWLANDS_EXP, {["timeline"] = { ADDED_9_0_2 }}),
	achcat(ACHIEVEMENT_CATEGORY_DRAGONFLIGHT_EXP, {["timeline"] = TIMELINE_DF_REL }),
}));