--------------------------------------------------
--    A C H I E V E M E N T S    M O D U L E    --
--------------------------------------------------
-- Purely used for alignment of Achievement Categories to match the in-game Achievements UI. Maybe eventually will have an automated way to replace this file
root(ROOTS.Achievements, {
	achcat(ACHIEVEMENT_CATEGORY_CHARACTER),
	achcat(ACHIEVEMENT_CATEGORY_QUESTS, {
		achcat(ACHIEVEMENT_CATEGORY_EASTERN_KINGDOMS_QUESTS),
		achcat(ACHIEVEMENT_CATEGORY_KALIMDOR_QUESTS),
		achcat(ACHIEVEMENT_CATEGORY_OUTLAND_QUESTS),
		achcat(ACHIEVEMENT_CATEGORY_NORTHREND_QUESTS),
		achcat(ACHIEVEMENT_CATEGORY_CATACLYSM_QUESTS),
		achcat(ACHIEVEMENT_CATEGORY_PANDARIA_QUESTS),
		achcat(ACHIEVEMENT_CATEGORY_DRAENOR_QUESTS),
		achcat(ACHIEVEMENT_CATEGORY_LEGION_QUESTS),
		achcat(ACHIEVEMENT_CATEGORY_BATTLE_FOR_AZEROTH_QUESTS),
		achcat(ACHIEVEMENT_CATEGORY_SHADOWLANDS_QUESTS, {["timeline"] = { ADDED_9_0_2 }}),
		achcat(ACHIEVEMENT_CATEGORY_DRAGONFLIGHT_QUESTS, {["timeline"] = { ADDED_10_0_2_LAUNCH } }),
	}),
	achcat(ACHIEVEMENT_CATEGORY_EXPLORATION, {
		achcat(ACHIEVEMENT_CATEGORY_EASTERN_KINGDOMS_EXP),
		achcat(ACHIEVEMENT_CATEGORY_KALIMDOR_EXP),
		achcat(ACHIEVEMENT_CATEGORY_OUTLAND_EXP),
		achcat(ACHIEVEMENT_CATEGORY_NORTHREND_EXP),
		achcat(ACHIEVEMENT_CATEGORY_CATACLYSM_EXP),
		achcat(ACHIEVEMENT_CATEGORY_PANDARIA_EXP),
		achcat(ACHIEVEMENT_CATEGORY_DRAENOR_EXP),
		achcat(ACHIEVEMENT_CATEGORY_LEGION_EXP),
		achcat(ACHIEVEMENT_CATEGORY_BATTLE_FOR_AZEROTH_EXP),
		achcat(ACHIEVEMENT_CATEGORY_SHADOWLANDS_EXP, {["timeline"] = { ADDED_9_0_2 }}),
		achcat(ACHIEVEMENT_CATEGORY_DRAGONFLIGHT_EXP, {["timeline"] = { ADDED_10_0_2_LAUNCH } }),
	}),
	pvp(achcat(ACHIEVEMENT_CATEGORY_PVP, {
		-- TODO: sub-categories as they are cleaned
	})),
	achcat(ACHIEVEMENT_CATEGORY_DUNGEONS_AND_RAIDS, {
		achcat(ACHIEVEMENT_CATEGORY_CLASSIC_DR),
		achcat(ACHIEVEMENT_CATEGORY_THE_BURNING_CRUSADE_DR),
		achcat(ACHIEVEMENT_CATEGORY_LICH_KING_DUNGEON),
		achcat(ACHIEVEMENT_CATEGORY_LICH_KING_RAID),
		achcat(ACHIEVEMENT_CATEGORY_CATACLYSM_DUNGEON),
		achcat(ACHIEVEMENT_CATEGORY_CATACLYSM_RAID),
		achcat(ACHIEVEMENT_CATEGORY_PANDARIA_DUNGEON),
		achcat(ACHIEVEMENT_CATEGORY_PANDARIA_RAID),
		achcat(ACHIEVEMENT_CATEGORY_DRAENOR_DUNGEON),
		achcat(ACHIEVEMENT_CATEGORY_DRAENOR_RAID),
		achcat(ACHIEVEMENT_CATEGORY_LEGION_DUNGEON),
		achcat(ACHIEVEMENT_CATEGORY_LEGION_RAID),
		achcat(ACHIEVEMENT_CATEGORY_BATTLE_DUNGEON, {["timeline"] = { ADDED_8_0_1_LAUNCH }}),
		achcat(ACHIEVEMENT_CATEGORY_BATTLE_RAID, {["timeline"] = { ADDED_8_0_1_LAUNCH }}),
		achcat(ACHIEVEMENT_CATEGORY_SHADOWLANDS_DUNGEON, {["timeline"] = { ADDED_9_0_2 }}),
		achcat(ACHIEVEMENT_CATEGORY_SHADOWLANDS_RAID, {["timeline"] = { ADDED_9_0_2 }}),
		achcat(ACHIEVEMENT_CATEGORY_DRAGONFLIGHT_DUNGEON, {["timeline"] = { ADDED_10_0_2_LAUNCH } }),
		achcat(ACHIEVEMENT_CATEGORY_DRAGONFLIGHT_RAID, {["timeline"] = { ADDED_10_0_2_LAUNCH } }),
	}),
	achcat(ACHIEVEMENT_CATEGORY_PROFESSIONS, {
		-- TODO: sub-categories as they are cleaned
	}),
	achcat(ACHIEVEMENT_CATEGORY_REPUTATION, {
		achcat(ACHIEVEMENT_CATEGORY_CLASSIC_REP),
		achcat(ACHIEVEMENT_CATEGORY_THE_BURNING_CRUSADE_REP),
		achcat(ACHIEVEMENT_CATEGORY_WRATH_OF_THE_LICH_KING_REP),
		achcat(ACHIEVEMENT_CATEGORY_CATACLYSM_REP),
		achcat(ACHIEVEMENT_CATEGORY_PANDARIA_REP),
		achcat(ACHIEVEMENT_CATEGORY_DRAENOR_REP),
		achcat(ACHIEVEMENT_CATEGORY_LEGION_REP),
		achcat(ACHIEVEMENT_CATEGORY_BATTLE_FOR_AZEROTH_REP),
		achcat(ACHIEVEMENT_CATEGORY_SHADOWLANDS_REP),
		achcat(ACHIEVEMENT_CATEGORY_DRAGONFLIGHT_REP),
	}),
	achcat(ACHIEVEMENT_CATEGORY_WORLD_EVENTS, {
		achcat(ACHIEVEMENT_CATEGORY_LUNAR_FESTIVAL),
		achcat(ACHIEVEMENT_CATEGORY_LOVE_IS_IN_THE_AIR),
		achcat(ACHIEVEMENT_CATEGORY_NOBLEGARDEN),
		achcat(ACHIEVEMENT_CATEGORY_CHILDRENS_WEEK),
		achcat(ACHIEVEMENT_CATEGORY_MIDSUMMER),
		achcat(ACHIEVEMENT_CATEGORY_BREWFEST),
		achcat(ACHIEVEMENT_CATEGORY_HALLOWS_END),
		achcat(ACHIEVEMENT_CATEGORY_PILGRIMS_BOUNTY),
		achcat(ACHIEVEMENT_CATEGORY_WINTER_VEIL),
		achcat(ACHIEVEMENT_CATEGORY_DARKMOON_FAIRE),
		achcat(ACHIEVEMENT_CATEGORY_TIMEWALKING),
	}),
	achcat(ACHIEVEMENT_CATEGORY_PET_BATTLES, {
		-- TODO: sub-categories as they are cleaned
	}),
	achcat(ACHIEVEMENT_CATEGORY_COLLECTIONS, {
		-- TODO: sub-categories as they are cleaned
	}),
	achcat(ACHIEVEMENT_CATEGORY_EXPANSION_FEATURES, {
		achcat(ACHIEVEMENT_CATEGORY_ARGENT_TOURNAMENT),
		achcat(ACHIEVEMENT_CATEGORY_TOL_BARAD),
		achcat(ACHIEVEMENT_CATEGORY_PANDARIA_SCENARIOS),
		achcat(ACHIEVEMENT_CATEGORY_PROVING_GROUNDS),
		achcat(ACHIEVEMENT_CATEGORY_DRAENOR_GARRISON),
		achcat(ACHIEVEMENT_CATEGORY_LEGION_CLASS_HALL),
		achcat(ACHIEVEMENT_CATEGORY_ISLAND_EXPEDITIONS),
		achcat(ACHIEVEMENT_CATEGORY_WAR_EFFORT),
		achcat(ACHIEVEMENT_CATEGORY_HEART_OF_AZEROTH),
		achcat(ACHIEVEMENT_CATEGORY_VISIONS_OF_NZOTH),
		achcat(ACHIEVEMENT_CATEGORY_TORGHAST),
		achcat(ACHIEVEMENT_CATEGORY_COVENANT_SANCTUMS),
		achcat(ACHIEVEMENT_CATEGORY_DRAGON_RACING),
	}),
	achcat(ACHIEVEMENT_CATEGORY_FEATS_OF_STRENGTH, {
		-- TODO: sub-categories as they are cleaned
	}),
	achcat(ACHIEVEMENT_CATEGORY_LEGACY, {
		-- TODO: sub-categories as they are cleaned
	}),
});
