---------------------------------------------------
--          Z O N E S        M O D U L E         --
---------------------------------------------------
--_.Zones =
--{
--	m(572, {	-- Draenor	
--		m(543, {	-- Gorgrond
--			["groups"] = {
--				n(  -38, {	-- Profession
--					prof(356, { -- Fishing
	--					i(118380),		-- Hightfish Cap
--					}),
--				}),
	--		},
--		}),
--	}),
--};

-- Item would cause 16 entries even tho its not collectable