-- Build NYI
root(ROOTS.NeverImplemented, bubbleDown({["u"] = NEVER_IMPLEMENTED}, {
	tier(CLASSIC_TIER),
	tier(TBC_TIER),
	tier(WOTLK_TIER),
	tier(CATA_TIER),
	tier(MOP_TIER),
	tier(WOD_TIER),
	tier(LEGION_TIER),
	tier(BFA_TIER),
	tier(SL_TIER),
	tier(DF_TIER),
	n(ACHIEVEMENTS),
	n(ARMOR),
	filter(BAGS),
	filter(BATTLE_PETS),
	n(CLASS_TRIAL),
	n(FACTIONS),
	n(FLIGHT_PATHS),
	n(-101),	-- Followers
	filter(ILLUSIONS),
	filter(MISC),
	n(MAPS),
	filter(MOUNTS),
	n(PARTY_SYNC),
	n(PROFESSIONS, {
		prof(ALCHEMY),
		prof(BLACKSMITHING),
		prof(COOKING),
		prof(ENCHANTING),
		prof(ENGINEERING),
		prof(HERBALISM),
		prof(INSCRIPTION),
		prof(JEWELCRAFTING),
		prof(LEATHERWORKING),
		prof(MINING),
		prof(SKINNING),
		prof(TAILORING),
	}),
	n(QUESTS),
	filter(RECIPES),
	n(SETS),
	filter(TITLES),
	filter(TOYS),
	n(WEAPONS),
}));
root(ROOTS.HiddenAchievementTriggers, {
	tier(WOTLK_TIER),
	tier(CATA_TIER),
	tier(MOP_TIER),
	tier(WOD_TIER),
	tier(LEGION_TIER),
	tier(BFA_TIER),
	tier(SL_TIER),
	tier(DF_TIER),
});
root(ROOTS.HiddenQuestTriggers, {
	tier(CLASSIC_TIER),
	tier(TBC_TIER),
	tier(WOTLK_TIER),
	tier(CATA_TIER),
	tier(MOP_TIER),
	tier(WOD_TIER),
	tier(LEGION_TIER),
	tier(BFA_TIER),
	tier(SL_TIER),
	tier(DF_TIER),
});