WILD_POLYMORPH = createHeader({	-- Wild Polymorph
	readable = "SOD - Wild Polymorph",
	icon = "Interface\\ICONS\\Spell_Nature_Polymorph",
	text = {
		en = "Wild Polymorph",
		es = "Polimorfo Salvaje",
		de = "Wilder Polymorph",
		fr = "Polymorphe Sauvage",
		it = "Polimorfo Selvaggio",
		pt = "Polimorfo Selvagem",
		ru = "Дикий полиморф",
		ko = "야생 변이",
		cn = "野生多晶型物",
	},
	description = {
		en = "Cast Polymorph on critters afflicted by Wild Polymorph to turn them back into apprentices. Each one will give you a note. Collect 6 notes to learn the rune.",
		es = "Lanza Polymorph sobre criaturas afectadas por Wild Polymorph para convertirlas nuevamente en aprendices. Cada uno te dará una nota. Recoge 6 notas para aprender la runa.",
		de = "Wirke „Polymorph“ auf Lebewesen, die von „Wilder Polymorph“ betroffen sind, um sie wieder in Lehrlinge zu verwandeln. Jeder wird Ihnen eine Notiz geben. Sammle 6 Notizen, um die Rune zu lernen.",
		fr = "Lancez Polymorph sur les créatures affectées par Wild Polymorph pour les transformer en apprentis. Chacun vous donnera une note. Collectez 6 notes pour apprendre la rune.",
		it = "Lancia Polymorph sulle creature affette da Wild Polymorph per trasformarle di nuovo in apprendisti. Ognuno ti darà una nota. Raccogli 6 note per imparare la runa.",
		pt = "Lance Polymorph em criaturas afetadas por Wild Polymorph para transformá-las novamente em aprendizes. Cada um lhe dará uma nota. Colete 6 notas para aprender a runa.",
		ru = "Примените «Превращение» к существам, пораженным «Диким превращением», чтобы снова превратить их в учеников. Каждый даст вам записку. Соберите 6 нот, чтобы выучить руну.",
		ko = "야생 변이에 걸린 동물에게 변이를 시전하여 그들을 다시 견습생으로 되돌리세요. 각자가 당신에게 메모를 줄 것입니다. 노트 6개를 모아 룬을 배워보세요.",
		cn = "对受到野生变形术影响的小动物施放变形术，将它们变回学徒。每个人都会给你一张纸条。收集 6 个笔记来学习符文。",
	},
});