EVENTS = {
	-- Seasonal Holidays
	BREWFEST = 372,
	CHILDRENS_WEEK = 201,
	DARKMOON_FAIRE = 479,
	DAY_OF_THE_DEAD = 409,
	FEAST_OF_WINTER_VEIL = 141,
	HALLOWS_END = 324,
	HARVEST_FESTIVAL = 321,
	LOVE_IS_IN_THE_AIR = 423,
	LUNAR_FESTIVAL = 327,
	MIDSUMMER_FIRE_FESTIVAL = 341,
	NOBLEGARDEN = 181,
	PILGRIMS_BOUNTY = 404,
	PIRATES_DAY = 398,

	-- Weekly Events
	KALUAK_FISHING_DERBY = 424,	-- Obtained from Wrath Classic
	STRANGLETHORN_FISHING_EXTRAVAGANZA = 301,	-- Obtained from Wrath Classic

	-- Micro-Holidays
	CALL_OF_THE_SCARAB = 638,
	FREE_T_SHIRT_DAY = 1053,
	KALIMDOR_CUP = 1395,
	MARCH_OF_THE_TADPOLES = 647,
	SECRETS_OF_AZEROTH = 1396,
	THE_GREAT_GNOMEREGAN_RUN = 696,
	THOUSAND_BOAT_BASH = 642,
	TRIAL_OF_STYLE = 691,

	-- No event file exists for these yet. (and maybe they don't need to?)
	AUCTION_HOUSE_DANCE_PARTY = 692,
	FIREWORKS_CELEBRATION = 658,
	FIREWORKS_SPECTACULAR = 62,
	GLOWCAP_FESTIVAL = 648,
	HATCHING_OF_THE_HIPPOGYPHS = 634,
	KIRIN_TOR_TAVERN_CRAWL = 646,
	LUMINOUS_LUMINARIES = 1054,
	MOONKIN_FESTIVAL = 694,
	PET_BATTLE_BONUS_EVENT = 565,
	SPRING_BALLOON_FESTIVAL = 645,
	UNGORO_MADNESS = 644,
	VOLUNTEER_GUARD_DAY = 635,
	WANDERERS_FESTIVAL = 1052,
	WELCOME_TO_SANCTUARY = 1383,
	WORLD_QUEST_BONUS_EVENT = 592,

	-- Add PVP Brawls?
	-- TODO: Not wasting my time pasting this right now!

	-- Timewalking
	TIMEWALKING = 1271,	-- Generic, "any" timewalking event
	TIMEWALKING_OUTLAND_DUNGEON_EVENT = 559,
	TIMEWALKING_NORTHREND_DUNGEON_EVENT = 562,
	TIMEWALKING_CATACLYSM_DUNGEON_EVENT = 587,
	TIMEWALKING_MISTS_OF_PANDARIA_DUNGEON_EVENT = 643,
	TIMEWALKING_WARLORDS_OF_DRAENOR_DUNGEON_EVENT = 1056,
	TIMEWALKING_LEGION_DUNGEON_EVENT = 1263,	-- Alternative, possibly being 1271

	-- These aren't eventIDs, they're groups of eventIDs...
	WOW_ANNIVERSARY = 590,
};