-- #if ANYCLASSIC
-- Classic Phases
PHASE_ONE = 11;
PHASE_ONE_DIREMAUL = 1101;
PHASE_TWO = 12;
PHASE_THREE = 13;
PHASE_FOUR = 14;
PHASE_FIVE = 15;
PHASE_FIVE_TIER_ZERO_POINT_FIVE_SETS = PHASE_FIVE;
PHASE_FIVE_WAR_EFFORT = 1501;
PHASE_FIVE_GONG = 1502;
PHASE_FIVE_WAR = 1503;
PHASE_FIVE_CATCH_UP = 1504;
PHASE_SIX = 16;
PHASE_SIX_SCOURGE_INVASION = 1601;
PHASE_SIX_SILITHYST = 1602;
PHASE_SIX_CLASSICERA = 1603;
SOM_PHASE_ONE = 1604;
SOD_PHASE_ONE = 1605;
SOD_PHASE_TWO = 1606;
SOD_PHASE_THREE = 1607;
SOD_PHASE_FOUR = 1608;
-- #if SEASON_OF_DISCOVERY
PHASE_ONE_DIREMAUL = SOD_PHASE_FOUR;	-- Dire Maul actually came out with Phase 4 of SOD.
PHASE_FIVE_TIER_ZERO_POINT_FIVE_SETS = SOD_PHASE_FOUR;	-- T0.5 Sets actually came out with Phase 4 of SOD.
-- #endif
SOD_PHASE_FIVE = 1609;
SOD_PHASE_SIX = 1610;
SOD_PHASE_SEVEN = 1611;
SOD_PHASE_EIGHT = 1612;

-- TBC Classic Phases
TBC_PHASE_ONE = 17;
TBC_PHASE_ONE_DARKPORTAL = 1701;
TBC_PHASE_TWO = 18;
TBC_PHASE_TWO_OGRILA = 1801;
TBC_PHASE_TWO_SKYGUARD = 1802;
TBC_PHASE_TWO_SWIFTFLIGHTFORM = 18;	-- Subcategory not necessary.
TBC_PHASE_THREE = 19;
TBC_PHASE_THREE_NETHERWING = 1901;
TBC_PHASE_THREE_GLAIVEPRIO = 1902;
TBC_PHASE_FOUR = 20;
TBC_PHASE_FIVE = 21;
TBC_PHASE_FIVE_OFFENSIVE_PHASE_ONE = 21;	-- Note: Same as above, distinction isn't necessary, but it helps keep timeline data streamlined.
TBC_PHASE_FIVE_OFFENSIVE_PHASE_TWO = 2101;
TBC_PHASE_FIVE_OFFENSIVE_PHASE_TWO_B = 2102;
TBC_PHASE_FIVE_OFFENSIVE_PHASE_THREE = 2103;
TBC_PHASE_FIVE_OFFENSIVE_PHASE_THREE_B = 2104;
TBC_PHASE_FIVE_OFFENSIVE_PHASE_FOUR = 2105;
TBC_PHASE_FIVE_OFFENSIVE_PHASE_FOUR_B = 2106;
TBC_PHASE_FIVE_OFFENSIVE_PHASE_FOUR_C = 2107;

-- Wrath Classic Phases
WRATH_PHASE_ONE = 30;
WRATH_PHASE_ONE_REALM_FIRST = 3001;
WRATH_PHASE_TWO = 31;
WRATH_PHASE_TWO_HAMMERPRIO = 3101;
WRATH_PHASE_THREE = 32;
WRATH_PHASE_FOUR = 33;
WRATH_PHASE_FOUR_SHADOWMOURNE = 3301;
WRATH_PHASE_FOUR_RUBYSANCTUM = 3302;
WRATH_PHASE_FOUR_OPERATION_ZALAZANE = 3303;
WRATH_PHASE_FOUR_ELEMENTAL_INVASION = 3304;

-- NOTE: Reason for this is to show when stuff is going away eventually.
-- Cataclysm Classic Phases
CATA_PHASE_ONE = 40;
CATA_PHASE_TWO = 41;	-- ZA/ZG
CATA_PHASE_THREE = 42;	-- Firelands
CATA_PHASE_FOUR = 43;	-- Dragonsoul

-- Mists of Pandaria Classic Phases
MOP_PHASE_ONE = 50;
MOP_PHASE_TWO = 51;
MOP_PHASE_THREE = 52;

-- Warlords of Draenor Classic Phases
WOD_PHASE_ONE = 60;
WOD_PHASE_TWO = 61;
WOD_PHASE_THREE = 62;

-- Legion Classic Phases
LEGION_PHASE_ONE = 70;
LEGION_PHASE_TWO = 71;
LEGION_PHASE_THREE = 72;

-- Battle for Azeroth Phases
BFA_PHASE_ONE = 80;
BFA_PHASE_TWO = 81;
BFA_PHASE_THREE = 82;

-- Shadowlands Phases
SHADOWLANDS_PHASE_ONE = 90;
SHADOWLANDS_PHASE_TWO = 91;
SHADOWLANDS_PHASE_THREE = 92;

-- Dragonflight Phases
DF_PHASE_ONE = 100;
DF_PHASE_TWO = 101;
DF_PHASE_THREE = 102;

-- The War Within Phases
TWW_PHASE_ONE = 110;
TWW_PHASE_TWO = 111;
TWW_PHASE_THREE = 112;

-- Done defining Phases for Classic
-- #endif