-- D&R Tiers
CLASSIC_TIER = 1;
TBC_TIER = 2;
WOTLK_TIER = 3;
CATA_TIER = 4;
MOP_TIER = 5;
WOD_TIER = 6;
LEGION_TIER = 7;
BFA_TIER = 8;
SL_TIER = 9;
DF_TIER = 10;

-- #if AFTER DF
CURRENT_TIER = DF_TIER;
-- #elseif AFTER SHADOWLANDS
CURRENT_TIER = SL_TIER;
-- #elseif AFTER BFA
CURRENT_TIER = BFA_TIER;
-- #elseif AFTER LEGION
CURRENT_TIER = LEGION_TIER;
-- #elseif AFTER WOD
CURRENT_TIER = WOD_TIER;
-- #elseif AFTER CATA
CURRENT_TIER = CATA_TIER;
-- #elseif AFTER WRATH
CURRENT_TIER = WOTLK_TIER;
-- #elseif AFTER TBC
CURRENT_TIER = TBC_TIER;
-- #else
CURRENT_TIER = CLASSIC_TIER;
-- #endif