-- Unobtainable Filters
NEVER_IMPLEMENTED = 1;
REMOVED_FROM_GAME = 2;
-- #if ANYCLASSIC
BLACK_MARKET = 3;
BLIZZARD_BALANCE = 3;
TCG = 3;
-- #else
BLACK_MARKET = 9;
BLIZZARD_BALANCE = 35;
TCG = 10;
-- #endif
ELITE_PVP_REQUIREMENT = 4;
TRAINING = 15;